### ISSUE TITLE
How to hide purple insertion mark?

### ISSUE THREAD

**Issue by charliechen912ilovbash** [igvteam/igv#1000]
Please tell me how to hide the purple insertion mark in alignments.
I have tried `View > Preference > Alignments > "Hide indels < threshold"`
and `View > Preference > Alignments > "Label indels > threshold"`
with different threshold like: 1, 1000, 1000000
but nothing changed.
I am using version 2.9.3

**Comment by jrobinso** [comment]
If its 3rd generation data (e.g. pacbio). you need to hide it on the "Third
Gen" preferences tab.   On later versions this isn't necessary.

**Comment by charliechen912ilovbash** [comment]
I see. I am using Nanopore data. 
Thanks!
