### ISSUE TITLE
Sashimi plot on IGV-MacOS

### ISSUE THREAD

**Issue by nroak** [igvteam/igv#1001]
I'm trying to visualize Sashimi plot using standalone IGV on Mac OS. There are a ton of reads in the region. However, all the junction arcs are squeezed within a small window and there's a ton of white-space around it. Is there any setting that I can change for the IGV?

I checked with a colleague who doesn't have any issues on Windows standalone version.

### MAC
![Mac](https://user-images.githubusercontent.com/24547900/126000182-fd17661c-ab63-45cd-bfb2-bfab9e01dc9e.png)

### WINDOWS
![Windows](https://user-images.githubusercontent.com/24547900/126000189-8d9cef85-aa1b-4f3e-a1c0-c19812d2149b.jpg)

**Comment by helgathorv** [comment]
As this is not about igv.js, I transferred this issue to the repository for the IGV desktop application.
