### ISSUE TITLE
Save session to list absolute paths

### ISSUE THREAD

**Issue by sarahhp** [igvteam/igv#1002]
Would be nice if File->Save session... automatically listed the absolute path (no ../ in resource paths).  

This has been catching me out when I'm loading files from different parts of my filesystem.   IGV (v 2.10.2 on linux) is saving the "Resource path" with relative directories ( ../../) and then failing when I try to load the sessions.   Checking the xml files afterward I can see the absolute paths ARE listed in the track:id section but not in the Resource path :/.  This seems to be specific to the parent dir syntax (../) and not the child dirs.  Its not hard to fix  (I just manually change the relative (../) paths to absolute), but it would be nice if this were automatic :)

Thanks!!

**Comment by jrobinso** [comment]
This should be controllable from user preferences (View > Preferences),
first checkbox.   However it should not be failing.   Are you moving the
files (data or session) after saving the session file?   I don't see any
scenario where this should fail.

**Comment by jrobinso** [comment]
Closing for lack of response

**Comment by sarahhp** [comment]
This is correct, View->Preferences has a tick box for this.  Thanks for your reply, very helpful :)
