### ISSUE TITLE
Read details missing in paired-end mode

### ISSUE THREAD

**Issue by marc-sturm** [igvteam/igv#1003]
Hi,

I noticed that IGV 2.10.2 on Windows 10 does not show read details when "show as pairs" is on:
![grafik](https://user-images.githubusercontent.com/5638144/126280820-f4cf4829-1296-45fc-a2a6-d8e2659a5546.png)

If "show as pairs" is off, details are shown:
![grafik](https://user-images.githubusercontent.com/5638144/126281011-01630006-57a5-429c-aa24-cb61daab91f3.png)

Best,
  Marc

**Comment by helgathorv** [comment]
@marc-sturm Thanks for letting us know. I've verified that this is also a problem on other platforms and crept into IGV in the 2.10.0 release. Until we've fixed this, you can install an earlier release from [here](https://data.broadinstitute.org/igv/projects/downloads/2.9/).

**Comment by jrobinso** [comment]
The fix for this is released in 2.10.3
