### ISSUE TITLE
Save session via port command

### ISSUE THREAD

**Issue by Firestar93** [igvteam/igv#1010]
Hello, I want to save a whole session via a port command (through java code). Is this somehow possible? Thank you for your help :)!
If this option is not available, could you please implement it :)?

**Comment by jrobinso** [comment]
This has been added and will be included in the next release, 2.11.1, which will go out later today.

**Comment by jrobinso** [comment]
The command will be 

saveSession <full path to file>

A full path is not neccessary, but without it the session is saved relative to the IGV working directory.    This in turn is platform dependent and hard to predict.
