### ISSUE TITLE
Make the size of the splice junction tracks proportionate to counts > 50

### ISSUE THREAD

**Issue by hbeale** [igvteam/igv#1015]
Currently the height of the arc and its thickness are proportional to the depth of read coverage up to 50 reads. I would like to be able to change 50 to an arbitrary number. Currently I have one arc representing 813 reads and another representing 62 reads, and they look the same. 

![image](https://user-images.githubusercontent.com/54659/128905197-ee1f4626-459b-4d0c-8ea5-c94c93d83755.png)

Tagging @maximilianh who suggested I submit this request.

**Comment by zukailiu** [comment]
Hi hbeale,

Did you solve this problem at the end? I came across exactly the same issue with you. 

Thanks,
Zukai

**Comment by jrobinso** [comment]
I'll look into this for the next point release.

**Comment by jrobinso** [comment]
@hbeale @zukailiu Did either of you try setting the track to "Autoscale"?   That works for me, although there is a refresh problem (autoscale doesn't take effect until a repaint is forced, e.g. by dragging).

**Comment by jrobinso** [comment]
I'll add a menu item to set an explicit value, that should be there in any event, but autoscale works in the meantime.

**Comment by hbeale** [comment]
Autoscale does not change the phenomenon for me using either version 2.4.5
or 2.14.1, even if I drag the tracks a bit to force a refresh.

**Comment by jrobinso** [comment]
@hbeale I might need a test set to reproduce that, it works for me with all my test datasets.   For example, load the attached (after unzipping as a session) and select "Autoscale" for the Liver track, then drag to force refresh.  
[rnaSeq.xml.zip](https://github.com/igvteam/igv/files/9854364/rnaSeq.xml.zip)

**Comment by zukailiu** [comment]
@jrobinso I tried the 'autoscale' on my IGV 2.12.3 and it worked!! Thank you so much!

**Comment by hbeale** [comment]
Interesting! I get similar results with your test data as I do with my data. It looks like the data is scaled even above 50 reads within a track (or what do you call it, probably not a track, but the distinct rows within a track that appear when you set the junction track to "expanded"), but not across "tracks". 

Here's before
![before autoscale](https://user-images.githubusercontent.com/54659/197608183-40379455-ae5f-490f-ae00-88260e4a43c9.jpg)

Here's after:
![Untitled 3](https://user-images.githubusercontent.com/54659/197608911-77416475-8403-4062-b0d8-3331cac96b18.jpg)

After, in the top "track", the middle-ish junction representing 1495 reads is now taller than one to the left in the same horizontal line with 693 reads, but both junction arcs are smaller than the one representing 40 reads in the "track" below it.

**Comment by jrobinso** [comment]
OK, I will look into that,  I had not looked at "expanded" mode.   The rows are just rows, tracks in this case would be liver and heart.

**Comment by jrobinso** [comment]
Yes I see what's happening, its autoscaling each row, which of course is not what we want.

**Comment by jrobinso** [comment]
This is released in 2.15.1
