### ISSUE TITLE
"RNA junction track" and "expand feature track" option

### ISSUE THREAD

**Issue by axelgschwind** [igvteam/igv#1018]
Hello,

I think there is a small bug in IGV. When I load a BAM file with RNA data into IGV and when at the same time both the options Preferences->RNA->Show junction track and Preferences->Tracks->Expand feature tracks are checked, IGV will freeze when I zoom to see some alignments.

I have to disable the option "Expand feature tracks" in the preferences to make it work again. In contrast, if i choose "Expanded" via right click onto the junction tracks, everything works fine.

I use IGV 2.10.3.

Best,
Axel

**Comment by jrobinso** [comment]
Thanks for the report.  I just pushed a fix for this, which will be in the next release.  

While investigating I noticed that using the preference actually sets the tracks to "squished" mode,  which is a space efficient expansion but not "expanded".    I can imagine this is confusing but its been that way for a long time and I am hesitant to change it.   Just be aware that using that preference is equivalent to selecting "Squished" for the mode.
