### ISSUE TITLE
BAM index files without content

### ISSUE THREAD

**Issue by cihanerkut** [igvteam/igv#1021]
I tried to copy BAM files and their index files from our workstation to my computer (macOS) to visualise them in IGV 2.11.0. I don't know what happened but the index files were copied without content. That means, the files were there but their size was 0 B. When I opened the BAM file in IGV, I could see that the coverage track had bars, until the point I zoomed in enough to visualise individual reads. Then the coverage track gets the scale 0 - 10 and coverage bars are gone. I also didn't see any alignments. I checked the BAM file and the alignments were indeed there. Then I realised that the index files were empty, so I copied them properly this time. The problem was gone.

I think this bug can be fixed easily if IGV checks whether the index file has the proper format, and complains when it's corrupted, etc.

**Comment by jrobinso** [comment]
I don't understand what you mean by "the coverage track had bars".   That doesn't seem possible.   Could you provide a screenshot?

**Comment by cihanerkut** [comment]
I can't reproduce the coverage track thingy now but I reproduced the original problem, that is alignments are invisible when the BAI file is empty. Please check the screenshot, two copies of the same BAM file on different folders are loaded. On one folder there's an empty BAI file (upper panels) and on the other folder there's the correct BAI file (lower).

<img width="1267" alt="Screenshot 2021-09-01 at 13 28 17" src="https://user-images.githubusercontent.com/10242823/131664185-bc288cd2-c1e4-4973-8da9-20e3ea11c40f.png">

**Comment by jrobinso** [comment]
Well certainly you are going to get unpredictable behavior with a corrupt index file.   I will see if anything can be done about validation and an error message, but as the BAM file is read by the htsjdk library it would have to caught there.

**Comment by cihanerkut** [comment]
Sound great, thank you!

**Comment by jrobinso** [comment]
Unfortunately the htsjdk does not throw a specific error, so nothing can really be determined about the validity of the index.  but we can raise a generic error message.
