### ISSUE TITLE
 flipAxis="true"  dosenot work 

### ISSUE THREAD

**Issue by yancychy** [igvteam/igv#1023]
Hi,
    I want to flip bigwig signals by make the positive singals show down and negative signals show up. It is a very speical application when comparing the PCA signals.
    I tired the flipAxis="false" in XML which produced by "tracktables" package in R. But when setting the flipAxis="true", the IGV did not change. Thanks.

Best regards,
Yang

**Comment by jrobinso** [comment]
I had to investigate "flipAxis" as I didn't recognize it.   It looks like it might have been an option in earlier versions of IGV, but is no longer.    Sorry I don't know when or why it was added, or when it was removed.   

I don't know anything about "tracktables", or what version of IGV it was developed for.
