### ISSUE TITLE
release notes for 2.11 are access denied!

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#1025]
Oh goodie a new release!

Ouch:

http://software.broadinstitute.org/software/igv/2.11.x#LatestVersion   shows “Access Denied”

**Comment by helgathorv** [comment]
Oops! Will fix that. Thanks for letting us know.

**Comment by malcook** [comment]
thanks... 

also - related - though the release is announced in http://software.broadinstitute.org/software/igv/download it is also not listed in http://software.broadinstitute.org/software/igv/ReleaseNotes

**Comment by helgathorv** [comment]
Fixed.
