### ISSUE TITLE
Show sequencing errors

### ISSUE THREAD

**Issue by lbal-biomat** [igvteam/igv#1030]
Hello,
I can't seem to find an option to see all mismatches, I only see polymorphisms but I don't see random mismatches. Is there any way to see them?

Thanks

**Comment by jrobinso** [comment]
See them where? Is this 3rd gen data?   All mismatches between read base and reference are highlighted in the alignments by  default, except for 3rd gene (pacbio, ont).   If you want to see all mismatches for 3rd gene uncheck "Quick consensus mode" in the 3rd gen preferences panel (View > Preferences).

**Comment by lbal-biomat** [comment]
Thanks @jrobinso, that was exactly what I needed. I'm working with nanopore reads.
I closing this issue.
Kind regards

**Comment by lbal-biomat** [comment]
Thanks @jrobinso, that was exactly what I needed. I'm working with nanopore reads.
I closing this issue.
Kind regards
