### ISSUE TITLE
I unable to open vcf file in igv

### ISSUE THREAD

**Issue by fernandabf** [igvteam/igv#1031]
Hi, 
I'm trying to open a vcf file in igv, but I get a message with the following error:
![image](https://user-images.githubusercontent.com/90794752/133488833-8d9b2afe-34c3-4f10-bd41-481449bde87d.png)
 I already created the idx file using the "run igv toots" as you can see in the directory:
![image](https://user-images.githubusercontent.com/90794752/133489073-d3d5f61f-d768-425c-9226-74513ec160e2.png)

What I have to do?

thanks in advance!

**Comment by jrobinso** [comment]
I suggest you delet the index (".idx") file.   That vcf is small enough to not need it.  If IGV prompts you to create an index decline.

If you do need to index a larger vcf file I suggest you do it offline with "bgzip" and "tabix", a web search should yield information on using those tools.

**Comment by fernandabf** [comment]
Thanks a lot jrobinson!

**Comment by jrobinso** [comment]
I'm assuming that worked for you, reopen if not.
