### ISSUE TITLE
IGV web app: sequence is showing up on .bam tracks (alignments and coverage) and not above the tracks

### ISSUE THREAD

**Issue by erikamag** [igvteam/igv#1035]
Hello IGV-help,

I have loaded my genome and bam files using the igv-webapp-1.4.1 with Amazon s3. The sequence track is not showing up below my loaded genome or above my loaded tracks, but sequence is showing up on my loaded .bam files (both on the alignments and the coverage track). I cannot change the color of the tracks loaded because the sequence track is showing up on the reads even though these are not SNPs. How can I change this default? I would like my coverage track to be one color.

![Screen Shot 2021-09-22 at 12 05 26 PM](https://user-images.githubusercontent.com/39595594/134399016-65a7880d-260e-4614-bdb5-66fa45f1559a.png)
![Screen Shot 2021-09-22 at 12 05 51 PM](https://user-images.githubusercontent.com/39595594/134399022-e51f1d7d-6358-48a6-97fb-1fb7f90cb381.png)

**Comment by jrobinso** [comment]
That is not the sequence track, those are your alignment read bases.  What you are observing can happen if http request to fetch reference sequence fails,  or if the alignments are not aligned to the reference sequence you are using.    Its not possible to determine which problem you are having from the screenshots, but if you look in your "javascript console" for errors there might be hints.    If you need instructions on how to view the console let us know the platform (windows, mac) and browser you are using, it differs for all of them.

**Comment by erikamag** [comment]
We can close this issue, I changed the chromosome names in my reference.fasta file to match my .bam file and needed to recreate the .fasta index file. All is well and it is working

**Comment by helgathorv** [comment]
@erikamag  Good to hear. Thanks for letting us know.

**Comment by realmungmung** [comment]
Hi I encountered the same problem, could you please let me know how did you solve it? Thanks so much!
<img width="558" alt="Screenshot 2024-03-11 at 12 20 11 PM" src="https://github.com/igvteam/igv/assets/157068422/b52bc8f0-2d36-4914-95fc-1c3d7b1e6f7b">

**Comment by jrobinso** [comment]
@realmungmung Could you describe your problem?

**Comment by helgathorv** [comment]
The most likely cause of the colorful coverage tracks is that the reference genome currently loaded into IGV is not the same one as was used for the alignment of the reads. They need to match.

**Comment by realmungmung** [comment]
> The most likely cause of the colorful coverage tracks is that the reference genome currently loaded into IGV is not the same one as was used for the alignment of the reads. They need to match.

Yes! Thanks so much! I fixed it by changing the reference genome!
