### ISSUE TITLE
Blank yellow screen on Linux VM

### ISSUE THREAD

**Issue by hpcchris** [igvteam/igv#1036]
I downloaded and installed per the instructions and the gradle test ran with no errors. Running on a Ubuntu 20.04 desktop IGV starts with a blank yellow screen. The precompiled Linux packages, both with and without Java, do the same thing. I've tried CentOS and Fedora VMs as well and all show the same. My virtual environment typically runs with this display hardware:

```
# lshw -C display
  *-display
       description: VGA compatible controller
       product: GD 5446
       vendor: Cirrus Logic
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 00
       width: 32 bits
       clock: 33MHz
       capabilities: vga_controller rom
       configuration: driver=cirrus latency=0
       resources: irq:0 memory:fc000000-fdffffff memory:febd0000-febd0fff memory:c0000-dffff
```

I tried setting LIBGL_SOFTWARE_ALWAYS=true env variable but to no effect. I never see any errors in the shell when I run the app, and I can see the mouse and hints of invisible menus and dialogs reacting to the cursor movements.

**Comment by davideby** [comment]
Do either of these look similar to your issue?
https://github.com/adoptium/adoptium-support/issues/187
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/664

You mention VMs and "virtual environment" which suggests a display-forwarding type of configuration.  It looks like Java/Swing may have some issues with that kind of arrangement.  If those reports look similar to yours then maybe their workaround of setting `-Dsun.java2d.xrender=false` would help, though it's also possible it would have other side-effects on IGV.  It's not a configuration we test - or support in general - so we can't really say any more about it than that.

You can set this property in the `~/.igv/java_arguments` file (in the user's home directory) on the VM where IGV is installed.  Just restart IGV after that.  Let us know how that works for you.

If this doesn't match your issue then we might need some more info, particularly how you are "virtually" accessing the display of the Linux VM.  Even then I'm not sure we'll be able to help.  Generally IGV would be installed on the _client_ and access the files remotely.

- David

**Comment by hpcchris** [comment]
Thanks, those issues look just like what I ran into.

So far, adding -Dsun.java2d.xrender=false has made it work fine- thanks! I’ll do some more testing. I’m accessing this VM using HTML5 NoVNC on an OpenNebula cloud platform, but I can’t tell you much more that that. I haven’t tried other VNCs or Apache Guacamole or other things.

Chris

**Comment by davideby** [comment]
OK, sounds good @hpcchris .  Good luck with this and thanks for letting us know.
