### ISSUE TITLE
Can not create separate features

### ISSUE THREAD

**Issue by biomedswe** [igvteam/igv#1037]
Hi!

I'm following the tutorial "IGV | Data Navigation Basics (V2)" on you youtube page. 

When I try to write three genenames like it's is done in the tutorial I dont get two separate panels:

![image](https://user-images.githubusercontent.com/64096349/135442900-ab20a982-3176-4328-8002-02f1e13c0f1a.png)

It doesn't matter what genes i type. Then all panels become blank and I have to restart IGV to get the data back.

![image](https://user-images.githubusercontent.com/64096349/135443115-3757ba20-c958-4d5d-a32c-41fc15c78492.png)

What is wrong here?

**Comment by helgathorv** [comment]
There appears to be a bug with the multi-gene lookup in the when the human genome hg19 is loaded. We will look into this as soon as possible, but in the meantime that same tutorial will work if you select the human genome hg18. 
Thanks for letting us know.

**Comment by biomedswe** [comment]
> The problem here is PRRC2C does not exist in the hg19 annotations. Try EGFR MYC

It doesn't matter what I type, I have also tried genes that I saw was there. According to @helgathorv it appears to be an actual bug.

**Comment by biomedswe** [comment]
> There appears to be a bug with the multi-gene lookup in the when the human genome hg19 is loaded. We will look into this as soon as possible, but in the meantime that same tutorial will work if you select the human genome hg18. Thanks for letting us know.

no problem! and thank you:)

**Comment by helgathorv** [comment]
Released in IGV 2.11.2
