### ISSUE TITLE
.gwas file can not be read by IGV

### ISSUE THREAD

**Issue by avkermanov** [igvteam/igv#1048]
Hi,
IGV can not load the track from .gwas file. File first 10 lines: 

```
CHR	BP	SNP	P
NC_004354.4	52208	snp1	0.1615466
NC_004354.4	52313	snp2	0.108709
NC_004354.4	52394	snp3	0.8986483
NC_004354.4	52400	snp4	0.2270447
NC_004354.4	52411	snp5	0.0003543941
NC_004354.4	52470	snp6	0.003077863
NC_004354.4	52473	snp7	0.8626491
NC_004354.4	52602	snp8	0.4763675
NC_004354.4	52637	snp9	0.6984265
```

Genome is from D.melanogaster (NCBI Genome version) 

Thank you for you help!

**Comment by jrobinso** [comment]
@avkermanov yes that is a bug.  I've pushed a fix, and it will be released this week.  If you need it in the meantime you can build from source, or use the development build. https://software.broadinstitute.org/software/igv/download_snapshot
