### ISSUE TITLE
Requirements of igv in bioconda channel

### ISSUE THREAD

**Issue by YuanfengZhang** [igvteam/igv#1049]
`conda install igv -c bioconda`
it shows that openjdk8.0 is needed.
`openjdk            pkgs/main/linux-64::openjdk-8.0.152-h7b6447c_3`

Since there have been many newer JDK versions for a long time, why not altering this requirement to JDK11 or JDK17 for better performance?
IGV works well along with them.

And, the openjdk-8.0 is not compatible with cmdline igvtools.（“error：Could not create the Java Virtual Machine”）
![image](https://user-images.githubusercontent.com/71358306/139821459-29814f80-d576-40d0-bc07-ea4936c8ac60.png)

Is there a chance to update requirements of igv in bioconda channel? 35793 total downloads imply that it may influence many people.
![image](https://user-images.githubusercontent.com/71358306/139822049-266b0234-5c08-447a-9e3e-281d06e918ab.png)

**Comment by helgathorv** [comment]
Hi - we don't manage IGV in Bioconda.

With that said, when I try to install IGV on my Mac via
`% conda install igv -c bioconda`

I get the following:
```
The following NEW packages will be INSTALLED:
  igv                bioconda/noarch::igv-2.11.2-hdfd78af_0
  openjdk            pkgs/main/osx-64::openjdk-11.0.6-h7bc2e8c_1
```
In other words, it will install IGV 2.11.2, which is our latest version of IGV, and openjdk 11, which is also what we currently use.
But if you are having problems with Bioconda, please contact them directly.

**Comment by YuanfengZhang** [comment]
> Hi - we don't manage IGV in Bioconda.
> 
> With that said, when I try to install IGV on my Mac via `% conda install igv -c bioconda`
> 
> I get the following:
> 
> ```
> The following NEW packages will be INSTALLED:
>   igv                bioconda/noarch::igv-2.11.2-hdfd78af_0
>   openjdk            pkgs/main/osx-64::openjdk-11.0.6-h7bc2e8c_1
> ```
> 
> In other words, it will install IGV 2.11.2, which is our latest version of IGV, and openjdk 11, which is also what we currently use. But if you are having problems with Bioconda, please contact them directly.

THX. Got it.
