### ISSUE TITLE
No dialog box for "unload current session before loading new tracks" since IGV version 2.10.x

### ISSUE THREAD

**Issue by littlebzh** [igvteam/igv#1050]
Hello

I have a problem since version 2.10.x and 2.11.x

I'm loading files in IGV from html links with merge=false arguments (as decribed here https://software.broadinstitute.org/software/igv/ControlIGV)

With previous versions (still working with 2.9.x versions), with "merge=false" argument in html link, IGV was displaying a dialog box to ask if we want to load or unload current session (cf captured image below)

![image](https://user-images.githubusercontent.com/2368728/140036864-7b4fe446-39df-498b-9bde-c7fc424777c7.png)

It was very useful to decide on the way what we want to display in IGV : a clean new session or a session with cumulative tracks.  

Except if I have a wrong configuration on my side (I tested with a brand new config file), I do no not have this dialog box anymore. "merge=false" argument cleans everytime the session (like html link without  merge argument) in the last IGV release.
"merge=true" has the expected behavior and merge tracks without asking.

Is this feature is removed in the current version ?
I did not read anything about this fact in the release notes and I can not find any issue about it in github.
I hope you can help me to retrieve this fonctionality

Anyway, thank you for your continuous work on this very useful software 

Regards

**Comment by jrobinso** [comment]
This was removed after many requests to do so, I will update the release notes to reflect that.

**Comment by littlebzh** [comment]
Thank for your answer.
Too bad, it was useful for us to have a contextual choice to merge or not.
I suppose there is no workaround except create 2 kinds of links ?

**Comment by jrobinso** [comment]
Well, one suggestion is to ask your user what they want to do from your website and dynamically create the appropriate link.    BTW most of our web integration work is now focused on the web version of IGV.

**Comment by littlebzh** [comment]
Yes, it can be an solution.
I understand and I use the web version in some projects too but sometime we still need the stand alone version.
Thank you for your help.
