### ISSUE TITLE
default gene track download

### ISSUE THREAD

**Issue by josephhalstead** [igvteam/igv#1051]
Hi - Is it possible to download the default Gene track? I am looking to create a custom .genome file with same track, but which points to a local fasta rather than remote in order to speed up CRAM file loading when internet is slow

Thanks,

Joseph

**Comment by jrobinso** [comment]
For what assembly?  Most are available from UCSC in the genome downloads
area,  look for "refGene.txt.gz".

**Comment by josephhalstead** [comment]
thankyou - I was being blind

**Comment by maximilianh** [comment]
Note that UCSC somewhat discourages using the refGene track which is UCSC‘s
own BLAT alignment of RefSeq transcripts. These days NCBI provides the
official alignment and their data is available in the file
ncbiRefSeq.txt.gz from UCSC (same file format, I believe). The two differ
for transcripts that have major differences from the genome and they differ
for big transcript  families with very similar sequences.

**Comment by jrobinso** [comment]
You're absolutely correct,  my mistake.  Please use "ncbiRefSeq.txt.gz".   IGV recognizes that filename as "special" and parses it accordingly, so please don't rename.

Thanks for catching that @maximilianh
