### ISSUE TITLE
~ in session file paths

### ISSUE THREAD

**Issue by gevro** [igvteam/igv#1056]
Hi, Can you add support for using '~' in session file paths? Useful when using a session file on two different computers with different root directory structure but same structure under a home folder.

**Comment by jrobinso** [comment]
I'm not sure this is possible but I'll try.  ~ is not recognized on Windows, which is the majority of our users.    On Linux and Mac I would expect Java to resolve it correctly, I assume you have tried this and it doesn't.   So whatever I do will be a hack, not guaranteed to work in all cases.
