### ISSUE TITLE
bam file issue

### ISSUE THREAD

**Issue by HANIVANI** [igvteam/igv#1059]
Hello, IGV
I'm first to Github today. So pleased to meet you.

Anyway, i have one problem regarding loading bam files in IGV.
I have the bam files of BRCA1 with GRCh38/hg38 ver, but when I loaded it, IGV says my file "does not contain any sequence names which match the current genome."
![error](https://user-images.githubusercontent.com/95030093/143439673-158d2374-dfb4-4b75-b164-021539033ae9.PNG)

I struggled with loading it for about 2 weeks. If you give me any advise, i would really thank you.

**Comment by jrobinso** [comment]
The message means the sequence names in your bam file do not match the names of the reference you are trying to view it against.   Its printing an example of the sequence names in your file and the reference ("Genome:").

**Comment by jrobinso** [comment]
Based on that sequence name ("hg38_knownGene_...") I would guess your reads were aligned to a fasta file of gene sequences, not the hg38 dna reference sequence.

**Comment by HANIVANI** [comment]
I got it. thanks.
Then should i get fasta file of gene to view my bam file?
I got the message that the my reads' reference ID is hg38 of BRCA1. 
Is there other way to view my bam file with the reference sequence in IGV?

**Comment by jrobinso** [comment]
You need the fasta file the reads were aligned to.
