### ISSUE TITLE
Right click alignment menu not appearing on Linux snapshot version

### ISSUE THREAD

**Issue by gtollefson** [igvteam/igv#1061]
Hi,

I've run the Linux IGV Snapshot igv.sh bash script to launch IGV on a remote Linux system using both X-Forwarding to view the IGV window also a VNC to view the window. When I zoom into my region of interest (a single gene) and right click on the alignment track, no menu appears. I am trying to launch the Sashimi Plot tool. 

Does the current Linux snapshot IGV version support the right click menu on the alignment track? Can you help me to troubleshoot?

Thank you,
George

**Comment by jrobinso** [comment]
I can't help you troubleshoot x-forwarding or VNC,  but does this happen with the released Linux version?

**Comment by gtollefson** [comment]
@jrobinso I understand! Unfortunately I don't have access to a Linux system and am not able to set up a Linux env on my personal computer at the moment. I did install the current Mac version and am able to generate the Sashimi plots. It may well be an issue specific to right clicking using x-forwarding or VNC on our shared computing system. Thank you for your response!

**Comment by jrobinso** [comment]
Its also possible that the context menu is mapped to something other than right-click, for example on single button Mac OS its mapped to ctrl-click
