### ISSUE TITLE
Offline locus search with gene name is not working when offline tribble index is present with the transcript definition file. 

### ISSUE THREAD

**Issue by gokalpcelik** [igvteam/igv#1063]
Hi 

I have experienced a regression in locus search function where typing a gene name brings the locus immediately. This function works offline perfectly with old style genomes however with the new .json style genomes it stopped working when there is no internet connection. Internet connection may be a standard commodity for many places however when we work outside it becomes absolutely necessary. 

I noticed that the problem can be fixed by removing the tribble index file from the json genome definition file. Once you remove the tribble index and define an offline file in the json locus search function is back. Conversely, If you place offline tribble index along with the original file search function does not work again. 
Regards.

**Comment by jrobinso** [comment]
That's not a regression or bug, it is by design.   Tribble indexed annotation files are not searchable, obviously, as they aren't loaded in full.  You have discovered a "workaround", which is in effect to load the entire feature file which in turn makes its features searchable.

**Comment by jrobinso** [comment]
I'll leave this open for now as something to document.
