### ISSUE TITLE
Lost Blat tracks

### ISSUE THREAD

**Issue by rassgatibala** [igvteam/igv#1065]
Hi. 

I installed IGV_Linux_2.11.4 IGV this week and i'm gradually getting it to work for me. Prior to this I have no experience with it.

For Blat i've implemented a script that talks directly to a local gfServer service and converts the psl to json. I added the path to this script as value for "Blat URL" in the Advanced tab in the client. This works fine, the hits are displayed in a table in a popup dialog and on selection can be viewed in the console application.

When i restart and reopen the session after saving it, only the track names appear.
Looking at the saved session xml file, i see that the Blat tracks have been saved and their sequence saved as the "id" tag value.
The "sequence" tag value however is empty ("").

Once i modified the xml "sequence" tag value to hold the sequence, the Blat hits show in the IGV console.

So looking at the saved session xml, there's the "id" field, the "name" field and the "sequence". 
From editing the file, it seems the "name" holds the value being displayed in the Track display in the IGV console left pane. I'm not sure if this is by design ? but this stays the same for all Blat tracks. 

The "sequence" field is always empty but the "id" field contains the user sequence. I guess this is the reason behind the "empty" Blat tracks, since the "sequence" field value is presumably used in a re-Blat once a session is opened.

When I use the Blat feature, the dialog prompts to input a single line for the sequence. If I prefix the sequence with some text (like in a fasta header), it does not show up in the viewer nor in the xml file. So the script i mentioned at the start, creates a fasta file WITH a header which is submitted to a Blat server through gfClient and this header will show up as a tooltip when I select the Blat hit in IGV.

It would be useful to know the purpose of the 3 fields in the xml file. Was the "name" field supposed to be constant or was it perhaps meant hold a user-defined name for the sequence ? 

Thank you,
Sverrir

**Comment by jrobinso** [comment]
This is fixed for the next release.  

I do not know anything about gfClient. 

The "name"  property is the name of the resulting track.  This has a default but is user settable as are all track names.

**Comment by helgathorv** [comment]
Is now available in the latest version of IGV on the [downloads](https://software.broadinstitute.org/software/igv/download) page.
