### ISSUE TITLE
AWS support regression?

### ISSUE THREAD

**Issue by brainstorm** [igvteam/igv#1069]
Upon upgrading to the newly released log4j-fixing version (2.11.6), there seems to be a regression with AWS support, @jrobinso? Can you reproduce/confirm it (before I go through commits, changes, backtraces, etc...)?

![Screen Shot 2021-12-15 at 1 47 43 pm](https://user-images.githubusercontent.com/175587/146113790-978e754c-26b5-492d-9742-bdc0ad32c408.png)
![Screen Shot 2021-12-15 at 1 47 53 pm](https://user-images.githubusercontent.com/175587/146113813-990eab22-dd2b-414b-abac-400fd20b7638.png)

**Comment by jrobinso** [comment]
You need to enable the port listener explicitly now, go to advanced preferences and turn it on.   As part of general security upgrade that is off by default now, as most users don't need it.   The thinking was with no port listener it is physically impossible to hack into your computer through IGV.   However, to be honest I had forgotten that port was also used for oAuth, so perhaps a rethink is in order,  but I'm sure that is what's happening here.  I will look at turning the port on when oAuth is invoked, since it won't work without it.

In the meantime enable it through advanced preferences.

**Comment by jrobinso** [comment]
BTW it has always been possible, at least theoretically, to use oAuth with the port listener off (that is without a redirectURI).  That is what the popup is for.   This has been tested on Google, which presents an auth code in the web browser, but not on AWS.     Still not sure what we will do about this but we could start the port listener when the authorization page is opened, if not for Google at least for AWS.

**Comment by jrobinso** [comment]
I've tested starting it when an oAuth page with Google login, I see no reason that wouldn't work with AWS.   We'll discuss pushing a new release soon with this change, it seems a good compromise.   In the meantime either don't update yet or tell your users to enable the port.

**Comment by brainstorm** [comment]
I'd prefer not to prompt the user with OOB codes, enabling the port with oAuth urls sounds like a good compromise and makes the IGV upgrade process seamless (as it should be IMO). Thanks for looking into this Jim!

**Comment by jrobinso** [comment]
This should be resolved with todays release, 2.11.7.  The port is open when the oAuth page is open, and closed when the redirect response is received.  Tested against Google and AWS

**Comment by brainstorm** [comment]
Thanks so much Jim for the speed on fixing this up, much appreciated! I just notified our staff, I'll come back and reopen this if there's any issues.

**Comment by jrobinso** [comment]
@brainstorm Heads up that we are going to drop log4j soon, if you do anything special with log4j loggers WRT IGV (i.e. with your own configuration, for example) it will not be supported in the next and future releases.   I'm writing a simple wrapper around java.util.logging.   There is yet another patch for log4j,  3rd in a week:  https://www.zdnet.com/article/apache-releases-new-2-17-0-patch-for-log4j-to-solve-denial-of-service-vulnerability/.   The simple logging we do isn't worth it.

I don't believe any version of IGV is vulnerable to this,  I can't see how,  but that's irrelevant as just having the log4j jar in your distribution is a problem for many organizations.

**Comment by brainstorm** [comment]
Thanks Jim and no worries, thanks for telling in advance!
