### ISSUE TITLE
Opening Coverage dailog box using  batch file/igvtool

### ISSUE THREAD

**Issue by vyomeshj209** [igvteam/igv#1070]
Hello  @jrobinso,

Opening coverage window manually is tedious for many samples at a time and take a snap (manual).
I want to open the coverage dialog box that highlights frequency of bases using batch file/or any other alternative method.

Similar to this image.
![igv](https://user-images.githubusercontent.com/77434374/146637722-c1d5f4e5-0525-4dc4-9600-b6bff19e2fea.png)

Currently using the below script:
new
#load /home/user/Projects/dna/sample_1/sample_1.bam
genome hg19
goto chr17:41,209,090-41,209,100
sort position chr17:41,209,095
#coverage_dailog_box #unable to find the command
colorBy READ_STRAND
sort BASE
maxPanelHeight 500

#snapshot abc.png

Kindly guide.

Thanks  & regards,
Vyomesh

**Comment by vyomeshj209** [comment]
We want to use the snap shot (that includes the coverage dialog box) into other tool and make inhouse software more efficient and automated

**Comment by jrobinso** [comment]
That doesn't really answer my question, it just restates your request.  That's not possible with IGV, and perhaps IGV is the wrong tool for this.
