### ISSUE TITLE
Batch command `new` doesn't appear to unload tracks

### ISSUE THREAD

**Issue by CiaranOMara** [igvteam/igv#1071]
Given an IGV session with loaded tracks, when running a batch command from the tool menu, the command `new` doesn't unload tracks.

**Comment by CiaranOMara** [comment]
As an aside, does `new` reset preferences to default values?

**Comment by jrobinso** [comment]
It should unload the tracks, so that is a bug if I can reproduce it.   New should be equivalent to "new session" from the file menu.   So the default annotation and sequence tracks should remain, but tracks you have loaded should be removed.  It has no effect on preferences.

**Comment by CiaranOMara** [comment]
Sorry, my batch script had `new` commented out. I hope you didn't spend too much time on this.
