### ISSUE TITLE
Security issue with igv tools command line with Log4Shell library

### ISSUE THREAD

**Issue by paulinefx** [igvteam/igv#1075]
Hello,

I use igvtools in command line. However it has been picked up by the IT department as vulnerable because of the Log4Shell library. Therefore, I cannot use it anymore. Is there going to be an upgrade without the Log4Shell library?

Thank you

Pauline

**Comment by jrobinso** [comment]
I think you mean the log4j2 library.   There was an update the day after
that vulnerability was announced, install the latest build (2.11.9).
