### ISSUE TITLE
igv 2.11.8 test failure

### ISSUE THREAD

**Issue by chenrui333** [igvteam/igv#1076]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>test error log</summary>

```
INFO [Dec 20,2021 19:52] [Main] Startup  IGV Version 2.11.8 12/20/2021 02:45 PM
INFO [Dec 20,2021 19:52] [Main] Java 17.0.1 (build 17.0.1+1) 2021-10-19
INFO [Dec 20,2021 19:52] [Main] Java Vendor: Homebrew https://github.com/Homebrew/homebrew-core/issues
INFO [Dec 20,2021 19:52] [Main] JVM: OpenJDK 64-Bit Server VM Homebrew   
INFO [Dec 20,2021 19:52] [Main] OS: Mac OS X 12.0.1 aarch64
INFO [Dec 20,2021 19:52] [Main] IGV Directory: /private/tmp/igv-test-20211220-54087-1jt2x/igv
INFO [Dec 20,2021 19:52] [GenomeManager] Loading genome: https://s3.amazonaws.com/igv.org.genomes/hg19/hg19.json
INFO [Dec 20,2021 19:52] [GenomeManager] Loading genome: https://s3.amazonaws.com/igv.org.genomes/hg19/hg19.json
INFO [Dec 20,2021 19:52] [IGV] Loading 1 resources.
INFO [Dec 20,2021 19:52] [TrackLoader] Loading resource, path https://s3.amazonaws.com/igv.org.genomes/hg19/ncbiRefSeq.sorted.txt.gz
SEVERE [Dec 20,2021 19:52] [IGVPreferences] No default value for: CIRC_VIEW_ENABLED
INFO [Dec 20,2021 19:52] [ShutdownThread] Shutting down
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/runs/4590571011
relates to Homebrew/homebrew-core#91775

**Comment by jrobinso** [comment]
I can't tell what the problem is, it builds for us, however the latest
release is 2.11.9.   Try that.

**Comment by chenrui333** [comment]
Same error with 2.11.9 build

Where can I find the config, `CIRC_VIEW_ENABLED`?
> SEVERE [Dec 23,2021 14:38] [IGVPreferences] No default value for: CIRC_VIEW_ENABLED

**Comment by jrobinso** [comment]
That's not a real error, just a warning, is it causing any problem other
than console output?

**Comment by chenrui333** [comment]
my bad, updating the test fixed my issue. Thanks for pushing a new release.

**Comment by chenrui333** [comment]
As my problem got solved, closing this issue now.
