### ISSUE TITLE
No default value for: CIRC_VIEW_ENABLED

### ISSUE THREAD

**Issue by dpalachan** [igvteam/igv#1078]
I tried this with both the bundled Java version and the system version on Linux (Centos 7, openjdk 11.0.13)

This may relate to #1076 , but the solution was not documented, so I'd like to ask for some help on this one. 

When I run {{./igv.sh}}, I get:

> Using system JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8-LTS, mixed mode, sharing)
WARNING [Dec 27,2021 11:05] [Globals] Development mode is enabled
INFO [Dec 27,2021 11:05] [Main] Startup  IGV Version 2.11.9 12/21/2021 12:15 AM
INFO [Dec 27,2021 11:05] [Main] Java 11.0.13 (build 11.0.13+8-LTS) 2021-10-19
INFO [Dec 27,2021 11:05] [Main] Java Vendor: Red Hat, Inc. https://www.redhat.com/
INFO [Dec 27,2021 11:05] [Main] JVM: OpenJDK 64-Bit Server VM 18.9   
INFO [Dec 27,2021 11:05] [Main] OS: Linux 3.10.0-1160.36.2.el7.x86_64 amd64
INFO [Dec 27,2021 11:05] [Main] IGV Directory: /home/myfolder/igv
INFO [Dec 27,2021 11:05] [GenomeManager] Loading genome: /home/myfolder/SARS-CoV-2_1_MN908947.fa
INFO [Dec 27,2021 11:05] [GenomeManager] Loading genome: /home/myfolder/SARS-CoV-2_1_MN908947.fa
SEVERE [Dec 27,2021 11:05] [IGVPreferences] No default value for: CIRC_VIEW_ENABLED

When I run this with the bundled Java version of IGV, the only difference I get in the output is the Java Vendor, which makes sense.

This results in an empty IGV window with a yellow-ish background and nothing else. The only thing possible is to close the window which displays the "Shutting down" message on the console output.

**Comment by jrobinso** [comment]
Sorry I don't have any insight as I can't reproduce this on MacOS, and don't have a Linux box.   Could you try the "development snapshot" build available here?  https://software.broadinstitute.org/software/igv/download_snapshot

**Comment by jrobinso** [comment]
BTW re the "SEVERE" error that is just a logging mis-categorization,  this should be an "INFO" message.  I would be surprised if logging could cause the issue you see,  and it does not on MacOS.

**Comment by dpalachan** [comment]
Thank you for the swift reaction, I appreciate it! I tried the development snapshot and it didn't give this warning, but it also didn't work. I still get a blank yellow-ish window. 

I tried the stable version in an Ubuntu VM and the message appeared on the console, but I had no trouble with it and the IGV window appeared normally and everything worked. So, I guess I'm missing some visualization libraries for CentOS. How could I go about debugging which dependencies I'm missing? Or is there a list of dependencies somewhere? I couldn't find anything with a quick Google search. Thank you in advance.

**Comment by jrobinso** [comment]
I really couldn't say, we don't do anything special outside of normal Java
graphics.    If I find anything update this ticket.

**Comment by dpalachan** [comment]
OK, clear. I will actually close the ticket. On Ubuntu, I got this message on the console, but IGV still worked like a charm. So, my graphics issues on CentOS must be related to missing libraries and not to this message.

**Comment by davideby** [comment]
Hi @dpalachan,

You mentioned IGV coming up as a yellow screen on CentOS.  You might want to have a look at [issue 1036](https://github.com/igvteam/igv/issues/1036) as it sounds like a similar problem.

Sorry, just seeing this after the holidays.  Hope it helps.
- David
