### ISSUE TITLE
Visualizing Nanopore data with IGV

### ISSUE THREAD

**Issue by HAHasani** [igvteam/igv#1080]
Hello all,

I'm trying to simply visualize my data that were generated with FLONGLE; I downloaded the reference genome from _ebi.ac.uk/ena/_, used minipam2 to align the data to it. However, when I load the data to IGV the following error appears and only four records are then displayed (out of ~33k primary alignment records):

> Error encountered querying alignments: java.lang.IllegalArqumentException: Reference name for '488644383' not found in sequence dictionary.

I checked the results using `samtools flagstat` and this is the outcome:
_35805 + 0 in total (QC-passed reads + QC-failed reads)
2 + 0 secondary
2427 + 0 supplementary
0 + 0 duplicates
35536 + 0 mapped (99.25% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)_

Could you please help me clarify the reason? 
Thank you

P.S. this is lambda genome

**Comment by jrobinso** [comment]
This should not occur, the error indicates that a sequence in the index
file has no corresponding entry in the bam file sequence dictionary.  One
possible cause could be using an invalid bam (or cram) file index, or an
index created for another file.
