### ISSUE TITLE
Visualization of gene fusion from RNA seq data

### ISSUE THREAD

**Issue by vyomeshj209** [igvteam/igv#1081]
Hi,
Can you suggest the best way or highlight proper steps to visualize gene fusion from RNA seq data

**Comment by jrobinso** [comment]
Hi @vyomeshj209,  could you give us more details on what type of data you have?  Are you asking about alignments, or "calls" of known fusions in some other file format?

**Comment by vyomeshj209** [comment]
I m trying visualize gene fusion from BAM file of sample, within it we have EWSR1--ATF1 gene fusion and specific breakpoints.  What will be ideal representation that we get in IGV.

**Comment by jrobinso** [comment]
It depends on your purpose, there is no specific gene fusion view in IGV.   If you want to look at evidence for the fusion you might turn on "show soft clips" from the Alignments preferences,  you should see clipped reads at the breakpoints.   The clipped portion should align to the region at the other end of the fusion.   For many genomes we host you can check this by right-clicking and selecting "blat soft clip" from the menu.   Finally you can view both ends at the same time using multi-locus view.

**Comment by vyomeshj209** [comment]
I got soft clipped option. BLAT soft clip option is not available. It only show BLAT read sequence option. Kindly guide where to find the option.

Attaching image for reference.
![image.png](https://user-images.githubusercontent.com/77434374/148327829-da87b1fb-1c5d-44d4-bba9-339186a74a9b.png)

**Comment by jrobinso** [comment]
You did not state what version of IGV you are using.  If theres is not blat-soft-clip options it means you either have an old version, or the read you clicked over does not have soft clips.

**Comment by brainstorm** [comment]
Hello @jrobinso, several of our cancer sequencing curators have noticed that [this commit broke their flow with RNA fusion data analysis](https://github.com/igvteam/igv/commit/84a29e91038893b2ed7069272a9a97b831502a8e), perhaps is what @vyomeshj209 is also observing? Would it be possible for you to restore that particular functionality? In particular @JoepVissers stated that:

> colouring RNA reads by size and pair orientation is essential when analysing fusion genes. It helps us verify the read support for their expression.

**Comment by jrobinso** [comment]
@brainstorm Please open a separate issue for this, or ideally have the analysts open an issue because there will be some discussion.   The commit you reference does not affect pair orientation coloring, or pairs on different chromosomes, only pair-by-insert size.   The insert size stats are computed assuming DNA (no splices) so what we had before will not be restored as is, we will need to do something new appropriate for RNA.

**Comment by vyomeshj209** [comment]
@jrobinso 

> You did not state what version of IGV you are using. If there's is not blat-soft-clip options it means you either have an old version, or the read you clicked over does not have soft clips.

1] Version used for performing the analysis -> IGV_Linux_2.9.2
2] I m getting two option for BLAT, how can we use it? Kindly guide
![Blat_IGV_2](https://user-images.githubusercontent.com/77434374/148491778-da5304aa-f5c3-4daf-9424-660b3538c104.png)
![Blat_IGV_1](https://user-images.githubusercontent.com/77434374/148491780-5efa7cce-08df-45e1-a79c-c8309f1ecd18.png)
 
Is it possible you to connect google met/zoom and solve these queries?

**Comment by jrobinso** [comment]
That's an old version, it did not have blatting of soft clips.  Please
update to 2.11.9.  Sorry I can't give personal tutorials, and really don't
have expertise in biological interpretation.
