### ISSUE TITLE
BUG: `View > Fit Data To Window` resets the "Type of Graph" on overlaid tracks to "Bar Chart", and arguably shouldn't

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#1082]
I find this in version 2.11.0 

To reproduce:

load some tracks having a shared attribute 
display them all as "Line Plot" 
overlay them by the shared attribute 
fit to window
observe they are no longer Line Plots, but Bar Charts.

**Comment by jrobinso** [comment]
I can't reproduce this (2.11.9)

**Comment by jrobinso** [comment]
Fix in next release, sometime this week.
