### ISSUE TITLE
IGV batch snapshot is not working

### ISSUE THREAD

**Issue by yinshiyi** [igvteam/igv#1086]
new
genome susScr11
snapshotDirectory "C:\Users\Shiyi Yin\OneDrive - eGenesis Bio\Documents\puberty\bigwigs\"
load "C:\Users\Shiyi Yin\OneDrive - eGenesis Bio\Documents\puberty\bigwigs\21448_ATAC_S7_R1_001.trim.srt.nodup.no_chrM_MT.tn5.pval.signal.bigwig"
maxPanelHeight 400
goto chr11:333333-108138003
echo lol
collapse
snapshot lol.png
goto chr6:333333-333333

Behavior: it is going to the chr6 location but the snapshot is nowhere to be found

**Comment by jrobinso** [comment]
Please always state the version of IGV you are using.

**Comment by helgathorv** [comment]
@yinshiyi Your batch script works for me in IGV 2.11.9 (the current version), so make sure that's the version you are using.
There is one difference between your script and mine: you are writing the image file to OneDrive. If this continues to be a problem for you when you've made sure you have the latest IGV version, you could try writing the file somewhere else and see if OneDrive is the cause of the problem.
