### ISSUE TITLE
Sashimi plot not displaying anything until zoomed in to smaller region

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#1087]
Looks like the Sashimi plot is using the visibility range threshold from the DNA preferences (as opposed to the RNA preferences).
So a view that looks fine in the RNA alignment track is not displayed in the sashimi plot until you zoom in past the DNA preference threshold (actually the DNA threshold x2)

I found this when investigating the following [igv-help issue](https://groups.google.com/g/igv-help/c/gFf4w__5lXQ/m/7bbtB1XSEAAJ?utm_medium=email&utm_source=footer)

**Comment by jrobinso** [comment]
Fixed with commit 96822a3a
