### ISSUE TITLE
Disable fetching genome list 

### ISSUE THREAD

**Issue by jeremyNg** [igvteam/igv#1088]
Hi all, 

I am using IGVtools within a local environment with no internet connection. I have downloaded the required genome files, and the command igvtools count runs to completion. However, it always also attempts to fetch the genome list and throws an error message indicating a connection error. Is there anyway to disable the fetching of genome list? 

I am using igvtools 2.11 on a Linux platform. 

thanks in advance!

**Comment by jrobinso** [comment]
Does the command complete successfully?   I'm not sure what the problem is, is it the stderr output?  You can consider that a warning.

Also, 2.11 is not a complete version string.  Do you mean 2.11.0?

**Comment by jrobinso** [comment]
OK I can reproduce it.  It should be harmless, if not let me know, but I will leave this open until there is a fix.   There is nothing you can do no your side.
