### ISSUE TITLE
Intensity of color by base modification (Mm/Ml)

### ISSUE THREAD

**Issue by amwenger** [igvteam/igv#1095]
Thank you for implementing the ability to color reads by base modification (Mm/Ml tags); it is really useful.  Two extensions that would make it more useful are:

1. Option to configure the probability (Ml tag) range over which the color intensity varies similar to "Shade mismatched bases by quality."  Currently, it is hard for me to distinguish visually between very confident calls (Ml ~ 100%) and intermediate calls (Ml ~ 50%).  Perhaps call the section "Shade bases by base modification" with options: "No color for probability (%) ≤: " with default 0 and "Max color for probability (%) ≥:" with default 100 and then vary the intensity linearly between min and max.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/7155109/151704091-0dcdb128-23c7-45a0-9e3c-d1c72e6e6a60.png">

2. Reveal regional methylation by averaging the intensity for all positions that share a pixel when zoomed out.  When zoomed out to >30 kb, the general hypermethylation in human makes all reads looks red and hides potential methylation differences.  If each pixel were colored with an average of the intensity of the bases that contribute to the pixel, it might be possible regional differences. Here is how it looks now for a 30 kb region that should have a few kb with lower methylation:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/7155109/151704844-33fab1a8-da1f-445c-85fe-28f60225fbe2.png">

**Comment by jrobinso** [comment]
Thanks @amwenger for the suggestions.   RE (2),  I suppose the (unintended) effective behavior now is taking the "maximum" of the intensity of the bases, clearly not a good statistic for methylation.

**Comment by amwenger** [comment]
In my opinion, #1133 address the key goals of this issue.  So, perhaps you could close this one.
