### ISSUE TITLE
igvtools totdf with new genome json?

### ISSUE THREAD

**Issue by mcsimenc** [igvteam/igv#1097]
Hi,

The igvtools totdf tool online documentation says to use .genome files, but I see they have been deprecated. How should totdf be used now?

I may have missed it somewhere, but how do we generate the new genome json file?

Thanks,

Matt

**Comment by jrobinso** [comment]
You create json genomes with a text editor, the fields are described here:  https://github.com/igvteam/igv.js/wiki/Reference-Genome

However, for igvtools you can use a "chrom.sizes" file in lieu of a genome, this is a simple 2 column tab delimited file.  First column is sequence/chromosome name, the second the sequence length.   For example, the first few lines for hg19 are

```
chr1	249250621
chr2	243199373
chr3	198022430
chr4	191154276
```

**Comment by mcsimenc** [comment]
Thank you, Jim.
