### ISSUE TITLE
Sort Alignments By Base Works Intermittently

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv#1098]
It was working for me last time I tried it.

![image](https://user-images.githubusercontent.com/631218/152593581-8601f683-741f-4636-a09c-02fbe4922e3c.png)

But I restarted IGV, tried it again, and it doesn't sort them in any apparent order because the Ts are separated. I can't figure out when it fails and when it works to make the troubleshooting easier.

![image](https://user-images.githubusercontent.com/631218/152594362-d540e3ef-0f02-4ffa-a76c-08ccaf203185.png)

**Comment by jrobinso** [comment]
The sort is based on the bases at the center of the view.  The only way to know what is at the center reliably is to enable "Show Center Line" from the alignment preferences.    I can't tell from your screenshots what is at the center, of course.

**Comment by DarioS** [comment]
Oh, I see. This is [documented](https://software.broadinstitute.org/software/igv/AlignmentData#alignmenttrack) in Viewing Alignments section of user manual for anyone else wondering.
