### ISSUE TITLE
feature request: adding panels

### ISSUE THREAD

**Issue by duartemolha** [igvteam/igv#110]
Hi Guys

I would very much like the ability to add additional panels to the viewer to be able to group my tracks as needed.

I know I can specify multiple panels on a session file... but I could not find a way to just add a panel on the UI.
Apologies if there is already a way to do this ... but if there is it is not obvious because I cannot find it.

**Comment by vttrifonov** [comment]
I second that. Until then, I solved my problem by introducing an additional attribute that groups the tracks and then sort on this attribute.
