### ISSUE TITLE
Unable to load from s3 URL

### ISSUE THREAD

**Issue by qing-at-work** [igvteam/igv#1101]
Tested versions: 2.12.0, 2.11.9

After configuring igv with Cognito authentication by following instructions [here](https://umccr.org/blog/igv-amazon/), loading from s3 URLs doesn't work (no error messages, no tracks loaded in IGV).

**Comment by jrobinso** [comment]
Fixed with PR https://github.com/igvteam/igv/commit/104b3d97b0e9ded9ae1a18d7c5ba030a14c12917
