### ISSUE TITLE
2.12.0 - problem loading vcf file in the proper track

### ISSUE THREAD

**Issue by gokalpcelik** [igvteam/igv#1104]
Hi.

Since 2.12.0 I observed a weird issue of misplaced vcf tracks upon loading.

![image](https://user-images.githubusercontent.com/37572619/153012406-c8add6d7-f10f-4adb-a200-9340c9ca8209.png)

And here is the 2.11.9 

![image](https://user-images.githubusercontent.com/37572619/153012651-93febd37-bc68-4bee-a0ae-4e1c688f818c.png)

Also I noticed another issue with 2.11.9 which was not there with 2.11.8. 

Genotypes were always shown when vcf file is loaded however 2.11.9 hides genotypes panel and has to be manually switched on. 

I tried reverting to 2.11.8 by pulling the proper branch and recompile myself but the problem persists. 

I am on a ubuntu 20.04 machine with openjdk 11. 

Thanks.

**Comment by jrobinso** [comment]
Thanks for the reports, I will look into them.   For the first issue, you
can drag the vcf track to the upper panel,  just mouse press over the track
name and drag.    You co not want to reorder the panels themselves.
