### ISSUE TITLE
"Enable port"-setting (from previous install?) is not preserved after new installation

### ISSUE THREAD

**Issue by sam-ber** [igvteam/igv#1105]
After a fresh installation (2.12.0) I had to tick this option again, which took me a while to figure out:

![grafik](https://user-images.githubusercontent.com/48088251/153438105-746049e7-fb32-4faf-b3b7-63373e209a08.png)

Other settings seem to have been taken over from the previous installation just fine.

**Comment by jrobinso** [comment]
As of release 2.11.7 the port is off by default, as noted in the release
notes.    I'm not sure what you mean by "fresh install" but if you clear
you igv folder all preferences are lost.   Now that you have explicitly
enabled the preference it should be remembered, unless of course you remove
the igv folder (or more specifically prefs.properties).

**Comment by sam-ber** [comment]
Ah, I see. Thanks for pointing that out!
