### ISSUE TITLE
Feature Request: Support sorting options for alignment groups.   (was:  reverse order for grouping)

### ISSUE THREAD

**Issue by nh13** [igvteam/igv#1106]
I would like to group my alignments by a numerical tag that has a value between 0 and 1.  Currently, IGV sorts by tag in ascending order.  I would like a way to sort the records by tag in descending order. 

I can hack this in this example by converting the tag value to `1-Value`, but then the name of the groups are also `1-Value`.  Is there a way to overcome this?

I see the group order comparison is ascending here: https://github.com/igvteam/igv/blob/f92314efbf0878761152d56d8eef0ad32a1e1a0f/src/main/java/org/broad/igv/sam/AlignmentDataManager.java#L296

CC: @jacarey

**Comment by jrobinso** [comment]
@nh13 I'm a bit confused, are we talking about groupign or sorting,  or sorting groups.   The line of code you reference sorts alignment rows within groups (by default there is 1 group), not groups.    AFAIK there is no way to arrange or sort groups, perhaps that is the request?   Or is it about sorting?

I had thought that sorting by the same attribute twice would toggle the order, but it doesn't seem to.  Perhaps I'm thinking of igv.js.   

So there is an enhancement request here,  I'm just not sure what it is.

**Comment by nh13** [comment]
Sorry I wasn’t clear. I want the sort across groups to be able to be ascending or descending. My apologies again for the confusion.

**Comment by jrobinso** [comment]
Ahhh, English syntax is hard sometimes.    So you want
(1) sort of alignment rows within each group to be ascending or descending, or
(2) new concept of sorted groups

I'm assuming (1).   Would toggling the sort order work?   That is repeated sorts by the same property at the same location toggle direction.   This is a common expectation, I think igv.js does this.

**Comment by nh13** [comment]
Imagine four groups of alignment, with the records in group having value one, and so on. I’d like to sort the four groups ascending or descending. Sorting alignments within a group is supported I believe.

**Comment by nh13** [comment]
@jacarey may have a better command of English (technically not my first language, sorry)

**Comment by jrobinso** [comment]
OK that's new, glad you clarified.  It looks like groups are arranged alphabetically by key.   This is unrelated to alignment row sorting.   There is no sort groups option per se.  

I will rename this issue now that I understand it.

**Comment by lbergelson** [comment]
closed by #1167
