### ISSUE TITLE
AB0 gene shows 8 exons in IGV instead of 7 with GRCh38.

### ISSUE THREAD

**Issue by generalbytes** [igvteam/igv#1108]
AB0 gene shows 8 exons in IGV instead of 7 with GRCh38.

**Comment by generalbytes** [comment]
I was thinking about ways how to fix this in IGV but didn't come up with any good enough solution.

**Comment by jrobinso** [comment]
If it shows 8 that's because the annotation says they are 8.  Why do you think there are 7?

**Comment by jrobinso** [comment]
Checked against UCSC genome browser, 8 is the correct number.

**Comment by generalbytes** [comment]
UCSC Genome Browser is wrong. Uses error-nous annotation.
Yes, annotation says there are 8 exons. Annotation is wrong.

On following page is shown that ABO has 7 exons: 
https://www.ncbi.nlm.nih.gov/genome/gdv/browser/gene/?id=28
Scientific papers also mention that ABO has 7 exons.

How did you generate annotation file? What is the primary source from which you generated ncbiRefSeq.sorted.txt (that is being downloaded as ncbiRefSeq.sorted.txt.gz) ? I would like to fix it at the source (probably outside of IGV). Thank you for directing me at right place.

It is most likely due to indel at exon 6. An algorithm generating annotations incorrectly separated exon 6 on two parts (exon 6 and new exon 7), exon 7 therefor becomes exon 8.

Thank you,
Karel
