### ISSUE TITLE
Feature request: color by mapping quality

### ISSUE THREAD

**Issue by nh13** [igvteam/igv#1110]
It would be useful to have both implemented when looking at low complexity regions and trying to identify mapping artifacts.

**Comment by nh13** [comment]
I think having the sort/group/color all have the same options would be ideal.  I just found that I'd like to group by insert size.

**Comment by jrobinso** [comment]
@nh13 Grouping as currently implemented works for categorical values, there is 1 group per value.   Grouping by insert size could work by using the same categories we use for color. (small, normal, large, inter chromosome).    Grouping by mapping quality is more difficult, there are no predefined categories  other than zero (which isn't really a mapping quality) or not.   Grouping by a continuous value that is not categorized or binned in some way would not really work, you could end up with as many groups as you have individual values.

**Comment by jrobinso** [comment]
@droazen @lbergelson this would be a good initial issue to get your teeth into IGV.

**Comment by nh13** [comment]
As long as there’s numerical or lexicographical ordering, I don’t care how many groups there are. 

For mapping quality, the range is 0-255, as per the SAM spec I believe.


For coloring, I’d be fine with a gradient from min to max in the window, or perhaps even in the preferences.

**Comment by jrobinso** [comment]
Here's an idea for quality - we shade alignments by quality as we do mismatched bases, that is apply an alpha transparency, with the color being whatever it is according to other options (which can be "none" -- i.e. grey or whatever is chosen via "change track color").    The option would work as "Shade bases by quality" works, with min & max tunable in the preferences.

**Comment by nh13** [comment]
That’d be great, as long as I can have control if I want low or high be transparent. Sometimes I want to see high quality mappings, sometimes low.

**Comment by nh13** [comment]
Thank you!!!
