### ISSUE TITLE
Why would a bigwig have coverage peak when there are no alignments in the bam?

### ISSUE THREAD

**Issue by hchetia** [igvteam/igv#1116]
Why do you think would a bigwig have a coverage peak in the upstream promoter region (before start codon) but the bam wouldn't show any corresponding alignments in the region?
The bigwig was generated from the bam file using deeptools (bamCoverage --effectiveGenomeSize 2913022398 --normalizeUsing RPKM)
Kindly correct me if this is not a relevant issue for IGV.
![image](https://user-images.githubusercontent.com/64626735/155222858-e001d33c-0adb-4759-944b-15b2dc817daf.png)

**Comment by jrobinso** [comment]
This is a question for deeptools, IGV is just showing you what is there.
 My guess is they are binning, not computing coverage for every single
base, but in any event its not an IGV question.

**Comment by hchetia** [comment]
Thanks @jrobinso
