### ISSUE TITLE
the alignment color of inversion or translocation

### ISSUE THREAD

**Issue by charliechen912ilovbash** [igvteam/igv#1120]
How to color the alignment like the picture below?
when a read is mapped into two different place, sometimes is two different chromosome,
then when I click the read, the color will change, so I could tell the read at two mapped position.
I have succeed some times, but not sure how to turn on this function.

The red and blue lines link the read are added by me.
![截圖 2022-03-09 上午6 10 38](https://user-images.githubusercontent.com/54789400/157325735-136b8151-ce58-4b09-87e1-4335201fe28d.png)

**Comment by jrobinso** [comment]
You can't really color like the picture in bulk,  however "command-click" will highlight an individual pair.   It is "command-click" on a Mac,  I'm not sure how that translates to windows and linux but it is some modifier key combined with a click.

**Comment by charliechen912ilovbash** [comment]
Thanks!
It is ctrl + click in Ubuntu 20.04.
