### ISSUE TITLE
Feature request: option to rebind or turn off global keyboard shortcuts

### ISSUE THREAD

**Issue by KHR0** [igvteam/igv#1122]
Hello, thank you for creation and maintenance of such a great tool. 

I am currently using v2.12.2. When using the feature name/locus panel to type and search for certain genes, there are times when pushing keys like F and R are accepted as hotkey for next feature when I am trying to write a gene name like "ifng". As a result, "i" gets deleted and replaced by the genome coordinate of the next feature and rest of the string gets appended to the corrdinate, like "chr0:0000-0000fng". 
I say "there are times" because sometimes this doesn't happen and other times it constantly does, and I could not figure out how to exactly get the program to be in this "hotkey constantly on" state. 
Given that this hotkey feature is quite useful for folks who need it (like in #1046), it would be great to have a way to customize/rebind these shortcuts to keys less commonly used or even turn them off in preference as an option. Thank you!

**Comment by jrobinso** [comment]
Yes that is extremely annoying, I encountered it myself, and thought that this had been fixed.   Can you give me a set of steps to reproduce this?

I can also provide a preference to turn this off, but that's not really a fix for people who have it on.
