### ISSUE TITLE
Bug: Reads are not appearing unti l click on the track name

### ISSUE THREAD

**Issue by gevro** [igvteam/igv#1123]
Hi, I just upgraded to 2.12.3 from 2.11.9. On Mac OS Maverick.

I'm loading a session (XML) with about 10 tracks. I then go to a specific location, but the tracks are all blank with the spinning mouse cursor wheel until I click on the name of one of the tracks, and then instantly all the reads appear.

And the mouse cursor wheel keeps spinning.

**Comment by gevro** [comment]
Also: Zoom in/out does not work. I click zoom in and out and nothing happens, and then again when I click the track name, the viewing window updates to show the correct zoom level.

CORRECTION: I'm on Mac OS Big Sur.

**Comment by jrobinso** [comment]
I'm not able to reproduce this, could you give more details or ideally a test case that will reproduce the problem?  This is not much to go on.   The igv.log file might have some info.

**Comment by gevro** [comment]
It is happening with every file I open. Also with older version of IGV actually.
It must be a system issue with Big Sur. This started after upgrade.

Are you available for 5 min Zoom so I can show you? Because I'm not sure how to guide you on replicating this.

**Comment by jrobinso** [comment]
I don't need to see it, I believe you, but this is not happening on a wide scale and we have 100s of thousands of Mac users.    In fact I personally use BigSur to develop IGV.   As I suggested, there might be some info in your igv.log file, located in an igv folder in your home directory.   

Has anything changed in your network environment?   Are there any new firewalls, anti-virus software, or proxies?

**Comment by gevro** [comment]
[igv1.log](https://github.com/igvteam/igv/files/8316504/igv1.log)

See attached. But I don't know if this issue is related.

The tracks are all from GCloud.

However, these same tracks are loading fine on a different computer.

Nothing changed on my computer, but the business network I'm on may have changed.

**Comment by jrobinso** [comment]
I see errors in the log but unfortunately they are rather generic and don't indicate a cause.   Let's try this next,   (1) shut down igv and rename. "prefs.properties" in your igv folder to "prefs.properties.bak",  or just delete it.   Then restart.  If that fixes the problem please zip and attach prefs.properties so we can look for a cause there.   (2) if possible try your computer somewhere other than on your business network.

**Comment by gevro** [comment]
prefs.properties doesn't help.

I tried same computer via cell phone hotspot, doesn't help.

It is bigwig + CRAM.

Another feature of this issue is that for some tracks, the scroll bar doesn't show up. And scrolling left right doesn't work.

But I think maybe I found the source of the bug? One of the bigwig tracks I realized no longer exists. And when I try to remove the track by right clicking on it, IGV doesn't show the usual right click menu to remove the track. And it didn't give an error that the file is missing.
 - Could it be that this missing file is messing up IGV and causing all these issues? This would still be a bug however, because IGV should alert regarding missing track files. This would also explain why the mouse wheel keeps spinning.

So perhaps the thing to do to try and replicate this is to make a session with an existing bigwig file on Gcloud and maybe a few other bigwig and CRAM files -> save session. Then delete one of the bigwig files from Gcloud. Then reopen the session.

**Comment by gevro** [comment]
I put that in my first post above: "I'm loading a session (XML) with about 10 tracks."

The session worked on a different computer yesterday, but I will try again later today.

**Comment by jrobinso** [comment]
Sorry, yes I missed that.   But please let me know about the test on the other computer.   I will try to get to this tomorrow afternoon.

**Comment by gevro** [comment]
I tried the session again on another computer and it doesn't work. So I think it's safe to say that my hypothesis about the issue above is probably the one to investigate - if you can replicate it too:

"So perhaps the thing to do to try and replicate this is to make a session with an existing bigwig file on Gcloud and maybe a few other bigwig and CRAM files -> save session. Then delete one of the bigwig files from Gcloud. Then reopen the session."

**Comment by jrobinso** [comment]
Yes will do, I don't have access to gcloud but that shouldn't matter.
