### ISSUE TITLE
Subject Alternative DNS name?

### ISSUE THREAD

**Issue by kalbflei** [igvteam/igv#1124]
Hello,

     I am running IGV 2.12.3 on Mac OS X 11.6, and am attempting to load a genome I have created with annotation from the URL via Genomes:Load Genome from URL.....

https://equinegenomics.uky.edu/data_warehouse/igv.jsonFiles/EquCab-3.0/goldenPath.Ec_build-3.0.json

I get the error message displayed in the attached file.

![Screen Shot 2022-03-21 at 4 10 01 PM](https://user-images.githubusercontent.com/14911381/159385924-9c77b811-0ae8-48eb-adbe-293c214253cc.png)

A colleague was able to demonstrate that the alternative DNS name matched that of our domain name 

% echo | openssl s_client -connect equinegenomics.uky.edu:443 2>/dev/null | openssl x509 -noout -ext subjectAltName
X509v3 Subject Alternative Name:
    DNS:equinegenomics.uky.edu

This did not happen when I used IGV a few weeks ago, although I am not certain what version that was.

Any information you could provide would be greatly appreciated.

**Comment by jrobinso** [comment]
That error message is not from IGV,  so I really don't know what to suggest.   Can you download it from a web browser on that machine?  I am able to load the genome without issues.

There might be more details in your igv. og file, located in the "igv" folder in your home directory, although I doubt there is anything helpful there.  This error would have been thrown in the Java network library.
