### ISSUE TITLE
Simple question on alignments in IGV

### ISSUE THREAD

**Issue by MarkWaltham** [igvteam/igv#1126]
Hi! Simple question
Can someone tell me what the significance is of the very soft coloured blue and pink aligned sequences (as on the left of screen grab) as opposed to the usual darker coloured blue/pinks (on the right). Thanx

<img width="337" alt="Screen Shot 2022-03-24 at 3 57 06 pm" src="https://user-images.githubusercontent.com/102277186/159845291-0acb63e2-223e-4aae-b1ba-d87afc2bc5c9.png">

**Comment by jrobinso** [comment]
See the user guide here, scroll down to the section on "Transparency for Mapped Reads". https://software.broadinstitute.org/software/igv/AlignmentData
