### ISSUE TITLE
gwas file-new plink

### ISSUE THREAD

**Issue by bnj50** [igvteam/igv#1127]
Hi
I am trying to upload summary statistics from plink generated  glm (hybrid) association file that include CHr, BP, SNP and P , plus other columns. 
however the new version of plink, also produce NA for some SNPs (due to several reasons). I noticed that IGV can not upload these files with NA in these fields. 
Cleaning file from NA is not easy given thousands of variants. 
Any advise or suggestion appreciated
thank you

**Comment by jrobinso** [comment]
Could you provide us with a small example file?
