### ISSUE TITLE
Support MM tag spec with new `.` or `?`

### ISSUE THREAD

**Issue by marcus1487** [igvteam/igv#1131]
The sam tag MM (modified bases) has been updated to add clarity to missing bases specified by the tag. This update adds a `.` or `?` mark after the modified base specification. This update appears to have broken the IGV parsing of this tag. My guess would be that IGV is interpreting the extra character as an additional modified base. Hopefully this can be fixed with a relatively simple update to the code to parse this tag. If it would be helpful I could submit a MR for this update given a pointer to the tag parsing code.

**Comment by jrobinso** [comment]
@marcus1487 Yes that would be helpful, but what would be more helpful is some test data to reproduce the issue.

**Comment by marcus1487** [comment]
I've put together a small set of reads (mapping to chr20 of hg38) with the old style MM tag and a the same set with the new style (containing `?` specifier) which fails to load in the latest version of IGV. 

You can find these files for download here:
[old style](https://nanoporetech.box.com/s/vzv001yyhphs3xme4apl3rgn9jxyhxxy)
[new style](https://nanoporetech.box.com/s/y2fah8quxtr2cs08fyhlu74o2u8lbo1s)

**Comment by marcus1487** [comment]
Is there any update on supporting this new format? Were you able to access the test files?

**Comment by jrobinso** [comment]
@marcus1487 Its on my current plan for the next point release,  hopefully by the end of next week but mid May at the latest.   Yes I can access the test files.

**Comment by jrobinso** [comment]
@marcus1487 Where is the updated specification for modified bases?

**Comment by jrobinso** [comment]
OK here's what I'm doing, based on a guess not the. actual spec.  If the base modification string ends with "." or "?" I'm stripping off that character.   That's it.  Java below, mmi is, for example ```C+m?,1,91,26,46,115,4,27,29,50,63,4,5,4,3,12,10,14,4,13,50,5,14,39,20,13,10,0,40,18,2,13,36,56,3,29,20,20,72,6,49,27,49,14,4,6,3,39,15,8,13,9,12,9,11,40,8,3,4,0,2,3,7,1,0,0,8,3,0,5,7,3,0,4,5,3,4,0,0,0,1,4,8,16,2,2,2,6,7,5,2,4,6,5,0,1,2,1,1,6,3,10,3,1,1,0,2,1,2,4,2,1,3,0,0,0,5,1,2,0,0,0,0,3,0,0,2,3,0,0,10,0,0,0,0,4,0,6,0,3,5,7,1,1,2,0,9,2,8,2,2,4,1,0,4,0,24,24,4,6,29,11,13,1,0,9,19,5,7,1,1,12,4,28,29,13,84,38,7,25,74,3,39,55,18,6,86,44,9,38,64,0,67,1,3,6,3,7,9,4,3,43,12,31,123,24,81,6,7,30,136,60,21,71,13,36,48,19,26,3,21,5,46,24,125,57,10,256,5,95,5,19,11,0,25,88,34,11,4,8,0,55,1,32,1,9,4,0,12,19,1,6,7,2,12,1,4,11,16,3,26,6,2,3,3,8,46,7,32,53,14,7,47,17,9,6,10,6,3,51,0,16,32,4,9,16,13,4,26,48,119,7,6,54,48,21,14,34,45,28,18,67,1,18,66,24,2,31,12,41,3,190,7,42,16,24,4,24,0,91,42,82,5,5,22,66,68,105,6,0,0,1,13,2,0,0,1,18,8,2,0,1,4,29,2,12,1,85,23```

```
            String[] tokens = mmi.split(","); 
            if (tokens.length > 1) {

                char strand = tokens[0].charAt(1);
                char base = tokens[0].charAt(0);

                boolean newStyle = tokens[0].endsWith(".") || tokens[0].endsWith("?");
                String modificationString = newStyle?
                        tokens[0].substring(2, tokens[0].length() - 1) :
                        tokens[0].substring(2);
```

**Comment by marcus1487** [comment]
That was my interpretation of the specification as well. The specification is in section 1.7 here https://samtools.github.io/hts-specs/SAMtags.pdf

**Comment by jrobinso** [comment]
I would not bet anything of value on my ability to interpret the spec referenced with 100% confidence.  I'm sure its entirely self-evident for those in the know.   So my interpretation is represented in the code above,  if there are problems reopen this issue or create a new one.
