### ISSUE TITLE
IGV not storing all the information from VCF

### ISSUE THREAD

**Issue by aswathyseb** [igvteam/igv#1135]
Hi

I have a VCF file produced by `paftools.js call` command. It produces a VCF file that looks like this in IGV (fig1)

![before_save](https://user-images.githubusercontent.com/5373487/163295865-81282712-54ab-4867-9ef3-cb8a4cf488c3.png)

But after saving the igv session, if I open it again it looses some information as you can see here (fig2)

![after_save](https://user-images.githubusercontent.com/5373487/163295884-8d13523f-d7eb-4327-a373-8ba658595a2d.png)

I am using IGV version 2.12.3.

Could you please help with this? How can I save the VCF file as it is loaded?

Thanks,

**Comment by helgathorv** [comment]
It looks like the genotypes are not being shown in fig2.  Try right-clicking on the VCF track and selecting "Show Genotypes". Does that bring it back? If so, did you hide them before you saved the session? That would cause the session to record showGenotypes="false" for the track in the session .xml file.

**Comment by aswathyseb** [comment]
Thank you, when I right clicked on the VCF track and selected  "Show Genotypes" it showed up.

I saved it again, but when I opened the session after that it is not showing up.I will have to right click and select "Show Genotype" option every time I open the session even though it is saved as "Show Genotype=true" in .xml file.

Here is how the track is given in .xml

`<Track attributeKey="PLD.vcf.gz" clazz="org.broad.igv.variant.VariantTrack" colorScale="ContinuousColorScale;0.0;13.0;255,255,255;0,0,178" displayMode="EXPANDED" fontSize="10" groupByStrand="false" id="~/work/test/PLD.vcf.gz" name="PLD.vcf.gz" showGenotypes="true" siteColorMode="ALLELE_FREQUENCY" squishedHeight="1" visible="true"/>`

Thanks,

**Comment by helgathorv** [comment]
I think you found a bug. Try removing the _showGenotypes="true"_ from the session file. Looks like the track is not respecting the "showGenotypes" value when specified in a session file. However, the default is "true", so if you remove it from the session file altogether, then they should be visible when you load the session. Let me know if that works for you.
