### ISSUE TITLE
Global and user specific preferences file

### ISSUE THREAD

**Issue by fgvieira** [igvteam/igv#1137]
Dear all,

I've installed `IGV` on a shared server with several users and setup a common folder with all `IGV` files (genomes, global `prefs.properties` file, logs, etc...). When each user starts `IGV`, it is launched with the `--igvDirectory` option pointing to that common folder.

However, some users would like to tweak (and save) their own preferences. Is it possible to have a global preferences file in a common folder and a user-specific one (e.g. in each users home folder)? The common prefs file is write-protected, so it is important that the users are able to save their preferences to their own local file.

thanks,

**Comment by jrobinso** [comment]
No that is not possible.

**Comment by fgvieira** [comment]
And is it possible to specify the path to `prefs.properties` from the command line?
I've tried using `--preferences` but any preference changes are not saved here.

**Comment by jrobinso** [comment]
The --preferences option is to override preferences for the current
session, as you've observed.   You can change the location of the "igv"
directory,  but not specific files within it (like prefs.properties).
IGV isn't designed for what you are tying to do, it's a desktop application
and is assumed that users are running as themselves on their personal
machine.
