### ISSUE TITLE
java: symbol lookup error: /lib64/libgtk-3.so.0: undefined symbol: g_log_structured_standard

### ISSUE THREAD

**Issue by yifnzhao** [igvteam/igv#1142]
Hi, I was trying to load files in IGV using remote server. I downloaded command line IGV from [here](https://data.broadinstitute.org/igv/projects/downloads/2.13/IGV_2.13.0.zip). The GUI looks fine, and loading data from external servers (e.g., 1000G, TCGA) also works well. Below is the error message when running ```bash igv.sh``` and trying to use "File > Load from File..." option:
```
Using system JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
java version "11.0.11" 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)
INFO [May 20,2022 13:40] [Globals] Development mode is enabled
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
INFO [May 20,2022 13:40] [Main] Startup  IGV Version 2.13.0 05/16/2022 11:36 AM
INFO [May 20,2022 13:40] [Main] Java 11.0.11 (build 11.0.11+9-LTS-194) 2021-04-20
INFO [May 20,2022 13:40] [Main] Java Vendor: Oracle Corporation https://openjdk.java.net/
INFO [May 20,2022 13:40] [Main] JVM: Java HotSpot(TM) 64-Bit Server VM 18.9
INFO [May 20,2022 13:40] [Main] OS: Linux 3.10.0-1160.45.1.el7.x86_64 amd64
INFO [May 20,2022 13:40] [Main] IGV Directory: /home/yiz188/igv
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
INFO [May 20,2022 13:40] [CommandListener] Listening on port 60151
INFO [May 20,2022 13:40] [GenomeManager] Loading genome: https://s3.amazonaws.com/igv.org.genomes/hg19/hg19.json
INFO [May 20,2022 13:40] [TrackLoader] Loading resource:  https://s3.amazonaws.com/igv.org.genomes/hg19/ncbiRefSeq.sorted.txt.gz
java: symbol lookup error: /lib64/libgtk-3.so.0: undefined symbol: g_log_structured_standard
```
Thanks in advance for your help!

**Comment by jrobinso** [comment]
I'm confused when you say "The GUI looks fine", if its working fine what exactly is the question?

**Comment by yifnzhao** [comment]
Hi sorry about the confusion. I meant that I was able to load the GUI from remote server, which looks like this:
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/44952562/169588870-7e5b7358-b498-4a39-9927-443fb2035cf6.png">

However, when I tried to load alignment files, the program immediately exits and reports ```java: symbol lookup error: /lib64/libgtk-3.so.0: undefined symbol: g_log_structured_standard```

**Comment by jrobinso** [comment]
Ok, well I'm not a linux expert but it looks like you are missing a library that Java requires.

**Comment by yifnzhao** [comment]
Okay thanks. I will look more into it.
