### ISSUE TITLE
the color of homozygous SNP from vcf

### ISSUE THREAD

**Issue by charliechen912ilovbash** [igvteam/igv#1145]
Hi,
I am wondering about what is the difference between the red/blue SNP showing in igv when imported variant from .vcf.

In the manual:
blue - minor allele frequency/fraction is known from annotation or genotype data
red - height is proportional to minor allele frequency

Could you explain a little bit more? Like what does 'height is proportional' means?

Thanks

**Comment by charliechen912ilovbash** [comment]
where the blue homozygous SNP allele frequency is -1.0, the red homozygous SNP allele frequency is 1.0.
I guess the blue means there is no SNP here?

**Comment by charliechen912ilovbash** [comment]
![截圖 2022-05-27 上午6 28 10](https://user-images.githubusercontent.com/54789400/170583204-10f30e07-2d7a-456f-9bb2-7fdb7b9e3a5f.png)

**Comment by jrobinso** [comment]
I'm not sure I understand your picture, but there is a distinction between the variant and the optional genotypes.  Not all VCFs even have genotypes.    The variant band, which is not associated with any specific sample,  is colored blue & red where the % of the bar that is red is proportional to the allele frequency or allele fraction depending on the option selected through the menu.   Genotypes do not have allele fractions of course, they are individual calls, and have their own color scheme,  homozygous reference = grey, homozygous variant = cyan,  heterozygous = blue.

If you have a single genotype and choose to color by allele fraction the associated variants are going to always be blue or red, because the minor allele fraction will of course be always 0% or 100%.   Its not a meaningful color scheme choice in that case.

Apologies for the documentation, I don't understand it myself to be honest.  We will take care of that.

**Comment by charliechen912ilovbash** [comment]
It is colored by allele frequency.

**Comment by charliechen912ilovbash** [comment]
![截圖 2022-05-27 上午10 32 40](https://user-images.githubusercontent.com/54789400/170610728-e4521afc-3d73-45db-81b2-69f86a2dc885.png)

In the vcf file, the allele frequency (AF) are 1, 0.8636, 1. In the IGV, the  allele frequency it showed are 1.0, -1.0, 1.0 and color as red, dark blue, red (collapse) or red + cyan , dark blue + cyan , red + cyan (expand).

**Comment by jrobinso** [comment]
I don't understand your question, if there is a question, about the colors.   It would be helpful if we could discuss the color of the variants and genotypes separately, as they are not related.   Allele frequency has no impact on genotype coloring.  I can't make any sense of the screenshot.

WRT discrepancy in allele frequency,  that could indicate a bug in the "htsjdk",  but to confirm we would need a test case.  Could you zip and attach a small VCF file illustrating this problem.

**Comment by jrobinso** [comment]
I need a complete VCF, not just a few lines with variants.

**Comment by jrobinso** [comment]
Also, the IGV version you are running, as you didn't say I am assuming its the latest.

**Comment by charliechen912ilovbash** [comment]
I am using version 2.12.3.

**Comment by jrobinso** [comment]
OK, that's fairly recent.  When I get a sample VCF from you I will investigate further and possibly open an issue with the htsjdk, which is used for vcf parsing.

**Comment by charliechen912ilovbash** [comment]
Thank you very much, previously I have some misunderstanding about the basic concept of SNP color in IGV. I understood the genotype color meaning now.
and previously I did not merge the vcf files, I imported three vcf in expanded mode display instead, so it may look weird.

Now I have one question about the variant part, what is the difference between 'allele frequency' and 'allele fraction'?

**Comment by jrobinso** [comment]
Allele frequency is a field in the VCF file.   Allele fraction is computed from the genotypes in the VCF file, if genotypes are present, it is not an interesting calculation unless you have many genotypes.

**Comment by charliechen912ilovbash** [comment]
I understood, thank you very much !

I still have some questions about the definition of some terminologies and coloring of variants:
1.  In the first picture, the percentage of ALT nucleotide C is 61%, but the allele frequency shows 0.5, does it shows 0.5 if the ALT percentage is closed to 0.5, and shows 1.0 when the ALT percentage is closed to 1.0 ?
2. In the first picture, what is the difference between the two allele frequencies circled by red rectangles?
3. In the second picture, this is a heterozygous SNP, but how come the variant part is colored all blue? I thought it would be colored as red + blue like the SNP in the first picture.

![igv](https://user-images.githubusercontent.com/54789400/170850732-d2423234-6f02-46b9-82c4-bad9e7f90987.png)
![截圖 2022-05-29 下午12 15 57](https://user-images.githubusercontent.com/54789400/170850739-16af96d4-b00f-4684-9bf8-8db6bc914ee8.png)

**Comment by jrobinso** [comment]
I would suggest you familiarize yourself in detail with the VCF specification as well as the BAM file specification, and the process of calling snps and creating VCFs.   This is not the right forum for those sorts of questions.    In general IGV is just presenting to you what is in the files,  I am not going to try to interpret that.

The red/blue coloring of a variant is controlled by allele frequency, or allele fraction if that is selected.   It has nothing to do with whether a particular genotype is heterozygous or not.   A careful study of the VCF specification should make this clear.   In your last picture you are asking about the relationship between a BAM file and a VCF, that is out of scope here, from IGV's point of view there is not relationship whatsoever.   I suggest you ask these sorts of questions in a more general forum.
