### ISSUE TITLE
Getting prepared for OpenJDK 17

### ISSUE THREAD

**Issue by pgrt** [igvteam/igv#1147]
Hello,

I am the Debian maintainer of igv; in Debian we will soon (?) have OpenJDK 17 as default instead of OpenJDK 11.

The good news is igv is ready for it. I just had to apply the enclosed patch as the no-argument constructor of URLDecoder becomes private in OpenJDK 17. Anyway, the decode() method is static.

[no_instantiation_of_URLDecoder.txt](https://github.com/igvteam/igv/files/8809052/no_instantiation_of_URLDecoder.txt)

Best wishes,
Pierre

**Comment by jrobinso** [comment]
That's good to know, thanks for the patch.
