### ISSUE TITLE
IGV Jar Binary File Latest Version

### ISSUE THREAD

**Issue by abiraaaaaaf** [igvteam/igv#1149]
Hi. I'm using IGV binary file version 2.4.10 and between my reads, there are gray areas which it does not happen in the latest versions. The IGV binary jar file has not been released after 2.4.10. What should I do?
I'm trying to generate the snapshots automatically and need the binary version.

**Comment by jrobinso** [comment]
Did you look at our downloads page?  There is a link to archived versions there https://data.broadinstitute.org/igv/projects/downloads/

**Comment by abiraaaaaaf** [comment]
Yes, I have checked the archived versions and I'm looking for such a file like this: https://data.broadinstitute.org/igv/projects/downloads/2.4/IGVSource_2.4.10.zip
And the IGVSource has not been released after this version.

**Comment by abiraaaaaaf** [comment]
I want to use this binary file in such a way:
igv_command = f"xvfb-run --auto-servernum --server-num=1 java -Xmx{memMB}m -jar {igv_jar} -b

**Comment by jrobinso** [comment]
IGV source is available for all versions, I'm not sure what you mean,  that's what this repository is.    Prebuilt packages are available for all versions in the link above.

**Comment by abiraaaaaaf** [comment]
Sorry for asking again. Look in IGVSource 2.4.10 when we extract it, we have these files:
![image](https://user-images.githubusercontent.com/38458092/171791268-3f839623-7857-4b72-a789-545deee0c41f.png)

But in all the next versions the content of the IGV is like this:
![image](https://user-images.githubusercontent.com/38458092/171791438-11aa01c9-dcb3-4aef-ba0c-bd66d8b279e7.png)

Which does not contain an igv.jar file.  (Although there is one igv.jar in the lib subdirectory but is not what we want since it errors running the command below)
I need the igv.jar file directly to use this command:
f"xvfb-run --auto-servernum --server-num=1 java -Xmx8000m -jar igv.jar -b file.bat

**Comment by jrobinso** [comment]
No, of course source code will not contain an "igv.jar" file,  you need to build it.    You should not be looking at source packages unless you intend to build the package yourself.   The packages without "Source" in the name are prebuilt, and all have readme files with command line instructions.

We don't know anything about or provide any support for xvfb, BTW.

**Comment by abiraaaaaaf** [comment]
Can you guide me on how to build it? Many thanks in advance.

**Comment by jrobinso** [comment]
Please read the readme.
