### ISSUE TITLE
impossible to open a cram file

### ISSUE THREAD

**Issue by quentin67100** [igvteam/igv#1156]
I have a cram of a human genome (reference = hg38). 
If i open the cram with igv no problem

Then i split the cram file by chromosome with samtools: 

```
samtools view \
-C -h \
-@ ${SLURM_CPUS_PER_TASK} \
-T ${reference_genome} \
--output ${cram_dir}/${chromosome}.${biosample}.cram \
${cram_dir}/full/${biosample}.cram \
${chromosome}
```

If i open for example the chromosome 1 it works, but with the chromosome Y i get the error: 
```
SEVERE [juin 13,2022 13:44] [LongRunningTask] Exception running task
SEVERE [juin 13,2022 13:44] [LongRunningTask] org.broad.igv.exceptions.DataLoadException: Reference MD5 failed to validate against 72462f4264e257ea77db6a016e20ced1
	at org.igv/org.broad.igv.track.TrackLoader.load(TrackLoader.java:269)
	at org.igv/org.broad.igv.ui.IGV.load(IGV.java:1250)
	at org.igv/org.broad.igv.ui.IGV.lambda$load$5(IGV.java:1282)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I specify that I used the same command on other crams (the crams having been generated in the same way by the same pipeline) without any particular problem when opening with igv

To add more information :

I partially solved the problem: 

I convert the cram to bam file and then i convert back to cram but with to different reference genome: 

- One from the google cloud ressource bundle of the broad ([here ](https://console.cloud.google.com/storage/browser/_details/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta;tab=live_object)) : Again it's not possible to open this cram with igv
- One used by igv from the s3 bucket of the broad ([here](https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa)) : In this case it's work

I don't understand why the reference genome from google cloud of broad works well with some cram and not with others...

**Comment by jrobinso** [comment]
That's because some crams were aligned against that reference and others weren't.     You must use the exact reference sequence that CRAM was aligned against.  The available hg38 / GRch38 fastas have small differences,   mostly in the use of "N" for some regions.  So your CRAM might mostly work but fail at certain loci.

**Comment by jrobinso** [comment]
Can you use "samtools view" with the chr Y file?
