### ISSUE TITLE
Specify color scale when coloring alignments by tag

### ISSUE THREAD

**Issue by mdshw5** [igvteam/igv#116]
![screen shot 2015-03-06 at 4 30 54 pm](https://cloud.githubusercontent.com/assets/819554/6536749/343ed3dc-c41e-11e4-8f22-9a64a4c8cf7a.png)

The alignments shown above are colored using a tag encoding an integer, with values on a continuous scale. Bet you couldn't tell from looking.

It seems like the current "color alignments > by tag" color scale is useful for categorical data only. Could we implement a continuous color scale? You could allow the user to set a bound on the data range for the scale using the "View > Color Scale" selector.

**Comment by jrobinso** [comment]
Yes, but its just complicated enough to not quite make it to the top of 
my stack.   Reply occasionally to bump it up.   Probably won't get to it 
this month.
