### ISSUE TITLE
IGV: no update check

### ISSUE THREAD

**Issue by marc-sturm** [igvteam/igv#1161]
Hi,

when there is a new version, we get a notice like this:
![grafik](https://user-images.githubusercontent.com/5638144/175501070-30db3a17-e93f-4a0a-9ae9-8833c2c60948.png)
 

Is there a way to suppress checking for updates via a command line option?

In general, could not find the documentation of command line options for IGV anymore.
Could you point me to the documentation please.

Thanks,
  Marc

**Comment by jrobinso** [comment]
No there is no such option,  command line options are here:  https://github.com/igvteam/igv/wiki/Command-Line

**Comment by marc-sturm** [comment]
Thanks!

**Comment by jrobinso** [comment]
I think we'll just remove that check next release.

**Comment by marc-sturm** [comment]
That would be good for us, we update it manually because it's on a shared drive for all users...
