### ISSUE TITLE
IGV performance gradually degrades

### ISSUE THREAD

**Issue by hidtak** [igvteam/igv#1166]
Thanks for the high-performance viewer!

I'm running IGV in batch mode for whole-genome loci following the script.
  xvfb-run --auto-servernum igv.sh -b script.bat

IGV performance gradually degrades. Are there any plans for improvement?

I save my script.bat separated by chromosome, such as script_chr1.bat, script_chr2.bat, script_chr3.bat. So they will run in parallel.

**Comment by jrobinso** [comment]
This is much too vague to take any action on.
