### ISSUE TITLE
Regression: Missing/black chromosome name in batch mode using MATE_CHROMOSOME grouping since 2.12.0

### ISSUE THREAD

**Issue by cbrueffer** [igvteam/igv#1172]
First of all, thanks for all your work on this software!

Working version: up to and including 2.11.9
Broken version: from 2.12.0 to latest (2.13.2 as of now)

I'm using IGV in batch mode and headless using xvfb-run with option SAM.GROUP_OPTION=MATE_CHROMOSOME. This should show the chromosome name in each "read group" in the top-left corner of each grouping. In batch mode this worked up to and including version 2.11.9. Since version 2.12.0, including the latest 2.13.2, only a black box is being printed.

Environment:
- IGV installed via Bioconda
- OpenJDK 11.0.15

The first (working) screenshot is from 2.11.9, the second (broken) from 2.12.0. Config, batch file etc are the same.
![SV-2 11 9-working](https://user-images.githubusercontent.com/2705287/178750341-69774681-40ea-49eb-9c78-3cb1b3bc87ff.png)

![SV-2 12 0-broken](https://user-images.githubusercontent.com/2705287/178750370-360d4a96-6583-4202-9b8a-e79c35b4ac7a.png)

**Comment by jrobinso** [comment]
Could you provide a test script, it's o.k. if the bam file isn't reachable I'll substitute another.

**Comment by jrobinso** [comment]
@cbrueffer ignore test request, I can reproduce it.    

Tangentially, I don't recall why we paint group labels (chromosome names in this case) with black background / white text,  I think they should look as they do on screen.

**Comment by cbrueffer** [comment]
Glad to hear it, I was just putting the files together.

I was wondering the same, at first I thought it was an Xvfb artifact.
