### ISSUE TITLE
IGV not showing deletions

### ISSUE THREAD

**Issue by elcortegano** [igvteam/igv#1175]
I'm finding a problem where some 1bp deletions are being called in a VCF (e.g. by deepvariant), and IGV will only show the total or partial drop in the coverage track, but not the deletion itself in the reads (see example below for an heterozygous deletion). Why this happen?

![Screenshot_20220728_100209](https://user-images.githubusercontent.com/57492899/181468650-1fe345c4-732d-4b9d-9037-4dc8325c2ccc.png)

I have tried changing settings like soft-clipping and others in the Alignment tab, but no luck. Tried also with alignments generated by different software (ngmlr and winnowmap2). The call and the drop in coverage remains, but not the deletion itself in the reads. IGV version is 2.13.2.

**Comment by jrobinso** [comment]
Do you have "hide indels < show indel threshold" enabled in the alignment
preferences?

I this is 3rd gen data indels < 2 bases are hidden by default,  you can
override this in the "3rd gen" preferences tab.    This setting is also
available for short read alignments ("Alignments tab") but is off by
default.  Right-click over the alignments and select "Experiment Type" to
see what type read experiment IGV thinks this is.

Jim

[image: Screen Shot 2022-07-28 at 10.55.50 AM.png]

**Comment by elcortegano** [comment]
I see, this was using 3rd gen data (PacBio HiFi) and I can now clearly see the indels after making changes in the "3rd gen" preferences tab. Thank you very much for the feedback!

**Comment by jrobinso** [comment]
@amwenger Is it time to revisit these defaults?  Technology has moved on a bit since we first set them.

**Comment by amwenger** [comment]
> Is it time to revisit these defaults? Technology has moved on a bit since we first set them.

Long-read sequencing does look much different now than in 2016, and considering a change in default is a good idea. Perhaps we could eliminate the separate third-gen options altogether and use the same settings for all alignment tracks.  

To make the new default work best, I think it would be nice to minimize the visual impact of small insertion errors in large window views (>20 kb). The purple mark for insertion errors dominates visually disproportionately to deletion errors. A few ideas:
* Hide 1 bp indels at the same zoom level where substitutions are hidden.  Still show >1bp indels.
* Collapse the insertion mark to a single pixel wide when zoomed out far.

@jrobinso - What do you think?

Here is https://downloads.pacbcloud.com/public/dataset/HG002-CpG-methylation-202202/HG002.GRCh38.haplotagged.bam with no indel filtering
<img width="969" alt="image" src="https://user-images.githubusercontent.com/7155109/184574409-3ea02bc9-677e-486e-a7dd-eed1aa827952.png">

And 1 bp indels hidden
<img width="969" alt="image" src="https://user-images.githubusercontent.com/7155109/184574504-d5a02f43-c0fc-435e-9940-419aa6a1dee1.png">
