### ISSUE TITLE
Feature request - color duplicate reads

### ISSUE THREAD

**Issue by joegeorgeson** [igvteam/igv#1177]
Dear IGV team,

I would love to be able to color duplicate reads (PCR, optical, or both). I found that [this was asked on the google group](https://groups.google.com/g/igv-help/c/-fcURpZ0_zY/m/dwj1VCXyAQAJ) but did not find an open issue here, so I'm posting now. 

Thanks!
Joe

**Comment by jrobinso** [comment]
@joegeorgeson So to be precise that would color reads according to the SAM flag for "duplicate read"?  I don't think that flag distinguishes between duplicate types.   These are not shown at all by default, perhaps when they are shown they could be flagged in some way, as we do "zero mapping quality" reads now.

**Comment by joegeorgeson** [comment]
I actually now realize that one can simple color by a tag of 'nM' and this more or less accomplishes the task. While it might be more convenient for a user to select 'color by duplicate' I have a solution for my issue....thanks!

> I don't think that flag distinguishes between duplicate types. 

Right, so maybe ignore this part of the request - when duplicates are marked, you _could_ specify different tags based on the duplicate type, but this complicates things.

> These are not shown at all by default, perhaps when they are shown they could be flagged in some way, as we do "zero mapping quality" reads now.

I understood that one read of all the duplicates is shown, and I was hoping to color this read (one read representing all duplicates) to distinguish them from non-duplicated reads. It would be very convenient to have this as a pull-down option for 'Group/Sort/Color alignments by' if you can support.

**Comment by jrobinso** [comment]
RE the tags,  you should be able to color by any tag,  e.g. "Color alignments by > tag -> <dialog box>, type in SQ".   What you can't do, currently, is color by 2 tags at once (SQ and LB).

**Comment by joegeorgeson** [comment]
Thank you very much Jim, I figured out everything I wanted.
