### ISSUE TITLE
Sort by Aligned Read Length

### ISSUE THREAD

**Issue by akkadadam** [igvteam/igv#1184]
This sort by aligned read length does not seem to be working. Please see image below
![image](https://user-images.githubusercontent.com/50845595/184171388-688c2d79-22a1-4d6a-af9b-87e4eb065273.png)

I am not sure if this is something on my end or not but any advice would be very helpful. Thank you in advance!

**Comment by akkadadam** [comment]
I am using 2.14.0. Thank you for the tip, I did not have the center line showing which is why the sorting did not work. However, in our case we are looking at polycistronic cassettes so sorting based on intersecting alignments does not sort all reads since the are multiple cassettes that are not all on the same strand.

**Comment by jrobinso** [comment]
I'm not sure what a "cassette" is,  but strand does not matter with respect to sorting,  strictly speaking it is sorting the rows of alignments based on the alignment in each row that intersects the center line.    Alignments are not repacked during a sort, they remain in the same row as before,  its the rows themselves that are sorted.   Rows that have no alignment intersecting the center line will be at the bottom.

**Comment by lbergelson** [comment]
@akkadadam Do you know how your data is stored in the bam file?  If the separate cassettes are separate reads in a bam then this sort won't sort them together.   Are they linked by mate entries like paired end reads are?

**Comment by jrobinso** [comment]
@akkadadam @lbergelson I'm not sure what to do with this without clarification or a test case we can run.     Again sorting sorts the rows of packed alignments based on the value of the selected alignment intersecting the center line.   I can't find any case where sort by aligned read length fails to do this.    Feel free to reopen if you can provide a test case.
