### ISSUE TITLE
How to load a local bed file as track in a web app

### ISSUE THREAD

**Issue by BrightHQZ** [igvteam/igv#1191]
Hi @jrobinso , I make a local web app using javascript but can't load the local bed file as a track. The error is "Error accessing resource: file:///.....". The file exists and the path is right. My script is at following.

 const options =
            {
                genome: "hg19",
                showSampleNames: true,
                tracks: [
                    {
                        name: "DosageMapping",
                        type: "annotation",
                        format: "bed",
                        samples: ["a"],
                        url: "file:///Users/xxxxx/Desktop/HPOMatch/annotationData/test.bed",
                        indexed: false
                    },
                ]
            }

Could you provide some suggestions to deal with the problem? Thanks a lot.

**Comment by malcook** [comment]
Not Jim here, but, did you confirm the URL loads the .bed file when (a) pasted into a browser (b) “downloaded” with wget or curl?

**Comment by BrightHQZ** [comment]
Yes, the file could be opened by pasting the location into a browser directly. 
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/33643825/184687833-b77c4db7-8fe7-4d75-b026-59db06e58116.png">

**Comment by jrobinso** [comment]
You can't use file:// urls with web apps.   It would be a massive security hole if this were allowed.
