### ISSUE TITLE
Add an indicator on the zoom options to show which levels display reads

### ISSUE THREAD

**Issue by lbergelson** [igvteam/igv#1192]
It would be useful if the zoom bar had a visual indicator to show which zoom levels display individual reads.

Something like this maybe:

<img width="260" alt="Screen Shot 2022-08-15 at 5 25 37 PM" src="https://user-images.githubusercontent.com/4700332/184721827-ae514461-27e4-42e0-8b5c-2e6d415acfb3.png">

**Comment by jrobinso** [comment]
Its difficult to do this since, with the exception of alignment tracks,  each track can have a different visibility window.   Its a good idea,  but we need to figure out how to handle the case of multiple tracks.
