### ISSUE TITLE
Unable to launch jnlp file in igv

### ISSUE THREAD

**Issue by dhwani2410** [igvteam/igv#1218]
<img width="562" alt="Screenshot 2022-09-13 at 12 11 32 PM" src="https://user-images.githubusercontent.com/30225789/189829165-41a1dbb2-f00f-4037-814b-36d5be568c73.png">

I am not able to launch the application from the .jnlp file. However, if i just open IGV, i can do that in my system

**Comment by jrobinso** [comment]
That's a question for Ion Torrent, not the IGV project.  They forked IGV many years ago, what you are displaying there is not our product.
