### ISSUE TITLE
TDF - Time Series Wind Data

### ISSUE THREAD

**Issue by ktillett88** [igvteam/igv#1222]
Hi,

I'm looking to understand more about this file format and how I can convert it to a excel .csv. I've been directed that the IGV software can export it. It has been exported from a remote sensing device that captures time series wind data.

**Comment by jrobinso** [comment]
This is a special format specifically designed for display of genomic data in IGV.   It is described here:  https://github.com/igvteam/igv/wiki/TDF-Format.   There is no converter to .csv format.

**Comment by jrobinso** [comment]
Also, BTW,  I kind of doubt these files are created by any software other than IGV, and it wasn't designed for time series wind data, perhaps that is a different format with the same extension (.tdf).

**Comment by ktillett88** [comment]
Cheers for the information Jim, the user manuals reference it as a triton data file which is the name of the remote sensing device which is likely just a different file format with the same extension. It would seem I have reached a dead end with cracking this file. Thanks again for confirming

**Comment by jrobinso** [comment]
Yes that is something else, the "tdf" here stands for "tiled data format"
