### ISSUE TITLE
wrong region display for mut file 

### ISSUE THREAD

**Issue by hiroshisuga** [igvteam/igv#1226]
When a .mut file is imported, a region starts one nucleotide later. No problem when displaying a single nucleotide.

![igv_snapsho2t png](https://user-images.githubusercontent.com/45039819/193173367-5cce9fb4-dffc-4f87-b17b-b79a33498a05.png)

**Comment by jrobinso** [comment]
Sorry, but I don't understand what you are saying.  What does the red box you have drawn signify?   And what do you mean by "no problem when displaying a single nucleotide?  I don't see any "mut" file tracks in your screenshot.

**Comment by jrobinso** [comment]
I think I have an idea.  The "mut" file format does not really have a specification, and the coordinate system was never formally defined as far as I know.   Some early TCGA "mut" files used the UCSC "0-start, half open" system.   Other producers of "mut" files have used "1-start fully closed" system.   As IGV started as a TCGA project it assumes the "0-start, half open" convention unless it can be proven that the 1-start system is in use.   With single nucleotide variants this is easy,  if start == end we know the 1-start system is in use.  For variants with size > 1 it is not possible to determine, so currently 0-start, half open is assumed.

Changing now could be difficult as this has been the convention for > 12 years.   I need to survey existing repositories we use for ".mut" files and try to determine what system they are using.  

I am curious, where did you obtain ".mut" files,  that is what repository or software has produced them?  This format has been deprecated for 10 years or so,  the successor format was ["maf"](https://docs.gdc.cancer.gov/Encyclopedia/pages/Mutation_Annotation_Format_TCGAv2/), which in turn was deprecated in favor of "vcf".

**Comment by hiroshisuga** [comment]
Thanks for the investigation. I understand you need to be careful to change what has been there for 12 years.;-) However, I have to say the current implementation is not very intuitive to me. What is most problematic is the numbering is not the same as the other windows of igv. 

For instance, if you specify two nucleotides like "10 11", you will have a red square only at the position 11. 

BTW I made the mut file manually by myself. I am using it for showing polymorphisms.

**Comment by jrobinso** [comment]
Yes that makes sense,  (10,11)  is a single base in the UCSC system.   This is used for many file formats, including all formats from UCSC (such as BED).   The first base in that system is (0,1).

**Comment by jrobinso** [comment]
I can't find any extant ".mut" files in any repository, I think they have all been replaced by "maf" and "vcf" files.   In fact I can't find any description of the "mut" format other than our own documentation.   I'm curious why you chose this format, and where you found a specification for it.    

So I think it should be safe to use the "1-start fully closed" coordinate system for ".mut" files,  I will change this for the next release.

**Comment by hiroshisuga** [comment]
Thanks @jrobinso, I have confirmed that it's fixed in the nightly build. 
I do not have any special reason why I chose .mut format. I just thought, based on the suffix, it's ideal to manually mark assembly errors (and indeed it is, given it's relatively simple grammar). And yes, I can only find the specification of this format in your website.

**Comment by jrobinso** [comment]
This change is released in 2.15.1

**Comment by clintval** [comment]
@jrobinso would you be open to reversing this decision?

We at @twinstrandbio are using the MUT file for customer-friendly representations of variant calls and have quite an embedded data ecosystem using them as IGV had originally specified them (0-based, fully closed). The change in 2.15.1 represents a regression for all users of our software. Perhaps we could get on a call to discuss the impact of this decision?

**Comment by mjhipp** [comment]
This comment makes a great point about making a breaking change to this behavior after 12 years 🤔

https://github.com/igvteam/igv/issues/1226#issuecomment-1263109557

**Comment by hiroshisuga** [comment]
The good part of this change is it's more intuitive than before.
I would be happier if this change is moved to an optional setting, instead of completely removing it. 
Also, we may want to re-define the mut file format (AFAIK it is used only in IGV).

**Comment by jrobinso** [comment]
@clintval I wasn't aware we specified this before, and the few 'mut' files produced during the TCGA project (from which this format came) I could find are 1-based.    The successor to this format, MAF, is 1-based.   So I just thought this was an igv bug.   However point taken, if it was a bug people have built systems around it should be left alone.

I will revert this to 0-based by default, with an option to specify 1-based based on history.   If anyone has any pointer to any specification for this format.

@hiroshisuga intuitiveness is in the eye of the beholder,  I find the UCSC coordinate system perfectly intuitive.   Both are widely used.

**Comment by clintval** [comment]
You can keep this change from your commit if you want. (it doesn't affect me)

https://github.com/igvteam/igv/commit/9d9d65d70e5a17e912300c55333f8877a30542fb#diff-6c54b41397181df1ffca34684e9fc7e218c3b3e0bbadf80f06fb9f6082fde86bL181-L186

It's this line I prefer we revert so that MUT stays 0-based, half-open:

https://github.com/igvteam/igv/commit/9d9d65d70e5a17e912300c55333f8877a30542fb#diff-6c54b41397181df1ffca34684e9fc7e218c3b3e0bbadf80f06fb9f6082fde86bR156

We have a "TwinStrand-flavored" MUT specification that I could share, but a base specification that IGV supports would be a good addition, perhaps managed by hts-specs. I'll take this as a lesson to advocate and put energy into maintaining public standards!

**Comment by clintval** [comment]
@jrobinso would you also be willing to add back the MUT page in IGV docs?

It used to be here:

- https://software.broadinstitute.org/software/igv/MUT

**Comment by clintval** [comment]
Would you like us to make PRs?

**Comment by jrobinso** [comment]
@clintval Thanks but I can do this,  we have a convention for specifying coordinate system I just have to find it.    

We support "mut" in igv.js also, but it is 1-based arggg.   That's not quite 12 years old, probably 7.  I think I'm just going to have to live with this contradiction.     The 1-based is consistent with MAF, which uses the same parser as MUT in igv.js.

**Comment by jrobinso** [comment]
@clintval as far as docs,  this is an officially deprecated format of the TCGA project, AFAIK.  I don't think we want to promote it from here, and be responsible for the specification.   I just don't have time for that.   The page you reference was written when this was an active TCGA format, and was more of a description of current practice than a spec.     

The goal here is just maintaining backward compatibility, especially now that I am aware these files exist.

If someone wants to resurrect this format, so-to-speak, with a specification that is maintained somewhere that's great, we'll reference it.

**Comment by jrobinso** [comment]
WRT specifying coordinates, necessary as we have extant files using both conventions,  IGV has 2 conventions in use already.  This will be extended to "mut" files

(1) a coords directive

```
#coords=0|1
```

(2) a coords property in a track line, for formats that support track lines

**Comment by jrobinso** [comment]
As discussed above, in the upcoming 2.15.3 release the default coordinate convention for "mut" files will be reverted to UCSC style "0" coordinates.   There are 2 options for overriding this default

(1) A new user preference under the "Mutations" tab.  This preference is stored in prefs.properties with the key "MUT_COORDS", for example

```
MUT_COORDS=1
```

(2) A new "#coords" directive is supported for "mut" files with legal values of 0 and 1.   For example

```
#coords=1
chr	start	end	patient	type	gene	phase	center	shared	strand	site	supertype	context	class	newbase	status	validation	call	evidence	filtered	use	hypermutated
1	2072180	2072180	TCGA-06-0206	Missense	PRKCZ	1	BCM	No	+	PRKCZ|chr1:2072180-2072180	Missense	cgggcGcggga	G (CpG)	A	Somatic	Valid	Somatic	Validated	OK	Use_nonsilent	Non-hypermutated
1	2106249	2106249	TCGA-02-0083	Missense	PRKCZ	1	BCM	No	+	PRKCZ|chr1:2106249-2106249	Missense	agtcaGagttc	G (GpA)	A	Somatic	Valid	Somatic	Validated	OK	Use_nonsilent	Hypermutated
```
