### ISSUE TITLE
`Tracks > Overlay Data Tracks ` doesn't overlay bigbed files.  

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#1230]
I tried to `Overlay Tracks By > Data Type` and `... by None` and found that neither had any effect.
I would expect this to be possible.
Am I mistaken in my observation, or my expectation?

**Comment by jrobinso** [comment]
That is expected, "bigbed" is not a data track (in the parlance of IGV its a feature track).

**Comment by malcook** [comment]
thanks - I have learned how to concatenate my bigBeds outside of IGV.  Case closed.
