### ISSUE TITLE
can it be made possible to programmatically `set feature label field` for bigBed files?

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#1231]
It would suffice for my use case if providing a header of `##displayName="myCustomField"` on the bed from which a bigBed was crafted (using Jim Kent's bedToBigBed)  would serve to initialize the bigBed display in IGV to use myCustomField as the default feature label field.  I have not check - perhaps this already works "out of the box" - should it?  Or perhpas some annotation in the AutoSql file used (though I don't see how this should be possible in this case).

**Comment by jrobinso** [comment]
Are the # comments preserved in a bigBed file?   I doubt it, if they are I don't know how to access them.  Try creating a bigbed file with the comment,  then convert back to bed and see if its preserved.

**Comment by malcook** [comment]
No, they are may not appear in a bed file being converted to bigBed.  This is documented in [How to make a bigBed file – Part 1](https://genome-blog.soe.ucsc.edu/blog/2021/08/03/how-make-a-bigbed-file-part-1/) we read " The first (step) would be to edit the file and remove the top track and browser lines, **_they will be used again at a later step after the bigBed is created_**" and later ". Go to the[ custom track page](https://genome.ucsc.edu/cgi-bin/hgCustom) and put in a track like the following, **_where you can use your track and browser lines again_**"

Confirmatory documentation is in [[https://genome.ucsc.edu/goldenPath/help/bigBed.html][bigBed Track Format]]: "If your BED file was originally a custom track, remove any existing "track" or "browser" lines from your BED file so that it contains only data. "

So, any such track/browser lines may optionally appear elsewhere when submitting a bigBed track to a session.

So my need can not be met with my suggested approach.

Further experimentation with IGV reveals that `set feature label field`  is easily applied to multiple selected tracks.  This is sufficient to my need, and I am closing this issue.  Thanks for you consideration.

**Comment by malcook** [comment]
No, they are may not appear in a bed file being converted to bigBed.  This is documented in [How to make a bigBed file – Part 1](https://genome-blog.soe.ucsc.edu/blog/2021/08/03/how-make-a-bigbed-file-part-1/) we read " The first (step) would be to edit the file and remove the top track and browser lines, **_they will be used again at a later step after the bigBed is created_**" and later ". Go to the[ custom track page](https://genome.ucsc.edu/cgi-bin/hgCustom) and put in a track like the following, **_where you can use your track and browser lines again_**"

Confirmatory documentation is in [bigBed Track Format](https://genome.ucsc.edu/goldenPath/help/bigBed.html): "If your BED file was originally a custom track, remove any existing "track" or "browser" lines from your BED file so that it contains only data. "

So, any such track/browser lines may optionally appear elsewhere when submitting a bigBed track to a session.

So. my need can not be met with my suggested approach.

Further experimentation with IGV reveals that `set feature label field`  is easily applied to multiple selected tracks.  This is sufficient to my need, and I am closing this issue.  Thanks for you consideration.
