### ISSUE TITLE
Save image as .eps outputs dark tracks

### ISSUE THREAD

**Issue by ghost** [igvteam/igv#125]
I've been trying to generate EPS images as described in the documentation (https://www.broadinstitute.org/software/igv/MenuBar). I installed the EPSGraphics Library as suggested into my "~/igv/plugins" directory, after which the option appears in the "File -> Save Image..." menu (as shown below).
![screen shot 2015-03-27 at 18 08 30](https://cloud.githubusercontent.com/assets/8597866/6863880/35c30102-d4ad-11e4-920e-1817c4adeedf.png)

However, when generating the image, the EPS one displays with no alignments and darkened tracks while the other formats display normally (as shown below). 
![screen shot 2015-03-27 at 18 11 14](https://cloud.githubusercontent.com/assets/8597866/6863908/b62d79a8-d4ad-11e4-9925-3509de698bed.png)

Any idea of what's going on?
For the record, I'm using LaTeX (compiling with latex) which requires images in .eps format. I can generate EPS screenshots using IGV's batch tool but not manually.
Thanks - Peter

**Comment by PeterDee** [comment]
Note that I'm using the newly released March 2015 IGV version (2.3.46).

**Comment by jrobinso** [comment]
What OS are you using?  We see this sometimes on Macs.   Try editing 
them in illustrator or another tool that can edit .eps and see if the 
dark regions can be removed.  They are possibly layered on top.

To confirm,  you can successfully create eps images from the batch 
command but not the save menu?  That is good information.  We have not 
so far been able to track down the origin of these dark overlays.

**Comment by PeterDee** [comment]
Hi Jim - thanks for your quick response.
I’m using OS X Mavericks (10.9.5).
Yes, I can successfully create eps images from the batch command i.e. generating the script with bedtools’ bedToIgv command with the -img eps option. This produces a script like the one below which works perfectly super duper well (tried with ~50 different regions in one go). 
```
snapshotDirectory /Users/me/Desktop/IGV/vars/
goto chr2:37368676-37368718
snapshot chr2_37368696_37368698_slop20.eps
goto chr2:37384034-37384085
snapshot chr2_37384054_37384065_slop20.eps
goto chr2:42488238-42488280

```

But it's of course less flexible than doing it manually when you want to print something as is. 
Thanks for the great work :-)

**Comment by jrobinso** [comment]
OK,  thanks for the info.   This might be difficult to fix,  but one 
possibility is to add a menu item that basically does what the batch 
command does.  If you look carefully you will see this is not a true 
"screenshot",  the individual panels are output separately without 
window artifacts such as scrollbars.

In the meantime, are you able to edit your images?  I think if you have 
a tool to "ungroup" them you will find the dark regions are just layered 
on top of the actual image and can be removed.   I have no idea what 
causes this, or why it only occurs on Macs.

Jim

**Comment by PeterDee** [comment]
I'll try to fiddle around with them in the next couple of days with Illustrator and I'll let you know if I get anywhere.
Cheers - Peter

**Comment by PeterDee** [comment]
Just to update: I managed to use Illustrator and remove the dark regions. I've noticed sometimes the sample labels are missing but that's not too much of a problem.
Thanks!
