### ISSUE TITLE
Cannot connect to the internet over a proxy server

### ISSUE THREAD

**Issue by ubuntolog** [igvteam/igv#1251]
Hello,

I have been testing IGV 2.15.1 from inside of our infrastructure and have encountered a problem with the proxy server. IGV cannot connect to the outside world. With the same proxy settings IGV 2.14.1 works fine and IGV 2.15.1 fails to reach any outside server. It seems like IGV cannot longer detect the system proxy. In the Preferences -> Proxy tab I have only proxy credentials, previously IGV (before 2.15.1) was able to detect the proxy host and port automatically:

![image](https://user-images.githubusercontent.com/5293569/199469390-62387cf4-8a87-4e78-a629-32b24974f508.png)

Connection times out while loading genomes
![image](https://user-images.githubusercontent.com/5293569/199471791-cb76d6a7-5171-4c9d-8d04-a8778889b3c5.png)

Even if I manually specify the host and port, it still fails to connect. 

If I have a server running locally on my development machine, IGV can connect to it (direct connection, without proxy).

I will keep debugging and let you know if there is something new. Thanks.

**Comment by jrobinso** [comment]
There were no changes affecting proxies for 2.15.   There were changes affecting oAuth,  are you trying to connect to an external Google, AWS, or other servers that might require oAuth authentication?

**Comment by ubuntolog** [comment]
> There were no changes affecting proxies for 2.15. There were changes affecting oAuth, are you trying to connect to an external Google, AWS, or other servers that might require oAuth authentication?

No, I am not using oAuth at the moment. I have simply replaced the old IGV with the new one and it stopped working with our proxy. However, the old version still can go through the proxy

**Comment by jrobinso** [comment]
OK I'll look into it.  I made need you to test some development builds as I'm not sure I will be able to reproduce this.

**Comment by ubuntolog** [comment]
Thanks. I will also keep trying to find out more.

**Comment by jrobinso** [comment]
I'm actually going to need to find or develop a test proxy server to debug this, hopefully I can.  Otherwise we might need to get your IT department involved,  they will be able to see the exact network traffic.   I'm working on it.

**Comment by jrobinso** [comment]
@ubuntolog I think I found the issue.  I think, but am not sure, and http request is made during IGV startup before proxy properties are set.   I need to confirm this and then recode the flow so this doesn't happen.    I should have a fix soon.

**Comment by ubuntolog** [comment]
Great, thank you!

**Comment by jrobinso** [comment]
I've pushed a possible fix which is available now for testing at https://software.broadinstitute.org/software/igv/download_snapshot.

This will be released early next week unless further problems are found.

**Comment by ubuntolog** [comment]
It worked! Thank you for such a quick fix.
