### ISSUE TITLE
Cursor guide function is broken in igv-2.13.5.js

### ISSUE THREAD

**Issue by ruzsaz** [igvteam/igv#1254]
The reason seems to be that the "igv-viewport-content" wrapper div has disappeared around the content in the "igv-viewport" classed divs, but the coordinate-detection code in the /js/ui/cursorGuide.js file still searches for it (line 63-67).

A possible solution is to change the lines 63-67 in /js/ui/cursorGuide.js from this:
```
                if (target.parentElement.classList.contains('igv-viewport-content')) {
                    viewport = target.parentElement.parentElement
                } else if (target.parentElement.classList.contains('igv-viewport') && target.classList.contains('igv-viewport-content')) {
                    viewport = target.parentElement
                }
```
to this:
```
            if (target.parentElement.classList.contains('igv-viewport')) {
              viewport = target.parentElement;
            } else if (target.classList.contains('igv-viewport')) {
              viewport = target;
            }
```
however, I don't know if it will break something else or not. At first glance it seems to be working, but I don't know the code enough to dare a pull request.

**Comment by jrobinso** [comment]
OK, thanks for the investigation,  that fix will work but I am going to see if we can re-code this to not depend on specific class names, which seems like a problem waiting to happen (which it has).

**Comment by jrobinso** [comment]
I've pushed a fix for this.  BTW this is an igv.js issue, not an igv issue.
