### ISSUE TITLE
How to change the track background color of IGV

### ISSUE THREAD

**Issue by zhoudreames** [igvteam/igv#1255]
Somehow IGV's default background is not white. When I take a screenshot from IGV and put it onto powerpoint, I can clearly see that IGV is kinda grey-ish. I was wondering if there is a simple toggle to make IGV display use white background (255, 255, 255), instead of 249, 249, 249
![image](https://user-images.githubusercontent.com/54714639/201623290-abb9ec70-76b5-4878-b10b-791d8fde9be0.png)
![image](https://user-images.githubusercontent.com/54714639/201623344-ea9b28c3-24af-425d-831d-ac93e760d93c.png)

**Comment by zhoudreames** [comment]
@etal @rmzelle @ssadedin @brainstorm I am so sorry to disturb you, can you help me ?

**Comment by ssadedin** [comment]
@zhoudreames have you tried setting the background color in preferences under General?

![image](https://user-images.githubusercontent.com/138868/201641338-17d5fb67-2290-4aa7-b891-520248ff5fac.png)

**Comment by jrobinso** [comment]
Thanks @zhoudreames that is what I would suggest.

This is interesting though because the default background color is (250, 250, 250).
