### ISSUE TITLE
Path in batch file containing a space cannot be read

### ISSUE THREAD

**Issue by micans** [igvteam/igv#1258]
A batch file like this:

```
new
genome "/Users/me/plasmids/foo bar/lambda2.fa"
```

leads to the error

`WARNING [Nov 16,2022 14:16] [BatchRunner] genome "/Users/me/plasmids/foo bar/lambda2.fa" => ERROR: Could not locate genome: "/Users/me/plasmids/foo bar/lambda2.fa"`

If I have it correctly, the code at for example https://github.com/igvteam/igv/blob/dfd9fb580f6a1a3db71e1118c67b5cf47eeff5e9/src/main/java/org/broad/igv/util/StringUtils.java#L53 (there is one other definition of breakQuotedString) uses the quotes to prevent tokenisation if the token character is within quotes, but then keeps the quotes as part of the string, explaining the error message above.

**Comment by jrobinso** [comment]
Yes, you're correct, this should be fixed in the next release.

**Comment by micans** [comment]
Super, thanks.
