### ISSUE TITLE
[OpenJDK17] URLDecoder cannot be instantiated anymore

### ISSUE THREAD

**Issue by pgrt** [igvteam/igv#1259]
Hello,

I am the Debian maintainer of igv; in Debian we have switched from OpenJDK11 to OpenJDK17 recently. igv can be built against it except for the line
    params.put("redirect_uri", new URLDecoder().decode(redirectURI, "utf-8"));
in
    src/main/java/org/broad/igv/oauth/OAuthProvider.java
because URLDecoder cannot be instantiated in OpenJDK17. If you would like to build against OpenJDK17 in the future, you could simply consider using the static form of the decode method:
    params.put("redirect_uri", URLDecoder.decode(redirectURI, "utf-8"));

Cheers,
Pierre

**Comment by jrobinso** [comment]
Thanks, I'll make that change for the next point release.   We're planning to switch to 17 early next year,  but I might switch in my development environment sooner.   

And thanks a lot for maintaining this.
