### ISSUE TITLE
Error opening up bam file from URL in 2.3.47

### ISSUE THREAD

**Issue by timothyjlaurent** [igvteam/igv#126]
This happens both with the osx .app and with the 'binary' version. 2.3.34 works okay.

Error message:

```
Error loading http://someplace/aligned.bam: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by jrobinso** [comment]
|You would expect this error to be seen if the server securing the bam 
file used a self-signed certificate or certificate created by a 
non-trusted authority.   However,  only when accessing by https,  your 
example url was http://,  is that just a typo?

Could you test the following urls?   Note the https in the second

http://www.broadinstitute.org/igvdata/BodyMap/hg19/IlluminaHiSeq2000_BodySites/heart_merged/accepted_hits.bam
https://www.broadinstitute.org/igvdata/BodyMap/hg19/IlluminaHiSeq2000_BodySites/heart_merged/accepted_hits.bam

Also, please be specific about the versions,  3.4 is not a version 
released by us,  and also platform and java version.



|
> |unable to find valid certification path to requested target|

**Comment by timothyjlaurent** [comment]
Sorry about the lack of specificity, I noticed this and edited this on the [website](https://github.com/broadinstitute/IGV/issues/126), but I suspect that you are answering the first email; the version that works is 2.3.34.

I already tested putting https:// and that didn't help. From the web browser it automatically switches to https:// and there is not warning about untrusted certificates. 

This is running on MAC OSX and I saw this problem with both java 1.7 and 1.8 .  My coworker also installed the software and was able to reproduce the error. 

I dug 2.3.47 out of my trash and discovered that the test urls in the reply work without any error. I'm still getting problems with our internal URL however with 2.3.47.

Please let me know if there is additional debugging , or grabbing of logs you would like me to do.

**Comment by jrobinso** [comment]
If you could please try a more recent version like 2.3.44, 45, or 46.   
If we can pinpoint exactly where it stopped working it would help.   Its 
hard for us to debug it without being able to reproduce.

Java is strict about certificates,  and with Java 1.8 some of the tricks 
we used to get around the strictness ceased to work, and in fact caused 
errors.  So there is a check on Java version in the most recent 
release,  if running on 1.8 no tricks are used and certificates have to 
be legit and from a trusted CA authority. This should not affect you if 
running with Java 1.7, so I have no explanation for that.  Its possible 
your web browser is configured to accept certificates from an internal 
certificate authority,  if that's the case we might have to figure out 
how to configure IGV to accept those.

Jim

**Comment by jrobinso** [comment]
ping -- could you verify the snapshot fix when you have a chance, and respond here?  Since I can't reproduce the problem,  I can't verify the possible fix.   Thanks.
