### ISSUE TITLE
IGV genome tracks like in UCSC browser

### ISSUE THREAD

**Issue by Adnanhashim** [igvteam/igv#1264]
Hi,
Unfortunately, the biologists in my lab prefer UCSC browser to IGV simply because the enriched regions (bigWig) are more visually appealing :( then IGV in the UCSC browser Could you please tell me if there are any settings/parameters that can be utilised to create IGV tracks that are similar to the UCSC genome browser? I've included screenshots of both the UCSC (yellow boxes) and IGV tracks. Also, the settings/parameters used by the UCSC genome browser. Thanks in advance, looking for a positive response. 

![IGV_vs_UCSC](https://user-images.githubusercontent.com/18658412/204006630-c0e4fc83-ab03-4297-a70f-a03dfcef0a92.jpg)
![paramters_UCSC](https://user-images.githubusercontent.com/18658412/204006767-c7cf4c4b-de6d-4b8b-ba0e-d778ca1c9a81.jpg)

**Comment by jrobinso** [comment]
@Adnanhashim I'm not sure why that's unfortunate, could you elaborate, the UCSC browser is an excellent tool.  

Also, if you had not outlined the tracks in the figure I wouldn't know which was which was which.   Could you be more specific in your request?
