### ISSUE TITLE
question regarding alignment

### ISSUE THREAD

**Issue by olechnwin** [igvteam/igv#1266]
Hi,

I am hoping someone can help me understand this. I aligned my genome assembly to hg38 and it is showing 3 counts of coverage on this region:

![image](https://user-images.githubusercontent.com/20069067/204616202-449aec97-88a2-4a7d-86c7-1bdde4322110.png)

So, I tried to search for this particular sequences "TCAATTTTGAAATCTGCAAAGTATTCATTA" in my genome assembly fasta file using blast. I was expecting to have 3 matches but then it only returns 2 matches. 
I am confused. I was expecting the search to 3 matches. Can anyone please help me understand why it only returns 2 matches instead of 3? I am attaching the files containing the 3 alignment information when you click on the alignments. 
[1st_align.txt](https://github.com/igvteam/igv/files/10116243/1st_align.txt)
[2nd_align.txt](https://github.com/igvteam/igv/files/10116244/2nd_align.txt)
[3rd_align.txt](https://github.com/igvteam/igv/files/10116245/3rd_align.txt)

Here are the BLAST results:
```
Database: scaffolds_FINAL.fasta
           99 sequences; 2,916,671,763 total letters



Query= > test2

Length=30
                                                                      Score     E
Sequences producing significant alignments:                          (Bits)  Value

scaffold_8                                                            56.5    2e-07


>scaffold_8
Length=141881116

 Score = 56.5 bits (30),  Expect = 2e-07
 Identities = 30/30 (100%), Gaps = 0/30 (0%)
 Strand=Plus/Plus

Query  1        TCAATTTTGAAATCTGCAAAGTATTCATTA  30
                ||||||||||||||||||||||||||||||
Sbjct  7937684  TCAATTTTGAAATCTGCAAAGTATTCATTA  7937713


 Score = 56.5 bits (30),  Expect = 2e-07
 Identities = 30/30 (100%), Gaps = 0/30 (0%)
 Strand=Plus/Plus

Query  1        TCAATTTTGAAATCTGCAAAGTATTCATTA  30
                ||||||||||||||||||||||||||||||
Sbjct  8007698  TCAATTTTGAAATCTGCAAAGTATTCATTA  8007727



Lambda      K        H
    1.33    0.621     1.12

Gapped
Lambda      K        H
    1.28    0.460    0.850

Effective search space used: 17500016322


  Database: scaffolds_FINAL.fasta
    Posted date:  Nov 29, 2022  1:21 PM
  Number of letters in database: 2,916,671,763
  Number of sequences in database:  99



Matrix: blastn matrix 1 -2
Gap Penalties: Existence: 0, Extension: 2.5

```
Thank you in advance for your help!

**Comment by jrobinso** [comment]
That's not how it works.  this is not the right forum for questions like that,  maybe try https://www.biostars.org/.
