### ISSUE TITLE
[Feature Request] Group by all tracks 

### ISSUE THREAD

**Issue by mnshgl0110** [igvteam/igv#1275]
Hi IGVteam,

In the earlier versions of IGV, group-by used to work on all tracks (which I assumed was a feature). However, in the newer version grouping works on one track at a time (https://github.com/igvteam/igv/issues/1045, https://github.com/igvteam/igv/commit/b0fc0b7ac40db1bb080bb6a837c256a564405236).

Would it be possible to add an option so that the user can choose whether to apply group-by all tracks or one (or a subset of tracks)? Currently, in the newer versions, when working with multiple samples it becomes tedious to group each track individually.

Thanks a lot.

Best
Manish

**Comment by jrobinso** [comment]
Yes I can see how that bug could be a feature.  We could consider a global option in the form of a user preference,   allowing subsets would require selecting tracks which can also be tedious.

**Comment by malcook** [comment]
FWIW: to my understanding, all the "Tracks" menu options always apply to all tracks, regardless of whether any, or one, are selected.  This has made intuitive sense to me so far.  If this issue is discussing changing this UX, I suggest care be taken to somehow clearly distinguish the scope of the associated menu actions.

**Comment by jrobinso** [comment]
@malcook I don't think the user is referring to the "Tracks" menu,  rather the alignment track popup menu, but I could be wrong.  @mnshgl0110 could you clarify?

**Comment by jrobinso** [comment]
Specifically the item "Group alignments by > ...",   this is not really about actions on tracks at all its display of alignments within a track.

**Comment by mnshgl0110** [comment]
@jrobinso Yes, you are right. I am interested in the "Group alignments by" option.

**Comment by jrobinso** [comment]
Its difficult if not impossible to do this in a totally consistent way.   Renaming a track from the popup menu should obviously not apply to all tracks.   I can think of 2 options off hand,  (1) the global user preference which applies to certain alignment track options only, such as group and sort, or (2) use a key modifier, if shift key is down (for example) apply these actions to all tracks.

**Comment by mnshgl0110** [comment]
> Renaming a track..

I assume you mean grouping.

These options would work, I agree.

Alternatively, "Group alignments by" has a "reverse group order" property. Is it not possible to have a "all tracks" property as well which is then shared by all tracks?

**Comment by lbergelson** [comment]
I like the idea of applying options to the set of selected tracks when it is something that makes sense to do.   
If we implemented cmd+a for select all it would be easy to use.

**Comment by jrobinso** [comment]
@lbergelson Select all what Louis?  There's a heterogeneous set of tracks in general, not all are alignment tracks.  Generally when you multi-select tracks you get a menu with the subset of items that apply to all the track types selected.   So you won't even see the alignment-specific track options if you select all tracks.

@mnshgl0110 That's an interesting idea, it might work.  And yes I did mean "rename track" as an example of a menu item that clearly should not apply to all tracks.

**Comment by jrobinso** [comment]
The suggestion by @lbergelson to apply actions to all tracks selected is a good one, but will require some refactoring.  The concept exists now,  you can multi-select tracks and apply certain actions common to all selected tracks now.   For example changing a track color.   However this doesn't quite work as expected when selecting multiple alignment tracks.   One might expect to see the alignment track menu,  but you don't, just a reduced generic menu.  This is arguably a bug, but not easily remedied without some redesign.

In the meantime I'm going to experiment with @mnshgl0110 suggest of implementing a "group all" state similar to the  the "invert group sort" option.   I expect this option will be wanted either all the time, or never, and does not need to be track specific.   It could be set in the preferences UI,  which will essentially revert  to previous IGV behavior.   Alternatively it could (also) be set in the alignment track menu.   These options aren't mutually exclusive.   

Unlike "invert group sort",  the "group all" option is not a track state and does not need to be stored in a session.   The state itself is in the individual alignment track groupings.   This is just a shortcut menu option.    I know I'm in the weeds now,  I will stop.

**Comment by jrobinso** [comment]
@mnshgl0110 I implement this as you suggested, with a "Group all tracks" option after "Reverse group sorting".   Unfortunately selecting either of these options dismisses the menu, and you have to re-open to group, but the option is remembered until you change it.   

This will be in the next point release,  which should happen the end of this week or early next week.

**Comment by mnshgl0110** [comment]
Thanks @jrobinso . I am looking forward to it.
