### ISSUE TITLE
VCFv4.4 is not a supported version

### ISSUE THREAD

**Issue by eroller** [igvteam/igv#1289]
Hi, I tried to load a VCF file that uses VCF 4.4 which is the latest specification:

https://github.com/samtools/hts-specs/blob/master/VCFv4.4.pdf

 and got an error:
 

>  Error loading ....vcf.gz. Unable to parse header with error: Your input file has a malformed header: VCFv4.4 is not a supported version for input source: ....vcf.gz

 
 Generally the vcf spec seems to be forward compatible so I was wondering what is the need for rejecting future versions of the VCF specification? Can we safely remove this error without major changes to IGV?

**Comment by jrobinso** [comment]
That's a question for the htsjdk,  @lbergelson ?

**Comment by lbergelson** [comment]
Unfortunately htsjdk doesn't support 4.4 yet.  There are some changes in 4.4 that are not compatible with previous versions ( leading | in GT field and genotype number value P for instance. ). In many cases they will be compatible but you might run into issues.  There's no current plan/timeline to support 4.4 although it's an obvious thing that people want.  Adding an option to disable version validation and just give it a shot seems plausible as a stopgap measure.

**Comment by droazen** [comment]
@KevinCLydon will add the capability to toggle VCF version validation as a stopgap measure until full 4.4 support is implemented in HTSJDK.
