### ISSUE TITLE
Fonts too small on high resolution screens

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#129]
I have recently bought two 4K 24" screens with pixel density of about 185 PPI. I have an Ubuntu box to work with them. Alas, though I can scale system fonts and menus, all the menus and pop-up windows in IGV are tiny. Almost unreadable, which makes IGV almost unusable.

I changed the "default font" in preferences, but it only affected track descriptions.

Could you allow for font scaling in all menus? With more high-density screens coming more and more people will experience this problem.

**Comment by jrobinso** [comment]
Useful links 

http://stackoverflow.com/questions/28673127/how-can-i-scale-fonts-on-a-high-resolution-screen
http://stackoverflow.com/questions/26877517/java-swing-on-high-dpi-screen?rq=1
http://www.miglayout.com/
http://docs.oracle.com/javase/7/docs/api/java/awt/FontMetrics.html

**Comment by jrobinso** [comment]
Perhaps a better solution? http://www.3rd-evolution.de/tkrammer/docs/java_font_size.html

**Comment by mdshw5** [comment]
I'm not sure if you're planning support for high-dpi screens on MacOS ("retina"), but I would appreciate any support beyond what is currently done - very poor scaling.

![screen shot 2015-06-26 at 12 02 34 pm](https://cloud.githubusercontent.com/assets/819554/8381682/3fe8bb82-1bfb-11e5-91fe-349ecc3295f8.png)

**Comment by nchernia** [comment]
Jim have you looked into this further?  We're having similar issues in Juicebox

**Comment by jrobinso** [comment]
I did do something, but I don't have a retina screen to test this 
with.   Users reported it worked though.     The code below changes all 
the built in fonts, if you explicitly create a font of a certain size 
you need to scale it as well of course.

public static void scaleFontSize(double sf) {

     double resolutionScale  = Toolkit.getDefaultToolkit().getScreenResolution() / Globals.DESIGN_DPI;        <= design value is 96

     Set<Object> keySet = UIManager.getLookAndFeelDefaults().keySet();
     Object[] keys = keySet.toArray(new Object[keySet.size()]);
     for (Object key : keys) {
         if (key !=null && key.toString().toLowerCase().contains("font")) {
             Font font = UIManager.getDefaults().getFont(key);
             if (font !=null) {
                 int newSize = (int) (scaleFactor  * font.getSize());
                 font = font.deriveFont((float) newSize);
                 UIManager.put(key, font);
             }
         }
     }

}

**Comment by magicgoose** [comment]
Keep in mind that `Toolkit.getDefaultToolkit().getScreenResolution()` does return incorrect value (twice as small) on OS X w. "retina" displays.

**Comment by jrobinso** [comment]
Do you have a reference for that,  and do you know if its been fixed in the
latest Java release?   I do have a retina display and don't see this
problem.

**Comment by magicgoose** [comment]
Reference? I just tested it myself, on JDK 8u112 and OS X 10.11.6.

But there's another way to do this: https://stackoverflow.com/a/40399909/1418097

**Comment by jrobinso** [comment]
Reference as in Oracle bug report.   I'll look at the code snippet and see
if it can be used.  I can't just do a 2X correction because, again,  I have
a retina display and it is correct here.    This is Yosemite and
java 1.8.0_60-b27.

**Comment by magicgoose** [comment]
>Reference as in Oracle bug report

Ah, OK. I didn't send it to Oracle and probably won't bother doing this.

**Comment by jrobinso** [comment]
Here's what I get if I run the code snippet above on my macbook

scale factor = 2    realDPI = 221.0

I don't really know what to do with this information, however, since the
fonts look good.    What version of IGV are you running?

Jim

**Comment by magicgoose** [comment]
I'm not really a user of igv, just noticed that the code snippet shown above doesn't always work correctly on OS X. However maybe igv also needs this "virtual" dpi value (in our case 110), then I guess it's just right as it is. 😂

**Comment by anderspitman** [comment]
Is there a solution to font/UI scaling for IGV? I'm running it on Linux (Arch with kernel 4.10 and OpenJDK 8) and it's very tiny and has poorly rendered fonts.
![igv_scaling](https://cloud.githubusercontent.com/assets/7820200/26380796/850f4e1a-3fd5-11e7-9e79-a660cf5fbce6.png)

**Comment by lloydkirk** [comment]
@anderspitman I'm in exactly the same boat.

IGV version 2.3.92; Arch linux kernel 4.10; Xmonad (an X11 based window manager); OpenJDK 8; Apple 5K macbook, or 4K external. 5K is excruciatingly tiny, 4K is still pretty small, a lot smaller than when I compare against my colleagues running OSX. I've tried the ``Scale Fonts`` setting with no result.

I ran this code ``Toolkit.getDefaultToolkit().getScreenResolution()``, and it returned 97, even though my DPI in X11 is set to 180

Any thoughts on a feature that allows for explicitly overriding the dpi?

**Comment by slowkow** [comment]
Could I please ask if there is any way to increase the font size in the IGV app?

**Comment by jrobinso** [comment]
@slowkow For the most part no, but the high DPI problems have been fixed in recent releases.  Give us more details on your OS, screen, what version of IGV you are using (and Java),  and what problem motivates the question.

**Comment by Afollet** [comment]
I'm getting the same problem with @anderspitman, but I'm on Ubuntu 22.04 LTS x86_64 , Kernel 5.15.0-30-generic. WM is mutter, Resolut
ion: 3456x2160.

**Comment by jrobinso** [comment]
@Afollet version of IGV and Java?

**Comment by nahanoo** [comment]
For people ending up here after googling this issue make sure to execute `igv_hidpi.sh` and not `igv.sh`.
I ended up trying to fix this for a while and it made me laugh once I realized that the solution was already there.
Cheers.

**Comment by jrobinso** [comment]
@nahanoo What OS are you run?  The hidpi problem should be solved automatically for most,  `igv_hidpi.sh` is there as a backup solution.    We will be moving to Java 17 soon, maybe this problem is finally solved.

**Comment by nahanoo** [comment]
Hi @jrobinso 
Thanks for the clarification.
I'm running Ubuntu 22.04.2 with 6.3.0 Linux kernel version. Not sure if it's relevant but I'm using Mutter 42.5 as a window manager.
IGV version is 2.16.1. 
`igv_hidpi.sh` is working fine for me but I'm happy to provide more infos if this is useful for developing.
Thanks!

**Comment by ira-zibbu** [comment]
Came here with the same issue of the fonts appearing very small on my 27' monitor. Running `igv_hidpi.sh` fixed it for me.
