### ISSUE TITLE
bug: region doesn't update in split-screen mode

### ISSUE THREAD

**Issue by yfarjoun** [igvteam/igv#1293]
When viewing a read and it's mate in a split-screen, one can still navigate (pan by dragging, zoom in and out with double click and alt-click) but the region noted above the split screen remains unchanged. 

Desired behaviour: the region listed is updated when the window is modified.

Version: 2.16.0

Thanks!

**Comment by jrobinso** [comment]
Yes good suggestion,  I think there is a historical reason for this but I can't recall it.   Anyway I agree it should update.
