### ISSUE TITLE
Feature request - highlighting location of matching soft-clipped reads 

### ISSUE THREAD

**Issue by bellmartin** [igvteam/igv#1296]
Dear IGV team, 

I use IGV daily in my research in rare disease and find it a fantastic tool - so thank you !

The feature I would like to see is a way of highlighting the location of a series of soft-clipped reads, located at the same location in the genome, with at least 6-10bp of matching soft-clipped sequence,   so that you can see their location in the genome without having to zoom in to the base pair level.

Ideally the feature would allow you to select how many soft-clipped reads start in the same location to be marked, as well as how many reads in the soft-clipped sequence need to match each other, again to be marked.   This would be highlighting breakpoints in the DNA (or RNA), that have a certain amount of reads supporting it. How these breakpoints are highlighted would need to be different than the usual purple arrow for small mapped insertions ( ie dup of a nucleotide) 

The reason I would like this feature is one of the more difficult mutations to pick up are insertions. They are also very hard to spot in IGV unless you zoom right in to the base pair level.    

I have pasted an example which I would like IGV to be able to highlighted. 
 - notice that the soft clipping all starts at the same location 
 - and the sequence of the soft-clipping is the same, though there are different lengths of soft-clipping in each read.  
<img width="784" alt="image" src="https://user-images.githubusercontent.com/12620680/223885866-39309001-8846-4e2f-9cf5-793c15a1f632.png">. 
- it is also worth noting that many of the examples I would like highlighted, have inserted sequence that do not map elsewhere in the genome ( or not uniquely). For example, novel insertions of ALU  sequences.

Is this a feature you think you might be able to include in IGV?  I acknowledge that confirming the soft-clipped sequences match each other is not an easy / quick problem to solve.  

Please let me know if you would like more information or examples

Kind regards,
Katrina

**Comment by jrobinso** [comment]
Hi,  I don't have time to respond in detail right now,  but your example screenshot is a bit confusing as you are zoomed into bp level.   I think you are just trying to illustrate the case, but ow far zoomed out are you ideally interested in?     

Normally we expect a variant caller (in this case an SV caller) to be used to find breakpoints like this, and IGV used to zoom in to confirm them.   It is an interesting use case you describe, and might be possible, but feels more like the job of a variant caller.   But leave this issue open until we have some time to study this.
