### ISSUE TITLE
bug: igv doesn't show details about bedpe locus when interval is inter-chromosomal

### ISSUE THREAD

**Issue by yfarjoun** [igvteam/igv#1302]
For example even if I zoom into a given locus

<img width="181" alt="image" src="https://user-images.githubusercontent.com/2745554/226415738-6d31c7d8-7bba-47ab-a87a-7f56d10d4d67.png">

I still get no response when I click on the black line. when I click on the purple/pink line a pop-up opens up telling me the details of the interval (namely the two loci and possibly the score)

It would be great to have that for the inter-chromosomal records as well.

IGV version:  2.16.0

<img width="262" alt="image" src="https://user-images.githubusercontent.com/2745554/226415399-8165b279-3cf1-468d-b824-0fe4f63525e6.png">

**Comment by jrobinso** [comment]
Yes that looks like a bug.  I'll look at it.
