### ISSUE TITLE
How to set the height of Alignment track?

### ISSUE THREAD

**Issue by dinglinfeng** [igvteam/igv#1307]
Hello,

I‘m using IGV 2.16.0 on macOS. I am not able to change the height of Alignment track, https://software.broadinstitute.org/software/igv/ChangeDataDisplay#trackHeight may be only worked on Coverage track.

I used to drag and drop the mouse to change the height, but the line between different samples was disappeared. How can I change the height of Alignment track?

![image](https://user-images.githubusercontent.com/69247265/228222800-3fad13de-63bc-4cb9-a3dc-9fe36a957a08.png)

Thank you, 
DLF

**Comment by jrobinso** [comment]
You cannot change the height of tracks, only panels.  Normally when you load an alignment track it, and the associated coverage track,  are placed in a new panel.   You can adjust the boundary of the panel by grab and dragging the divider bar.

I do not know how you got multiple alignment tracks in the same panel,  that could be from drag and dropping the tracks, or done by modifying a session XML file.
