### ISSUE TITLE
Genome not loading properly

### ISSUE THREAD

**Issue by nicolecalamari** [igvteam/igv#1308]
Hello,

I have a batch file script that I had previously used to run IGV_2.4.14 and it produced plots with the tracks that I wanted. I had to update my IGV to IGV_16.0 and I am now having problems loading in the genome for the Gene track despite using the same batch file. The genome appears to be loaded with no error messages, but the plot itself does not show a Gene track. I have the .fai and .dict file downloaded in that directory as well. Thank you so much, I look forward to hearing from you and figuring this out!

**Comment by jrobinso** [comment]
Its difficult to say as I don't know what's in your ".genome" file.    Unless you need a local ".genome" file for some reason I suggest loading the hosted version, i.e.

```
genome hg38
```

I'm happy to look into this further if you zip and attach your "hg38.genome" file here, alternatively you could email it to igvteam (at) broadinstitute.org

**Comment by nicolecalamari** [comment]
Thank you Jim! I just sent you an email at igv-team@braodinstitute.org

**Comment by jrobinso** [comment]
So far I can't reproduce this problem, the file you sent works perfectly fine in a 1 line batch script

```
genome hg38.genome
```

From the stack trace,   the attempt to load the default genome is trying to load `hg38load`, as if the script was

```
genome hg38load
```

**Comment by jrobinso** [comment]
One suggestion is to delete all the cached genomes in the "igv" folder, then restart IGV.   The ".genome" format was deprecated in release 2.11 for a new "json" format,  if you delete the cached genomes it will update.

**Comment by nicolecalamari** [comment]
Great I will try that, thank you! Where can I find the json format of the genome file?

**Comment by jrobinso** [comment]
The format is described here:  https://github.com/igvteam/igv/wiki/JSON-Genome-Format.   

If you clear the "igv/genomes" cache (remove all ".genome" and ".json" files in that folder),  the json genome definition will be downloaded when you select it from the "Genomes > Select Hosted Genome" menu.

**Comment by nicolecalamari** [comment]
Great, thanks so much!

**Comment by nicolecalamari** [comment]
Hi Jim,

To follow up with you, I was able to get the .json file working, using this file. For the Refseq Genes track, I am having trouble collapsing the track. I have tried adding `collapse Refseq Genes` to the batch file, and tried using the "height" variable in the .json file but have not had any luck. With the Refseq Genes track included, the tracks below it are cut off, but when I remove it all together I can see the Nested Repeats and Simple Repeats tracks. Do you have any idea how to fix this issue?

`{
  "id": "hg38",
  "name": "Human (GRCh38/hg38)",
  "fastaURL": "Homo_sapiens_assembly38.fasta",
  "indexURL": "Homo_sapiens_assembly38.fasta.fai",
  "cytobandURL": "cytoBandIdeo.txt.gz",
  "aliasURL": "hg38_alias.tab",
  "chromosomeOrder": [
    "chr1",
    "chr2",
    "chr3",
    "chr4",
    "chr5",
    "chr6",
    "chr7",
    "chr8",
    "chr9",
    "chr10",
    "chr11",
    "chr12",
    "chr13",
    "chr14",
    "chr15",
    "chr16",
    "chr17",
    "chr18",
    "chr19",
    "chr20",
    "chr21",
    "chr22",
    "chrX",
    "chrY"
  ],
  "tracks": [
    {
      "name": "Refseq Genes",
      "type": "annotation",
      "format": "refgene",
      "url": "ncbiRefSeq.sorted.txt.gz",
      "indexURL": "ncbiRefSeq.sorted.txt.gz.tbi",
      "displayMode": "COLLAPSED"
    },
    {
      "name": "Nested Repeats",
      "type": "annotation",
      "format": "bed",
      "url": "nestedRepeats.ref.bed.gz",
      "indexURL": "nestedRepeats.ref.bed.gz.tbi",
      "displayMode": "COLLAPSED"
    },
    {
      "name": "Simple Repeats",
      "type": "annotation",
      "format": "bed",
      "url": "simpleRepeat.ref.bed.gz",
      "indexURL": "simpleRepeat.ref.bed.gz.tbi",
      "displayMode": "COLLAPSED"
    }
  ]
}`

**Comment by jrobinso** [comment]
It looks like IGV Desktop ignores the `displayMode` property.   That is a bug, there is nothing you can do until it is fixed.  Leave this open and I will fix it for the next release.

`height` is ignored in IGV Desktop because currently individual tracks do not have scroll bars.  That will be addressed at some point, but is a longer term project.
