### ISSUE TITLE
tag labels blacked out in igv batch snapshot for png

### ISSUE THREAD

**Issue by JesseRop** [igvteam/igv#1310]
Tag labels in IGV png snapshots are blacked out when I generate them using batch script as seen below:

batch script to generate plots in igv version 2.13.2

```
snapshotDirectory "path/to/dir"
goto Pf3D7_01_v3:29410-37226
snapshot 01_29510_37126_VAR_PF3D7-0100100.png
goto Pf3D7_01_v3:42267-46607
snapshot 01_42367_46507_VAR_PF3D7-0100300.png
goto Pf3D7_01_v3:78141-79991
```

![image](https://user-images.githubusercontent.com/18431376/229619660-6fea20a0-5081-4376-87e3-eee72e38d4cd.png)

This is not the case when I save the images as svg

**Comment by jrobinso** [comment]
I cannot reproduce this with the latest release (2.16.0).

**Comment by jrobinso** [comment]
If you can reproduce this behavior with the latest release please re-open the issue.
