### ISSUE TITLE
How to set `~/igv` directory using batch commands?

### ISSUE THREAD

**Issue by nh13** [igvteam/igv#1312]
I don't see any way via: https://github.com/igvteam/igv/wiki/Batch-commands.  I am looking at the logs and getting:
```
INFO [<date>] [Main] IGV Directory: /root/igv
Can't create cache file!
Can't create cache file!
Can't create cache file!
Can't create cache file!
Can't create cache file!
...
```
I am wondering if `/root/igv` is not writable, so I need to change the IGV directory in the batch command.

**Comment by jrobinso** [comment]
You're running IGV as root? Yikes, I hope it doesn't do anything harmful.

You can't set it from batch commands, however it is a command line parameter,  ```igvDirectory```

**Comment by jrobinso** [comment]
As in ```--igvDirectory /path/to/directory```.   That should work, at least from code inspection, I haven't tried it.

**Comment by nh13** [comment]
Running in a container, nothing to see here!

Sorry for not checking the help options!
