### ISSUE TITLE
Reads not displayed after switching genome

### ISSUE THREAD

**Issue by nh13** [igvteam/igv#1313]
I am not sure this is a bug, or just one should load the genome before any other tracks, but I thought I would report it in case others hit the same issue.  

Consider the first time you run IGV (i.e. no `~/igv` directory, with preferences and a default genome), and the following batch file:

```
new
snapshotDirectory .
load custom.gtf
load sample.bam
genome custom.fasta
goto contig_in_custom:1-1000
```

The first time running IGV batch, it will fail to show reads.   In this case, IGV will default to hg19 when loading the GTF and BAM (since no genome is loaded).  When we load the custom FASTA switch to a contig, no reads are displayed.

If you run IGV again, the reads will display because the IGV preferences are set to the new custom genome as the default:
```
$ cat ~/igv/prefs.properties 
IGV.Bounds=0,0,1150,800
DEFAULT_GENOME_KEY=/path/to/custom.fasta
```

The solution is to move `genome custom.fasta` to execute prior to loading other tracks.

This is especially important for running IGV batch in a container as part of a workflow, as IGV will almost surely not have the preferences set in the `~/igv` directory since it is "run for the first time" each time its executed.

**Comment by jrobinso** [comment]
Thanks for the tip, yes you should always load the intended genome before tracks in a batch script.  I should update our examples to do that.   Switching genomes starts a new session, since presumably anything currently loaded aligned to the previous genome.

**Comment by nh13** [comment]
Also, updating the [wiki](https://github.com/igvteam/igv/wiki/Batch-commands) would be great!

**Comment by jrobinso** [comment]
I added a note to the wiki.
