### ISSUE TITLE
IGV sequence does not match refseq

### ISSUE THREAD

**Issue by atgustin** [igvteam/igv#1314]
Hello,

I apologize if this question has been addressed already.  

What can cause the IGV sequence for a well-characterized gene to not match the refseq track?  
(Hg38 on IGV 2.16)

Currently, the sequence bar for the amino acid sequence does not match the known amino acid sequence for RIG-I provided by refseq.  

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/37525448/230722647-60361b61-deac-46c1-a465-69eeb771162f.png">

I attempted to search for similar problems and found " hg38 genome not what's expected #363 ", but in their case the problem results in a high degree of mismatches in their data.  In my case, my transcripts align with the IGV sequence bar with minimal mismatches, so I feel this is potentially a distinct problem.

 Thank you so much for any insights!

Andrew

**Comment by jrobinso** [comment]
That's a negative strand gene, and you are viewing sequence for the postitive strand.  Try viewing the complementary sequence with the arrow button to the left of the sequence.

**Comment by atgustin** [comment]
Sorry this isn’t my wheelhouse - and thank you for bringing the obvious to
my attention!

Andrew
