### ISSUE TITLE
IGV_2.16.0 SVG files cannot be opened in Mac preview or Adobe Illustrator 2021

### ISSUE THREAD

**Issue by AlexdeMendoza** [igvteam/igv#1318]
Dear IGV Team, 

Using the IGV desktop app, doing `File` -> `Save SVG Image ...` produces SVG files that I cannot open in Adobe Illustrator (none of them works), or cannot even be previsualised in Mac OS. 

In contrast, SVG files generated from the IGV internet browser app work fine. 

Thanks,

A.

**Comment by jrobinso** [comment]
What types of tracks (data files) are you saving as SVG?

**Comment by AlexdeMendoza** [comment]
Bigwigs, GTF, bed.

**Comment by jrobinso** [comment]
Attached is an SVG with a bigwig, gtf, and bed track.   Can you open it?   I do not have illustrator, and my version of Preview at least does not support SVG, but it displays fine in a browser as well as Gimp

[igv_snapshot.svg.zip](https://github.com/igvteam/igv/files/11300201/igv_snapshot.svg.zip)
