### ISSUE TITLE
CircularView AppImage will not run on Ubuntu 22.04.2

### ISSUE THREAD

**Issue by DaniilSarkisyan** [igvteam/igv#1319]
"IGV JBrowse CircularView-0.1.1.AppImage", which I got following the instructions on https://github.com/igvteam/igv/wiki/Circular-View will not run. I think it still wants libfuse2, while Ubuntu's default now is libfuse3.

```
$ ./IGV\ JBrowse\ CircularView-0.1.1.AppImage 
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information

$ apt list libfuse*
Listing... Done
libfuse-dev/jammy 2.9.9-5ubuntu3 amd64
libfuse-dev/jammy 2.9.9-5ubuntu3 i386
libfuse-perl/jammy 0.16.1+20180422git6becd92d7fce3fc411d7c-5build1 amd64
libfuse2/jammy 2.9.9-5ubuntu3 amd64
libfuse2/jammy 2.9.9-5ubuntu3 i386
libfuse3-3/jammy,now 3.10.5-1build1 amd64 [installed,automatic]
libfuse3-3/jammy 3.10.5-1build1 i386
libfuse3-dev/jammy 3.10.5-1build1 amd64
libfuse3-dev/jammy 3.10.5-1build1 i386

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

Since https://github.com/AppImage/AppImageKit/wiki/FUSE explicitly say "While libfuse2 is OK, do not install the fuse package as of 22.04 or you may break your system", I was not brave enough to experiment with "sudo apt install libfuse2".

**Comment by jrobinso** [comment]
I'm afraid I'm a little out of my depth here.   I rely on electron-builder to create the app image, documentation for linux is here:  https://www.electron.build/configuration/linux.   There is no mention that I can find of libfuse version.  

I have updated electron, electron-builder, and dependencies to the latest released versions and rebuilt as version "0.2.0".  I'm not hopeful for this as the electron updates looked minor, but if you want to try the AppImage is at https://igv.org/downloads/circview/test/.  There is also an RPM package in there in case that is useful.   Let us know if you find a solution.

BTW I have no way to test any linux distribution, so these new builds are untested.
