### ISSUE TITLE
Add shortcut for "View" in Region Navigator

### ISSUE THREAD

**Issue by rmzelle** [igvteam/igv#132]
I have a several hundred regions of interest I would like to inspect visually, but it looks like I need to select each region by hand in the Region Navigator and then click the View button.

It would be nice if e.g. double-clicking on a region, or pressing Enter when a region is selected, both would have the same effect as pressing the View button.

**Comment by rmzelle** [comment]
I also would like to be able to delete features in the Region Navigator by pressing the Del key.

**Comment by jrobinso** [comment]
OK.  Here's a workaround for the region navigator "next" issue.   Load the regions from the File menu (they are in bed format).   This will give you a feature track.  Select the feature track by clicking its name.  You can then skip through features using the ctrl-f and ctrl-b key combinations.

**Comment by jrobinso** [comment]
I should add the file containing the regions should end with ".bed" for this to work.

**Comment by rmzelle** [comment]
I was using a .bed file but imported via the Regions menu ("Import Regions..."). I'll give the feature track a try.

**Comment by rmzelle** [comment]
I ran in several additional issues with the Region Navigator:

* after clicking on an entry, I can use the arrow keys to move up or down and select another entry. This doesn't work anymore after I click the "View" button (presumably focus is lost).
* deleting multiple entries at the end of the list is extremely buggy for me. After I click "Remove" the entries I want to delete don't disappear, and some other strange things happen (the values in the "Chr" and "Start" and "End" columns of the remaining entries shift relative to each other, which obviously is very bad)
* if I select an entry and then select the main IGV window (so that the Region Navigator window loses focus), pressing "Remove" gives the error "No regions have been selected for removal".
