### ISSUE TITLE
Unable to load 'Repeat Masker' from IGV server in Linux

### ISSUE THREAD

**Issue by lucylz** [igvteam/igv#1320]
Hi, 

I am unable to load 'Repeat Masker ' from IGV server, with hg19 . My IGV version is 2.16.0. 
I am using IGV in Linux system (Fedora 37 ). 

IGV gives me the error message below :

"Error loading https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/variations/Unknown.rmask.gz:Unalbe to create
BasicFeatureReader using feature file, for input source:
https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/variations/Unknown.rmask.gz "

Can anyone help me solve this issue?

Thanks!

**Comment by jrobinso** [comment]
Hi, that looks like a problem with the file or IGV.   I will investigate.

**Comment by jrobinso** [comment]
This is now fixed, you will need to restart IGV.

**Comment by lucylz** [comment]
It works now!! Thank you so much!!
