### ISSUE TITLE
Copy read sequence without indels?

### ISSUE THREAD

**Issue by itslittman** [igvteam/igv#1322]
Is there a way to copy a read sequence without small indels? I set the small indel threshold higher and that hides the indels visually, but when I copy and paste the read sequence it is of course the full sequence.
I'm analyzing a transcript sequenced with the ONT direct RNA protocol, which is fairly noisy. I want to paste a "corrected" sequence into ORFfinder and see what it looks like.

Noah

**Comment by jrobinso** [comment]
No there is not.  The read sequence is just that,  the sequence the machine read.   Alignment to a particular reference has no impact on the read sequence.  Indels are, of course, artifacts of alignments.   What you are requesting would be some kind of new generated sequence.

**Comment by itslittman** [comment]
@jrobinso so there’s no simple way to generate that sequence in IGV?

**Comment by jrobinso** [comment]
No there's not.
