### ISSUE TITLE
Cannot load GRC m38.p6 IgH track data onto IGV 

### ISSUE THREAD

**Issue by JamesIgE** [igvteam/igv#1324]
Hi,

I'm trying to load NCBI derived GRC m38.6 IgH locus track data (GFF3) onto IGV (desktop) in parallel with the default m38/m10 reference genome however no IgH data shows up. When I load the m39 version onto the m39 reference genome, it works well (but I need to use the m38 version for my project right now). I've also tried using the m38.p6 reference genome FNA file downloaded from NCBI as well and the m38 IgH locus still doesn't show up. Can anyone help me figure out what's going on? 

Here is the IgH NCBI track data link:
https://www.ncbi.nlm.nih.gov/gene/111507

IGV 2.16.0

Thanks,
James

**Comment by jrobinso** [comment]
Have you verified that there are annotations at the genome coordinates you expect to find them by examining the GFF3 file?  For example in a text editor?

**Comment by JamesIgE** [comment]
Just checked in notepad. A little difficult to understand what's going on (I'm completely new to all of this). Looking at one of the flanking genes, the coordinates seem near but not exactly where mm38 is showing it to be. Having said that, all of the coordinates I see in the text file are generally in the region I've been looking in IGV/mm38.

**Comment by jrobinso** [comment]
If you give me a direct link to the GFF file, and also a genome location (in chr:start-end coordinates) where you expect to see annotations but see none I will check it out.

**Comment by JamesIgE** [comment]
Hi Jim! Thanks for helping!

I don't know how to give you a direct link to download the m38p6 IgH GFF3 track data but I can give you the NCBI link with pictured instructions:
https://www.ncbi.nlm.nih.gov/gene/111507

[cid:7782078c-8228-47cf-8f17-8c26678ed81d]After this, I opened up IGV (Windows PC desktop version, 2.16.0), loaded the default genome for Mouse (GRCm38/mm10). Then I dragged onto the browser (or go to file --> load from file) the m38p6 IgH track GFF3 file.

I am looking within the general range of:
113,258,768-116,009,954 for m38/mm10 which is where the IgH locus should be. (The default m38/mm10 reference genome doesn't have the IgH locus which is in the reverse direction but includes surrounding genes, so I can only see it by adding the additional IgH track). I cannot see the m38 track data when I use it with the m38 reference genome but I can see it when I use the m39 track data with the m39 reference genome:

GRCm38p6 (the top row is my atacseq data, row below is where the IgH track should be)
[cid:c79f1063-106a-4160-beaf-01d7b9694de7]

GRCm39 (what the IgH track should look like)[cid:4e30ee15-9c19-4093-9e98-bfe0d7f82ea1]

Thanks again for the help!
James
________________________________

**Comment by jrobinso** [comment]
Did you try to upload screenshots?  I don't see one.  My question is a simple one, how did you get this file?  "m38p6 IgH track GFF3 file".   I don't see a downloadable GFF3 file anywhere on the page you referenced.   Perhaps you could zip it and upload it here, since you seem to have it.

**Comment by JamesIgE** [comment]
Oh. Yea, I loaded a few screenshots that showed how I downloaded the file off NCBI.

As a note, I also contacted NCBI and here is their response:
---------------
I was able to reproduce the problem, but looking at both .gff3 files, I could not tell any difference in the format.
I enlisted help from other NCBI staff. One of the developers was able to identify the problem with IGV. IGV seems to understand RefSeq acc.ver (NC_000078.7) for GRCm39 but not GRCm38.

Your work around for the .gff3 file that you download for m38, is to open it in a text editor, use find/replace and replace all instances of NC_000078.6 with chr12. The genes should then show up in IGV.

---------------

I realized the files aren't that big so I didn't zip them (let me know if you need me to do that though). Just sent both the m38p6 IgH GFF3 track and m39 version.

James
________________________________

**Comment by jrobinso** [comment]
Well I couldn't see the screenshots, as you will note they do not show up, and I can't figure out how to download the file.  However NCBI has identified the problem, the chromosome names in the GFF file do not match the names in IGV's reference.  Their solution is what I would recommend.
