### ISSUE TITLE
Can't access google cloud

### ISSUE THREAD

**Issue by gevro** [igvteam/igv#1328]
Hi, Version 2.16.1. Never had an issue like this, this is new. No settings have changed with Google cloud. When I open a Gcloud URL file, it opens the authorization page in my browser. I authorize and click continue, but then the browser gets stuck on this (progress bar keeps going left to right and nothing loads in IGV:
<img width="543" alt="Screenshot 2023-05-13 at 11 09 46 PM" src="https://github.com/igvteam/igv/assets/47928628/31521812-a679-4511-9a58-61aea2867289">

Then eventually the browser goes to this page:
http://localhost:60151/oauthCallback?state=56bd0266-e232-4cfe-af.....df&code=4/...&scope=email%20https://www.googleapis.com/auth/devstorage.read_only%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=...&prompt=consent
 [ Partially redacted/corrupted URL just in case]

with this error shown on the page:
```
Unable to connect

Firefox can’t establish a connection to the server at localhost:60151.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.
```

**Comment by gevro** [comment]
Update: Restarting IGV and browser and clearing all cookies/cache didnt' help. But restarting computer fixed the issue.

**Comment by helgathorv** [comment]
Thanks for letting us know.
