### ISSUE TITLE
FEATURE REQUEST: native bzip2 support

### ISSUE THREAD

**Issue by javasmith** [igvteam/igv#1329]
IGV natively supports gzip compressed CRAM and VCF files (and perhaps other files as well). The bzip2 compression format is open-source and more efficient. As an example, I have a human genome VCF file that's 1.176 GB uncompressed. Using gzip with its maximum compression parameters, it compresses down to 204 MB. Using bzip2 with its maximum compression parameters, it's 147 MB. That's almost a 30% improvement.

**Comment by javasmith** [comment]
Not CRAM files...

**Comment by jrobinso** [comment]
BAM anc VCF are typiclally block-gzipped (bgzip), not gzipped, so they can be indexed.   So bzip2 is not a viable alternative.

**Comment by jrobinso** [comment]
More concretely, bzip2 compressed files could not be indexed.   See the BAM and tabix format descriptions for more info.
