### ISSUE TITLE
how to expand the visible window of reads mapping

### ISSUE THREAD

**Issue by zhoudreames** [igvteam/igv#1335]
![1](https://github.com/igvteam/igv/assets/54714639/c96dab6e-9f76-48e6-ad54-70bd6ecdd1fe)
The max visible window is 30k when I open the Illumina alignments files, can I expand the visible window of reads mapping?

**Comment by jrobinso** [comment]
Have you checked the user documentation?   Select "View > Preferences > Alignments tab and look for the visibility window setting.

**Comment by rzelle-lallemand** [comment]
@zhoudreames, I would also like to kindly ask you to stop tagging people like you did above. You did the same before (https://github.com/igvteam/igv/issues/1255#issuecomment-1313361989), but I'm not an IGV developer.
