### ISSUE TITLE
Error with "export features" batch command in IGV

### ISSUE THREAD

**Issue by JC-Delmas** [igvteam/igv#1338]
Hello,

I'm encountering an issue with the "export features" command in IGV and I was wondering if someone could help me troubleshoot it.

I have a script that uses the "export features" command to export splice junction information for multiple genes. However, when I run the script, I receive the following error message for each gene:

```
WARNING [date and time] [CommandExecutor] UNKNOWN COMMAND: export features [gene]_splice_junctions.bed junctions WARNING [date and time] [BatchRunner] export features [gene]_splice_junctions.bed junctions => UNKNOWN COMMAND: export features [gene]_splice_junctions.bed junctions
``` 
I'm using IGV version 2.12.3. Is the "export features" command not supported in this version? If so, is there an alternative method to export splice junctions in IGV?

I would appreciate any guidance or suggestions to resolve this issue. Thank you in advance for your help!

Best regards,
Jean-Charles

**Comment by jrobinso** [comment]
I'm curious where you found a reference to "export features",  that is not a batch command in any IGV version.  The complete list of supported batch commands can be found here: https://github.com/igvteam/igv/wiki/Batch-commands.
