### ISSUE TITLE
Add preference for bam file display mode  (EXPANDED | SQUISHED)

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#134]
In future versions of IGV viewer, would it be possible to add the ability to keep by default the view settings (click on right on bam file)? for example, we use in our laboratory by default the BAM files viewing in mode “squished” and sort “alignment by bases”: it is very very convenient!

**Comment by ylipacbio** [comment]
Dear IGV developers,

I want to automatically generate IGV snapshots with `squished` view using igv bash script, without having to launch IGV GUI, load genomes, change view each time.

`igv.perf` is very useful configuring many attributes, but I haven't found one for toggling `squished` view.
 Is there an attribute to toggle `squished` view in perf? Where should I look for such information? It doesn't have to be document, source code is also fine.

Thanks!

**Comment by jrobinso** [comment]
Apologies for the delayed response.    There is no such preference currently,  I will leave this issue open until we add one.

**Comment by helgathorv** [comment]
Released in IGV 2.8.0
