### ISSUE TITLE
Sure select XT HS2

### ISSUE THREAD

**Issue by BioMilano** [igvteam/igv#1340]
Dear all, 
we are Bioscience genomics from Milan. 

We are contacting you because we are introducing a new library protocol with duplex molecular barcodes (Sure select XT HS2, agilent) and we cannot understand how to see our NGS results on IGV.  Sequencing was made with - NovaSeq 6000 S4 - 100 PE.
Below we attached the screenshot of what we see in Surecall software and what we see in IGV

![image](https://github.com/igvteam/igv/assets/135981798/3239670e-a3e6-493a-b534-2136adc5827c)
question: In this context a read pair In IGV is a duplex consensus sequence?

Let us know if it is all clear. 
Thanks, 
Bioscience Genomics

**Comment by jrobinso** [comment]
Sorry I don't understand the question.  The IGV view is showing you the read alignments.  It looks like you have selected "color by read strand".   I don't see any pairs in the screenshot.

You might find this useful.  https://software.broadinstitute.org/software/igv/AlignmentData
