### ISSUE TITLE
Can't open .json file 

### ISSUE THREAD

**Issue by chorong5155** [igvteam/igv#1341]
I created .json file to load in IGV but I could not open it..

https://m-b55e05.a0115.5898.data.globus.org/projects/b1154/referenceGenomes/hg38%2BVacV/hg38VacV.json 

What can I change to make it work..?

**Comment by jrobinso** [comment]
I can't answer your question because its too vague, what exactly are you trying to do?   

Also I can't access that json file.  Please zip and attach it here, or just paste the contents here.

**Comment by chorong5155** [comment]
so I have this .fna file combined human and virus genome..
then, I made it to .json file.. to open in IGV so I can see my .bam files aligned with genome seq.

{
  "id": "hg38VacV",
  "name": "hg38plusVacV",
  "fastaURL": "https://m-b55e05.a0115.5898.data.globus.org/projects/b1154/referenceGenomes/hg38%2VacV/hg38%2VacV.fna",
  "indexURL": "https://m-b55e05.a0115.5898.data.globus.org/projects/b1154/referenceGenomes/hg38%2BVacV/hg38%2BVacV.fna.fai",
  "chromosomeOrder": [
    "chr1",
    "chr2",
    "chr3",
    "chr4",
    "chr5",
    "chr6",
    "chr7",
    "chr8",
    "chr9",
    "chr10",
    "chr11",
    "chr12",
    "chr13",
    "chr14",
    "chr15",
    "chr16",
    "chr17",
    "chr18",
    "chr19",
    "chr20",
    "chr21",
    "chr22",
    "chrX",
    "chrY"
  ],
  "tracks": [
    {
      "name": "Refseq Genes",
      "format": "refgene",
      "url": "https://s3.amazonaws.com/igv.org.genomes/hg38/ncbiRefSeq.sorted.txt.gz",
      "indexURL": "https://s3.amazonaws.com/igv.org.genomes/hg38/ncbiRefSeq.sorted.txt.gz.tbi"
    },
    {
      "name": "Gencode v24 genes",
      "format": "gtf",
      "url": "https://m-b55e05.a0115.5898.data.globus.org/projects/b1154/referenceGenomes/hg38%2BVacV/hg38%2BVacV.gtf"
    }
  ]
}

I could open this file, is that the reason why I can not load in IGV?
it says, I have to log in to access to this file. but where in?

**Comment by jrobinso** [comment]
How exactly are you trying to open it?  I can't guess what you are doing you have to tell me.

**Comment by jrobinso** [comment]
And log in to acces which file?  It must be the "gencode v24" genes file, if that requires a login you won't be able to use that URL with IGV.

**Comment by chorong5155** [comment]
I am trying to load it by trying 
Genomes > Load genomes from file..

**Comment by chorong5155** [comment]
I used following 👍 {
  "id": "hg38VacV",
  "name": "hg38plusVacV",
  "fastaURL": "https://m-b55e05.a0115.5898.data.globus.org/projects/b1154/referenceGenomes/hg38%2VacV/hg38%2VacV.fna",
  "indexURL": "https://m-b55e05.a0115.5898.data.globus.org/projects/b1154/referenceGenomes/hg38%2BVacV/hg38%2BVacV.fna.fai",
  "chromosomeOrder": [
    "chr1",
    "chr2",
    "chr3",
    "chr4",
    "chr5",
    "chr6",
    "chr7",
    "chr8",
    "chr9",
    "chr10",
    "chr11",
    "chr12",
    "chr13",
    "chr14",
    "chr15",
    "chr16",
    "chr17",
    "chr18",
    "chr19",
    "chr20",
    "chr21",
    "chr22",
    "chrX",
    "chrY",
    "chrVacV"
  ],
  "tracks": [

    {
      "name": "Gencode v24 genes",
      "format": "gtf",
      "url": "https://m-b55e05.a0115.5898.data.globus.org/projects/b1154/referenceGenomes/hg38%2BVacV/hg38%2BVacV.gtf"
    }
  ]


but I still get the same warning, that I need to log in.
I still doubt you not being able to open my .json, made me think that it has something to do with my link.

**Comment by jrobinso** [comment]
When I try to access the files your reference (e.g. the fastaURL)  I get at 500 error from the server.
