### ISSUE TITLE
Gapped transcript/protein-genome alignment visualisation available?

### ISSUE THREAD

**Issue by imichalop** [igvteam/igv#1345]
Dear all,
Known transcript and/or protein sequences are rarely misaligned to their corresponding genomes due to errors in genome sequencing and assembly or frameshift mutations. The "gap" attribute in GFF3 accommodates for such discrepancies:
https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md#the-gap-attribute
I wonder if IGV is able to parse the content of the gap GFF3 attribute and visualise the indel event. If this is the case, I would be indebted if you show an example of how a GFF3 should represent an indel event. If this is not the case, I wonder if you intend to add such functionality in forthcoming releases.
Thank you in advance.
Yours Faithfully,
Dr Ioannis Michalopoulos

**Comment by jrobinso** [comment]
Apologies for the delayed response,  this fell through the cracks as they say.   This is not possible in IGV, and unlikely to be implemented without significant demand given the number of higher priority issues currently open.
