### ISSUE TITLE
Want to filter VCF from 1000 Genomes by attribute

### ISSUE THREAD

**Issue by sooheelee** [igvteam/igv#135]
Here is what I've done and I've made the files read-public via my GenomeSpace account so you can test also. The bug is in filtering VCF data using Tracks>Filter Tracks in Step 7 below. I am wanting only to show super_pop + contains + EUR. However, data remains unfiltered.
1. Load Human hg19 genome onto IGV.
2. Then "Load from URL" VCF file (TBI file is already in same directory) and Sample Info file onto IGV:
3. https://dm.genomespace.org/datamanager/file/Home/soh33l33/1KG/ALL.chrX.phase3_shapeit2_mvncall_integrated_v1a.20130502.genotypes.vcf.gz
4. https://dm.genomespace.org/datamanager/file/Home/soh33l33/1KG/integrated_call_samples_v3.20130502.ALL.panel
5. These files correspond to data from chromosome X only. Type in OPN1LW to go to this loci. This loci codes for one of the three opsins expressed in the eye that help us differentiate color. It codes for the long wave (LW) sensitive light detecting opsin that is implicated in the most common form of color blindness, red-green color vision deficiency.
6. Right-click track window and select "Set Feature Visibility Window" to increase the threshold from 10 to 20. Data will load in the window.
7. We want to differentiate VCF tracks by population and gender, as red-green color vision deficiency is most frequent in males of European ancestry. Go to Tracks>Filter Tracks. Change the three fields to  super_pop + contains + EUR and press OK. Only European (EUR) ancestry tracks should remain. Click on "gender" in the attributes panel header to sort by gender.
8. and so on.

**Comment by jrobinso** [comment]
Confirmed the bug.   At the code level there is 1 track, including all the samples,  so grouping, filtering, and sorting samples within the vcf track is a special case.  Filtering was never implemented, although grouping and sorting were.

**Comment by jrobinso** [comment]
As a workaround, you can group by population then scroll down to the group of interest (EUR in this case).  "Squishing" the track enables all EUR samples to be seen in one screen.

**Comment by sooheelee** [comment]
Thanks Jim. I will use this workaround.

Soo Hee Lee, Ph.D.
Science Technical Writer

**Comment by chichaz31** [comment]
Hello, was there any update on this functionality since 2015 ? I am looking for a way to filter my samples  in a track by attribute : ex mean depth > 5. But when i try to apply the filter Track parameter nothing happens.
