### ISSUE TITLE
Base modification menu improvements

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#1350]
I'm opening an issue to invite discussion on base modification menu options for alignment tracks.    This represents a generalization of the '6mA' option discussed in PR #1342 .    I specifically would appreciate feedback on naming the various menu options.   We have 2 basic visualization schemes.  The first is specifically for CpG methylation (5mC and 5hC) designed to emulate the bisulfite sequencing scheme.    It uses a 2 color red/blue scheme to represent the presence or absence of the modification, with alpha transparency used to represent the probability.    The second is a general mono-color representation applicable to all modifications,  with again alpha used to reflect probability.    

In the next release a specific menu option is presented for each modification present in the loaded alignments.  Selecting a specific modification will filter others.  This is an extension of the "6mA" option from PR #1342.    This new feature neccesitates a rethink of the menu option names, mainly because either the two-color or mono-color viz can be used for 5mC.  So we need to distinguish.   See the screenshot below, this is a working idea, is it clear enough?   @ctsa @mrvollger

I think some education by way of documentation will be required, not everything can be conveyed in menu names, but I don't want to make things worse.

<img width="291" alt="Screen Shot 2023-06-27 at 12 45 41 PM" src="https://github.com/igvteam/igv/assets/933148/84175cb6-8ba7-48ee-818b-03d9e37e5b29">

**Comment by ctsa** [comment]
The first segment of the menu is confusing. Based on the discussion above, this might be closer to what the options select for:

```
5mC modification (CpG)
5mC modification (all C)
```

**Comment by jrobinso** [comment]
Thanks, I can make that change.  The most accurate description would probably be `5mC modification (red/blue)` .

Actually it occurs to me I should check modifications present for the CpG menu as well, so if there is no 5hmC or others the "all C" can be dropped.

**Comment by jrobinso** [comment]
BTW the "(all C") means to show all C modifications, not just 5mC,  maybe that's still not clear.

**Comment by jrobinso** [comment]
Maybe should just be explicit, the difference in the menus are the first set (1) can only be used for modifications to "C", and (2) are two color.

**Comment by jrobinso** [comment]
I think this has been addressed.
