### ISSUE TITLE
MM/ML tags

### ISSUE THREAD

**Issue by SanityTree** [igvteam/igv#1351]
Hello,

Not so much an issue, but I could not find anything in the documentation (I may have missed it). Is igv able to read MM/ML tags from BAM files?

**Comment by jrobinso** [comment]
Yes it is.   If the tags are present you will find options to color by modifications in the popup menu, under "Color by...".   See also https://github.com/igvteam/igv/wiki/5mC-coloring-mode

**Comment by jrobinso** [comment]
See also https://github.com/igvteam/igv/wiki/5mC-coloring-mode

**Comment by AjaxWho** [comment]
Hi @jrobinso, with respect to visualizing modifications on igv, is it possible to filter 6mA modification levels based on the ML tag value? e.g., filter out modifications with ML tag values =< 204 (80% of 255)?

**Comment by jrobinso** [comment]
That's currently not possible.   If you would like to request this please open a new issue with a descriptive title.   I'm going to close this issue.
