### ISSUE TITLE
Hosting "json formated" genome files on local server  ? 

### ISSUE THREAD

**Issue by denoualflo** [igvteam/igv#1353]
Hi,

Is there a way to locally host several genomes defined with a JSON file instead of the now deprecated .genome file (according to this page : https://github.com/igvteam/igv/wiki/JSON-Genome-Format) to help users to select one genome ?

Maybe something like this: (based on genomes.txt existing format)

```
<Server-Side Genome List>
Human hg38 https://myserver/hg38/hg38.json hg38
Human hg19 https://myserver/hg19/hg19.json hg19
Sar-cov-2 https://myserver/sc2/sc2.json sarcov2
```

With hope, I tried this example (with IGV Desktop) but it failed.
Logs return "Severe" error -> "Foud invalid server genome list record: Human hg38 https://myserver/hg38/hg38.json hg38 

I couldn't find any specific information about serving JSON files instead of using the 'Load Genome from URL' option, but I would like to avoid using it if possible.

Thank you

Regards

**Comment by jrobinso** [comment]
Yes, json files are the preferred format.  Is your genome list file tab delimited?

**Comment by denoualflo** [comment]
I do not check that, my vscode converted my tab entry in spaces
With tab it is okay now.
Sorry for this a little bit stupid issue :)

Thank you
