### ISSUE TITLE
chimeric alignments split screen?

### ISSUE THREAD

**Issue by itslittman** [igvteam/igv#1356]
How do I view a chimeric transcript in split screen?

**Comment by lbergelson** [comment]
@itslittman There is no way to do that in the current release.  In the next release there is a right click option to open the related chimeric reads in split screen.  They won't be automatically linked together but it's 1 click to open them in split screen.  

There's also a new diagram which will show the structure of the whole set of chimeric reads and allow some navigation between them which should be helpful.
