### ISSUE TITLE
Broken link on https://software.broadinstitute.org/software/igv/VCF

### ISSUE THREAD

**Issue by nrockweiler** [igvteam/igv#1358]
Hi, 

On https://software.broadinstitute.org/software/igv/VCF, the there is a link that points to http://software.broadinstitute.org/software/igv/viewing_variants.  The latter URL gives a 404 error.

<img width="614" alt="image" src="https://github.com/igvteam/igv/assets/8428293/a9619d22-233b-4bb8-bef9-60900d323194">

**Comment by nrockweiler** [comment]
There are quite a number of broken links elsewhere.  I think the issue is stemming from the broken links using http rather than https.

Notedly, the search button is broken.

**Comment by helgathorv** [comment]
Thanks - I noticed that when I looked into your initial report. Am fixing them now ...

**Comment by helgathorv** [comment]
I fixed the links (although it's possible I missed some - feel free to reopen if you come across any). However, the search button cannot be fixed at this time. But the good news is that we are close to finishing a move of the documentation to a new system that will also include a search feature.
