### ISSUE TITLE
Issues Loading Custom Genome

### ISSUE THREAD

**Issue by k-kiani** [igvteam/igv#136]
I'm trying to load a custom viral genome .fa file into IGV, but 5 bases are being cut off somewhere though it's not clear from where because the beginning and end of the IGV file match my fasta file. Thanks!

**Comment by jrobinso** [comment]
What leads you to think 5 bases are being cut off?  Have you done an independent count of the # of bases in the fasta?     To investigate we will need the fasta.

**Comment by k-kiani** [comment]
The problem has been resolved. User error. Thanks for your time!
