### ISSUE TITLE
Batch script does not include junctions in exported image

### ISSUE THREAD

**Issue by christopher-holt** [igvteam/igv#1366]
When I use run a batch script in IGV, the track for the splice junctions is present, but the junction connections are not displayed when the image is exported. Is there a way to fix this?

**Comment by jrobinso** [comment]
I can't reproduce your issue.  The script below creates the attached snapshot.  If you can provide a script that reproduces the issue, and verify you are using the latest IGV version (2.16.2),  I will look into it further.  

```
new
genome hg19
load https://www.broadinstitute.org/igvdata/tutorials/SL2C5A3/liver.bodyMap.bam
goto slc25a3
snapshot
``` 

![chr12_98,985,464_99,002,145](https://github.com/igvteam/igv/assets/933148/d9e177f5-06e6-43d8-9e76-1fa0011fd992)
