### ISSUE TITLE
cBioPortal plugin Regions>Gene Lists>Retrieve Network gives null error

### ISSUE THREAD

**Issue by sooheelee** [igvteam/igv#137]
Links in the documentation showing what IGV should do:
    http://www.broadinstitute.org/software/igv/gene_list_view
    http://www.broadinstitute.org/software/igv/cbio_viewer

Description of bug:
cBio Portal plugin Regions>Gene Lists>Retrieve Network gives "Error loading data: null" message. 

Additional info that may be helpful:
I checked out the CBio Portal's site and the network drawing tool is only a feature for their predefined datasets under "example queries". Perhaps it used to be a feature that allowed user-specified input. The network drawing feature derives from PathwayCommons [http://www.pathwaycommons.org/about/], which is from the Bader Lab that we know as the Cytoscape/GeneMania folks. GeneMANIA is the plugin Cytoscape uses to find other genes related to the input genes using functional association data, which sounds much like what we are trying to do with Retrieve Network. Of course, there are now many other network association tools since PathwayCommons was released that if you are interested I can provide as a biased list.

![screenshot 2015-04-29 12 47 20](https://cloud.githubusercontent.com/assets/11543866/7415076/8b911c40-ef24-11e4-868d-f4df612d01e7.png)

**Comment by helgathorv** [comment]
Also reported by user on igv-help on 6.8.2015
