### ISSUE TITLE
vcf files only show Zoom in to see features

### ISSUE THREAD

**Issue by 1090585084** [igvteam/igv#1370]
Hello, I encountered some issues while using IGV to visualize vcf files. The software only displays Zoom in to see features. There are no other displays, how can I resolve them.
![O98L6P}{_ELM_E}5512X NH](https://github.com/igvteam/igv/assets/63289856/a255a2fb-629b-4813-9e7c-fffc86202f93)

**Comment by jrobinso** [comment]
I think you also asked this question on igv-help.  It's not neccessary to post the same question in multiple places.

As the message indicates, you need to zoom in to see the vcf features.    You cannot in general load and view VCF variants at whole genome view.
