### ISSUE TITLE
Moving to the next variant from a short insertion variant loses the reads

### ISSUE THREAD

**Issue by nh13** [igvteam/igv#1371]
Suppose I am viewing a VCF and associated BAM file, and currently looking at the reads showing a short (<10bp) insertion.  If I "expand" the insertion to see the inserted bases, highlight the variant track, then use "ctrl-F" to move to the next variant, IGV will not display any reads (and no coverage histogram).  If I go back to the previous variant, not only do I see the reads, but if I "reload the tracks", highlight the variant track, then use "ctrl-F" to move to the next variant, the reads are displayed correctly for the next variant (a deletion).

So I _think_ it's moving to the next variant when a current insertion is expected which is the issue I am seeing.  

I also see that the sequence track is also not displaying all the bases, which is resolved by "reload the tracks":
![Screenshot 2023-08-07 at 4 03 25 PM](https://github.com/igvteam/igv/assets/846274/d41c7401-1ae6-4e0f-a574-bec67a74166a)

Bonus question: is there a way to "collapse" an insertion?

**Comment by jrobinso** [comment]
Hey Nils good to hear from you, even if its an issue :).    We'll check it out.

**Comment by jrobinso** [comment]
OH, to collapse an expanded insertion you are supposed to be able to click either end of the expand icon and toggle the expansion, but it is very finicky, buggy even.   The whole thing is a bit 1/2 baked to be honest.   We'll look into improving this also.  

If you could give us a small test case that would be helpful, although probably this isn't hard to reproduce.

@lbergelson am I correct in recollecting you have fixed some things related to expanded insertions?   Perhaps the behavior is better in the unreleased code?

**Comment by jrobinso** [comment]
Well, that escalated quickly.  This will not be news to you but there were many issues with expanded insertions.   I just finished a major re-do,  it should fix this issue as well as others.  Also I made a UI change, the insertion markers are now just over the coordinate "ruler".   You can now close them by clicking the expanded icon.  

This will hopefully get released in the next few weeks.  If you want to try it in the meantime you can use  the snapshot.

https://software.broadinstitute.org/software/igv/download_snapshot

**Comment by jrobinso** [comment]
This should be fixed with release 2.17
