### ISSUE TITLE
Question about view the VDJ Outputs through IGV

### ISSUE THREAD

**Issue by q541425866** [igvteam/igv#1372]
Hi, I I want to check the "all_contig.bam" file of  10x VDJ outputs through IGV, the error is as follows. The genome is "Human(GRCh38/hg38)". Please help me to deal with it. Thanks.
![20230809095254](https://github.com/igvteam/igv/assets/105573515/d9ddf6ab-81d4-4ea3-9481-f5b4b9871c3c)

**Comment by jrobinso** [comment]
The error message indicates there is no match in the sequence names in your BAM file and the sequence names in the reference genome you have selected (GRCh38 in this instance).
