### ISSUE TITLE
Can't access entire track menu on a small screen

### ISSUE THREAD

**Issue by diekhans** [igvteam/igv#1376]
On a Mac Air M1 13" screen, opening the alignment track menu goes of the bottom of the screen and does not scroll.  Thus is it not possible to remove an alignment track.

One would expect the menu to scroll once you hit the bottom.

**Comment by jrobinso** [comment]
Yes I would expect that too.   I'll see what we can do about it.

**Comment by diekhans** [comment]
I am surprised it didn't "just work"; let me know if you want me to test it.

thanks for supporting it; IGV has become an essential tool!

**Comment by jrobinso** [comment]
Yes me too but the menu is too long.  The solution is to redesign this as another type of widget.  This might take a little time.   In the meantime, for an admittedly extreme workaround you can try changing your display settings to the smallest pixel size ("more space" on the setting scale).

**Comment by jrobinso** [comment]
FYI, we're addressing this by making the menu smaller, its too large in any event.   This change will be in the next release, sometime in September,  if you want to try it before then you can use the "Development snapshot" build available from the downloads page.  https://software.broadinstitute.org/software/igv/download_snapshot

**Comment by jrobinso** [comment]
@diekhans I love Santa Cruz,  we had an ITCR conference there a few years ago.
