### ISSUE TITLE
Error in opening IGV

### ISSUE THREAD

**Issue by HuynhThienPhai** [igvteam/igv#1378]
Hi,

I installed IGV () in Debian12 (wget-->unzip). I have a problem when opening it by executing the command ./igv.sh. 

The output is
-----------------------
echo Using bundled JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
INFO [Aug 22,2023 18:58] [Globals] Development mode is enabled
Aug 22, 2023 6:58:30 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
INFO [Aug 22,2023 18:58] [Main] Startup  IGV Version 2.14.1 09/02/2022 12:22 AM
INFO [Aug 22,2023 18:58] [Main] Java 11.0.13 (build 11.0.13+8) 2021-10-19
INFO [Aug 22,2023 18:58] [Main] Java Vendor: Eclipse Adoptium https://adoptium.net/
INFO [Aug 22,2023 18:58] [Main] JVM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8   
INFO [Aug 22,2023 18:58] [Main] OS: Linux 6.1.0-11-amd64 amd64
INFO [Aug 22,2023 18:58] [Main] IGV Directory: /home/huynhtp/igv
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
INFO [Aug 22,2023 18:58] [CommandListener] Listening on port 60151
INFO [Aug 22,2023 18:58] [GenomeManager] Loading genome: https://s3.amazonaws.com/igv.org.genomes/hg19/hg19.json
INFO [Aug 22,2023 18:58] [TrackLoader] Loading resource:  https://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/ncbiRefSeq.txt.gz
INFO [Aug 22,2023 19:01] [ShutdownThread] Shutting down
----------------------
And then, there is a black window with untidy icons appears.

P/S:  java -version
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8+7-Debian-1deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.8+7-Debian-1deb12u1, mixed mode, sharing)

**Comment by jrobinso** [comment]
There's not enough information here to diagnose the problem, but I have 2 suggestions to try.   (1) download the latest version, (2) do not use the bundled JAVA version, rather use your locally installed Java.    To do this download the package labeled "for all platforms",  i.e. this version:  
https://data.broadinstitute.org/igv/projects/downloads/2.16/IGV_2.16.2.zip

**Comment by QR3704** [comment]
Hi, I have just started working on Ubuntu/command line with zero background. I installed IGV_Linux_2.16.2 in Ubuntu 22.04. Executing command ~$ IGV_Linux_2.16.2/igv.sh does'nt open igv and gives error. 

echo Using bundled JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
INFO [Nov 17,2023 17:08] [Globals] Development mode is enabled
INFO [Nov 17,2023 17:08] [Main] Startup  IGV Version 2.16.2 07/14/2023 12:24 AM
INFO [Nov 17,2023 17:08] [Main] Java 11.0.13 (build 11.0.13+8) 2021-10-19
INFO [Nov 17,2023 17:08] [Main] Java Vendor: Eclipse Adoptium https://adoptium.net/
INFO [Nov 17,2023 17:08] [Main] JVM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8
INFO [Nov 17,2023 17:08] [Main] OS: Linux 4.4.0-19041-Microsoft amd64
INFO [Nov 17,2023 17:08] [Main] IGV Directory: /home/raza/igv
SEVERE [Nov 17,2023 17:08] [DefaultExceptionHandler] Unhandled exception
SEVERE [Nov 17,2023 17:08] [DefaultExceptionHandler] java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(Unknown Source)
        at java.desktop/java.awt.Window.<init>(Unknown Source)
        at java.desktop/java.awt.Frame.<init>(Unknown Source)
        at java.desktop/java.awt.Frame.<init>(Unknown Source)
        at java.desktop/javax.swing.JFrame.<init>(Unknown Source)
        at org.igv/org.broad.igv.ui.Main.lambda$main$0(Main.java:108)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

INFO [Nov 17,2023 17:08] [ShutdownThread] Shutting down

Java --version
openjdk 11.0.20.1 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)


Please help to resolve this issue. Thanks

**Comment by QR3704** [comment]
I'm using Windows 10 WSL feature for Ubuntu.

**Comment by jrobinso** [comment]
I don't know anything about Windows 10 WSL, but from the message you need to set your X11 display.   

`No X11 DISPLAY variable was set, but this program performed an operation which requires it.`
