### ISSUE TITLE
1000Genomes VCFs load as separate tracks for the different chromosome files that represent an identical sample set

### ISSUE THREAD

**Issue by sooheelee** [igvteam/igv#138]
Loading to 1KG VCFs representing different chromosomes, i.e. X and 7, loads the files as separate tracks in which sample labels are identical sets. “Combine data tracks” does not work here and I get “No Tracks Found” in the dialog. Changing Preferences to load all tracks in same panel also failed to merge the chromosomes. At this stage, load gene list view does not work at all but this will become irrelevant when this bug is fixed. Gene list view works fine for single track VCFs, e.g. just chromosome X data.

To recapitulate this bug here are the steps:
* Connect to 1000genomes AWS S3 bucket in your GenomeSpace account. Within the GS app, this is under Connect>Amazon S3>Public S3 Bucket>, then enter "1000genomes". 
* Make sure you log into this specific GenomeSpace account on IGV. You can do this when prompted at the next step.
* Load via URL these two files for chrX and chr7 (copy-paste these): <https://dm.genomespace.org/datamanager/file/Home/s3:1000genomes/release/20130502/ALL.chrX.phase3_shapeit2_mvncall_integrated_v1a.20130502.genotypes.vcf.gz> and <https://dm.genomespace.org/datamanager/file/Home/s3:1000genomes/release/20130502/ALL.chr7.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz>.
* I don't know if it's relevant that I had two additional files loaded when I encountered this bug. Here are the additional files: <https://dm.genomespace.org/datamanager/file/Home/s3:1000genomes/release/20130502/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5a.20130502.sites.vcf.gz> and <https://dm.genomespace.org/datamanager/file/Home/s3:1000genomes/release/20130502/integrated_call_samples_v3.20130502.ALL.panel>.
* The 4 genes to input into Regions>Gene Lists>My lists>New are OPN1LW, OPN1MW, OPN1MW2, and OPN1SW. The first three are on chrX and the 4th is on chr7.

![screenshot 2015-04-29 12 32 23](https://cloud.githubusercontent.com/assets/11543866/7415045/766b171c-ef24-11e4-8de8-fba920cdd3aa.png)

Tried to copy-paste my session file contents for the above but it shows up blank here. Here is a link to the session file in my GenomeSpace account:
<https://dm.genomespace.org/datamanager/file/Home/SpaceCadet/Tetrachromats/1KG_X&7.xml>

**Comment by sooheelee** [comment]
I tried the genelist view again for the two chromosome files and it works fine. Here is a link to the session file:
<https://dm.genomespace.org/datamanager/file/Home/SpaceCadet/Tetrachromats/1KG_X&7_4geneview.xml>

**Comment by jrobinso** [comment]
The problem here is the vcf data for each chromosome is loaded from separate files,  and separate files mean separate tracks.  Using a "list" file to combine the vcfs might work.

**Comment by jrobinso** [comment]
Closing, nothing to do here.
