### ISSUE TITLE
Feature request: Separate group for insertions in base_at_pos grouping

### ISSUE THREAD

**Issue by DevangThakkar** [igvteam/igv#1380]
Hi,

IGV currently has the ability to group reads based on the base at a given position. This is very helpful when looking at a SNV - for a SNV at chr1:50, grouping reads at chr1:50 works as expected. It also has support for deletions, although that requires some adjustment since a deletion of, say, GATTACA->G at chr1:100 needs to be grouped at position chr1:101 and not chr1:100 to obtain reads with a deletion at chr1:100 in a separate grouping.

However, I don't believe there is a way to group reads based on an insertion since it's not tied to either position - for a G->GATTACA at chr1:150, sorting either by chr1:150 or chr1:151 is ineffective. It would be helpful to have this functionality.

I use a batch script (IGV version 2.14.1) to generate multiple screenshots and I can change my positions by 1 for deletions, but I wanted to raise this point for discussion - should the behavior be similar for deletions and SNVs?

Thank you for your time.

Cheers,
Devang

**Comment by jrobinso** [comment]
Yes I agree insertions should be supported.  WRT position,  we could use the convention that the position of an insertion is the base just to the right, that is next position after the insertion.   Sorting and the coverage track popup text already use this convention.

I'm not sure I understand your comment on deletions.  The "pos" column as you would find in a VCF is not sufficient for precise position.   If I understand your example the leading "G" is at position chr1:100.   That could also be represented as TGATTACA->TG,  where T is at chr1:99.  The VCF position would be chr1:99 although the actual deletion has not changed.    So there is always some calculation involved in mapping a VCF "pos" to the actual position of the event for everything other than SNVs.

**Comment by DevangThakkar** [comment]
Thank you for considering the insertion feature request. My understanding is that the "correct" way to describe variants, specifically indels, is to normalize them. More on variant normalization [here](https://genome.sph.umich.edu/wiki/Variant_Normalization). (The link used to work before, but it didn't right now so here is an [archived version here](https://web.archive.org/web/20230124183225/https://genome.sph.umich.edu/wiki/Variant_Normalization)). 

In brief, it says that variants should be parsimoniously represented

>  A variant is parsimonious if and only if it is represented in as few nucleotides as possible 
  without an allele of length 0.
  A variant has superfluous nucleotides on its left side if the leftmost nucleotide of each variant is of the same type 
  and the removal of the nucleotide from each allele will not result in an empty allele.
  
So that  would mean that representing the variant as TGATTACA->TG would not be the standard way to represent it. Hope that makes more sense. 

To reiterate, I am okay with indels being grouped using the +1 position, it just threw me off when it wouldn't group the reads correctly.

**Comment by jrobinso** [comment]
It might not be standard or recommended but it is legal according to the spec,  in fact there is nothing about normalization that I can find in the spec:  https://samtools.github.io/hts-specs/VCFv4.2.pdf.   IGV at one time implicitly assume normalization to place variants but this is actually incorrect, due to representations such as my example above (and I've seen many more bizarre ones than that).   So we now don't assume anything and compute it.  

In any event this is a side tangent as we are talking about grouping reads not interpreting VCFs.    This works of course without any reference to VCFs, and it would be a bit strange to consider deletions to "occur" at one position to the left of where they actually are.   Insertions are a special case since they by definition are between 2 reference positions, so we just need a convention for that.   So we use the base just to right, i.e. the following base.

**Comment by jrobinso** [comment]
In sort I think its incorrect to say the "pos" field in a VCF refers to the position of the variant, that is not its definition, it is simply the position of the first base in the ref & alt sequences.   For SNVs this is of course also the position of the variant.

**Comment by DevangThakkar** [comment]
I agree, that makes sense to me!

**Comment by jrobinso** [comment]
I've implemented this for the next release.    Its a new option, overloading "base" to include insertions is too messy.   The insertion can be either side of the specified position,  consider it "adjacent" to the position.  Groups are formed based on the length of the insertion.    The batch command looks like this

```
group insertion chr21:26001843
```
