### ISSUE TITLE
What is the best method to use IGV to view structural mutations？

### ISSUE THREAD

**Issue by user-tq** [igvteam/igv#1383]
This is a great tool.
But the usage instructions related to structural variation seem to be lacking, which makes me a bit confused.
I need to visualize  bam file（illunima PE）.
 I  chose ```group by alignment pair orientation```,and Through the screen splitting method [here](https://software.broadinstitute.org/software/igv/AlignmentData#paired), i chose ```View mate region in split screen``` .

![image](https://github.com/igvteam/igv/assets/72878144/1b7cff74-7e33-4496-b80c-ad717064da71)

Of course, this is consistent with the results I obtained from delly's bcf.
```
2	29448234	INV00000097	A	<INV>	10000	PASS	PRECISE;SVTYPE=INV;SVMETHOD=EMBL.DELLYv1.1.6;END=29448692;PE=345;MAPQ=60;CT=3to3;CIPOS=-4,4;CIEND=-4,4;SRMAPQ=60;INSLEN=0;HOMLEN=3;SR=20;SRQ=1;CONSENSUS=AATCAGGGGCTCCTCAGGGAACTGCAGCTGCTCTGGTGGGGGGAAGGTTGGGAGCTTCCGTTTTGGCTTGGCCTGGGCTGCCCTAATCACCACCCCACCCAATTCCAGGGACTAGCATAACGAATGTTTCAAACCAACATCCCGCCACTGATATTCATCC;CE=1.9883	GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV	0/1:-153.834,0,-420.992:10000:PASS:1330534:2579570:993231:2:2340:347:170:80
2	29448310	DUP00000099	G	<DUP>	1200	PASS	PRECISE;SVTYPE=DUP;SVMETHOD=EMBL.DELLYv1.1.6;END=42507520;PE=0;MAPQ=0;CT=5to3;CIPOS=-2,2;CIEND=-2,2;SRMAPQ=60;INSLEN=0;HOMLEN=2;SR=20;SRQ=0.994792;CONSENSUS=TAAGGAAATGGCCATTGGTTTATTTTTCCCTACAATGTTTTAGACTAGGACTTTATAGTATCACTTTGTATTCGGGCTCTGTGCACTCACCAATCATGATGCCGGAGAAAGCCAGGACCAGGGCGGCCACGAGGGCAGAGGTCACCACAGAGAGGATCAGCGAGAGTGGCAGGTGTGGCTCCGGGGTGGGTG;CE=1.98362	GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV	0/0:0,-75.1503,-755.993:10000:PASS:191585:102194:98208:1:0:0:250:0
```
This makes me a bit confused, there are too few reads on the left screen. Is it due to downsampling?How many reads does this variant be supported?
I wonder if there's anything like 'View split reads in split screen',
This seems more conducive to finding breakpoints
Of course, Delly's results also surprised me,(the RV=0).
Thank you for any advice

**Comment by jrobinso** [comment]
The reads on the left are definitely downsampled, you can tell by the black bars under the coverage graph.  See the user guide for details on downsampling.    There is a "view split reads in split screen" in the development build, which will be released by the end of September.   If you would like to try it before then you can use the snapshot build:  https://software.broadinstitute.org/software/igv/download_snapshot
