### ISSUE TITLE
The batch control of igv docs still up to date?

### ISSUE THREAD

**Issue by jpfacio** [igvteam/igv#1384]
Hi, I'm writing a program and I want to open automatic sessions in IGV, the batch scripts in IGVs website still works or there is a better way to do it?

**Comment by jrobinso** [comment]
I'm not sure what you mean by "open automatic sessions".    The batch commands as described here are up-to-date as far as I know:  https://github.com/igvteam/igv/wiki/Batch-commands

**Comment by jrobinso** [comment]
Given your use case why do you need to execute any commands.  You can open the xml session when IGV starts with a command line argument.   You don't even need an xml session if you are opening IGV on a single file.

**Comment by jrobinso** [comment]
Actually I think you are asking about command line arguments, not batch commands,  if that's the case yes these are still up to date:  https://github.com/igvteam/igv/wiki/Command-Line

**Comment by jpfacio** [comment]
I think this is what I need, thanks. In order to open an IGV session from the command line with a loaded bedgraph file I would use the -i parameter, right? This would work for a xml file too?

I'm sorry if I'm not making myself clear, english isn't my first language

Thanks

**Comment by jrobinso** [comment]
No, you do not use any flags.  Simply

```
igv.sh myBedgraphFile.bed
```

Or if you want to create a session (generally not recommended)

```
igv.sh mySessionFile.xml
```
