### ISSUE TITLE
Support for Ultima Genomics data

### ISSUE THREAD

**Issue by ilyasoifer** [igvteam/igv#1393]
Hello, 
My name is Ilya Soifer. I work at Ultima Genomics. 
We would like to contribute few small change that facilitate investigation of Ultima Genomics data
Specifically, we developed some features that allow to easier investigate the certainty of insertions and deletions. 
What would be the most reasonable way to submit this
Thanks!
Ilya

**Comment by jrobinso** [comment]
The starting point would be a pull request.

**Comment by ilyasoifer** [comment]
Thanks @jrobinso, we will create a PR in the near future

**Comment by ilyasoifer** [comment]
The PR was merged, closing
