### ISSUE TITLE
Support bedMethyl format. 

### ISSUE THREAD

**Issue by ArtRand** [igvteam/igv#1396]
Hello, 

Jumping off from: https://github.com/nanoporetech/modkit/issues/43

I develop a tool for secondary analysis of base modification data, modkit. One use case it fulfills is to generate "bedMethyl" tables. The schema of these tables have been described by [Encode](https://www.encodeproject.org/data-standards/wgbs/), [modbam2Bed](https://github.com/epi2me-labs/modbam2bed), and again my [modkit](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#bedmethyl-column-descriptions). In principal, they're all BED files, however to load the tables generated by modkit, I need to use spaces to delimit the fields after the 10th field. Perhaps not surprisingly, this causes a bunch of downstream headaches, but it was important to me that the output of the tool can be immediately loaded into IGV. 

This issue is to track the ability of IGV to load bedMethyl tables such as those produced by modkit when only tabs are used to separate the fields. (Modkit has an --only-tabs flag to allow this). 

Please find a "tab-only" version output here: https://raw.githubusercontent.com/nanoporetech/modkit/master/tests/resources/modbam.modpileup_nofilt.bed

The reference for this BED can be found at: https://raw.githubusercontent.com/nanoporetech/modkit/master/tests/resources/CGI_ladder_3.6kb_ref.fa

**Comment by jrobinso** [comment]
OK this format will be supported in release 2.17.0, targeted for the end of October.  To test or use it before then you can download our snapshot build from here: https://software.broadinstitute.org/software/igv/download_snapshot

If you have a "bigBed" version please point me to it, or upload it here.   It should just work but it would be good to test it.

**Comment by ArtRand** [comment]
@jrobinso Sounds good. I'll add bigBed output to `modkit`, It's a feature that's been requested before.

**Comment by jrobinso** [comment]
@ArtRand I have a question on your sample file, it seems to have more columns than the spec defined, for example

```
chr20	22613919	22613920	h	2	+	22613919	22613920	255,0,0	2	0.00	0	2	0	0	0	0	0
```

The spec defines 2 extra columns

* Coverage, or number of reads
* Percentage of reads that show methylation at this position in the genome

The extra columns should be harmless,  just noting this.

**Comment by jrobinso** [comment]
OK this is set for the next release, 2.17.0, sometime in October.

**Comment by jrobinso** [comment]
OK, but only the first 11 are specified here:
https://www.encodeproject.org/data-standards/wgbs/.  If you want to include
the rest in the popup text we can do that,  but there is nothing in the bed
file itself to tell us what they are.   With bigBed you can define this in
autosql, and in fact every file could have a different set of extra
columns,  with "bed" type files you just have to know.

Until release the new support is only available in the snapshot build for
IGV desktop,  and https://igv.org/app-test for the webapp.

**Comment by jrobinso** [comment]
Ahh, o.k., in one of these tickets someone directed me to the Encode site.   I'll update to use this as the spec: https://github.com/nanoporetech/modkit/blob/master/book/src/intro_bedmethyl.md

**Comment by jrobinso** [comment]
I added support for all columns in the javascript version, will do desktop soon, but first look at the column names.  They can be whatever you like, just post corrections here.

<img width="271" alt="Screen Shot 2023-09-28 at 11 07 50 PM" src="https://github.com/igvteam/igv/assets/933148/8e958919-c618-4a3f-93e7-d9d3c4cc3bd3">

**Comment by ArtRand** [comment]
@jrobinso This is great, thanks. I'm assuming I can modifiy modkit so that the output always "all-tabs" (previously all-tabs required a flag)? I can test on both platforms, of course. BigBed output may not come in the next release - but a fast follow since it will be nice for things like DMR output as well.

**Comment by jrobinso** [comment]
For IGV purposes BigBed is not so important now that bedmethyl is a recognized format.   Its nice for unknown bed formats because the # of defined fields and names of the extra columns can be discovered in the BigBed autoSql.   Also good if your files get large.

**Comment by JoukjeKloosterman** [comment]
Hello,

I am wondering if the release is ready? I am having the same issue as @ArtRand as described by his first message.
I have a Bedmethyl file i would like to load into IGV.

**Comment by jrobinso** [comment]
@JoukjeKloosterman Working on it, its a big release, however you can get a preview here: https://igv.org/doc/desktop/#DownloadSnapshot/

**Comment by maximilianh** [comment]
@ArtRand Is modKit now making bigBed files? Or can it get an option to make bigBed files? At UCSC, we're interested in that, because bigBed files can be loaded remotely, into any genome browser. the text formats needs to be uploaded, so they cost us storage and they're slower to load. Also, bigBed includes the data description, the little .autoSql file, with the field names and descriptions. If you could support bigBed files, you could tell your users that they can load these files really anywhere.
