### ISSUE TITLE
IGV macOS download link missing from website

### ISSUE THREAD

**Issue by rquigley-aus** [igvteam/igv#1405]
Hi Team,

This isn't an issue with the software, simply an issue regarding the missing link towards downloading the macOS version of IGV from the new download page

[https://igv.org/doc/desktop/#DownloadPage/](https://igv.org/doc/desktop/#DownloadPage/)

It shows versions for Windows and Linux but not for macOS, could this please be added?

Many thanks!

**Comment by jrobinso** [comment]
Ah, thanks for pointing that out.  In the meantime these are the links

Java included:
https://data.broadinstitute.org/igv/projects/downloads/2.16/IGV_MacApp_2.16.2_WithJava.zip

Use your own Java:
https://data.broadinstitute.org/igv/projects/downloads/2.16/IGV_MacApp_2.16.2.zip

**Comment by helgathorv** [comment]
Again, thanks for letting us know. This has now been fixed.
