### ISSUE TITLE
Gene List does not recognize Gencode genes

### ISSUE THREAD

**Issue by sooheelee** [igvteam/igv#141]
Gene List recognizes HGNC gene symbols that correspond to RefSeq track features (e.g. OPN1LW) and also UCSC annotation track features (e.g. P04000). However, it does not recognize Gencode genes format features (e.g. ENST00000369915.3).

**Comment by jrobinso** [comment]
It recognizes whatever is searchable, which in turn depends on what annotation tracks you have loaded.
