### ISSUE TITLE
Minimum junction coverage doesn't exclude low-coverage junctions

### ISSUE THREAD

**Issue by hbeale** [igvteam/igv#1411]
If I set minimum junction coverage to 50, I still see junctions with just one read. 

Steps:
IGV 
New session
View|Preferences, RNA, Minimum junction coverage to 51
set genome to hg38
open bam file
go to my gene
click on junction track, select expanded
hover over thin junction arc and see low depth values, e.g. 2 or 1

Thanks in advance for your insights!

**Comment by UdoUnnoetig** [comment]
I do have the same problem. I tried changing View>Preferences>RNA>minimum junction coverage and it rarely ever removes junctions with lower coverage. It doesn't seem to matter if the value set first or the .bam file is loaded first or whatever sequence of actions I do. I can't see what produces this problem.
