### ISSUE TITLE
IGV BLAT issue: copied sequence from right-click menu of an input sequence for BLAT, the actual copied sequence is from the reference sequence and not the input

### ISSUE THREAD

**Issue by santataRU** [igvteam/igv#1419]
Hi, IGV support team,

After I entered a sequence to BLAT (Tools --> BLAT) to the hg38 genome, the sequence can be mapped in the genome. However, after I right-click the mapped sequence and choose "Copy Sequence", the copied sequence is from the reference sequence and not from the input BLAT sequence. Is this normal?   If the input BLAST sequence contains indels, I would like to copy the actual BLAST sequence rather than the reference sequence, which is wild type.

My IGV version is 2.16.2 in Mac OS Monterey.

Thanks,

Xiao

**Comment by jrobinso** [comment]
Yes that's normal,  actually I don't know what you mean by the "BLAST" sequence.   Do you mean the input sequence?   The output of blast is just alignments, there is no sequence output.

**Comment by santataRU** [comment]
Hi, Jim,

Yes I mean the input sequence, I found that in IGV, there is a BLAT feature
(Tools --> BLAT), and I use this feature to blast the input sequence with
reference. Why does IGV use "BLAT" instead of "BLAST"?

Another problem I have is that the BLAT does not work for custom genomes
(it only works for genomes default in IGV such as hg38 and mm10). I wonder
if this is normal.

Thank you!

Xiao

**Comment by jrobinso** [comment]
BLAT uses the UCSC server,  and only supports genomes known to that server.   You can also run a server locally, details are here: https://igv.org/doc/desktop/#UserGuide/tools/blat/

Does the genome you are interested in have a "GCA" or "GCF" accession number?  If it does you can try adding the following property to your genome.json file

```
"blatDB":  "<your genome accession>"
```

**Comment by santataRU** [comment]
Hi, Jim,

Thank you very much!  How do I know if my sequence has a "GCA" or "GCF"
accession number? Do I need to blast my sequence in the NCBI database and
get these numbers from the NCBI database if there is a match in the blast
results?

Xiao

**Comment by jrobinso** [comment]
I'm referring to the accession number of the assembly.   Not the sequence.  If you don't know the accession number of your assembly, or it doesn't have an accession, this doesn't apply.

**Comment by santataRU** [comment]
I see. Thank you!

Xiao
