### ISSUE TITLE
Sequence Translation Tracks Rearranging When Dragging Genome Files in IGV

### ISSUE THREAD

**Issue by eyetoey3** [igvteam/igv#1420]
Hello,

When dragging genome files into IGV, I've noticed that the three types of sequence translation tracks are rearranged in the vertical order. This may be a little bit misleading, especially when I need to examine the presence of stop codons in the amino acid coding of a long open reading frame.
Here is a video. 
https://github.com/igvteam/igv/assets/87290652/24f58986-5ed3-4012-90f8-f145a7b7cbec
In this gene, two rows have plenty of stop codons, one have none, it's obvious to notice. I wonder whether it is a bug or if there's a specific pattern to this rearranging.

Thanks,
Irica

**Comment by jrobinso** [comment]
I think you mean the rows are rearranged?   I think it would be easier to see what's going on if you zoomed in to see the amino acid boundaries and letters.    The order of the rows is arbitrary,  and I can imagine they could get rearranged during dragging,  although I can see how that might be visually confusing.    The stop codons are still there, and in the same genomic positions.

**Comment by eyetoey3** [comment]
Thanks for reply. Yes, what I mean is that the sequence translation rows are rearranged.
I know that the stop codons do not change its position actually. However, in which case, for example, I need to check for the presence of a stop codon in the first row of translation in a very long genome region (up to 10kb). When I drag to the middle of that region, the order of the three rows gets randomly rearranged, causing my first row of interest to shift to either the second or third row. This results in inadvertently seeing a wrong stop codon on the first row, leading to a wrong judgement of this translation.
And most of the time, these rearrangements happen very quickly, making it hard to notice. Is there any solutions?

**Comment by jrobinso** [comment]
Nothing you can do at the moment, other than reporting the issue here.

**Comment by edeaguiar** [comment]
This is still an issue for the Mac IGV in the most current 2.19.2 version
