### ISSUE TITLE
How to display bedpe files in straight line form?

### ISSUE THREAD

**Issue by GleeenSIBS** [igvteam/igv#1422]
Hello!
I want to display the bedpe file in the form of a straight line instead of an arc, but I can't find the corresponding operation mode, please give me a solution, thank you!
IGV version is 2.12.2.
Glen

**Comment by jrobinso** [comment]
I'm not sure what you mean "straight line", could you elaborate?  If you use bedpe you will get arcs, but perhaps there is some other format.

**Comment by GleeenSIBS** [comment]
I mean, turning an arc into a straight line, like this:
I——I
loop anchors are in the form of blcok segments.
My bedpe files just include 6 columns, viz chr1,start1,end1,chr2,start2,end2.
Thanks!

**Comment by jrobinso** [comment]
There are no settings to do that in IGV

**Comment by maximilianh** [comment]
This made me laugh: We've had this problem come up forever in the UCSC browser. Arcs are not always useful for all people, they look pretty but are not very helpful in many cases. So we switch off the arcs in certain display modes, which is of course completely obscure to the poor users. 

To make your bedpe use straight lines, the easiest solution is probably to convert the file to a normal BED file or bigBed and with two exon-like blocks, one for each side of the connection...
