### ISSUE TITLE
strands for reverse stranded

### ISSUE THREAD

**Issue by zjanna** [igvteam/igv#1432]
Dear all ,
 I have a query about the strands that IGV shows for my bams and for the reference. What we see in the splice junction track does not agree with what we should see according to the manual - i.e. that the colour of these arc depends on the strand on which the gene is on and in these bams it is exactly the opposite (red arc for the gene that is on the minus strand). 
In this print screen I have that gene FOXJ3 is on the - strand but in my bam Junctions track there is a red line and I can see that is + strand.(the oposit with LMO4)
Does this mean that the bam files have been mapped incorrectly? My protocol is reverse stranded and for mapping I used this option.
I would be very grateful for your help and guidance.
Best wishes, Joanna 

![LMO4](https://github.com/igvteam/igv/assets/9252183/84490b6e-4803-4e3d-af68-835261f54a5f)
![FOXJ3](https://github.com/igvteam/igv/assets/9252183/80421c92-e989-4be0-8fb9-c499a3b663b8)

**Comment by jrobinso** [comment]
Hi, sorry for the delay in a response.   

If the alignments have an "XS" tag, which is recommended for stranded RNA data, strand is determine by that tag.    If it does not, IGV has to guess.   For paired alignments the strand is assumed to be the strand of the first-in-pair.   This can be incorrect for some libraries,  but when it is it should be consistently flipped.   So please interpret accordingly.   

In all cases the strand is determined from the alignment data, it has no connection to the Refseq Genes track or any other track.
