### ISSUE TITLE
RefSeq track disappears from IGV

### ISSUE THREAD

**Issue by didkovn** [igvteam/igv#1436]
The default RefSeq track URL specified in the hg38.json file must be the same as the RefSeq URL specified in the xml session file, otherwise the RefSeq track disappears when the sesson is loaded. 

To reproduce:
In my hg38.json file, I see a URL at ucsc.edu: 
"url": "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ncbiRefSeq.txt.gz",

In an IGV session file of mine, the RefSeq Track has a URL served from a different URL, at amazonaws.com:
  <Track attributeKey="Reference sequence" clazz="org.broad.igv.track.FeatureTrack" colorScale="ContinuousColorScale;0.0;836.0;255,255,255;0,0,178" fontSize="10" groupByStrand="false"  id="https://s3.amazonaws.com/igv.org.genomes/hg38/ncbiRefSeq.txt.gz" name="Refseq Genes" visible="true"/>

When I launch IGV and open this session, the RefSeq track disappears.  This is the problem.

If I change the URL in the Track of the session xml file to the UCSC URL, it loads as expected. 
Similarly, if I change the URL in the hg38.json to the amazonaws URL, it also loads as expected.
It works as long as the URL's are the same.

So it seems whenever the "url" value in hg38.json is different from the URL in the session's Reference Sequence xml session file, the RefSeq track disappears

The behavior I would like to see is that IGV successfully loads the RefSeq track that is specified in the session xml file even if it is different from the default.

**Comment by jrobinso** [comment]
@didkovn Apologies I thought I could replicate this situation but I haven't been able to.   Could you zip and attach one of the problematic sessions?

**Comment by jrobinso** [comment]
Also verify the version of IGV you are using.  Thanks.

**Comment by jrobinso** [comment]
Never mind, I got it.
