### ISSUE TITLE
The hg38 genome lacks mitochondrial gene information

### ISSUE THREAD

**Issue by fo40225** [igvteam/igv#1439]
When choosing Human (GRCh38/hg38) or Human (hg38 1kg/GATK), the chrM does not display RefGene-related information. Only NC_012920 has gene information.

![1](https://github.com/igvteam/igv/assets/10285869/185e01b4-3841-4600-a129-0017ab257896)
![2](https://github.com/igvteam/igv/assets/10285869/f8bc6c58-a89e-4b52-99be-24d56ef1c946)
![3](https://github.com/igvteam/igv/assets/10285869/b721d7a9-0bde-4c31-876b-a47638dd338a)

**Comment by maximilianh** [comment]
Excellent question.

The reason why NCBI has no chrM annotations in the ncbiRefSeq GFF file and
they're not considered RefSeq genes is that these genes are not part of
RefSeq, but a different part of NCBI (bacteria databases/pipelines) and
they don't have RefSeq accessions, but special YP_ accessions. You can see
that here: https://www.ncbi.nlm.nih.gov/gene/4535 - no RefSeq accession.

We could revisit this. I've always thought that this makes no sense for
users. We could also have the NCBI RefSeq Other track as a default track.
We could also reach out to NCBI for an opinion.

**Comment by jrobinso** [comment]
@maximilianh I could add the ability to load a different annotation set for chrM / MT.  Its a bit of a hack, but this is an important special case.

**Comment by maximilianh** [comment]
The "different annotation set" is our "RefSeq Other" track, so you can see
these annotations, you just have to switch it on.

The reason why we haven't changed this, so "forced" the transcript into the
"RefSeq curated" track is that we try not to change the annotations as they
were provided by the data provider and one annotation track should be a
consistent set of annotations, with e.g. same outlinks, same identifiers.
In this case, the chrM annotations are in the GFF file but are not part of
RefSeq, so, for example, the annotations don't have accessions and the
outlinks back to NCBI won't work:
https://www.ncbi.nlm.nih.gov/nuccore/?term=YP_003024026.1+AND+srcdb_refseq%5BPROP%5D
I'll discuss some more with my colleagues, we usually talk over things many
times before we come to a good solution. If you have suggestions or
thoughts, don't hesitate to send them to, it would be good to be consistent
between the browsers on important genes like this. We could also ask RefSeq
to make these genes "real" genes and at least give us a way to link to them.

**Comment by maximilianh** [comment]
This is a bug on our side. Either related to a file format change by NCBI
at some point or something that sprang loose during release. We have code
to catch the YP_ genes and put them into the curated track but it didn't
work.

**Comment by maximilianh** [comment]
It turns out that RefSeq changed the format of the GFF file 2-3 years ago
and we didn't notice, since the genes were still there, just in the wrong
track.

I think I've fixed this now, can you look at
https://genome-test.gi.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chrM and
see if the genes that you're looking for are there? We can then re-release
the track, and IGV can import the new file.

Another user just noticed on our mailing list that the IGH genes are not in
the curated track either. They're similar, have no RefSeq accession, but
also, they're not real transcripts. So these are also in the "other" track
now, but maybe we should move them?

Same for pseudogenes and TCR segments. These are also in the "other" track.

**Comment by jrobinso** [comment]
Sorry I was mistaken, we do use http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ncbiRefSeq.txt.gz.   I will switch to a bigGenePred when available.

**Comment by maximilianh** [comment]
Sorry, I fixed this but forgot to reply: 
main problem is solved: on chrM, the gene annotations are now in the curated subset, so in the same file with all other genes, even if they don't have proper RefSeq accessions. we provide the YP_ protein accessions now in lieu of RefSeq nucleotide in that file, which means that outlinks will work. 

On your questions:
> I will switch to a bigGenePred when available.
Looks like we haven't made the switch ourselves yet on hg38. But I changed the main .txt.gz file so no need to switch.

> It occurs to me you already provide a BigGenePred file in GenArk, several in fact. RefSeq All, 
> Curated, Predicted, etc. Do any of these directly correspond to ncbiRefSeq.txt.gz?
Yes, all Genark RefSeq assemblies so those with GCF_ IDs have a bigGenePred ncbiRefSeq, e.g. in https://hgdownload.soe.ucsc.edu/hubs/GCF/003/597/395/GCF_003597395.1/bbi/GCF_003597395.1_ASM359739v1.ncbiRefSeq.bb. There also is a "predicted" file, for most assemblies, the "predicted" file is probably what you want to show by default, as there is almost no curation outside of the typical model organisms by RefSeq, I assume: https://hgdownload.soe.ucsc.edu/hubs/GCF/003/597/395/GCF_003597395.1/bbi/

**Comment by northwestwitch** [comment]
Hello, we're having this bug where MT genes are not displayed in the browser. We're currently using this file: `https://s3.amazonaws.com/igv.org.genomes/hg38/refGene.txt.gz`. Which annotation should we switch to instead? 
Many thanks!

**Comment by jrobinso** [comment]
As noted above

```
https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ncbiRefSeq.txt.gz
```

**Comment by northwestwitch** [comment]
> As noted above
> 
> ```
> https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ncbiRefSeq.txt.gz
> ```

Thanks @jrobinso!

**Comment by jrobinso** [comment]
In the next release you will be able to select that annotation used by default for a genome.   In the interim, if you are comfortable doing it you can edit the "hg38.json" file in your igv/genomes folder.   Just replace the 'url' property in the annotation track with the one above.
