### ISSUE TITLE
N+n MM tag display bug

### ISSUE THREAD

**Issue by AlexCalderwood** [igvteam/igv#1444]
Hello,

It seems that positions tagged using the MM base-modification tag N+n (see https://samtools.github.io/hts-specs/SAMtags.pdf top of page 9) overflow the coverage track when select colour alignments by > base modification.

no color by chosen:
![Screenshot 2023-11-27 at 15 00 12](https://github.com/igvteam/igv/assets/17953270/28a65506-6255-4faf-8eb3-7ad7a56a7b81)

color by base modification:
![Screenshot 2023-11-27 at 14 59 26](https://github.com/igvteam/igv/assets/17953270/c0fba2f6-c632-4247-98aa-e78eba5c6bd1)

IGV v2.16.2

demo reads:
[test_Nn.sam.txt](https://github.com/igvteam/igv/files/13476767/test_Nn.sam.txt)

**Comment by jrobinso** [comment]
That's not surprising, this is the first N+n example I have seen.  I will get to this when I can.
