### ISSUE TITLE
In what case there are RR reads but no LL reads?

### ISSUE THREAD

**Issue by Chen-Jingfang** [igvteam/igv#1449]
Hi,
When I use the orientation of Illumina paired reads to detect inversions, I found a region only have RR reads, see the picture below.
From User Guide, when an inversion shows up in paired-end reads, there should be both RR reads and LL reads. So I can't understand why there are only RR reads. Looking forward to your help. 

![image](https://github.com/igvteam/igv/assets/73156566/086a8cb7-bbcf-48b5-acb5-0dbf350a5c6b)

**Comment by jrobinso** [comment]
I don't know what situation would cause this.  You might post your question to a general analysis forum, like SeqAnswers.
