### ISSUE TITLE
alignments starting with "D" CIGAR operation not correctly rendered 

### ISSUE THREAD

**Issue by AndrewUzilov** [igvteam/igv#145]
Similar to #144.

Test data here (for hg19):
https://github.com/AndrewUzilov/BugReports/tree/master/2015_05_07.igvBug2

See screenshot below with two alignments (BAM file is in test data above):
```
@SQ	SN:chr1	LN:249250621
fakeRead001_WRONG	0	chr1	1234567	255	8D10M	*	0	0	GGCCGGAGCC	*
fakeRead001_CORRECT	0	chr1	1234567	255	10M	*	0	0	GGCCGGAGCC	*
```

The sequence of both alignments is supposed to be identical to reference, but clearly alignment `fakeRead001_WRONG` is rendered incorrectly.

Affects: IGV v2.3.51.

Screenshot:
![igvbug](https://cloud.githubusercontent.com/assets/124773/7519237/d4e0373a-f4ad-11e4-92af-3fb3e5476546.png)

**Comment by jrobinso** [comment]
I disagree on this, alignment one is rendered as indicated by the cigar.

**Comment by jrobinso** [comment]
Perhaps you intend to use a hard clip operator, rather than "D". 8H10M 
would be identical visually to 10M,  8D10M is not.

**Comment by AndrewUzilov** [comment]
From SAM/BAM spec (18 Oct 2013 version), the `POS` column is:

```
POS: 1-based leftmost mapping POSition of the first matching base. The first base in a reference sequence has coordinate 1. POS is set as 0 for an unmapped read without coordinate. If POS is 0, no assumptions can be made about RNAME and CIGAR.
```

So, position 1234567 should thus indicate the start of the `10M` block in `8D10M`, as it is the first actual alignment match.

I know this is not a common representation, but as explained in #144 rationale, my intention is to test edge cases against the SAM/BAM spec.  The spec does not seem to expressly forbid starting with a delete operation.

**Comment by jrobinso** [comment]
Without a real case,  and agreement on this interpretation from the 
broader community,  I am would be hesitant to make this change.   I 
suggest you start a discussion in the relevant forum,  samtools help or 
the new ga4gh on this issue.

I will make the change for consecutive soft clips as it is harmless, and 
not subject to interpretation,  but its not a priority without a real 
case from a real aligner.

**Comment by AndrewUzilov** [comment]
Sounds reasonable.  Which samtools help forum?  This one?
https://sourceforge.net/p/samtools/mailman/samtools-help/

**Comment by jrobinso** [comment]
Hi,

I just posed your question on samtools-devel@lists.sourceforge.net, you 
can follow or comment on it there.   If the consensus is your 
interpretation of the spec is correct it is easy enough to change.

Jim

**Comment by AndrewUzilov** [comment]
Thanks Jim, I will post there.

**Comment by jrobinso** [comment]
I posted, just look for the discussion.  Two authorities on the sam spec, Heng Li (original author) and Peter concurr with IGV's current inerpretation.   You can open a discussion on the spec there, but I am going to close this issue.
