### ISSUE TITLE
The "Refseq Genes" track of IGV disappeared

### ISSUE THREAD

**Issue by yqxopq** [igvteam/igv#1456]
Hi,

   The  "Refseq Genes" track disappear from my IGV (latest release of IGV Desktop: 2.16.2/2.15.4)，would you tell me how to solve this problem？Thank you so much！

![IGV](https://github.com/igvteam/igv/assets/153061441/82ef1098-4aee-4665-97cf-ae5abef67689)

Sincerely yours,

**Comment by jrobinso** [comment]
Try refreshing your "hg19" genome.  You can do this from "Genomes > Select
Hosted Genome".   Select "Human (hg19)" and click "OK".

**Comment by yqxopq** [comment]
I tried refreshing  my "hg19" genome before,  and I also tried to reinstall the IGV software, unfortunately it didn't work.  Is there any other way to solve this problem?  Thank you so much！

**Comment by yqxopq** [comment]
Steps：
File→Load from File→*.sort.bam


"igv.log" file:
[igv.zip](https://github.com/igvteam/igv/files/13597493/igv.zip)

**Comment by jrobinso** [comment]
Note to self -- try to catch this error and present a helpful message.

**Comment by maximilianh** [comment]
We deactivated all blocks on our site a few months ago. Many thanks for
this ticket, we really need to check with our central campus IT what’s
going on.

Did you try to download this file from a normal internet browser ? Can you
access the hgdownload server ?

**Comment by yqxopq** [comment]
Yes，I successfully downloaded the ncbiRefSeq.txt.gz file at home, and the "Refseq Genes" track displayed normally in the IGV software when using the home network, but failed while I used the company's network.

**Comment by jrobinso** [comment]
Hi @yqxopq ,  yes you can download all files locally,  instructions are [here](https://igv.org/doc/desktop/#UserGuide/reference_genome/),  but in your case if you are only interested in hg19 its is very simple.  In your "igv/genomes" folder you should find an "hg19.json" file.   Make a copy of that file, and edit the copy.   Change the ID property from "hg19" to something else.  Under the "tracks" section you will find the refseq entry.   Change the "url" value to a full file path to your ncbiRefSeq.txt.gz file.    Its important you save this file with a different name as igv/genomes is a cache, and the files can get automatically updated in the future.     You might also change the "name" property to avoid confusion in your pulldown list.   Restart IGV and it should find your copy.

Alternatively, and even easier,  just load your local file from the "File" menu as an additional track.

**Comment by jrobinso** [comment]
RE your colleagues, they might be using older cached versions of the genome definition file (hg19.json).   In the past we indexed and hosted the refSeq files on our own servers.   However we now load directly from the UCSC browser to insure users are always getting the most up-to-date annotation, and that it is consistent with the UCSC browser.

**Comment by jrobinso** [comment]
I'm closing this as its a network issue IGV has no control over.
