### ISSUE TITLE
Set file type independently of extension

### ISSUE THREAD

**Issue by danvk** [igvteam/igv#146]
I'm using the IGV listener port to configure a few tracks in IGV from a web app. I do this by issuing an XHR to:

`http://localhost:60151/load?user=foo&genome=hg19&file=http://example.com/foo.vcf&name=Run&locus=1:5466526`

I don't control the file names, however, and sometimes they lack the `.vcf` suffix. For example, they might be generated by a spark job and look like `http://example.com/foo.vcf/part-r-00000`.

I know for a fact that these are VCF files. Is there any way to tell IGV that via the `/load` URL?

**Comment by jrobinso** [comment]
No there is not,  there should be but there isn't.   I will fix this and 
reply here when the fix is available.

**Comment by danvk** [comment]
Fantastic, thank you!

**Comment by jrobinso** [comment]
This should be available now in the "snapshot" build.

**Comment by danvk** [comment]
Thanks for the quick turnaround, @jrobinso. Any guess when this will roll out into an IGV release?

**Comment by jrobinso** [comment]
Within a week,  I just did one and am working on some other bugs.
