### ISSUE TITLE
Building against htsjdk/4.0.2

### ISSUE THREAD

**Issue by pgrt** [igvteam/igv#1461]
Hello,

You might be interested in knowing that igv can be built successfully against new htsjdk/4.0.2, one only needs to remove an ambiguity in the tests as htsjdk 4 introduces a class named NamedFeature, which also exists in igv.

The enclosed patch fixes this.

Best,

Pierre

[htsjdk4.txt](https://github.com/igvteam/igv/files/13672386/htsjdk4.txt)

**Comment by jrobinso** [comment]
Thanks, but the corresponding class in IGV was renamed to IGVNamedFeature at the time we updated htsjdk to 4.0.2.  Are you sure you are using the latest code?

**Comment by pgrt** [comment]
Hi,

Sorry, I missed #1413 about this. I am using tags to grasp new versions, which is why I had not seen it as I tsill have version 2.16.2. All good then, thanks!
