### ISSUE TITLE
Right click issue in IGV macos

### ISSUE THREAD

**Issue by huangnengCSU** [igvteam/igv#1462]
Hi,

When I right click to open the menu, occasionally the program will execute, opening the menu and automatically clicking on an option. I am using the igv (version 2.16.0) in MacOS, and this problem has not occurred with igv in Windows. This problem seems to exist in versions with the feature of setting small indel threshold in right click menu.

Best

**Comment by jrobinso** [comment]
I can't reproduce this problem.  If you can find reproducible steps to reproduce it please re-open.
