### ISSUE TITLE
Less options color by base modification

### ISSUE THREAD

**Issue by JoukjeKloosterman** [igvteam/igv#1465]
Hello,

I have a cram file with base modification. When reading your documentation I see 6 different colouring options:

![image](https://github.com/igvteam/igv/assets/144109774/0ca81242-3a19-497f-97a9-5e9f408a7aa8)

When loading my own data into the IGV desktop, version 2.16.2, application, I only see three options:

![image](https://github.com/igvteam/igv/assets/144109774/cc6d01e5-14c7-4d0a-a674-ff219316e105)

However, I also used the snapshot version for a while, and when I wanted to color the base modifications of the same sample, i saw the six options again:

![image](https://github.com/igvteam/igv/assets/144109774/df7ed1d7-ecf4-44e5-9333-14b613940e1c)

Why is there a difference? And how can it be fixed? Or is de documentation based on the snapshot? The version of the snap shot is from 26 september 2023.

**Comment by jrobinso** [comment]
The documentation in this case is ahead of the release.  If you need the new options continue to use the snapshot,  these features will be released sometime this month.

**Comment by jrobinso** [comment]
Released in 2.17.0
