### ISSUE TITLE
Unable to copy/paste from the read popout panel in MacOS

### ISSUE THREAD

**Issue by jamesemery** [igvteam/igv#1469]
I have noticed an issue using v16.2 (and this issue has been around in various old versions like v14) that if you are looking at the IGV app and click to open a read pane that it is not intractable by the OS. There is no way to drag-select any of the data in the read pane but you can double-click to select some elements of the reads. However if you try to copy-paste in MacOS while the read pane is selected you get the ENTIRE read pane context copied into your clipboard even if you visually have highlighted just a spicific annotation that you might want. 

This behavior is mildly annoying and it would be nice to be able to drag-select tags/annotations/elements of the poped out reads pane into the clipboard for use rather than having to copy it elsewhere to get what I want to see. At the very least it would be nice to prevent the text pane from letting you visually highlight the text in order to disabuse myself of the idea that I COULD be copying what I want.

**Comment by jrobinso** [comment]
What exactly do you mean by "read popout panel".   Are you using mouse hover text or popup on click?  A screenshot might help.

**Comment by jamesemery** [comment]
Here is an example. You can see that I have the reference span for the "popup on click" pane for one of my reads. However I am unable to copy paste just the highlighted selection. Instead the OS seems to select the entire text of the read pane. 

![Screenshot 2024-01-19 at 1 53 57 PM](https://github.com/igvteam/igv/assets/16102845/f3d1e76d-94fa-439f-b2f2-ed0c69421b03)

**Comment by jrobinso** [comment]
OK thanks,  I'll investigate.
