### ISSUE TITLE
IGV (>= 2.17.0): igv.sh --version gives error on Java 11, but not on Java 17

### ISSUE THREAD

**Issue by HenrikBengtsson** [igvteam/igv#1472]
On an up-to-date Rocky 8 Linux, running Java 11;

```
$ java -version
openjdk version "11.0.21" 2023-10-17 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.21.0.9-1) (build 11.0.21+9-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.21.0.9-1) (build 11.0.21+9-LTS, mixed mode, sharing)
```

IGV 2.17.0 and IGV 2.17.1 fails `--version` with:

```sh
$ /path/to/IGV-2.17.0/igv.sh --version 
Using system JDK.
Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 61.0

$ /path/to/IGV-2.17.1/igv.sh --version 
Using system JDK.
Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 61.0
```

whereas it works with 2.16.2 and before:

```sh
$ /path/to/IGV-2.16.2/igv.sh --version 
Using system JDK.
OpenJDK Runtime Environment (Red_Hat-11.0.21.0.9-1) (build 11.0.21+9-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.21.0.9-1) (build 11.0.21+9-LTS, mixed mode, sharing)
INFO [Jan 24,2024 19:28] [Globals] Development mode is enabled
2.16.2
```

With Java 17:

```sh
$ java -version
openjdk version "17.0.9" 2023-10-17 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.9.0.9-1) (build 17.0.9+9-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.9.0.9-1) (build 17.0.9+9-LTS, mixed mode, sharing)
```

it seems to work, modulo some warnings:

```sh
$ /path/to/IGV-2.17.0/igv.sh --version 
Using system JDK.
WARNING: Unknown module: jide.common specified to --add-exports
WARNING: Unknown module: jide.common specified to --add-exports
WARNING: Unknown module: jide.common specified to --add-exports
WARNING: Unknown module: jide.common specified to --add-exports
WARNING: Unknown module: jide.common specified to --add-exports
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
WARNING: Unknown module: jide.common specified to --add-exports
WARNING: Unknown module: jide.common specified to --add-exports
openjdk version "17.0.9" 2023-10-17 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.9.0.9-1) (build 17.0.9+9-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.9.0.9-1) (build 17.0.9+9-LTS, mixed mode, sharing)
2.17.0
```

Same for IGV 2.17.1.

I've used <https://data.broadinstitute.org/igv/projects/downloads/2.17/IGV_2.17.1.zip> here.

**Comment by jrobinso** [comment]
IGV 2.17 requires Java 17, as noted on the downloads page.

**Comment by HenrikBengtsson** [comment]
Oh, thanks for clarifying.  I was reading <https://github.com/igvteam/igv#building>, which still says:

> IGV requires **Java 11** to build and run.   Later versions of Java should work but we build and test  on **Java 11**. Previous (versions =< 2.6.3) running on Java8 have been deprecated.

**Comment by HenrikBengtsson** [comment]
> IGV 2.17 requires Java 17, as noted on the downloads page.

FWIW, maybe also add "requires Java 17" as plain text to <https://igv.org/doc/desktop/#DownloadPage/> (if that's the download page you're referring to).  Right now that info is only available in non-accessible/non-searchable/non-indexable images.

FWIW2, <https://igv.org/doc/desktop/#ReleaseNotes/2.17.x/> is clear about the Java 17 requirement.

**Comment by jrobinso** [comment]
Good suggestion, I will update the Downloads page to make this more
prominent.

**Comment by HenrikBengtsson** [comment]
Thanks for the Download-page updates.  Please note that the README still says Java 11.
