### ISSUE TITLE
ONT bam shows [Malformed CIGAR string] error in IGV 2.17.0 and 2.17.1

### ISSUE THREAD

**Issue by miwi610** [igvteam/igv#1473]
Error arises when trying to view BAM file from ONT (`dorado 0.5.1 sup,5mC_5hmC,6mA`) in both `IGV 2.17.0 `and `2.17.1` for mac, showing following error in `igv.log `and error window shows up every time I try to click something.
`[DataPanel] java.lang.IllegalArgumentException: Malformed CIGAR string: 30H22568M1D-22468H`
This does not occur in` IGV 2.16.2`.
The string is at `SA:Z` tag of BAM file, as shown in below.
`SA:Z:chr20,22334011,+,30H22568M1D-22468H,60,280;`
I attached the part of sam file with this read (macfas5.0 genome).
I am not sure if this is only happening to me or not.
Could you take a look at it and check if it works ?
[visibleData1.sam.zip](https://github.com/igvteam/igv/files/14050554/visibleData1.sam.zip)

**Comment by jrobinso** [comment]
I can reproduce it.  In 2.17 we parse the "SA" tags,  which we did not do previously.   That does not look like a valid SA tag, in particular the presence of the "-" character in the cigar string.    There is a related report here https://github.com/nanoporetech/dorado/issues/496

**Comment by jrobinso** [comment]
According to the ticket linked above this bug was fixed in dorado 0.5.2.    For the time being, if you wish to view files created with dorado < 0.5.2 you will need to use IGV 2.16.2.     We will look into workarounds for the next point release.

**Comment by miwi610** [comment]
Thank you for the link, I did not know.
I guess all I can do for now is, to re-basecall all my data with dorado < 0.5.2.

**Comment by jrobinso** [comment]
Well that's one option, and will have the advantage of making your files compatible with other tools that use that tag.

**Comment by jrobinso** [comment]
In the next release (2.17.2) you should be able to read these files, although supplemental read information will not be available due to the malformed cigar.

**Comment by sklages** [comment]
@jrobinso @miwi610 - consider simply separating the basecalling step (GPU) from the mapping step (CPU) in your workflow. We do this routinely for our P2 runs. This gives you more control on mapping parameters, resources and the aligner itself. The litlle extra time spent on mapping is worth it :-)

**Comment by miwi610** [comment]
@sklages 
Thank you for advice. I am good with current mapping parameter dorado uses or, in other words, I do not know where to adjust to improve mapping quality for my purpose.
But, it is true, it was better for me to run basecalling and mapping, separately, because I had been doing "dorado basecaller" several times per sample, not for improving basecalling, but only for improving mapping output.
I have never done this way, but I guess the procedure would be
(1) `dorado basecaller POD5 > basecall.bam` without reference, outputs unmapped BAM file.
(2) `dorado aligner ref_index basecall.bam > mapped.bam`
I am not sure if (2) works for bam with mapped information. Mapped bam includes secondary alignments and may need to be removed before (2).
Anyway, I got the image, and started to feel this is better for my purpose that, I can modify MM and ML to remove some modification information after (1), then do (2) on this. This was related to my question in other issue.

**Comment by sklages** [comment]
@miwi610 - It is not just to improve mapping, but also to avoid potential issues with the "internal alignment" produced by dorado (there were a few bugs over the time).. 

You can just use your (basecalled and) aligned BAM and realign the reads, see [dorado#196](https://github.com/nanoporetech/dorado/issues/196#issuecomment-1562701192)
