### ISSUE TITLE
Issue with Indel Popup Window Behavior When Hiding Small Indels in IGV

### ISSUE THREAD

**Issue by shuaibw** [igvteam/igv#1480]
I've encountered an issue in IGV where hiding small indels does remove them from view as expected. However, if I click on the region where these indels were previously visible, the indel information popup still appears. This behavior persists even though the indels are set to be hidden. It seems like the graphical representation is removed, but the interactive layer remains active. Is there a way to also disable the popup for hidden indels, or is this an unintended feature?
![image](https://github.com/igvteam/igv/assets/57074038/a2af2617-26b4-481d-ab78-4da2a8fc1235)
![image](https://github.com/igvteam/igv/assets/57074038/94eb2c5b-9b3a-4892-aabc-10af14bd2de2)

**Comment by jrobinso** [comment]
Thanks for the report.   That is not intended behavior, I will look into it.
