### ISSUE TITLE
IGV Refseq error

### ISSUE THREAD

**Issue by starikov-instadeep** [igvteam/igv#1482]
Hello,

Seems like the https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ncbiRefSeq.txt.gz file is corrupted and is not in gzip format. Looking inside the file with `cat` reveals something more  like an sql dump file instead, it's very small, around 1.5kb. The hg19 [file](https://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/ncbiRefSeq.txt.gz) is fine - it's large, gzipped and fine. It's not an IGV problem per se but 
* this track is loaded every time IGV loads giving errors
* I don't think there's a way to run batch scripts explicitly forbidding loading this refseq file, right? This makes all the scripts hang up.

Is there any workaround for this issue? Many thanks.

Best,
Sergey

**Comment by maximilianh** [comment]
Thank you! At UCSC we can fix this problem in a few hours, I hope.

**Comment by jrobinso** [comment]
It looks like this is fixed now.
