### ISSUE TITLE
Bioconda requires openjdk 11

### ISSUE THREAD

**Issue by starikov-instadeep** [igvteam/igv#1483]
Hello,

As far as I understand, IGV now requires Java 17 version but bioconda igv [recipe](https://bioconda.github.io/recipes/igv/README.html) lists `openjdk: 11.*` as a requirement. I was wondering if this should be updated?

Best,
Sergey

**Comment by jrobinso** [comment]
Hi Sergey,  yes it probably should.  I don't know who maintains that but I will see if I can send a PR.

**Comment by jrobinso** [comment]
Actually that recipe is for release 2.16.2,  Java 11 is correct for that version.

**Comment by starikov-instadeep** [comment]
I see, my bad, shoud've checked the version, it's lagging behind. Probably the new version needs to be uploaded but I don't know who maintains it either. Thanks!
