### ISSUE TITLE
IGV release notes UserGuide links are 404 

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#1484]
This is similar/the same as #1466 

I find the problem again in [2.17.x - IGV Desktop Application](https://igv.org/doc/desktop/#ReleaseNotes/2.17.x/)

For example the link is 404 in:

> See the [Reference genome](https://igv.org/UserGuide/reference_genome/#load-a-track-hub) section for more details on how to use a track hub for IGV's reference genome.

**Comment by helgathorv** [comment]
This has been fixed. Thanks for letting us know.

**Comment by malcook** [comment]
thanks - fix confirmed!
