### ISSUE TITLE
gct file oddities

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#1486]
I am trying to "File > Load From URL" [this track](https://research.stowers.org/mec/cpm.gct) which is a [gct file](https://igv.org/doc/desktop/#FileFormats/DataTracks/#gct) holding gene expression data.

It works very nicely as I would expect when the genome is your hosted danRer11 (zebrafish).

However, taking advantage of your new ability to [Load a track hub](https://igv.org/doc/desktop/#UserGuide/reference_genome/#load-a-track-hub), I find that when loading this same track on GCF_001465895.1 (killifish), I get the dialog:

> The probes in the file    https://research.stowers.org/mec/cpm.gct could not be mapped to genomic positions. This can be corrected by specify a probe mapping file from the Preferences window (Probes tab), or by specifing the genomic positions in the expression data file. Please see the user guide for more details.

The first issue I note is that there is no (longer) a Probes tab in the Preferences, so this message needs to be changed.

The .gct file is result of DGE in killifish.  Displaying it over zebrafish works because killifish gene names were annotated by orthology with zebrafish in the first place.  However, the values for the `name` attribute are the refseq identifiers.  The common gene names appear are held in the 'name2' attribute.

I can display name2 in IGV if I right-click on the .gct trace and "set feature label field" to "name2".  

Further, I can search for genes using the "name2" attribute by typing into IGVs search bar.

However, as noted, the .gct file fails to appeal to the "name2".

Is there a possibility of making .gct loading similarly search on the current "feature label field"?

**Comment by jrobinso** [comment]
gct files are not actively supported.  This is a legacy format.  The problem with them is they don't have genomic coordinates, which makes it difficult to know where to place the data.    Given the 121 open issues here and nearly as many in igv.js this is not going to get prioritized.    I would consider a focused PR if didn't touch many files.

You could follow the instructions here and annotate your gct files with genomic positions.   This <should> work, it did at one time.   https://igv.org/doc/desktop/#FileFormats/DataTracks/#gct.

I will change the message.

**Comment by malcook** [comment]
Thanks - I understand. Feel free to close.  

I will follow-up here with my success/failure in annotating the genomic positions as you suggest, if I take that route.

FWIW: I might additionally remark that the documentation of gct handling is misleading where it reads (**_bold/italics_**, mine):

>IGV determines the genomic locations for probes as follows...    IGV searches all loaded annotation tracks for each probe. (**_This is the same as entering the ID in the first column [the Name column] of the file into the search box on the IGV tool bar and clicking Go._**) If a probe is found, IGV displays the data at that location. Otherwise, it goes to the next step.

In this case (at least?) it is decidedly not the same as using the tool bar.

You might like to fix the documentation, or perhaps completely deprecate .gct.

**Comment by jrobinso** [comment]
gct documentation has been removed.   What a complex mess that was.     You can convert .gct files to .tdf with igvtools, see https://igv.org/doc/desktop/#UserGuide/advanced/command_line/#totdf.   That conversion first converts to ".igv" format,  that is not documented but could be made available.

**Comment by malcook** [comment]
Thanks for that tip.  Documenting the gct->igv->tdf conversion sounds in order.

Can you please confirm that such conversion will only work for gct files annotated with genomic positions? I can't see how it could be otherwise, but confirmation is still good...

**Comment by jrobinso** [comment]
gct -> tdf is documented, at the link posted:  https://igv.org/doc/desktop/#UserGuide/advanced/command_line/#totdf.   It uses a bed file for positions (the -p parameter).
