### ISSUE TITLE
Unable to load hg38 genome in 2.17.2

### ISSUE THREAD

**Issue by andyjslee** [igvteam/igv#1492]
I am using IGV 2.17.2 with open-jdk 21 on CentOS. The IGV is stuck loading the genome with the following log message in the terminal:
`INFO [Feb 14,2024 02:33] [GenomeManager] Loading genome: /path/igv/genomes/hg38.json`

I eventually get the error message:
`Error: Could not connect to genome server https://igv.org/genomes/genomes.tsv Trying https://s3.amazonaws.com/igv.org.genomes/genomes.tsv`

For your information, IGV 2.13.2 works fine.

What can I do to fix this issue?

**Comment by jrobinso** [comment]
Are you behind a proxy or firewall that might prevent loading this URL?

`https://igv.org/genomes/genomes.tsv`

**Comment by jrobinso** [comment]
I'm closing this,  I think the admins at UNC have implemented a workaround.
