### ISSUE TITLE
Feature request: Add BCF support

### ISSUE THREAD

**Issue by adrhelix** [igvteam/igv#1495]
Though IGV can display VCF files, I gather that BCF files are not supported.  It would be great if BCF support could be added.

Or if nothing else, hopefully the existence of this issue will make it clearer for someone else that BCF is not currently supported by IGV.  :-)

### What I've tried

When I try loading a BCF, I get the following error message (despite the fact that I have a `*.csi` index file alongside the BCF file):

> An index file for /path/to/my.bcf could not be located. An index is recommended to view files of this size.   Click "Go" to create one now or "Cancel to proceed without an index.

Regardless of whether I click "Go" or "Cancel", I get another error message:

> Error loading /path/to/my.bcf: Unable to parse header with error: Input stream does not contain a BCF encoded file; BCF magic header info not found, at record 0 with position 0:, for input source: /path/to/my.bcf

I have tried multiple BCF files (all valid according to `bcftools view`) from different sources with the same result, so I think my BCF files are validly formatted.  When I run `zcat my.bcf | head -c5 | cat -A`, I see `BCF^B^B`, which I believe are the expected header bytes for BCF2.2.

### Why I think BCF is not supported

The fact that the above error message mentions "BCF" initially made me suspect that BCF files were supported, but further investigation makes me think IGV does not currently attempt to support BCF:
* The [File Formats](https://igv.org/doc/desktop/#FileFormats/DataTracks/) section of the IGV Desktop Application documentation makes no mention of "BCF".
* [This old comment](https://groups.google.com/g/igv-help/c/Z_I_4lGP4sc/m/np-6KFovCwAJ) from 2018 explicitly states that "IGV does not support BCF."
* According to [this more recent comment](https://github.com/igvteam/igv/pull/850#issuecomment-883713725) from July 2021, it sounds as though a lack of BCF support in IGV derives from a lack of BCF support in htsjdk.

P.S. Many thanks for creating such an amazing tool!

**Comment by jrobinso** [comment]
Hi, as you discovered in the user documentation BCF is not supported.    We don't have any plans to support it at this time.

**Comment by nspies-carisls** [comment]
I'm not going to make a strong case for bcf file format support, but it would be great if you could add a more meaningful error message when IGV is asked to open a bcf file. The current error message produced makes it sound like there's something wrong with the file - given how contorted vcf files are, this is entirely believable!
