### ISSUE TITLE
IVG reporting  Zoom in to see coverage/alignments in tiny BAM at 80kb

### ISSUE THREAD

**Issue by diekhans** [igvteam/igv#1497]
IVG 2.17.2

1. Select to T2T CHM13 V2.0
2. Go to chr1:145,265,708-145,345,897 (80 kb)
3. Add this ONT genomic CRAM:
    https://hgwdev.gi.ucsc.edu/~markd/browser/bugs/2024-02-sam-disp-bug/hs1.edit_del58.cram
5. Add this BAM which contains three alignments of one read from the above CRAM
   https://hgwdev.gi.ucsc.edu/~markd/browser/bugs/2024-02-sam-disp-bug/del58.ba30ffe6.bam

CRAM trackshows alignments just fine
BAM track says "Zoom in to see coverage/alignments"

**Comment by jrobinso** [comment]
Hi, what is your question?

**Comment by jrobinso** [comment]
I am not sure what you are asking but will hazard a guess.  I assume you know what the message means, you are outside the visibility window.  For generic alignments the visibility window is 30kb, by default.  It is longer for RNA and long reads.   These settings are in the preferences under separate tabs.  There is no standard to tell IGV what type of experiment any particular file represents, so it guesses it from the reads themselves.     However 3 alignments are not considered enough to confidently guess, so I suspect that file is just tagged generic.   You can change the experiment type by right-clicking and selecting the appropriate menu item.

**Comment by diekhans** [comment]
Opps, I didn't make it clear; this is late-night bug report.

In the CRAM track, one sees the alignments at 681kb.

In the BAM track, one has to zoom into 21kb to see the alignment.

However, I now see that the Visible Range Threshold is 30kb and
if I up this it fixes it. So I guess the questions "why are
these different"?

Added a message to "Zoom in to see coverage/alignments" to
suggest change the threshold as an alternative would be helpful.

**Comment by diekhans** [comment]
Bingo; experiment type is it.

Suggest making the message guide one more to solutions so we don't
annoy you.

thanks as always!

**Comment by jrobinso** [comment]
That's a good suggestion to reference the threshold setting in the message.  It can't know that the experiment type is wrong, and this is a rare edge case.  Most files have more than 3 alignments.   One could question the minimum number IGV requires to guess a type, even 1 alignment in this case could tell us these are not short reads.   Another edge case is a merged alignment file with mixed types.   But 99% of the time it gets it right.    

I haven't loaded alignments into the UCSC browser, I wonder how it handles zoomed out views.

**Comment by diekhans** [comment]
A friend of mine this "solution directed error messages".
The experiment type is obscure, although this was an extreme
edge case.

UCSC has various methods for controlling what happens at
different zoom levels depending on the track type and
developer-defined configuration in the tracks.

However, the default for BAM/CRAM seems to be keep drawing when
zooming out until it times outs out ;-)
