### ISSUE TITLE
Header Panel Missing Chromosome-Scale Naviation Bar (IGV 2.17.2 + Java)

### ISSUE THREAD

**Issue by FrostFlow13** [igvteam/igv#1498]
Hello! I just installed a fresh version of IGV 2.17.2 with Java 17 included, and I've run into an odd issue where the chromosome-scale navigation bar in the top panel appears to be missing. I don't see the issue listed anywhere in any open or recently closed Issues, and I can't find any relevant options in the "Preferences" menus or the other drop down menus, but maybe I've just missed it. To be more clear, I have attached images of two different IGV versions launched via the Start Menu in Windows 10 (it also occurs when launching IVG via the `igv-launcher.bat` file):

IGV 2.16.2
![image](https://github.com/igvteam/igv/assets/105405804/ee1d46b1-78e9-428d-8b1f-5bfd16836fe0)

IGV 2.17.2
![image](https://github.com/igvteam/igv/assets/105405804/a3a6d4fa-74d9-43de-b54b-91437af3864b)

What's interesting to me is that it appears it recognizes the navigation bar SHOULD be there, given it can be hovered over, but left or right clicking on where it should be does nothing. I very much like the new chimeric reads feature with the mapping, but the lack of ability to quickly navigate between regions of the genome makes it a bit harder to use. Are there any suggestions or thoughts on how I may be able to get the bar to reappear?

**Comment by jrobinso** [comment]
This looks like a bug, probably affecting genomes with no 'cytobands' defined.   I will see if it can be fixed by modifying the genome definition file,  if not the only alternative is to wait for the next point release (2.17.3).

**Comment by FrostFlow13** [comment]
Understood - thank you for the quick response!

**Comment by jrobinso** [comment]
Can you confirm the genome assembly you are using?  Is it our hosted c.alibcans genome, or something custom?

**Comment by FrostFlow13** [comment]
I can confirm that it is not the IGV-hosted C. albicans assembly. It is a new C. albicans genome assembly I have been working on.

**Comment by jrobinso** [comment]
OK,  are you using a genome .json file, or just the raw fasta, to define the assembly?

**Comment by jrobinso** [comment]
Yes I was just looking for workarounds, with just a fasta there aren't any.   With a genome "json" file you could add a no-op cytoband file that would probably fix this.   Otherwise wait a few weeks for 2.7.3

**Comment by FrostFlow13** [comment]
I see, thank you for at least looking into it! I'll be looking forward to 12.7.3.

**Comment by jrobinso** [comment]
I'm not sure why this is still open, it was fixed for 2.17.3
