### ISSUE TITLE
Reverse 5' to 3' display

### ISSUE THREAD

**Issue by tanyasarkjain** [igvteam/igv#1499]
I am working with soft-clipped read that contains repeat expansions. 

Currently, IGV displays the data in the 5' to 3' direction. The repeat occurs on the reverse strand (3' to 5') and I'm interested in understanding the aligned methylation of the site upstream of the repeat expansion (3' end). 

Is there a way to switch the display of the IGV to a 3' to 5' orientation, so I see the reads aligned starting at the 3' upstream end? Currently the site upstream of the expansions of interest are not aligned and rather are staggard, due to different repeat lengths captured in the reads, therefore it is difficult to view the consensus in upstream methylation.

Hope this is clear. Thanks

**Comment by jrobinso** [comment]
I don't understand what you mean by "displays the data in the 5' to 3' direction".    Are you talking about alignments?  IGV displays them where they are.

**Comment by tanyasarkjain** [comment]
Is there a way for us to manually choose where the sequence aligns from? For soft clipped reads

**Comment by tanyasarkjain** [comment]
Thank you for the quick response. To clarify ill give an example of what I am trying to do:
if I have reads (soft-clipped) in the following form:

5' to 3'
AAAAAAGGGGGGGGGGGGGGGGGGGGGGTTTT
AAAAAAGGGGGGGTTTT
AAAAAAGGGGGTTTT
AAAAAAGGGGTTTT

Where the G's are a repeat expansion, and soft clipped bases, is there a way to display the alignments on IGV from the 3' to 5' end in this way, so I can easily understand the consensus in the reads and methylation starting at the 5' end?

3' to 5'
TTTTGGGGGGGGGGGGGGGGGGGGGGAAAAAA
TTTTGGGGGGGAAAAAA
TTTTGGGGGAAAAAA
TTTTGGGGAAAAAA

Or, as you were saying, does ther need to be upstream re-processing of the alignment files.
If so you can go ahead and close this issue. Thank you!

**Comment by jrobinso** [comment]
I don't think you understand what IGV or any other genome browser does.  It does not align the features it displays.   That information is in the alignment file (BAM in this case) you are loading.

**Comment by jrobinso** [comment]
Alignments do not have 3' or 5' ends,  they are simply sequence aligned to a genomic location.   The directional arrows indicate the DNA strand the sequence aligned to.   The soft clips do not of course align to the reference.   In any event what you are requesting is not possible in IGV, or probably any other genome browser.
