### ISSUE TITLE
Batch script return data

### ISSUE THREAD

**Issue by danielboloc** [igvteam/igv#150]
It would be very useful if the batch script could return (not just the snapshot), but for example the Total Count for one position in a _.sam_ file like so (or formatted differently):

Total count: 41
A      : 0
C      : 23  (56%,     11+,   12- )
G      : 18  (44%,     9+,   9- )
T      : 0
N      : 0

To my knowlegde you can get this count opening the _.sam_ file and right-click on the position at the top and selecting "_copy to clipboard_", which is useful, but if you have 100 files it could be a very boring task. 

Thanks in advance!

**Comment by jrobinso** [comment]
You can do something like this with igvtools,  see the count command  (command line version).   Not going to try to turn igv into an analysis tool via the batch command.

**Comment by danielboloc** [comment]
That sounds good, i'll try the igvtools. Thanks!
