### ISSUE TITLE
Desktop app downloads page links not working: 503 Service Unavailable

### ISSUE THREAD

**Issue by jcasado** [igvteam/igv#1503]
Steps to replicate the issue:
1. Go to Downlaods page: https://igv.org/doc/desktop/#DownloadPage/
2. Click on ANY of the download buttons, for instance, here I clicked on the Windows installer, which goes to this address: https://data.broadinstitute.org/igv/projects/downloads/2.17/IGV_Win_2.17.3-WithJava-installer.exe

Regardless of the operating system, the download buttons yield a `503 Service Unavailable` error page.

**Comment by jrobinso** [comment]
It seems to be working now, could you try again?

**Comment by jcasado** [comment]
Yes, now it works, thank you for a fast response!

**Comment by WandererMath** [comment]
2024-12-4. I got 503 error when trying to download IGV Desktop

**Comment by jrobinso** [comment]
Its working fine for me.    Which package are you downloading, and what is the URL link?
