### ISSUE TITLE
Gencode genome no data 

### ISSUE THREAD

**Issue by davidvilanova** [igvteam/igv#1507]
Hi,
I´m trying to load the genome file from gencode [GRCh38.p14.genome.fa.gz](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_45/GRCh38.p14.genome.fa.gz)

This is the log file. It says no data found
![image](https://github.com/igvteam/igv/assets/11404840/755ebca8-441e-4bc4-bacd-b2ae908f24ce)

And this is what i see in IGV

![image](https://github.com/igvteam/igv/assets/11404840/04f90ed9-5608-4ddb-b445-47d11c6e4df6)

What´s wrong ?

**Comment by jrobinso** [comment]
I don't understand what you are trying to do, the fasta file defines the reference but you've already done that.   What are you expecting to see?
