### ISSUE TITLE
group by haplotype?

### ISSUE THREAD

**Issue by kevfengler227** [igvteam/igv#1509]
I recall a very useful feature in previous versions for grouping by haplotype based on the number of specified groups. Is that feature still available I am not seeing it "Group By" options anymore?

Thanks,
KF

**Comment by ASLeonard** [comment]
There is a groupby "phase" option or by tag (typically HP or PS) option, which is what I used for haplotype-binned alignments

**Comment by kevfengler227** [comment]
So I am talking about a "Group By" function that would actually compute the clustering for un-binned alignments. Given un-binned alignments you could specify how many haplotype groups you wanted to create and it would do the clustering. Sort of like the group by base, or insert, but for all variations. It used to be there.

**Comment by jrobinso** [comment]
@kevfengler227 Sorry for the delay.   I was not aware anyone used that, it was experimental and never worked to my satisfaction.   I will look into restoring it, there was some refactoring done for base modifications and I think it was probably dropped then.

**Comment by kevfengler227** [comment]
Thanks Jim. I am glad to hear it. Otherwise I was worried I was having a Mandela Effect moment. I thought it worked pretty well. It is very useful for alignment based applications for polyploids or pangenomes, so I would be happy if you could bring it back.

**Comment by jrobinso** [comment]
I've restored this menu item, but renamed it "Cluster alignments" to better describe what it does.    I also tagged it *EXPERIMENTAL*.
