### ISSUE TITLE
IGV quits unexpectedly when saving tracks

### ISSUE THREAD

**Issue by Vernonjustice** [igvteam/igv#1515]
Translated Report (Full Report Below)
-------------------------------------

Process:               java [61807]
Path:                  /Applications/IGV_2.16.2.app/Contents/MacOS/../jdk-11/bin/java
Identifier:            java
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               1153143764

Date/Time:             2024-05-01 09:13:07.8852 -0400
OS Version:            macOS 14.4.1 (23E224)
Report Version:        12
Anonymous UUID:        DD5C1B92-D60A-369A-D0AB-F7997C5F8400

Sleep/Wake UUID:       DC1B2DED-7C96-4CC0-8DC3-9600FC213BC8

Time Awake Since Boot: 140000 seconds
Time Since Wake:       8784 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x7FF8A0572A78)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00000001047fe008
Exception Codes:       0x0000000000000002, 0x00000001047fe008

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   java [61807]

VM Region Info: 0x1047fe008 is in 0x1047fe000-0x1047ff000;  bytes after start: 8  bytes before end: 4087
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Rosetta Generic             1047fd000-1047fe000    [    4K] rw-/rwx SM=PRV  
--->  VM_ALLOCATE                 1047fe000-1047ff000    [    4K] ---/rwx SM=NUL  
      VM_ALLOCATE                 1047ff000-104800000    [    4K] r--/rwx SM=PRV  

Application Specific Information:
abort() called

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x7FF8A0572A78)

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff8a0572a78 ???
1   libsystem_kernel.dylib        	    0x7ff8102e314a __pthread_kill + 10
2   libsystem_pthread.dylib       	    0x7ff81031bebd pthread_kill + 262
3   libsystem_c.dylib             	    0x7ff810241a39 abort + 126
4   libc++abi.dylib               	    0x7ff8102d4932 abort_message + 241
5   libc++abi.dylib               	    0x7ff8102c713a demangling_terminate_handler() + 266
6   libobjc.A.dylib               	    0x7ff80ff642b7 _objc_terminate() + 96
7   libc++abi.dylib               	    0x7ff8102d3d8b std::__terminate(void (*)()) + 6
8   libc++abi.dylib               	    0x7ff8102d3d46 std::terminate() + 54
9   libdispatch.dylib             	    0x7ff81017add0 _dispatch_client_callout + 28
10  libdispatch.dylib             	    0x7ff81017d91c _dispatch_continuation_pop + 511
11  libdispatch.dylib             	    0x7ff81018df0d _dispatch_source_invoke + 2076
12  libdispatch.dylib             	    0x7ff8101870f0 _dispatch_main_queue_drain + 745
13  libdispatch.dylib             	    0x7ff810186df9 _dispatch_main_queue_callback_4CF + 31
14  CoreFoundation                	    0x7ff810438b6a __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
15  CoreFoundation                	    0x7ff8103f8210 __CFRunLoopRun + 2463
16  CoreFoundation                	    0x7ff8103f72a9 CFRunLoopRunSpecific + 557
17  HIToolbox                     	    0x7ff81b2e2829 RunCurrentEventLoopInMode + 292
18  HIToolbox                     	    0x7ff81b2e2636 ReceiveNextEventCommon + 665
19  HIToolbox                     	    0x7ff81b2e2381 _BlockUntilNextEventMatchingListInModeWithFilter + 66
20  AppKit                        	    0x7ff8139c0be5 _DPSNextEvent + 880
21  AppKit                        	    0x7ff8142d0fe9 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1273
22  libosxapp.dylib               	       0x1133916a0 -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 121
23  AppKit                        	    0x7ff8139b2005 -[NSApplication run] + 603
24  libosxapp.dylib               	       0x1133914e5 +[NSApplicationAWT runAWTLoopWithApp:] + 269
25  libawt_lwawt.dylib            	       0x1413d19e3 +[AWTStarter starter:headless:] + 511
26  libosxapp.dylib               	       0x113393025 +[ThreadUtilities invokeBlockCopy:] + 15
27  Foundation                    	    0x7ff81132a935 __NSThreadPerformPerform + 178
28  CoreFoundation                	    0x7ff8103f9226 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
29  CoreFoundation                	    0x7ff8103f91c9 __CFRunLoopDoSource0 + 157
30  CoreFoundation                	    0x7ff8103f8f98 __CFRunLoopDoSources0 + 215
31  CoreFoundation                	    0x7ff8103f7c08 __CFRunLoopRun + 919
32  CoreFoundation                	    0x7ff8103f72a9 CFRunLoopRunSpecific + 557
33  libjli.dylib                  	       0x10d15c64e CreateExecutionEnvironment + 398
34  libjli.dylib                  	       0x10d15885e JLI_Launch + 1322
35  java                          	       0x1047e7807 main + 375
36  dyld                          	       0x204b6c366 start + 1942
Model: MacBookPro18,3, BootROM 10151.101.3, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: DELL U2718Q, 5120 x 2880 (5K/UHD+ - Ultra High Definition Plus), Main, MirrorOn, Online
Display: Color LCD, 3024 x 1964 Retina, MirrorOn, Online
Display: DELL U2720Q, 5120 x 2880 (5K/UHD+ - Ultra High Definition Plus), MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Jan 20 2024 04:08:41 version 20.103.12.0.8.7.171 FWID 01-e09d2675
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: USB 10/100/1000 LAN, Ethernet, en4
PCI Card: pci8086,15f0, USB eXtensible Host Controller, Thunderbolt@3,0,0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.1 Hub
USB Device: USB3.0 Hub
USB Device: USB3.0 Hub
USB Device: USB 10/100/1000 LAN
USB Device: USB Storage
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: USB Audio
USB Device: SCR3500 C Contact Reader
USB Device: USB Billboard Device
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Device: TBT3-UDZ, Plugable, 1, 66.2

**Comment by helgathorv** [comment]
I'm not able to reproduce this issue. There are a few reasons why I might not be seeing the issue:
- your Mac is running the Sonoma operating system and I don't currently have access to that system
- you are running an older version of IGV (2.16.2). 
- perhaps it has something to do with the track you are trying to save

Can you try saving your track in the latest IGV and see if it makes a difference.
If not, can you try saving a simple track that has little data to see if that makes a difference. 
If so, then it's related to your track -- can you give us a test case that will allow us to reproduce the error on our end.
Also, are there any errors in the IGV log file in <your user home>/igv directory?
If it crashes for you in all cases using the latest IGV, I will see if I can get a Sonoma Mac to try to reproduce.

**Comment by Vernonjustice** [comment]
Thanks for your response. Updating my IGV from version 2.16.2 to 2.17.4
seems to have helped.

**Comment by helgathorv** [comment]
Glad to hear it. Thanks for letting us know.
