### ISSUE TITLE
Bug in showing mismatched bases

### ISSUE THREAD

**Issue by gevro** [igvteam/igv#1516]
IGV v. 2.17.4 on Mac

See the mismatched base in one of the reads here:
<img width="620" alt="Screenshot 2024-05-04 at 3 58 44 PM" src="https://github.com/igvteam/igv/assets/47928628/3ad6243c-bdc1-40f1-b7b7-b4af8bf90e8c">

The mismatched base is not showing up even though 'show mismatched bases' is selected:
![Screenshot 2024-05-04 at 3 59 12 PM](https://github.com/igvteam/igv/assets/47928628/02899452-11c0-46b8-b9b7-4bca0be457ac)

**Comment by jrobinso** [comment]
I can't reproduce this, and its not really possible to guess what is going on from the screenshots.

**Comment by gevro** [comment]
Weird, I tried to reproduce it and can't. There was something in that specific read that was preventing it from showing mismatches. Unless there is some setting in preferences that can somehow cause mismatches not to show up even when 'show mismatched bases' is selected.

**Comment by jrobinso** [comment]
I can't think of any setting that would cause that, if its low base quality changing the shading formula in preferences might but I doubt it.  Are you sure you are looking at the same alignment?  Its impossible to say from a screenshot, alignment rows might be in a different order between the two.

**Comment by gevro** [comment]
100% sure I was looking at the same alignment. And I turned off shading by base quality - I thought of that - and no difference.

In that session of IGV, for some reason for that specific alignment, the mismatches were not showing up per the screenshot. The screenshot for sure shows that so I know I'm not hallucinating :-) And going to other loci in that session showed mismatches fine.

If it recurs, I will let you know.

**Comment by gevro** [comment]
Hi, The bug is happening again. Can I e-mail you offline to share a BAM file showing the issue

**Comment by jrobinso** [comment]
Yes, igv-team@broadinstitute.org.   Also exact steps to reproduce, including genome selection,   and include your "prefs.properties" file from the "igv" folder.

**Comment by gevro** [comment]
Sent

**Comment by jrobinso** [comment]
OK mystery solved, you are in "quick consensus mode", which by default is on for long read alignments.   This default definitely needs changed, and will be in the next release, but in the meantime you can go to "View > Preferences > Third Gen" and uncheck the "quick consensus mode" box.   This should have occurred to me earlier, honestly I had forgotten about this.    For more background on this mode see https://www.pacb.com/blog/igv-3-improves-support-pacbio-long-reads/#:~:text=IGV%20has%20added%20two%20features,(recommended%20setting%3A%2025%25)..

**Comment by gevro** [comment]
Phew that's a relief. I thought I was imagining this! Thanks

**Comment by jrobinso** [comment]
No, and you did ask if there were any preference settings.   Really I just forgot,  I'm relieved its not something more serious as well.

**Comment by gevro** [comment]
It is a bit confusing that 'show mismatched bases' can be overridden by the quick consensus mode. Perhaps that is something to consider for the future in how these interact. Maybe they should be mutually exclusive settings.

**Comment by jrobinso** [comment]
@gevro That would defeat its purpose,  the purpose is precisely to not show mismatches unless there is consensus.  If you read the link I posted above you'll understand the rationale,  but with modern PacBio data its no longer necessary.    Earlier generations of pacbio (an ont) data were not interpretable without this.   The defaults haven't kept pace with the technology in this case.

**Comment by gevro** [comment]
Got it, thanks.

**Comment by gevro** [comment]
Are there any other settings that affect this? Because on a different computer I have the opposite issue. Even though I set quick consensus mode on both in the 'third gen' and in the 'alignments' preferences, I still see the mismatch.

**Comment by jrobinso** [comment]
The mode is explained pretty well in the article I posted.   Note "**_The logic is the same as used by the coverage track"_**.   So the threshold for quick consensus is the threshold used for the coverage track,  which in turned is governed by "Coverage allele-fraction threshold" and "Quality weight allele fraction".   

`
