### ISSUE TITLE
Support specifying file format for URLS  ("Tracks from presigned URL *without* the file extension")

### ISSUE THREAD

**Issue by SergejN** [igvteam/igv#1526]
Dear IGV team,

for reasons I have no influence on, the BAM/BAI files are stored in the s3 bucket without extensions. I can generate presigned URLs to load the files in IGV, but it raises an error because it cannot guess the file type.

"Cannot determine file type of: https://***.amazonaws.com/data/without_extension_bam?X-Amz......."

Is there a way to explicitly force IGV to interpret the file as BAM/BAI?

It's not a bug as I wouldn't know how to handle files without extension, either, unless told explicitly, but rather an idea.

thank you!

**Comment by jrobinso** [comment]
Currently there is not a way without a file extension.    Any suggestions?

**Comment by SergejN** [comment]
Not a super elegant one - prefix the URL with the filetype, e.g. `bam:https://my_s3_bucket/my_file_with_no_extension?additional-aws-param=.....`
An alternative would be to add a dropdown menu to the dialog and allow the user to specify the data type

**Comment by jrobinso** [comment]
Another idea is a url paramter,   e.g. ```format=bam```.   This would not actually get passed to s3 just parsed by IGV

**Comment by SergejN** [comment]
That's true, we also thought about that because we were inspired by an old google groups thread
https://groups.google.com/g/igv-help/c/2xsxhvHDDa0?pli=1 . We are currently checking whether it is possible to have an additional parameter in the AWS presigned URL.

**Comment by jrobinso** [comment]
Again, it is not neccessary that AWS see the additional parameter, IGV could just parse and remove it before the requests.

The dropdown menu option is not a bad one actually.

**Comment by jrobinso** [comment]
There are a few formats, BAM being one, that can be determined from the file itself as they define required magic number bits at the front of the file.    I'm going to look into implementing auto detection for these formats if it can be otherwise determined.

**Comment by jrobinso** [comment]
I think this should be fixed, and you shouldn't need to do anything.  As outlined above, the file type will be determined from required header bits for those formats that require them, which includes BAM, if no file extension is present.    This change is available in the snapshot build, if you are able to test this that would be helpful.   The snapshot build can be downloaded from https://igv.org/doc/desktop/#DownloadSnapshot/.
