### ISSUE TITLE
doesn't show RefGene from my custom genomefile.

### ISSUE THREAD

**Issue by saky7009** [igvteam/igv#1528]
I am almost new here. Please give me some suggestion. I uploaded my genome file but it did not show refGene section. 
![Custom file](https://github.com/igvteam/igv/assets/133572669/c37b9e3d-e575-4058-9b1d-01d79cb95f21)
This is my file and I also upload IGV file for example.
![IGV file](https://github.com/igvteam/igv/assets/133572669/f6030fad-f1b4-4978-b6f7-0c1050f6b75d)

**Comment by helgathorv** [comment]
From the screenshot it looks like you loaded a fasta file to use as the reference genome, which means you've loaded  the genome sequence, but no gene annotations. If you have a gene annotation file for your genome, you can load it separately as you would other tracks ie via the File menu. Or if you want the gene annotation track to be loaded automatically with your genome, you can create an IGV reference genome file in JSON format as described here: https://igv.org/doc/desktop/#FileFormats/Genomes/
