### ISSUE TITLE
Problem to data using if the URL is redirected

### ISSUE THREAD

**Issue by dercyc** [igvteam/igv#1529]
Let say I have a bam file and bai file, e.g., http://example.com/file.bam and http://example.com/file.bai. If I load them using URL, IGV displays the content correctly. However if I load it via PHP redirect function, e.g.,

http://mylab.com/bam.php

which redirect the URL to:
http://example.com/file.bai

Then the IGV cannot load the content. (Tested the URL in browsers and they work fine)

I even tried the pretty URL via .htaccess, e.g.,
http://mylab.com/php/file.bam

In my PHP script, it is nothing more than 301 redirect, e.g.,

header("Location: http://example.com/file.bai", true, 301);

What is the best way to load data via redirect URL?

**Comment by jrobinso** [comment]
I'm not a PHP expert but IGV follows 301 redirects.     However the extension "php" will not work, IGV is not going to know that is a bam file.   The URL to the bam file must end with ".bam",  the url the index file doesn't really matter.

You did not tell us what the error is, or what version of IGV you are using.   Also, could you attach the contents of the log file, located in the igv folder under your home directly with a name like "igv0.log".

**Comment by dercyc** [comment]
Thanks for the reply. I am using IGV 2.17.4 / Windows (the latest version as of today). My version includes Java Engine.

Here are the URLs I tested:
BAM: https://demo.bxgenomics.com/IGV/download/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam
BAI: https://demo.bxgenomics.com/IGV/download/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam.bai


Notice that these URLs return 301 headers and redirect to ucsc.edu.

Here is the error message from GUI:
Error loading https://demo.bxgenomics.com/IGV/download/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam: An error occurred while accessing: https://demo.bxgenomics.com/IGV/download/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam Error loading BAM file: htsjdk.samtools.FileTruncatedException: Premature end of file: https://demo.bxgenomics.com/IGV/download/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam


Here is the error log:
https://demo.bxgenomics.com/IGV/igv.log


Thanks again!

**Comment by dercyc** [comment]
I've found the issue. It was related to the headers. My initial version involved many cookies related headers such as:

Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Encoding: gzip
Vary: Accept-Encoding

After I remove them, the IGV works fine now. Thanks again.

**Comment by jrobinso** [comment]
This is the problematic header, I suspect.    This will cause the BAM file to be gunzipped, which definitely will break things.

```
Content-Encoding: gzip
```
