### ISSUE TITLE
IGV track requests for hg38 genome

### ISSUE THREAD

**Issue by vivekbhr** [igvteam/igv#153]
Hi

It will be great if the following tracks could be included for hg38 genome in IGV.

1) Gene track (It's already there in my IGV since I loaded it a couple of months ago, but I don't see hg38 in the "load genome from server" option anymore).
2) Repeatmasker track.
3) PhastCons track
4) Common SNPs

Thanks a lot.

**Comment by jrobinso** [comment]
The HG38 genome should be in your genomes pulldown.

The phastcon track can be loaded directory using "File > Load from URL...".  Just paste in the following URL  
http://hgdownload.cse.ucsc.edu/goldenPath/hg38/phastCons20way/hg38.phastCons20way.bw

**Comment by jrobinso** [comment]
These are added under "load from server", with the exception of the gene track which is loaded automatically.   You must use the latest igv,  2.3.53,  to load the snp track.

**Comment by vivekbhr** [comment]
Yes it's available now! Thanks a lot..
