### ISSUE TITLE
Installing with admin privileges

### ISSUE THREAD

**Issue by shashwatsahay** [igvteam/igv#1532]
Is there a way to install IGV without admin privileges in windows

**Comment by jrobinso** [comment]
I'm not sure this is an IGV question, are you able to install other applications?

**Comment by shashwatsahay** [comment]
No i can't, but generally for some of the software it is possible to run
them  without installing by just having them as a binary instead of
installer

**Comment by jrobinso** [comment]
You can try the command line version on our downloads page https://igv.org/doc/desktop/#DownloadPage/.  You'll have to have or install Java 17.
