### ISSUE TITLE
batch model: how to set copy number range 

### ISSUE THREAD

**Issue by lamz138138** [igvteam/igv#1534]
Hi Dear IGV team,

I am trying to generate screenshot based on seg file in batch model. I would like to set negative range from -0.05 to -0.5, positive range from 0.05 to 0.5, value between -0.05 to 0.05 to be white. I had tried the following two ways:

```
echo "CN_FREQ.AMP_THRESHOLD 0.05" >>igv.pref
echo "CN_FREQ.DEL_THRESHOLD -0.05" >>igv.pref
xvfb-run /path/to/igv.sh --preference igv.pref
```
or
```
echo "preference CN_FREQ.AMP_THRESHOLD 0.05" >>igv_script.bat
echo "preference CN_FREQ.DEL_THRESHOLD -0.05" >>igv_script.bat
xvfb-run /path/to/igv.sh -b igv_script.bat
```
However, both of them are not work. Can you tell me how to set the value in batch model?
Thanks for any help in advance!

**Comment by jrobinso** [comment]
Batch commands are described here
https://igv.org/doc/desktop/#UserGuide/tools/batch/

See "preference"

**Comment by lamz138138** [comment]
Hi @jrobinso ! Thanks for your quick response. I generated above two ways after reading the describe below, but they are not work, so I open this issue. Is it because I did not write it correct? Besides, I do not know how to write colorScale.

> ##Segmented Copy Number Track Defaults
> CN_FREQ.AMP_THRESHOLD	CN freq amplification threshold	float	0.1
> CN_FREQ.DEL_THRESHOLD	CN freq deletion threshold	float	-0.1
> NO_DATA.COLOR	 No data	color	216,216,216
> NO_CALL.COLOR	 No call	color	150,150,150
> COLOR_LEGENDS	Color Legends	colorScale

**Comment by jrobinso** [comment]
I'm not sure what you are showing me.   Could you post the actual batch script you are using?

**Comment by lamz138138** [comment]
Here are my files and command:
```
cat igv.pref
IGV.Bounds=0, 0, 2560, 1440
```
```
cat igv_script.bat
new
geome hg38
expand Refseq%20Genes
preference CN_FREQ.AMP_THRESHOLD 0.05
preference CN_FREQ.DEL_THRESHOLD -0.05
load input_cnv_ratio.seg
snapshotDirectory /path/to/igv_screenshot
goto chr3 35483850 35794496
region chr3 35639173 35794496
snapshot temp.png
exit
```
`xvfb-run -d -s "-screen 0 2560X1440X24" /path/to/igv/install/2.16.0/igv.sh -b igv_script.bat --preferences igv.pref`

I am not sure whether "CN_FREQ.AMP_THRESHOLD 0.05" and "CN_FREQ.DEL_THRESHOLD -0.05" will set value [-0.05, 0.5] to white. I also want to know how can I set the maximum value to 0.5 and the minimum value to -0.5?
Current, for example, I have a segment value is -0.09, it will be white after running above command, but I would like to make it light blue.

**Comment by jrobinso** [comment]
The easiest way to discover preferences syntax is to configure what you want in the UI,  then look at the "prefs.properties" file in your igv folder.    You can edit heatmap legends visually from the "View > Color Legends" menu.   Here's the result of a rather random edit

```
COLOR_SCALE_COPY_NUMBER=ContinuousColorScale;-0.5;-2.5;0.5;2.5;102,255,51;255,255,255;0,204,204
```

The thresholds you are setting only impact the frequency track that appears above the heatmap, they have no impact on the color scale

**Comment by lamz138138** [comment]
This is really helpful. I solve the problem. Thank you very much!
