### ISSUE TITLE
Shift in the visual representation of a junction 

### ISSUE THREAD

**Issue by Mohamed-HAMICI** [igvteam/igv#1535]
Hello,

Sometimes when using IGV to visualize RNAseq data, there is what seems to be a glitch in the graphical representation of the junctions. 
The start and end of the graphical representation of the junction do not always correspond to the actual start and end of the junction.
The gap between the position we see and where it is supposed to be is usually small (2-3 bp) but can sometimes be important leading to a big shift of the graphical representation of the junction. See example below:
<img width="1174" alt="Screenshot" src="https://github.com/user-attachments/assets/34691175-50de-44dd-9b2e-4cded3a9123c">
For information:
I use IGV v2.17.4 (downloaded from igv.org - IGV MacOS App Java included) on an Apple silicon Macbook and the data is a bam from human RNAseq sequencing (illumina I think) aligned with star on HG19.

**Comment by jrobinso** [comment]
I would need to see all the alignments to comment,  are there any with a junction at that point?    How deep is the coverage here?

**Comment by Mohamed-HAMICI** [comment]
I don't know if this is exactly what you asked for: (The junction of the previous post is the one in bright red).
<img width="2661" alt="Screenshot" src="https://github.com/user-attachments/assets/4d3c2d0e-0f00-4273-8157-8c17dfac3137">

If it's too small, the numbers on the upper left corner are: [0-113]
The junction track is set to "Expanded"

**Comment by jrobinso** [comment]
What I am looking for are alignments that might support the junction at the "shifted" location.    This is too zoomed out to tell, could you zoom into the junction?  Also, we are only seeing a bit less than 1/2 of the alignments, as determined from the scrollbar.

If you are convinced there are no alignments supported the shifted location I will probably need the data to determine what's going on.  If you are able to share it, you can export the data in view directly from IGV, right click and look for the "export alignments" option.    This will create a file "visibleData.sam".   You can zip that and attach it here, or send it to igv-team@broadinstitute.org.

**Comment by jrobinso** [comment]
Thanks for the data, that was helpful.   What is happening is the bezier curves are extending past the junction point then looping back.  You can see this is you increase the track height enough to see the details at the junction.    Fixing this by trying to adjust the curves would have potential unintended side effects for a track that has been stable for many years.   So I have simply clipped the curves at the junction boundaries.    Pictures before and after clipping are below.

<img width="307" alt="Screenshot 2024-08-12 at 12 50 35 PM" src="https://github.com/user-attachments/assets/8f77a866-7f9f-472b-a64f-92454b9f5131">
<img width="218" alt="Screenshot 2024-08-12 at 12 51 52 PM" src="https://github.com/user-attachments/assets/f9d39220-ac0c-41f6-999b-8316e86669be">

**Comment by Mohamed-HAMICI** [comment]
Thank you for the bug fix and explanation. I will make sure to try the updated version.
Thanks again

**Comment by jrobinso** [comment]
@Mohamed-HAMICI This is not yet released, if you want to try it early you can download the development snapshot at https://igv.org/doc/desktop/#DownloadSnapshot/

**Comment by Mohamed-HAMICI** [comment]
@jrobinso Thank you. It works well and the junctions are way cleaner this way
