### ISSUE TITLE
How do I load from server the Tutorial Dataset?

### ISSUE THREAD

**Issue by fantauzzi** [igvteam/igv#1537]
The [IGV tutorial videos](https://youtu.be/YpNg0hNUuo8?si=TNvIpdAbgKN4yF7e&t=35) use a `Tutorial` dataset. When I try to open it, I only see an `Annotations` dataset. How do I add other datasets, such as the `Tutorial` dataset?

Running version 2.17.4 under Ubuntu 22.04.

This is what I see when I do `File > Load From Server...`
![image](https://github.com/user-attachments/assets/d811fd51-eab1-4af3-83aa-4d47750e006e)

**Comment by helgathorv** [comment]
The set of available datasets depends on the currently selected reference genome. Both hg18 and hg19 have "Tutorial" sections in Load from Server.
