### ISSUE TITLE
Suggestion for UX improvement

### ISSUE THREAD

**Issue by tadast** [igvteam/igv#1539]
When there are multiple queries and none are selected, the UI tells the user to "Zoom in to see features", but there is no zoom controls. Instead the user needs to select a query first. Perhaps the UI should read "Select the query to see the features" in this scenario?

<img width="723" alt="image" src="https://github.com/user-attachments/assets/c9ecbd31-b901-4704-a00a-3915444ae959">

**Comment by jrobinso** [comment]
That's true, there are no zoom controls when in whole-genome view.   I think calling sequences (usually chromosomes) "query" however would cause more confusion.    I for one would not know what that means.   But good suggestion, we will change the wording here.

**Comment by tadast** [comment]
This is awesome, thanks @jrobinso 🙌

**Comment by tadast** [comment]
@jrobinso how do you keep the embeddable js version up to date with changes here? Does it need a separate manual update?

**Comment by jrobinso** [comment]
Its a completely different project and code base.
