### ISSUE TITLE
proxy : resources  on intra AND internet

### ISSUE THREAD

**Issue by lindenb** [igvteam/igv#154]
(related: https://github.com/igvteam/igv/issues/86 )

Feature Request: Hi IGV team, could your please consider to add a text-field in the "Preferences Panel/Proxy" to set a "No-proxy host":

I've played with a data server hosted in our server: http://123.45.678.90/projects/GRCh37_igv_servers.txt

```
$ cat hg19_igv_servers.txt 
https://data.broadinstitute.org/igvdata/annotations/hg19/hg19_annotations.xml
http://123.45.678.90/projects/GRCh37_igv_server.xml
```

currently the proxy must be disabled to access http://123.45.678.90 but then Igv cannot access https://data.broadinstitute.org/

**Comment by jrobinso** [comment]
Hi Pierre,

Yes, so perhaps one would enter a comma-delimited list of hosts for 
which the proxy is bypassed?

How's it going.   Have you checked out igv.org,  particularly the middle 
link to igv.js?

(related: #86 <https://github.com/igvteam/igv/issues/86> )

**Comment by lindenb** [comment]
Hi Jim,

Yes, I saw igv.js in May https://twitter.com/yokofakun/status/595486641545969664  , it  looks great !

**Comment by jrobinso** [comment]
Oh cool, thanks!  I've got to start tweeting.

Follow igv.org for further progress and examples,   I'll put some 
redirects in from the old broadinstitute.org urls.

Best

Jim

**Comment by jrobinso** [comment]
I've added support for entering a comma-delimited list of hosts for which the proxy is bypassed.  Enter the list (the "whitelist") on the Proxy preferences page.  This is deployed in the "snapshot" build, and will be included with the next release.

**Comment by lindenb** [comment]
:+1:
