### ISSUE TITLE
Make IGV session file

### ISSUE THREAD

**Issue by diego-rt** [igvteam/igv#1549]
Hello,

I was wondering whether there is a way to generate an IGV session file from the command line?

I have some custom genomes (i.e. path to some fasta file + index) and some bam and bed files that I would like to load in specific combinations and I would like to automate the creation of the session file.

Thank you as always!

**Comment by jrobinso** [comment]
There is no tool for this but it is XML so it shouldn't be difficult if you do not want to customize the tracks.  See the user documentation for a description of the XML.

**Comment by diego-rt** [comment]
Oh I see! Yes, looks straightforward. 

Thanks for the quick feedback!
