### ISSUE TITLE
Bam read coverage track and relative paths in IGV session.xml

### ISSUE THREAD

**Issue by DavidAustinNix** [igvteam/igv#155]
Hello Folks,

I'd dearly like to create a session.xml file that is included in a directory of bam, bed, and vcf files.  A client would then download the whole folder and load the session (or double click a custom jnlp). Currently this works beautifully.  One issue I encountered though is when trying to specify in the session file that a Read Coverage track be opened for each bam file.  It appears that the path to the bam file must be absolute, it can't be relative.  If it is relative then the Read Coverage track isn't created.  Worse it can't be created unless the client deletes the bam track and reloads from File.  

A good fix here would be to allow the ReadCoverage track to be created when pointed at a relative pathed bam in a session.xml file.

Not sure if there are other work arounds?

Thanks for such an awesome app!

-cheers, David

**Comment by jrobinso** [comment]
Thanks for the report, clearly a bug.  Will look into it.
