### ISSUE TITLE
"Read Order" is wrong in "Supplementary Reads Diagram"

### ISSUE THREAD

**Issue by simondrue** [igvteam/igv#1550]
Hi,

First, thank you very much for the very useful "Supplementary Reads Diagram" feature. If understand it correctly, the order in the vizualization in the "Read Order" pane is reversed. Here are two examples for a forward and reverse read:

Reverse read 
![image](https://github.com/user-attachments/assets/e33e0234-6087-4a87-8af4-6662ae7c2177)

Forward read
![image](https://github.com/user-attachments/assets/07a0de9d-e54d-49e6-8ca0-5c64c5d7916f)

Thanks for a great tool,

Kind regards,
Simon

**Comment by jrobinso** [comment]
Hi Simon.  Its impossible to say from screenshots, what makes you think it is wrong?  Have you examined the reads sequence and SA tag?

**Comment by simondrue** [comment]
Hi @jrobinso,

After looking at some more examples i must admit i misunderstood the figure. In my mind the in the read order pane the read should be shown always from left to right, i.e. all "parts" of the read pointing to the right. I understand now that its the order of the parts in the read, but shown in the direction of the alignment.

Tanks again for a great feature - looking forward to getting to know it better.

I'm closing the issue.

/Simon
