### ISSUE TITLE
Could not connect to the genome server from Chinese mainland

### ISSUE THREAD

**Issue by cyk64** [igvteam/igv#1557]
Hi,
I am a user from Chinese mainland. From Sep 4, 2024 when I open my IGV (2.13.2), there is a warning saying: 
![image](https://github.com/user-attachments/assets/48475d7b-0459-43ad-9b6d-1a6601b37691)

Warning:could not connect to the genome server(https://s3.amazonaws.com/igv.org.genomes/genomes.tsv).Only locally defined genomes will be available.

However after a period of loading, I can have my Refseq Genes of hg38 from https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ncbiRefSeq.txt.gz

But if I want to switch my genomes to other species (mm39 or rn6), there is still a warning:
![image](https://github.com/user-attachments/assets/3661b731-808a-4036-81ee-dac36c9e0d6a)

Since my local IGV served properly until yesterday, I wonder if it is just a temporary issue of Internet, or access from Chinese mainland is totally forbiddened (as aws might not be fully supported here in China). Did you change your genome server recently?

Thank you!

**Comment by northwestwitch** [comment]
We are experiencing the same here in Sweden (using igv.js) -->

![image](https://github.com/user-attachments/assets/1f9400bf-a7b1-415d-82d5-9a901ba2fa91)

**Comment by jrobinso** [comment]
There are some issues with one of our S3 buckets.  However, if you are using a recent version of IGV you can fix this problem by refreshing your hg38 genome.  To do this select it from "Genomes > Select hosted genome".

**Comment by jrobinso** [comment]
Bucket problems are fixed.
