### ISSUE TITLE
feature request: primer design

### ISSUE THREAD

**Issue by hmontenegro** [igvteam/igv#156]
Simple as that: it would be really handy to have integrated primer design.

**Comment by jrobinso** [comment]
I know zilch about primer design,  could this be expanded to detailed 
feature requests?

**Comment by hmontenegro** [comment]
I will think about it and elaborate, but my initial idea was just adding primer3 as a plugin, then selecting a region or feature would enable designing primers around it. 
I found a help thread (Plug-ins for IGV) discussing a BLAT plugin, though the original question also suggested primer3 as a possible plugin.
