### ISSUE TITLE
GRCh37/hg19 alias missing chr23

### ISSUE THREAD

**Issue by MayTheForestBeWithYou** [igvteam/igv#1560]
Hello,

I'd like to get some more information about the recent changes I have noticed in the supplied hosted genome GRCh37/hg19 especially in the alias. Since 29-08-2024 I noticed that GRCh37/hg19 alias changed especially for chr23, which used to be in the alias to be able to map variants to chrX. Due to chr23 not being present in the alias, variants were not mapped to chrX any more. 

To resolve the issue I linked back to the old alias in the h19.json hosted at https://s3.amazonaws.com/igv.org.genomes/hg19/hg19_alias.tab which does contain the chr23 alias. I changed the aliasURL in the hg19.json which is stored in the ~/igv/genomes folder. Unfortunately, on 04-09-2024 the genome could not be loaded, due to an access denied on https://s3.amazonaws.com/igv.org.genomes/hg19/hg19_alias.tab. 

However, today (05-09-2024) I noticed the hosted genome GRCh37/hg19 uses a different alias file which does again contain the chr23 alias. Due to the recent changes which I could not track down the reason for I would like to know whether we are now in a stable state. Or I would need to make changes to accommodate the removal of the chr23 alias. Furthermore, I would like to know whether the changes in the alias file and the access denied on amazonaws are related, or unrelated issues.

I appreciate any answer to give me some peace of mind.

-Timon

**Comment by jrobinso** [comment]
The blockage of the s3 bucket igv.org.genomes was resolved, that is unrelated.  RE chr alias, we switched to using the UCSC alias file, but dues to a missing MT / chrM alias we reverted back to ours, and took the opportunity to move it to a server we control.

**Comment by maximilianh** [comment]
Oh... very interesting "a missing MT / chrM alias" ? Which one?

**Comment by jrobinso** [comment]
@maximilianh In this particular case this file (hg19).   Also, I guess some systems use chr23 and chr24 for X and Y.   I don't know where that convention comes from but we included it in our alias file.

https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.chromAlias.txt

**Comment by maximilianh** [comment]
Just in case: You cannot alias "MT" to "chrM" in hg19, it's a different
sequence, as you probably know better than me, since back in 2009 there was
no chrM in the NCBI release of Grch37, as far as I know, and UCSC picked a
sequence very quickly to fix this, but it was not the one that was later
added to Grch37.

**Comment by jrobinso** [comment]
Thanks for the clarifications.   Yes I totally agree with not touching old files.     

I did not know the MT <-> chrM history for hg19.     This is interesting, I will remove that one.

**Comment by jrobinso** [comment]
@maximilianh Do you know where this convention of using chr23 for X came from?    It obviously happens, @MayTheForestBeWithYou opened this ticket over it.    It seems like a bad idea as some species have a chr23.    I just don't know where it came from.

**Comment by maximilianh** [comment]
I have no idea, sorry, I've never seen this before, and we've certainly
seen a lot of BED files. I can ask around in the group.

**Comment by jrobinso** [comment]
I'm going to reopen this until we resolve this "chr23 - X" mystery.

**Comment by jrobinso** [comment]
The benefit is the chromosome alias file is from an official vetted source, UCSC, rather than something we create and host (and don't maintain).   However I agree with the backward compatibility comment wrt chr23 for hg19.

The chrM <-> MT thing is different.  For hg19 / b37 those are different sequences.  So they are not aliases for the same sequence as I erroneously assumed.   This gets back to my comment above.
