### ISSUE TITLE
How to view 'linked read' in IGV?

### ISSUE THREAD

**Issue by kuangzhuoran** [igvteam/igv#1565]
I found this in Google
![2](https://github.com/user-attachments/assets/701e7b76-50f1-4772-a0c5-7d4350fb2593)

But I can't find “View linked reads” when I actually use it. like this:
![1](https://github.com/user-attachments/assets/28a04d1d-b66a-4f08-a1df-2386a528f89f)

**Comment by kuangzhuoran** [comment]
Thanks for your reply~
I've identified some potential inversions (1~2 Mb) with short reads, and I'd like to use linked reads to further validate the breakpoints and presence of inversions

**Comment by jrobinso** [comment]
But does your BAM file contained link reads, and if so how are they linked?

**Comment by kuangzhuoran** [comment]
Yes, they contain linked reads (there are BX/MI tags in my BAM file).
I used IGV version 2.5.3 and finded this option.
![微信截图_20240911180225](https://github.com/user-attachments/assets/630afbe1-f706-4dc7-b871-d7a9bdfdceb4)

**Comment by jrobinso** [comment]
Then you would link by those tags ("Link by tag...") as I described earlier.
