### ISSUE TITLE
BAM files not loading in local IGV on Linux

### ISSUE THREAD

**Issue by aboyd003** [igvteam/igv#1567]
I have been successfully using IGV locally on my linux system. Today, I went to use IGV 2.14 and it failed to load bam files, even ridiculously small bam files. I performed a fresh download of IGV 2.18. However, the issue persisted. I can see on the command lines that the RNAMES for the bam files match the loaded genome. The issue only occurs with loading bam files. I was able to load my gtf and gff files without issue. I have included examples of the bam file for just chr1. Due to file upload size constraints, I have included only approximately the first third of chromosome 1 from the genome file. 

I did note that when loading the genome file which is only chr1 IGV lists multiple chromosomes?

My system information:
Operating System: Linux Mint 20.2
Kernel: Linux 5.4.0-195-generic
Architecture: x86-64
[chr1_testbams.zip](https://github.com/user-attachments/files/16969878/chr1_testbams.zip)
[chr1_firstthird.fa.zip](https://github.com/user-attachments/files/16969902/chr1_firstthird.fa.zip)

**Comment by jrobinso** [comment]
Hi, I don't have any issues loading your files.    Also, there are 3 chromosomes listed your your fasta (chr1, chr2, and chr3).

There might be information in your log file, located in the "igv" folder in your home directory.   The filename is usually "igv0.log".

**Comment by aboyd003** [comment]
Can I ask what is your operating system?

- Sorry I uploaded the wrong genome file. Below is the correct one. That explains the chromosome number issue. 
- However the bam files are not loading on my running of IGV. I have included screenshots. The first has just the bam file loaded. The second screenshot has the gff loaded as well to show that the gff file loads correctly. I do not think there is an issue with the files as they have loaded correctly before and load ok on my macbook. The issue occurs with every bam file I attempt to load across multiple projects. The uploaded files in my posts on this forum are small test files provided for testing the issue. The original files even when compressed are too large for the 25MB upload limit. I suspect there is an issue with linux running IGV. The issue is newer as IGV has run without issue for me on linux in the past. This is why I provided my system info in the first post. 

[chr1only.fa.zip](https://github.com/user-attachments/files/16970957/chr1only.fa.zip)
![image](https://github.com/user-attachments/assets/d1a9a0b3-9e13-4f52-bd06-e4520f89c4d0)
![image](https://github.com/user-attachments/assets/3237c3ab-dc50-41e9-9d68-6d251fe9ca6e)

**Comment by jrobinso** [comment]
MacOS, but that's not important.    I can load the file without issues.  Once again, there might be information in igv0.log.   Could you look and post that here?
 
Also, I assume you are loading from the "File > Load from file..." menu, correct? 

<img width="519" alt="Screenshot 2024-09-11 at 3 43 09 PM" src="https://github.com/user-attachments/assets/a45e6a8d-98b4-4288-a48b-5c2710a20985">

**Comment by aboyd003** [comment]
Yes I am using "File > Load from file..." menu to load bams.
Where should i look for igv0.log? Base on my command line search and visual inspection of the directory, there are no log file.

![image](https://github.com/user-attachments/assets/243a91e2-361b-429c-969a-5de1422c6df6)

![image](https://github.com/user-attachments/assets/60701ac2-6651-4a53-9823-c765a8cee228)

**Comment by jrobinso** [comment]
From above

` located in the "igv" folder in your home directory. The filename is usually "igv0.log".`

On a linux machine the home directory is usually, but not always,   /users/<user name>.     The location will be listed in the preferences, select "View > Preferences > Advanced" and scroll to the bottom, the location of the igv directory will be shown there.

**Comment by aboyd003** [comment]
I have attached the log file. The igv.log file contain instances where igv worked as expected. The igv0.log contain the most recent usage where igv did not load bam files.
[igv0.log](https://github.com/user-attachments/files/16971301/igv0.log)
[igv.log](https://github.com/user-attachments/files/16971304/igv.log)

**Comment by jrobinso** [comment]
Unfortunately there are no errors in the log.  I'm almost out of ideas, but we could see if there is something in your preferences that are implicated.   This is easy to do,  first quit IGV if its running,  then rename  the file "user.preferences" to "user.preferences.bak", restart IGV, and try again.   This effectively resets IGV to original settings.

**Comment by aboyd003** [comment]
I don't see a user.preferences file. I do have a prefs.properties file that is copied below

IGV.track.show.attribute.views=true
SAM.SHADE_BASE_QUALITY=false
SAM.SHOW_MISMATCHES=false
IGV.single.track.pane=false
IGV.Bounds=464,23,1150,800
DEFAULT_FONT_SIZE=10
VARIANT_COLOR_BY_ALLELE_FREQ=false
COVER_OVERLAY_KEY=false
SAM.SHOW_COV_TRACK=false
LAST_TRACK_DIRECTORY=/home/xena/Documents/HJLab/new1306/GFF
ENABLE_ANTIALIASING=true
SAM.GROUP_OPTION=NONE
SAM.SORT_OPTION=STRAND
SHOW_SEQUENCE_TRANSLATION=true
SAM.COLOR_BY=READ_STRAND
SAM.INVERT_SORT=false
SAM.FLAG_LARGE_INDELS=false
DEFAULT_GENOME_KEY=/media/xena/Backup_AmyBoyd2024/chr1only.fa
SAM.SHOW_ALIGNMENT_TRACK=true

##RNA
SAM.SORT_OPTION=STRAND
SAM.SHOW_JUNCTION_TRACK=false
SAM.INVERT_SORT=false
SAM.SHOW_ALIGNMENT_TRACK=false

##THIRD_GEN
SAM.SORT_OPTION=STRAND
SAM.MAX_VISIBLE_RANGE=1000
SAM.INVERT_SORT=false

**Comment by jrobinso** [comment]
Sorry I mispoke,  did you try what was suggested with prefs.properties?

**Comment by aboyd003** [comment]
Resetting the prefs.properties worked. 
Thank you for helping me with this issue. I will no in the future where to find the log and properties files :)

**Comment by jrobinso** [comment]
Thanks for your patience.   I'm able to reproduce the issue with your properties.  The next step is to determine which property is causing the issue.  I will report back here.

**Comment by jrobinso** [comment]
Ahh I see it.   The following properties were all set to false.  So there was nothing to show

```
SAM.SHOW_COV_TRACK=false
SAM.SHOW_JUNCTION_TRACK=false
SAM.SHOW_ALIGNMENT_TRACK=false
```

**Comment by aboyd003** [comment]
That makes sense. I do not remember setting those but I cannot imagine it is something that happens by accident.
