### ISSUE TITLE
Feature request: Open gappedPeak files

### ISSUE THREAD

**Issue by sandertan** [igvteam/igv#157]
Files are similar to .narrowPeak and .broadPeak, used by Encode and are outputed by MACS2 (with --broad). I can open the file if I rename it to .bed. Would be great if IGV automatically supports the gappedPeak format.

**Comment by jrobinso** [comment]
Could you attach or provide a link to an example file?  I browsed the Encode downloads pages but haven't found one yet.

**Comment by sandertan** [comment]
Hi Jim,

Thanks for the quick response. Here you can find some examples:
http://www.broadinstitute.org/~anshul/projects/encode/rawdata/peaks_histone/mar2012/broad/combrep_and_ppr/

And here is a bit off info on how they are used:
https://sites.google.com/site/anshulkundaje/projects/encodehistonemods

Kind regards,
Sander

**Comment by jrobinso** [comment]
Gapped peak files are now supported (extension .gappedPeak) in the snapshot build.  This will be included in the next release.
