### ISSUE TITLE
Right-Click mode

### ISSUE THREAD

**Issue by minw2828** [igvteam/igv#1575]
Hello,

I'm sorry in advance if the following question has already been asked before. I searched but could not find a similar topic through browsing the subject line. 

When I opened the IGV app through the manual approach and right-clicked the alignment track, I saw the following:
<img width="400" alt="Figure1" src="https://github.com/user-attachments/assets/bc7f0a3d-35bb-4692-b5a6-6287af467d51">

But when I opened a session file that I generated, I saw the following when I right-clicked the alignment track. 
<img width="385" alt="Figure2" src="https://github.com/user-attachments/assets/b31e4d79-dd09-4595-b158-a25112b6fea6">

When I compared the session file from the manual approach with my coded session file, both files started with 
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Session genome="hg38" version="8">
```
The rest of the files had the same structure that defined the content of the session files. Hence, I could not identify the cause of the difference in the right-click mode from the session files. 

Could you advise why the right-click modes are different and how I might be able to fix it please? 

Many thanks,
Min

**Comment by jrobinso** [comment]
According to the popup you have 3 tracks selected.  The menu presented are items that are common to all 3 track types.  I can't determine from the popup what the other 2 tracks are.  

To deselect all tracks just hit the escape key.

**Comment by minw2828** [comment]
Hello @jrobinso, 

Thank you for your quick reply. 

My puzzle wasn't about what tracks being selected. I did not understand why I saw two different right-click panels from the two session files. 

Was it because my session file was generated from your API, but from a generic python library for XML? 

Many thanks, 
Min

**Comment by jrobinso** [comment]
I don't think it has anything to do with sessions, rather how many and what type of tracks you have selected.  If you have a heterogenous collection of tracks selected you will see the second menu.   Without knowing exactly what is selected I really can't say.   

I don't understand the comment about "your API", what are you referring to?

**Comment by minw2828** [comment]
Hello @jrobinso,

Thank you for patiently debugging this through with me. :)

I aim to code a session file (my_session.xml) that is the same as the one saved from manual input (saved_session.xml). 

In both session files, I loaded three VCF files to the variant panel, one normal bam file to one alignment panel, and one tumour bam file to the other alignment panel. 

In the saved_session.xml, a junction track was hidden (visible="false") for each alignment panel, and the coverage track was listed as a separate record from the alignment track. Hence, I coded my_session.xml the same as saved_session.xml.

Does the above fall into your definiton of "a heterogenous collection of tracks"? 

Because I loaded the same files/tracks in my_session.xml as saved_session.xml to recreate saved_session.xml, I am puzzled why the right-click panel in saved_session.xml,

**Comment by jrobinso** [comment]
Hi,

When I said selected heteorgeneous files I mean manually clicking on the name panels to select them before right clicking.  This has nothing to do with session files. 

Secondly,  I can't really comment on session files unless you post them.   If you think a session file is causing this behavior I really need to see one that I can load.   If you can reproduce this behavior with public files please post the zipped XML here.  You can find public files for the hg19 assembly under "File > Load from Server..."
