### ISSUE TITLE
copy sequence does not work

### ISSUE THREAD

**Issue by BenxiaHu** [igvteam/igv#1582]
Hello,
  I tries to copy sequences in the highlighted regions. however, the copy sequence does not copy anything.

<img width="1127" alt="image" src="https://github.com/user-attachments/assets/3c9b741b-019f-4505-9278-c03fcdf463b6">

**Comment by jrobinso** [comment]
What version of IGV are you using?  Also, can you tell the coordinates of the region, and the genome assembly you have loaded?

**Comment by BenxiaHu** [comment]
What version of IGV are you using?  >=2.18.0
can you tell the coordinates of the region---any genomic region
the genome assembly you have loaded?--no

**Comment by jrobinso** [comment]
I can't reproduce the problem with IGV 2.18.2,  hg19, region chr8:128749973-128751536

**Comment by BenxiaHu** [comment]
![image](https://github.com/user-attachments/assets/20c187ec-18b7-442e-abbd-09a419c02409)

**Comment by BenxiaHu** [comment]
copy sequencec doesnot copy any sequences.

**Comment by BenxiaHu** [comment]
Now it works.
thanks
