### ISSUE TITLE
"Error repainting view" Issue loading reference.

### ISSUE THREAD

**Issue by Jfen101** [igvteam/igv#1583]
Hello, 

I am running into an issue where I am unable to zoom in to see the reference or any alignments to only ChrM in the Human (T2T chm13-V2.0/hs1) reference. This only occurs on this contig, other references seem unaffected.

![image](https://github.com/user-attachments/assets/ca34c496-b8c4-45c6-bd89-7a3ad7bafcb6)
[igv0.log](https://github.com/user-attachments/files/17128317/igv0.log)

I have tried reloading the reference and deleting all IGV related folders I can find including hidden folders before reinstalling but the issue persists.

Any help would be appreciated.

Many thanks,

Joe

**Comment by lbergelson** [comment]
I can confirm that I see the same issue.

**Comment by jrobinso** [comment]
@Jfen101 Thanks for the report,  we will include the fix in the next bug fix release.
