### ISSUE TITLE
Export the report for SNP list, base, depth of coverage from IGV

### ISSUE THREAD

**Issue by Szuchieh17** [igvteam/igv#1591]
Hi all
I am conducting the Nanopore sequencing and using IGV to conduct SNP calling by uploading VCF file output from EPI2ME lab, and I would like to inquire whether it is possible to export a list of all the SNPs on a chromosome, including the bases and the depth of coverage. It is my first time to use this software. I greatly appreciate your help.

**Comment by jrobinso** [comment]
This is not possible with IGV.  IGV does not call SNPS, it is just a visualization tool.   You should be able to get that information from your VCF file.

**Comment by Szuchieh17** [comment]
Hi
I uploaded the VCF file output from EPI2ME Lab, and I would like to inquire whether I can export entire information as excel file or other file to view easily because I have to view information by clicking the color block. I greatly appreciate your help.

**Comment by jrobinso** [comment]
Hi, once again, no, you cannot do that from IGV.

**Comment by Szuchieh17** [comment]
Hi 

I apologize for any inconvenience. I was worried about inappropriate description. I copied the description from my advisor “ What we are looking for is probably from IGV.  Recall during our meeting this week that you hovered your mouse over the colors in the IGV output.  A box appeared that gave information on that position.  Some had low coverage and an apparent difference between the expected genotype, for instance GT, with what was observed, G.  But the coverage was very low.  This is what we are looking for across a chromosome. Hence, we need a list of all the SNPs on a chromosome, including the bases and the the depth of coverage.” Additionally, may I inquire what mean by getting information from VCF file? I really apologize for any inconvenience. I greatly appreciate your help.

**Comment by Szuchieh17** [comment]
Thank you so much for your help!

**Comment by jrobinso** [comment]
Doing a search on "vcf filter by read depth" should turn up something useful.

**Comment by Szuchieh17** [comment]
Hi 
I have a question. The information said that the VCF file is text file, and it can be opened on PC using Notepad. However, when I tried to use Notepad to open it, there are a lot of garbled information. I would like to inquire whether it is normal. Additionally, the approach of the VCF file is from the storage drive, and I would like to inquire whether it causes this troubleshooting. I greatly appreciate your help.

**Comment by jrobinso** [comment]
I'm going to refer you to biostars, these questions are not really about IGV.   https://www.biostars.org/

**Comment by Szuchieh17** [comment]
Got it. I apologize for any inconvenience. I greatly appreciate your help.
