### ISSUE TITLE
Load From Server Error

### ISSUE THREAD

**Issue by helrick** [igvteam/igv#1593]
Hi there,

Since today, when I try to 'Load From Server' on IGV desktop I get an error: 
```
The following urls could not be processed due to load failures: https://igv.org/genomes/data/hg38/hg38_annotations.xml The reference to entity "g" must end with the ';' delimiter
```

It looks like this might be due to some misconfiguration in the xml? When I try to view the [XML link](https://igv.org/genomes/data/hg38/hg38_annotations.xml) in a browser I see the same error:
<img width="705" alt="Screenshot 2024-10-03 at 13 30 40" src="https://github.com/user-attachments/assets/8a8ed516-429f-45b5-8149-a509a6627d55">

Let me know if I can provide any more information.

**Comment by duartemolha** [comment]
same here
slightly different error message
![image](https://github.com/user-attachments/assets/7317ef13-e6d3-4a06-8c86-d9957aaebf22)

**Comment by jrobinso** [comment]
Sorry about that, it should be fixed now.

**Comment by helrick** [comment]
Cheers, thanks! Can confirm it's working properly now.
