### ISSUE TITLE
The meaning of SNP color in vatiant track

### ISSUE THREAD

**Issue by charliechen912ilovbash** [igvteam/igv#1605]
Normally, a heterozygous SNP in the variant track (vcf format input) will be shown as red-blue.
However, some variants in my data are gray. Could you tell me what does this mean?
It seems to be caused by low QUAL.

**Comment by jrobinso** [comment]
I would need details about the variant or your VCF to answer, but usually it means the alternate alleles are non-reference (either  NON_REF or *).

**Comment by charliechen912ilovbash** [comment]
This is one of the gray SNP records.
`chr1    178023755       .       A       T       23.98   PASS    F       GT:GQ:DP:AD:AF:PS       1|0:23:28:14,14:0.5:177998655`

**Comment by jrobinso** [comment]
Could you zip and attach a small vcf, it only needs to have this one record.   I can't read this in IGV without the VCF header.    

Also, what version of IGV are you using?

**Comment by charliechen912ilovbash** [comment]
Sure!
[test.vcf.gz](https://github.com/user-attachments/files/17483872/test.vcf.gz)

I am using version 2.8.2.

**Comment by jrobinso** [comment]
Did you mean 2.18.2?  I have no idea what 2.8.2 did to be honest.  Here's what I see with the latest release (2.18.4)

<img width="726" alt="Screenshot 2024-10-22 at 7 39 51 PM" src="https://github.com/user-attachments/assets/8ea56227-3470-47d4-bd84-b48bc3cb083a">

**Comment by charliechen912ilovbash** [comment]
When I click "about IGV", it shows the version is 2.8.2.03  03/23/2020.
I think it is the below version.
https://igv.org/doc/desktop/#ReleaseNotes/2.8.x/

**Comment by charliechen912ilovbash** [comment]
But the question is the same.
In version 2.18.4, the heterozygous SNP is in red-blue, homozygous SNP is red. 
I am wondering the meaning of the blue SNP.

**Comment by jrobinso** [comment]
I'm not a VCF expert but I don't understand this file.   AF (allele frequency) is not listed as a genotype field in the VCF spec, it is an INFO field (https://samtools.github.io/hts-specs/VCFv4.2.pdf).   I don't think I've ever seen an AF field on a genotype,  it is legal but it is not going to be interpreted as the allele frequency for the variant.   So in this case the AF for the variant is unknown, and it is just drawn a solid blue.  

@lbergelson Does this look normal to you?  IGV gets allele frequency from `variantContext.getAttributeAsString("AF")`,  it does not do anything special with AF attributes on genotypes.

```
##fileformat=VCFv4.2
##source=Clair3
##clair3_version=1.0.9
##cmdline=/opt/bin/run_clair3.sh --bam_fn=/home/charlie/hepatoblastoma/clair3/JC-HB-1001-LR01-N/chr1/JC-HB-1001-LR01-N.chr1.bam --ref_fn=/home/charlie/hepatoblastoma/ref/GRCh38.d1.vd1.fa.split/GRCh38.d1.vd1.part_chr1.fa --threads=4 --platform=ont --model_path=/home/charlie/clair3_models/r1041_e82_400bps_sup_v420 --output=/home/charlie/hepatoblastoma/clair3/JC-HB-1001-LR01-N/chr1 --ctg_name=chr1
##reference=/home/charlie/hepatoblastoma/ref/GRCh38.d1.vd1.fa.split/GRCh38.d1.vd1.part_chr1.fa
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=LowQual,Description="Low quality variant">
##FILTER=<ID=RefCall,Description="Reference call">
##INFO=<ID=P,Number=0,Type=Flag,Description="Result from pileup calling">
##INFO=<ID=F,Number=0,Type=Flag,Description="Result from full-alignment calling">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads 1. with MQ below 5 or an user-specified threshold, or 2. selected by 'samtools view -F 2316', are filtered)">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##FORMAT=<ID=AF,Number=A,Type=Float,Description="Observed allele frequency in reads, for each ALT allele, in the same order as listed, or the REF allele for a RefCall">
##contig=<ID=chr1,length=248956422>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE
chr1	178023755	.	A	T	23.98	PASS	F	GT:GQ:DP:AD:AF	0/1:23:28:14,14:0.5000
```

**Comment by charliechen912ilovbash** [comment]
Sorry I forgot to delete the file path in the vcf.
Could you delete the file path in the above comment ? (/home/charlie/......)
Thanks

**Comment by jrobinso** [comment]
Done, good catch.   So I think the question is answered,  there is no allele frequency information for the variant so its not going to be drawn in two colors.   That will be true of all records in this file as AF is not listed as an ##INFO field.    I was under the impression you saw AF information (red/blue) for some records, but not others.   I do not understand what an allele frequency for a genotype means, but again I'm not a VCF expert.

**Comment by jrobinso** [comment]
Actually I'll hazard a guess based on the description,  they are recording the fraction of reads for that sample (genotype) that show the allele.   I've not seen this before, but IGV does not do anything with that information.   It looks for Allele Frequencey (AF) or Allele Count (AC) attributes on the variant (INFO), if not missing you will get a solid color.

**Comment by charliechen912ilovbash** [comment]
Thank you.
I understood where the problem is.
I may try moving the AF information to the INFO, so then IGV can show the SNP in two colors.
By the way, in the future, will IGV also recognize this kind of AF record?

**Comment by jrobinso** [comment]
@charliechen912ilovbash If it does it will be to color the genotype, not the variant, but I'm unsure.  I've never seen this field associated with a genotype, and its not mentioned in the 4.2 or 4.3 specs.    So its unlikely at this time.   In this case it wouldn't add any additional information, genotypes are already colored by zygosity.   Grey for homozygous reference, blue for heterzygous, and cyan for homozygous variant (1/1).

Was this file produced as is by Clair3?

**Comment by charliechen912ilovbash** [comment]
Yes I generated the vcf by Clair3, the version is v1.0.9

**Comment by jrobinso** [comment]
Well, once again it is information on the genotype not the variant.  If we expand coloring options for genotypes we might consider it, but it would not address this question as it concerns coloring for the variant.

**Comment by lbergelson** [comment]
I don't remember seeing AF as a FORMAT field for germline calls before.  It's an important value for somatic mutations though.  Typically it's called Allele Fraction and not Allele Frequency.   Mutect produces this field but describes it differently.   It's important in somatic calls because the fraction is important in determining things like subclonality and unlike germline calls it varies a lot.

I don't have any plans to coloring the variant itself by format values, although that might be a reasonable feature if there is only a single sample in the VCF.  

The branch I'm working on now will let you color the genotypes by an arbitrary format field, so if you expand the genotypes you could get coloring based on this.
