### ISSUE TITLE
Setting IGV window width & height via port or batch file interface

### ISSUE THREAD

**Issue by bw2** [igvteam/igv#161]
Is there a way to control IGV window width & height through these interfaces? 
Currently, I'm not finding a way to do this, and end up with screenshots that aren't wide enough (or tall enough, although I see that maxPanelHeight can be used to deal with height).

**Comment by jrobinso** [comment]
There's no way to manipulate actual width and height of the window, 
which of course would not be a good idea when running igv as a client.   
Running "headless" is not something we support or have time to test, 
although we are aware that people do it.    The only way to 
programmatically maniuplate window size would be to manipulate the 
"prefs.properties" file in the igv directory of the user that it is run 
under.  Specifically set the IGV.Bounds property, which is left, top, 
width, height

IGV.Bounds=267,22,1150,800

**Comment by bw2** [comment]
I see. That should be good enough. Thanks!

**Comment by jingcruk** [comment]
By this way a window size larger than the screen size is not allowed. Is there any way that I can preset a window size which is not constraint by the screen size, without debugging the source code?  Many thanks.

**Comment by jrobinso** [comment]
I don't understand what you are asking,  how could you present a window
larger than the screen?

**Comment by yubau1112** [comment]
Why always is "IGV.Bounds=0,0,1150,800"
I chang that, but it change by itself 
Can I set "IGV.Bounds=0,0,2048,1080" ?

**Comment by jrobinso** [comment]
Dose you screen support that resolution?   That is not meant to be a user-settable value, it simply records the size of the IGV window when it is shut down.   Setting this is not a supported function.
