### ISSUE TITLE
Base display cuts off at an undefined grey line

### ISSUE THREAD

**Issue by rowi2024** [igvteam/igv#1612]
Hello,
I wonder if anyone can tell me how to remove the grey line (at about 27,263 bp) that seems to be cutting off base display of the reads.  The position of this line shifts as I change the magnification.
I have "Quick consensus mode" turned off.
Below, I aligned a subset of nanopore reads to an ~100 kb linear DNA segment using minimap2.
Samtools was used to convert to bam files.
I'm using IGV Version 2.9.4.
Thanks for any advice!
![image](https://github.com/user-attachments/assets/5525cf18-86b0-4327-8087-a518e5a36f2e)

**Comment by jrobinso** [comment]
Hi, that is a very old version of IGV and I can't answer your question precisely,  but that looks like the center line which is turned off and on through the preferences.   However it has nothing to do with the read display.    I have no explanation for that, I have not seen it before.   If you can reproduce the issue in the latest release (2.18.4) I will look into it further.

**Comment by rowi2024** [comment]
I just updated IGV, and this took care of the problem!  Thanks again for the suggestion.
