### ISSUE TITLE
Nucleotides not displayed in IGV 2.18.4

### ISSUE THREAD

**Issue by evaluca** [igvteam/igv#1619]
Hi all, 

I am using the IGV 2.18.4 app on my MacBook M1. 

Usually, zooming in completely on a region of a target sequence suffice to display the nucleotide sequence of this particular region. 

Since I updated IGV to version 2.18.1 back in August, little gray boxes are displayed instead of the color-coded nucleotides. I tried to get the latest update (2.18.4) but it did not solve the problem. I attached a screenshot so you can see what I mean. 

Has anyone encountered this issue ? And do you have any idea how to solve it ?

Thanks in advance for your help ! 

Eva Lucarelli, PhD student
University of Liège, Belgium

![Capture d’écran 2024-11-19 à 12 30 42](https://github.com/user-attachments/assets/844d01aa-a4e6-4381-b582-0c4ce395e97f)

**Comment by jrobinso** [comment]
I can't reproduce this issue, below is what I see for those coordinates.    You might try refreshing your "genome" file for hg38, which you can do from the Genomes menu.   

<img width="1168" alt="Screenshot 2024-11-19 at 9 19 11 AM" src="https://github.com/user-attachments/assets/9b95c908-976e-4247-a629-edabb708e1a5">

**Comment by evaluca** [comment]
Hello jrobinso, thanks for your answer! What you suggested solved my problem. 

Have a nice day!
