### ISSUE TITLE
.gsawoman file load

### ISSUE THREAD

**Issue by Xue77966** [igvteam/igv#1627]
Version 2.18.4, Windows.
I changed the suffix of the gff file as demonstrated in the cookbook, but I couldn't successfully read it. Consequently, my interface lacks the "genome.woman" section, I can't proceed subsequent operations. Could you please tell me how to solve this problem? Thank you very much.
<img width="848" alt="76b475f015ce35441519372792b6985" src="https://github.com/user-attachments/assets/a9cb6c36-4d34-48a1-ab17-1eb2230f9678">
<img width="1260" alt="cc309e8e51509ca0004f131f28a5467" src="https://github.com/user-attachments/assets/af7b8b27-7e8c-4d9f-95c5-74e40bba8e8b">
<img width="308" alt="f57c6965c0e725e20559c31cfadd6ac" src="https://github.com/user-attachments/assets/21f236d8-edac-42f9-a68b-2ed01af54d29">

My files are in a same folder
<img width="193" alt="1733318334138" src="https://github.com/user-attachments/assets/af24b20b-b061-46f9-8f56-8df8e3441f0b">

**Comment by jrobinso** [comment]
You cannot change the extension (suffix) of a gff3 file.    What cookbook are you referring to?

**Comment by Xue77966** [comment]
<img width="1260" alt="1733336084848" src="https://github.com/user-attachments/assets/a0c50a46-d339-4de2-bd6d-92ddb52be362">
The step shown in the GIF image, what I understand is creating a copy of the genome GFF3 file and change its suffix. 
Am I misunderstanding something? Please advise me. Thank you so much.

**Comment by jrobinso** [comment]
You referred to a "cookbook",  I don't know what that is but you cannot change the extension (suffix) of a gff file, or really any type of genomic data file.  IGV uses the extension (suffix) to determine the file type.      So my advice to you is to not do that.

**Comment by Xue77966** [comment]
The cook book I referred is from https://www.yuque.com/cjchen/ra7ghy/udlbcgx4ygcb4l0k.
How can I get the "gsawomn" file? Could you please guide me on how to generate this type of data? Thank you so much.

**Comment by Guoboxiong** [comment]
I have same problem,can you help me to solve proplem?
![Uploading 屏幕截图 2025-01-02 095420.png…]()

**Comment by Guoboxiong** [comment]
![屏幕截图 2025-01-02 095420](https://github.com/user-attachments/assets/d8cbc209-b1ca-4503-ad44-cd77036a0743)

**Comment by jrobinso** [comment]
As I've already explained above, the extension ".gsaman" and ".gsawoman" are not recognized by IGV.   You cannot name your files like that, the extension has to reflect the file type.  I suggest deleting the ".gsaman" extension and trying again.
