### ISSUE TITLE
Mouse (GRCm39/mm39) reference genome missing "Load From Server" option

### ISSUE THREAD

**Issue by tud03125** [igvteam/igv#1629]
Do you know how to get the "Load From Server" option for the Mouse (GRCm39/mm39) reference genome? When I checked the other ones: Mouse (GRCm38/mm10) or Human (hg18) reference genomes, they both have "Load From Server" option, but Mouse (GRCm39/mm39) reference genome does not. And, I need it for RepeatMasker, to load TEs or ERVs underneath "Coverage" Track. I have Version 2.18.2, which's "08/21/2024 12:06 PM" (though I think I downloaded somewhere last month, but definitely not in August). Any ideas how to get "Load From Server" option for the Mouse (GRCm39/mm39) reference genome on my IGV app, inside my Windows 11 PC laptop?

**Comment by jrobinso** [comment]
Hi, sorry but we do not have any configured extra (i.e. "load from server") tracks for mm39,  you will need to find and load the tracks you want on your own.
