### ISSUE TITLE
Truncated features search result box

### ISSUE THREAD

**Issue by sjackman** [igvteam/igv#163]
When I search for the name of a feature in the location text entry box and press enter, a modal dialog box "Features" pops up with the results of the search. It shows the first 20 results, and no more. It doesn't scroll. It would be nice to show all results and scroll through them.

**Comment by sjackman** [comment]
My use case is a GFF file of annotation evidence as output by MAKER. It's a GFF file of BLAST alignments.

**Comment by jrobinso** [comment]
Oops, commit was for wrong git issue.   I'll tackle this one next.
