### ISSUE TITLE
Fails to reload newly saved igv_session.xml

### ISSUE THREAD

**Issue by mmoisse** [igvteam/igv#166]
On the newest version of IGV (v2.3.59) I don't seem to be able to save and reload sessions unless I edit the xml myself and remove the path variable in the Session line and remove all ../ in the Resources lines.
Session files created by older IGV versions work just fine.

I'm using java 1.6 on a mac 10.6.8

> \<Session genome="hg19" hasGeneTrack="true" hasSequenceTrack="true" locus="All" path="/Users/IGV/igv_session.xml" version="8">
>     \<Resources>
>         \<Resource path="../../Volumes/MD3200/bamfiles/Sample.bam"/>
> ...

**Comment by sandertan** [comment]
I'm experiencing this issue. Thanks mmoisse for identifying this problem. In my saved xml files its missing the full path.

This is what it saves:
<Resource path="Data1/Project1/Sample1.tdf"/>

And I think this is what it should save:
<Resource path="/home/myname/Data1/Project1/Sample1.tdf"/>

**Comment by jrobinso** [comment]
Hi,  the original report is very Mac specific,  "../../Volumes" is not a valid path.     Paths in session are saved as relative to the location of the session file,  this is intentional and in response to many requests.  We could perhaps make that behavior optional by user preference.   What does the path in the "Session" element at the top of the file say?

**Comment by mmoisse** [comment]
Hi,

I've been looking into my issue in a little more detail and found out that the problem is caused by the combination of mac and symlinks.
My issue occurs whenever I try to save a session in a folder with a symlink in its path. The filepath seems to be wrongly resolved, see examples below:

Session file without symlink in path. Works fine
> \<?xml version="1.0" encoding="UTF-8" standalone="no"?>
> \<Session genome="hg18" hasGeneTrack="true" hasSequenceTrack="true" locus="chr17:10071907-10071948" path="/Users/IGV/Documents/GeneFiles/Projects/igv_session.xml" version="8">
> \<Resources>
>    \<Resource path="../../../../../Volumes/MD3200/bamfiles/Sample.bam"/>
> ...


Session file with symlink in path: Projects links to /Users/IGV/Documents/GeneFiles/Projects/
> \<?xml version="1.0" encoding="UTF-8" standalone="no"?>
> \<Session genome="hg18" hasGeneTrack="true" hasSequenceTrack="true" locus="chr17:10071907-10071948" path="/Users/IGV/Projects/igv_session.2.xml" version="8">
>     \<Resources>
>         \<Resource path="../../../Volumes/MD3200/bamfiles/Sample.bam"/>
> ...

Error message:
> Error loading SAM header: java.io.FileNotFoundException: /Users/IGV/Volumes/MD3200/bamfiles/Sample.bam (No such file or directory)

**Comment by sandertan** [comment]
For me on Ubuntu the files are also in a folder which is an symbolic link, and saving the session works when I save a session with files from a 'normal' folder.

**Comment by jrobinso** [comment]
I see, thanks for the clue its helpful.

**Comment by jrobinso** [comment]
Thanks for the update,  this will be helpful.   I will try to resolve 
this by the end of next week,  I am quite literally in the middle of a 
cross-country move.

**Comment by jrobinso** [comment]
I can't reproduce the problem with Java 1.8 on a Mac (Yosemite).   What I'm going to do is make saving sessions with relative paths optional, via a user preference.    This will give you the opportunity to restore the old behavior.    BTW we won't be able to support Java 1.6 much longer,  the htsjdk which is used for BAM and VCF files is now requiring Java 1.8.

**Comment by jrobinso** [comment]
Sessions will now save absolute paths, which should resolve this problem.

**Comment by donutbrew** [comment]
Using the latest (2.8.6 6/22/2020) on CentOS 8, and sessions do not save absolute paths in the Resources section.

Additionally, there are non-dereferenced symlinks in all the Track tag, the `id` attribute. They are absolute paths, but rely  on the symlink. 

Opening the file as gives me errors loading every track. Changing all paths in the xml to canonical, deferenced paths makes it work.

**Comment by jrobinso** [comment]
RE relative paths, that is the intended default behavior.  You can change
this with  "View > Preferences > General", the first checkbox.

I can't reproduce your problem on my Mac,  I suspect it has something to do
with the symlink.    I'll leave this open until that is reproduced and
fixed,  in the meantime try using absolute paths (uncheck in the
preferences).
