### ISSUE TITLE
Null pointer exception arrises when loading certain igv_session.xml files

### ISSUE THREAD

**Issue by fleharty** [igvteam/igv#167]
In the Variant Review Lunches, it is common for someone to generate an IGV session that is shared with other people in the group.

IGV works just fine for the person who generated the igv_session.xml file, however other people encounter null pointer exceptions when navigating to new sites.

It appears that it has something to do with information about the state of the GUI being contained within the xml file.  If this data is removed, the IGV session appears to work for everyone.

**Comment by jrobinso** [comment]
Could you elaborate on exactly what you needed to remove?    Also if you can please paste and "igv.log" file for a machine with the error here, and more details on how to reproduce the error.

**Comment by jrobinso** [comment]
Hi, could you please post a session file that exhibits the problem,  along with a note saying what you had to remove?
