### ISSUE TITLE
bug: VCFs and BED files from Google Cloud Storage paths do not open

### ISSUE THREAD

**Issue by deflaux** [igvteam/igv#175]
IGV Desktop opens BAM files expressed as Google Cloud Storage paths just fine (e.g., gs://my-bucket/my.bam) but other file types such as BED and VCF cause an immediate error.

**Comment by jrobinso** [comment]
Could you create an example bed that illustrates the problem?  Its not obvious what the problem could be, the URLs are translated as follows

gs://mybucket/my.bed

becomes

https://www.googleapis.com/storage/v1/b/mybucket/o/my.bed

Perhaps the translation rules for non-bam files differ?\

**Comment by jrobinso** [comment]
Never mind,  I see you have some test cases in email.   I'll repeat them here for the record

    I can open these fine:
        https://storage.googleapis.com/deflaux-public-test/NA12877.vcf.gz
        (and https://storage.googleapis.com/deflaux-public-test/NA12877.vcf.gz.tbi)
        https://storage.googleapis.com/deflaux-public-test/bed_chr_17.bed.gz (43MB, I will put a smaller bed file here shortly)
    But I cannot open them using the gs:// path
        gs://deflaux-public-test/NA12877.vcf.gz
        (and gs://deflaux-public-test/NA12877.vcf.gz.tbi)
        gs://deflaux-public-test/bed_chr_17.bed.gz

**Comment by jrobinso** [comment]
The problem appears to e a difference in URL translation rules WRT the earlier pattern I was given for bam files.   Is there a general rule for gs -> https web service urls?

**Comment by deflaux** [comment]
Thanks for taking a look Jim!

I got these urls from here https://cloud.google.com/storage/docs/json_api/v1/objects/get by pasting in `deflaux-public-test` for `bucket` and `NA12877.vcf.gz` for `object` and then grabbing the url from the `media` field.

This appears to be the correct url to download the data: https://www.googleapis.com/download/storage/v1/b/deflaux-public-test/o/NA12877.vcf.gz?generation=1440375388453000&alt=media

Compare this to https://www.googleapis.com/storage/v1/b/deflaux-public-test/o/NA12877.vcf.gz to get metadata about the data.

**Comment by jrobinso** [comment]
Does this vcf have an associated tabix index (.tbi) file?

**Comment by jrobinso** [comment]
Is the proper way to tranlsate these URLs to get the meta data first,  then use the mediaLink property?

**Comment by deflaux** [comment]
According to https://cloud.google.com/storage/docs/json_api/v1/objects/get you can skip a step --> the metadata url can be used for both metadata and the download _"By default, this responds with an object resource in the response body. If you provide the URL parameter alt=media, then it will respond with the object data in the response body."_

Is it possible that the problem is not the download, but that the file is gzipped but the url does not end in gz so the client doesn't realize its compressed?

**Comment by jrobinso** [comment]
Found it.  The bug is actually in the htsjdk.  I'll have to do a patch and pull request, if I can't find an IGV only workaround.

**Comment by deflaux** [comment]
that's great news Jim!

**Comment by jrobinso** [comment]
Reopening,  gs://deflaux-public-test/NA12877.vcf.gz  works, but gs://deflaux-public-test/bed_chr_17.bed.gz still does not.

**Comment by jrobinso** [comment]
OK, both indexed and non indexed vcf and bed files should work now.  I couldn't completely test the bed file because its so large,  but it did start loading.
