### ISSUE TITLE
TDF notes out of date

### ISSUE THREAD

**Issue by superbobry** [igvteam/igv#179]
Hello, it seems that the TDF spec is slightly out of sync with the implementation. For instance, the header section is defined as

```
Header
------
magic number  (32 bit int)
version       (32 bit int
index position  (64 bit long)
index size (bytes)  (32 bit int)
header size (bytes) (32 bit int -- # of bytes for rest of header).
# of window functions
[window functions]
track type (string)
track line (string)
# of tracks
```

while the code expects two additional fields:

```
genome (string)
flags (int)
```

I wonder if there's an up to date spec of the format somewhere or is it implementation-defined?

**Comment by HenrikBengtsson** [comment]
I'm also looking for formal specs/docs on the Tiled Data File (TDF) format - that would be great to have.

BTW, am I correct if I interpret TDF to be used as an "internal" file format for speeding up IGV and not really a file format for data sharing / archiving?  The reason why I ask is that there are now public data sets appearing in the TGV file format only (e.g. http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE70991), which seems a bit strange given that such data can only be used in IGV.

**Comment by jrobinso** [comment]
Hi,

Yes TDF was never published as an archival format.   It was developed 
before BigWig,  when BigWig was published there was no real reason to 
continue development of TDF except for IGV purposes.    There is a 
single development "resource" for IGV and igv.js,  that same person 
would also have to write the spec,  but I will keep this git issue open 
and try to do it.

**Comment by superbobry** [comment]
Hi Jim, 

Having implemented a TDF reader, I might be able to help with the spec. Would it be possible to make the spec open and editable via e.g. via GitHub Wiki/repo or even Google Docs?

**Comment by jrobinso** [comment]
Yes, for sure,  I can help with that if you want and will try to contribute.

Jim

**Comment by HenrikBengtsson** [comment]
Thanks for the replies and follow ups.

Just for the record, in case someone finds it useful, I noticed that I can use [`org.broad.igv.tdf.TDFUtils.tdfToBedgraph()`](https://github.com/igvteam/igv/blob/master/src/org/broad/igv/tdf/TDFUtils.java#L64-L98) to convert a TDF to a BED file.  Not sure if the BED file contains all information available though (modulo the index).

**Comment by jrobinso** [comment]
That converts to a bedgraph file.   It only works for "single track" 
TDFs,  which are the most common type.   Precomputed summary data for 
"zoom levels" is lost.

**Comment by superbobry** [comment]
I've started a draft on [Gist](https://gist.github.com/superbobry/c67614cbfe2a15d35d5c). It only covers binary organization of the format. Feel free to fork/comment.

**Comment by floem7** [comment]
Thank @HenrikBengtsson for the hint regarding conversion.
I'm a java noob so I'd like to ask how could I run TDFUtils' tdfToBedGraph in bash
