### ISSUE TITLE
Feature request: Merged genomes

### ISSUE THREAD

**Issue by chenyu32548** [igvteam/igv#182]
I would be nice to load more than one genome file at one time. For example, if we look at xenograft tumor sequencing, we map to both human and mouse. Sometimes, we'd want to look at pathogen and host at the same time. I know we can generate a new genome using fasta files for both human and mouse combined or we should use separate sessions. But it'd be nice to load more than one.

**Comment by jrobinso** [comment]
I don't understand how this would work.
