### ISSUE TITLE
Load from server IGV

### ISSUE THREAD

**Issue by duartemolha** [igvteam/igv#186]
Hi guys

I was wondering if and when you are planning to support all the data annotations you have for hg19 on hg38.

as you can see from the screenshots in attachment the hg19 has a fair amount of useful tracks to display with you data... hg38 selection is very limited indeed!

![hg19_load_from_server_tracks](https://cloud.githubusercontent.com/assets/722005/12451864/86aeacd0-bf83-11e5-9556-de50b0478396.PNG)

![hg38_load_from_server_tracks](https://cloud.githubusercontent.com/assets/722005/12451865/88a500ac-bf83-11e5-893c-67e6a34101f6.PNG)

**Comment by jrobinso** [comment]
Hi,  I add tracks as they are requested,  as time permits.  The accumulated
requests for hg19 is just much longer than hg38.  You can add a prioritized
list to this ticket, if you like.

**Comment by duartemolha** [comment]
that is ok... I was just wondering if I was missing something on my config in order to have more of these tracks. I am happy to wait for most of these to slowly become available.

It would be good to have the GC track though.

**Comment by jrobinso** [comment]
GC % has been added.   Please open another issue to request more tracks,  if not requested they probably won't get added.
