### ISSUE TITLE
#gffTags on bed file not displaying correctly on tooltips

### ISSUE THREAD

**Issue by duartemolha** [igvteam/igv#187]
Hi 

Based on the information provided here:
https://www.broadinstitute.org/software/igv/BED

we can use the name field on  a bed file to add key=value style atributes that get displayed in the IGV tooltips

I have tried this by it does not seem to be working.

Or more precisely.. it seems to be recognizing these are tags but as soon as it encounters a space it stops processing the remainer of the line.

According to this:
http://www.sequenceontology.org/gff3.shtml

spaces are supported and to not need to be escaped.

Can you tell me what I am doing wrong?

Best regards

Duarte

[example.txt](https://github.com/igvteam/igv/files/99303/example.txt)

**Comment by jrobinso** [comment]
The un-encoded spaces are tripping it up.   This is in igv bug, un-encoded spaces are allowed  in gff3 (but not in gff2).   I will look into a fix.

**Comment by jrobinso** [comment]
OK, I see the issue.  Un-encoded whitespace can't be allowed in bed files because bed files themselves are whitespace-delimited.  So to use GFF tags in a bed file you will need to url enocde the spaces, i.e replace spaces with %20.    This is not an issue for gff3 files as the fields are tab-delimited.  I will add a note to the documentation.

**Comment by duartemolha** [comment]
Hi .. I just replaced all spaces with %20 and by doing that the tags do not get displayed...

**Comment by duartemolha** [comment]
here is a sample of one of those files
[example_with_chr_space_encoding.txt](https://github.com/igvteam/igv/files/100527/example_with_chr_space_encoding.txt)

**Comment by jrobinso** [comment]
Your example is missing the #gffTags directive.  After adding it it 
works fine for me.
<https://github.com/igvteam/igv/files/100527/example_with_chr_space_encoding.txt>

**Comment by duartemolha** [comment]
so it is... rookie mistake :) many thanks




[image: --]
Duarte Molha
[image: https://]about.me/duarte
<https://about.me/duarte?promo=email_sig>
