### ISSUE TITLE
IGV tracks available on server

### ISSUE THREAD

**Issue by duartemolha** [igvteam/igv#188]
Hi ... As requested here are the tracks I would like to see available on hg38 whenever possible

Annotations\Genes\Ensemble Genes
Annotations\Genes\Genecode genes
Annotations\Phenotype and Disead Associations\COSMIC
Annotations\Phenotype and Disead Associations\OMIM Genes
1000 genomes - all

Many thanks

**Comment by jrobinso** [comment]
COSMIC does not allow distribution of their data anymore, unless they 
recently changed policy.

I'm not aware of any 1000 genomes data in hg38 coordinates,  could you 
point me to it?

**Comment by duartemolha** [comment]
sorry... you are correct... COSMIC is not free anymore, and 100 genomes is not yet in GRCh38..

what about the latest genecode track?

I can of course download them and open them directly... but it would be great if we could load them from the server anytime we wanted :)

Many thanks

**Comment by jrobinso** [comment]
Latest gencode (V24) has been added.

**Comment by duartemolha** [comment]
awesome! Many thanks
