### ISSUE TITLE
Feature Request: Export Track Names from IGV display

### ISSUE THREAD

**Issue by ctcncgr** [igvteam/igv#196]
Hey All,

I would like to be able to export selected track names into some sort of text file.  Lets say I have 100's of samples displayed in a VCF or MUT file and I want to export samples 100-120 after doing some sort of sort or filtering on an attribute.  I can currently shift + click the tracks for the samples, resulting in these samples being highlighted in grey, however I cannot export the names or meta data about the tracks in anyway.  I also cannot simply copy paste and have it retrieve the highlighted text.

I can mine these from the xml session file but this is very clumsy.

This is in reference to igv-help post:

https://groups.google.com/forum/#!topic/igv-help/DzsSr4h3uKA

Thank you for your consideration,

Connor

**Comment by jrobinso** [comment]
Hi, you can highlight samples from ".mut" files,  but you cannot highlight individual genotypes (samples) from VCF files.   This is a limitation in IGV which is not easy to get around,  the genotypes are not separate tracks.    I'm inclined to implement this by multi-selecting "tracks",  and adding export names & metadata to the menu,  but it will not work for VCF genotypes.   Will this meet the need?

**Comment by ctcncgr** [comment]
Hey Jim,

This is great, and exactly what I wanted.

Thank you,

Connor
