### ISSUE TITLE
sashimi plots for long genes (where zoom in to see alignment)

### ISSUE THREAD

**Issue by AMChalkie** [igvteam/igv#198]
Sashimi plots don't render when we need to zoom in to see the alignments. (i.e. mm10: chr1:138,060,859-138,177,305  gene Ptprc)

**Comment by jrobinso** [comment]
Could you be more specific?   If possible reproduce the problem with data I have access to, and be specific on the steps.

**Comment by AMChalkie** [comment]
Solved once I learnt more about navigating the sashimi plots. Assumed they were not dynamic! (Will RTFM in future)
