### ISSUE TITLE
Problem with IGV batch

### ISSUE THREAD

**Issue by haoziyeung** [igvteam/igv#200]
Hi,
when i use batch like this:

new
snapshotDirectory "snapshot"
maxPanelHeight 664
preference DEFAULT_FONT_FAMILY "Times New Roman"
load "session/C151207C04001.xml"
goto chr7:56088902
sort position chr7:56088902-56088902
snapshot "C151207C04001_chr7_56088902_56088902.png"
new
snapshotDirectory "snapshot"
maxPanelHeight 664
preference DEFAULT_FONT_FAMILY "Times New Roman"
load "session/C151214C03301.xml"
goto chr11:111680470
sort position chr11:111680470-111680470
snapshot "C151214C03301_chr11_111680470_111680470.png"

IGV software always pop up this warning:
“Unload current session before loading new tracks?”
need press "yes" ,then igv run again,but i don't want press this button N+ times ,can somebody tell me how to disable this confirm pop up menu?thanks alot.

**Comment by jrobinso** [comment]
Hmmm, yes that would get annoying.  No way to disable it, but I will add one for this week's release.

**Comment by haoziyeung** [comment]
thank you very much,i will download it this week,can you tell me which day of the week we can get the newset release?thanks again.

**Comment by haoziyeung** [comment]
SORRY for disturb you again,can you tell me how to control the zoom in & zoom out button via batch command ?thank you!

**Comment by haoziyeung** [comment]
@jrobinso #
![qq 20160225143352](https://cloud.githubusercontent.com/assets/16606564/13311848/d1503afa-dbcc-11e5-9d29-b6710a77c92e.png)

**Comment by jrobinso** [comment]
No command for that,  you have to explicitly set the locus to what you want.  See the user guide for available commands.    Watch this issue list for further updates, including release.

**Comment by haoziyeung** [comment]
OK,i see

**Comment by haoziyeung** [comment]
thank you for your help

**Comment by haoziyeung** [comment]
it's great,i just try new release version,it's fantastic !
