### ISSUE TITLE
Feature Request - Multitrack files

### ISSUE THREAD

**Issue by duartemolha** [igvteam/igv#206]
Hi.. if there any plans to support multitrack files in IGV? 

You already support track lines compatible with USCS genome browser. It would be great if we could create single files with multiple tracks and import tthem to IGV and visualize them as separate.

Thanks

**Comment by jrobinso** [comment]
Do you mean bed and wig files with multiple "track" lines?   This is 
difficult to support with indexing  (impossible actually).   We could 
possibly support this with the caveat that you can't index it.  First 
confirm that is what you mean.

What do the UCSC tools do if you try to make a bigbed or bigwig from one 
of these files?

Jim

**Comment by duartemolha** [comment]
yes... especially bed files ... it would be very helpfull.

I understand that these could not be indexed ...  The files I am dealing with are not that big and that would not be a big issue. 

But it would be helpful to be able to give a single file to a collaborator and have that file split into several tracks in IGV for analysis.

As for converting to bigbee... I do not believe bigbed format accepts more than multiple tracks

**Comment by jrobinso** [comment]
This would be too disruptive to implement for the benefits obtained.  The concept of a single header and track per bed or gff file is deeply embedded in underlying libraries (in particular "tribble") and would require some major hacks to get around.
