### ISSUE TITLE
Document GCS support

### ISSUE THREAD

**Issue by jean-philippe-martin** [igvteam/igv#207]
IGV can open files that are stored on Google Cloud Storage ("gs://" prefix). However, the [current documentation](https://www.broadinstitute.org/software/igv/LoadData) does not mention this fact.

We could add a section called "**Load from Google Cloud Storage**" that explains that we can load BAM files with a gs:// prefix. Something similar to what is on [Google Genomics' IGV page](http://googlegenomics.readthedocs.org/en/staging/use_cases/browse_genomic_data/igv.html) would be perfect.

**Comment by helgathorv** [comment]
The Load from URL doc has been updated to include a note about Google Cloud Storage.
