### ISSUE TITLE
Rename "Google" menu to "GA4GH (on Google)"

### ISSUE THREAD

**Issue by jean-philippe-martin** [igvteam/igv#208]
IGV's [menu bar](https://github.com/igvteam/igv/blob/master/src/org/broad/igv/ui/IGVMenuBar.java#L1135) has a "Google" entry to load data from Google Genomics using the GA4GH standard. As a way to emphasize that IGV could be easily adapted to read from other GA4GH servers, it would be nice to rename this menu item from "**Google**" to "**GA4GH (on Google)**".

(disclaimer: I work with Google Genomics)

**Comment by jrobinso** [comment]
The menu really is Google specific, it has OAuth login and logout, and the queries are hardcoded to go to the Google server.  Also, "GA4GH (on Google)" is too long for a menu.   We could rename it to just "GA4GH",  then maybe have a submenu or Google section within the menu.   Would this suffice?

**Comment by jrobinso** [comment]
Looking deeper into this, we also have a "Load from GA4GH..." item under the file menu.   Currently it just has a few example datasets from Google.  Perhaps all load functions should be here,  the the Google menu being reserved for OAuth login/logout.    @helgathorv  do you care to comment?

**Comment by jean-philippe-martin** [comment]
Your suggestion makes sense. We could leave the OAuth options in the Google menu and we would then have, under "File", the option to load either from that hardcoded list, or to provide our own ReadGroupSet ID. To make this even less Google-specific we can also offer the option of providing our own URL (pre-populated with the Google Genomics one by default).

So the "Load from GA4GH" page can end up looking something like that:

```
GA4GH
   |
   +--- Google 
   |       |
   |       +--------- 1000 Genomics
           +--------- Platinum Genomes
   |       +--------- PGP
   |       +--------- Simons Foundation
   |       
   +--- Custom
          |
         URL [ https://genomics.googleapis.com ]
         ReadGroupSet [ (type here) ]
```

Where we can either select one of the public datasets, or type in our own. As a bonus this allows one to try new GA4GH servers when they come live.

Another option would be to split this into two different screens: one for the list of public data on Google Genomics, and another for a custom GA4GH query (i.e. letting the user type in the ReadGroupSet ID and optionally change the URL). 

If that makes sense, the list of public data on Google might be merged with the "Load from server" option, adding a "Google" row to that dialog's list of available datasets.

So the end result could be:

**File / Load from server**

```
Available Datasets
   |
   +--- Annotations
   +--- TCGA
   +--- ...
   +--- Google
           |
           +---- 1000 Genomes
           +---- Platinum Genomes
           +---- PGP
           +---- Simons Foundation
           +---- ...
````
**File / Load from GA4GH**
````
         URL [ https://genomics.googleapis.com ]
         ReadGroupSet [ (type here) ]
````
