### ISSUE TITLE
Pop up option not working on IGV 2.3.69

### ISSUE THREAD

**Issue by Terim1** [igvteam/igv#209]
Im having difficulty getting my ChIPSeq data to autoscale since the popup menu does not appear to exist on the new IGV version, is this a bug? It doesn't appear to be working on the older IGV version I have either 2.3.36.

**Comment by jrobinso** [comment]
Sorry I can't find any popups that are not working.  Could you be more specific, about track types, etc,  also your operating system?

**Comment by Terim1** [comment]
Thanks for the fast reply jrobinso, Im visualising bedgraph.tdf files on a Mac OSX Yosemite version 10.10. Is there any option for autoscaling in the bar menu, I can't find any.

**Comment by jrobinso** [comment]
I'm not sure what you are referring to re "bar menu",  in the right-click popup menu for a tdf track I see this.  
<img width="549" alt="screen shot 2016-03-12 at 5 40 46 pm" src="https://cloud.githubusercontent.com/assets/933148/13726380/b5175260-e879-11e5-931c-d61655cafb22.png">

**Comment by Terim1** [comment]
When I right click nothing happens, I mean the top menu that says file, genomes, view, track etc, do you know of any autoscaling options within these headings? The right click worked before it just doesn't appear to be working now since I updated Java for the new download.

**Comment by jrobinso** [comment]
IGV its not usable without a right-click menu,  so you need to get that working.    I don't have Yosemite but many people do and no reports of this.  Does right-click, or control-click,  work with other applications?  What is the exact Java version?

**Comment by Terim1** [comment]
Java 8 update 73. It works with Control click, I only every tried command click and right click! Thats great, thank you so much! Its been driving me crazy for the last week!

**Comment by jrobinso** [comment]
Check your mouse settings from the Mac control panel,  or maybe try a different mouse.  Something changed but its hard to say what.

**Comment by Terim1** [comment]
Ok will do! Thanks a million :)
