### ISSUE TITLE
Mysterious insertion on 10X v2 data in "vacuum"

### ISSUE THREAD

**Issue by SHuang-Broad** [igvteam/igv#211]
Hi IGVTeam,

We are doing variant reviews on 10X data and found one weird issue.
You could reproduce the issue in this way:

1. Load the following session while connect to Broad-Internal (or VPN)
https://iwww.broadinstitute.org/igvdata/humgen/gsa-hpprojects/dev/fleharty/VariantReviewLunch/Mar-03-2016/callednotindb.xml

2. Go to location: 20:10,326,341-10,326,411

3. In the track "NA12878 from 10X v2 bamout", select "Group alignments by tag", and the tag is "HP". Then in the first group, there will be this mysterious single insertion of "AC" appearing by itself (vacuum).

I believe this isn't the intended result, but could be wrong.

Thanks.

**Comment by jrobinso** [comment]
I suppose that's a bug,  that insertion belongs to the alignment that appears to start about 5 bases to the right.   The cigar string is 2I5D71M  which is kind of weird.   The bug here is IGV apparently doesn't know how to draw an alignment that starts with a deletion.  I suppose this is legal,  haven't checked the spec, but not very common.   Thanks for the test file,  if you can leave it in place for a while it would be helpful.

**Comment by SHuang-Broad** [comment]
Thanks for the response, Jim. I got the IGV session from @fleharty, whom I also discussed with about this issue. I'll let him know that you prefer to have the test file available for a while.

**Comment by jrobinso** [comment]
That's o.k.,  I grabbed the portion I need.   How do these alignments 
arise (alignments that begin with a deletion)?

**Comment by fleharty** [comment]
@SHuang-Broad @jrobinso These files are intended to be achieved permanently.

**Comment by SHuang-Broad** [comment]
I'm not quite sure honestly. But the specific read is generated from a 10X pipeline, where, to my primitive understanding, an extra step of barcoding long molecules (1kb~10kb length) is carried out for better phasing before normal Solexa DNA shearing. @cwhelan is better knowledged with the actual pipeline.

**Comment by fleharty** [comment]
@jrobinso These alignments do not occur on our pipeline, they occur on the 10X pipeline which is probably why we haven't seen this.

**Comment by jrobinso** [comment]
Alignments that start with deletions and/or insertions should be rendered properly now.
