### ISSUE TITLE
Cannot open a BAM file that contains the string "refGene"

### ISSUE THREAD

**Issue by Tabea-K** [igvteam/igv#212]
When I try to open a BAM file that contains the string `refGene` in its name, IGV displays an error message, saying that it cannot find the index file, although this file is available.

For example, the files named `foo_refGene_bar.bam` and `foo_refGene_bar.bam.bai` don't work. But, when I rename them to `foo_bar.bam` and `foo_bar.bam.bai`, they can be opened.

I am using version 2.3.69 (98)

**Comment by jrobinso** [comment]
Yes, I see the problem.  That is definitely a bug,  the only workaround at the moment is to rename as you have.  Will fix asap.
