### ISSUE TITLE
Receiving message on batch run of IVGtools

### ISSUE THREAD

**Issue by dtnorth** [igvteam/igv#214]
Hi,

As of today, I am receiving the following message when running igvtools in batch mode.

"INFO: Although this software is installed and can be used on xxxxxx 
	 - the developers have requested users to register at their website.
	Therefore please register yourself as a user at:
		  https://www.broadinstitute.org/igv"

As I have already registered on the IGV site , how do I male the tool aware of this or can I just ignore the above message.

Regards

Derek Templeton Northcote
MRC Centre for Genetics and Genomics
Cardiff University
Wales.
UK

**Comment by helgathorv** [comment]
Hi Derek, 
You can just ignore it. 
BTW, where did you get the version of igvtools you are using? While we do like people to register, we did not insert that message. If it's centrally installed at your University, perhaps the IT team there added the message.

Thanks,
Helga

**Comment by jrobinso** [comment]
Hi,

That message isn't coming from our software,  and I don't know what 
"Raven" is.  Yes,  you can ignore the message.

Jim
