### ISSUE TITLE
Support GVCF format

### ISSUE THREAD

**Issue by sooheelee** [igvteam/igv#218]
IGV versions post 2.3.60 no longer color variant sites in the GVCF. All blocks are grey. This is because IGV no longer supports calculation of allele fractions and instead strictly displays AF/AC/AN values so that non-diploid genomes can be correctly displayed.

The [GVCF format](https://www.broadinstitute.org/gatk/guide/article?id=4017) is something GATK has been pushing and is part of the new Best Practice workflow. I understand it as an intermediate VCF, given per sample, that allows these multiple GVCFs then to be called jointly to give the canonical VCF. This per-sample level VCF allows researchers to skip having to joint call on all the BAMs again when they add samples to a cohort. All they have to do is take the GVCFs and call jointly.

One thing that is in these GVCFs in a symbolic allele <NON_REF> that calculates the likelihoods of a site not being reference without explicitly calling out a particular variant. These <NON_REF> blocks are the majority of the GVCF (the ones I shared with you) and allow the joint caller to calculate the confidence that a sample's site is REF versus there is just NO_DATA (e.g. no coverage) at the site.

The sample GVCFs I sent you at glance contain mainly these <NON_REF> sites. The variant sites look like the following:

```
20 10000000 . T <NON_REF> . . END=10000002 GT:DP:GQ:MIN_DP:PL 0/0:15:39:15:0,39,585
20 10003692 . A G,<NON_REF> 227.77 . BaseQRankSum=0.064;ClippingRankSum=0.529;DP=30;MLEAC=1,0;MLEAF=0.500,0.00;MQ=60.00;MQRankSum=-0.148;ReadPosRankSum=0.783 GT:AD:DP:GQ:PL:SB 0/1:18,12,0:30:99:256,0,453,309,488,797:10,8,2,10 
20 10004222 . C CA,<NON_REF> 149.73 . DP=19;MLEAC=2,0;MLEAF=1.00,0.00;MQ=60.00 GT:AD:DP:GQ:PL:SB 1/1:0,11,0:11:31:187,31,0,187,31,187:0,0,7,4
```

It looks like the AC and AF equivalents are MLEAC and MLEAF where MLE=maximum likelihood expectation. These are from the GVCF header:

```
##INFO=<ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
##INFO=<ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed"> 
```

I imagine IGV could take one of these metrics to again color the variant sites?

**Comment by sooheelee** [comment]
Perhaps @ldgauthier can comment on Jim's question on AN (total number of alleles in called genotype):

> Is there a GVCF equivalent for "AN",  or would that just be "1" by definition?

**Comment by ldgauthier** [comment]
We aren't guaranteed to produce AC, AF, or AN for gVCFs, but if PLs are present and they are not all zeros, then you can assume that AN is equal to the ploidy (namely 2 for humans).

**Comment by jrobinso** [comment]
Is there any attribute or property of a VCF that can be used to know or 
infer the ploidy?

**Comment by ldgauthier** [comment]
The number of entries in the genotype will do it, if the genotype is called.  Otherwise, you can infer from the number of alleles and number of PLs.
