### ISSUE TITLE
Fonts are pixelated on Retina screen

### ISSUE THREAD

**Issue by PFRoux** [igvteam/igv#220]
Dear all,

I am using IGV 2.3.72 on a MacBook Pro Retina running under El Capitan, with Java 8.77.
Even if not affecting the global performance of the tool, the fonts are pixelated despite the anti-aliasing and the option "scale fonts" being activated.

This issue has already been discussed before for 4K screens : https://github.com/igvteam/igv/issues/129
But I didn't manage to fix it so far on my MacBook.

Has someone experienced this too ?

All the best,

Pierre-François

**Comment by jrobinso** [comment]
I don't have any issues on my new MacBook Pro Retina running Yosemite, nor on my new iMac also running Yosemite.  Could you be more specific about which fonts (which panel).  A screenshot might help.

**Comment by igordot** [comment]
I have the same issue. I took a screenshot:
<img width="512" src="https://cloud.githubusercontent.com/assets/6363505/15031567/af0e6854-1227-11e6-833b-e07bab517ce2.png">
The native menu bar (with File, Genomes, etc) is retina. The IGV window content (genome name, chr, etc.) is pixelated.

**Comment by jrobinso** [comment]
I'm not actually sure there is a solution, but will leave this open to investigate.    I have 2 retina screens, iMac and Macbook, and don't have this problem.  Perhaps it is a function of of what native fonts are installed, but I'm not sure.    Do you have other Java programs installed, and do they look o.k.?

**Comment by igordot** [comment]
I don't think it's the fonts. I went through different fonts and none of them scale properly.

I don't have any other Java programs.

**Comment by jrobinso** [comment]
Well, its not retina per-se either as I have 2.  Do you have the "scale fonts" option checked on the general preferences, or not?   I tried both ways but don't see the problem with either.

**Comment by jrobinso** [comment]
This might be relevant, how are you launch IGV  (command-line, application, or java webstart)?

http://apple.stackexchange.com/questions/53741/java-and-mac-retina-support

**Comment by igordot** [comment]
I used the application. I just tried web start and the fonts are retina in that version.

I then added to `Contents/Info.plist` this:
```
<key>NSHighResolutionCapable</key>
<true/>
```
That fixed the problem.

**Comment by jrobinso** [comment]
Thanks, that's brilliant.  I will include this with the next release package.

**Comment by igordot** [comment]
I got that from the StackExchange link (Matt Solnit's answer), so thanks for finding that.

**Comment by PFRoux** [comment]
Hi there,

Thanks a lot for the suggestion. 
For any reason, I tried to modify `Contents/Info.plist` as igordot suggests but it doesn't change anything.
And as igordot noticed, when using the web start, the fonts are also retina on my computer.

**Comment by igordot** [comment]
@PFRoux The plist file contents are cached. If you rename the app (for example, from "IGV" to "IGVX"), it will reload the plist. You can also try moving it to a different directory and then moving it back to Applications.

**Comment by jrobinso** [comment]
This is more difficult than I hoped to implement in the build script.  We use JarAppBundler and it does not allow one to manipulate the plist.   Meanwhile the manual solution suggested by Igor should work.

**Comment by igordot** [comment]
@jrobinso It looks like there is a bug report about it from 2012:
https://java.net/jira/browse/APPBUNDLER-12
There is also this workaround (also from 2012, so may or not still be applicable):
http://lists.apple.com/archives/java-dev/2012/Dec/msg00009.html
