### ISSUE TITLE
Sequence resolution threshold

### ISSUE THREAD

**Issue by amohajeri** [igvteam/igv#223]
Hi,

I have a problem with Sequence resolution threshold when running batch file to take snapshots. For the first two position sequence resolution is the default setting and  high but after that it changed to a very small resolution. I have no setting in my batch files and I am not sure why this is changing automatically. 

This is an example of one of my batch files:

new
genome hg18
load DIRECTORY-To-bam
snapshotDirectory Output-Directory
goto chr4:176135576-176135576
sort base
collapse
snapshot
goto chr4:176135596-176135596
sort base
collapse
snapshot
goto chr4:176135619-176135619
sort base
collapse
snapshot

**Comment by amohajeri** [comment]
Issue resolved :)

**Comment by jrobinso** [comment]
OK,  I haven't had a chance to try your script but I suspect the problem was you were specifying a range of zero bases.

**Comment by amohajeri** [comment]
No the zero bases was okay. this is what I always use in IGV. The issue was using collapse. I wasn't really using collapse function and i wasn't inputting anything for that.
