### ISSUE TITLE
Sorting by base on XML

### ISSUE THREAD

**Issue by rghu** [igvteam/igv#224]
I am loading BAM files on IGV using html links (https://www.broadinstitute.org/igv/ControlIGV). After loading the xml session file, I routinely sort by base. I would like to automate this operation.  Is it possible to specify the sort in the session file? If yes, which variable do I use for this action?

**Comment by jrobinso** [comment]
Unfortunately these is not a way to do this.  There should be, but there isn't.   I'll treat this as a feature request,  and try to do it in the next point release.   Respond to this comment if too much time passes.
