### ISSUE TITLE
[Feature Request] IGVtools command line can return number of insertions and deletions

### ISSUE THREAD

**Issue by kwgsmith** [igvteam/igv#225]
I am attempting to recreate the information from the coverage track with the igvtools through the command line. Right now I can get the counts of the ACTG, but to get the complete report as seen here:

![readsfromivg](https://cloud.githubusercontent.com/assets/8976581/14713103/65bfbe28-07a5-11e6-84ce-8f5dc9b7025e.png)

I also need to be able to get insertions and deletions.

This feature would be greatly appreciated!

**Comment by jrobinso** [comment]
Hi,  can you download and try again?  There were 2 issues, one resolved, and one not a real issue
(1) insertions were being counted as deletions (FIXED)
(2) insertions really don't have a position, they occur between 2 bases.   In the gui we show an insertion count on either side of the insertion point (left and right flanking base).   In igvtools the insertion is counted only on the left flanking base (base preceding insertion).     Its possible we will change the UI to conform to igvtools,  but as a visual component its purpose is different.

**Comment by kwgsmith** [comment]
Great! This works perfectly. Thank you so much!
