### ISSUE TITLE
Setting IGV user directory does not work on Mac OS

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#230]
https://groups.google.com/d/msgid/igv-help/ef70f665-0964-46cc-8f78-df9f914ccdf8%40googlegroups.com?utm_medium=email&utm_source=footer

On  Mac with OS 10.11 this doesn't work for me. I can go to the Preferences menu to select a different directory, but the "OK" button after I make the change is not responsive and the new directory is not saved. I'm trying to keep my IGV data on an external drive since I use multiple computers and it would be helpful to get this to work!

Here's info about my IGV and java.

[Main.java:99] [main]  Startup  IGV Version 2.3.68 (97)01/13/2016 04:53 PM
[Main.java:100] [main]  Java 1.8.0_66

On Thursday, March 3, 2016 at 3:33:30 PM UTC-7, Jim Robinson wrote:

```
Hi,

There is no option in the shell file, however you can start it once and then use the preferences window (“Advanced” tab) to change the directory.   After this shutdown and it should be remembered.  On some Linux platforms this doesn’t work as the Java preferences support is broken,  but it usually does work.

Startup flag is a good idea, I will add that as a feature request.

Jim
```

> ```
> On Mar 3, 2016, at 2:22 PM, Kirill Tsyganov <kirill....@monash.edu> wrote:
> 
> Hi guys, 
> 
> How do you set different home directory for IGV i.e this INFO [2016-03-04 09:19:22,632]  [DirectoryManager.java:163] [main]  IGV Directory: /home/kirill/igv
> I'd like to set to ~/.igv instead.. ~/igv directory annoys me..  Is there an option I can put in my igv.sh file ? 
> 
> Thanks in advance, 
> 
> Kirill 
> ```

**Comment by jrobinso** [comment]
Its working for me with Mac OS 10.10.5.  I do not have a 10.11 Mac to test on,  will leave this open until I have a means to reproduce.

**Comment by outpaddling** [comment]
The move option under preferences does not work for me at all.  The file browser allows you to navigate directories, but there is no way to select one.  The only way out of the file browser is clicking Cancel.

**Comment by jrobinso** [comment]
It works for me (Big Sur 11.6,  IGV version 2.11.9).

**Comment by outpaddling** [comment]
Actually, never mind.  I thought I was on the latest version, but I was not.  2.11.9 works for me as well.  Thanks...
