### ISSUE TITLE
idiomatic way to programmatically create session files

### ISSUE THREAD

**Issue by holgerbrandl** [igvteam/igv#234]
I'd like to create a session file from a list of bams and beds. Since I'd like to do it often for various projects, I'd like to do it programmatically. Is there some tool already which I could use?

**Comment by jrobinso** [comment]
We don't have such a tool.  Others might, you could inquire on the google group or other informatics forums.   I'll leave this open and treat it as a feature request.

**Comment by holgerbrandl** [comment]
In case somebody has the same idea/need: I've created a small tool to do so. See [make_igv_session](https://github.com/holgerbrandl/kutils/blob/master/src/main/kotlin/de/mpicbg/scicomp/bioinfo/igv/README.md) for docs and details.

**Comment by jrobinso** [comment]
Awesome, thanks.
