### ISSUE TITLE
Migrate GA4GH support from Google v1beta2 to v1

### ISSUE THREAD

**Issue by mbookman** [igvteam/igv#235]
The v1beta2 API is deprecated.
IGV should be upgraded to v1.

Looking at Ga4ghAPIHelper.java, Ga4ghAlignmentReader.java, this may be as minimal as changing:

```
"https://www.googleapis.com/genomics/v1beta2",
```

to

```
"https://genomics.googleapis.com/v1"
```

For more migration details, see:

http://googlegenomics.readthedocs.io/en/latest/migrating_v1beta2_to_v1.html

**Comment by jrobinso** [comment]
Something has changed, I get a 400 error for this request.   I don't see anything in the migration guide that is pertinent.

https://genomics.googleapis.com/v1/reads/search?key=<key>

{"readGroupSetIds": ["CMvnhpKTFhCjz9_25e_lCw"], "referenceName": "chr8", "start": "128732265", "end": "128769729", "pageSize": "10000"}

**Comment by mbookman** [comment]
Hi Jim,

Is the location correct? I just tested this with the APIs explorer on the documentation site:

https://cloud.google.com/genomics/reference/rest/v1/reads/search

and with chr8 I get the same response. It suggests using "8" as the reference_name, which worked.

-Matt

**Comment by jrobinso** [comment]
Yea I just caught that and deleted the comment.  Still debugging, something has changed.  Perhaps the # of reads returned per page is less.   The old API returns right away on the query, the new one appears to hang.  Will update when I know more.

**Comment by jrobinso** [comment]
Found it.  In the old API I would get "null" for nextPageToken when results were complete.  Now I get an empty string.  This was causing an infinite loop.
