### ISSUE TITLE
Insertion size flag not working

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#236]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/igv-help/ORL9rH0xxAE/Qm9o4dTAAAAJ

**Comment by amwenger** [comment]
It looks like this issue has (at least) 2 parts:

1. Changes to the "large insertion" threshold are not reflected immediately.  I think #305 addresses this.
2. Feature request to hide insertions.  #295 could be adapted to provide this by adding a setting to let users specify the basepair size of insertions/deletions to hide.  While I like the "dynamic" resolution-based approach in the pull request, an explicit setting that defines the "hide" threshold in basepairs would be easier for users to control and understand.

**Comment by jrobinso** [comment]
I just pushed an implementation for suggestion #2,  setting SAM_MIN_INDEL_SIZE.   This is not exclusive to the min pixel width,  they can co-exist.

**Comment by amwenger** [comment]
@jrobinso I can not speak for the issue submitter, but between #295 and #305 I think this issue is resolved.
