### ISSUE TITLE
Access genome information via Google Cloud Storage

### ISSUE THREAD

**Issue by tomsing1** [igvteam/igv#238]
It's great to be able to view a BAM from Google Cloud Storage. Would it be possible to extend this functionality to also read genome information from Google Cloud Storage? 

For context: when collaborating on a non-model organism, it is now easy to share BAM files with collaborators via Cloud Storage, but they still need to download & index the corresponding reference genome files from elsewhere. 

It would be great to either serve indexed genomes from Cloud storage or - if that's not feasible - to retrieve the raw data (fasta, gff, etc) from there.

**Comment by jrobinso** [comment]
Hi,

I don't understand the request,  most of our fasta and other files are 
hosted in S3 storage.  What specifically is the problem?

Jim

**Comment by tomsing1** [comment]
Hi Jim,
sorry for not being clear. I was wondering if there is a way to allow users to add custom entries to the genome list as gs://URLs. Right now, I can add a custom genome locally, but not without downloading it from cloud storage. Does that make sense?

Thomas

**Comment by jrobinso** [comment]
Sorry, my fault, I mentally translated Google to Amazon.   However, gs:// urls are supported in igv.js.   Are you using the latest version?  If its not working for you can you post a test "config" object with public gs urls?.

**Comment by jrobinso** [comment]
Ping, any clarification?  If not I'll close this issue.
