### ISSUE TITLE
Setting maxPanelHeight through batch script with command line isn't working. 

### ISSUE THREAD

**Issue by gunho-park** [igvteam/igv#239]
Hello, Jim.

I found out it had been the issue at different website in below link.

 **https://groups.google.com/forum/#!topic/igv-help/LPruViUnrm0**

The phenomena is that setting the maxPanelHeight with GUI [ Tools > Run Batch Script ] is working well, but setting the one through below command line with -b option is not working.

**java -Xmx750m -jar igv.jar -b ../BAM/test/batch_script**

When checking out the png files output, the value of maxPanelHeight is not applied.
And above testing was conducted under the linux enviroment with IGV Version 2.3.72.
I wrote the simple batch script setting the maxPanelHeight option and making snapshot.

 **new
 genome hg19
 load  /home/ghpark/Downloads/BAM/test_1.chrM_2000_2100.bam
 snapshotDirectory /home/ghpark/Downloads/temp/
 goto chrM:1-1000
 sort position
 maxPanelHeight 3000
 snapshot**

I wonder this issue is going to be fixed.

Cheers.

**Comment by jrobinso** [comment]
I can't reproduce it, it works as intended with my test scripts.  Could you create a script with a publically available file that reproduces the problem?  Althernatively create a small bam and attach it here.

**Comment by gunho-park** [comment]
No problem.

My environment is under Ubuntu 14.04.

Used command line is below.

**java -Xmx750m -jar igv.jar -b ../BAM/test/batch_script**

I attached a zip file including batch script, bam and bai file for testing.

Thanks for following up this issue.

[upload.zip](https://github.com/igvteam/igv/files/278862/upload.zip)

**Comment by jrobinso** [comment]
OK, I'll try to look at it tomorrow.

**Comment by gunho-park** [comment]
Also, I'm uploading png files the one through command line and the other through GUI [ Tools > Run Batch Script ].

The name of png file through command line is chrM_1_1,000_1.png.

The other one through GUI is chrM_1_1,000_2.png.

Right, thanks!

[png_files.zip](https://github.com/igvteam/igv/files/278872/png_files.zip)

**Comment by jrobinso** [comment]
This should now be fixed in v 2.3.73

**Comment by gunho-park** [comment]
It's working well. 
Thanks for figuring out!

Cheer~
