### ISSUE TITLE
IGV imports features for searching from unsorted (and un-indexed) GFFs but not from indexed GFFs

### ISSUE THREAD

**Issue by vladimirg** [igvteam/igv#244]
Hello,

I'm working with Candida albicans Assembly 22, and genomic features as published on the Candida Genome Database. "Jumping" to named features is an excellent ability, but strangely enough sorting the GFF gives the paradoxical result of that ability not working anymore. The genome and unsorted GFF attached as a zip: [A22.zip](https://github.com/igvteam/igv/files/288359/A22.zip).

Specs: IGV 2.3.74, Mac OS X 10.11.5, Java 1.7.0_71-b14.

Steps to reproduce:

1. Open IGV.
2. Select the appropriate genome.
3. Open an unsorted GFF file.
4. IGV will suggest creating an index file, fail, and suggest to sort it.
5. Look up a gene anyway (say, HSP90) - it'll jump to that gene.
6. Dutifully sort the GFF using igvtools.
7. Close IGV (the GFF cache doesn't seem to be cleared even after starting a new session).
8. Open IGV, select the same genome as in step 2.
9. Open the sorted GFF this time.
10. IGV will proceed to index it without errors.
11. Search for the same gene as in step 5 - it doesn't work (gives a "cannot find feature" error message).

While I'd expect the search in step 5 to perhaps fail, the search in step 11 should definitely work.

Thank you!

**Comment by jrobinso** [comment]
Hi, this is normal,  searching does not work with indexed files.  Searching relies on having the features loaded in memory, and with an index they are not.  That is the point of an index.   Delete the index (the .idx file) and searching will working again.  This has nothing to do with sorting per se.     

So if you want to search,  say no (or cancel?) when IGV suggests to index.

**Comment by vladimirg** [comment]
OK, this works, but is extremely unintuitive. Especially since if an index file is already created, the user is given no option about this (of course, as you say, they can delete it). Isn't the whole point of loading a feature file is to use it to search the genome? Perhaps there is a more appropriate way to do this I'm missing?

**Comment by jrobinso** [comment]
The point of loading a feature file for most is to visualize the 
features.   Think about this critically,  an index is used to load just 
the small slice of the file you are viewing.   There is no way to have 
information on anything else in the file, it is not loaded.

**Comment by olechnwin** [comment]
Hi,
I'm wondering whether there is a workaround for this. I tried to load the un-indexed gff file but it requires an index file. I assumed because the file is too big. Can I somehow load another track with features or something similar so it can be searched?

**Comment by jrobinso** [comment]
Any non-indexed annotation file (gff, bed, etc) can be used to support
search.     GFF files typically have a parent gene and/or transcript record
and then many child records such as exons, cdrs, utrs, etc.   If you grep
out just the parent records (e.g. gene) you should have a much smaller file
that can be loaded without problem.   If you convert that to a 4 column bed
file, rather trivial with awk,  you will have an even smaller file.

**Comment by olechnwin** [comment]
@jrobinso,
Thank you so much for your suggestions.
