### ISSUE TITLE
Potentially issue with alignment with D as the first operation in CIGAR

### ISSUE THREAD

**Issue by FrankFeng** [igvteam/igv#249]
Hi there,

It seems IGV (V 2.3.75) doesn't correctly show the alignment with D as the first operation in the CIGAR string. It mistakenly shows the alignment with position shifted.

Below is an example alignment and how it is shown in IGV:

3M02027:253:000000000-ANYE7:1:1106:8190:19290	99	17	29663615	60	2D128M	=	29663717	275	TTTTTTTTTTTAAAAAAAAAAATCCTGCTTCTTTACAGGTTATTGGAAGGATGTGCAAAATAATTGACAAGACATGCTTATCTCCAACTCCTACTTTAGAACAACATCTTATGTGGGATGATATTGCT	HHHHHHGGGGGFGFGGGGGGGCHFGHFCGHFFFHHDF33FGDFDG3GHHGFHGGFB4FG2GFFHHF3?FG0C2FG3CBFGHDGFHHFGG22FFGHHHH3<G22F/FCCGHDGDFG1//<?1?1?G11F	NM:i:3	AS:i:136	XS:i:23	RG:Z:random_IVMWOC

P.S. There is not problem when I (insertion) is the first operation in the CIGAR.

Regards,

Frank

![igv_snapshot](https://cloud.githubusercontent.com/assets/4476144/15735561/eeb3525e-28d8-11e6-9e73-0a1a09a7af98.png)

**Comment by jrobinso** [comment]
Could you hover over the first base (the deleted one) and see what the 
position is?   Also, attache the sam file,  the whitespace does not 
survive a cut & paste into email.

**Comment by FrankFeng** [comment]
Hi @jrobinso 

When hovering over the first base (the deleted one), I see the position is the POS value in the SAM file, which is 29663615 in this example. According to the SAM specification, the POS value in a SAM file is the "leftmost mapping position of the first matching base", so if D is the first operation in CIGAR, there is no need to the rest to the right-hand side.

The SAM file is already attached (I renamed the file extension to .txt as it didn't allow me to upload a sam file directly). Thanks.

[d_is_1st_operation.sam.txt](https://github.com/igvteam/igv/files/296905/d_is_1st_operation.sam.txt)

**Comment by jrobinso** [comment]
Hi,

I think you are misinterpreting the meaning of "mapping base",  the "D" 
is considered a mapping base in this context.   Its poorly worded, I agree.

Jim

**Comment by jrobinso** [comment]
I should clarify,  the software that produced this sam is possibly misinterpreting the spec, or has some other bug.  I believe IGV is correctly interpreting this alignment,  did you say what software produced this?  I thought you had, but don't see it above.

**Comment by FrankFeng** [comment]
Thanks Jim.

This is the result of trimming after alignment. The original CIGAR string was "10M2D128M", and because the first 10 bases (aka the 10M in CIGAR) was a primer sequence (synthetic DNA), so we removed the first 10 bases before variant calling and got "2D128M" left. So here 2D128M means a 2-base deletion plus 128 mapping bases.

**Comment by jrobinso** [comment]
When you trimmed the first 10 bases that should have shifted the position by 10,  not by 12, is that what happened?

There was a similiar discussion some time ago,  link below.   I conferred with Heng Li on the correct interpretation and he confirmed the current implementation.   This is not the correct forum to discuss this, I'm a neutral arbiter.   I'm not sure who keeps the SAM specification now, not Heng, perhaps the GA4GH?

**Comment by jrobinso** [comment]
Here is the last discussion, on the samtools-devel mailing list

https://sourceforge.net/p/samtools/mailman/message/34096246/

**Comment by jrobinso** [comment]
And if you are interested in further reading, see  https://github.com/samtools/hts-specs/issues/80

I think that forum is the correct place to discuss this,  you could open a new issue (and reference issue 80) or comment on issue 80.   If you do so comment here so I can follow.

**Comment by FrankFeng** [comment]
Thank you very much Jim. You are right. The "D" is a mapping base. I am closing this issue.
