### ISSUE TITLE
data range scaling

### ISSUE THREAD

**Issue by zrsmith** [igvteam/igv#25]
IGV is awesome.  One extremely useful feature would be to be able to scale the data range of multiple tracks simultaneously and/or to autoscale groups of tracks to the same data range.  If you are using IGV to view and compare RNA-seq, ChIP-seq, etc., you will have many tracks that need to be viewed on the same scale, but the scale will vary dramatically for each locus you view. RIght clicking and setting the range for each track every time you view a different locus is very tedious.  An example is IGB, which is exremely slow, but has scroll bars that control the data range view for multiple tracks.

Thanks,

Zachery Smith
Postdoc
Danforth Center

**Comment by duartemolha** [comment]
Has this feature improvement been abandoned?

**Comment by jrobinso** [comment]
Not abandoned,  but obviously not on schedule.

**Comment by jrobinso** [comment]
Just checked in partial progress on this,  e5807eac4512350687a16fed093236153cc4aa21.

However,  in looking back the original question got hijacked.  For the record the OP asked how to set scales manually,  you have to uncheck autoscale.   This was answered, but got sidetracked to a related question (group autoscale).

**Comment by AsproV** [comment]
Is there a bug in the recent version that would be link to this?
I tried to load BedGraph files and scale them manually but the "autoscale" check box does not "check" anymore, and manual scaling also have no effect (setDataRange) ...

**Comment by jrobinso** [comment]
Yes there was.   Just pushed fix.

**Comment by jrobinso** [comment]
Group autoscale has been implemented,
