### ISSUE TITLE
Can't get to mRNA feature information through "Copy Details to Clipboard"

### ISSUE THREAD

**Issue by rmzelle** [igvteam/igv#251]
With either Collapsed or Expanded view, I'm not able to access the "mRNA" feature information of genes through "Copy Details to Clipboard". My GFF3 file looks like:

```
scaffold12_size430423	AUGUSTUS	gene	269342	271066	.	+	0	ID=x_g374;Name=GAL2
scaffold12_size430423	AUGUSTUS	mRNA	269342	271066	.	+	0	ID=x_g374.t1;Parent=x_g374;product=Galactose transporter;accession=P13181;translation=...
scaffold12_size430423	AUGUSTUS	exon	269342	271063	0.92	+	0	ID=x_g374.t1.269342-exon;Parent=x_g374.t1
scaffold12_size430423	AUGUSTUS	CDS	269342	271063	0.92	+	0	ID=x_g374.t1.269342-CDS;Name=GAL2;Parent=x_g374.t1
```

The popup text of the GAL2 gene above looks like this in Collapsed view:

![image](https://cloud.githubusercontent.com/assets/77951/15754329/b9e1e292-28c5-11e6-89fe-381f1d85f6ca.png)

But when I use "Copy Details to Clipboard", I only get the popup text for the parent "gene" feature:

> <b>GAL2</b>
scaffold12_size430423:269342-271066
Type = gene
id = x_g374

> <b>ID</b>:&nbsp;x_g374<br/><b>Name</b>:&nbsp;GAL2<br/>
scaffold12_size430423:269342-271066

In Expanded view, I can get the "gene" and "exon"/"CDS" feature information, but not the "mRNA" one.

Wouldn't it make more sense if IGV copied all the pop-up text in Collapsed view to the clipboard, and not just the pop-up text of a single feature.

**Comment by jrobinso** [comment]
It is supposed to work like that (copy all text), so this is a bug.

**Comment by rmzelle** [comment]
I just tried IGV 2.3.76, and I still don't get all the text from the popup in the clipboard when I use  "Copy Details to Clipboard".

**Comment by jrobinso** [comment]
Could you file a separate issue for that.  Sometimes things like this 
get missed when multiple issues are combined in 1 ticket.

As a workaround you should be able to use the "Show on click" popup text 
option, then use ctrl-a / ctrl-c  (command-a / command-c) to copy the 
contents to the clipboard.

**Comment by jrobinso** [comment]
Sorry, it was I who misunderstood the report,  because some information was actually dropped from the popup text dialog when features were collapsed.    The copy details to clipboard does in fact just do the first feature.  I was incorrect in stating that the intent was to do all features you are over.  This should probably be clarified in documentation,  but it is deeply embedded and would be too disruptive to change.   Perhaps we could add a "copy" icon to the popup text when using "show on click" mode,  but you can already do that using ctrl-a / ctrl-c.

**Comment by rmzelle** [comment]
> The copy details to clipboard does in fact just do the first feature. ... it is deeply embedded and would be too disruptive to change.

Ah, okay. Do you mean that it would be hard to code, or that you wouldn't want to change the behavior for the user?

There isn't a way to change to what extent features are expanded, right? Even in Expanded view, I only get two boxes instead of four. One for the "gene", and one for the "mRNA"/"exon"/"CDS" features. Using "Copy Details to Clipboard" on the latter copies the "exon" information for me. If I could get the "mRNA" feature to render separately, I could right-click it.

**Comment by jrobinso** [comment]
To hard to code,  the menu is built around selection of a single feature.

I don't understand the second comment "2 boxes instead of 4".   The exon 
and CDS features are constitutive parts of the mRNA, not distinct 
features on their own (see the Parent field in column 9). That is how 
IGV and every other browser I am aware of treats them.

**Comment by rmzelle** [comment]
> The exon and CDS features are constitutive parts of the mRNA, not distinct
features on their own (see the Parent field in column 9). That is how
IGV and every other browser I am aware of treats them.

Okay. I figured each line from the GFF could be shown as an individual feature, but I'm not too familiar with the conventions here.

The main reason for opening this issue in the first place was that I'm looking for a way to access the protein sequence of genes. Is there perhaps another (better) way to do this? Thanks for your time.
(in my GFF files, the translated protein sequences are stored on the "translation" attribute of the mRNA features, which seems reasonable)

**Comment by jrobinso** [comment]
I would just script something to extract them,  I don't think a genome 
browser is the most efficient way to do that.

**Comment by rmzelle** [comment]
I didn't mean in bulk. My use case is to use IGV to make it easy for my colleagues to explore genomes and give them the ability to easily access the annotations of any given feature. It's probably easiest to write some documentation for them on how to switch to "show on click" mode and copy and paste the feature information, then, as you originally suggested.

**Comment by jrobinso** [comment]
Or tell them to expand the track and click on the specific transcript 
that they are interested in.  The copy/paste workaround is only 
necessary if you want information on all overlapping features / 
transcripts / etc at a given locus.   This is not a very common use 
case, which is why it has only just arisen as in issue.

**Comment by rmzelle** [comment]
> Or tell them to expand the track and click on the specific transcript
that they are interested in.

That doesn't work for me without editing my GFF files, since all ORFs have overlapping exon/CDS/mRNA features.

Actually, it seems a bit odd that when I use expanded view, the ID of the "mRNA" feature is shown ("x_g374.t1"):

![image](https://cloud.githubusercontent.com/assets/77951/16011396/56c46b08-3153-11e6-9037-94ef1628cb34.png)

But when I use "Copy Details to Clipboard" on this feature, I get the "exon" feature information. Shouldn't it give the "mRNA" feature information?

**Comment by jrobinso** [comment]
You are right, that is odd (the exon info).  That was a bug, just fixed.  If you could try the snapshot build, it has the fix, which will be included in next release.  The snapshot is available at  http://www.broadinstitute.org/software/igv/download_snapshot.

Your example contains 2 features in IGV terms,  a "gene" record and an mRNA.  The exon and CDS records are just constitutive components of the mRNA.     So the overlapping records here are gene and mRNA.  Expanding the track lets you select the feature you are interested in.

**Comment by rmzelle** [comment]
Thanks so much! This solves my issue!

Now I get the results from the entire mRNA record in expanded view, which is great:

```
scaffold2_size1257356:67302-69026

ID: x_g3960.t1
Parent: x_g3960
product: Galactose transporter
accession: P13181
translation: ...
---------------------------
ID: x.t1.67302-exon
Parent: x_g3960.t1
---------------------------
ID: x_g3960.t1.67302-CDS
Name: GAL2
Parent: x_g3960.t1
```

**Comment by jrobinso** [comment]
Thanks for your patience and reports.
