### ISSUE TITLE
Group autoscale broken when using shift-click to select tracks

### ISSUE THREAD

**Issue by duartemolha** [igvteam/igv#253]
Hi

I see there has been an implementation of group autoscale. However I have a question regarding this

Does this only work for 2 tracks at a time?

I have a set of bam files open (10)
and I would like to select all of them and set group autoscale to that in every interval I am at the space is the maximum of any of the bam coverage tracks.

I noticed that we first need to deselect autoscale from every track and then select 2 tracks and the option from group autoscale is then visible... however if you do the same to 3 coverage tracks the option is not there any longer

What am I doing wrong?

Thanks

**Comment by jrobinso** [comment]
Hi,

There is no limit on the # of group autoscale tracks.  Also, you do not 
have to de-select autoscale first.   To group autoscale you have to 
select numeric tracks only, if you select feature or alignment tracks as 
well it will only show you menu items that in common for all of them.   
So select only the coverage tracks (or combination of coverage and wig 
type tracks).

**Comment by jrobinso** [comment]
Hmmm,   I can't reproduce either problem.   Could you send me a screenshot of what the menu looks like, and if possible what the IGV screen looks like?   Also your prefs.properties file.

**Comment by duartemolha** [comment]
![igv](https://cloud.githubusercontent.com/assets/722005/15980199/6851e600-2f61-11e6-8ca6-ba0435558ff1.png)

here is a screenshot

**Comment by jrobinso** [comment]
Note that it says you have 7 tracks selected.   Some of the view is 
scolled out

**Comment by duartemolha** [comment]
Content of prefs file:

SAM.SORT_OPTION=START
DEFAULT_GENOME_KEY=hg19
DETAILS_BEHAVIOR=CLICK
SESSION.RELATIVE_PATH=true
GENOME_LIST=hg19;hg18;hg38;b37
ENABLE_ANTIALIASING=true
SAM.SHOW_ALIGNMENT_TRACK=false
LAST_TRACK_DIRECTORY=U:\src\genomesdata\data\repeats
LAST_SESSION_DIRECTORY=U:\Projects\1469-OGT_Haematological_Cancel_Panels\ND-42_CLL_PANEL\2016-04-08_ReportV1
IGV.track.show.attribute.views=true
IGV.single.track.pane=true
LAST_CHROMOSOME_VIEWED_KEY=All
SAM.FILTER_SECONDARY_ALIGNMENTS=false
IGV.Session.recent.sessions=C:\Users\duartem\Desktop\BED_AN~1\Design_IGV_viewer_session.xml
IGV.Bounds=-8,-8,1936,1186
SCALE_FONTS=true
IGV.Frame.ExtendedState=6
IONTORRENT.RESULTS=../../alignments/36_S12_L001.bam,../../Genotypes/Filtered/36_S12_L001-recalBAMS_INDELS.vcf.gz
ENABLE_GOOGLE_MENU=true
LAST_SNAPSHOT_DIRECTORY=C:\Users\duartem\Desktop

**Comment by jrobinso** [comment]
I can reproduce this problem using shift-click to multi-select. That is 
the problem.   Not sure of the cause.   A workaround for now is to use 
individual selection,  command-click on a Mac,  I don't recall what it 
is on a PC.

**Comment by duartemolha** [comment]
ok... I can see now... I can do it with control+click

A bit less usefull than shift + click multiselect but will do ;)

**Comment by jrobinso** [comment]
By reproduce I mean see "7" tracks selected when in fact I chose 3.   I 
think what's happening is the shift-click is selecting the bam and 
splice junction track, even though they are hidden, because they are in 
the range selected.  I will fix this to skip hidden files.  In the 
meantime the only option is command-click on the mac, or equivalent on 
the PC.

You do not need to deselect auto-scale,  this is just a side effect of 
the shift-click bug.

**Comment by jrobinso** [comment]
Its only an interim solution,  I'll fix the shift-click bug

**Comment by duartemolha** [comment]
thanks... sorry for the bother
