### ISSUE TITLE
feature: add new panel

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#258]
I'm writing this feature request in the form of a speculative release note:

- "View > Reorder Panels" is now "View > Manage Panels" and the dialog now includes an option to add a new panel to the display.

**Comment by helgathorv** [comment]
Released in IGV 2.8.0

**Comment by hisplan** [comment]
No remove? At the moment, I would have to manually modify the session XML file...

**Comment by jrobinso** [comment]
When the last track in a panel is removed the panel itself is removed.
