### ISSUE TITLE
BUG? `group alignments > by chromosome of mate` v.  "mate is mapped = no"  

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#261]
`group alignments > by chromosome of mate`  incorrectly includes reads whose  "mate is mapped = no"  in the same group with reads whose mate is on the currently displayed chromosome.

**Comment by jrobinso** [comment]
Could you provide a small test case for this (i.e. small SAM or BAM file)?

**Comment by jrobinso** [comment]
OK, even though the mate is unmapped it is assigned the chromosome of its mapped partner.  Still I agree this is splitting hairs and not useful.   I will change it to have its own category.   Note this is not the same as an un-paired alignment (no mate at all), which will have yet another category.

**Comment by malcook** [comment]
Hi.  I'm actually quite glad you've addressed this.  I am using IGV to review the results of scaffolding assemblers and it greatly helps visualization to discern between these two cases.

If there is any way you can make one group listed first, this would also be a great addition.  Which group?  The one corresponding to the chromosome being viewed?

Even better would be able to filter by, oh many things, including to ONLY show read pairs both of which align to the current chromosome.

THANKS FOR IGV!

**Comment by jrobinso** [comment]
BTW you know you can flag alignments with un-mapped pairs with a red 
outline by checking "Flag unmapped pairs" in the preference window?

**Comment by malcook** [comment]
Hi - though useful, one of my needs is to distinguish read pairs where both mapped to same scaffold vs both mapped to different scaffold.  Thanks.


~ malcolm_cook@stowers.org
________________________________

**Comment by jrobinso** [comment]
I'm not sure if you'll ever find such detailed filters in IGV, the 
possible combinations would be endless.   Why don't you just spit the 
bam into 2 from the command line?

**Comment by malcook** [comment]
Sure thing - that's what I wind up doing - thanks for the suggestion


But, I still think filtering on the same attributes you already group and sort on (more or less) would a boon to certain applications.  When I come across other use cases I will +1 my own request and you can consider it again later.  Sound good?


Thanks for IGV,


Malcolm


~ malcolm_cook@stowers.org
________________________________

**Comment by jrobinso** [comment]
Yes, I agree on that.
