### ISSUE TITLE
unable to upload annotation from server for hg19

### ISSUE THREAD

**Issue by nbahlis** [igvteam/igv#262]
Hello

I am using IGV_2.3.59. As of last week I am no longer able to upload annotation from server. Did anything change or is it a bug?

**Comment by jrobinso** [comment]
Please be more explicit about the problem.  What exactly are you trying 
to load, from what assembly?   I assume you are referring to "Load from 
Server...".

**Comment by jrobinso** [comment]
I can't help you without details, nothing has changed on this end and 
they are working fine for me.

**Comment by nbahlis** [comment]
I get the message "No datasets are available for the current genome (hg19)" ....or hg18 or or hg38..I also tried from different location assuming it was the university firewall but I got the same message

**Comment by jrobinso** [comment]
There have been no changes here,  I just tested it.   Could you attach the contents of your igv.log file?  Also,  your "prefs.properties" file.     Also verify that you can load the following with a web browser: http://data.broadinstitute.org/igvdata/hg19_dataServerRegistry.txt.

**Comment by nbahlis** [comment]
It is working now, it was the address link to one of the servers I had connected to that was no longer valid. thank you
