### ISSUE TITLE
MD5 mismatch from default hg38 when using CRAM file aligned to Broad's hg38

### ISSUE THREAD

**Issue by meganshand** [igvteam/igv#264]
When opening a CRAM file that was aligned with hg38 using the Broad's hg38 reference files I got an MD5 mismatch exception when I tried to use IGV's default hg38 reference. Once I loaded the Broad's fasta file it worked fine. I appreciate the error to know that these two references are different, but am curious as to why the IGV hg38 files don't seem to match the Broad's files.

**Comment by jrobinso** [comment]
The 2 fasta files do in fact differ, specifically the fasta IGV uses for hg38 is soft-masked,  that is repeats and low complexity regions use lower case.  It looks like Broads reference is not.   So the MD5 check is working correctly.

**Comment by meganshand** [comment]
@yfarjoun Do you have any thoughts on this?

**Comment by jrobinso** [comment]
@yfarjoun Do you know how CRAM files are compressed if a soft-masked fasta is used for the reference (lower-case actg)?   Soft-masking doesn't make sense for a read sequence,  so perhaps the sequence is upper-cased first?   I tried googling for this and haven't found any information.

**Comment by yfarjoun** [comment]
I'd ask Vadim, but he isn't on this repo...

**Comment by jrobinso** [comment]
OK, we'll continue at https://github.com/samtools/htsjdk/issues/614

**Comment by jrobinso** [comment]
The answer is in the CRAM spec.   So IGV needs to upper-case the sequence used for CRAM decompression.  

"M5 (sequence MD5 checksum) field of @SQ sequence record in the BAM header is required and UR (URI for the sequence fasta optionally gzipped file) field is strongly advised. The rule for calculating MD5 is to remove any non-base symbols (like \n, sequence name or length and spaces) and upper case the rest."
