### ISSUE TITLE
Session.xml setting for "view as pair"

### ISSUE THREAD

**Issue by holtgrewe** [igvteam/igv#267]
Is it somehow possible to encode the "view as pair" for BAM tracks? This would be super useful!

**Comment by jrobinso** [comment]
Hi, did you try saving a session with "view as pairs" enabled?

**Comment by holtgrewe** [comment]
Yes, I did. After l loading, the "view as pair" option is cleared.

**Comment by jrobinso** [comment]
OK, this is a bug.
