### ISSUE TITLE
expand RefSeq Genes doesn't work in batch script

### ISSUE THREAD

**Issue by innamittal** [igvteam/igv#268]
Hi,

expand RefSeq Genes doesn't work in batch file.

CODE:

new
genome hg19
load test.bam
snapshotDirectory target/results
goto chr1:248487618-248487658
sort strand
viewaspairs
expand RefSeq Genes
snapshot 17.52241.248487638.png

Regards,
Inna

**Comment by jrobinso** [comment]
Did you try quoting the track name (it has whitespace)?

**Comment by innamittal** [comment]
I have tried with quotes, but still not working

expand 'RefSeq Genes'

**Comment by jrobinso** [comment]
Try double qoures " "

On Friday, July 1, 2016, innamittal <notifications@github.com> wrote:

> I have tried with quotes, but still not working
>
> expand 'RefSeq Genes'
>
> On Fri, Jul 1, 2016 at 10:00 AM, Jim Robinson <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Did you try quoting the track name (it has whitespace)?
> >
> > On 6/30/16 9:28 PM, innamittal wrote:
> > >
> > > Hi,
> > >
> > > expand RefSeq Genes doesn't work in batch file.
> > >
> > > CODE:
> > >
> > > new
> > > genome hg19
> > > load test.bam
> > > snapshotDirectory target/results
> > > goto chr1:248487618-248487658
> > > sort strand
> > > viewaspairs
> > > expand RefSeq Genes
> > > snapshot 17.52241.248487638.png
> > >
> > > Regards,
> > > Inna
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/igvteam/igv/issues/268>, or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AA49HCmpWbPtRonzMnHqmtWucYzySVPjks5qRJeEgaJpZM4JCzxk
> > >.
> > >
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/igvteam/igv/issues/268#issuecomment-229851499>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/ATTH7mWT4YFB7JLJFPw5Q_7mjZ7yIXaYks5qRJffgaJpZM4JCzxk
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/igvteam/igv/issues/268#issuecomment-229875884>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA49HFhKMINWXDF91-hx36b1ruEuOqerks5qRMFPgaJpZM4JCzxk>
> .
>


-- 
Sent from Gmail Mobile
