### ISSUE TITLE
Ctrl+F/R sometimes not working

### ISSUE THREAD

**Issue by holtgrewe** [igvteam/igv#269]
The shortcut of Ctrl+F/R in custom BED tracks is sometimes not working.

How would I go about collecting more information for helping to track down the problem?

**Comment by jrobinso** [comment]
FIrst tell use the version you are using.   Describe the problem, "not working" is not enough, and if possible provide a bed file that exhibits the problem and detailed steps for us to reproduce it.  If we can't reproduce the problem we can't fix it.
