### ISSUE TITLE
Request for interactive sort option of tracks

### ISSUE THREAD

**Issue by AMChalkie** [igvteam/igv#270]

**Comment by jrobinso** [comment]
Could you please elaborate?

**Comment by AMChalkie** [comment]
Sure:
When I add a track (manually), rather than create xml files on the fly, then it ends up at the bottom (I commonly have 10+ bam tracks), and I want to then move that coverage track (or both), up closer to particular samples, and dragging it upwards multiple times is painful (there may be an easier way to do this). An interactive drag/drop or general selector for the order of all tracks would be lovely, rather than sorting specifically by name. A text list for this with track names that could be moved up/down would be sufficient functionality.

**Comment by jrobinso** [comment]
OK.   If you have 10 or more bam tracks have you considered turning off 
the alignment track altogether?  You can always switch it on for 
particular tracks by right-clicking the coverage.

**Comment by AMChalkie** [comment]
Thanks for that tip, certainly helpful. Still think that an interactive track sorting functionality would be a nice addition.
