### ISSUE TITLE
java.lang.NullPointerException error in IGVtools when trying to Find Motif

### ISSUE THREAD

**Issue by naglemi** [igvteam/igv#273]
I am running the latest version of IGVtools and have several .fa files loaded. I am now trying to locate a particular motif in these files. I start with Tools -> Find Motif, enter the sequence, then get this error. How should I go about resolving this? Thanks

INFO [2016-07-06 10:57:15,174] [MessageUtils.java:74] Error loading features for interval: scaffold_4:17206330-24417620 
java.lang.NullPointerException ERROR [2016-07-06 10:57:29,139] [FeatureTrack.java:925] Error loading features for interval: scaffold_4:17206330-24417620 
java.lang.NullPointerException java.lang.NullPointerException at htsjdk.samtools.util.SequenceUtil.reverseComplement(SequenceUtil.java:594) at org.broad.igv.tools.motiffinder.MotifFinderSource.getMatcher(MotifFinderSource.java:116) at org.broad.igv.tools.motiffinder.MotifFinderSource.searchSingleStrand(MotifFinderSource.java:99) at org.broad.igv.tools.motiffinder.MotifFinderSource.search(MotifFinderSource.java:140) at org.broad.igv.tools.motiffinder.MotifFinderSource.getFeatures(MotifFinderSource.java:156) at org.broad.igv.feature.CachingFeatureSource.queryRaw(CachingFeatureSource.java:68) at org.broad.igv.feature.AbstractCacher.loadTiles(AbstractCacher.java:198) at org.broad.igv.feature.AbstractCacher.getBins(AbstractCacher.java:172) at org.broad.igv.feature.AbstractCacher.queryCached(AbstractCacher.java:102) at org.broad.igv.feature.CachingFeatureSource.getFeatures(CachingFeatureSource.java:73) at org.broad.igv.track.FeatureTrack$1.run(FeatureTrack.java:903) at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

**Comment by jrobinso** [comment]
You can't resolve this yourself, its an IGV bug.   What do you mean you 
have "several .fa files loaded"?

**Comment by naglemi** [comment]
I mean I went through Import Genome and loaded 3 different versions of a genome in FASTA format. I'm trying to quickly find a motif that is in some versions of the genome but not others. Is there a workaround or another feature in IGV to accomplish the same task?

**Comment by jrobinso** [comment]
You can only load a single fasta at a time, but I think you know that.   I can't reproduce your problem, is it possible to provide a small fasta and detailed steps to reproduce this error?  If I can reproduce the error I'm sure I can fix it.  

This looks like a task that would accomplished more efficiently via scripting with basic linux commands,  like grep.

**Comment by naglemi** [comment]
I'm unable to reproduce it myself and everything is working great now. I don't know what is different.

**Comment by jrobinso** [comment]
OK, I'll close the ticket.  If it happens again try to capture steps and reopen.
