### ISSUE TITLE
problem entering optional index url for a file in Google Cloud Storage 

### ISSUE THREAD

**Issue by smrgit** [igvteam/igv#274]
I have bam and bai files in GCS that I would like to view using IGV desktop.  If I enter just the bam file url into the **File > Load from URL...** pop-up, it works fine, but if I add the "optional" index url, I get the following error:
```
Error loading https://www.googleapis.com/storage/v1/b/isb-cgc-open/o/ccle%2FBRCA%2FDNA-Seq%2FG15512.HCC1954.5.bam?alt=media: An error occurred while accessing: https://www.googleapis.com/storage/v1/b/isb-cgc-open/o/ccle%2FBRCA%2FDNA-Seq%2FG15512.HCC1954.5.bam?alt=media Error loading BAM file: java.net.MalformedURLException: unknown protocol: gs
```

The files that I am using (should be accessible to anyone) are:
```
bash-4.2$ gsutil ls -l gs://isb-cgc-open/ccle/BRCA/DNA-Seq/G15512.HCC1954.5*
558055062336  2016-03-11T17:42:24Z  gs://isb-cgc-open/ccle/BRCA/DNA-Seq/G15512.HCC1954.5.bam
    10126368  2016-03-11T17:42:24Z  gs://isb-cgc-open/ccle/BRCA/DNA-Seq/G15512.HCC1954.5.bam.bai
TOTAL: 2 objects, 558065188704 bytes (519.74 GiB)
```

**Comment by jrobinso** [comment]
Thanks for the report, I'll look into it.  However, why are you entering the index URL?    And what exactly are you entering, if it differs from the two gs URLs above?

**Comment by smrgit** [comment]
I am entering the .bam url into the upper box and the .bam.bai url into the lower box.  Is it not necessary? will IGV find the index file anyway?  If so, I misunderstood.

**Comment by jrobinso** [comment]
Its only neccessary if the index file is not where its expected to be,  
in your case it looks like it is.  It should still work,  I'll look into 
that,  just not neccessary.  That's why its optional.

**Comment by smrgit** [comment]
Thanks for the clarification, Jim.
