### ISSUE TITLE
Google Genomics - Sample name from readGroupSet id

### ISSUE THREAD

**Issue by lmtani** [igvteam/igv#279]
Hello,

The feature to add tracks from google genomics readGroupSet is very useful, but it can be improved by adding the sample name to the tracks imported (and not just show the ReadGroupSet Id). When working with more than one alignment track it is easy to forget the track names as it shows only the id.

I'm not a java expert or even very familiarized with IGV source code, but the following hack worked to me using the api v1beta2 (I still don't know why, but when using the API v1 the resource is forbidden).
- Add a function to GET from Google Genomics API in the `Ga4ghAPIHelper.java`. The POST method (already used in igv) requires the information of the dataset id, using GET it is not required.

``` java
    public static String getReadName(Ga4ghProvider provider, String readGroupSetId) throws IOException {

        JsonPrimitive pageToken = null;
        StringBuffer result = new StringBuffer();
        String authKey = provider.getApiKey();
        String baseURL = provider.getBaseURL();
        String token = OAuthUtils.getInstance().getAccessToken();

        String fullUrl = baseURL + "/readgroupsets/" + readGroupSetId;
        if (authKey != null) {
            fullUrl += "?key=" + authKey;
        }

        URL url = new URL(fullUrl);

        // Create a URLConnection
        HttpURLConnection connection = null;
        BufferedReader br;
        OutputStream outputStream;

        connection = (HttpURLConnection) url.openConnection();
        connection.setUseCaches(false);
        connection.setDoInput(true);
        connection.setDoOutput(true);
        connection.setRequestMethod("GET");
        connection.setRequestProperty("Content-Type", "application/json");
        connection.setRequestProperty("Cache-Control", "no-cache");
        connection.setRequestProperty("Accept-Encoding", "gzip");
        connection.setRequestProperty("User-Agent", "IGV (gzip)");

        if (token != null) {
            connection.setRequestProperty("Authorization", "Bearer " + token);
        }


        int responseCode = connection.getResponseCode();
        // Read the response
        br = new BufferedReader(new InputStreamReader(new GZIPInputStream(connection.getInputStream())));
        StringBuffer sb = new StringBuffer();
        String str = br.readLine();
        while (str != null) {
            sb.append(str);
            str = br.readLine();
        }
        br.close();

        String readString = sb.toString();

        JsonParser parser = new JsonParser();
        JsonObject obj = parser.parse(readString).getAsJsonObject();
        String name = obj.get("name").toString();

        return  name.replace("\"", "");

    }
```
- Add a step in the file `TrackLoader.java` (in loadAlignmentsTrack) to check if the alignment comes from google. It will raise an exception if loading from the menu "Load from GA4GH", so I put it inside a try/catch.

``` java
            if (typeString.equals(Ga4ghAPIHelper.RESOURCE_TYPE)){
                try {
                    String impersonate = Ga4ghAPIHelper.getReadName(Ga4ghAPIHelper.GA4GH_GOOGLE_PROVIDER, dsName);
                    alignmentTrack.setName(impersonate);
                } catch (Exception e){
                    log.debug("Loading readgroup using datasetID...");
                }
            }
```

Hope it can be useful to someone.

**Comment by jrobinso** [comment]
Hi,  using the "name" property is a good idea, but it can be done more directly (a separate http request should not be needed).   I will look into that.

There was a bug affecting oAuth with release 1.0,  but that has been fixed with 1.0.1.  Also it is fixed in the master branch.

**Comment by jrobinso** [comment]
Also, if you can explicitly set the track name to anything you want, the id is just a default.

**Comment by jrobinso** [comment]
Oops, sorry, I see this is an IGV issue, not igv.js.   I'm immersed in both and even the code looks the basically same.  Comments above apply to igv.js.    The v1Beta google API is not supported and shouldn't be used,  I'll see if I can solve this problem with the v1 API.   Also, I'm going to open a parallel issue in igv.js as using the readgroupsetname,  when it is defined (its not a required field), is a good idea there also.

**Comment by lmtani** [comment]
Thank you @jrobinso. You have already helped with IGV.js.

**Comment by lmtani** [comment]
I think this issue could be closed due to the evolution of IGV and Google Genomics.
