### ISSUE TITLE
load reads from Google Genomics readGroupSet in batch "load" command

### ISSUE THREAD

**Issue by smrgit** [igvteam/igv#282]
is this possible?  if so, what is the syntax for the load command in this case?

**Comment by jrobinso** [comment]
No, this is not possible.

**Comment by jrobinso** [comment]
Working on this now.  If you have a suggested syntax please comment.

**Comment by jrobinso** [comment]
I just pushed a fix for this.  They syntax follows.   The "name" parameter is optional,  if its ommited the readgroupsetid will be the track name.  There is another issue open to use the readgroupset name for the track name.

load CMvnhpKTFhCjz9_25e_lCw format=ga4gh name="ga4gh alignments"

Note: currently this only works for Google (are there any other working endpoints)?
