### ISSUE TITLE
Add a generic "Send read to URL" feature 

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#283]
Issue to track item #9 from #277.   Also see pull request #280.   Synopsis below

Add a generic "Send read to URL" feature that is like the "Blat read sequence" option but supports user-defined URLs. Some data representation (e.g. read v ref dotplot) is difficult to show within IGV but could be built as a separate web application. The user should be able to add new URLs and define which information is sent with a request: read name, read sequence, reference span, reference sequence, and CIGAR string, and others.

@pb-jchin  Splitting this off to track it separately while its refined.

**Comment by jrobinso** [comment]
@pb-jchin -- one question, is there a reason that the endpoint
"/ExamineReadAlignment/"
is hardcoded in the client code?  Any object to moving that to the EXTVIEW_URL property?

**Comment by pb-jchin** [comment]
@jrobinso when I was thinking about it, the question is "whether we need EXTVIEW_URL for both features and reads".  If we want to put both end points in the configuration, we probably need `EXT_READVIEW_URL` and `EXT_FEATUREVIEW_URL`. I think that is OK.  Since I was thinking only adding one more option in configuration, I needed to hardcode some the endpoints in the client code.

**Comment by jrobinso** [comment]
I vote for the EXT_READVIEW_URL, EXT_FEATUREVIEW_URL.    Its probably not worth generalizing this too much right now.   I’ll make that change.

Do you have a publicly available URL to test this feature with?

**Comment by pb-jchin** [comment]
@jrobinso  I think it might be useful to have simple local server for testing.  I can send you a simple python script (using Tornado) for it. Not sure if you want such code in the repository.  With the Tornado framework, the code can be trivially short.

**Comment by pb-jchin** [comment]
hi, @jrobinso, I put a test server code in Python + Tornado here, https://gist.github.com/pb-jchin/aa699f366a03f714dd89e8357893801a
