### ISSUE TITLE
Improve performance for pacbio reads

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#284]
See #277 item 8  for initial discussion, summarized here

@amwenger writes

Improve performance. Rendering PacBio alignments in IGV is often slow, and it is not practical currently to render read information at low zoom. One cause is that PacBio reads have frequent indel errors that break the alignment into many, many CIGAR blocks. Some of the rendering logic is performed per CIGAR block, not per alignment. Thus, rendering PacBio reads is much more expensive than the equivalent coverage in Illumina reads, which are often 1-2 blocks per alignment. For example, 40-fold coverage over 1kb would be something like 40 PacBio reads, each broken into ~100 CIGAR blocks for a total of 4,000 CIGAR blocks; it would require 400 Illumina reads, each broken into ~1 CIGAR block for a total of 400 blocks. So, the estimated cost is 10x higher for PacBio reads when operations are performed per block and not per alignment.

**Comment by jrobinso** [comment]
I've done some profiling with "unmodified" igv.   Results are consistent with profiling done a year or so ago.   For a ~200kb view the most expensive operation,  ~50% of cpu,  is drawing the individual alignment blocks  (GraphicsContext2D.fillRect).    There are many individual blocks,  most too small to be resolved (width < 1 pixel) but they are drawn anyway.   Profile screenshot attached 
![screen shot 2016-07-18 at 2 44 01 pm](https://cloud.githubusercontent.com/assets/933148/16931665/f4cb0fb4-4cf6-11e6-893d-98e1b89b346d.png)

**Comment by amwenger** [comment]
Nice.  Let's see how performance changes as we add other features from #277, particularly 2 (drop small indels at low zoom) and 5 (show variation at low zoom).  I am a beginner at profiling, but I will try my best to quantify the impacts.
