### ISSUE TITLE
problem viewing bed file data

### ISSUE THREAD

**Issue by caroyer** [igvteam/igv#286]
I am new to IGV. Last week I succeeded in loading a genome and then loading .bed files to view ChipSeq results. Today I tried again to open the same .bed files and there is no error message, but nothing is displayed in the track.

**Comment by jrobinso** [comment]
Can you attach a sample .bed file that doesn't display?

**Comment by caroyer** [comment]
Hi
Thanks. I got it to work just a few minutes ago.
It was the wrong genome. Sorry☹
Thanks
Sincerely

Catherine Royer
Professor of Biological Sciences
Professor of Chemistry and Chemical Biology
Constellation Professor - Bio-computation and Bio-informatics
Rensselaer Polytechnic Institute
110 Eighth St. BT3244B
Troy NY 12180-3590
tel: (518) 276-3796
royerc@rpi.edu
http://biotech.rpi.edu/faculty/catherine-royer
