### ISSUE TITLE
Sashimi plot track scale issue

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#287]
From https://groups.google.com/d/msgid/igv-help/d2178341-3569-457a-b1ab-874d3f08f806%40googlegroups.com

I've noticed a change in the way IGV displays the sashimi plots: the track height used to adjust automatically to the number of reads but for whatever reason, now it's always set up at 60. Similarly, some of the settings were maintained as long as I wouldn't restart IGV (for exmaple once I would set up the minimum number of reads to a certain number, that setting would be maintained, regardless of the gene I'm looking at), but again, for whatever reason, I have to set it up every time I look at a different gene.
Is there a way to change the defaults settings for the display of sashimi plots? I've looked in the preferences but couldn't find anything.
I also tried to reinstall IGV several times, but it didn't change anything. The default sashimi plot track height seems to be stuck at 60.

**Comment by gacatag** [comment]
Hello. I also noticed changes with the scaling (min and max of exon coverage) in the latest IGVs , i.e. IGV_2.3.81 and all IGV versions later than 2.3.72. They are always set to min 0 and maximum 60 where as up to version 2.3.72 it was set according to each sample.
I was wondering if you regard or recommend any of the IGV versions, as the stable version?
Cheers.

**Comment by jrobinso** [comment]
This is fixed in 2.3.82
