### ISSUE TITLE
how to snapshot faster in batch

### ISSUE THREAD

**Issue by hchen1103** [igvteam/igv#288]
it takes me about 3 mins to snapshot 3 positions , how can I snapshot faster on my linux system? Looking forward for your reply!

my running step as follows:
java -jar igv.jar -b all_posi.txt    

##the content of all_posi.txt is:
load HD658-Pa.dedup.bam
snapshotDirectory testPNG
maxPanelHeight 10000

goto chr16:23646988-23647088
sort position
sort base
snapshot HD658-Pa_chr16_23647038.png

goto chr9:135771938-135772038
sort position
sort base
snapshot HD658-Pa_chr9_135771988.png

goto chr10:89720599-89720699
sort position
sort base
snapshot HD658-Pa_chr10_89720649.png

exit

**Comment by jrobinso** [comment]
Get a faster computer?  How long does it take to do these operations through the UI?

**Comment by hchen1103** [comment]
it takes 3 mins.
I'd like to ask another question. How can I use the preopened igv port to take snapshot through shell script without relaunching the igv again ?

**Comment by jrobinso** [comment]
I don't understand the question, just write the snapshot command to the port.    How you do that depends on the language you use.

**Comment by hchen1103** [comment]
let me put it in another way, I have noticed that using this module of python( "https://github.com/brentp/bio-playground/blob/master/igv/igv.py") for batch snapshot is faster than using the command line( java -jar igv.jar -b  batch.script.txt), but why? what's the difference?
