### ISSUE TITLE
igv-2.3.79: compile dependencies

### ISSUE THREAD

**Issue by mmokrejs** [igvteam/igv#293]
Hi Jim,
  in the past it was possible to drop oracle.jdbc in issue #149 but it seems it is back now.

  Also, mysql-jdbc is not found on my system, and maybe I have too old jfree version?

```
compile:
    [javac] Compiling 884 source files to /scratch/var/tmp/portage/sci-biology/igv-2.3.79/work/igv-2.3.79/tmp
    [javac] /scratch/var/tmp/portage/sci-biology/igv-2.3.79/work/igv-2.3.79/src/org/broad/igv/variant/VariantTrack.java:31: error: package oracle.jdbc.proxy.annotation does not exist
    [javac] import oracle.jdbc.proxy.annotation.Pre;
    [javac]                                    ^
    [javac] /scratch/var/tmp/portage/sci-biology/igv-2.3.79/work/igv-2.3.79/src/org/broad/igv/tools/sort/BAMSorter.java:29: error: package com.mysql.jdbc does not exist
    [javac] import com.mysql.jdbc.NotImplemented;
    [javac]                      ^
    [javac] /scratch/var/tmp/portage/sci-biology/igv-2.3.79/work/igv-2.3.79/src/org/broad/igv/tools/sort/BAMSorter.java:34: warning: NotImplementedException is internal proprietary API and may be removed in a future release
    [javac] import sun.reflect.generics.reflectiveObjects.NotImplementedException;
    [javac]                                              ^
    [javac] /scratch/var/tmp/portage/sci-biology/igv-2.3.79/work/igv-2.3.79/src/com/iontorrent/views/FlowSignalDistributionPanel.java:222: error: cannot access PublicCloneable
    [javac]                 dataset.addValue(data[j], seriename, cat);
    [javac]                        ^
    [javac]   class file for org.jfree.util.PublicCloneable not found
    [javac] /scratch/var/tmp/portage/sci-biology/igv-2.3.79/work/igv-2.3.79/src/com/iontorrent/views/FlowSignalDistributionPanel.java:266: error: cannot access Drawable
    [javac]             CategoryPlot plot = freechart.getCategoryPlot();
    [javac]                                          ^
    [javac]   class file for org.jfree.ui.Drawable not found
    [javac] /scratch/var/tmp/portage/sci-biology/igv-2.3.79/work/igv-2.3.79/src/org/broad/igv/tools/sort/BAMSorter.java:103: warning: NotImplementedException is internal proprietary API and may be removed in a future release
    [javac]         throw new NotImplementedException();
    [javac]                   ^
```

I have installed these:
dev-java/jdbc-mysql-5.1.26 from http://www.mysql.com/products/connector/j/
dev-java/jfreechart-1.0.14 from http://www.jfree.org/jfreechart

I do not have installed dev-java/jdbc-oracle-bin-10.2.0.4 from http://www.oracle.com/technology/software/tech/java/sqlj_jdbc/

Would you please comment on the required software and versions?

**Comment by jrobinso** [comment]
This should be fixed now, in master and 2.3.80.   Let me know if you have further problems.  I don't understand the question about jfree,etc,  there should be no external dependencies, everything required should be contained in the "lib" repository.

**Comment by mmokrejs** [comment]
Hi Jim,
  thank you. Well I hit some other issue, see the attached file.

[build.txt](https://github.com/igvteam/igv/files/427609/build.txt)

  On a general note, we managed to get a package in Gentoo Linux automagically compiling igv from sources, so we ignore some of the bundled 3rd-party libraries because they have their own packages already. So, my question was whether there are some new dependencies in igv itself (compared to previous versions), or not. Of course, in your eyes you just add a few more lib/.jar file and you are done, but we try to eliminate them all. I had the impression that the error about "org.jfree.util.PublicCloneable not found" is maybe a sign for a new dependency.

  Do you confirm igv now needs jdbc-mysql and jfreechart from the above URLs?

Look at https://gitweb.gentoo.org/proj/sci.git/tree/sci-biology/igv/ .

**Comment by jrobinso** [comment]
Hi

IGV has no dependencies on jdbc-mysql,  where exactly do you find such a 
dependency?  The necessary  jfreechart jar files are included in the 
"lib" folder.    If you are ignoring the 3rd party libraries in the 
"lib" directory its probably not going to work. I cannot give you a 
history of dependencies.

If you are reporting an error in our ant build script please be 
explicit.  I have downloaded and ran our ant build script with no 
compile errors in a clean directory.

Jim

**Comment by mmokrejs** [comment]
I showed the `import com.mysql.jdbc.NotImplemented;` error above and because I do not program in java, I was just guessing whether I have all necessary dependencies. That is why I asked for you insight. It seems from the lib/directory contents I indeed do not need it, and that `mysql-connector-java-3.1.14-bin.jar` is needed instead. Seems there is no such package yet in Gentoo, so we will use your bundled `mysql-connector-java-3.1.14-bin.jar` for the moment.


> If you are ignoring the 3rd party libraries in the "lib" directory its probably not going to work.

I try to delete as most as possible of those bundled jar files for which we already have a separate package. I am sorry this approach is a bit prone to render errors. But, should they manifest during compilation?

The package for 2.3.49 and 2.3.52 worked fine, so that is why I thought there are new dependencies in 2.3.79.

I still get these:

```
compile:
    [javac] Compiling 889 source files to /scratch/var/tmp/portage/sci-biology/igv-2.3.80/work/igv-2.3.80/tmp
    [javac] /scratch/var/tmp/portage/sci-biology/igv-2.3.80/work/igv-2.3.80/src/org/broad/igv/tools/sort/BAMSorter.java:33: warning: NotImplementedException is internal proprietary API and may be removed in a future release
    [javac] import sun.reflect.generics.reflectiveObjects.NotImplementedException;
    [javac]                                              ^
    [javac] /scratch/var/tmp/portage/sci-biology/igv-2.3.80/work/igv-2.3.80/src/com/iontorrent/views/FlowSignalDistributionPanel.java:222: error: cannot access PublicCloneable
    [javac]                 dataset.addValue(data[j], seriename, cat);
    [javac]                        ^
    [javac]   class file for org.jfree.util.PublicCloneable not found
    [javac] /scratch/var/tmp/portage/sci-biology/igv-2.3.80/work/igv-2.3.80/src/com/iontorrent/views/FlowSignalDistributionPanel.java:266: error: cannot access Drawable
    [javac]             CategoryPlot plot = freechart.getCategoryPlot();
    [javac]                                          ^
    [javac]   class file for org.jfree.ui.Drawable not found
    [javac] /scratch/var/tmp/portage/sci-biology/igv-2.3.80/work/igv-2.3.80/src/org/broad/igv/tools/sort/BAMSorter.java:102: warning: NotImplementedException is internal proprietary API and may be removed in a future release
    [javac]         throw new NotImplementedException();
    [javac]                   ^

```

I have jfreechart-1.0.19 installed system-wide. You bundle 1.0.13 version. Is my version too new?

**Comment by jrobinso** [comment]
You really can't substitute the version of the jars in the lib directory 
with other versions.  It might work but is very unlikely, that is why 
you are getting compile errors.    Are you trying to save disk space?

**Comment by mmokrejs** [comment]
Gentoo allows users to compile all packages from scratch. Hardly a few packages provide ready-made binaries. This is the main reason why people use Gentoo Linux: they can get tuned binaries from their favorite compiler for their CPU, they can cross-compile for any other platform, etc. Therefore, the intent is to compile igv from its sources and to ensure the required 3rd-party java stuff is also available on the system by standard means - i.e. also compiled from sources. So, I idealy I would like to delete whole ./lib/ contents but as you may have already seen in the igv-2.3.80.ebuild some jar files are kept because there are just no corresponding packages for them yet. It is not a problem to require a specific version of say htsjdk, provided I know which one is needed. Some of teh ./lib/*.jar file have no version number, so it is not easy to find. Probably unzipping the jar file would give me more info but I have not tried yet. Providing a list of dependencies is quite common.

**Comment by jrobinso** [comment]
There's not much I can help you with here,  the lib folder contains the necessary and sufficient jar files.  If you have those exact jar files somewhere else on your system you can substitute them, if not you should keep them.    We provide many distribution options, including an (almost) single jar option from the downloads page (the "Binary" distribution).   I'm basically the only developer and don't have time to debug build processes other than the script we provide.

**Comment by mmokrejs** [comment]
I understand all of that, but renaming the jar filename to include a version number would be very helpful. Second, I have to guess from their name where is the homepage of the project you compiled into the jar file. Both issue would be solved if there was a list of dependencies.

I also understand you cannot guarantee newer versions are without errors, but I will the version numbers and realize we may have too new version. Yes, I assume especially htsjdk is a trouble as it evolves too quickly.
