### ISSUE TITLE
BigWig: No Coverage Showing for Some Reference Sequences

### ISSUE THREAD

**Issue by nathanhaigh** [igvteam/igv#294]
I have a large genome (Wheat: 14-16Gbp of FASTA) for which I'm trying to display several coverage tracks (BigWig format). In one of the files I have noticed there is no coverage information being displayed for some scaffolds.

My pipeline of BAM -> bedgraph -> BigWig pipeline looks like this. The files we're talking about a prett big:

``` bash
$ export LC_COLLATE=C

$ bedtools genomecov -bg \
          -split \
          -ibam "${my_bam}" \
          | sort -k1,1 -k2,2n -S 10G --parallel 9 \
          > "${my_bedgraph}"

$ bedGraphToBigWig \
          "${my_bedgraph}" \
          "${my_chrom_sizes}" \
          "${my_bigwig}"

$ ls -hl "${my_bedgraph}" "${my_bigwig}"
-rw-rw-r-- 1 user group 47G Aug  1 15:22 my.bedgraph
-rw-rw-r-- 1 user group 20G Aug  1 16:30 my.bw
```

I wondered if my pipeline was failing somewhere and resulting in an incomplete/corrupt bigwig file. However, after some checks I don't think this is the case. I now think it could be IGV related. First, I checked my bedgraph to ensure it contained information for a "problematic" scaffold, and it did:

``` bash
$ fgrep -wc "scaffold${my_id}" "${my_bedgraph}"
121656
```

I checked the BigWig file for this "problematic" scaffold and it contained information for it:

``` bash
$ bigWigInfo -chroms "${my_bigwig}" | fgrep -w "scaffold${my_id}"
        scaffoldNNNNNN 23807 1354720
```

I even extracted the bedgraph info for this scaffold into it's own bedgraph file and converted it to BigWig to see if I can get IGV to display this file with covergage across the "problematic" scaffold. This worked as expected:

``` bash
$ awk -v my_id=${my_id} '$1=="scaffold"my_id' "${my_bedgraph}" > "${my_scaffold_bedgraph}"
$ fgrep -wc "scaffold${my_id}" "${my_scaffold_bedgraph}"
121656
$ bedGraphToBigWig "${my_scaffold_bedgraph}" "${my_chrom_sizes}" "${my_scaffold_bigwig}"
$ bigWigInfo -chroms "${my_scaffold_bigwig}" | fgrep -w "scaffold${my_id}"
        scaffoldNNNNNN 0 1354720
```

So I'm left thinking that my original `${my_bigwig}` file, which containes all the coverage infor for all my scaffolds is simply not being displayed correctly by IGV. Can anyone help to further diagnose this issue and if there might be a fix?

**Comment by jayoung** [comment]
I'm having similar trouble displaying gene annotations from a gtf files. Some scaffolds display fine, others appear to have no genes (even though I find them when I grep the gtf file).   I'm using IGV v2.3.79 on a Mac (looking at files mounted on a shared drive). 

This only started with recent IGV update (not sure which one). I've looked at the same gtf file successfully in the past using older IGV versions without this problem.  Strange.

**Comment by jrobinso** [comment]
I'll need some sample data that reproduces the problem to resolve this.  Can you extract some records  that are not showing up (from the gtf).   Same with the bigwig,  can you extract a few bedgraph records that are not displaying?    This probably won't be enough for me to reproduce the problem, but is a start.

**Comment by jayoung** [comment]
Perhaps I wrote prematurely - sorry about that.  I've figured out my problem:  I think it was actually the index for my gtf file that was a problem.  I had been sorting and indexing the gtf file using a remote linux node (not my mac), and I hadn't realized I was using an older version of igvtools over there (2.3.40).    I realized that, updated my linux igvtools, resorted and reindexed the gtf, and now I see the missing records. 

A diff on the old versus new sorted gtf files show they're identical:  the index files are different, though.

Not sure if that provides any clues to Nathan's problem: maybe something's changed recently about how IGV likes things to be indexed? sorry about the distraction.

**Comment by nathanhaigh** [comment]
As I said @jrobinso, when I extracted the bedgraph records for a region I was having problems with and converted that to a BigWig, IGV loaded that fine. With some other BAM files converted to BigWig I don;t see this problem - unless I'm just not looking at the right scaffolds to see evidence for it!

**Comment by nathanhaigh** [comment]
Just an update on my system:

OS: Ubuntu 14.04
[BEDTools](https://github.com/arq5x/bedtools2/): 2.25.0
[kentUtils](http://hgdownload.cse.ucsc.edu/admin/exe/): 334
[IGV](http://www.broadinstitute.org/igv/projects/current/igv_hm.jnlp?initialHeapSize=4g&maxHeapSize=8g): 2.3.79 (118) via Java WebStart

**Comment by jrobinso** [comment]
@nathanhaigh  Can you create a small bigwig using the original command that reproduces the problem?   I'm a bit stumped as to how I can reproduce this here.

**Comment by jrobinso** [comment]
@nathanhaigh --  How many scaffolds are in this fasta?  I wonder if the size of the index is a problem for IGV.   Here's an experiment that might help.   Extract the records for the problematic scaffold from the original bedgraph,  then put them in the front of the file.   Remake the bigwig and see if the same scaffold has a problem.   This will rearrange the order of nodes in the index.      

Also, is there anything interesting in the igv.log file?  (found in <user home>/igv/igv.log.

Finally, if you are able to place the fasta and bigwig on an http server I can access I can run these here and debug it myself.

**Comment by nathanhaigh** [comment]
@jrobinso The FASTA file has XX scaffolds.

Unfortunately, `bedGraphToBigWig` requires a case-sensitive sorted bedgraph file as input. Failing to provide this results in a warning like: `Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C, or bedSort and try again.` I'll see if there is anything in the logs.

I currently can't release the FASTA file :( But I could release the BigWig. I wonder if I created a mock FASTA file and substitute all bases for 'Ns' if that would obfuscate things sufficiently and still cause this issue. After all, the BigWif is just x/y coordinates.

As a workaround I've converted all my bedgraph files to IGV's `tdf` format. However, I still need BigWigs for other purposes and don't want to double-up on file formats unless I really have to! :)

**Comment by jrobinso** [comment]
Replacing the fasta sequence with Ns would work fine for viewing bigwigs.
