### ISSUE TITLE
Fasta file fails to load when stored at read-only location

### ISSUE THREAD

**Issue by rmzelle** [igvteam/igv#297]
I'm using HTML links to make Fasta and GFF files available to my colleagues, such as `http://localhost:60151/load?genome=n:\path\file.fasta&file=n:\path\file.gff`.

However, users are seeing errors with IGV 2.3.77 when the fasta files are not accompanied by a .fai index file, because the network drive location is read-only for the users, and IGV tries and fails to write this .fai file. Is there a solution to this, other than to pregenerate all the .fai index files? Since they're so small, could IGV perhaps just keep them in memory instead of writing them to disk (at least when it can't write out the file)?

The error output is:

```
INFO [2016-08-04 13:18:40,625]  [CommandListener.java:167] [Thread-6]  GET /load?genome=c:\path\file.fa&file=c:\path\file.gff HTTP/1.1
INFO [2016-08-04 13:18:41,000]  [GenomeManager.java:145] [Thread-6]  Loading genome: c:\path\file.fa
INFO [2016-08-04 13:18:41,000]  [FastaUtils.java:65] [Thread-6]  Creating indexfile at c:\path\file.fa.fai
ERROR [2016-08-04 13:18:41,000]  [IGV.java:659] [Thread-6]  Error loading genome file: c:\path\file.fa
java.io.FileNotFoundException: c:\path\file.fa.fai (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at org.broad.igv.feature.genome.FastaUtils.createIndexFile(FastaUtils.java:67)
        at org.broad.igv.feature.genome.GenomeManager.loadFastaFile(GenomeManager.java:290)
        at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:167)
        at org.broad.igv.ui.IGV.loadGenome(IGV.java:686)
        at org.broad.igv.ui.IGV.loadGenome(IGV.java:667)
        at org.broad.igv.ui.IGV.loadGenomeById(IGV.java:657)
        at org.broad.igv.batch.CommandListener.processGet(CommandListener.java:330)
        at org.broad.igv.batch.CommandListener.processClientSession(CommandListener.java:201)
        at org.broad.igv.batch.CommandListener.run(CommandListener.java:111)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by jrobinso** [comment]
They best solution is to just create the index files once for everyone and store it with the fasta.   Is there a reason you don't do this?

**Comment by rmzelle** [comment]
Our other software tools don't need the .fai files, so I never bothered to generate them. It's just a little inconvenient. Looks like I can use samtools on Linux/Mac to generate the .fai file (`samtools faidx <ref.fasta>`), or just load the Fasta file in IGV where I have write access.

Could IGV perhaps pop up an error dialog? It currently fails silently (apart from the error output in the console).

**Comment by jrobinso** [comment]
I will add an error popup.  You can create it with samtools,  or igvtools, or as you've discovered by loading it.

**Comment by rmzelle** [comment]
Thanks.

**Comment by rmzelle** [comment]
igvtools doesn't support wildcards, multiple files, or recursive directory searching for the Input File, right? It would be nice if I could e.g. use "n:\path\*.fasta". (we're mostly a Windows shop, so there are some advantages to being able to use igvtools for this)

While reading up on igvtools at http://software.broadinstitute.org/software/igv/igvtools_gui, I also noticed some of the image links are broken (e.g. `src="/igv/sites/cancerinformatics.org.igv/files/images/igvtools_gui_count.jpg"` needs to be `src="/software/igv/sites/cancerinformatics.org.igv/files/images/igvtools_gui_count.jpg"`).

**Comment by jrobinso** [comment]
igvtools doesn't support those things, you are correct,  I don't know what sort of batch scripting windows has but this is easy to add with a wrapper.   

There are multiple problems with the broad website right now, they are being addressed.   In the meantime you might have better luck with http://www.broadinstitute.org/software/igv/igvtools_gui  (note the leading "www." vs "software."

**Comment by rmzelle** [comment]
Okay. Thanks again.
