### ISSUE TITLE
hg38 dbSNP

### ISSUE THREAD

**Issue by sjackman** [igvteam/igv#299]
When I select genome `Human (hg38)` and `File`, `Load from Server…`, I see:

![screenshot 2016-08-08 16 39 35](https://cloud.githubusercontent.com/assets/291551/17500067/04ddff10-5d87-11e6-8de6-4986a13156c0.png)

I selected `All Snps 1.4.2`, and the GUI stopped responding. I think perhaps it's downloading this 2.7 GB file from http://data.broadinstitute.org/igvdata/annotations/hg38/snp142.snp.gz

You mention `common snps` in this post https://groups.google.com/forum/#!topic/igv-help/-jSZROeTy7E
> dbSnp 1.4.2  - all snps
dbSnpt 1.4.2 - common snps
conservation
repeat masker

Is there a smaller version of dbSNP that I can download using the IGV GUI?

With the `Human (hg19)` genome, I select `Load from server`, `Annotations`, `Variation and Repeat` and select `dbSNP 1.3.7` and it loads in a few seconds. Is there a similar track for `hg38`?

**Comment by sjackman** [comment]
This file of common SNPs is smaller at ~1 GB, but it still takes a few minutes to load. How did `hg19` load dbSNP 1.3.7 so quickly?

ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/00-common_all.vcf.gz

**Comment by jrobinso** [comment]
Hi,

The file should be indexed,  hg19 dbSnp is a bed file and indexed with 
tabix.   The hg38 file is not,  I'm not sure how this ever worked.   I'm 
going to remove it from the menu until I can figure it out.

In general loading snps as tabix indexed VCF or bed files is recommended.

**Comment by sjackman** [comment]
Hi, Jim. Thanks for the workaround. That's what I'll do.

This file is indexed with tabix:

ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/00-common_all.vcf.gz
ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/00-common_all.vcf.gz.tbi

ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/00-All.vcf.gz
ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/00-All.vcf.gz.tbi

**Comment by jrobinso** [comment]
That should work, but if possible download them or put them on an http 
server.  The ftp performance is not always good, sometimes freezes,  and 
its a total hack.

**Comment by sjackman** [comment]
Thanks for the suggestion, Jim. I hope there's already a http source for these files out there on the Internet somewhere. I'll see what I can find.

**Comment by jrobinso** [comment]
If you can describe, in words, what those files are I'll download and add them to the menu.

**Comment by jrobinso** [comment]
Also, if you do find an http source let me know.   I checked the 1KG Amazon S3 buckets.

**Comment by sjackman** [comment]
See http://www.ncbi.nlm.nih.gov/variation/docs/human_variation_vcf/

dbSNP Build142 (October, 2014 release)

`00-All.vcf.gz`: All human SNPs
`00-common_all.vcf.gz`: Common human SNPs (minor allele frequency >= 0.01 in at least one of 26 major populations, with at least two unrelated individuals having the minor allele)

**Comment by jrobinso** [comment]
OK, they are now in the menu

**Comment by sjackman** [comment]
Works like a charm. Thanks, Jim!

**Comment by duartemolha** [comment]
Hi...

Looking at the common Snps 142 loaded from server. It seems to me that the allel frequence is always -1

is this a bug?
