### ISSUE TITLE
Scaling and External Ports with Java

### ISSUE THREAD

**Issue by justinthezhu** [igvteam/igv#303]
Dear Broad Institute,
 Hello, my name is Justin.  I am asking as to whether the Integrative
 Genomics Viewer (IGV) is able to automatically set the data range of
 the BAM coverage to be the same for multiple BAM files within one IGV
 session.  Specifically, is there a command that can allow me to
 automatically scale and set the data range to be consistent for
 multiple BAM files?

 Secondly, my question arises as to whether I can save an IGV session
 from an external port.  I am currently running Java from Eclipse right
 now, and I am wondering if you offer specific functions or commands on
 the IGV such as setting the data range constant and saving an IGV
 session that can be used in addition to just taking photos as
 mentioned in here: https://www.broadinstitute.org/igv/PortCommands

 And finally, I was wondering how I can access the methods and commands
 inside IGVtools in reading in the recounts and variants from the
 textbox display in the IGVtools GUI.  Is there an open source code for
 the GUI?  If not, is there a method I can call within the jar file
 that can extract the recounts and variants information?

Thank you so much!

**Comment by jrobinso** [comment]
Hi,  to answer your last question first,  you are posting to the open source git project for IGV.

Second,  I've already addressed your questions in the help forum.  I'll paste the answer here:  

The answer to your questions in order are mostly no, with the exception of the preference question.   They key for that property is SAM.ALLELE_THRESHOLD.   The best way to discover keys is to change the preference in the UI, exit IGV, then look at prefs.properties in the igv folder.

Please enter issues for your other requests at our git repository, a separate issue for each request, at  github.com.igvteam.igv/issues.   Bear in mind that many requests compete for my time and port command enhancement is not currently a priority.   As you are also a developer I encourage you to submit pull requests,  I do review them and accept many.
