### ISSUE TITLE
IGV fails cryptically when the .fa.fai file does not agree with the .fa file 

### ISSUE THREAD

**Issue by sjackman** [igvteam/igv#307]
I create a .fa file `genome.fa`. I start IGV with `igv -g genome.fa`. It automatically creates a .fa.fai file. I quit IGV. I modify the FASTA file `genome.fa`. I restart IGV with `igv -g genome.fa`. The displayed genome sequence is now incorrect.

Could IGV somehow check the consistency of the .fa.fai file? It could for example that
- the time stamp of the .fa is older than the .fa.fai file
- the number of bytes that the .fa.fai file say should be in the .fa file agrees with the number of bytes in the .fa file.

Steps to reproduce the issue:

``` sh
curl -LO http://hgdownload.cse.ucsc.edu/goldenpath/hg38/chromosomes/chrM.fa.gz  
gunzip chrM.fa.gz
bwa mem chrM.fa chrM.fa |samtools sort -o chrM.bam
samtools index chrM.bam
igv -g chrM.fa chrM.bam
# quit IGV
mv chrM.fa chrM.orig.fa
seqtk seq chrM.orig.fa >chrM.fa # Remove the line breaks from the FASTA file
igv -g chrM.fa chrM.bam
```

Zoom in on the alignment and it's not correct.

**Comment by jrobinso** [comment]
Timestamps are not reliable, and the total # of bytes is not reliably available for remote files.   For local files this could be checked.   I prefer the second solution to the timestamp suggestion.   Could you possibly submit a pull request,  or post the math required to compute the # of bytes expected from the  .fai file?   This is not going to be a high priority given other items on my plate so a pull request will be the quickest route.

**Comment by sjackman** [comment]
Hi, Jim. The math should be `$3 + ceil($2/$4*$5)`. I haven't been able to check that this formula is 100% perfect. It's the right idea though. I probably won't get around to submitting a PR myself real soon. 😬 I understand if it's not a high priority for you. Thanks for responding.

```
❯❯❯ wc -c organelles.fa
6118973 organelles.fa
❯❯❯ tail -n1 organelles.fa.fai |awk '{print $3 + $2/$4*$5}'
6118973
```

**Comment by jrobinso** [comment]
I don't think that would work in general,  the last line for each contig
can be any length, you can't know how long it is from the .fai file.

The theses is that fasta files are very stable.   In your particular case
maybe they are not.   What could be done is a preference to not store the
computed .fai file,  i.e. recompute it every time.

**Comment by sjackman** [comment]
> I don't think that would work in general,  the last line for each contig
can be any length, you can't know how long it is from the .fai file.

I believe it does work in general. The position of the last sequence in the file `$3` plus the number of complete lines in the last sequence `floor($2 / $4)` times the number of bytes per line `$5` plus the number of characters on the last line `$2 % $4` plus one more line ending `$5 - $4` is the number of bytes in the file.

**Comment by jrobinso** [comment]
OK, my mistake, I see what you're doing now.  You are assuming the index is
sorted by column 3,  its not always, but that could be accounted for.

**Comment by sjackman** [comment]
Whoah. I thought the .fai file was always sorted by column 3. Will `samtools faidx` sort it by other columns, or is it other tools that do that?
