### ISSUE TITLE
Color by interpulse distance

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#308]
From issue #277 

Color basepairs based on interpulse distances, which indicate methylation status. The interpulse distance is provided in the "ip" SAM annotation. Instead of the standard "gray" background color, this would show a different shade at each basepair as a function of IPD.

@amwenger -- care to comment on color scale?  One base color with varying intensity (like a heatmap),  or some distinct thresholded values?   Fixed scale?  What range?

**Comment by amwenger** [comment]
One idea is to define a general-purpose solution that applies beyond IPD by adding a feature to color basepairs by any tag.  The basics would be:

* The tag would be required to be of type `B` (i.e. array of numbers).
* The length of the array would be required to match the read length (i.e. including clipped basepairs).
* The array entries would be in read native orientation (i.e. not complemented if the alignment is to the negative strand).  That way aligners do not need to know how to interpret them and cause just pass them through.
* The user would specify a color in which to show the values.
* The user would specify a range (min and max value) over which to show the values from the tag.  Bases with a value below the minimum would be colored as usual, bases with a value between min and max would have an intermediate intensity of the specified color, and bases with a value above the max would have full intensity of the specified color.  That makes it possible for people to implement either "heatmap" or "threshold" approaches.

IPD values are dependent on basepair context and methylation status.  So, even for IPD I would probably run an algorithm to adjust the `ip` values based on context to something that is more indicative of methylation status.

**Comment by rrazaghi** [comment]
Following up on this as I think this is now a feature that would be widely used with both PacBio and Nanopore reads. Currently we use a lazy hack with the IGV bisulfite mode to color code methylated/unmethylated bases at the read level. I was wondering if this can be implemented?

Thanks,
Roham

**Comment by rrazaghi** [comment]
I'll open a new issue

**Comment by jrobinso** [comment]
@rrazaghi  Yes but I want to do this once, so we need consensus with @amwenger if you want something other than what's described above.  I'll need some sample data to work with as well.

**Comment by rrazaghi** [comment]
I think what @amwenger has described above is brilliant. I can def get you some sample data to work with (this weekend). Any idea on the name for the tag?

**Comment by jrobinso** [comment]
@rrazaghi @amwenger I don't think we need a specific name for the tag as it can be entered by the user.   Just try to avoid already reserved tags or tags in common usage for another purpose.

**Comment by amwenger** [comment]
Great!  For PacBio, what we discussed earlier still makes sense with "[ip](
https://pacbiofileformats.readthedocs.io/en/5.1/BAM.html#use-of-read-tags-for-per-read-base-information)" as the tag that most people would use.  I am aligning some sample data now and will add it to this issue when available.

**Comment by jrobinso** [comment]
@amwenger Is the sample data available yet?

**Comment by rrazaghi** [comment]
Sorry for the delay! I have a sample bam that we prepared from nanopore reads with methylated C calls. We have two tags here:
The ip tag includes a list of log-likelihood ratios for methylation calls for cytosine. 
The XM tag includes the calls based on the ratios above and the following criteria. We usually define anything below -2.5 unmethylated, greater than 2.5 methylated and anything in between uncalled. 
I think it would be nice if users can have the option of looking at these quantified methylation calls with different intensity colors (using the ip tag here) or if already making definitive calls, have a 2/3 color scheme like the bisulfite mode (XM tag).

Link to the bam: https://www.dropbox.com/sh/w8cbtj63ijrejug/AAAj8v9tF4mPPLho_lOeu9mSa?dl=0

Happy to modify or provide more samples to make this easier on your end.
Let me know!

**Comment by amwenger** [comment]
Sorry, @jrobinso.  I lost track of this but will reply with an update tomorrow.

**Comment by amwenger** [comment]
@jrobinso - Thank you for working on this feature.

A PacBio epigenetic dataset for E. coli K12 (NC_000913.3 reference), which has methylation of A basepairs in GATC motifs is available at:
* BAM: https://dl.dnanex.us/F/D/6Zqx89bB26345GV29y33yp6V88VQbJxx20z52j66/ecoliK12-NC_000913.m54316_180808_005743.ap.bam
* BAM.BAI: https://dl.dnanex.us/F/D/z1yqVK8XQ9kbBxQF1jb38kQq3vzZ3506y4Fy3pQx/ecoliK12-NC_000913.m54316_180808_005743.ap.bam.bai
* GATC motifs BED.gz: https://dl.dnanex.us/F/D/Zf9jFz314zvJfQx2xQYK2kY9gBvJJ1jjgYxPk9XV/ecoliK12-NC_000913.GATC.bed.gz
* BED.gz.tbi: https://dl.dnanex.us/F/D/3PQ0yqj0KjbX1KXXpZK20VV4637Pk7gGky72xFBX/ecoliK12-NC_000913.GATC.bed.gz.tbi

The dataset includes 397 reads (19 MB) spanning `NC_000913:2,220,085-2,254,320`.

The signature of methylation observed by the PacBio DNA sequencer is the interpulse distance (camera frames between base incorporation pulses), which is stored in the `ip` tag in the unaligned BAM output by the PacBio sequencing instrument.  By the [PacBio BAM specification](https://pacbiofileformats.readthedocs.io/en/5.1/BAM.html#use-of-read-tags-for-per-read-base-information), the `ip` tag must be passed through by read mappers like `pbmm2`.  In other words, the `ip` in a BAM alignment is identical to `ip` in the native read from the sequencer, even if the alignment has hard clipping or is to the reverse strand of the reference genome.  For the sample dataset, I also provide an `ap` tag that is a clipped and reference-oriented version of the `ip` tag (i.e. it behaves like the QUAL string).  Do you prefer an `ip`-style or `ap`-style tag for IGV?

As a hack to demonstrate the epigenetic signature, I stored a scaled version of the `ip` values, which range from 0-255, in the alignment QUAL string and used IGV's existing "Shade mismatched bases by quality" feature with min and max both set to 37 to highlight basepairs with high `ip` values: 

**One GATC motif at `NC_000913:2,245,049-2,245,088`**
![GATC-example](https://user-images.githubusercontent.com/7155109/69125576-f27f8800-0a5a-11ea-9ab3-86a8990ba70c.png)

**Multiple modified basepairs at `NC_000913:2,244,379-2,244,887`** 
![zoomout](https://user-images.githubusercontent.com/7155109/69125579-f4494b80-0a5a-11ea-95e7-98580e58370c.png)

**Comment by amwenger** [comment]
@rrazaghi - It would be nice if we could represent the epigenetic signals more similarly to simplify the implementation for @jrobinso.

In my dataset, the `ip` tag is an array of uint8t (`ip:B:C`) and the length of the array matches the length of the SEQ.  In yours, the `ip` tag looks like an array of floats but is stored as a string (`ip:Z`).  Splitting your array on the comma delimiter, the number of entries matches the length of the alignment in reference coordinates, not the length of SEQ.  For example, your first alignment has a 14,311 bp SEQ but 14,596 entries in its `ip` tag.

My opinion (which I followed in my test dataset) is:
* It is fine to use either integers or floats
* It is better to use an array type instead of a string type for the tag.
* The tag should have one entry per read basepair not per reference position.

**Comment by rrazaghi** [comment]
Hi All, 
Just checking in on this to see if there's an update.

Thanks!

**Comment by jrobinso** [comment]
No,  I could use some help on this.     It affects a rather specialized subset of our user base generally,  so its hard to prioritize it over other pressing items in IGV and igv.js that affect many more people.

**Comment by jrobinso** [comment]
Hi all, reviewing old issues.  Apologies I never got to this, but how is it impacted (if at all) by the "MM" and "ML" tags, which are are a proposed standard for indicating base modifications?

**Comment by rrazaghi** [comment]
Hi Jim,

No worries! I have been following the discussion of MM and ML tags. I can see that there is a conversation about how to best implement this and if it is appropriate for downstream analysis (especially swapping the SEQ from the reference ). 
This should be fine for our uses as we mainly use this for visualization and fast access to single-read methylation data (for clustering reads based on methylation status).

I'm going to test the latest snapshot you have and hopefully, I can provide useful feedback there!

Thanks,
Roham

**Comment by amwenger** [comment]
> @jrobinso  Hi all, reviewing old issues. Apologies I never got to this, but how is it impacted (if at all) by the "MM" and "ML" tags, which are are a proposed standard for indicating base modifications?

The MM/ML implementation in IGV 2.10 is very nice, and addresses this request.  I think this issue can be closed now.

**Comment by jrobinso** [comment]
In addition to MM/ML tags, see PR #1270
