### ISSUE TITLE
"OK" and "Cancel" buttons obscured in Alignment Preferences

### ISSUE THREAD

**Issue by amwenger** [igvteam/igv#313]
The alignment preferences window is quite high, and it overflows the available vertical space on smaller screens.  When this happens, the "OK" and "Cancel" buttons are not reachable and preferences can not be set.

<img width="806" alt="screen shot 2016-09-01 at 3 04 37 pm" src="https://cloud.githubusercontent.com/assets/7155109/18186133/e7a8fe0e-7055-11e6-9703-629c07a0f375.png">

It would be nice if the height of the window were fixed and a scrollbar would appear when needed.  There also could be a reorganization/simplification of the preferences.  I can lend my opinion and perhaps help with the implementation if you decide on that path.

**Comment by jrobinso** [comment]
That window is a beast.    I will look into a scrollbar as a quick fix.   I'm also considering going for something radically simpler,  ugly but easy to maintain,  almost like a text editor for the raw file.

**Comment by deannachurch** [comment]
Is there another way to set preferences (like a config file) while this is being fixed? This is making IGV unusable on my laptop.

**Comment by jrobinso** [comment]
Hi Deanna,

Yes you can edit prefs.properties in your igv folder.   If you can give me
a list of preferences you want to set I'll look up the key names and
allowed values.   I will try to push out a fix for this soon.

**Comment by deannachurch** [comment]
Hi Jim,
I'm most concerned about only showing reads with MAPQ 30 or greater. 
Thanks for the fast reply.

**Comment by jrobinso** [comment]
Adding the following line to the "prefs.properties" file should do the
trick.  Edit the file with igv shutdown, to prevent the change being
overwritten when igv quits

SAM.QUALITY_THRESHOLD=30

BTW in the next major release the preferences editor will be uglier,  but
easier to maintain,  basically a flat table style editor for all the
preferences.   The current code had grown into a monster consuming vast
chunks of developer time out of proportion to its usefulness.
