### ISSUE TITLE
igv for comparative genomics

### ISSUE THREAD

**Issue by wangmeijiao** [igvteam/igv#314]
Dear igv team,  thanks for such wonderful visualization tools for the genomics and epigenomics field. I am writing to suggest a modified version for the comparative genomics purpose. To my knowledge,  this will be easy for your smart guys, by copy and paste then adjust some java code? Correct me if I am wrong. Please do reply if this is possible. And if it is too  trivial for you, please guide me with items in your code files and perhaps I can learn and have a try by myself.

**Comment by jrobinso** [comment]
Hi, please open separate tickets for each issue or request,  and be as specific as you can.    

WRT bgzip files this is not correct, IGV supports tabix indexed files.   The extension of the bgzipped file should be .gz,  and the tabix index .gz.tbi.    If you are having an issue please first insure you are using the latest version of IGV, and if so open a new ticket with an example bgzipped file and index file that reproduces the problem.

This is not the right place to ask how to program in Java,  please see a more general programming forum.

**Comment by wangmeijiao** [comment]
Oh sorry I am a newbie to github. Sure I will reorganize my description and support some test files. (And sure I will double check my problem)
