### ISSUE TITLE
Unable to access jarfile igv.jar

### ISSUE THREAD

**Issue by xogur** [igvteam/igv#315]
Hi,

I run "java -Xmx750m -jar igv.jar" but I got an error such as "Unable to access jarfile igv.jar". What is the path of the 'igv.jar'? igv.sh and igv.command are not working as well. Thanks!

**Comment by helgathorv** [comment]
If you downloaded the binary distribution from the IGV Downloads page, it will have created a subdirectory named IGV_<version#> (eg IGV_2.3.81) in the directory where your browser downloads go. The igv.jar file should be there, along with the igv.sh and the other files in the distribution. If you don't see the following files then something went wrong with the download.

IGV_2.3.81/batik-codec__V1.7.jar
IGV_2.3.81/goby-io-igv__V1.0.jar
IGV_2.3.81/igv.bat
IGV_2.3.81/igv.command
IGV_2.3.81/igv.jar
IGV_2.3.81/igv.sh
IGV_2.3.81/readme.txt

**Comment by balasink** [comment]
I still have this issue, there is igv.sh and igv.command but no igv.jar after a fresh install using git clone https://github.com/igvteam/igv.git

**Comment by jrobinso** [comment]
Did you read the readme?  If you just want a runnable distribution download
from http://software.broadinstitute.org/software/igv/download
