### ISSUE TITLE
IGV Server not loading data from tracks where the index file has a distinct URL

### ISSUE THREAD

**Issue by drmjc** [igvteam/igv#317]
Hi,

I've noticed some unexpected behaviour where IGV isn't loading reads or variants from a custom IGV server, but is loading them fine from URL. There seems to be two errors: for an XML with one BAM and one VCF.gz:
1. the bam tracks are added, but no data is shown when zooming in, and
2. the vcf.gz isn't loaded at all.

![image](https://cloud.githubusercontent.com/assets/591923/18655446/38e05e86-7f2c-11e6-895c-ad1281a83803.png)

We use DNAnexus, which for the purposes of accessing data in IGV standalone, you need to generate a secure URL for both the BAM, and BAI file. i.e. BAI url is not just BAM url+”.bai”. I’ve made some scripts to generate an XML representation of a DNAnexus project, creating secure download URLs, and a registry to point to these xml files. I've attached one of these XML files: 
[test igserver public data.xml.zip](https://github.com/igvteam/igv/files/481518/test.igserver.public.data.xml.zip)
These download links are valid for one month from today.

I’m getting two different error modes when using three different versions of IGV:

1) IGV Snapshot last night

> `        Error encountered querying alignments: htsjdk.samtools.util.RuntimeIOException: Invalid file header in BAM index https://dl.dnanex.us/F/D/Q4V427fk05j8yj6B5PgVK403xv4Kbv505zGPV0zy/NA12878-Vial1.dedup.realigned.recalibrated.bam.bai: �  
`

(yes with the � char at the end)    

2) IGV 2.3.81 or IGV 2.3.55
File > Load from Server
This loads only the BAM file track, and when you zoom in to an exon, there’s no reads displayed. The coverage depth drops from default of [0,60] to [0,10] and no reads are shown.

Debugging
* I've compared the format of this to the publicly available xml, and it doesn't look like an XML formatting issue, but perhaps relates to the fact that the index URL is distinct from the BAM or VCF.gz url.
* wget shows that the URLs are both valid and publicly accessible
* Thanks to your recent changes (prompted by DNAnexus I believe), we can load from URL, specifying both the BAM and BAI URL. IGV 2.3.81 loads both the BAM and vcf.gz file using the URLs as above.
* tried different combiunations of nested and un-nested Category nodes

Any thoughts are most welcome.

cheers,
Mark

excerpt from igv.log for 2.3.81 when Load from Server

> INFO [2016-09-20 09:13:13,258] [Main.java:133]  Startup  IGV Version 2.3.81 (127)08/30/2016 02:20 PM
> INFO [2016-09-20 09:13:13,258] [Main.java:134]  Java 1.8.0_101
> INFO [2016-09-20 09:13:13,258] [DirectoryManager.java:72]  Fetching user directory... 
> INFO [2016-09-20 09:13:13,693] [Main.java:135]  Default User Directory: /Users/marcow
> INFO [2016-09-20 09:13:13,694] [Main.java:136]  OS: Mac OS X
> INFO [2016-09-20 09:13:18,969] [GenomeManager.java:145]  Loading genome: /Users/marcow/igv/genomes/1kg_v37.genome
> INFO [2016-09-20 09:13:22,191] [GenomeManager.java:192]  Genome loaded.  id= 1kg_v37
> INFO [2016-09-20 09:13:22,249] [CommandListener.java:106]  Listening on port 60151
> INFO [2016-09-20 09:13:29,368] [IGV.java:1700]  Loading 2 resources.
> INFO [2016-09-20 09:13:29,369] [TrackLoader.java:120]  Loading resource, path https://dl.dnanex.us/F/D/Q4V427fk05j8yj6B5PgVK403xv4Kbv505zGPV0zy/NA12878-Vial1.dedup.realigned.recalibrated.bam
> INFO [2016-09-20 09:13:36,006] [HttpUtils.java:832]  Range-byte request succeeded
> INFO [2016-09-20 09:13:38,036] [TrackLoader.java:120]  Loading resource, path https://dl.dnanex.us/F/D/21kV32x5z1Bk5FYfpXbbb1JbgXFbqBpZ9FBxjyx7/NA12878-Vial1.hc.vqsr.vcf.gz
> INFO [2016-09-20 09:13:48,709] [HttpUtils.java:832]  Range-byte request succeeded
> INFO [2016-09-20 09:14:04,010] [ShutdownThread.java:51]  Shutting down
> INFO [2016-09-20 09:14:04,016] [ShutdownThread.java:51]  Shutting down
> ERROR [2016-09-20 09:14:04,018] [DefaultExceptionHandler.java:49]  Unhandled exception
> java.lang.NullPointerException
> 	at org.broad.igv.sam.AlignmentTrack.dispose(AlignmentTrack.java:1029)
> 	at org.broad.igv.ui.ShutdownThread.runS(ShutdownThread.java:57)
> 	at org.broad.igv.ui.ShutdownThread.run(ShutdownThread.java:64)
>

**Comment by jrobinso** [comment]
This should be fixed now.   Set properties coverage (for bams) and mapping (for vcf) to "." to indicate that the files do not exist.  See attached example.
[test_server.xml.zip](https://github.com/igvteam/igv/files/514459/test_server.xml.zip)

**Comment by jrobinso** [comment]
Fix will be included in 2.3.83, no later than the end of the month,  and also in the nightly snapshot

**Comment by drmjc** [comment]
excellent, thank you @jrobinso !
