### ISSUE TITLE
http /goto should support change-of-genome

### ISSUE THREAD

**Issue by jblachly** [igvteam/igv#318]
I appreciate the port and HTTP control of IGV.

As we have many projects in both hg19 and GRCh38, one way to enhance this would be to support a single HTTP request that could load the appropriate genome and go to a specific locus.

Presently:
1. the `/load` command can do this, but only when also loading files. `/load?genome=xxx&locus=yyy` will load a genome, but will abort without performing the goto if no file is specified.
1. the `/goto` command will go to a locus, but ignore a genome= parameter (or any param other than `locus`.

FIX: _I don't do java development so unfortunately I cannot offer a pull request (apologies)_

Add the following:

```
String genome = params.get("genome");
<some kind of if genome != "" stringcmp> {
    IGV.getInstance().loadGenomeById(genome);
}
```

in the `else if` block at
https://github.com/igvteam/igv/blob/master/src/org/broad/igv/batch/CommandListener.java#L354

The added lines should of course appear before

```
    String locus = params.get("locus");
    IGV.getInstance().goToLocus(locus);
```

Overall this patch should not alter existing functionality, only add the chance to load a new genome before seeking to a locus.

**Comment by routbort** [comment]
Loading a new genome resets the session (unloading all data and annotation tracks), which would make a subsequent seek to a particular locus quite unenlightening.  

Not sure if you are using `/load` to point to data files or using a session XML file, but either way if you want to switch genomes, this is the approach to use (I believe)

**Comment by jblachly** [comment]
That's a good point. I will look into session files.

That being said, I would still support this feature (&genome=) being added as it should not disrupt existing functionality.
