### ISSUE TITLE
Predictive Search Ignores Genes in User-Added Tracks

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv#323]
If I add an annotation track like GENCODE Genes with the GFF3 file, the few gene symbols which are unique to GENCODE can't be found using the search feature, when searching by gene symbol. It seems like IGV only takes gene symbols from the default RefSeq track.

**Comment by jrobinso** [comment]
It uses all non-indexed loaded annotation tracks.  Can you provide a
specific example.

**Comment by DarioS** [comment]
Oh, *non-indexed*. When I try to load GENCODE 25 without an index, I get an error that files of that size must be indexed. Can you make gene symbol lookup work for large, indexed files, such as GENCODE Genes?

**Comment by jrobinso** [comment]
No, how would that work?   It can't know the location of a feature it
hasn't loaded.   Your best option here is to try to grep out the feature
types of interest,  e.g. "Gene",  then load that file for search purposes.
GFF files are incredibly bloated.   Its probably easiest to start with the
genocde gtf for this purpose.

**Comment by jrobinso** [comment]
Here's an example for gencode v24.  The attached file has all gene records and can be loaded into igv without an index.  IGV will give you the index warning for this file, just hit cancel and it will load anyway.  The file was produced as follows 

grep '      gene    ' gencode.v25.chr_patch_hapl_scaff.basic.annotation.gtf > gencode.v25.genes.gtf

[gencode.v25.genes.gtf.zip](https://github.com/igvteam/igv/files/516753/gencode.v25.genes.gtf.zip)
