### ISSUE TITLE
Fatal error (SIGSEGV) when running IGV on Ubuntu Linux

### ISSUE THREAD

**Issue by Nmael** [igvteam/igv#326]
Hello!

I am attempting to run IGV on an Ubuntu 16.04 installation. Execution fails with the following output (I've replaced my home directory with "[~]"):

```
$ ./igv.sh
INFO [2016-10-17 12:55:28,530]  [DirectoryManager.java:169] [main]  IGV Directory: [~]/igv
INFO [2016-10-17 12:55:28,530] [DirectoryManager.java:169]  IGV Directory: [~]/igv
INFO [2016-10-17 12:55:28,533]  [Main.java:133] [main]  Startup  IGV Version 2.3.82 (130)09/28/2016 12:07 AM
INFO [2016-10-17 12:55:28,533]  [Main.java:134] [main]  Java 9-internal
INFO [2016-10-17 12:55:28,534]  [DirectoryManager.java:72] [main]  Fetching user directory... 
INFO [2016-10-17 12:55:28,633]  [Main.java:135] [main]  Default User Directory: [~]
INFO [2016-10-17 12:55:28,633]  [Main.java:136] [main]  OS: Linux
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f40ab563009, pid=5367, tid=5371
#
# JRE version: OpenJDK Runtime Environment (9.0) (build 9-internal+0-2016-04-14-195246.buildd.src)
# Java VM: OpenJDK 64-Bit Server VM (9-internal+0-2016-04-14-195246.buildd.src, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libjava.so+0x1d009]  JNU_GetEnv+0x19
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %P" (or dumping to [~]/igv/IGV_2.3.82/core.5367)
#
# An error report file with more information is saved as:
# [~]/igv/IGV_2.3.82/hs_err_pid5367.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```

I have attached my [hs_err_pid_5367.log.txt](https://github.com/igvteam/igv/files/534448/hs_err_pid_5367.log.txt) file (added `.txt` extension so github will allow upload). No `igv.log` file is produced.

I'm getting the same error whether I try installing the `igv` package from the Ubuntu package repository, or downloading the [binary distribution](http://data.broadinstitute.org/igv/projects/downloads/IGV_2.3.82.zip) from the [downloads page](http://software.broadinstitute.org/software/igv/download). My Ubuntu version is `16.04.1 LTS` and my Java version information is:

```
 $ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

Thank you for your help - let me know if you need any other information about my environment!

**Comment by Nmael** [comment]
I was able to fix the problem by installing Oracle's JDK (I was previously using Ubuntu's default installation of OpenJDK), using the [instructions listed here](http://askubuntu.com/questions/521145/how-to-install-oracle-java-on-ubuntu-14-04). It appears IGV is using a set of libraries that are only shipped with the Oracle JDK package; perhaps it would be helpful to include a note on the [downloads page](http://software.broadinstitute.org/software/igv/download) stating that Oracle JDK is required to use IGV (at least on Linux systems)?

Thank you!

**Comment by jrobinso** [comment]
Thanks for the report.  We were not aware of any Oracle dependency, and in
fact it must be very recent as we have many OpenJDK users.    Could you
identify which specific libraries?

**Comment by Nmael** [comment]
The segfault appears to happen in one of the GUI libraries; the [stack trace](https://github.com/igvteam/igv/files/534448/hs_err_pid_5367.log.txt) involves two in particular: the Swing library (which I believe is also part of OpenJDK) and the "FreetypeFontScaler," which I am not familiar with.

**Comment by rfarouni** [comment]
Hi @jrobinso

I had the same problem, so I installed Oracle Java 9
```
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java9-installer
```
but neither Oracle 9 nor Open-jdk 9 worked. When I switch the openjdk 8 it worked.

Note: To switch back and forth between java versions, one could just run
```
sudo update-alternatives --config java
```
and select the corresponding number
