### ISSUE TITLE
Range - Byte test failed

### ISSUE THREAD

**Issue by kennytruong714** [igvteam/igv#327]
INFO [2016-10-17 19:34:56,610] [Main.java:72]  Startup  IGV Version 2.3.14 (16)08/05/2013 09:18 PM
INFO [2016-10-17 19:34:56,610] [Main.java:73]  Java 1.8.0_101
INFO [2016-10-17 19:34:56,610] [Main.java:74]  Default User Directory: C:\Users\kenny.x.truong\Documents
INFO [2016-10-17 19:34:58,138] [GenomeManager.java:120]  Loading genome: C:\Users\kenny.x.truong\igv\genomes\hg19.genome
INFO [2016-10-17 19:35:00,141] [GenomeManager.java:164]  Genome loaded.  id= hg19
INFO [2016-10-17 19:35:00,395] [CommandListener.java:81]  Listening on port 60151
INFO [2016-10-17 19:35:09,703] [IGV.java:1576]  Loading 2 resources.
INFO [2016-10-17 19:35:09,729] [TrackLoader.java:113]  Loading resource, path C:\Temp\G-POSCTRL_S90\AHCFW2AFXX_NextSeq05_G-POSCTRL_S90.bam
INFO [2016-10-17 19:35:09,893] [TrackLoader.java:113]  Loading resource, path C:\Temp\G-POSCTRL_S90\AHCFW2AFXX_NextSeq05_G-POSCTRL_S90.vcf
INFO [2016-10-17 19:35:20,960] [HttpUtils.java:748]  Testing range-byte request on host: igvdata.broadinstitute.org
INFO [2016-10-17 19:35:26,612] [HttpUtils.java:724]  Range-byte test failed -- problem with client network environment.

Anyone getting this error message this week? or started to get it Friday of last week?

**Comment by jrobinso** [comment]
Also, the host mentioned (igvdata.broadinstitute.org) is no longer used.   There is code in newer versions to translate this host to the current one,  but not in the version you are using.  I suggest you try the following, both might be neccessary.   (1) clear you genome cache by manually deleting the file <user home>/igv/genomes/hg19.genome.   Restart IGV and load hg19 again.  Test.   (2) update to the latest version of IGV.     The latter step is recommended but you might still need to clear the cache.

**Comment by kennytruong714** [comment]
Dear Jim and IGVTeam,

Thank you very much for your prompt response.

Before I received your email, I had figured out by trial and error to delete the prefs.properties file located in C:\users\profilename\igv\. From my experience through this incident, deleting the prefs.properties file is the same equivalent method as you have suggested with step 1 to clear the  genome cache.

You are absolutely correct, I noticed on some workstations that we used were using version 2.3.12. I had to update the version to a later version to get it to work.

Our I.T. folks have been notified of the steps in order to resolve the issue.

We’re back up and operational on multiple workstations.

Thank you very much for your help,


Kenny Truong
Quest Diagnostics Nichols Institute | Bioinformatics | 33608 Ortega Highway | San Juan Capistrano, CA 92675 USA | phone 949-728-4212 | mobile 949-606-4747 | fax 949-728-7792 | Kenny.X.Truong@QuestDiagnostics.com<mailto:Kenny.X.Truong@QuestDiagnostics.com> | www.Questdiagnostics.com<http://www.Questdiagnostics.com>

**Comment by jrobinso** [comment]
Hi,  I assume you updated to 2.3.83.    If you are still seeing the "Range
byte test" failure messages in your igv.log file, which I suspect you are,
 it is indicating that Range headers in http requests are being removed by
a proxy before being forwarded to our server.   This is not uncommon in
some institutions,  so we run a webservice that is used as a workaround
when this error is detected.   A change in configuration of that webservice
caused it to fail,  which brought the root problem to light (missing Range
headers).   The webservice issue is resolved with 2.3.83, which fixes your
problem, but it is not optimal.   If you are unable to configure the proxy
or fiilter to allow Range headers another alternative is to setup a genome
hosted on your intranet.   I can assist with that if needed, open a new git
issue if you want to proceed.

So this is a long way of saying that things are working again, hopefully,
but sum-optimally.
