### ISSUE TITLE
Show full path/url in the IGV viewer

### ISSUE THREAD

**Issue by slagelwa** [igvteam/igv#334]
Any chance of showing the full path/url to an opened bam file in the viewer, some place?  Or at least some sort of context beyond the file name?  We organize our by folder (sample, run, etc.) and don't really want to have to include redundant metadata information in the file name (e.g. 20160101Run/Sample333223/20160101Run.Sample333223.reads.bam)

**Comment by jrobinso** [comment]
Full paths are unpredictably long,  but predictably too long to fit in the window.   I've added the full path to the tooltip text for the track label (see figure) 
<img width="826" alt="screen shot 2017-01-07 at 9 25 50 pm" src="https://cloud.githubusercontent.com/assets/933148/21747593/1e3a3742-d520-11e6-8d7f-dba0b7a8ed22.png">
