### ISSUE TITLE
bisulfite mode in small letter reference sequences "disabled"

### ISSUE THREAD

**Issue by aerval** [igvteam/igv#335]
I am displaying WGBS data on the default mm10 genome that contains at some positions in the reference genome small letter bases (repeats etc.?) like ```act``` instead of ```ACT```. The default bisulfite mode does not highlight the methylation in reads in these areas. Similar, C highlighting does not highlight Cs etc. I assume its a bug because CpGs are recognized by capital CG letters?

Edit: Of course you can create an all capital version of the reference genome to fix the display

**Comment by jrobinso** [comment]
Hi, yes that looks like a bug.  Could you please try the development snapshot version and see if that resolves the problem?  You can access it here:  http://software.broadinstitute.org/software/igv/download_snapshot

**Comment by aerval** [comment]
Brilliant, that works great. Thanks a lot!

**Comment by aerval** [comment]
Oh, well it is not important for me but the coverage plot still does not show the number of un-/methylated Cs. Really not important as you can easily look it up but yeah ...

**Comment by jrobinso** [comment]
OK, coverage plot should be fixed now (snapshot version).   These fixes will be in the next release.
