### ISSUE TITLE
'Copy Sequence' from same strand as the feature

### ISSUE THREAD

**Issue by thobrock** [igvteam/igv#351]
Thanks for all your efforts in developing this nice software.

But recently, I wanted to copy the sequence of a feature (Exon of the loaded GFF file) and it seems that the exported sequence is always from 5' to 3' end of the positive strand of genome regardless of the location of the feature, which is not intuitive.

Since the gene I'm interested in is located on the negative strand, it would make sense that the actual sequence of the feature will be exported, that means the sequence from the negative strand.

Best,
Thomas

PS: I'm using the Linux version 2.3.88

**Comment by jrobinso** [comment]
I agree this makes some sense for features, but is contrary to standard practice for alignments.

**Comment by thobrock** [comment]
Ok, I see. Thanks for clarification.

Would it solve the conflict, if the 'Copy Sequence' function is couple to the showed strand ('Flip strand')? 

Then it would be up to the user which direction/strand will be exported. For alignments he can use always the positive strand and for features he can adjust/flip the strand based on the location of the feature.

**Comment by jrobinso** [comment]
Yes, but I think your original proposal would work on reflection.    I will
get to this and the other bug for the next point release.

On Thu, Jan 5, 2017 at 1:25 AM, Thomas Brockmöller <notifications@github.com

**Comment by thobrock** [comment]
Thanks for considering this.

**Comment by thobrock** [comment]
Super, thanks you. I tried the new release 2.3.90 and it works fine.
