### ISSUE TITLE
Amino acid sequence on the negative strand is not correct (introduced in v2.3.89) 

### ISSUE THREAD

**Issue by thobrock** [igvteam/igv#352]
After my previous request I found out about the most recent version 2.3.89 and downloaded it for Linux. 

The bug can be reproduced by:
* Loading a genome
* Loading a GFF file
* In the bottom window 'Flip strand' to display the negative strand and 'Show translation'

Now the amino acid sequence is not correct; it's the same sequence for all three reading frames (e.g. Stop Codons are aligned) and if you move to the left or the right (e.g. by using the cursor) the amino acid sequences change completely.

**Comment by jrobinso** [comment]
Thanks for the report.

On Wed, Jan 4, 2017 at 8:25 AM, Thomas Brockmöller <notifications@github.com

**Comment by thobrock** [comment]
I think this might be related, although it's already in v2.3.88 (haven't tested with 2.3.89).

The reading frame of the AS sequence of the feature changes. Here are two figures from the same gene.
![right side](https://cloud.githubusercontent.com/assets/6839476/21677398/3c51efdc-d33a-11e6-975b-b8f6cad46c73.png)

And if I move the window to the left:
![left side](https://cloud.githubusercontent.com/assets/6839476/21677397/3c4e2bcc-d33a-11e6-9b08-0e7e92f15dfe.png)

**Comment by jrobinso** [comment]
Yes, probably related.  This only occurs on negative strand genes, correct?

On Thu, Jan 5, 2017 at 2:30 AM, Thomas Brockmöller <notifications@github.com
