### ISSUE TITLE
BED Parsing errors are more cryptic than they should be

### ISSUE THREAD

**Issue by mp15** [igvteam/igv#359]
Hi,

For some reason instead of stating the byte position where parsing failed on a BED file, IGV kicks out a hex position in htsjdk. It would be nice to fix this.

```
htsjdk.tribble.TribbleException$MalformedFeatureFile: Error parsing line at byte position: htsjdk.tribble.readers.LineIteratorImpl@36af05e8, for input source: /nfs/users/nfs_m/mp15/badbed.bed
```

Incidentally the above error was caused by a space accidentally following a position in the bed file.

**Comment by jrobinso** [comment]
I agree, but this is in the htsjdk library.   I suppose IGV could try to
parse it but the best solution is a fix there.
