### ISSUE TITLE
Feature request: Autoscale to Maximum

### ISSUE THREAD

**Issue by Mashin6** [igvteam/igv#364]
What I would find useful is if I could select multiple tracks and set them to autoscale to the maximum (in given view) of the track with the highest signal. 

<img width="900" alt="screen shot 2017-01-25 at 10 20 54" src="https://cloud.githubusercontent.com/assets/5265707/22296505/57928afa-e2e8-11e6-9822-3090c034f55f.png">

**Comment by helgathorv** [comment]
Have you tried the "group autoscale" feature? Select all the tracks, then right-click and select "Group Autoscale" from the popup menu.

**Comment by Mashin6** [comment]
Sorry. I was using v 2.3.68. Didn't realize this was added in the latest version.
