### ISSUE TITLE
IGV running with low available memory

### ISSUE THREAD

**Issue by marisarose92** [igvteam/igv#367]
Hi,

How can i fix IGV so that it runs smoothly without running out of memory during analysis?

Thanks

**Comment by jrobinso** [comment]
It's really impossible to give advice with the minimal information you've
given.

**Comment by marisarose92** [comment]
Hi,

Sorry about the minimal information. Lately when I go to launch IGV it comes up with this following nitification
[cid:image001.png@01D282AC.760153F0]
Then when I’m looking at the sequencing it runs out of memory and I can no longer look at the sequence.

Thanks,

Marisa

[Description: Description: Genea Corporate_PMS.jpg]

Marisa Zappia
Scientist
t  8484 6543
f  9229 6400
e   marisa.zappia@genea.com.au<mailto:marisa.zappia@genea.com.au>
w  genea.com.au
Level 3, 321 Kent Street, Sydney NSW 2000 Australia
Please consider the environment before printing

**Comment by jrobinso** [comment]
Hi,

What do you mean by  "looking at the sequence".   Tell us specifically what
type of file you are loading, and how many,  and whether or not you have
changed any settings or preferences from the defaults.   Also, most
importantly,  how are you starting IGV?

**Comment by marisarose92** [comment]
Hi,

I load bam files into IGV. I tend to load about 4-8 at a time which has ran smoothly in the past. No settings have been changed. Unless you include Java 8.

I downloaded the ZIP files from the website yesterday thinking it would help. I am launching it from the IGV in the ZIP file.


[Description: Description: Genea Corporate_PMS.jpg]

Marisa Zappia
Scientist
t  8484 6543
f  9229 6400
e   marisa.zappia@genea.com.au<mailto:marisa.zappia@genea.com.au>
w  genea.com.au
Level 3, 321 Kent Street, Sydney NSW 2000 Australia
Please consider the environment before printing

**Comment by jrobinso** [comment]
8 is a lot.  Could you attach your "prefs.properties" file?  Its in the IGV
folder.

What operating system are you running?

**Comment by jrobinso** [comment]
Also, are you running the igv.sh or igv.bat file to start?   If you just
double-click igv.jar,  which might appear as just "igv" if your operating
system hides extensions,  you will run out of memory very fast.

**Comment by marisarose92** [comment]
I can’t seem to find the prefs.properties file.

I am double clicking on just the igv.

I just figured out which one is the IGV.bat and can launch it from there without the low memory warning, so let’s see how it goes.

Thanks for your help.

Marisa

[Description: Description: Genea Corporate_PMS.jpg]

Marisa Zappia
Scientist
t  8484 6543
f  9229 6400
e   marisa.zappia@genea.com.au<mailto:marisa.zappia@genea.com.au>
w  genea.com.au
Level 3, 321 Kent Street, Sydney NSW 2000 Australia
Please consider the environment before printing

**Comment by jrobinso** [comment]
The "prefs.properties" file is in the igv folder under your home directory.
  However, that wasn't the issue,  you answered the question.
