### ISSUE TITLE
largedata dir for testing

### ISSUE THREAD

**Issue by david-w-mead** [igvteam/igv#374]
I'm trying to run the junit tests for IGV and there is a directory missing that is causing some tests for fail: test/largedata/

Can you tell me where I can find this test data?

Thanks,
David Mead
Mayo Clinic

**Comment by jrobinso** [comment]
Hi,  sorry about that.  You can download it here:
http://data.broadinstitute.org/igvdata/largeData.zip

**Comment by david-w-mead** [comment]
I tried to access the data but I'm getting a 403 forbidden error.

**Comment by jrobinso** [comment]
Sorry again, case error.  This should work

https://data.broadinstitute.org/igvdata/largeData.zip

**Comment by david-w-mead** [comment]
I was able to download the file this time, however there are files
HG00171.hg18.bam and HG00171.hg18.bam.bai that are not in this zip. Can you
point me to these file?

Thanks,

David

**Comment by jrobinso** [comment]
Apologies again David, that was an outdated zip.   This should be the
correct one:

ftp://ftp.broadinstitute.org/pub/igv/largedata.zip
