### ISSUE TITLE
Display command codes in IGV

### ISSUE THREAD

**Issue by dktanwar** [igvteam/igv#376]
Hi,

Is it possible to display the commands from IGV?

Suppose I have loaded 5 files in IGV. Now, I have changed their colours and displaying tracks for BRCA1 gene. 

Is it possible to get a command, which when run from command line, can give the same output and save it as a screen shot?

Thanks,
Deepak

**Comment by jrobinso** [comment]
No, that is not possible.   You can save the current state ("save session").

**Comment by dktanwar** [comment]
I want this as I would like to produce coverage graphs of 5 files (for some 100 genes), with specified colours and showing peaks called by 3 different softwares. This would be a great thing to have.

**Comment by dktanwar** [comment]
Can you please provide me a command that could do the following from command line:

1. Load the tracks from 5 bigwig files.
2. Custom colour the tracks.
3. Display bars from 3 bed files.
4. Save screenshot of tracks of a particular gene.
