### ISSUE TITLE
command codes for IGV

### ISSUE THREAD

**Issue by dktanwar** [igvteam/igv#377]
Can you please provide me a command that could do the following from command line:

Load the tracks from 5 bigwig files.
Custom colour the tracks.
Display bars from 3 bed files.
Save screenshot of tracks of a particular gene.

I have posted it as a new issue as you have closed #376

**Comment by jrobinso** [comment]
Are you asking a question or making a feature request?    IGV is not
primarily a command line program,  you will have to look elsewhere for
that.  Supported commands are listed here:
http://software.broadinstitute.org/software/igv/PortCommands.   Command
line instructions are here:
http://software.broadinstitute.org/software/igv/startingIGV.    I will
leave this open as a request but there are many competing priorities.
