### ISSUE TITLE
Windows self-extracting binary seems corrupt

### ISSUE THREAD

**Issue by peterragone** [igvteam/igv#383]
The self-extracting Windows binary reports errors upon opening. 
This is the file at http://data.broadinstitute.org/igv/projects/downloads/IGV_2.3.92.exe
Tested in Win7 and Win10. 
Attempting to open in Win7 results in error "IGV_2.3.92.exe is not a valid Win32 application."
Attempting to open in Win10 results in error "This app cannot run on your pc."

**Comment by helgathorv** [comment]
Note that the Windows package is for 64-bit Windows only.
Please try the regular binary distribution (available a little further down on the IGV downloads page, or directly from the following link http://data.broadinstitute.org/igv/projects/downloads/IGV_2.3.92.zip).
Let us know if you also have problems with that.

**Comment by peterragone** [comment]
Hi Helga,

I ran my extraction attempt on one of our Broad Win7 VM's which is 64-bit
Win7 Enterprise. Eric Jones ran his on his Broad-issued Windows 10
Enterprise, which is also 64-bit.

-- Peter

**Comment by jrobinso** [comment]
Also, did  you try the java web start link button?   That is the preferred
method of running IGV,  the Windows and binary packages are included for
users who have problems using the web start links.   This is rare.

If you have a 32 bit windows machine you will be limited to one of the
lower memory options,  try the lowest memory option first.

**Comment by peterragone** [comment]
Oh -- to complete the report, I had no problem unzipping and running the
IGV_2.3.92.zip from the data.broad you'd linked.

**Comment by helgathorv** [comment]
Thanks for the report Peter. The fact that the error message said it wasn't a "valid Win32 application" made me think you were on 32-bit windows.

**Comment by peterragone** [comment]
Hi Jim,
I'm a bit in the middle on this. My goal isn't actually to run IGV myself. The Broad's help@broad had received a request for assistance unzipping that file, so I've submitted this request. Perhaps it would have been better for me to have suggested the original caller submit this report. (I did inform him that one of the methods on the IGV contacts page would've been the right place to report.) I don't know whether the Java startup didn't work, nor more about the motivation to unpack the 64-bit self-extracting exe.

**Comment by helgathorv** [comment]
Peter, Please just tell them to use one of the other options for launching IGV. Feel free to let them know they can contact me at the Broad if they continue to have problems with the other options.

**Comment by jrobinso** [comment]
Thanks for the report Peter.    I'm not sure what the problem with the
archive is, the error message you received leads us to believe you were
extracting on Win32.    The self-extracting archive was added for users who
do not know how to unzip a file.

**Comment by ericbecker3** [comment]
Hey Jim, Peter,

I am the original caller, I need the software package to run through our own internal software packaging process, as we have managed desktop environments where users don't have admin rights, and all software is via push install.  The attached screenshot shows the PC is a 64-bit OS, and produces the error.  I will try the 32-bit version.

![ivg_2392 error](https://cloud.githubusercontent.com/assets/26655477/24301952/ed2cf2ee-107e-11e7-8252-d179750264ad.jpg)

**Comment by jrobinso** [comment]
Hi, we don't have 32 and 64 bit versions of IGV, the problem was with the self-extracting zip.   I have removed that link,  use the "binary distribution" link.   The self-extractor did just that, self-extracted,  but otherwise was equivalent to the binary distribution.    The actual executable is Java,  which should be separately installed.  64-bit Java is highly recommended.
