### ISSUE TITLE
Sequence track: show gaps of Ns when zoomed out [feature request]

### ISSUE THREAD

**Issue by sjackman** [igvteam/igv#387]
When zoomed out, the sequence track is blank. It would be very helpful to me to show the locations of sequence gaps of Ns in the sequence track when zoomed out. I'd like for even small gaps to visible at any zoom level, so even a single N would also be shown as at least one pixel wide.

**Comment by jrobinso** [comment]
Zoomed out to what range?  We of course would have to read the sequence to
know that there are "Ns" there,  typically sequence isn't read until its
needed.   Another solution is to make a simple bed track from your fasta
containing regions of "Ns".

**Comment by sjackman** [comment]
A few megabases? I'm working with draft assemblies of genomes.

**Comment by sjackman** [comment]
Creating a BED track of gaps is a good suggestion. I know that I've run into a command line that does exactly this, but I've forgotten which. Possibly GenomeTools or Bedtools.
