### ISSUE TITLE
Method to unbgzf bam byte array data 

### ISSUE THREAD

**Issue by amolpshinde07** [igvteam/igv#390]
Hi @jrobinso ,
is there any method/function to unbgzf bam byte array data similar to `igv.unbgzf = function (data, lim) ` from igv.js?

**Comment by jrobinso** [comment]
I don't understand the question, that is the function (the one you referenced).   Why do you need to do this?

**Comment by amolpshinde07** [comment]
Instead of passing byte array to igv.js, I want to send BamAlignments from server side to client side to reduce content size which will result into performance improvement.

**Comment by jrobinso** [comment]
I don't understand your proposal, I think it will increase content size.  The content from the server is compressed. In any event you will need to code that yourself.

**Comment by amolpshinde07** [comment]
@jrobinso is there any way to reduce content size receiving from server to igv.js?
e.g. for particular bam file, if we call with chr7:117231917-117232834 (size:917) then it will receive 11.8 MB data.
To transfer 11.8 MB from server to client it takes approx. 60 sec,so is there any way to reduce this data size?

**Comment by jrobinso** [comment]
No, there is not, and if it takes you 60 seconds to transfer 11 MB you have
a very poor network.   That is the root of your problem.

**Comment by amolpshinde07** [comment]
@jrobinso  Thank you so much.
