### ISSUE TITLE
Filter alignments by alignment score (AS) tag [feature request]

### ISSUE THREAD

**Issue by sjackman** [igvteam/igv#392]
The Preferences -> Alignments tab has a "Mapping quality threshold" option. I would find a similar "Alignment score threshold" option very useful to filter out alignments with a poor alignment score.

My use case is that I'm mapping reads to a de novo assembly of those reads, so the reads that are mapped correctly should map nearly identically. Reads with a poor alignment score are most likely mismapped.

**Comment by sjackman** [comment]
Gentle ping. I'd still love to have this feature.

**Comment by jrobinso** [comment]
I could add this as an undcoumented preference you insert into "prefs.properties".   It is too specialized to add to the UI.   Could you supply an example sam or bam file for testing, and fasta if needed.

Also,  what happens if filter is on and an alignment does not have an AS tag.   Does it pass or fail?

**Comment by sjackman** [comment]
Okay. I'll take an undocumented `prefs.properties`. Thanks, Jim. I can provide a BAM file if you like, but most BAM files should have `AS:i:` tags. BWA outputs these tags for sure. Let me know if you'd still like me to provide a BAM file.

> Also, what happens if filter is on and an alignment does not have an AS tag. Does it pass or fail?

I'd suggest pass.

**Comment by jrobinso** [comment]
I just tried a random 1000 genomes bam and it doesn't have it.   If you can point me to a publicly accessible bam that does I'll use it.

**Comment by sjackman** [comment]
Here's a sample BAM file from GATK `NA12878_20k.b37.bam`:
https://console.cloud.google.com/storage/browser/gatk-test-data/wgs_bam/NA12878_20k_b37

**Comment by sjackman** [comment]
Thank you very much for implementing this feature, Jim! It's very helpful to me. 😃

**Comment by jrobinso** [comment]
@sjackman no problem.   The threshold actually is in the next preferences UI,  not released yet but used in development.

**Comment by sjackman** [comment]
Excellent! Is the snapshot development build released nightly? https://software.broadinstitute.org/software/igv/download_snapshot

**Comment by jrobinso** [comment]
Its triggered on each commit, so it should have this change.
