### ISSUE TITLE
igv.sh missing from binary download

### ISSUE THREAD

**Issue by cb4github** [igvteam/igv#394]
I just now downloaded the zip file...

```http://data.broadinstitute.org/igv/projects/downloads/IGV_2.3.92.zip```

...but after unzip the shell script ```igv.sh``` file seems to be missing.

Please advise, and thanks for all your efforts!

Also, here's some sys info...
```
$ uname -a
Linux <my hostname> 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
Best,
CB

**Comment by cb4github** [comment]
Admittedly this is not urgent, though.

I got it directly from...
```
https://github.com/igvteam/igv/blob/master/scripts/igv.sh
```

**Comment by jrobinso** [comment]
Sorry, that's a mistake on my part.  That zip is intended for Windows
users,  I just realized I clobbered the general binary zip.   Will sort
this out this evening.
