### ISSUE TITLE
Overlay tracks by user selected sample attribute 

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#396]
It would be handy to have feature to overlay tracks having the same values for one or more attributes.

This would allow, by glancing at a single merged track, visualizing the *within group variance*, upon which differential expression computations are based.

I often do this by hand in IGV, as follows:
> group autoscale all my (FPM) bigwigs within the experiment
> change the plot type to display them as a Line Plot
> create overlays, one for each group of replicates

When comparing a bunch of different gene knockDowns done in replicate, with  "geneKnockDown" as a sample attribute, I would choose to "overlay by geneKnockDown".

Its just a few clicks to do it by hand with small/moderate set of experiments, but it would be quite useful when having many tracks large scale.

**Comment by helgathorv** [comment]
Released in IGV 2.8.0
