### ISSUE TITLE
"show data range" doesn't with overlay tracks, even if they are group autoscale

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#398]
Overlay tracks potentially are displaying data on multiple scales.  However, when they are on the same scale (due to group autoscale, or they have been assigned the same scale), it would be good to see these value displayed.

**Comment by kashyapchhatbar** [comment]
This feature would be good to have....

**Comment by jrobinso** [comment]
This was fixed at some point, sorry I neglected to update this issue.
