### ISSUE TITLE
Reference track not displayed

### ISSUE THREAD

**Issue by ryan-williams** [igvteam/igv#407]
![](https://d3vv6lp55qjaqc.cloudfront.net/items/0x440x2p2S0Z3244372V/%5B00970089e6a5ace4f9f4cbe967704df6%5D_Screen%2520Shot%25202017-05-11%2520at%252011.48.00%2520AM.png)

How do I toggle whether the reference track is shown?

Just upgraded from 2.3.42 to 2.3.92 and neither shows me the reference. Coworker looking at same locus/tracks on 2.3.72 has reference displayed.

**Comment by ryan-williams** [comment]
I was able to get it to display after downloading and switching to "Human (1kg, b37+decoy", but it cleared my session.

Unclear why it wasn't displaying it previously when I had "Human (b37)" selected, and switching back to that still has my session cleared. 🤷🏼

**Comment by jrobinso** [comment]
I'm not entirely sure what's going on here either,  there is no toggle.
Did this occur upon loading a session?   Could you share the session xml
file,  you can blank out the paths to the bam files,  I'll substitute
public bams.     Switching genomes always clears the session,  that is by
design.

**Comment by jrobinso** [comment]
Hi @ryan-williams ,   I can't reproduce this,  if you can share your session xml (you can blank out the bam file names if you want)  I will try again.

**Comment by ryan-williams** [comment]
Sorry for the delay… just tried recreating the session in question from scratch in 2.3.92, and I am seeing a reference, so I'll just close this for now, thanks!
