### ISSUE TITLE
Batch "snapshot" produces black for the data window

### ISSUE THREAD

**Issue by amwenger** [igvteam/igv#416]
The "snapshot" command in IGV batch scripts is producing all black in the data window.  File > Save Image works fine.  The behavior is the same for me for IGV 2.3, 3.0, and master on macOS Sierra.

Batch script

    genome hg19
    goto chr6:43136920-43151244
    snapshot 1.png

Batch script "snapshot"
![1](https://cloud.githubusercontent.com/assets/7155109/26383052/725b0fc4-3fe5-11e7-9011-f8b61a2ff32c.png)

File > Save Image
![filesave](https://cloud.githubusercontent.com/assets/7155109/26383064/819328f0-3fe5-11e7-8597-1e648a3c9a00.png)

**Comment by jrobinso** [comment]
Actually the first image is not "fully black",  it is in fact what should be produced from batch snapshots,  with the exception of the black background.   Batch snapshots behave different than save image from the file menu in a couple of ways  (1) minimal window decoration is painted (e.g. no scrollbars),  (2) panels are not limited to their screen dimensions, in fact they will expand vertically to paint all the data unless a "maxPanelHeight" is set,  (3) empty panels (panels with no tracks) are skipped.

**Comment by jrobinso** [comment]
Having said that,  I found other problems.   Perhaps we should add a command option to save an image using the "File > Save Image..."  method  ("onscreen" ->  paints the window components as seen in the UI).     Rather than use the option for each "snapshot" command it could be a state,  as the snapshot directory is.    I don't know what to call the option though, any ideas?

**Comment by jrobinso** [comment]
I've escalated this to 3.0.

**Comment by amwenger** [comment]
Thanks for the explanation and sorry for the sloppy test case.  I ran into the issue trying to create 100 snapshots of a session that included a BAM file and none of the snapshots had any read data shown, just black.  Let me see if I can reproduce that and give you a test case.

I like the "onscreen" idea.  Perhaps just "snapshotView" with defaults "current" or "all" with "all" as default.

It would be nice to have an option to get the "snapshot" view without window framing through the "File > Save image" too.  I often save the image and then edit the window framing out in an image editor.

**Comment by jrobinso** [comment]
Yes I agree you should have both options from batch & UI,  that's not going
to make 3.0 but should be done in master.   Right now I'm just cleaning up
some minor bugs I'm fixing for 3.0.   The image saving code is going to
have to be rewritten soon as we more or less have to port from Swing ->
Java FX,  that will force a rewrite and rethink of this.

**Comment by jrobinso** [comment]
If you want to open another issues for the "onscreen / offscreen" options (batch & file menu) I'll get to them when I can.   I'm about to push fixes for the ugly black background and a few other items for the 3.0 release which will resolve this issue.

**Comment by amwenger** [comment]
Thanks, Jim.  This fix is nice.  My batch script is now mostly working.  I still have some issues that seem to be timeout-related (i.e. looks like snapshot happens before load is complete).

**Comment by jrobinso** [comment]
That shouldn't be able to happen,  loading (should) be synchronous when in
batch mode.   What type of tracks are not getting loaded (bam/alignment,
others)?

**Comment by amwenger** [comment]
Sorry, I can not reproduce the timeout issue.  I was trying to load BED and BAM tracks on a filesystem mounted via sshfs and accessed from home over a VPN.  The problem was probably not with IGV but with the file access, as I can not reproduce and it now works well.
