### ISSUE TITLE
Provide progress monitor for CRAM loading

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#420]
Loading CRAM alignments can be slow, especially if using a remote reference.   Provide some feedback in the form of a progress monitor or dialog.

Even if using a local reference CRAM loading is slow compared to BAM.   Attached is a screenshot of a cpu profile.   There probably isn't much to be done about this, other than progress feedback.
<img width="1008" alt="screen shot 2017-05-24 at 3 19 23 pm" src="https://cloud.githubusercontent.com/assets/933148/26428158/010554d2-4095-11e7-97cb-4b0198a73ad3.png">

**Comment by SHuang-Broad** [comment]
I would love to see this feature.
In addition, would it make sense to provide a "button" so that a user can stop the loading process, particularly when one steps into a region with unexpectedly high coverage (structural variation review typically needs a large window size compared to when reviewing small variants, and sometimes fetching the reads in the specified window really takes a long time)?

**Comment by jrobinso** [comment]
I agree a cancel/stop button should be included on the dialog.   I've still not determined why CRAM is so slow,  but using a local reference does help considerably.   It doesn't completely solve the issue however.   From the above profile decoding the records seems to be implicated.

**Comment by jrobinso** [comment]
@SHuang-Broad I just pushed a major performance fix that might lessen the need for a "cancel" button.   There is still a delay when loading the reference sequence the first time for a chromosome, but after its fast (on the same chromosome).   If you use a local reference (i.e. load from local file not http) the sequence load is also fast.   I still plan to add a progress indicator for the sequence load.

**Comment by SHuang-Broad** [comment]
Thanks @jrobinso!

**Comment by jrobinso** [comment]
I'm still banging on this.   Did you notice an improvement?   Its better but still takes too long to download the sequence,  2x as long in Java as downloading the same number of bytes via a web browser.   If I can find that problem the initial delay will be much improved.   Next step is to support bgzipped fastas,  which theoretically should give another 2-3x speedup when they are used.   I did add a "cancel" button for the alignments, btw,  its in the lower left corner of the window and should be active when alignments are being loaded.    However, hitting that during the initial sequence download won't have any effect (yet).

**Comment by jrobinso** [comment]
Performance has been increased further by (1) supporting bgzipped fasta files, and (2) caching sequences locally.  Its now fast enough that a dedicated progress dialog is probably not needed (generally < 15 seconds).   A  "Load sequence" message is displayed in the lower left corner.
