### ISSUE TITLE
Have "color alignments by" override the YC tag

### ISSUE THREAD

**Issue by tcashby** [igvteam/igv#421]
Hello, I was wondering if it was possible (or maybe it's already there and I missed it) to have the "color alignments by" feature override the colors assigned by the YC tag. 

With bam files that have the YC tag assigned there is some utility in seeing different features this way in IGV, but it makes it impossible to use the other coloring features without creating a separate bam file with all the color tags stripped out. Ideally, there would be a setting to have no colors, use the YC tag colors or use one of the other coloring options.

**Comment by jrobinso** [comment]
I agree "color by" should override the YC tag,  it doesn't currently.  We will change the priority order.
