### ISSUE TITLE
Default window size from igvtools count causes wigtobigwig to fail

### ISSUE THREAD

**Issue by papanikos** [igvteam/igv#425]
Hello,
I got an error when trying to convert a wig file created with igvtools count to bigwig format. There are only a couple of reads aligning to the end of my contig and only there (i.e. no other window on this contig). The size of my reference contig is 7348 and my alignment starts from position 7329. If the window size is kept at 25 (span=25 in the wig file) then wigtobigwig exits with 
```line 3 of output.wig: chromosome x has 7348 bases, but item ends at 7350```

I am reporting this here because I think a check could be added for (extreme) cases like this. This way the output of igvtools count is corrected when the window size falls out of the chromosome to match its length and everything runs smoothly further downstream.

**Comment by jrobinso** [comment]
Actually this shouldn't happen,  the window size is truncated at the end of chromosome (contigs) if necessary.  Could you share a test case that reproduces the problem?

**Comment by papanikos** [comment]
I made a minimal test case from my original files. I have included all the relevant files (bam file, reference fasta and a small README file with the commands that give me the same error). Hope this helps!
[igv_test.tar.gz](https://github.com/igvteam/igv/files/1094542/igv_test.tar.gz)

**Comment by jrobinso** [comment]
This was really pathological.  It would only occur if there were a step line for the contig
