### ISSUE TITLE
IGV fails to open filenames containing + from the command line

### ISSUE THREAD

**Issue by sjackman** [igvteam/igv#427]
IGV fails to open filenames containing `+` from the command line. Replacing `+` with `%2b` does not work. Surprisingly, replacing `+` with `%252b` does work. The argument should not be interpreted as URL encoded when the command line argument is a file path (e.g. `./test+.bed`) rather than an URL (e.g. `file:///test%2b.bed`).

To replicate:
```sh
touch test+.bed
igv test+.bed
```

| Command           | Success | Error                       |
| ----------------- | ------- | --------------------------- |
| igv test+.bed     | ❌       | `File not found: test .bed` |
| igv test%2b.bed   | ❌       | `File not found: test .bed` |
| igv test%252b.bed | ✅       | NA                          |

**Comment by jrobinso** [comment]
I see the problem, but we've always accepted url encoded paths, it would potentially break a lot of scripts if we changed that.

**Comment by sjackman** [comment]
Do you thing people rely on file paths being URL encoded? It seems unusual to me. I can understand wanting to maintain backward compatibility though.

Should `igv test%2b.bed` open the file `test+.bed`? Currently that doesn't work.

**Comment by jrobinso** [comment]
All parameters are potentially url encoded.  This is primarily for websites that generate jnlp files from web links of other means.   I don't recall all the details but some of them definitely send all parameters (which become command line arguments) encoded.

I thought of a solution for files,  since they are local we can test that they exist.  First test  as is,  if the file doesn't exist decode.   I will work on implementing that.    BTW what is  "%2b" encoding?

**Comment by sjackman** [comment]
That's a good idea. Thanks, Jim!

`%2b` is `+` and `%25` is `%`. See https://en.wikipedia.org/wiki/Percent-encoding

I would expect `igv test%2b.bed` to open the file `igv+.bed`, but it instead opens the file `igv .bed` (space, not `+`).
I would expect `igv test%252b.bed` to open the file `igv%2b.bed`, but it instead opens the file `igv+.bed`.
It appears that the URL is being unencoded twice, which would explain this unexpected behaviour.

**Comment by jrobinso** [comment]
I've pushed a fix to the 3.0 branch, will push to master after resolving
some conflicts.   I don't expect to apply this patch to the 2.3.x branch.

**Comment by jrobinso** [comment]
Oh, good catch on the double decoding.   I caught that as well in the code,  the extra decoding was removed.

**Comment by sjackman** [comment]
Thanks, Jim!
