### ISSUE TITLE
HaplotypeCaller IGV plugin

### ISSUE THREAD

**Issue by lbergelson** [igvteam/igv#428]
I know in the past there has been talk about including a HaplotypeCaller plugin for IGV that could produce a reassembled view of reads at a specific location.  This is useful for reviewing variant calls from HaplotypeCaller.  From my admittedly vague memory of the subject, the proprietary license of HaplotypeCaller was the major factor preventing the development of such a plugin.  Now that all of Gatk4 is BSD licensed, would there be interest in collaborating on a plugin for HaplotypeCaller / Mutect2?  This would be a very valuable tool for a lot of GATK users.

**Comment by jrobinso** [comment]
Yes, sounds really interesting,  lets do it.   I don't recall discussing
this before.
