### ISSUE TITLE
Accept space-delimited file lists on IGV command line

### ISSUE THREAD

**Issue by sjackman** [igvteam/igv#430]
I typically start IGV from the command line.
I'd love to be able to `igv *.bam` to open all the BAM files in the current directory. Currently I do something like `igv $(ls *.bam | paste -sd, -)`, which is a bit clumsy.
Would you consider treating all arguments after `--` as file names? For example
```sh
igv -- *.bam
```
The locus could possibly be specified with an option. For example
```sh
igv -l chr1:100-200 -- *.bam
```

**Comment by jrobinso** [comment]
Yea, interesting idea, ping this again in a few months if no action.   Currently I am trying to close out a 3.0 release, so only bugs are being fixed (e.g. files with + problem is a bug).

**Comment by sjackman** [comment]
Sounds good.

**Comment by sjackman** [comment]
Good luck with the 3.0 release! The snapshot builds have been looking great.

**Comment by holgerbrandl** [comment]
How does a user know about the supported CLI. I've tried `java -jar igv.jar --help` and various flavors of it, but no luck. All I get is 
```
[3p_counts]$ java -jar /Users/brandl/Downloads/software/IGV_2.3.79.app/Contents/Java/igv.jar  -help
INFO [2017-09-05 10:45:37,408]  [DirectoryManager.java:163] [main]  IGV Directory: /Users/brandl/igv
INFO [2017-09-05 10:45:37,408] [DirectoryManager.java:163]  IGV Directory: /Users/brandl/igv
INFO [2017-09-05 10:45:37,414]  [Main.java:99] [main]  Startup  IGV Version 2.3.79 (118)07/09/2016 11:48 PM
INFO [2017-09-05 10:45:37,414]  [Main.java:100] [main]  Java 1.8.0_131
INFO [2017-09-05 10:45:37,414]  [DirectoryManager.java:72] [main]  Fetching user directory... 
INFO [2017-09-05 10:45:37,703]  [Main.java:101] [main]  Default User Directory: /Users/brandl
INFO [2017-09-05 10:45:37,703]  [Main.java:102] [main]  OS: Mac OS X
INFO [2017-09-05 10:45:39,283]  [Main.java:150] [main]  A later version of IGV is available (2.3.93)
jargs.gnu.CmdLineParser$UnknownSuboptionException: Illegal option: 'h' in '-help'
```
In particular I'd like to open a session file when opening IGV. Is this possible?

**Comment by sjackman** [comment]
Running igvtools from the Command Line
https://software.broadinstitute.org/software/igv/igvtools_commandline

**Comment by holgerbrandl** [comment]
@sjackman I know and use those as well, but I don't see hw I could use them to open the IGVviewer with a particular session file?

**Comment by jrobinso** [comment]
Documented here:
https://software.broadinstitute.org/software/igv/startingIGV

**Comment by holgerbrandl** [comment]
Cool thanks. Works via jar but (just fyi) somehow not for the macos app:

```
#works like charm
java -jar /Users/brandl/Downloads/software/IGV_2.3.79.app/Contents/Java/igv.jar my_session.igv.xml

#does not work for me
open -n  /Users/brandl/Downloads/software/IGV_2.3.79.app --args my_session.igv.xml
```

**Comment by jrobinso** [comment]
The igv macos app does not support command line arguments,  I'm not even sure that is possible.

**Comment by sjackman** [comment]
@holgerbrandl On macOS, install IGV using Homebrew, which installs an `igv` executable.
```sh
brew install homebrew/science/igv
```
The `IGV.app` can be installed using
```sh
brew cask install igv
```

**Comment by holgerbrandl** [comment]
@sjackman awesome, thanks a lot.

**Comment by sjackman** [comment]
Here's a workaround for specifying multiple files on the command line using `paste -sd, -`:
```sh
igv $(ls *.bam | paste -sd, -)
```
or alternatively using `tr`
```sh
igv $(echo *.bam | tr ' ' ,)
```

**Comment by sjackman** [comment]
Was this feature ever implemented, Jim? I'd still love to be able to run…
```sh
igv -g genome.fa *.bam
```

**Comment by sjackman** [comment]
Yes, and the wildcard is expanded by the shell to multiple files separated by spaces. For example
```sh
igv -g genome.fa track1.bam track2.bam track3.bam
```

**Comment by jrobinso** [comment]
Yes,  I don't have access to the shell but can support *.bam manually.    Java is pretty basic in this regard, but I can get a list of all files in the directory and filter them by whatever follows "*".     Its slightly harder to support general wildcard patterns.

**Comment by sjackman** [comment]
IGV doesn't need to expand the wildcard patterns. That part is handled by the shell. The feature request here is to support filenames separated by spaces rather than commas. Currently `igv -g genome.fa track1.bam,track2.bam,track3.bam` does work, but `igv -g genome.fa track1.bam track2.bam track3.bam` does not work. The latter is important (to me anyway) because the shell expands `igv -g genome.fa *.bam` to `igv -g genome.fa track1.bam track2.bam track3.bam`.

IGV currently supports `igv -g genome.fa track.bam LOCUS`. I suggest specifying the region with an option (perhaps `-r` for region or `-l` locus).

For backward compatibility, when IGV is invoked with two arguments `igv -g genome.fa ARG1 ARG2`, if ARG2 exists on disk, assume it's a filename, and if it does not but is a valid locus in the genome, assume it's a locus, and if neither, produce an error message.

**Comment by jrobinso** [comment]
What is driving the use case to support space separated files?   I've implemented support for wildcard patterns,  e.g.   *.bam,  I will be pushing that shortly.    Its a much simpler solution than what you propose.

**Comment by jrobinso** [comment]
It sounds simple, but its complex, 2 delimiters now instead of 1,  2 possible meanings for last arg.  This kind of change has a high % chance of introducing an edge case bug.

**Comment by jrobinso** [comment]
I like your suggestion, its more rational,  just 8 years too late.   I'll reopen this and assign it to release 2.5,  which will be a major feature release.   In the meantime wildcards are supported now,  so  *.bam will work,  as will  /path/to/datafiles/*.bam.    However /path*/*.bam will not work -- wildcard is only supported in the filename part of the path.

**Comment by jrobinso** [comment]
I haven't had to quote, testing on MacOS,  what happens if you don't quote it?

**Comment by sjackman** [comment]
Are you testing on Microsoft Windows, and if so, with which shell?
Both Linux and macOS should behave the same.
With two BED files in the current working directory named `one.bed` and `two.bed`.
```
❯❯❯ igv -g genome.fa *.bed
…
Cannot find feature or locus: two.bed
```
You can use `echo` to see how the shell globs for you.
```
❯❯❯ echo igv -g genome.fa *.bed
igv -g genome.fa one.bed two.bed
```

**Comment by jrobinso** [comment]
OK,  I was running from my IDE (Intellij).   When I test directly from the command line I see the error that you get.   I thought the 2 were equivalent, but obviously not.   Will look into it.

**Comment by sjackman** [comment]
Thanks again, Jim!

**Comment by jrobinso** [comment]
I pushed a change to accept space delimited file lists, and removed the wildcard option.   I would prefer the OS handle that.   However, my shell (MacOS) does not expand  *.bed by default.    That's o.k. with me, just noting it.

**Comment by jrobinso** [comment]
Pushed space delimited file list,  removed wildcard option, see commit 7e32ff104f95a10bca862a34e27474473754c43a

**Comment by sjackman** [comment]
Thank you, Jim! How does one specify say three files and a locus?

**Comment by jrobinso** [comment]
Use -l, or --locus.   Your suggestion I think.

**Comment by jrobinso** [comment]
If you can test this a bit, using old and new styles (comma and space delimited) it would be helpful.

**Comment by sjackman** [comment]
Hi, Jim. When I launch the daily IGV snapshot with `igv -f genome.fa track.bed` I get the error message `Error parsing command line argments: Unknown option '-f'`. There's also a typo in `argments`.

**Comment by sjackman** [comment]
The option is `-g` not `-f`. I don't where where my brain went this morning. At least I found the typo!

**Comment by sjackman** [comment]
This feature works fantastically, and has greatly improved my IGV user experience from the command line! `igv -g genome.fa *.bam` works like a charm. Thank you, Jim!
