### ISSUE TITLE
Track names passed using URL that include '+' not displaying properly

### ISSUE THREAD

**Issue by jacp1** [igvteam/igv#433]
I am using control via URL on port 60151 to add tracks to an IGV session, these tracks are supplied via a web server using https. The URL I use looks similar to the below:

http://localhost:60151/load?file=https://serverpathhere/results/Hip_GeneA%2B%2BGeneB%2B%2B/Hip_GeneA%2B%2BGeneB%2B%2B.genome.tdf

The track names include '+' characters.  In order to get this to load at all I have to use URI escaping, so each '+' is represented by a '%2B'. This works fine except that the track names in IGV display the '+' symbols as spaces - although if you hover over the track name the tool tip which displays the full path displays it correctly, having converted the %2B back to '+' as expected. This is a problem in that my track names are in some cases identical except for '+', '++' and '+++' and it is impossible to tell these apart in the display. 

Saving the session shows that the 'name' attribute has been incorrectly generated from the URL - I've attached a similar session XML below (partly obfuscated) showing resource 'geneA+' appears as 'geneA ' in the panel name.

[igv_session.txt](https://github.com/igvteam/igv/files/1091389/igv_session.txt)

**Comment by jrobinso** [comment]
What version of IGV are you using?

**Comment by jacp1** [comment]
2.3.90, but I also tested 2.3.94 and 3.0beta and got the same thing.

**Comment by jrobinso** [comment]
So its the displayed name that is the problem,  the resource loads.   Its normal that you would have to URI encode this,  I will look into the name parsing.

**Comment by jacp1** [comment]
Yes, that is correct - thanks very much for looking at this.

**Comment by jrobinso** [comment]
It should be fixed in 3.0 beta by the evening, and next point release of 2.3.X

**Comment by jacp1** [comment]
I can confirm that it is now working for me in 3.0beta Thanks for the fix!
