### ISSUE TITLE
Cannot able to make use of igv.removeTrack() i can able to access data from JSON correctly

### ISSUE THREAD

**Issue by shivangsoni** [igvteam/igv#441]
<b>On using a piece of code couldnot able to remove all tracks on button click</b>
var obj ;
var track1;
var track2;
var json;
function loadJSON(callback) {
    var xobj = new XMLHttpRequest();
    xobj.overrideMimeType("application/json");
    xobj.open('GET', 'tracks_DNA.json', true);
    xobj.onreadystatechange = function() {
        if (xobj.readyState == 4 && xobj.status == "200") {
            // .open will NOT return a value but simply returns undefined in async mode so use a callback
            callback(xobj.responseText);
        }
    }
    xobj.send(null);
}
// Call to function with anonymous callback
loadJSON(function(response) {
    // Do Something with the response e.g.
    //jsonresponse = JSON.parse(response);
    // Assuming json data is wrapped in square brackets as Drew suggests
    //console.log(jsonresponse[0].name);
   json=response;
   obj = JSON.parse(json);
      track1=obj.tracks[0].url;
   track2=obj.tracks[0].cutoffscore;
   //alert(obj.showRuler);  
   var div = $("#igvDiv")[0],obj;
   <b>igv.Browser.prototype.removeTrack(obj.tracks);</b>
   //igv.Browser.prototype.igv.browser.removeAllTracksremoveTrack(obj.tracks[1])
});

<b>Error Report</b>
<b>Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.igv.Browser.removeTrack (igv.js:4956)
    at bam.html:119
    at XMLHttpRequest.xobj.onreadystatechange (bam.html:102)
</b>
Can anyone please help me with this

**Comment by jrobinso** [comment]
Hi, sorry but this is a bit of a mess.  You are mixing some of your own code with igv.js,  so there is no way I can reproduce this with what you have posted.  Also,  this call makes no sense whatsoever 

 igv.Browser.prototype.removeTrack(obj.tracks);

If you can create a test case that I can run I will look at it.   Open a new issue with test case in the igv.js repository,  this is the wrong repository in any event (this is the IGV desktop repository).
