### ISSUE TITLE
IOPS

### ISSUE THREAD

**Issue by Martulie** [igvteam/igv#443]
Dear colegues,
we plan to buy a NAS for data storage plus we would like to check the data from it directly in IGV. Task from our informatician was How many IOPS should have the disk so we can comfortably go through the data? I have no idea how IGV works. Could you please help me in this case?

Thank you very much,
Martina

**Comment by jrobinso** [comment]
Network storage is not my expertise.   Could you be more specific with your
question?  IGV is a desktop program that reads data from files.
