### ISSUE TITLE
Track view commands (squish/expand) via port. Target specific tracks?

### ISSUE THREAD

**Issue by ranasats** [igvteam/igv#444]
Hey,

I'm sending track commands via the port command feature, but whenever I send a track view command like squish, it squishes all loaded tracks. Is there any way I can squish only the bam files, not any target/probes files?

Thanks.

**Comment by jrobinso** [comment]
You can add a track name as an argument after "squish".   It should match the display name of the track,  if you haven't otherwise named it in a session file that will be the filename (not the full path).   You'll have to do this for each track you want to squish individually.

**Comment by jrobinso** [comment]
Old thread, but for the benefit of anyone who finds it here is an example

```
load https://1000genomes.s3.amazonaws.com/phase3/data/HG01883/alignment/HG01883.mapped.ILLUMINA.bwa.ACB.low_coverage.20130415.bam
load https://1000genomes.s3.amazonaws.com/phase3/data/HG01879/alignment/HG01879.mapped.ILLUMINA.bwa.ACB.low_coverage.20120522.bam
goto myc
squish HG01879.mapped.ILLUMINA.bwa.ACB.low_coverage.20120522.bam
```
