### ISSUE TITLE
Error loading genome: java.security.cert.CertificateException

### ISSUE THREAD

**Issue by lucacozzuto** [igvteam/igv#445]
Dear developers,
I'm having the following error when trying to use this remote file for being used as a reference genome.

"Error loading genome: java.security.cert.CertificateException: Illegal given domain name: public_docs.crg.es"

Link to the file
https://public_docs.crg.es/biocore/lcozzuto/genome/references.fa
(In that path I also have the *.fai index)
However the certificate seems ok and the IT told me that there is no problem with it.

Can you help me, please?

thanks!

**Comment by jrobinso** [comment]
What version of IGV are you using?  I was able to load it using "Genome >
Load from URL" with no errors.

**Comment by lucacozzuto** [comment]
I'm using the mac version IGV_2.3.97

**Comment by jrobinso** [comment]
OK I reproduced this problem.  Strangely it occurs with the packaged
mac app, or the jnlp file, but not the binary distribution.    Until I can
find the problem I suggest you try the binary distribution.   You can
download it here:
http://data.broadinstitute.org/igv/projects/downloads/IGV_2.3.97.zip.
After unzipping, right click the  "igv.command" file and select "Open With
> Terminal".

**Comment by lucacozzuto** [comment]
Many thanks! I tried but now I face another error:

Error loading genome: Received fatal alert: handshake_failure

Luca

**Comment by jrobinso** [comment]
I don't get that error.   Could you shutdown IGV,  then delete or move the
"igv.log" file and restart.   Try loading the genome again, shutdown,  and
attach the igv.log file (or paste its contents here)

**Comment by jrobinso** [comment]
Also,  could you try opening a terminal in the directory with the "igv.command" file and starting with the following command line?   Then attach the contents of the "diag.txt" file here.   This should pinpoint the SSL problem

java -Xmx4000m  -Djavax.net.debug=all -jar igv.jar > diag.txt

**Comment by lucacozzuto** [comment]
Many thanks again. Here the latest 50 rows of the diag.txt file:

Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
AWT-EventQueue-0, setSoTimeout(180000) called
%% No cached client session
*** ClientHello, TLSv1
RandomCookie:  GMT: 1484999001 bytes = { 167, 194, 110, 156, 174, 83, 93, 93, 85, 221, 74, 114, 89, 253, 43, 90, 24, 172, 142, 151, 249, 253, 77, 198, 96, 173, 196, 33 }
Session ID:  {}
Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_SHA, TLS_ECDH_ECDSA_WITH_RC4_128_SHA, TLS_ECDH_RSA_WITH_RC4_128_SHA, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_RC4_128_MD5, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
Compression Methods:  { 0 }
Extension elliptic_curves, curve names: {secp256r1, sect163k1, sect163r2, secp192r1, secp224r1, sect233k1, sect233r1, sect283k1, sect283r1, secp384r1, sect409k1, sect409r1, secp521r1, sect571k1, sect571r1, secp160k1, secp160r1, secp160r2, sect163r1, secp192k1, sect193r1, sect193r2, secp224k1, sect239k1, secp256k1}
Extension ec_point_formats, formats: [uncompressed]
Extension server_name, server_name: [host_name: public_docs.crg.es]
***
[write] MD5 and SHA1 hashes:  len = 176
0000: 01 00 00 AC 03 01 59 83   49 59 A7 C2 6E 9C AE 53  ......Y.IY..n..S
0010: 5D 5D 55 DD 4A 72 59 FD   2B 5A 18 AC 8E 97 F9 FD  ]]U.JrY.+Z......
0020: 4D C6 60 AD C4 21 00 00   2A C0 09 C0 13 00 2F C0  M.`..!..*...../.
0030: 04 C0 0E 00 33 00 32 C0   07 C0 11 00 05 C0 02 C0  ....3.2.........
0040: 0C C0 08 C0 12 00 0A C0   03 C0 0D 00 16 00 13 00  ................
0050: 04 00 FF 01 00 00 59 00   0A 00 34 00 32 00 17 00  ......Y...4.2...
0060: 01 00 03 00 13 00 15 00   06 00 07 00 09 00 0A 00  ................
0070: 18 00 0B 00 0C 00 19 00   0D 00 0E 00 0F 00 10 00  ................
0080: 11 00 02 00 12 00 04 00   05 00 14 00 08 00 16 00  ................
0090: 0B 00 02 01 00 00 00 00   17 00 15 00 00 12 70 75  ..............pu
00A0: 62 6C 69 63 5F 64 6F 63   73 2E 63 72 67 2E 65 73  blic_docs.crg.es
AWT-EventQueue-0, WRITE: TLSv1 Handshake, length = 176
[Raw write]: length = 181
0000: 16 03 01 00 B0 01 00 00   AC 03 01 59 83 49 59 A7  ...........Y.IY.
0010: C2 6E 9C AE 53 5D 5D 55   DD 4A 72 59 FD 2B 5A 18  .n..S]]U.JrY.+Z.
0020: AC 8E 97 F9 FD 4D C6 60   AD C4 21 00 00 2A C0 09  .....M.`..!..*..
0030: C0 13 00 2F C0 04 C0 0E   00 33 00 32 C0 07 C0 11  .../.....3.2....
0040: 00 05 C0 02 C0 0C C0 08   C0 12 00 0A C0 03 C0 0D  ................
0050: 00 16 00 13 00 04 00 FF   01 00 00 59 00 0A 00 34  ...........Y...4
0060: 00 32 00 17 00 01 00 03   00 13 00 15 00 06 00 07  .2..............
0070: 00 09 00 0A 00 18 00 0B   00 0C 00 19 00 0D 00 0E  ................
0080: 00 0F 00 10 00 11 00 02   00 12 00 04 00 05 00 14  ................
0090: 00 08 00 16 00 0B 00 02   01 00 00 00 00 17 00 15  ................
00A0: 00 00 12 70 75 62 6C 69   63 5F 64 6F 63 73 2E 63  ...public_docs.c
00B0: 72 67 2E 65 73                                     rg.es
[Raw read]: length = 5
0000: 15 03 01 00 02                                     .....
[Raw read]: length = 2
0000: 02 28                                              .(
AWT-EventQueue-0, READ: TLSv1 Alert, length = 2
AWT-EventQueue-0, RECV TLSv1 ALERT:  fatal, handshake_failure
AWT-EventQueue-0, called closeSocket()
AWT-EventQueue-0, handling exception: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
INFO [2017-08-03 18:03:37,605]  [MessageUtils.java:74] [AWT-EventQueue-0]  Error loading genome: Received fatal alert: handshake_failure
INFO [2017-08-03 18:03:42,986]  [ShutdownThread.java:51] [Thread-3]  Shutting down

**Comment by jrobinso** [comment]
Could you attach more of the file, or zip and attach both files (igv.log
and diag.txt)?  If you don't want to post it here you can email it to
igvteam    (at)    broadinstitute.org.

One difference I have noticed,  in your output  "TLSv1"  is being used,  in
mine it indicates  "TLSv1.2".     Does the server have a requirement for a
particular version?   Are you running the latest Java release?

**Comment by lucacozzuto** [comment]
I don't know if is useful but I tried also from a Linux machine and I got the same error I had at the beginning. 

Luca
here the diag file
[diag.txt.zip](https://github.com/igvteam/igv/files/1197872/diag.txt.zip)

**Comment by jrobinso** [comment]
Its difficult because I can't reproduce the error from the command line or
 "igv.command",  everything works beautifully.

**Comment by jrobinso** [comment]
What version of Java are you using?  This is important.

**Comment by lucacozzuto** [comment]
On 03/08/2017 18:29, Jim Robinson wrote:
My version is Java 8 Update 144. The recommend version.

Luca

**Comment by jrobinso** [comment]
Your output indicates your client is using TLSv1.   My java client is using
TLSv1.2.   Java 8 should use TLSv1.2 by default unless you have configured
it differently.   I am successfully loading the fasta,  it could be the TLS
version difference.

Do you know what version the server uses?

**Comment by jrobinso** [comment]
Do you know if the server is using "Server Name Indication"?   

Also,  please find out if you can why your client is using TLSv1.   It should not with Java 8.

**Comment by jrobinso** [comment]
OK,  this is not my area of expertise so I am learning a lot.   A Java SSL class is rejecting the host name public_docs.crg.es because it contains an underscore.   This is not allowed for host names, host names can only contain letters, digits, and the minus sign (hyphen).  See https://tools.ietf.org/html/rfc952.    Obviously, the name exists and mostly works, but it is not legal and the Java 8 security classes are strict.   Because the host name is illegal Java is not sending it with the "server name extension" in the handshake and I think that is why it is failing.    Is it possible that the provider could use only legal host names?   If not I will try to find some way to work around this,  but I'm not sure if that is possible.

**Comment by jrobinso** [comment]
I am now able to reproduce your problem by forcing Java to use TLSv1.   I can load the genome with TLSv1.2 from the command line.  So access to that server requires at least TLSv1.2.  

I don't know why your client uses TLSv1,  Java 8 uses TLSv1.2 by default.   This would be a question for your system administrators.   You can try forcing the use of TLSv1.2 by adding the following at the command line:   -Dhttps.protocols="TLSv1.2".   So for example

java -Xmx4000m  -Djavax.net.debug=all -Dhttps.protocols="TLSv1.2"  -jar igv.jar

If its successful you should see the following in the output

ClientHello, TLSv1.2

There is still the warning about hostname,  this is due to the non-LDH character (the underscore) in the name.  This does not prevent loading when running from the command line but possibly is the problem when running from the mac app bundle.   It should be addressed, but obviously, that is not in your control.

"public_docs.crg.es" is not a legal HostName for  server name indication

**Comment by jrobinso** [comment]
If this works you should remove the -Djavax.net.debug=all for future use, it will slow down the application.

**Comment by lucacozzuto** [comment]
Many thanks! I forward this mail to my IT. I'll keep you posted

Luca

Il 04 ago 2017 5:08 PM, "Jim Robinson" <notifications@github.com> ha
scritto:

If this works you should remove the -Djavax.net.debug=all for future use,
it will slow down the application.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/igvteam/igv/issues/445#issuecomment-320273519>, or mute
the thread
