### ISSUE TITLE
Feature request: adding group command to "Controlling IGV through a Port" functionality

### ISSUE THREAD

**Issue by StefanDettenhofer** [igvteam/igv#449]
I am using IGV-viewer by controlling through port for loading data, goto locus, sort, ... but I am missing functionality for grouping data.
In the specific case I would like to send "group alignments by" -> "read strand" through port automatically.

I had a look into prefs.properties and there is an entry "SAM.GROUP_OPTION=STRAND" but this does not do anything for group alignments. 
I'm using IVG Viewer version 2.3.92

**Comment by jrobinso** [comment]
Hi, apologies for the long delay, this was implemented some time ago but the git issue did not get updated.  See the following example. 

```
load https://1000genomes.s3.amazonaws.com/phase3/data/HG01879/alignment/HG01879.mapped.ILLUMINA.bwa.ACB.low_coverage.20120522.bam
goto chr8:128,749,315
group STRAND
sort BASE chr8:128,749,315
```
