### ISSUE TITLE
JavaAppLauncher: UnknownSuboptionException

### ISSUE THREAD

**Issue by sjackman** [igvteam/igv#454]
I've installed the macOS IGV.app (2.3.98). I'd like to launch IGV from the command line. I ran…
```sh
~/Applications/IGV_2.3.98.app//Contents/MacOS/JavaAppLauncher
```
IGV started, but I got the following error on the console:
```
jargs.gnu.CmdLineParser$UnknownSuboptionException: Illegal option: 'X' in '-Xmx4g'
	at jargs.gnu.CmdLineParser.parse(CmdLineParser.java:462)
	at jargs.gnu.CmdLineParser.parse(CmdLineParser.java:426)
	at org.broad.igv.ui.Main$IGVArgs.parseArgs(Main.java:435)
	at org.broad.igv.ui.Main$IGVArgs.<init>(Main.java:413)
	at org.broad.igv.ui.Main.main(Main.java:83)
```
It looks as though the option `-Xmx4g` is intended for the `java` executable, but is instead being interpreted by IGV.

**Comment by cschin** [comment]
why not just "open ~/Applications/IGV_2.3.98.app"

**Comment by sjackman** [comment]
It seems that the `IGV.app` does not interpret its command line arguments.
```sh
open ~/Applications/IGV_2.3.98.app --args -g genome.fa bwa.bam
```
does not open the request genome file or BAM file.

**Comment by cschin** [comment]
I see. Well, I guess it will need some OS X packaging expert to know how to pass those through OS X app bundling system...

**Comment by cschin** [comment]
` open [-e] [-t] [-f] [-F] [-W] [-R] [-n] [-g] [-h] [-s sdk] [-b bundle_identifier] [-a application] file ... [--args arg1 ...]`

try `man open`. the `--args` option might work

**Comment by sjackman** [comment]
> the `--args` option might work

I had already tried it above https://github.com/igvteam/igv/issues/454#issuecomment-324717614
😄

**Comment by jrobinso** [comment]
As far as I know you can't use the JavaAppLauncher like that,  if you want to run from the command line with arguments just run the igv.jar file in the usual manner.    The mac app bundle is not intended for this.

**Comment by sjackman** [comment]
Okay. Thanks for the clarification, Jim.
