### ISSUE TITLE
Weirdest proxy setting bug with IGV on Windows when installing on network drives

### ISSUE THREAD

**Issue by holtgrewe** [igvteam/igv#456]
I just want to report the following super-weird issue that happened to me. It might be specific to our hospital Windows setup, but maybe someone else stumbles over it and can save some hours of debugging.

Here it comes:

- We have a Windows 7 setup in the university hospital, meaning centrally administrated in an "enterprise software" setup setting. Maybe there are certain policies setup regarding Java and network drives. I don't know and it's beyond my power to change or find out.
- I need to configure proxy settings and did so.
- I downloaded the "IGV Windows" package that includes the whole JRE.
- When extracting the package on a network share (my home turns out to be on a network share), the proxy configuration is not read properly for some reason and IGV does not work (of course!)
- When copying the same files to a local disk (here `C:`), proxy settings are read properly and IGV works.

I have no clue why this is the case but anyway, maybe this is helpful to anyone.

**Comment by holtgrewe** [comment]
Closing as I just want to leave this here for someone hitting the same problem. I don't know whether it's an IGV, Java or Windows issues...

**Comment by jrobinso** [comment]
I don't know either, but did you try setting the proxy settings in IGV itself via the Preferrences window?  Sometimes Java picks up Proxy settings from the right place,  sometimes it doesn't,   so I added the explicit settings.
