### ISSUE TITLE
No font antialiasing by default on Linux

### ISSUE THREAD

**Issue by nick863** [igvteam/igv#460]
The fonts are not looking good in the IGV on Linux. This problem is connected with the fact that anti aliasing is switched off by default.
The problem may be solved by addition of 
-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true 
to the igv.sh file.

11a12
> 	-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true \

**Comment by jrobinso** [comment]
Thanks,  I'll make that the default.    They were switched off in an attempt to improve performance with remote X Windows.   It did not help much.   I don't use Linux and had forgotten about this.

**Comment by jrobinso** [comment]
Actually this is more complex than it  used to be,  see https://wiki.archlinux.org/index.php/Java_Runtime_Environment_fonts

**Comment by nick863** [comment]
For me it works with OpenJDK 1.7.0_09-icedtea.

**Comment by jrobinso** [comment]
@davideby ,  sorry, where is the PR?

**Comment by davideby** [comment]
@jrobinso , I wrapped it up along with that JAXB fix, so you've already merged it.

Sorry, probably should have done that separately.
