### ISSUE TITLE
Feature request: Improvements on the chromosome dropdown list

### ISSUE THREAD

**Issue by cmacprobst** [igvteam/igv#465]
I am working with a genome that has 1,030 contigs, numerically labelled. When I access the dropdown menu for "Select a chromosome to view", the order is changed and it is difficult to find the desired contig.

I presume that this order has some rule (a hash?) but it is annoying when working with the scenario mentioned above. Perhaps an option to sort or not the "chromosomes" in the view->preferences.

Also, that this dropdown menu could be transformed in a dropdow with a option to type (with word search) the element you are looking after. So, you could browse the list (as now) and also type (or copy/paste) your element of search.

**Comment by jrobinso** [comment]
You can just type the contig name you want in the "go" box.
