### ISSUE TITLE
Issue loading IGV 2.4 on Windows 10

### ISSUE THREAD

**Issue by gabbs414** [igvteam/igv#467]
Hi, I have downloaded the Java version 8 as well as the IGV browser for binary distribution. I tried to open the igv.bat file for Windows (I am running Windows 10) and I got the following message in my command window:

C:\WINDOWS\system32>for %x in ("C:\Users\gabbs\igv\IGV_2.4.1\igv.bat") do set BatchPath=%~dpsx

C:\WINDOWS\system32>set BatchPath=C:\Users\gabbs\igv\IGV_24~1.1\

C:\WINDOWS\system32>for %x in (C:\Users\gabbs\igv\IGV_24~1.1\) do set BatchPath=%~dpsx

C:\WINDOWS\system32>set BatchPath=C:\Users\gabbs\igv\IGV_24~1.1\

C:\WINDOWS\system32>java  -Xmx1200m -Dproduction=true -Djava.net.preferIPv4Stack=true -Dsun.java2d.noddraw=true -jar C:\Users\gabbs\igv\IGV_24~1.1\\igv.jar
WARN [2017-09-28 21:28:45,544]  [Globals.java:138] [AWT-EventQueue-0]  Development mode is enabled
INFO [2017-09-28 21:28:45,569]  [DirectoryManager.java:76] [AWT-EventQueue-0]  Fetching user directory...
INFO [2017-09-28 21:28:45,569] [DirectoryManager.java:76]  Fetching user directory...
INFO [2017-09-28 21:28:45,629]  [DirectoryManager.java:171] [AWT-EventQueue-0]  IGV Directory: C:\Users\gabbs\igv
INFO [2017-09-28 21:28:45,629] [DirectoryManager.java:171]  IGV Directory: C:\Users\gabbs\igv
INFO [2017-09-28 21:28:45,634]  [Main.java:154] [AWT-EventQueue-0]  Startup  IGV Version 2.4.1 09/25/2017 11:46 AM
INFO [2017-09-28 21:28:45,634]  [Main.java:155] [AWT-EventQueue-0]  Java 1.8.0_144
INFO [2017-09-28 21:28:45,634]  [Main.java:156] [AWT-EventQueue-0]  Default User Directory: C:\Users\gabbs\Documents
INFO [2017-09-28 21:28:45,635]  [Main.java:157] [AWT-EventQueue-0]  OS: Windows 10

INFO [2017-09-28 21:29:03,634]  [GenomeManager.java:190] [pool-3-thread-1]  Loading genome: http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome
INFO [2017-09-28 21:29:05,039]  [CommandListener.java:120] [Thread-7]  Listening on port 60151

The main problem is that when IGV loads, hg19 is listed as the genome, but there are no genes in the bottom row and the drop-down menu for chromosomes is blank. Any ideas?

**Comment by jrobinso** [comment]
When IGV started did you get any dialogs wrt the windows firewall, and if so did you grant permissions?

Try shutting down IGV, then downloading the genome manually from http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome and saving it in the c:\Users\gabbs\igv\genomes folder, replacing the current copy if it exists

**Comment by jrobinso** [comment]
Also, particularly if you had earlier versions of IGV,  try shutting down and renaming your "prefs.properties" file  (e.g. to prefs.bak) and restart.   If that solves the problem attaching your old prefs.properties file would be helpful for diagnosis.

**Comment by helgathorv** [comment]
We've managed to reproduce this problem. 
Until we can release a fix, try the following workaround: 
- go into the folder <username>/igv/genomes 
- You'll see the genome files are named <genomeid>.genome.download, e.g. hg19.genome.download
- Rename the file and remove the ".download" suffix, so that the name is <genomeid>.genome 
- restart IGV (or if you have multiple genomes in the dropdown menu you can just re-select the genome)

**Comment by helgathorv** [comment]
A fix was released today with IGV 2.4.2.
