### ISSUE TITLE
IGV jump to rsID location

### ISSUE THREAD

**Issue by avilella** [igvteam/igv#477]
https://bioinformatics.stackexchange.com/questions/2705/igv-jump-to-rsid-location

**Comment by helgathorv** [comment]
Released in IGV 2.8.0

**Comment by jrobinso** [comment]
@avilella We've encountered some problems with the ncbi webservice we were using to support this.  It worked fine in testing but now that it's released we are blocked.  So we're populating our own search database with snp locations to support this.   This will take a couple of days to complete.

**Comment by avilella** [comment]
Thanks, looking forward to it.

**Comment by jrobinso** [comment]
It's about 1/2 way through, its been running 12 hours,  so it should finish this evening.    This database will have the "common snps",  seen in > 1% of samples.  That's 15 million or so.  The entire database is now around 400 million and we won't be able to support that until and unless NCBI un-blocks us.

**Comment by helgathorv** [comment]
@avilella The dbSNP rsID search is working again in IGV, using our new database. It supports "common" and "flagged" SNPs in hg19 and hg38, and "common" SNPs in mm10. Let us know if you run into any problems using it.
