### ISSUE TITLE
Support displaying the seen allele frequency on a vcf for based on a different field apart from AF

### ISSUE THREAD

**Issue by duartemolha** [igvteam/igv#481]
Hi Guys

What I am asking here is that the allele frequency displayed on the VCF file be in line with the seen read depth of the reads that support each allele.

Right now the VCF just displays the number of alleles and assumes a frequency of 0.5
(please see attached screenshot). I assume this is because it reads the AF field

In the VCF, however, there are fields that indicate the true seen allele frequency for that sample .

One field AB gives the frequency seen for the minor allele. In this case 0.38
However, IGV used by default the AF field for displaying the frequency.  I know this because if I change the AF field to 0.38, IGV displays the value correctly

It would be good there was an option to force IGV to use another field for the frequency display... in this case AB.

![screenshot](https://user-images.githubusercontent.com/722005/32217612-748d9294-be20-11e7-8b0f-2106be1963d5.png)

**Comment by jrobinso** [comment]
This would be complicated to support.  AB is not a standard reserved field, so if I can rephrase your request it is to color the variant by a user-specified field.   We can probably do that, by letting you type in the field name,  but we have no way to know if its a fractional value or something else.   

Also,  allele frequency is the frequency of an allele in a population.  Its not really even correct to speak of an allele frequency in a single sample, it doesn't make sense.      To the extent that it does make sense 0.5 is the correct number in your example.    There are only 2 alleles listed (diploid),  and the variant caller has called this heterozygous.   The # of reads with each allele is just evidence and not the call. 

So to re-iterate the request is to color the variant by a user-specified attribute,  not to define another attribute to represent the allele frequency.   In other words color the variant by something other than allele frequency.

**Comment by duartemolha** [comment]
Ok... dont really understand very well what you mean with colour the variant. You mean show it with different colours instead of blue and read as in the screenshot?

**Comment by duartemolha** [comment]
Maybe I am using the wrong nomenclature.  But I agree AF should be the allele frequency in the population. SO it the VCF file contained 2 samples and one has AC and the other AA would the alelle frequency shown be C 0.25 and 0.75 A ? is this what you mean?

**Comment by duartemolha** [comment]
if by colouring you mean .. I could type in AB as my input field and the 2 colours reflect that value proportion that would be what I mean...

SO if I choose AB field the VCF colours would have roughly the save proportion colours of the BAM coverage track above it.

Why I think this is interesting is for the analysis of for example cancer samples... where the cancer heterogeneity might mean that that a variant is only present in a small proportion of the cancer library... so the frequency I would like displayed is the frequency of the reads that support that mutation not based on a diploid model.

**Comment by jrobinso** [comment]
Yes,  I meant specifying another field to use for the frequency to allocate
the proportion.  Sorry I wasn't clear.   This would not be allele
frequency,  I'm not sure that what you describe has a name but it wouldn't
have to be named.
