### ISSUE TITLE
idxsession track colouring

### ISSUE THREAD

**Issue by avilella** [igvteam/igv#482]
Hi,

Is there a way to define the colouring of the tracks in an idxsession file?

**Comment by jrobinso** [comment]
That's an excellent question,  I had to do some investigation to see what an "idxsession" file is.   It looks like some code was contributed for this format in 2015 but I don't know what it is used for,  or even have a sample file.   Could you elaborate on that, and if you have a sample idxsession file attach it?   If you have a pointer to documentation for the format that would be helpful as well.     

It looks like you can specify a UCSC style track line in the file,  which would allow you to set color,  but at this point I'm guessing.

**Comment by avilella** [comment]
I originally found out about idxsession files via DNAnexus:

https://wiki.dnanexus.com/Guides/Using-IGV-with-DNAnexus

What could I try in regards to colouring?

**Comment by avilella** [comment]
I can confirm I can add lines like the one below before each of my file lines, and it will change the colour and name of the track:
```
track name=spacer description="Blue ticks every 10000 bases" color=0,0,255,
```

**Comment by jrobinso** [comment]
Ahh yes, thanks for the reminder.   DNANexus contributed that.    We will
add a pointer to their documentation from ours.

**Comment by jrobinso** [comment]
BTW,  this is a DNAnexus specific feature as you noted,  although anyone
could create and use this session file type.   If you are a DNAnexus
customer perhaps you could alert them to this and they can add it to their
documentation.
