### ISSUE TITLE
Neither genome.fa or aligned_read.bam will load on IGV.2.4.3 running on Windows 10.

### ISSUE THREAD

**Issue by madzayasodara** [igvteam/igv#484]
Hi
I'm working with v.2.4.3 on Windows 10, and trying to load a .fa genome file taeGut2. The file seems to be ok and I have its .fai in the same folder, but the program will act like it has loaded the genome but nothing happens. 
Same thing happens for sorted .bam files with corresponding .bai in the same folder. The program will act like it has loaded but nothing happens.
thanks! -madza

**Comment by madzayasodara** [comment]
I've decided generating a .genome from my .fa, and run from the binaries and it worked.
It did give me two warnings. 
One about running with low memory. How could I increase the memory allocated to the program?
and another:
Nov 02, 2017 11:59:00 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Should I worry about this one?
thanks

**Comment by jrobinso** [comment]
How are you launching the binary program?  You can't just double click the
jar,  you need to use one of the bat or shell script files or equivalent.
 You can increase memory by changing the value of the -XmX tag in those
files.

We haven't had any other reports of fasta files not being loaded on Windows
10,  and I can't reproduce the problem.    How did you load the fasta file
(what menu options did you use)?   Can you include the contents of your
igv.log file?

**Comment by davideby** [comment]
The "Windows RegCreateKeyEx(...)" error is [a known bug in Java 8](https://bugs.openjdk.java.net/browse/JDK-8139507) itself, but that the message is just a warning and shouldn't affect anything.  It should only happen on clean installations, meaning a Windows computer where Java had never been installed before (either Java 8 or any earlier versions).   You should be able to safely ignore this message

If the warning really bothers you, there is [an apparent fix](https://stackoverflow.com/a/17552837) that should make it go away.  It involves editing the Windows Registry, so if you're not comfortable with that then I'd recommend ignoring it. 

I'll leave the memory question to Jim.

**Comment by madzayasodara** [comment]
Hi, 
thank you for your responses. 
I was able to load taeGut2.fa as well as my aligned reads, however because I do need to look at specific genes, I generated a .genome using the same genome and gtf file I used to align then. The program correctly generates and loads .genome, but it acts like it has loaded the sorted.bam but nothing happens. 
The .genome file has been generated using:
.fa file (from ncbi) and its corresponding .fai
```
>chr1
aaattaaaattaaaatcatagcataaaaatcaaaaatttaaaattaaaat
taaaagtaaaattaaaattaaaacaaaaattaaaattaaaattaaaatta
aaattaaaattaaaattaaaattaaaaagtaaaattaaagctaaaaatta
aaattaaaatGTGATACTTTCCACTTTATGGGAGGAAAACATGGCCAAAA
TGAAAGAGCAGCCTAGAGAATAAGAGCATTCCTTGTGACTCTGTGGCCCC
```
plus this gtf (converted from the gff3 from ncbi) file:
```
NC_007897.1     RefSeq  exon    1       70      .       +       .       transcript_id "rna21331";
NC_007897.1     RefSeq  exon    71      1049    .       +       .       transcript_id "rna21332";
NC_007897.1     RefSeq  exon    1050    1119    .       +       .       transcript_id "rna21333";
NC_007897.1     RefSeq  exon    1120    2713    .       +       .       transcript_id "rna21334";
NC_007897.1     RefSeq  exon    2714    2788    .       +       .       transcript_id "rna21335";
NC_007897.1     RefSeq  CDS     2801    3778    .       +       0       transcript_id "gene17856"; gene_id "gene17856"; gene_name "ND1";
NC_007897.1     RefSeq  exon    3784    3856    .       +       .       transcript_id "rna21336";
```
The bam file looks like (I have the .bai files there):
```
SN860:669:C8F8HACXX:8:2316:21183:100805.firstrun.1      99      chr4    20951524        1       50M     =       20964458        126     AAAAACAGTGTTTTGGGGTAAAGGATTTTCAAGGCCCACAAGTACAGCAC      BBBFFFFFFFFFFIIIIIFFFFBFFFFIIIIIBFF7FFFIIFBFFFFFFF      AS:i:0  ZS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:50 YS:i:0  YT:Z:CP NH:i:2
SN860:669:C8F8HACXX:8:2316:21183:100805.firstrun.2      147     chr4    20964458        1       50M     =       20951524        -126    CCACGTAGTCCCCCAGGAAGAGGTACCGCGTGTTGGCAGGAGAACCTCCC      BFBFBBFIIIIFBIIIIIIIIIIFFBFFFIIIIFBIIFFFBFFBFFFB<<      AS:i:0  ZS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:50 YS:i:0  YT:Z:CP NH:i:2
SN860:669:C8F8HACXX:8:2316:21183:100805.firstrun.1      355     chr4    20951524        1       50M     =       20959751        126     AAAAACAGTGTTTTGGGGTAAAGGATTTTCAAGGCCCACAAGTACAGCAC      BBBFFFFFFFFFFIIIIIFFFFBFFFFIIIIIBFF7FFFIIFBFFFFFFF      AS:i:0  ZS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:50 YS:i:0  YT:Z:CP NH:i:2
SN860:669:C8F8HACXX:8:2316:21183:100805.firstrun.2      403     chr4    20959751        1       50M     =       20951524        -126    CCACGTAGTCCCCCAGGAAGAGGTACCGCGTGTTGGCAGGAGAACCTCCC      BFBFBBFIIIIFBIIIIIIIIIIFFBFFFIIIIFBIIFFFBFFBFFFB<<      AS:i:0  ZS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:50 YS:i:0  YT:Z:CP NH:i:2
```
Let me know if you guys have any idea of what might be happening. 
-madza

**Comment by jrobinso** [comment]
Hi,  I don't understand what you mean when you say "generate th e.genome using my gtf annotation".   What did you use for the fasta for the .genome file?  That is the relevant file, the gtf has no impact at all on the bam file.

BTW you gtf file is not compatible with the fasta snippet you post.  The sequence names are completely different  (chr1 vs NC_007897.1, etc).

Hi,   I don't think you should be creating a .genome file,  its not needed and is confusing the issue.  A gtf file is just a file of annotations, and can be loaded separately from the file menu.  It has no impact at all on the reference sequence, which is defined by the fasta file.     The only thing relevant to your bam file is the reference, which again is defined by the fasta.

**Comment by DarioS** [comment]
I can't load an RNA-seq BAM file with IGV 2.4.3 in Debian 8. The mouse pointer turns into a spinning circle, but nothing ever loads. `top` shows no increases in RAM or CPU utilisation. I have to use `pkill java` to force IGV to end. In contrast, I have kept IGV 2.3.98 in a nearby directory on the same server. The track loading successfully completes in about a second. I am executing with Java 8 both times.

**Comment by jrobinso** [comment]
@DarioS ,  could you open a separate issue for this?  I don't see any connection with this issue.

**Comment by DarioS** [comment]
It seems related to the issue's title. The original issue is about Windows 10 and I thought experiencing the issue using Debian 8 suggests that it's independent of the operating system.

**Comment by jrobinso** [comment]
We have 1,000s of successful windows launches per week,  so its not an OS
problem.

**Comment by madzayasodara** [comment]
Hi, 
I would like to visualize my aligned reads on annotated genome. So loading only my .fa file won't do it.
I tried now generating a .genome file using both my taeGut2.fa and .gtf from ensembl.
The .gtf file looks like 
```
chr2    ensembl gene    8262    11227   .       -       .       gene_id "ENSTGUG00000000041"; gene_version "1"; gene_source "ensembl"; gene_biotype "protein_coding";
chr2    ensembl transcript      8262    11227   .       -       .       gene_id "ENSTGUG00000000041"; gene_version "1"; transcript_id "ENSTGUT00000000039"; transcript_version "1"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding";
chr2    ensembl exon    10316   11227   .       -       .       gene_id "ENSTGUG00000000041"; gene_version "1"; transcript_id "ENSTGUT00000000039"; transcript_version "1"; exon_number "1"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSTGUE00000000333"; exon_version "1";
```
I am able to load the genome, but no annotation is present. 
I am also able to load the aligned reads.
How can I include annotation info so that I can inspect alignment for specific genes?
thanks

**Comment by jrobinso** [comment]
Just load the annotation file from the file menu,  you do not need a
.genome file.   First load your fasta from the genome,  then your files.
 That's it.   The .genome file is never required.

If the annotation is not showing up be sure that the sequence names in your
fasta file match the names in your annotation or bam file.

**Comment by madzayasodara** [comment]
Yes! That works. 
Btw, doing the .genome also works but for some reason searching for a gene or a locus will return "cannot find feature or locus". 
![2017-12-06](https://user-images.githubusercontent.com/22630874/33734954-baec318e-db42-11e7-987d-49e60bb3951d.png)
![2017-12-06 1](https://user-images.githubusercontent.com/22630874/33734956-bc6c14ca-db42-11e7-860e-2df32f0203d3.png)
Thanks

**Comment by jrobinso** [comment]
It can only search features based on names in the annotation track you have
loaded.   Is there a feature named KLHL3 in the annotation track?

Its sometimes useful to create a plain bed file with just the locations of
the features you want to search by,  by "plain" I mean with no exons,
introns or other details of the feature (to keep the file small).   After
loading it you will be able to search based on those names.
