### ISSUE TITLE
Memory leak during long batch script execution

### ISSUE THREAD

**Issue by rkostadi** [igvteam/igv#488]
Hi,

I'm running IGV with ~140 tracks, and have a batch script 
that goes to 20,000 regions and takes a snapshot at each of them.
I'm noticing that memory starts at about "212M of 1537M"
and during execution of the batch script
memory usage jumps by ~100-200 Mb every ~30-40 snapshots,
so in the end IGV crashes after ~about 1,000 png snapshots 
with out of memory (when it reaches ~3.5Gb).
If I increase the xmx parameter "java -Xmx4000m", perhaps it will crash after more than ~1,000 snapshots.

I was wondering if this could be solved by 
including a "clean memory" command within the batch script that the user provides 
(a temporary fix, the clean memory command will force a garbage collector cleanup)
or to try to trace where the memory leak occurs in long batch scripts.

What do you think?
Best regards,
rkostadi

**Comment by jrobinso** [comment]
Forcing a GC won't solve anything,  if there's a memory leak the leaked objects won't be GCed.     The most realistic solution for this in the short term is to limit the number of regions per batch run.
