### ISSUE TITLE
Depth track for a PAF track

### ISSUE THREAD

**Issue by sjackman** [igvteam/igv#490]
A BAM track has an associated depth track by default. Could a PAF track also have a depth track?

**Comment by sjackman** [comment]
Thanks for the PAF support!

**Comment by jrobinso** [comment]
Maybe PAF should be treated as alignments.   In the meantime, you can make one with igvtools,  use "count".   You can output a wig instead of a tdf if you want, give the output a wig extension.

**Comment by sjackman** [comment]
Thanks, Jim.
