### ISSUE TITLE
Group alignments with the same query name

### ISSUE THREAD

**Issue by sjackman** [igvteam/igv#491]
I'm looking at a PAF file of nanopore reads aligned to a genome assembly. There's a gap in the assembly (10 Ns). No alignments span this gap. However, there's one read (`53993a10`) that spans the gap (see the screenshot below). It'd be awesome if the alignments that I'm looking at could be grouped by query name, like paired-end reads are.

![igv_snapshot](https://user-images.githubusercontent.com/291551/33148240-f079a1e8-cf7f-11e7-82f2-03152fd3c8c8.png)

**Comment by jrobinso** [comment]
The only way this can happen is to make PAF files an alignment format,  as
opposed to a "feature" format.    So the tracks will look like bam tracks,
etc.    I will consider this a request to do so.

**Comment by sjackman** [comment]
That makes sense. Thanks, Jim.

**Comment by jrobinso** [comment]
Sorry @sjackman I have to get the # of open issues down to a tractable number, particularly as I have 2 other projects that are just as demanding as this one.   Can't do everything.    I will be bulk closing other issues,  trying to pick out the top 20 or so.

**Comment by sjackman** [comment]
No worries, Jim. I understand having to triage and cull issues for sure. I use Probot/Stale for this purpose. It's quite easy to enable it for a repo: https://probot.github.io/apps/stale/
It comments on an issue when it hasn't been touched in a couple weeks, and then closes the issue a couple of weeks later. I find that I don't feel guilty closing stale issues when a robot does it for me. You can label an issue as begin "in progress" if you don't want Stalebot to close it for you.

**Comment by sjackman** [comment]
Probot have lots of other useful GitHub robots, but I find Stalebot to be the most useful.

**Comment by jrobinso** [comment]
Thanks @sjackman ,  great tip about the bot!
