### ISSUE TITLE
Replace XML session format with json

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#492]
Replace the archaic and poorly documented JAXB based XML session format with an easy to read, well documented alternative compatible with igv.js.

Current candidate for format is json,  generated by Gson.

This issue is open for discussion by interested stakeholders.   Please join in if this is important to you.

**Comment by AMChalkie** [comment]
Nice idea. Would appreciate backward compatibility in this case (or a converter).

**Comment by jrobinso** [comment]
Yes,  backward compatibility is a given,  there are a lot of XML session
files out there.

**Comment by jrobinso** [comment]
Closed.  Duplicate of #589
