### ISSUE TITLE
Error when try to run bedtools on refseq genes track

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#498]
Select `Human hg18` genome.
Select `RefSeq genes` as an input track to any of the BEDTools commands 
=> you get an error similar to the following:
`Error: unable to open file or unable to determine types for file /var/folders/xx/fhy5vkjn4814p3t65f5s8fpjqnt3rq/T/features3255115436214173861.tmp`

**Comment by jrobinso** [comment]
This can't easily be fixed.   Our use of BEDTools only works for BED files, and
