### ISSUE TITLE
group autoscale is not preserved in session XML files

### ISSUE THREAD

**Issue by scottkall** [igvteam/igv#500]
following up from [this IGV-help post](https://groups.google.com/forum/#!searchin/igv-help/kallgren%7Csort:date/igv-help/97s7VEQRsdM/SZ3r7Ke_BgAJ):

I can't find a way to set up group autoscale in an IGV session XML file. Jim Robinson says: "Apparently (I just tried) ... group autoscale is not preserved in sessions.   This is a bug obviously,  I'm surprised it hasn't been reported before."

My system: IGV 2.4.3 in Mac OS 10.13.1

**Comment by scottkall** [comment]
Hope commenting like this isn't poor practice -- I just wanted to check in to see if there was any plan to knock this out. If not, I'll create my own or set user expectations.

**Comment by jrobinso** [comment]
I just pushed a fix for this.    The group identifier for autoscale is now a property of the track.   If creating the file manually the "autoScale" property must be set to false (that is,  set indpendent track autoscale off).   Example below

```
        <Track autoScale="false" autoscaleGroup="1" .... name="GM12878 H3K27me3"/>
        <Track autoScale="false" autoscaleGroup="1" ...  name="GM12878 H3K36me3"/>
```
