### ISSUE TITLE
Unable to load list of Google Storage and S3 bam files via control URL.

### ISSUE THREAD

**Issue by jfreidin** [igvteam/igv#501]
Hi,
I'm trying to control IGV via URL and tell it to load several bam files, which may either be in Google Storage, S3 or both.
Both cases work independently with the following caveat:
For Google Storage the URL must contain the file only in gs:// form.
For some reason, the `https://www.googleapis.com/storage/...` form doesn't work.
For S3 the URL must contain the signed URLs of both the bam file and its index (properly encoded).
The problem arises when I try to combine the two into a single URL, which requires file and index to be a matching list of comma-delimited file URLs.
If I specify the Google Storage index file, e.g.:
http://localhost:60151/load?genome=b37&file=gs%3A//project/data/file.bam&index=gs%3A//project/data/file.bam.bai
IGV reports an error:
```Error loading https://www.googleapis.com/storage/v1/b/project/o/data%2Ffile.bam?alt=media: An error occurred while accessing: https://www.googleapis.com/storage/v1/b/project/o/data%2Ffile.bam?alt=media Error loading BAM file: java.net.MalformedURLException: unknown protocol: gs```
If I omit the S3 index file, then IGV can't find it because the URL signature interferes with IGV's method of building the default URL to the bai file.

Since I cannot both specify and omit the index file (can I?) in the same link, these two limitations conspire to prevent this from working.
This is similar to https://github.com/igvteam/igv/issues/274 which was fixed a long time ago.

**Comment by jrobinso** [comment]
OK,  I'll look into it,  the error here is with the gs index file.     You
say you cannot use https://,   did you try including the ?alt=media
parameter?   That should work.    The URL alone without the parameter will
not.


As a workaround you could use a session file,  if that fits in your
workflow.

On Wed, Dec 27, 2017 at 12:55 PM, Jonathan Freidin <notifications@github.com

**Comment by jfreidin** [comment]
Thanks for you reply. I just tried https:// with ?alt=media as follows:
http://localhost:60151/load?genome=b37&alt=media&file=https%3A//storage.googleapis.com/bucket/subject.bam&index=https%3A//storage.googleapis.com/bucket/subject.bam.bai

IGV says "Loading ...", then after a long pause:
Error loading https://storage.googleapis.com/bucket/data/samples/subject.bam: An error occurred while accessing: https://storage.googleapis.com/bucket/data/samples/subject.bam Error loading BAM file: htsjdk.samtools.util.RuntimeEOFException: Premature EOF. Expected 4 but only received 0; BinaryCodec in readmode; streamed file (filename not available)

The https:// URL doesn't work in a browser either because:
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous users does not have storage.objects.get access to bucket/data/samples/subject.bam.
</Details>
</Error>

That's why I switched to using gs:// URLs.

I'm doing this in a web app.
I may improve this by switching to an javascript implementation that will handle the case where IGV isn't running more gracefully.
And then I could generate a session file on the fly and workaround this problem.

But allowing gs:// for the file, and not the index seems like a bug.

**Comment by jrobinso** [comment]
I just pushed a fox for the index bug.      BTW igv.js is intended to
replace the use of IGV desktop for web applications like this.    The
desktop URLs will continue to be supported,  but over time you might find
igv.js a better fit for webpages.

**Comment by jfreidin** [comment]
Thanks, Jim!
It seems like igv.js is fine for small bam files over a narrow range of loci.
But for large bam files of the sort we use, it appeared to be very much slower than the desktop app.
Is that a correct characterization?

**Comment by jrobinso** [comment]
I don't think that is correct as a generalization,  in testing we use some
very large BAMs.   There is no reason in principle for any performance
difference, both are client programs doing essentially the same thing.
IGV desktop has more features, but where features overlap igv.js should be
as fast or in some cases faster.

That said,  IGV desktop is more mature and there could be edge cases where
igv.js has a bug or penalty,  as those are found they are corrected.

**Comment by jrobinso** [comment]
I should add that our release is very out-of-date,  we are working to
correct that with a new release soon.    Until then,  the "test"
distribution is best for evaluations:  http://igv.org/web/test/

Also,  I'm working on supporting the same URL syntax as IGV desktop so that
existing websites can use it with minimal change,  basically changing
http://localhost:6051 to a URL to the page.    When that's ready you could
easily compare the 2.
