### ISSUE TITLE
autoscale group in sample metadata file no longer sets autoscale groups.

### ISSUE THREAD

**Issue by ThomasCarroll** [igvteam/igv#508]
hi, 

This issue is related to [a post I made on IGV google help](https://groups.google.com/forum/#!topic/igv-help/m7X04c5W69U).

I have been setting auto scale groups in a session metadata txt file for users and using this to set up-front the auto scale groups for different sets of data in one session. 
I had added this feature to our Bioconductor package in the last release.

I have noticed this has stopped working and my auto scale groups in sample metadata file are no longer being used.

Could this be to do with the recent update? https://github.com/igvteam/igv/issues/500

I am including a small test dataset here where I include the same artificial signal at different levels at the beginning 1000 bps of Chromosome 1.

[igv_Test.zip](https://github.com/igvteam/igv/files/1641408/igv_Test.zip)

When I open the XML session file igv_Test/igvfiles/Example.xml in 2.4.5 the data group autoscales. In 2.4.6 the data does not group autoscale.

Thank you for your help.

tom

**Comment by jrobinso** [comment]
Kudos for using the sample metadata.   We have, until now,  no real evidence anyone used this.    Looking into this now.

**Comment by jrobinso** [comment]
This is fixed and will be in the next point release (2.4.7).  If you need it earlier it will be in the nightly snapshot.      BTW the session had a  "genome.value" attribute set for the Global element.  This is not recognized and will be ignored,  the attribute name is just  "genome".
