### ISSUE TITLE
Can't use localhost links to open data in google storage

### ISSUE THREAD

**Issue by egafni** [igvteam/igv#509]
I get the following error when I try to load a cram file in google storage using this a http://localhost link

It works fine if I load from url manually.

Error loading https://www.googleapis.com/storage/v1/b/seq-data-us-1/o/bam%2F170907_AH3FMGDMXX_BH3CWCDMXX_BH3CW7DMXX_AH3CVVDMXX_BH3HYWDMXX_AH3HW2DMXX_BH3HTNDMXX_AH3HVMDMXX%2FS_10_I_10-10_CGACCATT-CGACCATT_S10.marked.cram?alt=media: An error occurred while accessing: https://www.googleapis.com/storage/v1/b/seq-data-us-1/o/bam%2F170907_AH3FMGDMXX_BH3CWCDMXX_BH3CW7DMXX_AH3CVVDMXX_BH3HYWDMXX_AH3HW2DMXX_BH3HTNDMXX_AH3HVMDMXX%2FS_10_I_10-10_CGACCATT-CGACCATT_S10.marked.cram?alt=media Error loading BAM file: java.net.MalformedURLException: unknown protocol: gs

**Comment by jrobinso** [comment]
Please specify an igv version when reporting an error.

**Comment by egafni** [comment]
IGV version 2.4.2

**Comment by jrobinso** [comment]
I think this has been fixed,  try the latest version (2.4.6).

**Comment by jrobinso** [comment]
I think this was fixed in release 2.4.6.

**Comment by egafni** [comment]
You're right, sorry about that!
