### ISSUE TITLE
DP (dot plot / pairing) format bug: arcs cross track boundaries

### ISSUE THREAD

**Issue by scottkall** [igvteam/igv#511]
I'm seeing a bug where large arcs from a DP (here converted to ".dp.bp") file (see [IGV-supported RNA Secondary Structure Formats](https://software.broadinstitute.org/software/igv/RNAsecStructure)) cross Track, but not Panel, boundaries. My hack solution is to separate the tracks into separate, necessarily differently-named Panels in the XML session file. Confirm this is a bug? See screenshot examples attached. Could you fix this?

I'm running IGV 2.4.6 on MacOS 10.13.3.

Here are the first four lines of the underlying .dp file:

```
1816
i	j	-log10(Probability)
6	37	1.62994
7	36	1.59094
```

And here are the first six lines (chromosome name redacted) of the corresponding, IGV-auto-converted .dp.bp file:

```
color:	255	204	0
color:	72	143	205
color:	81	184	72
nameRedacted	46	47	1811	1812	0
nameRedacted	92	93	105	106	0
nameRedacted	95	95	100	100	0
```
Bug example:

![igv_session_samepanel_bug_dp_bp](https://user-images.githubusercontent.com/3195509/35400199-209a2124-01c4-11e8-8742-38c863676ed1.jpg)

My hack: separate Panels:

![igv_session_namedpanels_separate_dp_bp](https://user-images.githubusercontent.com/3195509/35400220-27a70644-01c4-11e8-8f7e-3af26e15c7cc.jpg)

**Comment by jrobinso** [comment]
The only possible fix in the current architecture would be to truncate the arcs so they don't cross the boundary.   You would not get a scroll bar or other means to see the truncated arcs.   Is this what you are requesting?

**Comment by jrobinso** [comment]
In my forum response I suggested separate panels as you are doing because I thought that would give you scroll bars,  but I see from your screenshot that it does not.   That could also be considered a bug.

**Comment by jrobinso** [comment]
There are 2 potential fixes.   (1) just fix the arc renderer so it doesn't draw into other track spaces.   Arcs are truncated.  No scroll bar.   (2) automatically wrap arc tracks in new panels, as is done for bam files,  and also potentially add scroll bars if arcs are truncated.    Feedback on these?

**Comment by scottkall** [comment]
@jrobinso: My colleague working on this may comment himself further, but he said to me:

"I think solution 1 where the arcs are truncated and do not spill over into the next panel is fine. Most of the arcs are localized and a scientist familiar with this type of visualization would recognize arc going off the screen as sites of long-range interactions."

It sounds like solution 1 could be easier/faster to implement, too? If so, that would be great.

**Comment by jrobinso** [comment]
Yes, solution 1 is much easier.   I'll update here when fixed.

**Comment by jrobinso** [comment]
This should be fixed now in 2.4.7

**Comment by dmmauger** [comment]
@jrobinso :
The 2.4.7 release appears to have a bug in the structure visualization update. If multiple base pair tracks are loaded only the top track is displayed. See example below. 

In this example three different .bp files are loaded and only the top one is displayed. Removing the top track will allow visualization of the middle track.

MacOS 10.12.6 with IGV 2.4.7

![example 1](https://user-images.githubusercontent.com/15740949/35644178-47163014-0696-11e8-9b9d-d55287bd785b.jpg)

![example 2](https://user-images.githubusercontent.com/15740949/35644171-40f6fab0-0696-11e8-8402-6d037dde2df1.jpg)

**Comment by jrobinso** [comment]
OK, this is probably from setting the clip.   I thought that was too easy.
 So use 2.4.6 for now until this is fixed, which shouldn't be long.

**Comment by jrobinso** [comment]
I think this is fixed, could you try the snapshot build (link below).   If
the fix is confirmed I will release this as 2.4.8

http://software.broadinstitute.org/software/igv/download_snapshot

On Thu, Feb 1, 2018 at 12:54 PM, James Robinson <jrobinso@broadinstitute.org

**Comment by dmmauger** [comment]
I can confirm that the bug is fixed in the snapshot build. Screenshot attached below.

**Thanks!**

![screen shot 2018-02-02 at 10 17 44 am](https://user-images.githubusercontent.com/15740949/35740310-6292c2ea-0802-11e8-9cd4-5121dea62538.png)

**Comment by jrobinso** [comment]
OK,  we'll release it as 2.4.8 this weekend.

BTW you can suppress the non-meaningful sample attributes shown there by selecting "View > Preferences"  and unchecking "Show Attribute Display"
