### ISSUE TITLE
igv-2.4.8: browser fails to start due to some network restrictions

### ISSUE THREAD

**Issue by mmokrejs** [igvteam/igv#513]
Hi Jim,
  I used to run igv on our cluster login nodes directly. Currently, when I try 2.4.8 version it does not practically start but eat all available CPU cores. Running `strace` on the process I see lots of:

`[pid 20131] futex(0x7fff48469f54, FUTEX_WAIT_BITSET_PRIVATE, 1, {368799, 230229877}, ffffffff) = -1 ETIMEDOUT (Connection timed out)`

First I thought this is some phone-home  feature of IGV or HTSJDK but maybe not. BTW, is there any feature like this? At least in GATK there is. The issue would be the firewall of the cluster will discard such attempts. If you are aware of phone-home backdoors in IGV/HTSJDK please introduce a runtime switch so I could run igv.jar without the necessity to have a working network connection.

Second, after a long while the igv indeed moves a bit further with:

```
$ IGV_2.4.8/igv.sh 
WARN [2018-02-07 16:06:00,943]  [Globals.java:138] [AWT-EventQueue-0]  Development mode is enabled
Feb 07, 2018 4:06:00 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
INFO [2018-02-07 16:06:00,963]  [DirectoryManager.java:171] [AWT-EventQueue-0]  IGV Directory: /home/mmokrejs/igv
INFO [2018-02-07 16:06:00,963] [DirectoryManager.java:171]  IGV Directory: /home/mmokrejs/igv
INFO [2018-02-07 16:06:00,968]  [Main.java:154] [AWT-EventQueue-0]  Startup  IGV Version 2.4.8 02/02/2018 07:40 PM
INFO [2018-02-07 16:06:00,968]  [Main.java:155] [AWT-EventQueue-0]  Java 1.8.0_162
INFO [2018-02-07 16:06:00,968]  [DirectoryManager.java:76] [AWT-EventQueue-0]  Fetching user directory... 
INFO [2018-02-07 16:06:01,005]  [Main.java:156] [AWT-EventQueue-0]  Default User Directory: /home/mmokrejs
INFO [2018-02-07 16:06:01,006]  [Main.java:157] [AWT-EventQueue-0]  OS: Linux


Feb 07, 2018 4:06:01 PM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /home/mmokrejs/.java/.userPrefs/prefs.xml
INFO [2018-02-07 16:14:32,934]  [GenomeManager.java:186] [pool-2-thread-1]  Loading genome: http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome
ERROR [2018-02-07 16:14:49,353]  [Downloader.java:164] [pool-2-thread-1]  Error renaming download file /home/mmokrejs/igv/genomes/hg19.genome.download
java.nio.file.NoSuchFileException: /home/mmokrejs/igv/genomes/hg19.genome.download
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:409)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.broad.igv.ui.util.download.Downloader.run(Downloader.java:162)
	at org.broad.igv.ui.util.download.Downloader.download(Downloader.java:196)
	at org.broad.igv.feature.genome.GenomeManager.refreshCache(GenomeManager.java:710)
	at org.broad.igv.feature.genome.GenomeManager.getArchiveFile(GenomeManager.java:594)
	at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:199)
	at org.broad.igv.feature.genome.GenomeManager.loadGenomeById(GenomeManager.java:171)
	at org.broad.igv.ui.IGV$StartupRunnable.run(IGV.java:2129)
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

So, I need to tell IGV not to bother fetching genomes from amazon. How to disable this networking feature? Or could java-8 be made less aggressive so that it would not try desperately for many minutes in 24 threads, causi8ng sytem load about 28 and eating 35GB of RAM?

I used to have hg19 downloaded but during this exercise I removed my ~/igv/ completely hoping I will overcome this issue. I will copy the files via rsync from another computer. The firewall won't be unblocked (outgoing http, https, ftp, etc. are just blocked)

Finally, as you can see, igv crashes because it doe snot anticipate the download could eventually fail.

**Comment by jrobinso** [comment]
If you want to run without a network you'll have to create any genomes you
need locally.    It will try to load the last genome you used on startup.
 It loads various other things, such as the list of available genomes,  but
these should fail quickly and silently (from your point of view).     If it
is not failing quickly it means the attempt to create a network connection
is not failing quickly.

Running IGV without a network is more complicated than it should be,  its
something I am addressing for the next major release.   In the meantime
downloading and creating a local genome is your best option.

**Comment by mmokrejs** [comment]
Yes, somewhat verbose logging would be helpful to diagnose the problem. I am happy to test. Mostl likely, the key to repeat this issue is to have a firewall which silently discard the packets. In contrary, if you unplug your ethernet cable kernel will tell your application immediately there is no network connection. So, that is not very good way to test for this. At least my guess.

**Comment by mmokrejs** [comment]
BTW, htslib is also getting crazily hungry after network: https://sourceforge.net/p/samtools/mailman/samtools-help/thread/20180208181328.GC18980%40sanger.ac.uk/#msg36220509

**Comment by jrobinso** [comment]
Yes,  I do test with no network occasionally,  and it works if you have a
local genome.   But when network connections don't actually fail,  or take
a really long time to fail,  you will get symptoms you describe.

What's needed is a command line switch,  "no network",  which shuts down
all network attempts.   That shouldn't be too difficult to add,  probably
easier than debugging this.   The flag would just cause an exception to be
thrown whenever an http request would be attempted,  effectively the same
as unplugging the network.
