### ISSUE TITLE
NumberFormatException while creating index in mac

### ISSUE THREAD

**Issue by juancrescente** [igvteam/igv#514]
Go to file-> load from file -> select any .sam file and get this error:

<img width="930" alt="screen shot 2018-02-19 at 14 41 59" src="https://user-images.githubusercontent.com/2141907/36390955-4878ad28-1583-11e8-8cbf-a975ab997933.png">

macOS sierra: 10.13.3 (17D47)
IGV 2.4.8

**Comment by jrobinso** [comment]
That's not a .sam file.   It looks binary.
