### ISSUE TITLE
[SV Feature request] "View MATE region" functionality for BND records

### ISSUE THREAD

**Issue by SHuang-Broad** [igvteam/igv#515]
Hi Team, 

As we are moving along implementing more features in our SV caller, we are beginning to explore BND records. BND records are used for encoding (possibly complex) SV event breakpoints in VCF (e.g. VCF spec version 4.2 section 5.4). These BND records could be used for representing complex rearrangements, or possibly indicate an insertion where only breakpoints could be resolved but not the whole inserted sequence.

It would be great if on one BND record in the VCF track, one can "right click" and have the option of "view MATE region(s) in split screen", which could help us resolve the event better.

Possible difficulties:
* Multi-allelic variants, i.e. those with multiple mates, might request multiple "screen resources".
* Not all tools that output BND records output both mates. It shouldn't be very difficult to extract the mate's location except for 
    1. the MATE is located in an assembly file as exemplified in section 5.4.2. 
    2. telomeric mate's as exemplified in section 5.4.5, and
    3. unknown mates, i.e. when a BND is a single breakend (section 5.4.9)

Do you think this is approachable, given the difficulties?
Thanks!

**Comment by jrobinso** [comment]
I don't know, but I am interested in exploring it.    Can you supply some test VCFs?

**Comment by jrobinso** [comment]
@SHuang-Broad ping -- can you create or point me to a test VCF for this?  I have access to the Broad file system.
