### ISSUE TITLE
Run igv.sh error

### ISSUE THREAD

**Issue by ytguojian** [igvteam/igv#516]
Hi,
This is the first time for me to use igv in linux OS. When I run igv.sh, it showed error messages.
"INFO [2018-03-01 11:25:04,281]  [DirectoryManager.java:169] [main]  IGV Directory: /home/hrajxg/igv
INFO [2018-03-01 11:25:04,281] [DirectoryManager.java:169]  IGV Directory: /home/hrajxg/igv
INFO [2018-03-01 11:25:04,286]  [Main.java:135] [main]  Startup  IGV Version 2.3.93 (151)05/15/2017 06:11 PM
INFO [2018-03-01 11:25:04,287]  [Main.java:136] [main]  Java 1.8.0_161
INFO [2018-03-01 11:25:04,287]  [DirectoryManager.java:72] [main]  Fetching user directory...
INFO [2018-03-01 11:25:04,373]  [Main.java:137] [main]  Default User Directory: /home/hrajxg
INFO [2018-03-01 11:25:04,373]  [Main.java:138] [main]  OS: Linux
ERROR [2018-03-01 11:25:04,398]  [DefaultExceptionHandler.java:49] [main]  Unhandled exception
java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at org.broad.igv.ui.Main.main(Main.java:91)
INFO [2018-03-01 11:25:06,893]  [ShutdownThread.java:51] [Thread-2]  Shutting down"
How  to resolve it? Thanks a lot

Cheers,
Jian

**Comment by jrobinso** [comment]
Hi, you have to set your X11 display.   Do a web search for help.  A good test program is "xclock",  if that doesn't work the X11 display is not set.
