### ISSUE TITLE
Concurrent view is broken

### ISSUE THREAD

**Issue by kelepiradam** [igvteam/igv#520]
Latest version fails to display gene panels concurrently. Here is the error message that I get. 

![image](https://user-images.githubusercontent.com/37572619/37641227-f442fc28-2c29-11e8-88a8-ee75506c6552.png)

2.3.x releases don't have this problem. 

I am using macOS 10.13.3 Oracle Java 1.8.0.161 and IGV 2.4.9. Java Heap size is set to 8G. Same problem persists under windows as well.

**Comment by helgathorv** [comment]
Thanks for the report with the detailed info. Looks like it's a problem with bam files but not all datatypes. We'll take a look.

**Comment by jrobinso** [comment]
I pushed a fix.   We'll do a release this evening.   Thanks for the report.

**Comment by kelepiradam** [comment]
Thanks for the heads up.
