### ISSUE TITLE
SA:Z:-tags seem to block the mouse-over panels

### ISSUE THREAD

**Issue by yhoogstrate** [igvteam/igv#521]
Dear IGV developers,

I am analysing chimeric alignments to determine possible structural variants. In concorance with the SAM specification I have assigned these reads the `SA:Z:`-tag. Before, I was able to see the mouse-over box that provides the read names etc. . In the latests versions of IGV it seems that these boxes are disabled for reads that have their `SA:Z:`-tag is set.
I have searched through the IGV settings but I did not find an option to enable this. I am not sure if this is a bug or a feature, but since I think it is important to allow inspection of chimeric reads I would kindly ask you to share your thoughts on this and ask you whether there is some kind of work-around?

I hope you can help me a bit further. All best,

Youri

**Comment by amwenger** [comment]
The relevant preference is `View > Preferences > Alignments > Hidden SAM tags`, which is a list of (verbose and difficult for humans to parse) tags that are suppressed in the alignment details popup.  You can remove "SA" from the list to see the raw SA entries.

Even when SA is hidden, the popup does show information about supplementary alignments in the "Supplementary Alignments" section, which lists the location, strand, length, and MAPQ for supplementary alignments.

**Comment by yhoogstrate** [comment]
Hi there @amwenger,

Thank you for the suggestions. I have emptied the full textbox and saved the settings to make sure I can see the sequencing reads. Also all 'filter ... reads' are unchecked. After changing, still no popup appears at all when the mouse goes over the reads and the reads aren't clickable either.
I am also quite sure it doesn't have to do with the settings of the mouse because when my mouse is over the coverage track I do see the number of reads and mismatches etc. .
And when I change the sam file by by adding the `SA:Z:`-tag the popups will appear again.

May I ask which version of IGV you tested this with? I am using 2.4.10 03/20/2018

If other people suffer from the same issue and are searching for a workaround, you can use IGV 2.3 which is still available for download.

**Comment by amwenger** [comment]
Ah, I misunderstood your comment.  I think the problem occurs with invalid SA entries.  Parsing those entries causes an exception, which suppresses the popover.  I suspect you will see a parse exception in your igv.log along the lines of:

```
ERROR [2018-03-30 10:53:00,466] [DefaultExceptionHandler.java:49]  Unhandled exception
java.lang.ArrayIndexOutOfBoundsException: 5
    at org.broad.igv.sam.SAMAlignment$SupplementaryAlignment.<init>(SAMAlignment.java:878)
    at org.broad.igv.sam.SAMAlignment.getSupplAlignmentString(SAMAlignment.java:654)
```

I submitted a pull request that catches the exceptions and displays "* Invalid SA entry (not listed) *" for the invalid entries.

**Comment by yhoogstrate** [comment]
Thanks for the super quick fix! I can confirm the panel is back :+1: 

![image](https://user-images.githubusercontent.com/2264697/38246252-79fba208-3741-11e8-8f0d-4532f68fd9c6.png)
