### ISSUE TITLE
sampleMapping is documented incorrectly as being possible to exist in standalone file.

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#523]
By my reading of https://software.broadinstitute.org/software/igv/SampleInformation#samplemappingfile sampleMapping can either

 - be added at the end of an attributes .txt file, or
 - stand alone in its own .txt file

However, I find the following to work in the first case but not in the second:

#sampleMapping
data2/R1_WT_N.Log	R1_WT_N
data2/R1_WT_N.Log.final	R1_WT_N
data2/R1_WT_N.Log.progress	R1_WT_N
data2/R1_WT_N.ReadsPerGene.tab	R1_WT_N

        Unexpected error: An error occurred while accessing: /n/core/Genomics/Analysis/Si/younshim_park/yop2/mec/data2/SampleMapping.txt
        Could not determine file type. Does file have proper extension? .
        
I even get this trying the example standalone sampleMapping file provided in the documentation
       https://dm.genomespace.org/datamanager/file/Home/Public/SpaceCadet/IGV%20Sample%20Information%20Files/BLCA_SampleMapping_3sets.txt
    
Either this should be implemented, the documentation changed, or my understanding should be adjusted (often the case!).

**Comment by helgathorv** [comment]
Released in IGV 2.8.0
