### ISSUE TITLE
apply sample attributes automatically to more tracks

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#524]
In my hands, track labelled "foo.bam" will display with sample attributes declared for sample "foo".  

This is desirable.

However, automatic tracks "foo.bam Junctions"  "foo.bam Coverage" do not, and arguably should.

Also, arguably, *any* track gained from loading file "foo.*" should display with attributes declared for sample "foo".

Note:
 - This issue was first raised by me at https://groups.google.com/d/msg/igv-help/kfkaJp9Bcgc/PAV4CIMoBAAJ

**Comment by helgathorv** [comment]
Released in IGV 2.8.0
