### ISSUE TITLE
Refactor bigWig code into separate repository? 

### ISSUE THREAD

**Issue by purcaro** [igvteam/igv#529]
Hi!
We are looking into using the igv bigWig code for several projects. Would it be feasible to extract the bigWig code into a separate repository? This would simplify us utilizing the code (in particular, we'd like to try to implement a writer from an array of values). 

I could probably do the refactor into my own repository, but it might be preferable to keep the bigWig repository in the igvteam organization...

Just wondering,
Thanks!
Michael

**Comment by purcaro** [comment]
Thanks! Hope it won't take too much time!

**Comment by jrobinso** [comment]
Hi Michael,  this is not difficult and won't take too much time but I am unlikely to find time for it before the end of May.  We have an annual program meeting and much to do.   In the meantime,  if you want to develop based on the package in IGV that would not be a waste of time,  when I do make the repository it will be based on that code unmodified.   I can assist in merging at that time.

**Comment by jrobinso** [comment]
@purcaro Were you successful pulling the bigwig code out?  Its been a year and I'm even busier than before.   I don't have time for this, not just the coding but the required documentation and support burden.  Apologies for not getting back to you earlier.   Feel free to use the code,  you could actually use igv.jar as a library and access the class BigWigDataSource.
