### ISSUE TITLE
Igv 2.4.10 readme.txt missing

### ISSUE THREAD

**Issue by Ivalize** [igvteam/igv#532]
Hi.
I downloaded the igv source from page of igv and the zip dont have README.txt with the instruction to succefully instalation.

Thanks

Linux Ubuntu 16.04.4

**Comment by DarioS** [comment]
You don't need to compile IGV; there is a BASH script in the `scripts` folder named `igv.sh` to start it. So, to All you need to do is run `$ /path/to/IGV_2.4.10/scripts/igv.sh` and it will start.
