### ISSUE TITLE
Can not find hg38 in the server?

### ISSUE THREAD

**Issue by yuyang63203** [igvteam/igv#533]
hi,
I tried to load genome hg38 from the server. But I can not find it.
version 2.4.10
windows 10
2GB
![image](https://user-images.githubusercontent.com/17993955/38627227-7c1f5ba6-3d7c-11e8-99ba-111bcdf802f4.png)

**Comment by yuyang63203** [comment]
version 2.4.10
windows 10
2GB

**Comment by DarioS** [comment]
From the IGV menu, choose View then Preferences. You will see numerous tabs. Click on the Advanced tab. Have you changed the source of the genomes unintentionally? The settings should look like:

![image](https://user-images.githubusercontent.com/631218/39742831-50962692-52e2-11e8-8afa-20b9219a55f7.png)

These are my settings and I have hg38 available from the drop-down list.

**Comment by jrobinso** [comment]
Another possibility is you already have hg38 in your pulldown list.   Did you check it?
