### ISSUE TITLE
annotation incorrect for TNNI3 (NM_000363)

### ISSUE THREAD

**Issue by shmurray** [igvteam/igv#537]
Exon/intron boundaries and amino acid positions are incorrect.

**Comment by jrobinso** [comment]
You didn't identify an assembly.   Also, are they different than what you see in the UCSC genome browser?  The annotations come from there,  but possibly are out of date.   In any event can't do anything without knowing the assembly.

**Comment by shmurray** [comment]
Hi Jim,

Sorry – human hg19. It looks like UCSC is incorrect as well. We have our own pipeline where we correctly annotate, but just thought you would want to know.

Best, Sarah

Sarah S. Murray, PhD, FACMG
Professor, Department of Pathology
Director, Genomic Technologies
Center for Advanced Laboratory Medicine
University of California San Diego
10300 Campus Point Drive, Suite 150
MC 7181
San Diego, CA 92121
(858) 657-5716 (phone)
shmurray@ucsd.edu<mailto:shmurray@ucsd.edu>
