### ISSUE TITLE
Sashimi plot - junction counts and location issue

### ISSUE THREAD

**Issue by cbenoitp** [igvteam/igv#538]
Hello,

I'm using sashimi plots to visualize and confirm events of alternative splicing in my RNAseq data.
But I'm having problems with the sashimi plot in IGV. Indeed, I tried to generate sashimi plot with 2 versions of IGV and had discrepancies between the 2 versions.

First, I used IGV version 2.3.98.
With this version, I have a problem with the reads numbers shown on the junction. Each time, I load a new sashimi plot from the same region, the counts of some junction increase. It seems to only affect junction with high coverage and the counts for these junction seems to double each time we reload the sashimi plot or change the settings.

The first time I load the sashimi plot the counts are the following:
![gapdh_sashimi1_igv2 3](https://user-images.githubusercontent.com/35301937/39711387-e842739c-521f-11e8-816f-19a077266a97.png)

Then, after I redo the sashimi plot, I have the following counts:
![gapdh_sashimi2_igv2 3](https://user-images.githubusercontent.com/35301937/39711392-ec41dca8-521f-11e8-941b-017912625556.png)

Because I realized I wasn't using the last version of IGV, I then tried IGV version 2.4.10.
With this version, the counts of the junction don't change when reloading the sashimi plot. But this time, the position of the junction seems to be incorrect. They do not correspond to what we saw in IGV 2.3, neither to what we see in the alignment and coverage tracks.

Looking at the junctions, we can see they are misplaced (particularly comparing with the sashimi plots from the version 2.3):
![gapdh_sashimi1_igv2 4](https://user-images.githubusercontent.com/35301937/39711427-02e60394-5220-11e8-829a-fb7f710a3434.png)

Here are the samples to reproduce the bug: [example.zip](https://drive.google.com/open?id=1qwttyOXyFShmLW_CkNeAhiBcU4iwTA02).

Workflow to reproduce the figures:
- open the chosen version of IGV
- select the genome: Human (hg38)
- load the 4 samples (present in the [example.zip](https://drive.google.com/open?id=1qwttyOXyFShmLW_CkNeAhiBcU4iwTA02) archive)
- go to the following region: chr12:6,536,330-6,537,262
- do the sashimi plot
- for each samples "Set junction coverage min" to 10

I'm using IGV on ubuntu 16.04.

Thank you for your help,
Clara

**Comment by jrobinso** [comment]
Thanks for the report.   I will look into it.

**Comment by jrobinso** [comment]
@cbenoitp  I cannot access the example.zip archive.   Could you repost it?   Thanks.

**Comment by cbenoitp** [comment]
Sorry! Here is the new link : [example.zip](https://drive.google.com/open?id=1qwttyOXyFShmLW_CkNeAhiBcU4iwTA02).

**Comment by jrobinso** [comment]
Thanks for the sample data and detailed instructions, it is a big help.
 I'm looking at this now.

**Comment by jrobinso** [comment]
Thanks again for the test data and report.   I have found the problem and
pushed a fix, it will be released on Monday as 2.4.11.

The bug is in combining junctions from both strands,  if you view junctions
for one strand at a time it should be correct.   Again the fix will be
released on Monday.

**Comment by jrobinso** [comment]
This is fixed in the current release (2.4.11).
