### ISSUE TITLE
Intergenic Transcript Label Placement 

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv#539]
The placement of gene symbols for some transcripts can be unsuitable.

![image](https://user-images.githubusercontent.com/631218/39741703-46314366-52de-11e8-941d-990936088b88.png)

For some transcripts of IGHG1, the label is directly underneath the transcript, but for other near-identical transcripts, it's thousands of bases away from the transcript. This a surprising inconsistency. I used EMSEMBL Genes available from the Load From Server -> Available Datasets selection tree.

**Comment by jrobinso** [comment]
OK, I see the problem,  I think.    Have you seen this in other annotation files, or just this one?

**Comment by jrobinso** [comment]
The problem is not the placement of the name, which is correct, but only part of the transcript is being drawn.   It is correct in IGV-Web,  see http://bit.ly/2PoFOJZ,   so I just need to track down the differences.  gff and all its variants are very difficult to deal with because there is no agreement or standard about how to model genes.

**Comment by jrobinso** [comment]
OK,  I updated the Ensembl annotation to v 94 (from 80),  which is now a gff3 file.  In general those have fewer mistakes, and are more reliable to parse.   The problematic transcripts are gone in this version (IGHG-204 was one of them).      I don't believe those very long transcripts were real,  no other annotation set shows them.   There's still a mystery as to why they weren't parsed correctly (wrt what was in the file),   but if the transcript is not modeled in the expected way that can happen.   So v80 is gone from the IGV menu,  v94 looks better.   See screenshot.   
<img width="1262" alt="screen shot 2018-10-25 at 11 06 06 pm" src="https://user-images.githubusercontent.com/933148/47547614-1057d900-d8ab-11e8-90da-d364f39905db.png">

**Comment by DarioS** [comment]
Updating ENSEMBL Genes seems like a good solution to the issue.
