### ISSUE TITLE
can I sort by strand then by base in igv batch script?

### ISSUE THREAD

**Issue by sharon558** [igvteam/igv#543]
Is it possible to enable/implement consecutive sorting feature in igv or igv batch script?

It seems currently igv can only sort alignments based on one feature (e.g. base, or strand, or start position, etc. ). Is it right?

**Comment by jrobinso** [comment]
Yes, currently you can sort on only one attribute.

**Comment by jrobinso** [comment]
Apologies for the long delay, you can now group then sort, which I think is what you want to do for the case of strand.   Sorting sorts the existing rows of alignments by the value at a specific base, grouping separates them into groups.  See the following example

```
preferences SAM.COLOR_BY STRAND
load https://1000genomes.s3.amazonaws.com/phase3/data/HG01879/alignment/HG01879.mapped.ILLUMINA.bwa.ACB.low_coverage.20120522.bam
goto chr8:128,749,315
group STRAND
sort BASE chr8:128,749,315
```
