### ISSUE TITLE
Bisulfite mode displays 'N' bases only at C or G ref

### ISSUE THREAD

**Issue by caalo** [igvteam/igv#545]
Hi IGV team,

I'm working with bisulfite-converted methylation data, paying close attention to bases that are labelled as 'N'. I am noticing that IGV (2.4.10) only labels 'N' bases at C or G references where bisulfite conversion occurs, and all other 'N' bases are not labelled. I've attached a screenshot of the same sample viewed in bisulfite and in regular, no-color mode. The latter reveals 'N' bases not at C or G references. I was hoping that 'N' bases will also show up in bisulfite mode regardless of reference context -- was the display of 'N' bases designed specifically for C or G reference contexts in bisulfite mode?

![screen shot 2018-05-16 at 3 36 23 pm](https://user-images.githubusercontent.com/17771008/40139910-59ca3e86-591f-11e8-83d8-bcfb0bbf14c4.png)

![screen shot 2018-05-16 at 3 36 07 pm](https://user-images.githubusercontent.com/17771008/40139929-69ccfd50-591f-11e8-94d4-dd1ac7436feb.png)

**Comment by jrobinso** [comment]
The bisulfite support was contributed by @benbfly and I am not sure about the intended interpretation of an "N" read base, however this looks like an un-intended bug since "N" should be considered a mismatch WRT reference whereever it occurs.   Could you possible extract a small sample of your BAM file to use as a test?

**Comment by benbfly** [comment]
I haven't looked at this code in a long time, but I don't think there was a rationale for doing something like that- it looks more like a bug, like maybe I forgot to check for the "N" condition in the non C/G part.

**Comment by jrobinso** [comment]
Thanks @benbfly --  so I will treat "N" as any other mismatch and highlight it.

The default color for "N" is very close to the alignment color,  I will make it darker as well.

**Comment by jrobinso** [comment]
I think I have fixed this with commit d2f0c20ea366043a9770c79e159a7f77e16cc742.   This will be released as 2.4.11 towards the end of the week.

@caalo Could you provide a test case in the form of a small SAM or BAM file?
