### ISSUE TITLE
"File > Save Session" changes renderer from SCATTER_PLOT to BAR_PLOT in overlaid tracks.

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#546]
Steps to reproduce:

1. Set the "type of graph" to "points" for three tracks
2. Select two of the tracks and choose "Overlay Tracks"
3. Observe that the overlad tracks are still both displayed as "points", as expected/desired.
4. Chose "File > Save Session"
5. Observe the overlaid tracks switch to being "Bar Chart" upon saving the session.
6. Edit the igv_session.xml and reset all "BAR_CHART" to "SCATTER_PLOT" as value of renderer.
7. Chose "File > Load Session" and reload the edited session.
8. Observe that the overlaid tracks now again are displayed as "points".

**Comment by jrobinso** [comment]
In addition... support it from the right-click menu.   And don't use transparanency in "points" mode.

**Comment by jrobinso** [comment]
@malcook I can no longer reproduce this, maybe it got fixed and not updated.   If its still a problem re-open this.

**Comment by malcook** [comment]
Agreed - I too can no longer reproduce.  Thanks for checking.
