### ISSUE TITLE
Broken link to 'UCSC' browser help page

### ISSUE THREAD

**Issue by katerose** [igvteam/igv#548]
This link:
https://cgwb.nci.nih.gov/FAQ/FAQformat.html

on this page:
https://software.broadinstitute.org/software/igv/MultipleAlignmentFormat

isn't responsive.  

Suggest you use the actual UCSC public site instead, and more specific URL:

https://genome.ucsc.edu/FAQ/FAQformat.html#format5

**Comment by helgathorv** [comment]
Thanks. Now fixed.
