### ISSUE TITLE
BLAT Error: "Cannot determine species name for genome: Mouse (mm10)"

### ISSUE THREAD

**Issue by wanwayBioinfo** [igvteam/igv#552]
Hi, I'm using IGV 2.4.10 and get this error "Cannot determine species name for genome: Mouse (mm10)" while BLATing sequences against mouse genome which was downloaded from IGV. Things are fine with human genome. And it seems that this problem only occur in 2.4.x and specifically to mouse genome.

**Comment by jrobinso** [comment]
There was a typo affecting mouse.   A fix has been checked in,  will be released as 2.4.11 sometime this week.
