### ISSUE TITLE
What file format is the refseq track loaded with IGV at startup 

### ISSUE THREAD

**Issue by duartemolha** [igvteam/igv#553]
Hi. 
When IGV starts, refseq track is open as default. I was wondering what file format would make features display exactly like that? 

GTF and GFF3 files display differently. Bed12 seems very close to it , but it shown the features as black boxes and change track colour does not seem to work
 
Thanks

Duarte

**Comment by jrobinso** [comment]
Its the UCSC gene table format,  look at UCSC for details.    You didn't
specify a genome but for hg38 the exact file is this one:
http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/refGene.txt.gz

Generally IGV uses extension to determine format,  but for the special case
of these UCSC gene table files it looks for "refGene" anywhere in the
filename.   This was never intended to be a general format, only to support
the "refGene.txt.gz" files downloaded from UCSC.

An equivalent and correctly coded gtf or gff3 format file should display
features in the same way.

If you can reproduce the change track colour problem and post and example
file I will look at it,  please open a ticket specifically for that.
