### ISSUE TITLE
.tdf/.igv files: Configuring baseline in track line

### ISSUE THREAD

**Issue by holtgrewe** [igvteam/igv#554]
Is it possible to define the baseline value in the track line?

**Comment by jrobinso** [comment]
It should now be possible with commit 1d441c5be132e3d2b1ebe3544352180ffc8d1aee.   You can specify viewLimits with 3 value, middle being the baseline.   This will be released in the next 2 weeks, or you can pull and build or use the nightly snapshot.

Example
```
viewLimits=0:2:6
```
