### ISSUE TITLE
Gene list view leaves blank space in the middle

### ISSUE THREAD

**Issue by yurivict** [igvteam/igv#556]
I followed instructions about selecting gene list: http://software.broadinstitute.org/software/igv/gene_list_view

But my screen has blank space in the middle:
![igv-blank](https://user-images.githubusercontent.com/271906/41889752-0e3befca-78c1-11e8-9f33-670863863164.png)

unlike the screenshot on the webpage: 
![image](https://user-images.githubusercontent.com/271906/41889812-6433562a-78c1-11e8-9c66-f73869f9d8a1.png)

What could be wrong?

**Comment by jrobinso** [comment]
Do you have data loaded?  Give us a reproducible test case.
