### ISSUE TITLE
missing igv.jar in v2.4.10 release?

### ISSUE THREAD

**Issue by bataylor976** [igvteam/igv#559]
Downloaded v2.4.10 release (commit#7537317), I ran the igv.sh script as instructed in  scripts/readme.txt, and I'm getting the error: Unable to access jarfile ./igv.jar. Can't seem to find it anywhere. Should I be following a different set of instructions?

**Comment by davideby** [comment]
You didn't mention it, but did you build IGV first by running the Ant script?  Unfortunately, the repository at this tag didn't include explicit build instructions, so it's understandable you could have missed that.  We're in the process of revamping this.  The former build script was very much oriented towards workflows internal to the team so we're currently trying to simplify it for outside developers.

By the way, if you just want to *run* IGV and aren't interested in the code and development, we recommend using the [pre-built releases on our website](http://software.broadinstitute.org/software/igv/download).  That's much less complicated than what follows below.

To build IGV at the 2.4.10 tag requires Ant and Java 8 (not earlier or later; Java 7 & Java 9+ aren't supported).  From the project root, run `ant -f scripts/igv_build.xml publishBoth`.

That will create a set of three JARs in an IGV-dist directory at the project root.  All three are required.  If you copy `scripts/igv.sh`, `scripts/igv.command`, or `scripts/igv.bat` into this directory you can use those to run IGV per the `scripts/readme.txt` you referenced.

That build command will also create IGV_user.zip & IGVDistribution_user.zip in the project root, which are IGV "distributions" (binary and source + binary, respectively) that contain all the necessary JARs plus the launching scripts.

You can gain more control over file naming etc in the build by supplying certain Java properties.  Here's an example based on our internal build:
```
deploy.dir=./snapshot
download.dir=./snapshot
src.archive.name=IGVSource_snapshot
bin.archive.name=IGV_snapshot
version=snapshot
development=true
# Force the compiler to target Java 8
ant.build.javac.source=1.8
ant.build.javac.target=1.8
log.level=INFO
```
Obviously, change those paths to suit your local environment and any other info as desired.  If you save the above into a Java properties file (for example `build_snapshot.properties`), then the build command is instead `ant -propertyfile build_snapshot.properties -f scripts/igv_build.xml publishBoth`.

There are other properties available but the above should be enough for an outside developer.

You can also use:
- `ant clean` to do a clean build
- `ant -propertyfile build_snapshot.properties -f scripts/igv_build.xml publishBin` to build the binary distribution only.

FWIW, all of this is changing in the current code base as we are switching over to Gradle.
