### ISSUE TITLE
Support of Picard Interval Lists as interval track

### ISSUE THREAD

**Issue by clintval** [igvteam/igv#560]
The Picard and GATK toolkits require `Interval List` over `BED` files for representing interval data.

The `Interval List` files are only compatible against a single genome build in those toolkits (whereas `BED` files are genome build agnostic).

There are a few differences of the `Interval List` format as compared to `BED`:

- The coordinate system starts at +1
- Features have an inclusive 1-based end
- Has a header copied from the dictionary of a specific reference genome

It would be amazing to have support of this file format in IGV as an interval track. Currently, I need one `Interval List` file and a redundant accompanying `BED` file in order make use of both Picard and IGV on projects.

I see two features that could be implemented:

- [ ] Import `Interval List` files as interval tracks just like `BED`
- [ ] Allow import of an `Interval List` **if** the reference genome has a matching `*.dict` file

Here is the documentation on how to create an `Interval List`:

https://broadinstitute.github.io/picard/command-line-overview.html#BedToIntervalList

**Comment by jrobinso** [comment]
We could do the first feature if interval lists were assigned a specific extension.   I don't understand the second feature  ("Allow import....").   I would not be in favor of enforcing any requirements of matching headers,  in fact I'm not even sure what this means.   A reference is defined in IGV with a fasta file.  Also,  its very useful and perfectly legitimate to load files from equivalent but not identical reference files,  e.g. hg38 and GrCH38.

If you want me to pursue this zip up and attach an example file,  again we would have to assign and agree on an extension  (.interval)?

**Comment by jrobinso** [comment]
OK,  I could support loading an interval_list file as a bed file.   Lines
starting with @ will be skipped,  on parsing 1 will be subtracted from the
"start" column.     Other than that this looks like a 5 column bed file.

**Comment by clintval** [comment]
That would be much appreciated thanks!
