### ISSUE TITLE
W10 cant run / empty windows

### ISSUE THREAD

**Issue by robinjugas** [igvteam/igv#561]
Hello, I think I have the same or similar issues as guy here:
https://github.com/igvteam/igv/issues/484
I make a screenshot:
![igv](https://user-images.githubusercontent.com/5863997/42265672-7cb6d596-7f74-11e8-9702-d9e2c3b9ee2d.PNG)

I download the IGV for Windows, run the batch file. I have Java 8 upd. 151. Then I opened File, Load from File and loaded BAM file, sorted with samtools. But I think there should be something similar to tablet app I guess. 
Yeah, this is the first time I am using IGV. 
What can be wrong?
Thanks for your reply.
Robin

**Comment by helgathorv** [comment]
Hi Robin,
I don't see anything wrong with the screenshot. Follow the instructions in the message: Zoom in to see the data. IGV won't load the data until you are zoomed in to a smaller region. By default, the threshold is 30 kb, but that can be changed in your preferences. Note however that the larger the region, the more memory will be required for the data.

Helga

**Comment by robinjugas** [comment]
Oh. I did it. Firstly nothing happened for many seconds but then it showed the alignments. Thansk!
