### ISSUE TITLE
"Java Exception" at startup in version 2.4.13, but not in 2.4.11 (Windows 10, 64 bit)

### ISSUE THREAD

**Issue by molecules** [igvteam/igv#566]
I downloaded version 2.4.13 and clicked on `igv.bat` and up popped a messaged box titled "Java Virtual Machine Launcher" containing the message "A Java Exception has occurred.":

![image](https://user-images.githubusercontent.com/345060/42884949-4c29efca-8a65-11e8-8cf0-244e0eb7a0e7.png)

This doesn't happen with version 2.4.11, which so far seems to run fine. The `igv.bat` script in each of these versions is identical with an md5sum hash of `6293db166cabb2268d544de7199f46c0`. 

I am using Windows 10, 64-bit with Java 1.8.0_171 (architecture x86_64).

By the way, thank you so much for all of the hard work you have put into IGV. It is what I introduce people to when teaching them about genome browsers for the first time.

**Comment by jrobinso** [comment]
OK, thanks for the report.  Rather than double-clicking can you open a
terminal and run igv.bat from the command line?   This should give you a
more specific error message.

**Comment by davideby** [comment]
We had an error in our last build that broke this installer.  I've built a new one and replaced the old one on our Downloads page, so if you go back and grab that one it should be fine now.

Just as for advance notice, we'll be dropping this installer at some point in the very near future in favor of the normal Binary Distribution.  We only use it to deal with HiDPI screen issues but the hope is that the new Java 10 builds will handle this instead.

**Comment by molecules** [comment]
I just tried it. Thanks so much for fixing it!
