### ISSUE TITLE
Specify bar colours in bedgraph file

### ISSUE THREAD

**Issue by pdiakumis** [igvteam/igv#575]
Hi,

I have this file, called `test1.bedgraph`:

```
#track color="0,255,0" altColor="255,0,0"
1	100000	150000	-2
1	152000	160000	0
1	161000	165000	-1
1	166000	168000	1
```

![bedgraph_barplot](https://user-images.githubusercontent.com/29562861/44379633-3e870880-a54a-11e8-8893-95f36da99444.png)

With the `.bedgraph` suffix, this causes IGV to plot these segments as bars, where the height is the value of the last column. Is it possible to specify the colours of the positive/negative values _within_ the header of the file? I know you can do this within IGV by right-clicking on the track, then selecting the Negative/Positive Values colour. The above header I've specified doesn't seem to do the trick, so was just wondering if I'm missing an option.

Many thanks!
Peter

**Comment by jrobinso** [comment]
The leading '#' symbol in the track line makes it a comment, remove it and
it should work.

Also, the quotes around the color strings aren't neccessary, but they don't
harm anything.

**Comment by pdiakumis** [comment]
Awesome stuff, removed comment + quotes and it works!
(I just grabbed that header from an example I found so didn't pay much attention)
Thank you!

<img width="1110" alt="bedgraph_barplot2" src="https://user-images.githubusercontent.com/29562861/44385442-c5e07600-a562-11e8-8da7-622e963ea0ae.png">

**Comment by jrobinso** [comment]
The # comment is neccessary for some file formats for which a "track" line
is not defined, for example gff,  to keep them legal, but for UCSC formats
it should not be used.
