### ISSUE TITLE
Improve treatment of coverage display at zoomed out views on Sashimi plot.

### ISSUE THREAD

**Issue by spastasticgreenduck** [igvteam/igv#579]
Similar to Issue#530 concerning scaling Sashimi plots, I am having trouble visualizing the coverage track when zoomed out of RNA-Seq data.
![screen shot 2018-09-13 at 2 54 57 pm](https://user-images.githubusercontent.com/43253996/45518047-15caeb00-b765-11e8-9139-4d7a215fcaf6.png)
For exon 2, there are reads, but nothing is displayed in the coverage track.
When I then make a Sashimi Plot - the exon coverage is again missing:
![screen shot 2018-09-13 at 2 57 56 pm](https://user-images.githubusercontent.com/43253996/45518152-722e0a80-b765-11e8-9e59-dfd26b6618a5.png)
Here's what it looks like zoomed and finally appears:
![screen shot 2018-09-13 at 3 00 20 pm](https://user-images.githubusercontent.com/43253996/45518280-cafda300-b765-11e8-81d7-14fef85105da.png)

**Comment by jrobinso** [comment]
Sorry but I'm not following your figures at all.  I see coverage over exons in all the views.

**Comment by jrobinso** [comment]
Looking at the reads I see only 2 that might overlap that exon, although
there has to be a few likely out of view.  Most reads in view skip over
it.  Your data scale is 0-276,  try setting to 0-10 to see if there is
anything.

Also, always identify the version of IGV you are using, you can get it from
"help about".

**Comment by spastasticgreenduck** [comment]
Here's a screenshot when I zoom all the way into the exon in question. There are ~90 reads over most of it for the top sample. I am using version 2.4.14. Thanks again
![screen shot 2018-09-13 at 5 42 36 pm](https://user-images.githubusercontent.com/43253996/45523147-7d406500-b77c-11e8-8b34-2bb08bd6228e.png)

**Comment by jrobinso** [comment]
Well, the other possibility is that exon is occupying < 1 pixel in width at
your zoomed out view.   It should still show a thin line there, but that's
my best guess at what's going on here.   You've show a view zoomed out very
far, and zoomed way in,  but when does the coverage appear (at what
resolution)?

I will try to reproduce this with data I have,  if you want me to look at
this data specifically you can extract the region with IGV by selecting
"export alignments" from the right-click popup menu.

This has nothing to do with Sashimi,  correct?

**Comment by jrobinso** [comment]
Also, realize,  that the coverage shown is an average over the region,
where region === the genomic region covered by a pixel.   I can imagine
that for a very small exon the average coverage could be small when genomic
region is very large.   Again, the way to check this is to reduce the data
range to see if anything appears.

On Thu, Sep 13, 2018 at 5:59 PM, James Robinson <jrobinso@broadinstitute.org
> wrote:

> Well, the other possibility is that exon is occupying < 1 pixel in width
> at your zoomed out view.   It should still show a thin line there, but
> that's my best guess at what's going on here.   You've show a view zoomed
> out very far, and zoomed way in,  but when does the coverage appear (at
> what resolution)?
>
> I will try to reproduce this with data I have,  if you want me to look at
> this data specifically you can extract the region with IGV by selecting
> "export alignments" from the right-click popup menu.
>
> This has nothing to do with Sashimi,  correct?
>
>
>
> On Thu, Sep 13, 2018 at 5:45 PM, spastasticgreenduck <

**Comment by jrobinso** [comment]
Yes, I agree that should be improved.

**Comment by helgathorv** [comment]
Released in IGV 2.8.0
