### ISSUE TITLE
Alignments dissapeard while navigating

### ISSUE THREAD

**Issue by juancrescente** [igvteam/igv#583]
While moving in the viewer, alignments go away at the beginning position:
For example in gene:
TraesCS1A02G000100

![peek 2018-09-27 11-31](https://user-images.githubusercontent.com/2141907/46153210-15445100-c249-11e8-940a-85e0df5510b4.gif)

Version 2.4.14
Ubuntu 18.04

The only ouput  I see when the screen crashes is this one:

```

WARNING	2018-09-27 11:34:18	SamReaderFactory	Unable to detect file format from input URL or stream, assuming SAM format.
WARNING	2018-09-27 11:34:19	SamReaderFactory	Unable to detect file format from input URL or stream, assuming SAM format.
^[[DWARNING	2018-09-27 11:34:38	SamReaderFactory	Unable to detect file format from input URL or stream, assuming SAM format.
WARNING	2018-09-27 11:34:38	SamReaderFactory	Unable to detect file format from input URL or stream, assuming SAM format.


```

**Comment by jrobinso** [comment]
What type of file are you loading (BAM?)

**Comment by jrobinso** [comment]
I will try to reproduce it, but am traveling the rest of the week.

In the meantime try it with a BAM file.  SAM files are poorly supported in
the underlying libraries.   You can convert your SAM file to a BAM file
with samtools.

Jim

**Comment by juancrescente** [comment]
Sounds good. The only issue I had with bam files is that I'm not able to
work with big files. I'll give it a shot and let you know.

--
*Juan Manuel Crescente*

This message is confidential. It may also be privileged or otherwise
protected by work product immunity or other legal rules. If you have
received it by mistake, please let us know by e-mail reply and delete it
from your system; you may not copy this message or disclose its contents to
anyone. Please consider the environment before printing this email.

**Comment by jrobinso** [comment]
The BAM file should be smaller than the SAM file.  You will also need to index it.  You can create the BAM and index it with samtools.

**Comment by jrobinso** [comment]
Closing this as SAM files are deprecated.  If you can reproduce this with a BAM file please reopen.
