### ISSUE TITLE
Setting baseline for .seg tracks

### ISSUE THREAD

**Issue by axelgschwind** [igvteam/igv#584]
Hello,

for CNVs, we import track .seq-files into IGV. In these files, we can include view limits for our track ( viewLimits=0:6).
However, we did not find an option to set the baseline in the .seg file. Such an option is crucial because we need to center the baseline to 2 ("normal" copy number) automatically.
I've checked the IGV source code for an option to import the baseline but it seems to be hard coded to 0. Would it be possible to add an option for automatically importing the baseline settings from a seg. file?

If we do the whole thing manually, IGV performs great:
![1](https://user-images.githubusercontent.com/32520233/46196776-3d46b980-c308-11e8-8a0e-c4486447099d.png)
![2](https://user-images.githubusercontent.com/32520233/46196832-564f6a80-c308-11e8-81d6-b16b0591c249.png)
![3](https://user-images.githubusercontent.com/32520233/46196931-a5959b00-c308-11e8-94eb-eece8584cca7.png)

Greetings

Axel Gschwind

**Comment by jrobinso** [comment]
Yes.  I'm traveling for a week but should be able to do this when I return.   

I do note a rather obscure "yline" option in the track line, which might help in the interim.   It looks like the option would be  yLineMark=2 yLineOnOff=on.   See https://genome.ucsc.edu/goldenpath/help/trackDb/trackDbHub.html

**Comment by jrobinso** [comment]
Hi, sorry for the longer than expected delay.   I've pushed a fix for this,  you can now input 3 values for view limits,  for example  
``` 
viewLimits=0:2:6
```
This will be in the next release, around the end of the month.  If you need it sooner you can use the nightly snapshot build.
