### ISSUE TITLE
about the web page "Password Protected Directories": Username/Password Authentication Failed.

### ISSUE THREAD

**Issue by lindenb** [igvteam/igv#586]
unless I'm wrong, the files described at the bottom https://software.broadinstitute.org/software/igv/passwordprotected

http://www.broadinstitute.org/igvdata/private/SignalK562H3k36me3.tdf

http://www.broadinstitute.org/igvdata/private/cpgIslands.hg18.bed

are associated to another password now. 

```
$ wget --user=user1 --password=kJs1GPxWtLet2 -O -  "http://www.broadinstitute.org/igvdata/private/SignalK562H3k36me3.tdf"
(...)
Proxy request sent, awaiting response... 401 Unauthorized
Username/Password Authentication Failed.
```

furthermore the web page is ambigous about the password, there is a comma in the quoted string:

> ...the password is "kJx1GPxWtLet2," which...

Thanks
P.

**Comment by jrobinso** [comment]
The password is "password",  as stated on the web page.    What you've
entered is (part) of the contents of the .htpasswd file,  not the password.

**Comment by jrobinso** [comment]
Also, the user name is "guest",  not "user1".

**Comment by lindenb** [comment]
my bad , sorry.

**Comment by jrobinso** [comment]
try

wget --user=guest --password=password -O - --no-check-certificate  "http://www.broadinstitute.org/igvdata/private/SignalK562H3k36me3.tdf"
