### ISSUE TITLE
sequence length >2^29-1  are not supported 

### ISSUE THREAD

**Issue by MaPengyu** [igvteam/igv#597]
Hello @jrobinso ,
I got an error when i load the bam file to IGV:
Error loading BAM file: java.lang RuntimeException : Sequence length >2^29 -1 are not suppurted.
IGV: win_2.4.14
I have no  idea about it 
Thanks in advance for any kind of help!
best
MaPengyu

**Comment by jrobinso** [comment]
The error means what it says,  sequence lengths > 2^29-1 are not supported.   Does this BAM file have a .csi or .bai index?

**Comment by MaPengyu** [comment]
I sent a massage to your email (igv@noreply.github.com) on three days ago.
