### ISSUE TITLE
PAR-CLIP coloring mode

### ISSUE THREAD

**Issue by NoahMottelson** [igvteam/igv#600]
It would be convenient to have a mode for analyzing PAR-CLIP data in IGV. In PAR-CLIP data, regions of interest are marked by characteristic T to C (and A to G) conversions in the sequence. Thus when looking at PAR-CLIP data with IGV, reads of interest will have apparent T>C (and A>G) mismatches. Thus being able to color only these specific mismatches or color them differently than all other mismatches would be nice for visualizing PAR-CLIP data. 

I've attached a small example of PAR-CLIP data. If any more information is needed just ask.

[extdata.zip](https://github.com/igvteam/igv/files/2559224/extdata.zip)

**Comment by jrobinso** [comment]
I think that has come up before.   Are PAR-CLIP protocols generally strand-specific, as some RNA-Seq protocols are?    If so is a tag (such as XS) used to determine strand from the bam record?   If strand information isn't available then I suppose both T->C and A->G mismatches would be colored.

**Comment by jrobinso** [comment]
OK, we'll go with non-standed for now.   So all T->C & A->G mismatches will be highlighted.

If you happen to know if and how strandeness is indicated in the bam file for these experiments that would be helpful, but not essential.

**Comment by jrobinso** [comment]
Sorry this fell through the cracks.  If its still of interest please re-open it.  I will need some example aligned data, the example posted above is not aligned.   I did find some "eClip" datasets at Encode but its not clear that is the same technology.
