### ISSUE TITLE
Navigating a heavy loaded browser got more difficult in Ubuntu 18.04

### ISSUE THREAD

**Issue by alanlorenzetti** [igvteam/igv#601]
Dear IGV development team,
I recently updated my system from Ubuntu 16.04 (Unity Desktop) to Ubuntu 18.04 (Gnome Desktop) and noticed a huge difference of performance using the same version of IGV. It's almost impossible to navigate now. Tried the same session with different versions of IGV (including 2.4.15) and openjdk (java 8 and java 11), adjusted the RAM limit and the behavior persists.

The session is mainly composed by several bedgraph and annotation tracks, but no more than 50 of them. No BAM files or VCF are loaded. Do you have learned anything about that? Could you please help me to find what is the problem?

Thank you,
Alan.

**Comment by jrobinso** [comment]
I tested on Ubuntu 18.04.1 with Open JDK 1.8.0_181 with no issues.    Sorry I don't have expertise in troubelshooting Linux installs.

**Comment by alanlorenzetti** [comment]
Thank you for checking it. I will try to come up with any solution or insight.

**Comment by alanlorenzetti** [comment]
Since I had a fresh system install, the preferences were not set. I forgot that there was an antialiasing feature. Disabling antialiasing made it works as well as before. Sorry about that.

**Comment by jrobinso** [comment]
Thanks for letting us know.  Maybe we should disable that by default for Linux,  although it does work fine on my Linux box.   I will investigate disabling it.
