### ISSUE TITLE
Add --help and --version command line options [feature request]

### ISSUE THREAD

**Issue by sjackman** [igvteam/igv#611]
The Homebrew package requires a test. I'd previously been using `igv -b script` where script contains `exit` to test IGV. This test is now failing with `Unhandled exception: java.awt.HeadlessException`. I'm not sure whether it's Java or IGV or the CI system that has changed to cause this failure. See https://github.com/Homebrew/homebrew-core/pull/34787

`igv --help` and `igv --version` options that didn't require a graphical session would be helpful both for their usual reasons and as a simple test. `igv --version` would report the version of IGV, and `igv --help` could either report the command line options, or simply point the user to https://software.broadinstitute.org/software/igv/startingIGV.

In the mean time, can you suggest any command line test that does not require a graphic session?

**Comment by sjackman** [comment]
Thank you, Jim!

**Comment by helgathorv** [comment]
Released in IGV 2.8.0
