### ISSUE TITLE
Zoom in/out with +/- buttons in multi-locus view

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#616]
Allow zoom in and out with the +/- buttons in multi-locus view. All panels will be zoomed in/out. This is similar to what is currently done in igv.js.

**Comment by ranasats** [comment]
Work around for this is doing control/shift click. That will zoom in/out on both panes.

**Comment by jrobinso** [comment]
You would think this would be easy but its not.  The zoom slider is designed around a single reference frame, it would need a thorough redesign to work with 2,  or hacks that would surely lead to bugs.
