### ISSUE TITLE
Links to OMIM

### ISSUE THREAD

**Issue by fschiettecatte** [igvteam/igv#617]
The links to OMIM in the OMIM genes data set need to be updated. The canonical link to OMIM should be [https://omim.org/](https://omim.org/) and the link to individual OMIM entries should be https://omim.org/entry/######, where ###### is replaced by the MM number for example [https://omim.org/entry/134934](https://omim.org/entry/134934). See [https://omim.org/help/linking](https://omim.org/help/linking) for help on linking to OMIM. Feel free to reach out to us at [https://omim.org/contact](https://omim.org/contact) if needed

**Comment by jrobinso** [comment]
Thanks for the update!  But where are you finding these links?

**Comment by jrobinso** [comment]
OK, got it,  hg19 assembly.   I've done the updates.   Thanks for the heads up.

**Comment by fschiettecatte** [comment]
We switched to hg38 a while back and I can provide you with data for that, what would work best for you?

**Comment by jrobinso** [comment]
Any reasonable format,  bed, gff, or anything tab delimited with genomic
location and identifier for the link.   I can parse it into a format.
 Thanks,  users will appreciate it.

**Comment by fschiettecatte** [comment]
Apologies for the slow reply, I have an hg38 bed file with the same data that there is in the hg19 file. Let me how you want to receive it, and whether it would make sense to put in a process to update this data regularly. OMIM is updated daily, up to you how often you want data updates. Also not sure how up to date the hg19 data is, we don't have hg19 data anymore but I *could* rebuild for you if needed.

**Comment by jrobinso** [comment]
Hi @fschiettecatte now I have to apologize for the slow reply.    If you can provide a link to the hg38 file I can download it.   RE updates that is an important topic,  I will give it some thought.  

WRT hg19 I'm not sure its worth the effort,  most current studies seem to be on hg38.  I will be changing the default in IGV soon.   

RE updates,  yes it would make sense to update periodically.    I'm willing to write some code to do this if its automatable, and something I could do using your public APIs.

**Comment by fschiettecatte** [comment]
Hi @jrobinso, I have attached the file to this comment, let me know if you get it:

- [hg38_omim_genes.bed.gz](https://github.com/igvteam/igv/files/2903593/hg38_omim_genes.bed.gz)

For updates, the best thing would be for you to register for [OMIM downloads](https://omim.org/downloads/) and extract the data from the genemap2.txt file. This is what I used to generate the file above.

**Comment by jrobinso** [comment]
Got it.  I registered and filled out a brief description of how the data is used in IGV.  The licensing terms are confusing,  IGV is open source and use is unrestricted,  I don't know what to do about the OMIM terms or how to interpret them, but hopefully someone will read the registration blurb and respond.

**Comment by jrobinso** [comment]
@fschiettecatte Oh, re python script sure if you've got one.   That's exactly what I was going to do.

**Comment by jrobinso** [comment]
@fschiettecatte Here is the licensing text that I find problematic, on the face of it it would seem to preclude displaying this data in IGV without a specific license to do so:  "... anyone planning to redisplay or incorporate OMIM data into software MUST secure a license to obtain access to these files".

**Comment by fschiettecatte** [comment]
Hi @jrobinso, I had a short conversation with the power that be and they pointed something interesting, the genomic coordinates we use are for the NBCI reference genome which may not work for you and/or your users. We do have a [file that maps MIM numbers to gene identifiers (mim2gene.txt)](
https://omim.org/static/omim/data/mim2gene.txt) which is available with no strings attached. Would that work?

**Comment by jrobinso** [comment]
Hi @fschiettecatte ,   I'm not sure I understand the genome coordinates issue,  that should not be an issue.    However I've sent email re the license vis the official site and have not received a response.  It's not clear to me that IGV is allowed to "redisplay .... the OMIM data".   That's why I've taken no action, awaiting a response.   We should probably take this offline,  you or the power that be can contact me at igv-team (at) broadinstitute.org.   I'd like to get this resolved.    Thanks.

**Comment by fschiettecatte** [comment]
I'll pass your message on and told them to talk with you directly. I know they got your email via the official site , in the meantime we should close this issue.

**Comment by jrobinso** [comment]
Thanks @fschiettecatte
