### ISSUE TITLE
2.4.16 and 2.4.17 slower than 2.3*

### ISSUE THREAD

**Issue by RichardCorbett** [igvteam/igv#621]
Hi there,
This is a little subjective, but for me it really feels as though the contemporary versions listed above are quite a bit slower than the last versions I was using (2.3.92, or example).    Is this expected?

I'm running on Centos 7 on a machine with 32Gb or RAM where I'm allocation 8Gb of RAM to the JVM via -Xmx8g

I wonder if there is something I can check locally as I do like the indel viz stuff.

**Comment by jrobinso** [comment]
Try turning anti-aliasing off  (View > Preferences > Advanced tab).    This
is a problem with some, but not all Linux  installs.   Its actually
considerably faster on Mac, Windows, and some Linux installs.

I'm probably going to turn this off by default for Linux in the next
release.

**Comment by RichardCorbett** [comment]
Bingo!
Turning off the anti-aliasing sped up my script by 70%.

**Comment by jrobinso** [comment]
Thanks for letting me know.  I'm looking now at turning it off for Linux, or turning it off altogether.
