### ISSUE TITLE
rel 2.4.17 unable to launch

### ISSUE THREAD

**Issue by TC-Hewitt** [igvteam/igv#622]
hello,
I'm trying to start the latest release on linux with java9 but get the following error
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module org.igv not found
```
in previous versions I just run the igv.sh script or igv,jar directly no problems but this time not working. I'm unfamiliar with java. Thank you

**Comment by jrobinso** [comment]
Hi,  Java 9 is not supported, you must use Java 8 as noted on the downloads
page.    Alternatively, you can try the development snapshot build which
bundles Java 11:
http://data.broadinstitute.org/igv/projects/downloads/snapshot_java11/

**Comment by TC-Hewitt** [comment]
thanks @jrobinso. The snapshot seems to work but is this the latest release? It tells me it doesn't support sequence lengths > 2^29. I want to use 2.4.17 because it supports .csi indexes for sequences longer than this. However, when I try to run it on a linux server with java 8 it seems the the jar file it's calling is not there
```Error: Unable to access jarfile ./lib/igv.jar```
in the same scripts directory there is a subdirectory called java9 which when I try to run from there I get the same error as in the initial post. Thank you

**Comment by jrobinso** [comment]
Should be the latest,  I'll look into it.

**Comment by TC-Hewitt** [comment]
Hi @jrobinso. Seems to be working now with seqs >2^29. Thanks for the quick fix.
