### ISSUE TITLE
Feature request: Group by first/second in pair

### ISSUE THREAD

**Issue by isthisthat** [igvteam/igv#623]
I haven't found a way to sort/group all R1's together and all R2's together in a paired-end bam. The "first in pair strand" seems to be doing something else. This sorting would be useful for debugging instrument effects. Thank you.

**Comment by jrobinso** [comment]
OK, noted, you are correct there is no way to do that now.   The "first in pair strand" sorts by the read strand of the first read in a pair.   This is useful for stranded RNA.

**Comment by isthisthat** [comment]
Thanks @jrobinso! Very much appreciated.
