### ISSUE TITLE
details of IGV/ChIP-Atlas communication?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv#624]
@inutano (Tazro Inutano Ohta) of the ChIP-Atlas project suggested I contact you.  I hope this is the right forum in which to do so!

"View on IGV" is an option on the [ChIP-Atlas Peak Browser](https://chip-atlas.org/peak_browser).  Clicking this button seems to initiate communication between the chip-atlas webserver and IGV, and permit subsequent region-of-interest queries from IGV to the ChIP-alas web server.  At least this is what I understand Tazro to be saying.   He professes ignorance of the region slicing capabilities of (?) their server, saying that this is a mechanism your group provided.  I imagine bedtools, GenomicRanges, indices or related data structures and tools are used.

I hope to mimic this protocol and behavior in our own (non-competing!) webapp, [trenaViz](https://www.youtube.com/watch?v=TvGwJWmYaBI&t=368s), which we use to explore gene regulation in Alzheimer's Disease.  (I use igv.js in this shiny app.)   [trena](https://bioconductor.org/packages/release/bioc/vignettes/trena/inst/doc/TReNA_Vignette.html) and trenaViz are ongoing projects at the Institute for Systems Biology, all open source, all open data.

As best I can tell, after I click the "View on IGV" button in the Peak Browser, these things happen:

- the page somehow enables desktop IGV to connect to the ChiP-atlas server
- IGV economically requests data of the server, restricted (apparently) to IGV's currently displayed region, the user-specified Antigen Class, Cell type Class, and signficance threshold.

Can you help me emulate what IGV and ChIP-Altas so elegantly accomplish here?  

Thank you!
  - Paul Shannon
     Institute for Systems Biology

**Comment by jrobinso** [comment]
Hi Paul,
I did not know about ChIP-Atlas before, but there are a number of websites
like this out there.   It was one motivation for igv.js.

First this uses igv desktop, obviously, and we don't want to go that
direction.   What's actually going on here is more mundane that you
describe.    IGV desktop opens a port, 60151 by default,  and listens for
commands and http requests there.  Essentially it is a web server.    You
can talk to this port by creating http requests and send commands.    The
commands sent in this case are to set the genome reference and load a
file.   That's it.   Its no different than loading the files by URL from
the file menu.    IGV already uses indexes to query for slices.

You already have all you need, more than you need to do this actually, with
the igv.js api.

**Comment by jrobinso** [comment]
Specifically loadTracks and search/goto

**Comment by paul-shannon** [comment]
Thanks, Jim.  I didn't know you were still supporting IGV desktop.

I am seriously confused here.   To put my confusion on display:

- the ChIP-atlas UI offers filtering on antigen, cell type, signficance threshold
- IGV desktop filters on region, apparently retrieving only an roi slice on the tracks which meet antigen, type and significance contraints
- how are these four constraints combined into a query, then submitted where, and how?

Sorry to be so dense about this!

 - Paul

**Comment by jrobinso** [comment]
Desktop IGV is my main responsibility,  still an order of magnitude more
use than igv.js.    The web stuff is more fun though.

>
>
>    - the ChIP-atlas UI offers filtering on antigen, cell type,
>    signficance threshold
>
> OK

>
>    - IGV desktop filters on region, apparently retrieving only an roi
>    slice on the tracks which meet antigen, type and significance contraints
>
>
IGV always retrieves data for the region in view.  It knows nothing about
those other constraints.   I don't think its nearly as smart as you think
it is.


>
>    - how are these four constraints combined into a query, then submitted
>    where, and how?
>
> They aren't.   The ts you can control through the html links are
documented below.   Basically what tracks to load, what genome reference to
use,  and what regions to display

http://software.broadinstitute.org/software/igv/ControlIGV

**Comment by inutano** [comment]
Hi @paul-shannon, @jrobinso, a comment from the ChIP-Atlas side here: As described in [the documentation page of ChIP-Atlas](https://github.com/inutano/chip-atlas/wiki#assembled-peak-call-data-used-in-peak-browser), we are hosting the bed files for each combination of antigen, cell type, and threshold. From the documentation, the files are stored like below:

> Example:
> http://dbarchive.biosciencedbc.jp/kyushu-u/hg19/assembled/Oth.ALL.05.GATA2.AllCell.bed
> (All peak-call data of GATA2 in all cell types with Q-value < 1E-05.)

Therefore the ChIP-Atlas web app just selects the bed file corresponds to the slice the user selected, and give it to the IGV via HTTP. Then the IGV imports the bed file from the given URL.

The problem was that it takes a time to import the file if the bed file was too large. The one option was to make bigbed files, but we wanted to put the annotation information into the bed files so the IGV browser can show it by mouseover action. Then we've contacted the IGV team to ask how to get a part of bed files, then we've been told to use the bed file indexes. As I understand, the IGV browser can use the indexes to get a part of the remote bed file.

So I assume Paul may need to know how to use the bed index files generated by the IGV command to get the specific region of bed file.

**Comment by inutano** [comment]
Thank you @jrobinso, I've been interested in using the igv.js, but I had to keep providing our web app as it is during the publication review process (which took too long but just finished last month!). I suppose I will have a chance to update our app to use it in the future. Thanks for the heads-up!

**Comment by jrobinso** [comment]
@inutano Yes I totally understand.   If you do want to update in the future I can assist.   I'm trying to make the migration easy,  same parameters, etc,  there is just a little setup to do.

**Comment by paul-shannon** [comment]
re-opening this briefly, having only now gotten back to the topic.  Sorry for the delay.
My exploratory example is 
````
Antigen Class: TFs and others (8368)
Cell type Class: Blood(9096)
Threshold for Significance: 500
````
If I click ````Download BED file```` the download takes more than an hour.
If I click ````View on IGV````,  the track  appears in IGV desktop is less than a minute.

I have been consistently wrong on this :} so I am prepared to be wrong this time too.  But how to explain the difference in data dowload times other than that IGV requests just a slice of the large data set?

**Comment by jrobinso** [comment]
@paul-shannon did you mean to open this in IGV?   I know very little about CHiP-Atlas

**Comment by paul-shannon** [comment]
@jrobinso My bad.  I thought I saw evidence that IGV queried ChIP-atlas with ranges added.   I  was wrong.   Let's truly close this issue this time!

**Comment by jrobinso** [comment]
@paul-shannon It might well do that, its certainly capable of doing that,  but I don't know anything about it really.  @inutano should know.
