### ISSUE TITLE
CNV summary missing?

### ISSUE THREAD

**Issue by olechnwin** [igvteam/igv#625]
Hi,

I am trying to view SEG file in IGV. I modified the cbs file generated by varScan to match the example.seg in the IGV manual [SEG file format](https://software.broadinstitute.org/software/igv/SEG). I cannot figure out why my modified file test_1 (in IGV) does not have CNV summary while the example.seg file does.
![seg_visual](https://user-images.githubusercontent.com/20069067/52655707-cf6bea80-2ec2-11e9-9266-4de9693cab4a.png)

Can someone tell me why ?

I'm attaching my file: test.seg and the example from IGV: example.seg in the zip file: [seg_files.zip](https://github.com/igvteam/igv/files/2856893/seg_files.zip)
Thank you in advance for your help!

**Comment by jrobinso** [comment]
The test.seg file has a single sample, so there is nothing to summarize.

**Comment by olechnwin** [comment]
ahhh.....duh! I kept thinking that was the genome location summary. It couldn't be. Duh!
Thanks, Jim!
