### ISSUE TITLE
Removing a custom genome

### ISSUE THREAD

**Issue by anitagh** [igvteam/igv#626]
Removing a custom genome from the IGV menu will also delete the fasta file. Can you make the file deletion optional?

Thanks

**Comment by jrobinso** [comment]
Actually it shouldn't do that,  that is a bug.   It should only remove the
fasta if you downloaded it automatically from our hosted set.

**Comment by jrobinso** [comment]
@anitagh what version of IGV are you using?

**Comment by anitagh** [comment]
I apologize for the late response. I'm running version 2.4.16 
    On Tuesday, February 12, 2019, 2:55:17 PM EST, Jim Robinson <notifications@github.com> wrote:  
 
 
@anitagh what version of IGV are you using?

**Comment by jrobinso** [comment]
Are you sure it did not ask you before deleting the fasta file?  I have not been able to reproduce it (without the confirmation prompt),  and examining the code I can't find a path where it deletes the fasta without a confirmation prompt.   Nevertheless I added a further check,  it will only delete fastas (after confirmation)  in subdirectories of the "igv" folder.   These directories are caches and shouldn't be used to store user data.    If users download genomes from our server and click "include sequence" the fastas go here.

**Comment by anitagh** [comment]
Hi Jim,
Thanks for the quick response.  I'm running the windows version of the igv tools. I don't see any prompts.Should I download the latest version now?
Best,Azita

    On Thursday, February 14, 2019, 1:55:15 PM EST, Jim Robinson <notifications@github.com> wrote:  
 
 
Are you sure it did not ask you before deleting the fasta file? I have not been able to reproduce it (without the confirmation prompt), and examining the code I can't find a path where it deletes the fasta without a confirmation prompt. Nevertheless I added a further check, it will only delete fastas (after confirmation) in subdirectories of the "igv" folder. These directories are caches and shouldn't be used to store user data. If users download genomes from our server and click "include sequence" the fastas go here.

**Comment by jrobinso** [comment]
No the fix has not been released yet.   It will be in release 2.4.19 by the
end of the week.

**Comment by anitagh** [comment]
Thank you

**Comment by jrobinso** [comment]
One thing I should point out, do not put your own custom genomes, or any
files in the "igv/genomes" folder or any folder under "igv".   These are
meant for IGV program use,  and are used to cache genomes downloaded from
our server.

**Comment by anitagh** [comment]
Absolutely! Thank you
    On Thursday, February 14, 2019, 8:01:57 PM EST, Jim Robinson <notifications@github.com> wrote:  
 
 One thing I should point out, do not put your own custom genomes, or any
files in the "igv/genomes" folder or any folder under "igv". These are
meant for IGV program use, and are used to cache genomes downloaded from
our server.

**Comment by jrobinso** [comment]
I just released 2.4.19 which should not delete any fasta files outside the "igv/genomes" folder.
