### ISSUE TITLE
Issue with BAM file viewing

### ISSUE THREAD

**Issue by sagnikbanerjee15** [igvteam/igv#627]
Hello,

Thank you for updating IGV with the latest version of htsjdk. I downloaded the latest IGV and was attempting to view alignments. I work with barley which has chromosomes greater than 2^29-1. I was able to load the genome and also view the gene annotations which was provided to IGV in gff3 format. As for the alignments, I generated a csi index. I loaded the bamfile and entered a coordinate I wished to view. I got the following error - "Error encountered querying alignments: htsjdk.samtools.SAMException: Unexpected number of metadata chunks 3". Please see the attached image.

Thank you.
![image](https://user-images.githubusercontent.com/23457977/52816456-e4817e80-3066-11e9-9ec2-e3dfe5d3489e.png)

_Originally posted by @sagnikbanerjee15 in https://github.com/igvteam/igv/issues/96#issuecomment-463787656_

**Comment by jrobinso** [comment]
Apologies for the long delay, this issue was missed.  CSI indices are now supported,  please re-open this issue if you still have problems.
