### ISSUE TITLE
Suppressing Filtered Sites and Jumping Causes GUI Freeze

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv#629]
I can load a VCF file and jump from one feature to the next by pressing Ctrl-F. If I right-click and choose Suppress Filtered Sites, I can still slide the track by left-clicking and dragging to move the view. However, if I press Ctrl-F again, because I only want to view SNPs that are PASS, IGV freezes but it's using 100% of 1 CPU and doesn't respond to any user clicks anywhere in the GUI. It has to be killed from the operating system.

**Comment by jrobinso** [comment]
Hi @DarioS ,  I'm reviewing issues, this one got dropped.   I can't reproduce this with the VCF files I have available, if its still an issue can you re-open and attach a small example VCF that exhibits the problem?  Thanks.
