### ISSUE TITLE
Error parsing gff

### ISSUE THREAD

**Issue by melanieabrams** [igvteam/igv#630]
Hi,

When I try and load a .gff annotation file, I receive an error message: 

Error loading /Users/Melanie/Desktop/Melanie/NGS/Spar.gff: Error parsing line at byte position: LineIteratorImpl(SynchronousLineReader), for input source: /Users/Melanie/Desktop/Melanie/NGS/Spar.gff

The first few lines of my gff file are below (since github wouldn't allow uploading of a .gff) - any idea what could be causing the problem?

Thank you!
Melanie

10	Scannell_and Zill 2011	gap	1	1098		+	-	ID=1690892879902958018;ygobhmm=1e+100;none=;manual=-1e+100;SGD=;Gene=Spar_10.1;Parent=Spar_10.1;kaks2=-1e+100;struct=0;ltr=1e+100;hsp=1e+100;hcnf=0;aa=1e+100;lda=-1e+100;rna=-1e+100;synt=0;YGOB=;stop=0;introns=0;BLAST=;ncbi=1e+100;kaks=1e+100;nnnn=1e+100;length=1098;hmm=-1e+100;Name=Spar_10.1;ty=1e+100
10	Scannell_and Zill 2011	CDS	1099	1317	Anc_5.395	+	0	ID=1690892879902971809;ygobhmm=3.3e-08;none=;manual=-1e+100;SGD=YOL156W;Gene=Spar_10.2;Parent=Spar_10.2;kaks2=-1e+100;struct=1;ltr=1.1;hsp=8e-09;hcnf=0;aa=8e-09;lda=-1e+100;rna=-1e+100;synt=0;YGOB=Anc_5.395;stop=0;introns=0;BLAST=YOL156W;ncbi=1e+100;kaks=1e+100;nnnn=-1e+100;length=219;hmm=-1e+100;Name=Spar_10.2;ty=1e+100
10	Scannell_and Zill 2011	CDS	1220	1741	Anc_5.394	+	0	ID=1690892879902985709;ygobhmm=1.9e-93;none=;manual=-1e+100;SGD=YJL219W;Gene=Spar_10.3;Parent=Spar_10.3;kaks2=-1e+100;struct=2;ltr=2.7;hsp=3e-82;hcnf=0;aa=3e-82;lda=-1e+100;rna=-1e+100;synt=3;YGOB=Anc_5.394;stop=0;introns=0;BLAST=YOL156W;ncbi=1e+100;kaks=1e+100;nnnn=-1e+100;length=522;hmm=-1e+100;Name=Spar_10.3;ty=1e+100
10	Scannell_and Zill 2011	CDS	2529	3119	Anc_8.700	+	0	ID=1690892879902999823;ygobhmm=0.35;none=;manual=-1e+100;SGD=YJL218W;Gene=Spar_10.4;Parent=Spar_10.4;kaks2=-1e+100;struct=2;ltr=0.77;hsp=2e-104;hcnf=0;aa=2e-104;lda=-1e+100;rna=-1e+100;synt=2;YGOB=Anc_8.700;stop=0;introns=0;BLAST=YJL218W;ncbi=1e+100;kaks=1e+100;nnnn=-1e+100;length=591;hmm=-1e+100;Name=Spar_10.4;ty=3.7

**Comment by jrobinso** [comment]
I'll need the file.  You can zip it and upload the zip.

**Comment by melanieabrams** [comment]
Here's the zip!
[Spar.gff.zip](https://github.com/igvteam/igv/files/2907728/Spar.gff.zip)

**Comment by jrobinso** [comment]
Column 8 should be the reading frame, allowed values are 0, 1, and 2.   It can also contain "." to indicate not known or not applicable.  In your file it is a "-" sign.
