### ISSUE TITLE
Filter interaction loops based on score

### ISSUE THREAD

**Issue by ozturan** [igvteam/igv#631]
Hi everybody,

I'm always using IGV over WashU browser, however when I want to visualize looping data (i.e. .bedpe or any 3C-based data), I have no choice but to use WashU. My question: is there any chance that we will see an update on the horizon for IGV about this issue?

Best,
Dogancan

**Comment by jrobinso** [comment]
Hi,  bedpe is supported now for loops,  its not been announced but give it
a try.   I'll be officially releasing it soon.

This is also supported in igv.js and the igv webapp  (igv.org/app).

**Comment by ozturan** [comment]
Grreat news!

Thank you very much.

Best,
Dogancan

**Comment by jrobinso** [comment]
@ozturan I'll leave this open as a reminder to release it,  please post feedback on it here.   This was coded for a specific project and has some options hard coded.

**Comment by ozturan** [comment]
My first impression would be this: I think there should be a filtration system based on the interaction frequency. Setting the height is OK but if I can get only some of the loops based on the interaction frequency, that would be great. I don't know whether it's doable though.

**Comment by jrobinso** [comment]
Where is interaction frequency recorded?  Could you attach a small example
file?   You can attach it if you zip it first

**Comment by ozturan** [comment]
Here is an example of a .bedpe file:
`chr19	51354185	51354205	chr19	51376439	51376459  43`

last column is the interaction frequency. Like setting height for the ChIP-seq track it would be wonderful to set the frequency for these kinds of tracks.

**Comment by jrobinso** [comment]
OK, but that's a non-standard field.    In fact that field should be a string name.    Its not clear how to support this in a general way with arbitrary fields.

https://bedtools.readthedocs.io/en/latest/content/general-usage.html

**Comment by jrobinso** [comment]
@ozturan Any ideas on how to tell IGV this is an "interaction" bedpe file.  Again its not a legal bedpe file, as it breaks the specification for the 7th column.  The score (value) should be the 8ths column.  I assume there exists a lot of these in the wild.    If we can require a .bedpe extension I can probably hack IGV to treat this column as a score by checking that all values in the entire column are numbers.     Below is the track I'm working on to support this.  
<img width="1262" alt="Screen Shot 2019-06-19 at 3 05 57 PM" src="https://user-images.githubusercontent.com/933148/59804849-5df2dd00-92a4-11e9-8b3b-8f361fa545aa.png">

**Comment by jrobinso** [comment]
OK interaction frequency is parsed now with the special rule alluded to above, if all values of the "name" column are numeric it is interpreted as a score.   The interaction frequency filter is on my list.

**Comment by jrobinso** [comment]
@ozturan most of this request is released in v 2.6, however the filter by score is not released,  I've renamed the issue to reflect that and will leave it open.

**Comment by olechnwin** [comment]
@jrobinso,
Apologize for asking this stupid question. I'm using IGV 2.6.0, loaded the bedpe file that only contain 4 lines:
`

chrom1 | start1 | stop1 | chrom2 | start2 | stop2 | name | qual | strand1 | strand2 | filters | info
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chr9 | 130700000 | 130710000 | chr9 | 130870000 | 130880000 | 43 | . | . | . | . | .
chr9 | 137980000 | 137990000 | chr9 | 138040000 | 138050000 | . | . | . | . | . | .
chr19 | 51354185 | 51354205 | chr19 | 51376439 | 51376459 | 43 |   |   |   |   |  

`
It loaded with no error. However, I cannot see the interaction arc.
![igv_test_bedpe](https://user-images.githubusercontent.com/20069067/61643891-c2250a00-ac71-11e9-9a7b-b8627051aad7.png)

How do I view the interaction? Thank you in advance for your help

**Comment by jrobinso** [comment]
Can you zip and attach the bedpe file here?    It needs to be a tab-delimited plain text file.  Also,  I don't think the header line is legal, if you want to keep it put a # symbol in front to make it a comment.

**Comment by olechnwin** [comment]
@jrobinso, 
Thank you for your help.
I'm attaching the bedpe file. I put # symbol in front for the header line. This time, it gave me an unexpected error.
[test.zip](https://github.com/igvteam/igv/files/3418498/test.zip)

**Comment by jrobinso** [comment]
There's a couple of potential problems,  1 with the file and 1 with IGV.

* File issue -- scores (qual)  appear to be in the name column, is this
intentional?

* The IGV issue is the "." is not accepted as a valid score, its failing if
the score is not a number.   BedPE allows strings for scores so this is a
bug.

I will fix the score parsing bug.   What software produced this file?   Is
this a 10X output?

**Comment by olechnwin** [comment]
Ah...I finally get why you want me to zip the bedpe file. Sorry.
I'm attaching the original .bedpe file that was generated using HICCUPS.
I had to modify the file and since it keeps failing, I made another file keeping only two lines and add another line manually.
Is there a good bedpe file I can try to view in IGV? Thanks!
[loops.zip](https://github.com/igvteam/igv/files/3418623/loops.zip)

**Comment by jrobinso** [comment]
If this was generated by HICCUPS I'll change the parser to support it.
 Its not a legal bedpe file due to the header  but that's o.k. easy to
fix.    The modified file you posted looked a little like a 10X output
which was confusing IGV.

Stay tuned

**Comment by olechnwin** [comment]
Thank you so much for your quick help! Looking forward to view this file in IGV.

**Comment by olechnwin** [comment]
@jrobinso, super cool! I can see the loops now.
Thank you so much for your quick support. You guys are the best! Much better support than some companies.
Sorry I didn't see this message sooner. Somehow I didn't get notification when you added a commit.

**Comment by jrobinso** [comment]
This is a long issue thread with multiple topics, I think they have all been addressed but if not please open a new issue.
