### ISSUE TITLE
RefSeq gene names not properly aligned in split view in batch script

### ISSUE THREAD

**Issue by slw287r** [igvteam/igv#633]
Dear IGV developers,

I tried to screenshot structure variation in split view behind Xvfb, however, the RefSeq gene names are not properly displayed. It's not related to bams loaded.

* batch script (sv.bat)

```
new
genome hg19
goto 2:29447977-29447977 2:45619224-45619224
maxPanelHeight 65536
snapshot sv.png
```

* command

```
(Xvfb :1 -fp PATH_TO/lib/X11/fonts/misc &) && DISPLAY=:1 igv.sh -g hg19 -b sv.bat
```

* screenshot

![sv](https://user-images.githubusercontent.com/4134899/53693100-52070c00-3dd6-11e9-963b-c41b78dc1a64.png)

btw, IGV version: IGV_Linux_snapshot 20-Feb-2019

Thank you,
Richard

**Comment by jrobinso** [comment]
Yes I can reproduce it.  Its a problem with the image snapshot generally.

**Comment by jrobinso** [comment]
I pushed a fix for this, it will be in the next release (2.7.1).  Apologies for the long delay.
