### ISSUE TITLE
setSleepInterval Config

### ISSUE THREAD

**Issue by robertaboukhalil** [igvteam/igv#635]
Hi!

I'm using IGV to generate screenshots by sending commands through a port as described in https://software.broadinstitute.org/software/igv/PortCommands.

I just noticed the `setSleepInterval` setting. When I set it to 0, the screenshots are generated much faster. My understanding is that IGV commands get executed synchronously, so I'm curious whether there are cases when `setSleepInterval` should not be set to 0?

**Comment by jrobinso** [comment]
@robertaboukhalil apologies for the very long delay,  this got missed.  If its still of interest,  you are correct, theoretically all commands run synchronously and the delay should not be necessary.    If you find no ill effects (e.g. blank images) go for 0.    If you do find problems with this setting you can reopen this with a description.  Sorry again for the delay.
