### ISSUE TITLE
IGV cannot load Sniffles-produced VCF files due to version in header

### ISSUE THREAD

**Issue by oneillkza** [igvteam/igv#637]
I've been using Sniffles (https://github.com/fritzsedlazeck/Sniffles) to do SV calling from long reads. When I try to load the VCFs, IGV throws the following error:

```
Your input file has a malformed header: VCFv4.3 is not a supported version, for input source:
```

Editing these files to change the first line from:

```
##fileformat=VCFv4.3
```

to 

```
##fileformat=VCFv4.1
```

seems to solve this, and allows IGV to load the file fine. This is a little hacky, though, and it would be good if IGV were able to just load these files (assuming there isn't a strong reason why it might fail on other VCFv4.3 files).

**Comment by jrobinso** [comment]
You did not specify what version of IGV you are using.   This is important.    Assuming you are using the latest version, it looks like this is actually an issue with the htsjdk, you can follow or comment on it here:  https://github.com/broadinstitute/gatk/issues/2602

Changing the header line might work for your VCFs if they don't use v4.3 specific features,  but officially v4.3 is not supported by the htsjdk.

**Comment by oneillkza** [comment]
I'm using `2.4.18 02/05/2019 03:38 AM`, so a pretty recent one.

Thanks for the explanation -- it's a bit frustrating, but I guess we just have to wait for the upstream library.

**Comment by jrobinso** [comment]
This is resolved in the latest release.
