### ISSUE TITLE
IGV freezes when panning across a tdf file 

### ISSUE THREAD

**Issue by kevinslang** [igvteam/igv#641]
When viewing a tdf file made with igvtools, igv times-out when panning across the genome. None of the files are particularly large as they are prokaryotic genomes and chip-seq data. 

My machine shouldn't be an issue, 12 gb ram, i7 64 bit processor. Though, maybe this assumption is incorrect.

Anyone else have this issue?

**Comment by jrobinso** [comment]
I haven't seen or had reports of this issue.   What version of IGV are you using?

**Comment by kevinslang** [comment]
This only happens when I run 2 or more tdf tracks. 

I'm running IGV 2.5.0 on Ubuntu with 10g of memory, but the same thing happens when running with 4 or 8 g of memory specified.

**Comment by jrobinso** [comment]
The attached session loads 4 tdf files, could you load it (unzip then File > Open Session) and see if you can reproduce the problem with it.    Also, please attach your ig.log file.   
[tdf_session.xml.zip](https://github.com/igvteam/igv/files/3019567/tdf_session.xml.zip)

**Comment by kevinslang** [comment]
I can't recapitulate the issue using the session provided. It runs a bit slow but doesn't completely stall out like it does on my session. 

I'm not exactly sure how or when the log files are generated, so I'm attaching all of them. Should I delete them, start a new session and reproduce the problem and then send that log?

[igv:igv-1.log](https://github.com/igvteam/igv/files/3040840/igv.igv-1.log)
[igv:igv-2.log](https://github.com/igvteam/igv/files/3040841/igv.igv-2.log)
[Uploading igv:igv-3.log…]()
[Uploading igv:igv-4.log…]()
[Uploading igv:igv-5.log…]()
[Uploading igv:igv-6.log…]()
[igv:igv-7.log](https://github.com/igvteam/igv/files/3040846/igv.igv-7.log)

**Comment by kevinslang** [comment]
[igv:igv-3.log](https://github.com/igvteam/igv/files/3040854/igv.igv-3.log)
[igv:igv-4.log](https://github.com/igvteam/igv/files/3040855/igv.igv-4.log)
[igv:igv-5.log](https://github.com/igvteam/igv/files/3040856/igv.igv-5.log)
[igv:igv-6.log](https://github.com/igvteam/igv/files/3040857/igv.igv-6.log)

**Comment by jrobinso** [comment]
yes, delete the logs, restart, and attach the new one.

**Comment by jrobinso** [comment]
The slowness could be your network.  Slowness is in the eye of the beholder
I guess but its zippy for me.

**Comment by kevinslang** [comment]
The network could definitely be the issue for the slowness. Here are the new logs. I've realized that this issue arises when looking at combined tdf tracks. I use the combine tracks tool to normalize chip results to input for example.


[igv:igv-1.log](https://github.com/igvteam/igv/files/3044510/igv.igv-1.log)
[igv:igv-2.log](https://github.com/igvteam/igv/files/3044511/igv.igv-2.log)
[igv:igv-3.log](https://github.com/igvteam/igv/files/3044512/igv.igv-3.log)
[igv:igv-4.log](https://github.com/igvteam/igv/files/3044513/igv.igv-4.log)
[igv:igv-5.log](https://github.com/igvteam/igv/files/3044514/igv.igv-5.log)
[igv:igv-6.log](https://github.com/igvteam/igv/files/3044515/igv.igv-6.log)
[igv:igv-7.log](https://github.com/igvteam/igv/files/3044516/igv.igv-7.log)

**Comment by jrobinso** [comment]
@kevinslang thanks, but why so many logs?   Were all those logs created fresh from a single run?

**Comment by jrobinso** [comment]
@kevinslang Also, what do you mean by "use the combine tracks tool".   There are no igv options that I'm aware of with that name.    If I can reproduce your issue I can fix it, so far I can't.   The logs do not give quite enough information to isolate the problem.

**Comment by kevinslang** [comment]
They were all created from the single run. I deleted all logs as you suggested, reproduced the issue and then looked back at the file path and they were all there. 

The "combined data tracks" option is found under the Tools dropdown menu.

**Comment by jrobinso** [comment]
OK, I had forgotten about that option.   Still, I can't reproduce your problem.  If I can reproduce your it I can fix it.   The logs do not give quite enough information to isolate the problem.   If you can zip up a test case and give me exact steps to reproduce it that would be a help.

**Comment by kevinslang** [comment]
I've found a work around using deepTools to normalize coverages and produce bedgraph files. If you're still interested in potentially solving this issue with the combine tracks option, I can send some files. However, is there a way to send the files privately, I'm working with unpublished data.

**Comment by jrobinso** [comment]
Hi Kevin,  I'm glad you found a workaround, but yes I'd still like to solve
this problem.   If they are small enough to zip and email you can send them
to  igv-team (at) broadinstitute.org.    Alternatively I can maybe figure
out a way for you to upload them to our dropbox account.

Thanks
