### ISSUE TITLE
Feature request: Support multiple flavors of MAF files

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#642]
In addition to supporting the [official TCGA definition of a Mutation Annotation File (MAF)](https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/), Chip S. says they use two other 'liter' versions of MAF (I put some test files in a "maf" directory in the igv test data directory.)

1) A version that omits some fields that are not relevant to rendering the data (e.g. Center, NCBI Build, and more).  -- Loading the test file (test.maf) results in parser errors in the MUTCodec.

2) A relaxed [maf lite format as described on the gatk forum](https://gatkforums.broadinstitute.org/gatk/discussion/4151/oncotator-overview-and-basic-usage).  -- Loading the original test file (test.maflite.tsv) causes the file to be read in as a sample attribute file. Renaming the file to testlite.maf and reading it in, causes it to be read in as Multiple Annotation File.

NOTE: In IGV 2.5 we've lost the ability to color the mutations by type.  The legend is available under View > Color Legends. But the checkmark to enable coloring by mutation type is gone from the Preference window.

**Comment by jrobinso** [comment]
@helgathorv What directory are you referring to ("igv test data directory")?

**Comment by jrobinso** [comment]
The two non-standard MAF formats should now work (snapshot build).  

The "maf lite" files must conform to the format described here:  https://gatkforums.broadinstitute.org/gatk/discussion/4151/oncotator-overview-and-basic-usage.
Specifically there must be a column header line, and the following exact headers are required: 

* build
* chr
* start
* end
* ref_allele
* alt_allele

**Comment by jrobinso** [comment]
@helgathorv @chipstewart re color-by-type,  that legend is very old,  pre TCGA even, and that collection of types is hard-coded.    If bringing back the coloring option is desirable let's open a new git issue and discuss how to do it.   Hard-coded type names and colors?  It would be very hard to modify that old UI.

**Comment by jrobinso** [comment]
This should be fixed now, except for color-by-type (see note above)
