### ISSUE TITLE
igvtools fails to launch for JDK 8 with Unrecognized option: --module-path=

### ISSUE THREAD

**Issue by dinvlad** [igvteam/igv#643]
Hi Team,

We're trying to run IGVTools in a Docker container that only has JDK8 in it. The `igvtools` launcher script fails with `Unrecognized option: --module-path=/opt/lib`. This is an indication it's trying to pass `--module-path` argument to the JDK, which is not supported by JDK8. Is there any way to make it work for JDK8 again?

Thank you

**Comment by jrobinso** [comment]
You'll need to go back in the archive and get an earlier version,  or build
from a 2.4.X tag.

**Comment by dinvlad** [comment]
We figured out how to upgrade to JDK13. This is a rather breaking change, so it would be nice if this requirement was highlighted on the download page (I know it is in this repo's README, but that's only for those who want to _build_ IGV from source).

**Comment by jrobinso** [comment]
The download for igvtools states "requires Java 11",  what else would you
like to see?

**Comment by jrobinso** [comment]
You are correct it is a breaking change, so probably should get a major
version number,  but the versions are driven by the igv application.   It
is not a breaking change there, as the jre is included.

**Comment by dinvlad** [comment]
Ah, I see - thanks. I think I was using the link without `jdk-11` from http://data.broadinstitute.org/igv/projects/downloads/2.5/, but now I see that this was intended to be 2nd link at
<img width="581" alt="Screen Shot 2019-04-01 at 2 31 48 PM" src="https://user-images.githubusercontent.com/137337/55350871-07d38200-548b-11e9-83c9-10860915399b.png">

That being said, I think the second link (all platforms) actually points to "Linux" ZIP. Perhaps that needs to be fixed.

**Comment by dinvlad** [comment]
Additionally, could you confirm that the "IGV for Linux" doesn't bundle IGVTools, so we have to use the 2nd link (when it's fixed)?

**Comment by helgathorv** [comment]
And yes, to get igvtools, you need to download from the "IGV and igvtools to run on the command line" link. igvtools is not in the "IGV for Linux" bundle.
