### ISSUE TITLE
copy sequence from read within specific region

### ISSUE THREAD

**Issue by olechnwin** [igvteam/igv#644]
Hello,
I am wondering whether it is possible to copy sequences from a read within a specific region? If I put in region of interest, I can zoom in to the region and copy the sequences of the reference genome. I would like to be able to copy the sequences of a read in that region only. Is this possible?

Thank you!

**Comment by jrobinso** [comment]
Sorry that's not possible, and would be somewhat difficult to implement.

**Comment by olechnwin** [comment]
Thank you for letting me know.
