### ISSUE TITLE
IGV 2.5 doesn't allow to search for e.g. X:10-1000 instead of chrX:10-1000

### ISSUE THREAD

**Issue by GinaRe** [igvteam/igv#645]
IGV 2.5 doesn't allow to search for e.g. X:10-1000 instead of chrX:10-1000.
Furthermore, if I open a bed or bw file, all chromosomes (2L/2R/3L/3R/4) are displayed properly but not X. If I rename X into chrX, it works.
It would be nice if Ensemble gene IDs would be supported in IGV 2.5

**Comment by jrobinso** [comment]
I don't understand this,  could you elaborate?  "X" is not a chromosome name for any assembly I am aware of.    The alias for "chrX"  is  "23".

Re Ensemble gene IDs you can load any annotation file that you want in a supported format (bed, gff, gtf).

**Comment by GinaRe** [comment]
In flies, namely Drosophila melanogaster (Dm6), the chromosome names are 2L, 2R, 3L, 3R, 4, X and Y. X and Y are the sex chromosomes.

**Comment by jrobinso** [comment]
Ah, apologies, I assume you were referring to human.  Technically "dm6" is
the UCSC version which uses chrX.   I will make a note to add an alias for
that assembly.

Is this what you mean bye  "Ensemble gene IDs"?   If not could you expand
on that?

**Comment by GinaRe** [comment]
Thanks, it would be great if you could add an alias for this.

**Comment by jrobinso** [comment]
It should allow it now.

**Comment by GinaRe** [comment]
Can I get the working IGV branch from github or should I wait for a new IGV release?

**Comment by jrobinso** [comment]
You shouldn't need to do anything,  its in the .genome file.   If its not
working shut down IGV,  go to the "igv/genomes" folder, and delete
dm6.genome.   Then restart IGV and load that genome again.

**Comment by GinaRe** [comment]
Thanks, it's working now.
