### ISSUE TITLE
not showing any alignments

### ISSUE THREAD

**Issue by juancrescente** [igvteam/igv#647]
I downloaded latest version and suddenly stopped seeing alignments in all genomes and bam files:

```
samtools view -c merged_alignments_21.bam "4B:600374555-600374577" 
1511

samtools view  merged_alignments_21.bam "4B:600374555-600374577" | head
HWI-1KL178:62:H8HLVADXX:1:2113:16322:56166	0	4B	600374555	255	21M	*	0	0	AGGTGCGGCTGGATCACCTCC	*	XA:i:0	MD:Z:21	NM:i:0	XM:i:62	XX:i:61	XY:Z:P	XZ:f:0.036	RG:Z:21dpiR1C.trimmed
HWI-1KL178:62:H8HLVADXX:1:1102:20843:33717	0	4B	600374555	255	21M	*	0	0	AGGTGCGGCTGGATCACCTCC	*	XA:i:0	MD:Z:21	NM:i:0	XM:i:62	XX:i:61	XY:Z:P	XZ:f:0.036	RG:Z:21dpiR1T.trimmed
HWI-1KL178:62:H8HLVADXX:1:1110:19603:48897	0	4B	600374555	255	21M	*	0	0	AGGTGCGGCTGGATCACCTCC
...

java -version   
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)

```

I load that file and genome, go to position "4B:600374555-600374577" and pum! nothing at all. Under preferences -> alignments have mapping and alignment quality treshold both to 0.

This is the output of the program:

```
sh igv.sh
Bundled JDK not found.  Using system JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
WARN [2019-04-23T11:15:34,505]  [Globals.java:138] [AWT-EventQueue-0]  Development mode is enabled
INFO [2019-04-23T11:15:34,528]  [DirectoryManager.java:179] [AWT-EventQueue-0]  IGV Directory: /home/juan/igv
INFO [2019-04-23T11:15:34,556]  [Main.java:155] [AWT-EventQueue-0]  Startup  IGV Version 2.5.1 04/17/2019 08:50 PM
INFO [2019-04-23T11:15:34,558]  [Main.java:156] [AWT-EventQueue-0]  Java 11.0.2
INFO [2019-04-23T11:15:34,558]  [DirectoryManager.java:84] [AWT-EventQueue-0]  Fetching user directory... 
INFO [2019-04-23T11:15:34,617]  [Main.java:157] [AWT-EventQueue-0]  Default User Directory: /home/juan
INFO [2019-04-23T11:15:34,618]  [Main.java:158] [AWT-EventQueue-0]  OS: Linux
INFO [2019-04-23T11:15:36,252]  [GenomeManager.java:195] [pool-3-thread-1]  Loading genome: /home/juan/Desktop/juan/bio/data/IWGSC/42/Triticum_aestivum.IWGSC.dna.toplevel.fa
INFO [2019-04-23T11:15:36,287]  [GenomeComboBox.java:79] [AWT-EventQueue-0]  Enter genome combo box
INFO [2019-04-23T11:15:36,723]  [GenomeComboBox.java:79] [AWT-EventQueue-0]  Enter genome combo box
INFO [2019-04-23T11:15:36,731]  [GenomeManager.java:287] [pool-3-thread-1]  Genome loaded.  id= /home/juan/Desktop/juan/bio/data/IWGSC/42/Triticum_aestivum.IWGSC.dna.toplevel.fa
INFO [2019-04-23T11:15:36,736]  [CommandListener.java:120] [Thread-4]  Listening on port 60151
INFO [2019-04-23T11:15:42,568]  [IGV.java:1345] [pool-3-thread-2]  Loading 1 resources.
INFO [2019-04-23T11:15:42,575]  [TrackLoader.java:122] [pool-3-thread-2]  Loading resource, path /home/juan/Desktop/juan/bio/mrcv/data/ss/GTP/merged_alignments_21.bam
INFO [2019-04-23T11:15:54,397]  [AlignmentTrack.java:264] [pool-2-thread-2]  Experiment type = OTHER

```
I'm using Ubuntu 18.04.  I'm really confused, don't know if I'm missing something or is it my installation?

**Comment by jrobinso** [comment]
Those coordinates look large, what type of index are you using (bai or csi)?   Could you extract a slice of the bam around this location, zip, and attach it?

**Comment by juancrescente** [comment]
I'm using a csi index. 
I'm attaching the result of this:

`samtools view  merged_alignments_21.bam "4B:600374555-600374577" > splice.sam`

[splice.zip](https://github.com/igvteam/igv/files/3108628/splice.zip)

**Comment by jrobinso** [comment]
Thanks but I can' use the file without the header,  try

```
samtools view -b merged_alignments_21.bam "4B:600374555-600374577" > splice.bam
```

**Comment by juancrescente** [comment]
@jrobinso sorry about that
[splice.zip](https://github.com/igvteam/igv/files/3112096/splice.zip)

**Comment by jrobinso** [comment]
@juancrescente ,  I'm not sure what this is, just the header?  Could you please run this, it should give you a bam file I can index and use directly.    Is this what you ran?
```
samtools view -b merged_alignments_21.bam "4B:600374555-600374577" > splice.bam
```

**Comment by jrobinso** [comment]
Note that's a "-b" not a "-h"

**Comment by jrobinso** [comment]
Also, if its possible to make the fasta available for this chromosome/contig that would be helpful.   If not I will have to simulate one.

Did this every load on any version of IGV?  That is important information as well.  The support for ".csi" files was added fairly recently.

**Comment by juancrescente** [comment]
Sorry again. I attach the file and this is the genome I'm using, is the latest wheat genome available:

ftp://ftp.ensemblgenomes.org/pub/plants/release-43/fasta/triticum_aestivum/dna/
773d7a2216e7e5dce0e27ee1e66d7780  Triticum_aestivum.IWGSC.dna.toplevel.fa
6388dc6ff85c9ec8c68e29422e9efab4  Triticum_aestivum.IWGSC.dna.toplevel.fa.gz

I'm using IGV_2.5.1 in Ubuntu. Thank you for your patience

[splice.zip](https://github.com/igvteam/igv/files/3113582/splice.zip)

**Comment by jrobinso** [comment]
I can't reproduce any problem, it works fine for me (see screenshot).   Here's what I did.

The file you sent was a sam file,  did you forget the "-b"?    I created a bam file and index as follows

```
samtools view -b splice.sam  > splice.bam
samtools index -c splice.bam
```
I then loaded the chromosome 4B fasta and jumped to 4B:600374555-600374577.  This is what I see.   My only suggest would be to try recreating the index.

<img width="1262" alt="Screen Shot 2019-04-24 at 11 18 19 AM" src="https://user-images.githubusercontent.com/933148/56683793-2809f180-6683-11e9-8362-a56a579b2c74.png">

**Comment by juancrescente** [comment]
is there any other option besides mapping quality and alignment score that can hide reads?

**Comment by jrobinso** [comment]
There are lots of alignment options,  I don't know what you might have set or not set.   To reset to default do the following.   Shut down IGV,  make sure you don't have any IGV running.    Then,  delete or rename the "prefs.properties" file in your "igv" folder, under your home directory.   Then restart IGV and try again.

If this doesn't work try doing exactly what I did, create the bam and index as I noted above from the "splice.sam" file you sent me.   Use the commands exactly, cut and paste,  don't type them.  You did not create a bam file, so in following my original instructions you did not type it correctly,  so just use cut and paste to be sure.   Then   load  "slice.bam" and jump to your alignment.   If you see nothing attach a screenshot.

**Comment by juancrescente** [comment]
Indeed I see nothing

```
samtools view -h merged_alignments_21.bam "4B:600374555-600374577" > splice.sam
samtools view -b splice.sam  > splice.bam\n
samtools index -c splice.bam\n

```
![Screenshot from 2019-04-24 16-14-27](https://user-images.githubusercontent.com/2141907/56687162-11c45b80-66ac-11e9-9bea-37b742fdddd2.png)

**Comment by jrobinso** [comment]
I doubt seriously its a java problem, but I don't understand those warnings.   How exactly did you install IGV?

**Comment by jrobinso** [comment]
I asked earlier in what version of IGV these files worked for you.   If you think its a recent problem you can get access to archived versions here:  http://data.broadinstitute.org/igv/projects/downloads/

**Comment by juancrescente** [comment]
I downloaded it (igv for linux) and execute `sh igv.sh`

**Comment by jrobinso** [comment]
OK, I'm out of ideas.   Its not a java problem though, if it were the app wouldn't load.  

This is the third time I have asked, and sorry for being a pest, but in what version of IGV has this worked for you in the past?

**Comment by juancrescente** [comment]
I was using IGV_2.4.14, which is not working anymore. I updated in order to use .csi indexes. While updating I had to update java version to 11

**Comment by juancrescente** [comment]
any ideas why I cannot start IGV from jar file in this new version?

```
java -Xmx12g -jar lib/igv.jar
çError: Unable to initialize main class org.broad.igv.ui.Main
Caused by: java.lang.NoClassDefFoundError: htsjdk/samtools/seekablestream/ISeekableStreamFactory

```

**Comment by jrobinso** [comment]
Look at the shell script.

**Comment by jrobinso** [comment]
csi indexes will be supported in the later releases of 2.4.X

**Comment by helgathorv** [comment]
In particular try 2.4.18 or 2.4.19 from the archived release releases on the IGV downloads page.

> csi indexes will be supported in the later releases of 2.4.X

**Comment by juancrescente** [comment]
Same files under a different computer seems to work just fine. There's definitly something with my machine I cannot debug

**Comment by laurajohnson** [comment]
In downloaded and installed v2.9.4 on my mac running Catalina today. I wasn't able to see any bam files in IGV. I downloaded v2.8.13 and was able to see bam files.

**Comment by helgathorv** [comment]
This is not enough information for us to have an idea of what might be going on. How exactly were you trying to load the files? What do you mean you weren't able to see them? Sometimes a screenshot is helpful. Also, there might be useful information in the igv.log file that's located in the folder <your_home>/igv. Please send us the log entries from a run of IGV that is failing.

**Comment by helgathorv** [comment]
Wow - that's a lot of error messages. It looks like the problems start when you load the reference genome. Can you try the following. Make sure IGV is not running - then remove or rename the /Users/ljohnson/igv folder. Then restart IGV and load just one bed file and one bam file, and send us the log file again if you still have problems.

**Comment by laurajohnson** [comment]
@helgathorv Sure. I renamed the igv folder, reopened IGV 2.8.13 and reopened the bams. No problems.  Then I closed IGV, downloaded IGV v2.9.4, and tried to open the same bam file. Like before with 2.9.4 the bam files are not visible when viewing in IGV v2.9.4. Log attached. 
[igv.log](https://github.com/igvteam/igv/files/6300264/igv.log)

**Comment by helgathorv** [comment]
Are dragging&dropping both the bed file and the bam file at the same time? If so, can you try selecting just the bam file by itself.

**Comment by helgathorv** [comment]
The log indicates that it doesn't seem to find the index file.  I see that the bam file/index are under "Documents" which is one of the special restricted folders in Catalina. That should work OK with IGV, but another thing to try is to move them to a folder that isn't Desktop, Documents, Downloads, or a Network driver, and see if it works then.

**Comment by helgathorv** [comment]
But if it doesn't have anything to do with where the files are located, but rather something about how 2.9.4 handles the file itself, then it would be really useful to be able to get a small use case that replicates the problem so we can debug it.

**Comment by laurajohnson** [comment]
You are right! I can drag and drop the bam files and then see the tracks within 2.9.4 if the files are not stored in my Documents folder. Do you know how to work around this problem since I store most all of my work within the Documents folder and use Catalina?

**Comment by helgathorv** [comment]
@laurajohnson The system is supposed to ask permission the first time IGV tries to access the files. Perhaps the drag & drop is confusing it. Try loading files from Documents via File > Load from File. First a file that doesn't have an index, and then a bam file. Does loading them via the menu work? If so that may then be enough to also give the necessary permissions to the drag&drop.

**Comment by laurajohnson** [comment]
@helgathorv You are right that when I load from file first, then drag and drop an additional bam file, I can see the tracks in IGV 2.9.4.  However, I must "load from file" each time I re-open IGV before the drag and drop method works.  Not a big deal, but annoying given the 10+ year habit of dragging and dropping to view files in IGV.

**Comment by jrobinso** [comment]
Yes its annoying, it's out of our hands these rules are imposed by Apple.

**Comment by helgathorv** [comment]
@laurajohnson Also note that if you drag&drop your bam files before you remember to load from file, no need to start over - just load a file  from Documents via the menu (any file) and then IGV will be able to access the index files for the loaded bam files from then on. It won't automatically update the view, but if you do something to trigger IGV to access the file again (e.g. if you browse to a different locus) it will load the data.

**Comment by laurajohnson** [comment]
Thanks for your responses.  I'll probably stick with v2.8.13 for as long as I can to avoid the extra steps.
