### ISSUE TITLE
IGV_Win_2.5 and proxy server

### ISSUE THREAD

**Issue by apolanski** [igvteam/igv#650]
Dear IGV developers,
I need the list of Iinternet addresses for IGV_Win_2.5., I have some problems with proxy server.

**Comment by jrobinso** [comment]
I need you to narrow this request,  what problems are you having specifically?

**Comment by apolanski** [comment]
Now I've added the following addresses to the exception:
https://s3.amazonaws.com/1000genomes/
https://data.broadinstitute.org
https://s3.amazonaws.com/igv.broadinstitute.org/genomes/
https://diagenom.varvis.com/igv/
https://s3.amazonaws.com/igv.org.app/desktop_google
And now i can to see the following information:
![grafik](https://user-images.githubusercontent.com/50451940/57507480-3bfa5800-72ff-11e9-9761-fbe83d0e9042.png)
But after cancel button IGV starts normally. I do not know if the list is complete now. I searched the addresses in different sources:(

Of course it's everything works smoothly with the deactivated proxy.

**Comment by roland-ewald** [comment]
Maybe some list of URLs accessed by IGV per default would be useful, e.g. in the [manual section on loading genomes](http://software.broadinstitute.org/software/igv/LoadGenome), or in some of the more technical sections (e.g. [on the available genomes](http://software.broadinstitute.org/software/igv/Genomes))?

From the above list, these URLs seem to be accessed by IGV default installations (https://diagenom.varvis.com/igv/ is a custom URL for this particular setup):
- https://s3.amazonaws.com/1000genomes/
- https://data.broadinstitute.org
- https://s3.amazonaws.com/igv.broadinstitute.org/genomes/
- https://s3.amazonaws.com/igv.org.app/desktop_google

**Comment by jrobinso** [comment]
I don't know what https://diagenom.varvis.com/igv/ is or how they have IGV configured.  What's loaded will be largely driven by the data server registry configured for the IGV installation, as well as user preferences and what they have loaded previously.

**Comment by roland-ewald** [comment]
@jrobinso Is there some documentation where the _default_ data server registry for a new IGV installation is documented? I believe this would resolve the issue. 

https://diagenom.varvis.com/ is a URL with `session.xml` files (ie. custom configuration) and can be ignored here.

**Comment by jrobinso** [comment]
Yes, its in the advanced preferences.  See (2) here:
http://software.broadinstitute.org/software/igv/Preferences#Advanced.
Also http://software.broadinstitute.org/software/igv/server_configuration
