### ISSUE TITLE
IGV 2.5 java.lang.NullPointerException at startup on MacOS 

### ISSUE THREAD

**Issue by spapillon** [igvteam/igv#651]
Just installed Java 11.0.3 and IGV 2.5.2. 

When attempting to start IGV, I get the following java.lang.NullPointerException error

> Bundled JDK not found.  Using system JDK.
> WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
> WARNING: package sun.awt.windows not in java.desktop
> WARN [2019-05-14T17:33:19,010]  [Globals.java:138] [AWT-EventQueue-0]  Development mode is enabled
> INFO [2019-05-14T17:33:19,036]  [DirectoryManager.java:179] [AWT-EventQueue-0]  IGV Directory: /Users/papillos/igv
> INFO [2019-05-14T17:33:19,059]  [Main.java:155] [AWT-EventQueue-0]  Startup  IGV Version 2.5.2 04/23/2019 12:15 AM
> INFO [2019-05-14T17:33:19,060]  [Main.java:156] [AWT-EventQueue-0]  Java 11.0.3
> INFO [2019-05-14T17:33:19,060]  [DirectoryManager.java:84] [AWT-EventQueue-0]  Fetching user directory... 
> INFO [2019-05-14T17:33:20,135]  [Main.java:157] [AWT-EventQueue-0]  Default User Directory: /Users/papillos
> INFO [2019-05-14T17:33:20,136]  [Main.java:158] [AWT-EventQueue-0]  OS: Mac OS X
> ERROR [2019-05-14T17:33:20,171]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
> java.lang.NullPointerException: null
> 	at java.awt.Window.init(Window.java:509) ~[?:?]
> 	at java.awt.Window.<init>(Window.java:549) ~[?:?]
> 	at java.awt.Frame.<init>(Frame.java:423) ~[?:?]
> 	at java.awt.Frame.<init>(Frame.java:388) ~[?:?]
> 	at javax.swing.JFrame.<init>(JFrame.java:180) ~[?:?]
> 	at org.broad.igv.ui.Main$1.run(Main.java:106) ~[igv.jar:?]
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) ~[?:?]
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
> 	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
> 	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
> INFO [2019-05-14T17:33:21,604]  [ShutdownThread.java:46] [Thread-1]  Shutting down
> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> 
> [Process completed]

**Comment by davideby** [comment]
I'll leave it to @jrobinso to comment on possible causes for the exception trace, but is there a particular reason you're not using our Mac.app with the bundled JVM?

**Comment by davideby** [comment]
I'm not able to reproduce this locally on Mojave using the latest Adopt OpenJDK 11 release (11.0.3+7), which is the JVM distribution we're bundling in our other builds.

@spapillon Where did you get Java 11.0.3?  It's possible there are differences due to the distribution.  What version of macOS are you running?

**Comment by spapillon** [comment]
Issue was fixed by download  Adopt OpenJDK 11 release (11.0.3+7) instead of Oracle JDK
