### ISSUE TITLE
Can I run batch directly from igv.sh without opening igv's graphical interface？

### ISSUE THREAD

**Issue by zhengjiantao** [igvteam/igv#654]
![image](https://user-images.githubusercontent.com/41890364/58622670-b9adf400-82fe-11e9-9dcf-fdefbb51f963.png)

For some reasons, I cannot open the graphical interface of the server, but I know how to write the batch file, so now one question is how can igv.sh execute the batch file?(ps: I don't have a graphical interface, I just want to get the generated images)

**Comment by jrobinso** [comment]
No,  IGV requires the display.
