### ISSUE TITLE
User Interface Freeze After BAM File Loaded

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv#656]
I tried version 2.5.3 and loading a BAM file takes a couple of minutes. The user menus become unresponsive and the mouse icon always remains a spinning wheel, never returning to being an arrow. I also have version 2.3.98 available and the reads load almost instantly and the user interface doesn't become unresponsive. I am running IGV by using the shell script on a CentOS system. I don't notice any concerning messages shown in the Linux terminal.

**Comment by jrobinso** [comment]
Could you give me a test script and file to reproduce this?

**Comment by DarioS** [comment]
I can experience this simply by setting the genome to hg19 and arbitrarily choosing one of the 1000 Genomes BAM files which are easily accessible. I don't think that a test script will illustrate the problem. I tried doing the same on a personal laptop computer running Windows 10 operating system and there was no problem. What's peculiar is that there is no problem with the 2.3 series of IGV, just more recent versions. Any suggestions how to narrow down the cause?

**Comment by jrobinso** [comment]
Well, the jump form 2.3 to 2.5 is several years and many hundreds of commits.  If it could be narrowed down to a release that would be helpful, but probably not practical.  However trying the latest 2.4 version might be informative as its the last of the Java 8 builds.  You will need to install Java 8 yourself to use that one. 

I assume you've checked the igv.log file for messages.

I asked for a script because I assumed you were using command line options, but re-reading I see you probably just meant you were using our supplied .sh script.

Are you loading by URL or from a local copy of the bam?

**Comment by DarioS** [comment]
The BAM files are on a Lustre file system on a HPC and I an viewing them on an interactive node. I checked versions 2.3.98 and 2.4.0 and version 2.4.0 has the problem. Using version 2.4.0, I see

```
ERROR [2019-06-17 14:20:41,814]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.IllegalArgumentException: Cannot format given Object as a Number
        at java.text.DecimalFormat.format(DecimalFormat.java:507)
        at java.text.Format.format(Format.java:157)
        at org.broad.igv.sam.SAMAlignment.getValueStringImpl(SAMAlignment.java:636)
        at org.broad.igv.sam.SAMAlignment.getValueString(SAMAlignment.java:465)
        at org.broad.igv.sam.AlignmentTrack.getValueStringAt(AlignmentTrack.java:999)
        at org.broad.igv.ui.panel.DataPanel.updateTooltipText(DataPanel.java:512)
        at org.broad.igv.ui.panel.DataPanel$DataPanelMouseAdapter.mouseMoved(DataPanel.java:635)
```

I don't see the exception using version 2.5.3 but the lag is even worse, so it's probably unrelated to the probkem.

**Comment by jrobinso** [comment]
I don't know what to do with this @DarioS ,  I can't reproduce it and there are no other reports.   I'll see what changed between 2.3.98 and 2.4.0.    I'm sure you have access to a PC or Mac,  can you reproduce the problem on any other platform?

**Comment by jrobinso** [comment]
These versions are almost 2 years old.   If you can git-bisect and narrow it to a commit we might be able to find it.   Here's the git log of changes

<img width="1138" alt="Screen Shot 2019-06-16 at 10 41 14 PM" src="https://user-images.githubusercontent.com/933148/59580948-0c6e0680-9088-11e9-91e1-402ab9c21ac5.png">

**Comment by DarioS** [comment]
I can't reproduce the problem on a Windows computer. My git skills aren't good, so I would need to spend time learning it and couldn't get to it soon. I wonder if the [recent freezing report](https://groups.google.com/d/msg/igv-help/QN5pweac4Tw/xGdnXjU8AgAJ) could help, although ironically that is a about computer running Windows 10.

**Comment by jrobinso** [comment]
I will pull and do some builds for you to try if you're willing,  maybe we
can narrow it down to a commit.

**Comment by DarioS** [comment]
O.K. I'll give it a try. Take your time with this because I can simply rely on 2.3.98 for my current needs.

**Comment by jrobinso** [comment]
@DarioS OK I have 2 packages to test.   We'll take next steps depending on the results.    These 2 are somewhere between 2.3.98 and the 2.4.0 release.    Could you try them and see if the problem is present in either or both?   

Thanks

https://data.broadinstitute.org/igv/projects/downloads/2.4/IGV_test1.zip
https://data.broadinstitute.org/igv/projects/downloads/2.4/IGV_test2.zip

BTW one big change in 2.3.98 and 2.4 is the latter targets Java 8.

**Comment by DarioS** [comment]
Both of the test versions are extremely sluggish compared to version 2.3.98.

**Comment by jrobinso** [comment]
OK,  here's 2 more.  We're bisecting through the git history.

https://data.broadinstitute.org/igv/projects/downloads/2.4/IGV_test3.zip
https://data.broadinstitute.org/igv/projects/downloads/2.4/IGV_test4.zip

My Linux box is an old Dell running ubuntu 18.04.1,  all versions are
pretty zippy on it.   I can't detect any difference.   Is you linux box
local, by that I mean is the display on the same machine or are you
connecting to a remote node using an X11 windows server?

**Comment by DarioS** [comment]
The test3 variety has good responsiveness whereas test4 is sluggish. It seems that we've found the commit where the responsiveness changed. I am connecting to a server using X11 windowing.

**Comment by jrobinso** [comment]
We've narrowed it down but haven't found it,  getting closer.    There are
40 commits between test3 and test4.   Here's 3 more, ~ 10 commits appart.
 Do these in order, when you find a responsive one you don't have to
continue.

https://data.broadinstitute.org/igv/projects/downloads/2.4/IGV_test5.zip
https://data.broadinstitute.org/igv/projects/downloads/2.4/IGV_test6.zip
https://data.broadinstitute.org/igv/projects/downloads/2.4/IGV_test7.zip

 I'm surprised that any version is responsive,  my stock answer for remoted
X11 is we don't support it.    If I can find some magic that will make it
usable I will adopt it, my assumption is this is not usable and cannot be
made so.   Apparently I was wrong.

**Comment by DarioS** [comment]
All three versions are unresponsive. It will be good to get it running smoothly via X11 if easy to configure.

**Comment by jrobinso** [comment]
Wow.   OK try test8 and test9.   I was wrong about 40 commits, there are
hundreds of commits between 2.3.98 and 2.4,  because the 2.3 series lived
on a branch for quite a long time.

**Comment by DarioS** [comment]
Both are freezing.

**Comment by jrobinso** [comment]
This is not productive, clearly.     I'll see if I can setup a node,  its
been a long time since I did anything like this and I'm not sure the Linux
boxes I have access to even have X11 clients,  but I'll try.
