### ISSUE TITLE
BED thickStart and thickEnd ignored if either is outside (start,end)

### ISSUE THREAD

**Issue by tfenne** [igvteam/igv#657]
If I try to load a BED file that has `thickStart` or `thickEnd` outside of the range of `start`-`end` then the entire feature is silently rendered thick.  It would be nice if instead either a) a warning message could be logged that the BED contains invalid entries or b) the thick start/end could be capped to the closer of start/end.

**Comment by jrobinso** [comment]
There's not really a bed format specification so we can't say if this is out-of-spec or not, but would something like the following make sense?

```
thickStart = Math.max(start, thickStart)
thickEnd =   Math.min(end, thickEnd)
```

In your case is thickStart ever > end,  or thickEnd ever < start?   For that matter is thickEnd ever less than thickStart?

**Comment by tfenne** [comment]
That would work.  In fairness it's a bug on my end to be generated invalid BED files, but it took me quite some time to figure out why IGV was sometimes displaying the thickness as I expected and sometimes not.  In my case I was setting the thickStart to be < start or thickEnd > end, but never outside the opposite bound.
