### ISSUE TITLE
Feature request: preference for whether to confirm when tracks are removed

### ISSUE THREAD

**Issue by tfenne** [igvteam/igv#658]
It would be really nice to have a preference to enable/disable confirmation when removing tracks.  I don't think I've ever attempted to remove a track and then hit "No" on the confirmation dialog.  It would be really nice to skip the confirmation dialog all together.

**Comment by jrobinso** [comment]
Yea I agree this is really annoying.  Maybe we shouldn't have the confirmation at all?   Ditto when loading a new session.

**Comment by tfenne** [comment]
That'd be my preference too, but I figure it was probably there because some users liked it?

**Comment by jrobinso** [comment]
I doubt seriously anyone likes it.   It will be gone soon.
