### ISSUE TITLE
Feature request: reload track / reload all tracks

### ISSUE THREAD

**Issue by tfenne** [igvteam/igv#659]
I frequently use IGV to review collections of BED files that I'm generating from software that I'm writing.  My cycle is a) write files, b) look in IGV, c) identify issues, d) fix bugs, e) repeat.  Often I have 3-4 different files open.  The only way I can find to have IGV update the view with the updated files is to remove the tracks and then manually reload them.  It would be great to have an option to select one or more tracks and then have a context menu option to reload/refresh those tracks from the underlying datasource.

**Comment by jrobinso** [comment]
It would probably be easier to provide an option to reload everything, at the current locus etc.  Basically this would be equivalent to saving the session and reloading it, but without actually creating a session file.

**Comment by tfenne** [comment]
That sounds great. At least in my usage I'm generally regenerating and viewing fairly lightweight files like BED files, so reloading everything would still be very quick.

**Comment by jrobinso** [comment]
BTW this and the other issues you posted are in the latest release, 2.6.0.

**Comment by tfenne** [comment]
Fantastic, thanks @jrobinso !

**Comment by yfarjoun** [comment]
Hi @jrobinso I was unable to find a way to refresh all the tracks. I use the "refresh screen" button in the menu, which seems to reload read-tracks (and possibly others) but not variant tracks. Am I misusing IGV, or is this a bug?

**Comment by yfarjoun** [comment]
v2.8.0

**Comment by helgathorv** [comment]
Try File > Reload Session

**Comment by yfarjoun** [comment]
I’ll try it but it’s a confusion menu item if no session is loaded.

Thanks.

**Comment by jrobinso** [comment]
Ahh yes, I see how that could be confusing.  We'll rename it, suggestions?
Reload Tracks?

Also, I'll make the "refresh" button do this.  It had a different purpose
long ago.

**Comment by yfarjoun** [comment]
I think that "Reload Tracks" is good, especially if it isn't next to the "sessions" menu items, or separated from them with a bar.

the refresh change is also good, I think. 

Thanks!!

**Comment by helgathorv** [comment]
Action items:
- make the "refresh" button reload the tracks
- add a "Reload Tracks" to the File menu (between "Load from Server" and the first divider line)

Consider:
- repurpose "Reload Session" to reload the last session file that was loaded (if any). Rename the menu item to "Reload Session File".
