### ISSUE TITLE
no pop-up menus on MacOS

### ISSUE THREAD

**Issue by huidongchen** [igvteam/igv#663]
Hi,

When I do right-click within IGV app (I tried both 2.5.3 and 2.4.19), there are no menus popping up. (E.g. i right-clicked the RefSeq Genes, nothing happened)

I'm currently using MacOS 10.14.5. Java Version8 Update211. I asked my friend to download the latest version and try it on his Macbook. The same happened to him too. No pop-up menus showed up when right-click.

I would be very grateful if you could help me out.

Many thanks!

**Comment by helgathorv** [comment]
Are you running the Mac App or from the command line? I tried the 2.5.3 IGV Mac App on MacOS 10.14.2 and it works for me.

**Comment by huidongchen** [comment]
Hi thanks for your prompt reply! I'm running the Mac App. Is there anything i can potentially try to solve it? Do you think it might be related to the Java version?

**Comment by helgathorv** [comment]
I found a 10.14.5 machine and it works fine for me there too. If you are using the Mac App (not the command line IGV) then Java 11 is bundled with it and your system Java is not used. Perhaps there are clues in the IGV log file ~/igv/igv.log - can you share it with us?

**Comment by huidongchen** [comment]
Absolutely! Thanks for helping test it. I'm attaching the log file here.
[igv.log](https://github.com/igvteam/igv/files/3308282/igv.log)

**Comment by jrobinso** [comment]
Could you try ctrl-click,  alt-click, and command-click.   The context menu options are configurable on a Mac.   Technically the Mac mouse does not have a right button,  but  right-click on 3 button mice are usually, but not always, mapped to the context menu.

**Comment by huidongchen** [comment]
> Could you try ctrl-click, alt-click, and command-click. The context menu options are configurable on a Mac. Technically the Mac mouse does not have a right button, but right-click on 2 and 3 button mice are usually, but not always, mapped to the context menu.

I tried all three and `ctrl-click` works! Thanks so much for helping figure it out! Finally I got to see the pop-up menus! :)

**Comment by jrobinso** [comment]
OK, great.  You might look at your mouse settings in the "Settings" app and see if there is anything configurable, but ctrl-click should always work.
