### ISSUE TITLE
[Feature request]: Allowing CIGAR display expansion in long read

### ISSUE THREAD

**Issue by SHuang-Broad** [igvteam/igv#667]
Hello Team,

I am currently looking into SV calling using PacBio CCS reads, and one thing I noticed from the alignments generated by mimimap2 is that sometimes there are closely-neighboring insertion and deletion operations, e.g. `[0-9]+I(1|2)M[0-9]+D`, as illustrated in the figure below. 

Unfortunately, sometimes (see the top alignment record annotated in the attached screenshot) I see the CIGAR collapsed with `...`.  And this prevents me from looking at the whole CIGAR and judge if the above-mentioned phenomenon is true at the current locus.

So I am wondering if it is possible to display the full CIGAR (via some options) for long reads, given that the long base quality annotations are displayed anyway.

Thanks!

![Screen Shot 2019-07-02 at 1 20 05 PM (2)](https://user-images.githubusercontent.com/16310888/60533409-8f6c9f00-9ccd-11e9-93af-c7b4eeb0e078.png)

**Comment by jrobinso** [comment]
Hi @SHuang-Broad , apologies for the delay getting to this.   Perhaps we should just display the entire cigar at all times, without options,  that is the simplest solution.

**Comment by jrobinso** [comment]
I've updated the max cigar length to 1000,  this is released in version 2.6.   If that is not enough please re-open this issue.

**Comment by SHuang-Broad** [comment]
Thanks Jim! It is working!

A [greedy] further request, do you think it would be hard to offer the option to copy the sam record of a selected read?

**Comment by jrobinso** [comment]
@SHuang-Broad there should already be a "copy read details to clipboard" or something like that.  If that is not sufficient or you need a literal SAM record open a new issue.
