### ISSUE TITLE
Viewing vcf4.3 files

### ISSUE THREAD

**Issue by bkohrn** [igvteam/igv#668]
Would it be possible to add support for viewing vcf4.3 files (as specified at https://github.com/samtools/hts-specs/blob/master/VCFv4.3.pdf) to IGV, and if not, why not?  I need to make use of the ability of vcf4.3 to encode ambiguous bases (a functionality that is not present in vcf4.2), particularly the ability to have N be a valid alt allele.  I know I can get the VCF to read by changing the header to vcf4.2, but I'd prefer not to do that if I don't absolutely have to.

**Comment by jrobinso** [comment]
This is a question for the htsjdk,  which we use to read vcf.   You might try the snapshot version of IGV, which includes the latest htsjdk for unrelated reasons.   If that doesn't work open an inquiry on the htsjdk project https://github.com/samtools/htsjdk/issues

**Comment by jrobinso** [comment]
This should work with the latest IGV release.
