### ISSUE TITLE
advice on viewing RNA/ChIP-seq files

### ISSUE THREAD

**Issue by olechnwin** [igvteam/igv#669]
Hi,

This is more of a question than an issue. Apologize if this is not the correct place.

I have alignment files of RNA-seq that I would like to view in IGV and am wondering what would be the best way to view them. 

I have 2 different samples and each of them have 2 replicates so I have a total of 4 bam files that I would like to load into IGV. I'm mainly interested in visualizing expression/intensity.
I know if I upload the bam files it will calculate coverage automatically but it will display the two replicates as different tracks.
Should I merged the bam files of replicates then convert to bedgraph or tdf? FYI, I aligned the RNA-seq to custom genome.
The same question for ChIP-seq data.

Thank you in advance for your help.

**Comment by jrobinso** [comment]
That is entirely up to you.   You might post the question on a genomics analysis forum and see what advice you get.

**Comment by olechnwin** [comment]
Sorry I wasn't being clear. Since I have multiple bam files that I wanted to view in IGV, I wonder what would be the best way to do this in IGV (i.e. faster load with less memory used). Is converting to tdf better than bedgraph for IGV?

**Comment by jrobinso** [comment]
The best format is bigwig,  which you can create using UCSC command line tools from a bedgraph file.  However "tdf" will also work.

**Comment by olechnwin** [comment]
Great! Thank you so much for your advice. I'll convert to bigwig then.
