### ISSUE TITLE
TravisCI should actually run the tests, not just compileJava

### ISSUE THREAD

**Issue by brainstorm** [igvteam/igv#670]
As it is now at the time of writing this, `.travis.yml` is actually not [running any tests](https://en.wikipedia.org/wiki/Continuous_integration#Make_the_build_self-testing), it is just compiling the sources.

I would strongly advise to change `./gradlew compileJava` for `./gradlew build` (which also runs the tests), or just separate steps via `./gradlew test` under:

https://github.com/igvteam/igv/blob/4a93ad299d7d83b0fd0325fc595fc2db9da52cef/.travis.yml#L15

That way one could [easily spot regressions among other defects](https://travis-ci.org/umccr/igv/builds/557613584).

**Comment by davideby** [comment]
Are you talking about [master](https://github.com/igvteam/igv/blob/master/.travis.yml) or some branch?  Tests are run by line 13 of that file:
- ./gradlew -b build_java11.gradle check

The Travis config builds for both Java 11 (with tests; Line 13) and Java 8 (without; Line 15).  We have some folks still developing on Java 8 (@jrobinso among them) so we want coverage of both, but running the test suite twice leads to excessively long Travis build times so we opted for this configuration.

**Comment by brainstorm** [comment]
Ah, I see the reason now, sorry to bother!

**Comment by brainstorm** [comment]
Side note: TravisCI supports "matrix" testing, so you could run both JDKs side by side, without running on timeouts... hopefully we'll not need this anyway if IGV moves to Java11-only :)
