### ISSUE TITLE
batch export snps and gaps using igv

### ISSUE THREAD

**Issue by dqw77** [igvteam/igv#671]
Hello,

I am working with bacterial genomes and I am working on the assembled contigs right now. I mapped the ordered contigs to the reference and I would like to get the information on snps and gaps from the alignment. I found all available tools using BAM files for the variant call. I have alignment file in xmfa. Can igv call variants (including gaps) with my alignment? If yes, since I am working with hundreds of genomes, does igv/igvtools have a batch command line for this purpose?

Thank! I'd appreciated all suggestions!
QD

**Comment by jrobinso** [comment]
IGV does not call variants, it is a visualization tool only.

**Comment by dqw77** [comment]
Oh, I see.
Thank you!
