### ISSUE TITLE
Coordinates does not update when dragging the red box for zoomed region

### ISSUE THREAD

**Issue by gexijin** [igvteam/igv#674]
After zooming in, you can click on the genome bar to center to that location. This works. 
But when you drag the red box to a different location, the displayed coordinates "chr2:114,382,382-127,811,147", does not update. This caused me to retrieve and examine the wrong genomic region.

**Comment by helgathorv** [comment]
Released in IGV 2.8.0

**Comment by helgathorv** [comment]
Released in IGV 2.8.0
