### ISSUE TITLE
Custom genome FASTA file deleted on removal from "Remove Genomes" dialog

### ISSUE THREAD

**Issue by ealdraed** [igvteam/igv#675]
Hello, I'm using IGV 2.6.2 on Windows 10. Today, I encountered a bug which was already issued (#626) and should be fixed since 2.4.19:

If I remove a custom FASTA file from the "Remove Genomes" dialog via the "Remove" button and then quit the dialog by pressing "Save", the genome is not only removed from the Genome dropdown, but also deleted from disk.

I looked at the code of `RemoveGenomesDialog.java` and think that the part before the latest changes (https://github.com/igvteam/igv/blame/master/src/main/java/org/broad/igv/feature/genome/RemoveGenomesDialog.java#L150-L154) already deletes the local files. What do you think?!

**Comment by jrobinso** [comment]
Thanks for the report, yes that is a bug and a nasty one.  Apologies.   We'll fix this with high priority.

**Comment by helgathorv** [comment]
This has been fixed in IGV 2.6.3
