### ISSUE TITLE
Provide Mappability Track in Load From Server Menu

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv#677]
For popular genomes, such as hg38, mm10, and hg19, could we have easy to access unique mappability tracks for read lengths of 75 bases, 100 bases and 150 bases? It would help in interpreting regions with zero read coverage.

**Comment by jrobinso** [comment]
Do you have such tracks, or pointers to them?

**Comment by DarioS** [comment]
It appears that they're provided by the Umap and Bismap project as [BED files](https://bismap.hoffmanlab.org). Umap is for an ordinary genome whereas Bismap is for bisulfite-converted genome. Both could be useful for other users of IGV, although I am only interested in the standard genome.

**Comment by jrobinso** [comment]
I dont know when I will get to this.  In the meantime you can just downlaod
them.

**Comment by jrobinso** [comment]
Organizing, indexing, etc the files from that site would be time consuming, something I'm very short on.   UCSC has ready-to-use files for download for 24, 36, 50, and 100 mer, at least for hg38.   I don't think there would be much interest in 24,36,and 50,  but I could do the 100:  http://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/
