### ISSUE TITLE
Running IGV on a filesystem that does not support locking.

### ISSUE THREAD

**Issue by stetner** [igvteam/igv#678]
We are running IGV on a system where the users home directories are on a file system that does not support file locking.

Any way to turn it off to avoid the many messages like below?

Thanks,
Doug

Aug 19, 2019 10:00:02 AM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Aug 19, 2019 10:00:32 AM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 38.

**Comment by stetner** [comment]
Sorry, 

Centos 6.9
IGV 2.6.2

**Comment by jrobinso** [comment]
Im not aware of any way to turn that off, its in JVM code not appication
code.

**Comment by stetner** [comment]
Knowing that I found that it is not the filesystem not supporting locking but where java puts the prefs.

I found this:

> What I prefer to do, it’s change the path to my home directory. Let’s do this:

> mkdir -p ~/.java/.systemPrefs
> mkdir ~/.java/.userPrefs
> chmod -R 755 ~/.java


Then change the exec statement in igv.sh  to

exec java -showversion --module-path="${prefix}/lib" -Xmx4g \
    @"${prefix}/igv.args" \
    -Dapple.laf.useScreenMenuBar=true \
    -Djava.net.preferIPv4Stack=true \
    -Djava.util.prefs.systemRoot=~/.java -Djava.util.prefs.userRoot=~/.java/.userPrefs \
    --module=org.igv/org.broad.igv.ui.Main "$@"

That works (for me).

**Comment by stetner** [comment]
No, still does need file locking.  just need to make the user prefs go to a fs that supports locking.
