### ISSUE TITLE
Support more tags for linking reads

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#680]
As of IGV 2.4, you can view aligned reads linked by the 10X barcode sequence (BX) or molecular identifier (MI) (right-click popup menu in alignment tracks). However, this should be available for other tags as well. For example, an igv-help question asked about cell barcode (e.g. CB:Z:CTCCGGCAGCGG-1) and UMI (e.g. UB:Z:TGGCCGGT).

**Comment by jrobinso** [comment]
Easy enough to do but hard to test.

**Comment by helgathorv** [comment]
In the original [igv-help forum thread](https://groups.google.com/forum/#!topic/igv-help/X-JxXxrUcgk) I've asked for a small sample file.

**Comment by jamaschw** [comment]
Dear igv Team, 

are there any news on this issue? Are there plans to integrate more tags for the "group aligned reads by BARCODE" function? We are working with stLFR reads from BGI and would be highly interested in visualising reads grouped by the barcode. Although the barcode identifier from BGI stLFR data also starts with BX:Z, we have the feeling that the result in sorting reads when choosing the 10X / BX option in IGV could be optimised. Please reach out to me for sample files or further input. We think it would highly desirable to have better / more opportunities to visualise linked read information also from other platforms. Maybe there would also be a possibility to link the barcode identifier information with information from phased VCFs? It would be very nice to overlay this information from the different files to make the most out of haplotype / phasing data. Thanks in advance and regards!

**Comment by jrobinso** [comment]
Hi, you can link with any tag, try the "Link by Tag..." menu item.

**Comment by jrobinso** [comment]
Oh and yes, if you can provide a sample file that would be most helpful.

**Comment by jrobinso** [comment]
Closing this because linking by arbitrary tag is already supported, so its not clear what is being requested.
