### ISSUE TITLE
Feature Request: Rename tracks based on sample attribute column.

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#681]
From igv-help (https://groups.google.com/forum/#!topic/igv-help/OK18DerZXdI) 

I am using IGV 2.6.2 to visualize a large number of TDF files (RNA-seq data).
The track names appear as the file names, but this is really not convenient as those file names are uninformative to me (and others who will need to visualize the data)
I see that right-clicking on a track allows me to rename it, but with so many files I would like to have an automated way of doing so.

I have already loaded a customized sample attributes file, and this shows properly. See screen capture 
![Capture](https://user-images.githubusercontent.com/1265859/63732386-0fccfd80-c842-11e9-8f39-bd7228427ea7.PNG)

Is there a way to rename my tracks based on one of these columns (you can see that one of the columns there is "Sample_name").
It would be nice to have the option to right-click on one of the attributes and select "rename tracks based on this attribute".

This not being possible, I thought that loading also a sample mapping file would do the trick, but when I load my file (using file-->load from file) I get the following error message:
Error loading D:\mypath\sample_mappings.txt: An error occurred while accessing: D:\mypath\sample_mappings.txt
Could not determine file type. Does file have proper extension? 

Here is a snippet of that file, which I built according to the example given at: https://dm.genomespace.org/datamanager/file/Home/Public/SpaceCadet/IGV%20Sample%20Information%20Files/BLCA_SampleMapping_3sets.txt

#sampleMapping    
PrettyName_01    LRBS84.mm9dm6ERCC.nodups.bin10RPKM.for+revminus.tdf
PrettyName_02    LRBS85.mm9dm6ERCC.nodups.bin10RPKM.for+revminus.tdf
PrettyName_03    LRBS86.mm9dm6ERCC.nodups.bin10RPKM.for+revminus.tdf
PrettyName_04    LRBS87.mm9dm6ERCC.nodups.bin10RPKM.for+revminus.tdf
PrettyName_05    LRBS88.mm9dm6ERCC.nodups.bin10RPKM.for+revminus.tdf
PrettyName_06    LRBS89.mm9dm6ERCC.nodups.bin10RPKM.for+revminus.tdf
PrettyName_07    LRBS90.mm9dm6ERCC.nodups.bin10RPKM.for+revminus.tdf
PrettyName_08    LRBS91.mm9dm6ERCC.nodups.bin10RPKM.for+revminus.tdf
...

The second column of this sample mapping file (with long file names) matches the first column of my attributes file (that column is labelled TRACK_ID).
Is there something I am not doing right?

**Comment by jrobinso** [comment]
This is implemented.  There are 2 ways to do this.
(1) for the current session only -- from the track menu
(2) persistently from the preferences window (Tracks tab).  This actually existing in previous versions but the field was dropped with the new pref window.

To test load the session following session https://www.dropbox.com/s/uwfb6pcs5wdnint/encode.xml?dl=0

**Comment by helgathorv** [comment]
Released in IGV 2.8.0
