### ISSUE TITLE
Log shipping to AWS CloudWatch

### ISSUE THREAD

**Issue by brainstorm** [igvteam/igv#683]
After working with the AWS PR https://github.com/igvteam/igv/pull/620, our team has found out that it would be valuable to have centralized logging of IGV operations within our organization (leveraging our AWS Cognito-Federated setup).

This feature has good potential for both operational and analytics perspective (pure crashes and/or curator scientific insight).

Since there's already an existing log4j logging infrastructure available in IGV, the changes should be minimal and pluggable. There are many options that people have implemented in the past:

https://github.com/sensefly-sa/log4j-cloudwatch-appender
https://dzone.com/articles/announcing-log4j-aws-appenders

I just wanted to unload this from our internal ticketing system since:

1) I recognize that other people might be interested in this type of functionality.
2) Gauge opposition, interest or criteria from @igvteam.

**Comment by jrobinso** [comment]
I would be open to minimally invasive pluggable solutions for those who have a need for this.  We would never do it centrally, of course.

**Comment by jrobinso** [comment]
Issue maintenance.
