### ISSUE TITLE
Can add a chevron to the start of the read?

### ISSUE THREAD

**Issue by nh13** [igvteam/igv#686]
right now it's `|---->` but it'd be nice if it was `>---->` instead.  The former for some reason has never been intuitive to me when I only see `|---...`, but it would be if it was `>---...`.  Let me know if I am not making sense.

**Comment by jrobinso** [comment]
@nh13 how are you?  The time for this was 10 years and probably around a million screenshots ago.  Not only from IGV, this basic look has been copied all over the place.  Seriously we would not entertain changing the default look of alignments short of some massive outcry to do so.  Perhaps as some optional mode triggered by a preference?  Who knows it might catch on.

**Comment by nh13** [comment]
One can always dream... thanks for responding.

**Comment by jrobinso** [comment]
@nh13 hey I was serious about a special mode, just not the default view.  If its important to you reopen.

**Comment by nh13** [comment]
Sorry, I didn’t realize a special option was on the table. Thanks!
