### ISSUE TITLE
IGV Manhattan plot

### ISSUE THREAD

**Issue by jiehuang001** [igvteam/igv#689]
Hi, guys:

It is amazing that IGV could also show GWAS data. But I found a few issues. It would be great if someone is interested in addressing them:

I could not move thee top “Gene” panel to the bottom so that it looks like a LocusZoom plot.

When I select “Expanded” view, the height of the “Gene” panel goes out of control, and “Change Track Height” button won’t work. I could not drag the horizontal line right below the "Gene" panel to move up or down.

There are options for “set primary color” and “set alternating color”. But there is no way for me to manually color a few regions that I would like to highlight. As we know, highlighting some regions on a Manhattan plot is very important.

Best regards,
Jie

**Comment by jrobinso** [comment]
I see you posted on the forum, so I'm closing this.
