### ISSUE TITLE
Sessions with relative paths won't load

### ISSUE THREAD

**Issue by Mashin6** [igvteam/igv#693]
Not sure if this is only my problem, but when I set IGV to save relative paths for session and then I move the whole folder structure somewhere else, the session fails to load properly. I am running IGV 2.6.3 on macOS 10.14.6. 

Inspecting the .xml file shows that the path in <Resource/> field is set correctly to relative. However, path to session in <Session> field and path to file in <Track id= > field stays absolute.

Manually changing those to relative paths fixes the loading issue.

**Comment by jrobinso** [comment]
Hi, this is fixed with commit 505d806eee58e49163b780f419350853b5f8cb7c  and will be in the next release, sometime next week.

**Comment by helgathorv** [comment]
This was released with IGV 2.7.0
