### ISSUE TITLE
Group autoscale setting is not properly loaded from session file

### ISSUE THREAD

**Issue by Mashin6** [igvteam/igv#694]
Although the information about autoscaling groups is saved in .xml file as 'autoscaleGroup=' when the session is freshly loaded the autoscale is not set and needs to be done manually again.

Running IGV 2.6.3 on macOS 10.14.6.

**Comment by jrobinso** [comment]
I can't reproduce this one.   Try this for example:
https://www.dropbox.com/s/2j7pekznjc59o9l/group_autoscale_session.xml?dl=0

If the problem persists please attach an example session, preferably using
public files by URL so I can open it.   Alternatively zip a relative
session with data files.

**Comment by Mashin6** [comment]
Sorry to be more specific. Loading sessions like yours work (except the Attribute panel not showing the groups see screenshot).
![Screen Shot 2019-09-25 at 11 05 34 ](https://user-images.githubusercontent.com/5265707/65614305-62a2ed80-df85-11e9-9d39-83db8f78c60e.png)

Group autoscale is not working when track are overlayed. Also Overlayed track don't show range in the top left corner as well as any other track placed under. (See screenshot)
https://drive.google.com/file/d/1xrrC2mZPLTk10ImIODn_AfLMqrxzwBkV/view?usp=sharing

![Screen Shot 2019-09-25 at 11 05 01 ](https://user-images.githubusercontent.com/5265707/65614435-a5fd5c00-df85-11e9-9f85-72e3b8ff417d.png)
