### ISSUE TITLE
Cannot load BAM file from Google Drive

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#697]
Running IGV 2.6.3 
Loading a BAM file from Google Drive will create a track, but no data is ever loaded.
Here are public links to small test files:

https://drive.google.com/open?id=14dGM9acAByia5JCIQBBq34RMGj-SL6HF  (bam file)
https://drive.google.com/open?id=1SnK8svPWYj7nR03bIsqm-ObmKgJkbvYR (bai file)

Data should be visible by searching for BRAF and then zooming in a couple of times.

**Comment by jrobinso** [comment]
Google drive is not supported
