### ISSUE TITLE
IGV doesn't show red bar for imported regions

### ISSUE THREAD

**Issue by finswimmer** [igvteam/igv#700]
Hello,

I'm using igv browser 2.6.3 for linux.

I discovered, that the red bar at the top is missing if I import regions via bed file in the menu `Import`->`Import Regions`. This only happens if I select a reference genome, where the chromsome names are prefixed by `chr`, e.g `chr1`, but the prefix is missing in the bed file. Same happens the other way round. 

Navigating after import to the regions via `Regions Navigator` works fine after importing.

While I understand that `chr1` and `1` aren't the same, I thought that in a former IGV version, it works "magically", does it?

fin swimmer

**Comment by helgathorv** [comment]
Hi thanks for the report. It's definitely a bug and we'll fix it. BTW, it's not a regression - this the way it's always behaved (or at least going back 6 years).

**Comment by finswimmer** [comment]
Thanks for your quick answer and confirming this.  

> BTW, it's not a regression - this is the way it's always behaved (or at least going back 6 years).

:) Ok, than I had a lot of luck.

**Comment by helgathorv** [comment]
Yes - I was surprised we hadn't run into this before as well, so I checked a sampling of old IGV versions and they all behaved the same.

**Comment by jrobinso** [comment]
Pushed a fix, will be in next release

**Comment by finswimmer** [comment]
Perfect. Thanks a lot!
