### ISSUE TITLE
RFE: Windows installer - Desktop shortcut and Start Menu location

### ISSUE THREAD

**Issue by kuoirad** [igvteam/igv#703]
It would be helpful if the Windows installer for IGV put the Desktop shortcut and Start Menu entries in the "common" places (i.e. c:\Users\Public\Desktop in Win7 forward) instead of the installing user's desktop and Start Menu.  I know this is an issue with the Desktop shortcut, I have to verify with the Start Menu entry.

I'm installing IGV for multiple users at my company where they don't have administrative rights to their computers.  I install using my administrative account, then have to do some extra work to make it visible for them because the shortcut gets put on my administrative account's Desktop only.

**Comment by kuoirad** [comment]
Verified the Start Menu as well - that also gets set up only for the installing user.

So the Desktop shortcut should preferably go in c:\Users\Public\Desktop, and the Start Menu IGV folder should go into c:\ProgramData\Microsoft\Windows\Start Menu

**Comment by kuoirad** [comment]
Sure, happy to help.

**Comment by jrobinso** [comment]
@kuoirad you can download a snapshot build here.  Thanks for testing.  http://data.broadinstitute.org/igv/projects/downloads/snapshot/IGV_Win_snapshot-installer.exe

**Comment by kuoirad** [comment]
Yes - I don't think I'll have time today to give it a try, I'll set aside some time tomorrow.

**Comment by helgathorv** [comment]
This was released with IGV 2.7.0
