### ISSUE TITLE
Index file imputation not working for S3 load picker

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#704]
There is no way for the user to specify a tabix index file with the S3 picker.  This is a serious limitation, we need to figure something out.    @brainstorm what types of files are you loading?  BAM files for sure, but bed, gff?  Any other formats?

This is not insurmountable but something needs done before we can release this.  Looking at options.

**Comment by jrobinso** [comment]
Fixed in a rather crude way

**Comment by brainstorm** [comment]
Hi Jim, as discussed, we just support BAMs and VCFs for the AWS support branch... that's all we needed so far in our lab but support for BED among others might come in future PRs.

For VCFs we assume that the .tbi's are under the same S3 key ("folder" if you will), pretty much like other bioinfo cmdline tools behave, but we understand that mileages vary.

Do you remember the discussion with @reisingerf about TileReader/DataManager/`checkReader()` classes? Re-generating a pre-signed URL when it expires *and* reloading the underlying file descriptor, etc...?

We went through this and concluded it was not an easy fix without some delicate refactor on ResourceLocator and the above DataManagers, IIRC.

Anyhow, glad to see you got fixed fast :)

**Comment by jrobinso** [comment]
The fix is a patch, will work for most cases.
