### ISSUE TITLE
IGV port commands pass bed file contents

### ISSUE THREAD

**Issue by omarwagih** [igvteam/igv#709]
Is there a way I can pass a list of bed intervals using the port command instead of having to specify a file e.g. 

```
http://localhost:60151/load?content=BED_CONTENT&extension=bed&locus=egfr&genome=hg19
```

This would be useful for front-end apps that want to display a few intervals from the browser in that it saves having to dynamically create a bed file on the back end. 

Or perhaps data urls could be supported: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs with an extension required

**Comment by jrobinso** [comment]
Not currently.  I'll treat this as a feature request.

**Comment by jrobinso** [comment]
Sorry for the long delay.  This is implemented by supporting a dataURL in the standard "load" port command.   Note that although the subject of this ticket is "port commands",  your example is a URL,  the implementation is specifically for port (and batch script) commands, and is subject to the following constraints

* Only plain text, percent encoded, are supported
* The optional "format" property must be specified

This should work for most feature type formats (bed, gff3, gtf, etc), but only bed has been tested (format=bed).  Here's an example that loads 18 bed features.

```
load data:,track+name%3DH3k4me1+color%3D0%2C0%2C150%0Achr1%094798%094823%09U0%090%09-%0Achr1%094799%094824%09U1%090%09%2B%0Achr1%096086%096109%09U0%090%09%2B%0Achr1%097344%097369%09U1%090%09%2B%0Achr1%097353%097378%09U2%090%09-%0Achr1%099628%099653%09U0%090%09%2B%0Achr1%0918432%0918455%09U2%090%09-%0Achr1%0946121%0946146%09U1%090%09-%0Achr1%0974343%0974366%09U2%090%09%2B%0Achr1%0978497%0978522%09U0%090%09-%0Achr1%0981384%0981409%09U2%090%09-%0Achr1%0991680%0991705%09U1%090%09%2B%0Achr1%09118640%09118665%09U1%090%09%2B%0Achr1%09120062%09120087%09U2%090%09%2B%0Achr1%09160339%09160364%09U1%090%09%2B%0Achr1%09225519%09225544%09U0%090%09%2B%0Achr1%09225529%09225554%09U1%090%09%2B%0Achr1%09226823%09226846%09U0%090%09%2B format=bed
```
