### ISSUE TITLE
Color code individual bases based on a tag

### ISSUE THREAD

**Issue by rrazaghi** [igvteam/igv#712]
Following up on this as I think this is now a feature that would be widely used with both PacBio and Nanopore reads. Currently we use a lazy hack with the IGV bisulfite mode to color code methylated/unmethylated bases at the read level. I was wondering if this can be implemented?

Thanks,
Roham

_Originally posted by @rrazaghi in https://github.com/igvteam/igv/issues/308#issuecomment-541472748_

**Comment by jrobinso** [comment]
If you are referring to the proposal in #308 exactly no need to open a new issue, we can reopen that one.    Let's discuss it over there.
