### ISSUE TITLE
IGV_2.7.0 won't run on Mac OS Catalina

### ISSUE THREAD

**Issue by BenWittner** [igvteam/igv#713]
Hi, I recently made the mistake of upgrading my Mac to the Catalina OS. After I did that, the version of IGV that I had was not repainting the screen properly. So I deleted it and downloaded IGV_2.7.0. When I double click on that I get the attached error message. I don't know how to convince the Mac to run it anyway. Any help would be appreciated. Thanks.
-Ben

<img width="420" alt="Screen Shot 2019-10-15 at 2 41 04 PM" src="https://user-images.githubusercontent.com/39308871/66860819-e421e600-ef5b-11e9-9c4d-e024cff3aba0.png">

**Comment by jrobinso** [comment]
Thanks for the report, unfortunately we don't have Catalina and were unaware of this.    I can't give an ETA on Catalina support right now.

As a workaround you could try running  a command line version.  We don't have one for the Mac on the Downloads page, but do on the night snapshot page.   Here's a direct link:  http://data.broadinstitute.org/igv/projects/downloads/snapshot/IGV_Mac_snapshot.zip.     After unzipping you will need to use a terminal,  cd to the "IGV_Mac_snapshot" directory and execute

```
./igv.command
```

Could you please let us know if this works or not.

**Comment by jrobinso** [comment]
Here's another suggestion, from a web search.   Try right-clicking the IGV app and selecting "Open" from the popup, rather than double-clicking.

https://www.fireebok.com/resource/how-to-fix-that-app-can-not-open-on-macos-catalina.html

**Comment by BenWittner** [comment]
That worked. It still popped up the message saying it could not run it, but there was an “open” button added. When I clicked that button it ran. Now, double-clicking runs it as does single clicking on its icon in the dock. So I guess I can’t test your command line suggestion, but I’m happy. Thanks very much. I guess I should have web searched for work-arounds to the general problem, as you did.

**Comment by brainstorm** [comment]
@jrobinso How's the notarization process going? I've had a few questions about it recently from new users installing it on Catalina :-S

**Comment by davideby** [comment]
@brainstorm Yeah, we're starting to see an uptick on that front as well.  

There are issues with the JDK included in our Mac.app.  Technically we can notarize it with warnings, but we're about to cross an Apple-imposed deadline where those warnings will now be considered errors.

We're in a bit of a holding pattern to see how the JDK developers will deal with it.  There are some things we might be able to do on our own (looking at alternate JDKs, for example), but as usual it's a matter of competing priorities.

The workaround on our Downloads page seems to be working OK for most users, though it's not ideal.

**Comment by brainstorm** [comment]
Any news on this front? New users keep bumping into this :-S

![5B3B83B1-7451-4B44-AB33-909664C8A87C_4_5005_c](https://user-images.githubusercontent.com/175587/83716143-69d0de00-a672-11ea-83d8-b7e79a3b2a1a.jpg)

**Comment by davideby** [comment]
Hi @brainstorm,

Good timing.

@jrobinso just released 2.8.3, which I've signed and notarized and posted for download.  This is our first macOS notarized release and should _in theory_ fix this issue, plus the issue of accessing reserved file locations.  This should be possible without needing to grant special access, etc.  I don't actually have Catalina, though, so none of that has been tested yet.

Let us know if you hit anything further along those lines.

Thanks,
David
