### ISSUE TITLE
Change Default User Directory

### ISSUE THREAD

**Issue by kikegoni** [igvteam/igv#714]
Hey,

I am running igv from the command line and it works perfectly. I am trying to change the Default User Directory that igv is using, since it is using my home directory by default. I have already dig into the code to see if there is any parameter that can be modified to change this, but seems not obvious. 

So, I will appreciate any insight into this issue. 

Thanks;)

**Comment by jrobinso** [comment]
This is not something you can change with a parameter or from the command line, you have to do it from the UI.  Select "View > Preferences > Advanced and look to the bottom for the option to move the IGV directory.
