### ISSUE TITLE
Line plot problems

### ISSUE THREAD

**Issue by ToMatschulla** [igvteam/igv#715]
Hi IGV Team,
I have a problem with displaying bigwig data in a line plot. There are no problems with the other plot styles.
Thank you for helping.

**Comment by helgathorv** [comment]
Which version of IGV are you using? Can you run it in the latest version of IGV and give us more details about what is not working.

**Comment by ToMatschulla** [comment]
I´m working with version 2.7.0.
If I what to switch between the different plot styles(bar, dot or line plot), I can not see any data in the line plot, but if i scroll with the cursor over the data file, a yellow window with values are appearing. It seems to me that it ism kind of error with the visualisation. It is not data file dependent ( I tried with different files).

**Comment by jrobinso** [comment]
Apologies for the difficulties.  Line plot is an odd option for wig style
files, which define values over regions (bar charts) not connected points.
 UCSC does not provide this option at all.  We added it for some special
cases,  it works with many wig files but not all.   If you can post an
example wig file (zip and attach or send URL) I will look into your case.

**Comment by jrobinso** [comment]
That's new information.   Do you happen to know the version of IGV you were
using when it was working for you?

**Comment by helgathorv** [comment]
Released in IGV 2.7.2

**Comment by ToMatschulla** [comment]
Thank you very much for fixing the problem. :)
