### ISSUE TITLE
Google signin temporarily disabled

### ISSUE THREAD

**Issue by ahopki14** [igvteam/igv#717]
I get the attached error screen when I navigate to the GCS authentication link after trying to load a file from a `gs://` URL . Is this something that has to be enabled on my google cloud project? The project is private so I can not share a reproducible example.

IGV version 2.4.14 on Ubuntu, trying to authenticate with Firefox  69.0.1

Thanks!

![Screenshot from 2019-10-23 09-05-05](https://user-images.githubusercontent.com/7087297/67395807-99642780-f574-11e9-86fd-6c1c589b2af6.png)

**Comment by helgathorv** [comment]
That's an old version of IGV. Does it work for you in the latest version at http://software.broadinstitute.org/software/igv/download ?
