### ISSUE TITLE
default BAM index path

### ISSUE THREAD

**Issue by diekhans** [igvteam/igv#720]
It would improve usability to default the BAM index file to the path or URL with .bai appended instead of having to enter it twice.

**Comment by jrobinso** [comment]
In what context?  Load by URL, local file, or something else?

**Comment by jrobinso** [comment]
BTW it does default in most contexts, that's why I'm asking.

**Comment by diekhans** [comment]
URL and it does work, the text just implies that inputting it is required.
So please take this as a report to clarify the message.

thanks for the great tool.

**Comment by jrobinso** [comment]
It works sometimes, but not always, thus the text out of caution.  If will not work, for example, for dropbox, google drive, or amazon signed s3 urls.   It might not work for other could providers as well, I can't test them all.    Also, so you know, there are 2 conventions, one adds .bai and one replace .bam with .bai.     If you have a suggestion for a clarification please suggest it, I will give it some thought.
