### ISSUE TITLE
User Settable Hover Delay

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv#724]
When moving the mouse pointer over BAM alignment tracks, large blue panels with read details are displayed. This happens even when the mouse pointer is moving. Perhaps having a user-settable value of how long the mouse pointer stays still before the blue details panel appears would prevent it from blocking the track view when moving the mouse towards the read of interest.

**Comment by jrobinso** [comment]
Our solution to that was to give the user to turn the hover off altogether, and instead click on an alignment for details.    This arose specifically for BAM tracks.   The option is under the "speech balloon" icon.
