### ISSUE TITLE
Feature request: sort by start position (when showing soft-clipped bases)

### ISSUE THREAD

**Issue by nh13** [igvteam/igv#725]
When I click the option to show soft-clipped bases, the reads are sorted by the start position _including_ the soft-clipped bases.  I would like to re-sort reads by the position of the first mapped base.  This would not offset the mapped start position based on the soft-clipped bases.  The motivation is to view, for example, forward strand mapped reads that all have read through some insertion on their 5' end in a group, where the partial insertion is soft-clipped.  Some reads may read more inserted bases than others, but they their first mapped base would be the same. I can mostly recreate this by sorting by base (attached), but I would like a dedicated sort option or preference (like don't adjust the start position by soft-clipped bases when viewing).

<img width="645" alt="Screen Shot 2019-11-14 at 5 18 38 PM" src="https://user-images.githubusercontent.com/846274/68906820-dd28f780-0702-11ea-87f3-8c1e04921c7c.png">

**Comment by jrobinso** [comment]
OK, probably "sort by start position" should just behave like that by default.  Could you extract the slice shown to a bam file and attach it for testing? Alternatively point me to some public bam with a lot of soft clips as shown, that would be helpful.  Thanks.

**Comment by jrobinso** [comment]
I changed the behavior to do as you suggest,  I think that is the correct behavior.  The soft-clips are not part of the alignment, obviously.   If anyone needs the current behavior we'll add an additional sort option.

**Comment by nh13** [comment]
Thanks @jrobinso for the quick update.

**Comment by helgathorv** [comment]
Released in IGV 2.8.0

**Comment by Rasinj** [comment]
Hate to be late to the party, but I'd like to say it'd be helpful to be able to include the soft-clipping in the sorting order. It'd even be helpful to sort by total number of soft-clipped bases (left and right). This would help greatly in visualising certain regions

**Comment by jrobinso** [comment]
@Rasinj that would be 2 additional sort options, open a new issue for it.  Commenting on a closed issue, even if related, can get overlooked
