### ISSUE TITLE
Feature request: interactive filtering by read group

### ISSUE THREAD

**Issue by kevfengler227** [igvteam/igv#726]
For some applications it is convenient to merge alignments from many read groups into a single BAM, yet you may not want to view data from all the read groups in that file.  It would be awesome if the displayed read groups group be filtered in IGV within the browser so that it can be an interactive process. Perhaps the simplest implementation would be the right-click option to "remove read group" for a particular "track" when alignments are grouped by read group??

**Comment by jrobinso** [comment]
@kevfengler227 Interesting and useful suggestion.   We probably need a way to recover removed groups (un-remove) as well, correct?

**Comment by kevfengler227** [comment]
yes, ideally it would be interactive such that you could remove/add groups as needed. thanks.

**Comment by jrobinso** [comment]
After studying this its quite complex to make this interactive.  Would the filtered alignment affect coverage (lower it)?

**Comment by kevfengler227** [comment]
How about a right click option to "Filter alignments by"....Read Group which brings up a dialog box where you could list the read groups to include. For this application the coverage doesn't really apply so I typically remove it to make more space to view a lot of read groups.

So a little more background. The application for this is pan-genome visualization, where multiple genomes (read groups) are aligned to a reference. So the coverage of each is essentially 1X. But when >30 genomes are combined into a single BAM,to get just the right view you may want to filter out a few genomes (read groups), rather than creating a custom BAM each time.

Attached is an example of 10 kb chunks from each genome aligned to a reference.
![example](https://user-images.githubusercontent.com/20604003/69442828-dd348300-0d12-11ea-969b-c8c9c10ff993.png)

**Comment by jrobinso** [comment]
I'm looking for something simple that can be implemented in the near term, otherwise this will need to be deferred as we have more pressing issues.    In IGV filtering removes alignments permanently (for that session) as they are loaded.  We don't have any interactive filters,  this involves a bit of work to support.  "Hiding", which would be a new concept, could be implemented to just hide listed read groups from display,  however coverage would not be recalculated but it sounds like in your application this doesn't matter.

**Comment by kevfengler227** [comment]
awesome. thanks. "Hiding" sounds good.

**Comment by jrobinso** [comment]
OK, I will pick this up post Thanksgiving.  I don't want to rush out something hacky to the alignment menu, which is already busy.

**Comment by jrobinso** [comment]
Apologies I never got to this but am closing it now as its stale,  and I'm no closer to having time to deal with it.
