### ISSUE TITLE
Unable to change home directory on macOS Mojave 10.14.6

### ISSUE THREAD

**Issue by darrenzlmok** [igvteam/igv#729]
I am currently running IGV 2.7.2 and macOS Mojave 14.10.6. Previously, the IGV directory was set to /Users/_MyUserName_/igv. However, when I attempted to change the directory (e.g. /Users/_MyUserName_/NEWigv), an error message popped up saying:

**Error moving IGV directory:
nbsp;/Users/_MyUserName_/.rnd (Permission denied)**

Not only does this keep happening, but some of my other folders in the _MyUserName_ directory gets copied into the Newigv folder as well.

Is there any way to fix this issue?

**Comment by jrobinso** [comment]
Looks like a bug, obviously.   We will role out a new release in the next few days, I'll be sure this is fixed.   I'll alert you here when I track this down and you can use the snapshot version until the release.

**Comment by jrobinso** [comment]
@darrenzlmok I can't reproduce this.   How did you attempt to change it?  Did you use the "Preferences" dialog?
