### ISSUE TITLE
Can IGV use platform native file dialogs?

### ISSUE THREAD

**Issue by kelepiradam** [igvteam/igv#733]
Swing filechooser is pretty flat and extended functionality is not there especially for linux. 

Can file dialogs be rewamped to use the system native as in java.awt.FileDialog ?

**Comment by kelepiradam** [comment]
Looks like whatever hack apple.awt presents is also working under linux as well with OpenJDK 11. I am working on it in my own fork and I have a few additional features that some of my colleagues requested. I will post it to my own git tonight. 

![image](https://user-images.githubusercontent.com/37572619/80869647-52d15180-8caa-11ea-8ff8-bce1cd8f627d.png)

![image](https://user-images.githubusercontent.com/37572619/80869657-5cf35000-8caa-11ea-9d17-647d989a482f.png)

![image](https://user-images.githubusercontent.com/37572619/80869664-641a5e00-8caa-11ea-9798-f4e0c5c820a5.png)

**Comment by jrobinso** [comment]
@kelepiradam  I agree the native file dialogs would be much preferred, but I don't have any time to work on it now.   A pull request on this would be welcome.    We can't forget about Windows, its > 1/2 our users.

**Comment by kelepiradam** [comment]
Sure I will and I can. Thanks for the opportunity. I am working on all platforms so I can check to see if native file dialogs work for all.

**Comment by jrobinso** [comment]
Done

**Comment by kelepiradam** [comment]
Thanks!
