### ISSUE TITLE
Split screen by supplementary alignments

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#738]
See #298

**Comment by ryan-moreno** [comment]
I am trying to access this feature and am having difficulty. Based on #1278, my understanding is that if I right-click on an aligned read that has a supplementary alignment tag, then I should get the option to split screen. However, this is not among the options I'm seeing. I have used various preferences and tried to find documentation for this feature, but have not found the solution. My use case is that I want to view the two regions surrounding the ends of a translocation and see which reads span the translocation. I can pull up the two regions in split screen manually, but using "Link supplementary alignments" doesn't seem to work across split screen. Any suggestions?

**Comment by jrobinso** [comment]
What version of IGV are you running?

**Comment by jrobinso** [comment]
And linking (as in drawing a connecting line) will not work across split screens, they are completely independent.

**Comment by ryan-moreno** [comment]
I am using 2.16.0. Happy to provide log files if that is helpful.

**Comment by jrobinso** [comment]
I'm not entirely sure what you are trying to do, but there are a number of features for split reads in the latest version  (2.18).  See https://igv.org/doc/desktop/#UserGuide/tracks/alignments/chimeric_reads/.    I do not recall exactly what was in 2.16 in this regard.
