### ISSUE TITLE
Can I get igv screenshot result like using windows igv (full width)?

### ISSUE THREAD

**Issue by yubau1112** [igvteam/igv#740]
Hi, my command is:

xvfb-run --auto-servernum --server-args='-screen 1, 7680x4320x24' /local_work/bin/IGV_Linux_2.7.2/jdk-11/bin/java -showversion --module-path="/local_work/bin/IGV_Linux_2.7.2/lib" -Xmx8g @"/local_work/bin/IGV_Linux_2.7.2/igv.args" --module=org.igv/org.broad.igv.ui.Main "$@" --batch igv_batch_script.txt

and script is: igv_batch_script.txt:

new
genome hg38
load HLA_H8-122-2_S1/HLA_H8-122-2_S1.sorted.bam
load HLA_H8-123-2_S2/HLA_H8-123-2_S2.sorted.bam
load HLA_H8-124-2_S3/HLA_H8-124-2_S3.sorted.bam
load HLA_H8-125-2_S4/HLA_H8-125-2_S4.sorted.bam
load HLA_H8-126-2_S5/HLA_H8-126-2_S5.sorted.bam
load HLA_H8-128-2_S6/HLA_H8-128-2_S6.sorted.bam
snapshotDirectory .
goto chr6:29,940,470-29,947,884
maxPanelHeight 120
snapshot igv_batch_script/HLA-A.svg
exit

![image](https://user-images.githubusercontent.com/45645173/70483521-b0aaa480-1b23-11ea-8deb-7aaf6a182dfe.png)

![image](https://user-images.githubusercontent.com/45645173/70482784-6e806380-1b21-11ea-8f05-d746f6e3b462.png)

but I used windows, I can get beter result like:

![image](https://user-images.githubusercontent.com/45645173/70483242-e13e0e80-1b22-11ea-85e2-3e43db962953.png)

![image](https://user-images.githubusercontent.com/45645173/70482839-a091c580-1b21-11ea-8253-ee5cf9703053.png)

whatever how I modify the parameters and instructions, I always can not get the full width.
How do I get the full width like using windows?

thanks!

**Comment by jrobinso** [comment]
Sorry I don't know anything about xvfb, and my x-windows knowledge is very old, what you want to do is make the simulated application window full screen.   You might do a web search or check xvfb forums, this is not really an IGV question.

You can try setting the bounds of the window in the "user.preferences" file in the "igv" folder of the user home directory.   This will not make the window full size neccessary, you explicitly set the x,y,width, and height with an entry like this:

IGV.Bounds=0,0,1150,800

**Comment by zxclovezby** [comment]
@jrobinso hello,When I update home/igv/prefs.properties  The properties file does not work. Every time I run it, the file will be updated again. How do I save the prefs.properties information and apply it to.

**Comment by jrobinso** [comment]
When you exit IGV the prefs.properties file will be updated with the window bounds at the time or exit.  That's how it works, there's nothing you can do about that.   If that's not what you want it to do you might try keeping a copy of prefs.properties somewhere else (not in the igv folder) and specify its path using the command line property -o.  See https://github.com/igvteam/igv/wiki/Command-Line

**Comment by zxclovezby** [comment]
Thank you for your timely reply.I encountered a problem with screenshot display, as shown in the figure：The displayed base is only 41bp. I want to display a wider range, but specify the mutation location. For example, how to display the range of 100bp
![图片](https://user-images.githubusercontent.com/48982298/204434511-2a192df9-47ff-4656-8eb8-adf2eaa81702.png)

**Comment by jrobinso** [comment]
I think you should read the user documentation.   https://software.broadinstitute.org/software/igv/Navigate

**Comment by zxclovezby** [comment]
ok，thanks

**Comment by jrobinso** [comment]
In particular notice the explicit range option, e.g.  chr1:100-200

**Comment by zxclovezby** [comment]
solved my problem, thank you again for your timely reply.
![图片](https://user-images.githubusercontent.com/48982298/204453864-da529620-967e-4e52-a679-4b95a12dffff.png)
