### ISSUE TITLE
missing data in SEG format

### ISSUE THREAD

**Issue by marc-sturm** [igvteam/igv#741]
Hi,

we use the SEG format to display copy-number data from CNV calling.
An example SEG file can be found here:
https://github.com/imgag/megSAP/blob/master/test/data/vc_clincnv_germline_out1.seg

The copy numbers data is colored red (loss) and blue (gain).
However there are regions where the variance of the depth is too high and no CNV calling is possible.
Is it somehow possible to color those region differently (e.g. in gray)?

Thanks,
  Marc

**Comment by jrobinso** [comment]
Not currently.   How would these regions be represented in the seg file?

**Comment by marc-sturm** [comment]
We would assign the regions a copy-number neutral value (e.g. CN=2 for autosomes). By the coloring the user would know that this is only a placeholder for "missing data".

**Comment by marc-sturm** [comment]
It's not really important how it's implemented, only that a way to indicate "missing data" exists.

The color could be given in HTML-style (`<font color='gray'>value</font>`), or via some kind of JSON prefix. Whatever is easy to implement for you...

**Comment by jrobinso** [comment]
Sorry for the long delay.   There is a new "no call" color setting for heatmaps (including seg file heatmaps).  Its applied whenever the value is  NaN.   Case is important, the value field in the seg file has to equal  "NaN".

The color id dark gray by default, but can be adjusted via View > Preferences > Tracks.   

This change is pushed to master and will be in the nightly builds, and the next general release sometime in August.

**Comment by marc-sturm** [comment]
Hi Jim,

thanks for the update.

I just tied with the snapshot build, but the values are not shown:
![grafik](https://user-images.githubusercontent.com/5638144/87905908-ddcc1780-ca61-11ea-82f6-dcb03fa6686b.png)

Snapshot version is:
![grafik](https://user-images.githubusercontent.com/5638144/87905924-e9b7d980-ca61-11ea-8ecf-2cfa25b29263.png)


And the SEG file should be ok as well:
![grafik](https://user-images.githubusercontent.com/5638144/87905879-cd1ba180-ca61-11ea-9279-a114e8bbecba.png)

What did I do wrong?

Best,
  Marc

**Comment by jrobinso** [comment]
@marc-sturm I'm not sure, can you point me to an example file?

BTW there is a problem with this file https://github.com/imgag/megSAP/blob/master/test/data/vc_clincnv_germline_out1.seg

You have the type set to GENE_EXPRESSION, and also negative values (-1e-04)  in the file,  both of these might cause issues.   The presence of negative values is taken to infer that the values are log (copy #) for type = copy number.   I'm not sure what it does for GENE_EXPRESSION as that type is scaled differently.

**Comment by marc-sturm** [comment]
You can find the example file here: https://download.imgag.de/ahsturm1/NA12878_17_cnvs_clincnv_nan.seg

I tried without type and with type COPY_NUMBER, but still they are not displayed.

-Marc

**Comment by jrobinso** [comment]
OK I see the problem, you have the graph type set to points, not the default heatmap.  The change is implemented for heatmaps.   I'll have to think about what to do with NaN for points that will be intuitive and widely understood, its not obvious.

**Comment by marc-sturm** [comment]
Maybe you can add "nanColor" and "nanValue" paramters to the #track header.
The color would be used for each graph type and the value only for points, bars etc.

**Comment by jrobinso** [comment]
The color is not the problem,  where does NaN belong on a points graph?

**Comment by jrobinso** [comment]
The focus on color, and the fact that heatmaps are the default for seg files, is what left me confused in the first place.
