### ISSUE TITLE
Extracting coordinates for supplementary alignments

### ISSUE THREAD

**Issue by aadamk** [igvteam/igv#742]
Hello,
I am interested in extracting coordinates for supplementary alignments - e.g. for split reads that span a breakpoint of a structural variant. I noticed that for these types of reads, IGV displays the coordinates of both the primary and supplementary alignments when toggling over the read. How is the coordinate information for the supplementary/soft-clipped portion extracted from the sample bam file? Is there a way to export the coordinate information (chromosome: start-end positions) for all supplementary alignments to a text file using IGV? Or perhaps from another Broad tool?

**Comment by jrobinso** [comment]
Hi @aadamk sorry for the delay.    Coordinates are not really extracted, they are computed from fields in the SAM/BAM specification  https://samtools.github.io/hts-specs/SAMv1.pdf.  The most important fields here for position are the "POS" field and "CIGAR".  Other flags will tell you if the alignment is supplementary, primary, etc.  IGV does not have such an export option, you might ask on a more general analysis forum such as biostars or seqanswers if such a tool exists.
