### ISSUE TITLE
Duplication reads function is not working in Windows 2.8.0

### ISSUE THREAD

**Issue by CancerGenome** [igvteam/igv#743]
Then function of  "filter duplicated" in the preference -> alignment   is not working in Windows 2.8.0. 
The total depth didn't change before or after checking "filter duplicated".

I have tried the SAME bam file in Mac 2.8.0, it works. Is there anything different between Windows version and Mac version?

Thanks,

**Comment by CancerGenome** [comment]
By the way, I checked this problem with bam files from whole exome seq and RNA-seq. Only the RNA-seq has this issue. 
Thanks,

**Comment by jrobinso** [comment]
I can't duplicate this issue.  Could you extract a small portion of the bam that can reproduce the issue?  I can provide a dropbox link or you can email the bam to igv-team (at) broadinstitute.org.  To answer your question, no there is no difference between Windows and Mac, it is the same code.

**Comment by jrobinso** [comment]
Can't reproduce, re-open with test data if the problem persists.
