### ISSUE TITLE
Problem with viewing the annotations

### ISSUE THREAD

**Issue by efratca** [igvteam/igv#745]
Hi,

When I uploaded the following gtf file:
[sort_Moesziomyces_aphidis_dsm_70725_gca_000517465.PseuAph1.0.45.zip](https://github.com/igvteam/igv/files/4092413/sort_Moesziomyces_aphidis_dsm_70725_gca_000517465.PseuAph1.0.45.zip)
 to the IGV, I had problems with the annotations. I saw the annotations for only one chromosome (Seq1) and only the transcript_id and not the gene_id. Can you please help me with that?

Thanks

**Comment by helgathorv** [comment]
1) Regarding the feature labels:
You can set the display name to any field in the GTF file by adding the following line to the file:
##displayName="<field name>"
For example:
##displayName="gene_id"
will use the gene id's from your file to label the features.
However, you can't mix and match, and use different fields for different feature types in the same file.

2) If you saw the annotations only for one chromosome, then the chromosome names in the reference genome you have loaded probably don't match the names in the GTF file (except for Seq1).

**Comment by efratca** [comment]
Thanks for your answers, but the problem still didn't be solved.  
As you mentioned, I added the following line: ##displayName="gene_id" to the gtf file, but it didn't give the gene_id, it didn't give any name. In addition, the chromosome names in the reference genome and in the annotations file are the same, but as I wrote before in the IGV only Seq1 has been seen. 
Thanks

**Comment by helgathorv** [comment]
This conversation was continued in issue #751.
