### ISSUE TITLE
doc errata(?) "Data must be sorted by start position"

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#747]
https://software.broadinstitute.org/software/igv/IGV instructs that "Data must be sorted by start position" but I find that it must be sorted by chromosome and within chromosome by start position.

**Comment by jrobinso** [comment]
Well, technically it must be grouped by chromosome then sorted by start position but I get your point.   The general term used by genomic tools is "coordinate sorted".

**Comment by malcook** [comment]
Fair enough - in either case, the docs could be clearer on the point.  Am I to understand though that the order of the chromosome does not matter?  Not that I really care.
