### ISSUE TITLE
drag & drop xml .igv session file from (chrome) web browser succeeds after raising error

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#750]
Using IGV 2.8.0, I find that if I drag&drop from chrome web browser under windows the session successfully loads, but only after alerting me of unrecognized file extension:

![image](https://user-images.githubusercontent.com/484282/72914349-2d749500-3d04-11ea-870d-697553ec3549.png)

Otherwise, this capability (apparently provided in response to #291) seems to work quite well.

**Comment by brainstorm** [comment]
I suspect that the final `.url` is the culprit. IGV [will only read `.xml` or `.session` as session files, AFAICT](https://github.com/igvteam/igv/blob/1abce3c830f35bdedb29d40a29586c4d1f0be996/src/main/java/org/broad/igv/ui/action/LoadFromURLMenuAction.java#L92).

**Comment by malcook** [comment]
In my hands, it succeeds in opening the IGV_Session as if it were open as a file:// URL.  

Even though, yes, apparently the implementation of drag&drop is to create a .url file and have IGV open it.

So, it **succeeds**, but only after reporting "Unknown file type".

If it is smart enought to succeed, it probably could be smart enough to not report the Message.

**Comment by jrobinso** [comment]
Appears to be fixed
