### ISSUE TITLE
Problem with viewing the annotations

### ISSUE THREAD

**Issue by efratca** [igvteam/igv#751]
Thanks for your answers, but the problem (as written in the closed issues) still didn't be solved.
As you mentioned, I added the following line: ##displayName="gene_id" to the gtf file, but it didn't give the gene_id, it didn't give any name. In addition, the chromosome names in the reference genome and in the annotations file are the same, but as I wrote before in the IGV only Seq1 has been seen.
Thanks

**Comment by jrobinso** [comment]
I can't reproduce the "Seq1" problem.  Could you bundle and share your fasta and gtf file?

Please don't open new issues for the same problem, its too difficult to track.

**Comment by efratca** [comment]
Hi,
Attached the genome and gtf files.
Thanks
[genome.zip](https://github.com/igvteam/igv/files/4117152/genome.zip)

**Comment by helgathorv** [comment]
Hi,

First, my apologies for the bad info on the ##displayName. I had tested a few variations to be sure which ones worked and then copy/pasted the wrong one into the response. I also see that the markdown rendering removed part of what I wrote. Anyway, it works if you do not have the double quotes around the field name: 
##displayName=gene_id

Regarding the other issue, thank you for sending the files. There's something wrong with the index file. To see your annotations, you can either 
(a) Load the file without using an index (rename or move the existing index away from the GTF file), or 
(b) Create another index in igvtools: In IGV, load your genome fasta; select Tools > Run igvtools; select Command="Index"; Select the GTF file; Click Run.

Helga

**Comment by efratca** [comment]
Hi,
Thanks a lot, it is working now

**Comment by helgathorv** [comment]
Great, thanks for letting us know.

**Comment by fangling0913** [comment]
This is my batch script
`new
preference SAM.DOWNSAMPLE_READS false
preference SAM.SHOW_DUPLICATES false
preference SAM.FILTER_SECONDARY_ALIGNMENTS false
preference SAM.SHOW_SOFT_CLIPPED false
preference SHOW_REGION_BARS false
preference SAM.SHOW_CENTER_LINE true
preference SAM.GROUP_OPTION SAMPLE
preference SAM.SORT_OPTION NUCLEOTIDE
preference SAM.FILTER_FAILED_READS true
preference SAM.DOWNSAMPLE_READS false
preference SHOW_SEQUENCE_TRANSLATION false
preference SAM.COLOR_BY NONE
preference SHOW_GENOME_SERVER_WARNING false
preference SAM.FILTER_SUPPLEMENTARY_ALIGNMENTS false
genome /data/ONCO/development/projects/fangling/igv_batch/hg19.genome
load CA20061601-11800710D11P24_200618_142753.bam
snapshotDirectory /data/ONCO/development/projects/fangling/igv_batch
setSleepInterval 4000
goto chr2:29455250-29455250
sort base
expand
snapshot chr2_29455250.png
goto chr4:1803568-1803568
sort base
expand
snapshot chr4_1803568.png
goto chr17:7578461-7578461
sort base
expand
snapshot chr17_7578461.png
exit
`
The refGene shows several transcripts:
![image](https://user-images.githubusercontent.com/52685274/86314057-3d03ec80-bc59-11ea-91c5-d6380f86aa75.png)
how can I choose one script

**Comment by jrobinso** [comment]
@fangling0913 What does your question have to do with this issue?    I'm not sure what your question is, but I will make a guess, you want to show a single transcript.   You cannot do that.   You have expanded the track, it will show all transcripts.   If that does not answer your question open a new issue,  don't tag on an unrelated one,  with more detail.

**Comment by fangling0913** [comment]
@jrobinso Yes. You get my question. I only want to expand the alignment track. The refGene track should be collapsed. How to set it?

**Comment by jrobinso** [comment]
Don't use the "expand" command, the alignments are expanded by default.    Again if you have a new question open a new issue, don't reply to an unrelated one.
