### ISSUE TITLE
Experiment type not detected for RNA-seq data

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#761]
RNA-seq alignments from the Body Map data does not automatically get detected as RNA data.

1. Load Human hg18
2. Load from Server > Body Map 2.0 > Merged 50bp and 75bp > Reads > heart
3. Zoom in to load data
- "Other" is checked in track's popup menu Experiment type.
- It's not just a matter of the menu display being wrong. The  junction track is not displayed even though it is enabled in Preferences > RNA. Explicitly changing the experiment type to RNA in the menu will add the junction track to the display.

**Comment by jrobinso** [comment]
@helgathorv ,  I can't reproduce this.  What locus did you zoom into?  I used "slc25a3".

Note that the detection is not perfect, for example if you zoom into a region that looks like DNA (has no or very few junctions) its not going to work.
