### ISSUE TITLE
Could we have continuous-delivery for bioconda?

### ISSUE THREAD

**Issue by Hoeze** [igvteam/igv#765]
Hi, I noticed that the latest bioconda IGV version is 2.5.2 while the lastest release is 2.8.0.
Would it be possible to automatically update bioconda when there is a new IGV release?

**Comment by jrobinso** [comment]
Hi, we don't do the bioconda release,  I'm not sure who does.  Do they have a github repository you can open an issue in?

**Comment by Hoeze** [comment]
Ah, I did not know that. I created an issue at bioconda. Thanks @jrobinso!

**Comment by jrobinso** [comment]
No problem.   Let me know what they say or reference me from the issue if I
can do anything to support this.
