### ISSUE TITLE
Immunoglobulin genes

### ISSUE THREAD

**Issue by Eilama** [igvteam/igv#767]
Hi, 

I am interested in looking at the IGH (constant regions of immunoglobulin genes) but they are not annotated in the IGV browser (and don't show up when searching for them)
For instance IGHM should be at : Chromosome 12: 114,659,078-114,660,941 reverse strand in mm9 and Chromosome 12: 113,418,558-113,422,730 in mm10 (according to Ensembl). 
The other immunoglobulin genes are also annotated (8 gene segments total) but are not found in the igv browser. 

It would be great if you can add these tracks 

Thank you, Amalie

**Comment by jrobinso** [comment]
Hi, could you give me a pointer to gff3 or gtf files for the tracks requested?
