### ISSUE TITLE
Convert wig file to BigWig

### ISSUE THREAD

**Issue by elenu** [igvteam/igv#769]
Hi!

I'm trying to install wigToBigWig in order to transform my wig files to BigWig files and opening them to https://genome.ucsc.edu/cgi-bin/hgCustom website. 

This is because if I tried as wig or wig.gz file, or even from the GEO source, I always got the same error:
Unrecognized format line 1 of ftp://ftp.ncbi.nlm.nih.gov/geo/serie...SS%2Ewig%2Egz: fixedStep chrom=chr7 start=1 step=10 span=10 (note: chrom names are case sensitive, e.g.: correct: 'chr1', incorrect: 'Chr1', incorrect: '1') 

But now, I cannot install wigToBigWig from the UCSC webpage. I tried:
wget "http://hgdownload.cse.ucsc.edu/admin/exe/userApps.v324.src.tgz"

I have now tried to open the wig file with IGV but it does not work.

Is there another way?

Thank you in advance.

Best,
Elena

**Comment by jrobinso** [comment]
This is an IGV forum, you would need to ask UCSC questions at a UCSC forum.

WRT IGV, please describe what you mean by "does not work", with steps to reproduce and a pointer to the file.  Also, always include the IGV version number with problem reports.

**Comment by elenu** [comment]
Dear jrobinso,

I just mentioned the UCSC to put you into context.

You're right in your correction. IGV "did not worked" because I just obtained a flat line when uploading .wig files. In any case, I already managed to see the real content by converting .wig files into .tdf files.

Thank you for your answer and advices.

Best,
Elena
