### ISSUE TITLE
Add a refresh action to tracks

### ISSUE THREAD

**Issue by duartemolha** [igvteam/igv#77]
Hi Guys

I was wondering if any of you have planned or considered adding a refresh feature to the tracks.

So lets say you have a track of a bed file you opened in IGV. It would be great if you could right click on the name of the track and select "refresh data".

Without this feature, if I want to update a track with new data contained within the original bed file I have to remove the track and reopen it . It is a bit cumbersome and if you have made modified that track like changing the color or font or anything else you will loose them and have to reapply them.

**Comment by duartemolha** [comment]
also ... in addition to this... at least in windows I have found that the tracks imported into IGV become locked from further writing even after you remove them from IGV.

For example ... lets say you import a bed file to IGV .. you look at it and you find something wrong with it ... so you remove the track but do not close the session or IGV.

You then try to regenerate that file or delete it from its current folder and windows will not let you saying IGV is using that file even though I had removed it from IGV.

**Comment by jrobinso** [comment]
This is quite difficult to implement for everything except simple annotation tracks.   In general there is not a 1-1 correspondence between track and file, and some tracks are not backed by files at all.     Could you expand on the use case that motivates this request,  and narrow it if possible?    Frequent file content changes over the course of an igv session is not a very common use case.  Also apologies for the long delay on this one.

**Comment by duartemolha** [comment]
I would like to be able to do this because some times I make bed file operation on files that are opened in IGV and would like to see the changes reflected in the underlying bed files opened in a current IGV session without having to close IGV and reopen the session. I realise that it might be a uncommon use case.. but for me it would be very useful.
