### ISSUE TITLE
Error encountered querying alignments 

### ISSUE THREAD

**Issue by somabdn** [igvteam/igv#771]
Hi, I can upload BED, BAM and BAI files but no reads appear and when I try to zoom in to a region this error message comes up. Has this been seen by anyone and is there an easy fix? Thanks! 

Error encountered querying alignments: org.broad.igv.util.HttpUtils$UnsatisfiableRangeException: Requested range not satisfiable.

**Comment by jrobinso** [comment]
Always give the igv version number when reporting an issue.

This usually means your bam index (bai) is out of date or corrupt.   The fix is recreate the index.
