### ISSUE TITLE
view supplementary alignment region in split screen

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#774]
Split off from #632

**Comment by jrobinso** [comment]
duplicate of #738

**Comment by olechnwin** [comment]
I'm sorry if this is described somewhere but I can't find any documentation for this. 
How do I view supplementary alignment in split screen? I only see I am currently using IGV 2.13 and looking at HiFi bam aligned using minimap2. Thank you!

**Comment by lbergelson** [comment]
@olechnwin Its not implemented yet. I'm implementing it on it and it should be in the next release hopefully.

**Comment by olechnwin** [comment]
> Ah, that makes sense, it's closed because it's a duplicate of the other open issue :)

This is helpful to know. Thank you!
