### ISSUE TITLE
Support Gradle 6

### ISSUE THREAD

**Issue by yurivict** [igvteam/igv#777]
Both gradle4 and gradle6 fail to build the version ```2.8.1```:
```
===>  Building for igv-2.8.1

Welcome to Gradle 4.10.3!

Here are the highlights of this release:
 - Incremental Java compilation by default
 - Periodic Gradle caches cleanup
 - Gradle Kotlin DSL 1.0-RC6
 - Nested included builds
 - SNAPSHOT plugin versions in the `plugins {}` block

For more details see https://docs.gradle.org/4.10.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/usr/ports/biology/igv/work/igv-2.8.1/build.gradle' line: 161

* What went wrong:
A problem occurred evaluating root project 'igv'.
> Could not set unknown property 'archiveFileName' for task ':jar' of type org.gradle.api.tasks.bundling.Jar.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
*** Error code 1
```

```
===>  Building for igv-2.8.1

Welcome to Gradle 6.1.1!

Here are the highlights of this release:
 - Reusable dependency cache
 - Configurable compilation order between Groovy/Kotlin/Java/Scala
 - New sample projects in Gradle's documentation

For more details see https://docs.gradle.org/6.1.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> invalid flag: --module-path

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 21s
1 actionable task: 1 executed
*** Error code 1
```

**Comment by jrobinso** [comment]
I'm building with Gradle 5.5.1.

**Comment by yurivict** [comment]
The latest Grsdle is ```6.2.2```: https://github.com/gradle/gradle/releases

**Comment by jrobinso** [comment]
Right.  I'm not sure we support it yet.  @David Eby
<eby@broadinstitute.org> can
comment.

**Comment by yurivict** [comment]
All I have remaining is gradle-5.0 and it also fails.

I'll wait with the FreeBSD port update then until you support gradle-6.

**Comment by jrobinso** [comment]
Apologies, David will comment when he's able, I'm not a gradle expert, and
I don't know if its a version problem or not.  I actually doubt it as it
doesn't work with Gradle 4 for you either.   It's building fine on our
internal continuous integration system as well as travis.

**Comment by davideby** [comment]
Hey @jrobinso, sorry, just catching up on this after the weekend.

We actually specify the version of Gradle via the gradlew "wrapper script" and the gradle subdirectory, where the necessary jars to do the build are included.  It's like the old practice of including the Ant build jar in the project to be sure it's built as-expected.  This is what we tell developers to use in the README.md build instructions; so long as that is used, the correct version of Gradle ought to come automatically.  

Personally I have Gradle 4.7 installed on my Linux box and yet builds run fine and uses 5.5.1 because of the included jars.  I'm not sure where these other versions are coming into the picture.

**Comment by yurivict** [comment]
I run ```gradle4 createDist``` in order to build it, and it fails:
> Could not set unknown property 'archiveFileName' for task ':jar' of type org.gradle.api.tasks.bundling.Jar

**Comment by jrobinso** [comment]
@yurivict As @davideby  says use the wrapper, do not run a specific gradle version.  Run
```gradlew createDist```

**Comment by yurivict** [comment]
Unfortunately, gradlew can't be run in the context of package building, because it needs to run gradle with ```--offline``` and other flags.

**Comment by jrobinso** [comment]
Well currently our wrapper uses 5.5.1,  we use a wrapper so the builds are reproducible.    If you can't use a wrapper and you can't use the version we support I don't see a quick solution.   I'm going to retitle this tick to "support Gradle 6" but there is no immediate plans to do so.

**Comment by yurivict** [comment]
```gradlew``` is only suitable for individual builds. All serious packaging systems don't allow downloads during build, so the build should first be run w/out the ```--offline``` flag, and then with the ```--offline``` flag. Additionally, the download cache location should be set for ```gradle```. ALl this is impossible with ```gradlew```.

**Comment by jrobinso** [comment]
Understood, but we support individual builds not packaging systems.  We would consider a PR.
