### ISSUE TITLE
IGV custom file format help page is unclear and possibly incorrect

### ISSUE THREAD

**Issue by bbreton** [igvteam/igv#780]
I'm not certain if this belongs here because as far as I can tell the website help is not in the git repo (or I would give fixing this a shot myself), but hopefully this is the right place to post this.  

There are a number of issues with the page: https://software.broadinstitute.org/software/igv/custom_file_formats

The example does not properly render.  It is all on a single line meaning you have to guess where the line and column breaks should be.

The text contradicts the example:
'The column directive line starts with #column'
but the example has '#columns'
I'm not sure which one is correct, perhaps both work.

The #coords parameter in the example is not explained.  I'm guessing this is for if your genomic coordinates are 0 or 1 based, but it probably should be explicit.

It is also unclear if the column separator is a tab or space character.  I'm fairly sure it is tabs because that makes more sense and it might be overkill to specify it, but it is an assumption a user would need to make.

And for anyone googling in the future I think though I haven't actually tried it yet I believe the example should be:
```
#columns chr=7 start=8 probe=2 data=4-5
#coords=1
Index\tTargetID\tProbeID_A\tsample 1 methylation\tsample 2 methylation\tGENOME_BUILD\tCHROMOSOME\tPOSITION
60\tcg00002593\t25796427\t0.7642099\t0.7426524\t37\t1\t1258656
21\tcg00000957\t65648367\t0.8172337\t0.8323303\t37\t1\t5859840
```

Note: Unfortunately I have had to switch projects in the middle of trying to get this to work.  When I do get to go back to the project and hopefully get this working I will update this report with with a tested correct format if it isn't obsolete by then.

**Comment by jrobinso** [comment]
Hi, thanks for the post and apologies.   That is an obsolete page, we will remove it.   Having said that we

**Comment by jrobinso** [comment]
OK, I fixed the documentation page, below is the example data verified with the latest IGV.

```
#columns chr=7 start=8 probe=2 data=4-5 #coords=1
Index	TargetID	ProbeID_A	sample 1 methylation	sample 2 methylation	genome_build	chromosome	position
60	cg00002593	25796427	0.7642099	0.7426524	37	1	1258656
21	cg00000957	65648367	0.8172337	0.8323303	37	1	5859840
```
