### ISSUE TITLE
Developer hints for log4j and IGV argument passing on IntelliJ IDEA

### ISSUE THREAD

**Issue by brainstorm** [igvteam/igv#781]
This issue stems from https://github.com/igvteam/igv/issues/764 proxy debugging process.

After testing several combinations with IntelliJ IDEA and its VM options [while following the official apache log4j config precedence logic (`-Dlog4j.configurationFile=log4j2_debug.xml` and similar)](https://logging.apache.org/log4j/2.x/manual/configuration.html), I've found that so far the only working strategy is directly editing the default `log4j2.xml`:

```diff
diff --git a/src/main/resources/log4j2.xml b/src/main/resources/log4j2.xml
index 6ea7e906a..bb6d38ddd 100644
--- a/src/main/resources/log4j2.xml
+++ b/src/main/resources/log4j2.xml
@@ -33,8 +33,8 @@
     </Console>
   </Appenders>
   <Loggers>
-    <Logger name="org.broad.igv" level="info"/>
-    <Root level="info">
+    <Logger name="org.broad.igv" level="all"/>
+    <Root level="all">
       <AppenderRef ref="stdout"/>
     </Root>
   </Loggers>
```

The example above will not only get the `DEBUG` level but `all` others (`TRACE`, etc...), adjust at your convenience. Apparently, Eclipse does not seem to be affected by this issue, according to @davideby .

@pelacables, feel free to use that in your ongoing proxy debugging efforts and let me know if that works for you. 

In fact, you don't even need to have the IDE/dev setup since this [works too for the builds distributed by the Broad, AFAICT](http://software.broadinstitute.org/software/igv/download) via plain commadline after the following changes:

```diff
--- igv.sh.orig	2020-03-14 14:44:12.000000000 +1100
+++ igv.sh	2020-03-14 14:44:39.000000000 +1100
@@ -20,4 +20,5 @@
     @"${prefix}/igv.args" \
     -Dapple.laf.useScreenMenuBar=true \
     -Djava.net.preferIPv4Stack=true \
+    -Dlog4j.configurationFile=log4j2_all.xml \
     --module=org.igv/org.broad.igv.ui.Main "$@"
```

I suspect that the IDE's Gradle runner is interfering with the VM options passed for log4j.

/cc @reisingerf

**Comment by brainstorm** [comment]
It would also be nice to have some indication on how to run IGV app-level parameters through the editor, since I'm able to run the following via the CLI:

```
./gradlew run --args='--igvDirectory=/Users/romanvg/.igv-dev --preferences=/Users/romanvg/.igv-dev/prefs.properties --port=60152'
```

But on IDEA it fails:

![Skärmavbild 2020-04-22 kl  11 00 13](https://user-images.githubusercontent.com/175587/79929253-921cc880-8488-11ea-826e-12f60153caf0.png)
![Skärmavbild 2020-04-22 kl  11 00 42](https://user-images.githubusercontent.com/175587/79929266-9517b900-8488-11ea-8918-8b4904f9e47a.png)

**Comment by jrobinso** [comment]
Tell me about it!  The following seems to work, I can't pretend to understand why.  Notice the "Tasks:" field

<img width="1074" alt="Screen Shot 2020-04-21 at 10 05 40 PM" src="https://user-images.githubusercontent.com/933148/79942747-65cb6280-841c-11ea-8d3f-02e12c20a5ad.png">

**Comment by brainstorm** [comment]
OMG thanks so much! :)

Log level parameters (i.e debug) work for you without modifying the actual `log4j.xml` file manually?

**Comment by jrobinso** [comment]
@brainstorm I didn't mean to say that, I have long forgotten how log4j configuration works.

**Comment by brainstorm** [comment]
Oh, no, I was just asking in addition, just in case you had that one figured out too ;)

**Comment by brainstorm** [comment]
Actually, that doesn't work for me either:

![Skärmavbild 2020-04-22 kl  16 04 40](https://user-images.githubusercontent.com/175587/79946324-0f5d3300-84b3-11ea-9ebf-cf035e8973ca.png)

![Skärmavbild 2020-04-22 kl  16 05 42](https://user-images.githubusercontent.com/175587/79946351-22700300-84b3-11ea-8581-a2e9a1b5cf43.png)

**Comment by brainstorm** [comment]
I just figured it out, this is ridiculous but works:

![Skärmavbild 2020-04-22 kl  16 10 30](https://user-images.githubusercontent.com/175587/79946695-ceb1e980-84b3-11ea-995e-57607176243c.png)
