### ISSUE TITLE
Compatibility between Relative Paths in Saved Sessions for OSX and Windows

### ISSUE THREAD

**Issue by wuronald** [igvteam/igv#787]
I'm having issues opening a saved session that was created on a Windows 10 PC on my Macbook (MacOS 10.12.6). The reverse is also true with a saved session created on MacOS and opened on Windows 10.

I think the issue is with how these operating systems use slashes in their paths, with windows using forward slashes and mac using backslashes.

Is there a workaround for this?

**Comment by brainstorm** [comment]
One possible workaround is keeping things on the cloud (AWS) so (S3) paths and shared can be shared across multiple participants... it requires some time investment to set it up though:

https://umccr.org/blog/igv-amazon/
https://umccr.org/blog/igv-amazon-backend-setup/

IMHO, it can be rather complex to disambiguate paths across heterogeneous storage and authentication systems.

**Comment by jrobinso** [comment]
@wuronald Could you share one  that is giving you an issue?    You don't have to share the whole session file, just the problematic path.
