### ISSUE TITLE
Poor memory utilisation

### ISSUE THREAD

**Issue by Maplesoup** [igvteam/igv#788]
I won't pretend to be an expert on how IGV works or the file formats that it uses but IGV seems to struggle when working with very large files but I am a software developer with a partner suffering when attempting to use IGV.

My other half currently has several BAM files that all need to be opened at the same time for comparison with other BED files. This results in IGV attempting to use well over 10gb of memory. I can only assume that IGV attempts to load all of files into memory to make them viewable. This results in IGV throwing a memory error and just displaying blank tracks.

This should really be looked at as the data viewable on screen at one time can't amount to the amount of memory actually in use. 

I can think of 2 possible solutions

1 - build a tool that can split the BAM files down into sequential parts and add information into the index as to which bam file to load. Then load and unload parts as and when they are required. 

2 - enable the BAM files to converted into a format where only the data required to be viewed can be loaded record by record like a database using key value pairs to store the data. This will allow more utilisation of the disk rather than memory meaning you won't need a computer with 64gig of ram just to view data.

**Comment by jrobinso** [comment]
@Maplesoup actually IGV does not attempt to do anything like that.  It uses the index to extract just the slice in view.   What you are describing is anomalous behavior.    Are you sure the bed file is not the culprit?

**Comment by jrobinso** [comment]
Here's a link to a view from a 300 GB bam file, its web igv but the desktop version works the same.  The size of the bam file is irrelevant with respect to memory usage.  http://tinyurl.com/r9se9gn

If you want me to look further into your specific problem please save a "session" file (file > save session).     Place the session file and the "prefs.properties" file, found in an "igv" folder in the user home directory, in a zip and attach it here.    Alternatively you could prepare a reproducible use case but I assume that is not possible.

**Comment by Maplesoup** [comment]
@jrobinso I apologise for my assumption then that's good to hear. Currently we are loading 3 bam files totaling around 14gig (I've increased the max memory in the igv.bat to allow 14gig pc has 16 total) currently we just load the files in and then watch the memory increase to about 12gig in task manager then get a low memory warning. 

I'll grab the laptop and try grab the session information.

**Comment by Maplesoup** [comment]
Ok we understand what's happening. 

I'd argue that it's probably to do with the order in which we are using the software rather than the software failing on us. 

Basically we loaded the Bam files first then select a chromosome, this sets the zoom factor on the right to be as zoomed out as possible. This ends up loading way too much data and throws the error.

If we load the chromosome first then zoom in half way on the zoom selector then load the bam files we can avoid the issue. So I've had my partner make a note of this process to follow going forward.

I've noticed that if we zoom out then back in that javaw seems to hold onto quite a chunk of memory that was allocated when zooming out. Is this IGV caching the data for performance or a characteristic of Java much like C#'s garbage collection?

**Comment by Maplesoup** [comment]
Also if you change the chromosome you want to view it zooms straight back out again which loads all the data from the bam files and it gets the error again. So we have to unload the bam files, change chromosome, change zoom level, load the files again.

**Comment by jrobinso** [comment]
@Maplesoup that shouldn't happen unless you've change the settings.   By default alignments will not be loaded beyond a window of 30kb,  you will see a "zoom in to see alignments" message.  That's why I asked to see your prefs.properties file.   There is no way possible to view alignments at the scale of mammalian chromosomes.    Also it doesn't really make sense to do that in most cases, you can't possibly see individual alignments.   If you are just looking at basically coverage there are very memory efficient formats to do that.   Without knowing your preference settings I really can't help you here. 

Yes Java is garbage collected very much like C#.
