### ISSUE TITLE
NullPointerException when running batch script

### ISSUE THREAD

**Issue by mkirsche** [igvteam/igv#790]
Hi,

I am trying to use a batch script to visualize a large collection of variants in IGV 2.8.2.  The idea is that I load the files, set the screenshot directory, and then for each variant, zoom in on a window around it and take a screenshot.  However, when I do that, I get the following error message (I added the previous few successful commands for some additional context):

```
INFO [2020-04-07T10:50:15,193]  [CommandExecutor.java:209] [pool-3-thread-2]  OK
INFO [2020-04-07T10:50:15,194]  [BatchRunner.java:72] [pool-3-thread-2]  Executing Command: goto 1:631277-631378
INFO [2020-04-07T10:50:15,195]  [CommandExecutor.java:209] [pool-3-thread-2]  OK
INFO [2020-04-07T10:50:15,196]  [BatchRunner.java:72] [pool-3-thread-2]  Executing Command: sort position
INFO [2020-04-07T10:50:15,196]  [CommandExecutor.java:209] [pool-3-thread-2]  OK
INFO [2020-04-07T10:50:15,196]  [BatchRunner.java:72] [pool-3-thread-2]  Executing Command: collapse
INFO [2020-04-07T10:50:15,197]  [CommandExecutor.java:209] [pool-3-thread-2]  OK
INFO [2020-04-07T10:50:15,197]  [BatchRunner.java:72] [pool-3-thread-2]  Executing Command: snapshot 1_631327.png
Snapshot: /home/mkirsche/git/svs/igv/1_631327.png
ERROR [2020-04-07T10:50:15,212]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NullPointerException: null
	at org.broad.igv.sam.AlignmentTrack.renderAlignments(AlignmentTrack.java:542) ~[igv.jar:?]
	at org.broad.igv.sam.AlignmentTrack.render(AlignmentTrack.java:441) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanelPainter.draw(DataPanelPainter.java:229) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanelPainter.paintFrame(DataPanelPainter.java:165) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanelPainter.paint(DataPanelPainter.java:102) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanel.paintComponent(DataPanel.java:170) ~[igv.jar:?]
```

The commands I'm using for initialization are here:

```
new
genome /home/mkirsche/git/svs/data/GRCh38.mainchrs.fa
load /mnt/work-zfs/giab/AshkenazimTrio/alignments/HG002_2020_ONT.sort.bam
snapshotDirectory /home/mkirsche/git/svs/igv
```

And there are a few variants before the one where IGV crashes that seem to work fine and produce screenshots in the desired directory, so that makes me think the genome and alignments/index files are fine.

Could you please look into what might be causing this behavior?

Thanks!
Melanie

**Comment by jrobinso** [comment]
There's not enough information in the error message to determine this.
 Could you share the bam file, or reproduce the error on a
publicly available bam file?

**Comment by mkirsche** [comment]
Hi,

Thank you for the fast reply!

I have extracted/indexed a portion of the BAM file (aligned to GrCh38 main chromosomes with "chr" stripped from the chromosome names), verified that I still get the same error with it, and uploaded that along with my batch script here:

https://drive.google.com/file/d/1K4x7WcJuO_zr6BW8lFeoQy9AGl2sT9g6/view?usp=sharing

Thanks.
Melanie
________________________________

**Comment by jrobinso** [comment]
Thanks for the test data.  I can reproduce it but don't have a quick solution.   This might require some extensive re-engineering.

**Comment by jrobinso** [comment]
Apologies for not updating this issue, this should be fixed in the latest release.  If its still crashing please re-open.
