### ISSUE TITLE
not showing alignments and some texts not rendered on Ubuntu 18lts

### ISSUE THREAD

**Issue by xfengnefx** [igvteam/igv#792]
Perhaps related to https://github.com/igvteam/igv/issues/647 (closed but not solved, Apr 2019).

Environment: local Ubuntu 18.04.3 LTS on a thinkpad; has java 11 (default), java 8 (anaconda), IGV's bundled jdk.

Affected version: 2.4.0, 2.4.19, 2.7.x, 2.8.0, 2.8.2 release; didn't build from source.

Observations:

- IGV GUI was able to spawn from command line (`./igv.sh`), using either the bundled JDK or forced to system JDK 11. The GUI won't crash or anything. 

```
echo Using bundled JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)
WARN [2020-04-09T20:13:03,559]  [Globals.java:139] [main]  Development mode is enabled
INFO [2020-04-09T20:13:03,576]  [DirectoryManager.java:179] [main]  IGV Directory: /home/usrname/igv
INFO [2020-04-09T20:13:04,272]  [Main.java:159] [AWT-EventQueue-0]  Startup  IGV Version 2.8.0 01/06/2020 08:43 PM
INFO [2020-04-09T20:13:04,285]  [Main.java:160] [AWT-EventQueue-0]  Java 11.0.5 (build 11.0.5+10) 2019-10-15
INFO [2020-04-09T20:13:04,286]  [Main.java:163] [AWT-EventQueue-0]  Java Vendor: AdoptOpenJDK https://adoptopenjdk.net/
INFO [2020-04-09T20:13:04,286]  [Main.java:165] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK   
INFO [2020-04-09T20:13:04,287]  [DirectoryManager.java:84] [AWT-EventQueue-0]  Fetching user directory... 
INFO [2020-04-09T20:13:04,341]  [Main.java:168] [AWT-EventQueue-0]  Default User Directory: /home/usrname
INFO [2020-04-09T20:13:04,342]  [Main.java:169] [AWT-EventQueue-0]  OS: Linux 5.3.0-45-generic amd64
INFO [2020-04-09T20:13:05,070]  [GenomeManager.java:192] [pool-3-thread-1]  Loading genome: /home/usrname/igv/genomes/hg38.genome
INFO [2020-04-09T20:13:07,836]  [GenomeComboBox.java:90] [AWT-EventQueue-0]  Enter genome combo box
INFO [2020-04-09T20:13:07,846]  [GenomeManager.java:284] [pool-3-thread-1]  Genome loaded.  id= hg38
INFO [2020-04-09T20:13:07,852]  [CommandListener.java:120] [Thread-4]  Listening on port 60151
INFO [2020-04-09T20:13:35,101]  [HttpUtils.java:943] [pool-2-thread-2]  Range-byte request succeeded
INFO [2020-04-09T20:13:47,304]  [IGV.java:1338] [pool-3-thread-2]  Loading 1 resources.
INFO [2020-04-09T20:13:47,320]  [TrackLoader.java:126] [pool-3-thread-2]  Loading resource, path /home/usrname/Documents/prj/test.bam
```
- Track names, labels inside the tracks (e.g. entry names for .bed file blocks) were not rendered.

- BAM alignments were not rendered; more specifically, IGV was able to load the BAM file, but the track would display "zoom in to see alignments" even if already maximally zoomed in and (I think) most alignment-related thresholds were set to as low as possible.

- Chromosome names, menus, window's title name were rendered properly.

- Interactions were normal, e.g. zoom in, drag the tracks, load files etc.

- I don't whether this is relevant but: the warning lines are probably not the cause since I see them too on another machine that runs IGV alright.

Issue not solved by:

- Restart OS;

- Restart terminal / reopen IGV;

- Tried IGV 2.4.x which was JDK8. 

- Force to use system java (and update or reinstall system java via apt install)

I'm guessing that this is not entirely java's problem, and maybe just like https://github.com/igvteam/igv/issues/647 it's my Ubuntu 18 missing something related to text/object rendering, which was silently handled by java or IGV. Hadn't modified the Ubuntu 18, main usages were apt/conda/bash things.

I'd love to know if there's any means that I can use to track down stuff and fix it - have a working IGV on remote server and ssh forward the X11 for me, but when it comes to BAM files the network lagging is painfully slow and occasionally soft freezes my local GUI.

Thanks!

**Comment by jrobinso** [comment]
Hopefully someone with some knowledge can respond.   However we do not recommend remote client / server setups for IGV, they do not work well.   Is there a reason you are using IGV this way?  It works best for nearly all cases as a locally installed application.

**Comment by xfengnefx** [comment]
@jrobinso The remote one is used for some lightweight checkups on shared/spliced files. Actually it worked pretty well when I was at the lab, nothing to complain about. It's just not very fit for the wfh internet (I've spliced the BAM to only show the relevant ~1kb but still no luck, maybe the speed mainly depends on how X11 forward the graphics?). 

Also partially because I've had this rendering glitch with my local IGV for quite a while I would say :)

**Comment by xfengnefx** [comment]
![Screenshot from 2020-04-09 20-13-52](https://user-images.githubusercontent.com/61363437/78959291-81e41100-7ab8-11ea-9045-3310529d1d51.png)

Maybe doesn't help but here's a screenshot I forgot to plug into the main post. The top track is the auto-loaded genes, bottom the sequences, and the middle track is a BAM file. Not sure whether other types of tracks will glitch or not, I can test some if it means something to troubleshooting. (The other active IGV in the screenshot was a remote one, never mind.)

**Comment by jrobinso** [comment]
The main problem with a remote X11 setup is the tremendous amount of client/server traffic spawned by the protocol.      If you really need a remote IGV a VNC setup will work much better.

**Comment by xfengnefx** [comment]
Will look up VNC if I need stay remote but ditch X11, thanks!
