### ISSUE TITLE
Google oAuth does not work properly if running multiple IGV instances

### ISSUE THREAD

**Issue by SHuang-Broad** [igvteam/igv#794]
My IGV session needs access to 6 BAMs stored in Google Cloud buckets.

The nightly build (as of April 14th, 2020) asked for authentication code 6 times.

**Comment by jrobinso** [comment]
I will look into it,  does the released IGV do this?  

Also, are you logging in from the "Google" menu?  This shouldn't matter, but see if that works as a workaround.

**Comment by SHuang-Broad** [comment]
Nope. The release version runs smoothly.

> are you logging in from the "Google" menu?

I tried that, but it still asks me for a code and opens a web browser for generating that code.

I do have a release version IGV open at the same time, but I doubt that matters.

Thanks Jim!

**Comment by helgathorv** [comment]
Actually, I have found that running multiple instances of IGV can confuse Google. Try having only one open.

**Comment by SHuang-Broad** [comment]
Ah, I see. Maybe that's why. I'll git it a try.

**Comment by SHuang-Broad** [comment]
With the snapshot/nightly build itself open, it no longer asks for authentication codes multiple times.

I guess this might be a google cloud problem then.

**Comment by jrobinso** [comment]
So to confirm, the problem occurs with multiple IGVs open at one time, whether released or snapshot?   Is one of the IGVs just passively open, or do they both have Google cloud files open?  

Its not obvious why this should be.   Perhaps requesting an access token for the same app from the same ip address invalidates previous access tokens, but if one IGV is passive and not requesting tokens its not obvious how that would matter.    I'll see if I can reproduce it.

**Comment by SHuang-Broad** [comment]
I opened the same IGV session with a latest release and latest snapshot, release version opened first, snapshot afterward. Then the snapshot version keeps asking for the code.

Can I open multiple release version instances (I mean, same version) at the same time?

**Comment by jrobinso** [comment]
Well, apparently not when loading from Google buckets, based on your experience.     On a Mac you can't open multiple versions, what platform are you using?

**Comment by SHuang-Broad** [comment]
Mac.
I was indeed trying to take a quick glance of a different site and don't want to loose the current site. That was why I wanted multiple instances of IGV open.

**Comment by helgathorv** [comment]
You should be able to open the second IGV mac app by running the following from the command line:
open -n <app>
for example:
open -n /Users/helga/Applications/IGV_2.8.2.app 

This is true of Mac apps in general - it's not a specific IGV thing.

**Comment by SHuang-Broad** [comment]
Ah, that's nice to know!

**Comment by jrobinso** [comment]
I just realized, you can't run multiple instances of IGV and use oAuth (Google authentication), at least not easily.   The Oauth flow needs a url to call back to with the authentication token.   That is "localhost:60151" in our case.   The first IGV you use is going to grab that port.    I don't know what happens with the second, but I think you might get the "copy / paste token" message.   Is that correct?

**Comment by SHuang-Broad** [comment]
Yes, that's exactly what happened. It asked for the token/code multiple times.

**Comment by SHuang-Broad** [comment]
So should I change the ticket title? Or is this a known issue already?

**Comment by jrobinso** [comment]
No leave it alone.   It will have to ask you for the token, because the first IGV owns the port, but it should only do it once.   I'm going to try to reproduce it.

**Comment by jrobinso** [comment]
Leave the ticket title alone I mean.

**Comment by jrobinso** [comment]
OK,  I renamed the issue to be more descriptive.   I can't reproduce your symptoms exactly, but I can hang IGV when trying to do oAuth between 2 instances.  For now we just have to say its not supported  (OAuth login with multiple instances).

**Comment by SHuang-Broad** [comment]
And I don't think it matters, but just incase.

The IGV session was trying to access long read bam stored in regular Google Bucket, and short read bam where my access was provided through Terra (I believe you've heard of Terra the platform).
