### ISSUE TITLE
IGV 2.7.2 does not start -- can anyone help how to fix it?

### ISSUE THREAD

**Issue by Wabram** [igvteam/igv#797]
Hi, 

I have an issue with IGV 2.7.2 on Ubuntu 18.04.4 LTS with java 11.0.6

igv.log file exists
[igv.log](https://github.com/igvteam/igv/files/4496883/igv.log)
prefs.properties empty file exists so I follow  #718 issue [https://github.com/igvteam/igv/issues/718] which not helped.

Maybe someone can help or give me some hints?

**Comment by jrobinso** [comment]
Where did you get this version?  Did you build it yourself?

I suggest downloading a prebuilt-version from
http://software.broadinstitute.org/software/igv/download

**Comment by Wabram** [comment]
Prebuilt-version helped. I am a newbie so probably something messed. Thanks for the help. It was very helpful.
