### ISSUE TITLE
Option to hide names in annotation tracks

### ISSUE THREAD

**Issue by olechnwin** [igvteam/igv#800]
Hi,

This is more of a question than an issue. I tried to search around but cannot find the answer.
I'm viewing a narrowPeak file and wondering if there is an option to show/hide the peak names.
I am referring to the name column inside a narrowPeak.

Thank you!

**Comment by jrobinso** [comment]
Not currently.  Can you provide a screenshot to motivate the need?  The option would probably need to be a general one, not restricted to "narrowPeak".

**Comment by olechnwin** [comment]
Thanks for the quick response.
Yes. I actually think it would be great to have this option in general. 
As shown in the screen shot below, (at this range) the displayed peak name serves no purpose as it is hard to distinguish which bar the name belongs to. It becomes a distraction. Without peak names (track above it), it looks cleaner.
However, the peak names are still useful to easily search a specific peak and for trouble shooting. 

<img width="516" alt="igv" src="https://user-images.githubusercontent.com/20069067/80635043-5dc97f00-8a29-11ea-8c41-4c10b9b5f43b.png">

**Comment by jrobinso** [comment]
Yes I can see how that would be annoying.  I'm going to rename this to reflect the general case.

**Comment by olechnwin** [comment]
@jrobinso, This works great! Much appreciated.
