### ISSUE TITLE
REQUEST: display Feature name(s) appearing in .igv  name as sample attribute

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#801]
Currently, [Feature names are not displayed in IGV\.](https://software.broadinstitute.org/software/igv/IGV).  

It would be quite useful if upon load an .igv file, the Feature name in column 4 could be taken as an attribute name, and values used to color code the attribute display.

In the case the user provided a [custom specification of columns for the "\.igv" file format](https://software.broadinstitute.org/software/igv/custom_file_formats), you could extend the current "column specifier directive " to support a new optional **key** named **feature** whose **value** specify a column or range of column indices (like the data key) to be rendered in the attribute display.

**Comment by jrobinso** [comment]
@malcook Reviewing open issues.  I don't understand this suggestion, the "name" is associated with genome location (row), not any particular column.  This column could be displayed as its own track, something like a simple bed track.  That should be optional, as it would be new behavior.

**Comment by malcook** [comment]
Thanks for the consideration/feedback/education.

I now see that your provision for multiple data columns in .igv files is suited to my underlying need.
