### ISSUE TITLE
IGV 2.8.2 doesn't seem to respect the visibility range threshold

### ISSUE THREAD

**Issue by SHuang-Broad** [igvteam/igv#804]
Hi,

I find that IGV 2.8.2 defaults to decode all reads irregardless of my setting of "Visibility range threshold" (currently 1000kb, to view SVs), by doing to following

load an IGV session, then simply go from the "All" selection in chromosome pulldown menu to any particular chromosome, and hit "Reload tracks". After waiting for a while for IGV to respond, I get "Memory is low, reading terminating".

I'm not sure if this an edge case.

Thanks.
Steve

**Comment by jrobinso** [comment]
Hi Steve,

I can't reproduce this.  Could you send me a session with public data that
will reproduce it?   Also,  I might need to see your "prefs.properties"
file.

**Comment by jrobinso** [comment]
OK, finally I reproduced it in another context.   I'm not sure what triggers this bug, it doesn't always happen, but I'm looking into it.

**Comment by jrobinso** [comment]
@SHuang-Broad Is this still a problem?  I was able to reproduce this on the "master" branch, however I cannot reproduce it on the release tag v2.8.2.   I am using the attached session (File > Open Session) and following your steps.   
[igv_session.xml.zip](https://github.com/igvteam/igv/files/4713621/igv_session.xml.zip)

**Comment by jrobinso** [comment]
@SHuang-Broad  although I couldn't reliably reproduce this, I put come checks in release 2.8.3 that should prevent it from happening again.
