### ISSUE TITLE
Custom HTTPS header for authentication

### ISSUE THREAD

**Issue by sjackman** [igvteam/igv#805]
I'd like to use IGV to view a BAM file hosted over HTTPS that requires a custom HTTPS header to authenticate.

For example, to fetch the file with `curl`, I run `curl -H "cf-access-token: …" https://…/.bam`

 Could IGV add support for a configuration box to add a custom HTTPS headers for this purpose?

**Comment by jrobinso** [comment]
Yes, shouldn't be difficult.    I think we'd have to include some means to specify which files to apply it to, perhaps a regex matching the url, or maybe just a host name.

**Comment by sjackman** [comment]
Thanks, Jim! Specifying host names, possibly with wildcards like `*.foo.com`, would be great.

I launch IGV exclusively from the command line. For my use case, an `igv -H option` command line option mirroring the same option of `curl` that specifies the custom HTTP header(s) (it can be specified more than once) would be ideal. My token rotates periodically, so `igv -H "Authorization: token $TOKEN` would be more convenient for me than a configuration dialog box.

Here's a simple test case for you! Pulling a BAM file from the GitHub API requires the HTTP header `Accept: application/vnd.github.v3.raw`.
```console
$ curl -s 'https://api.github.com/repos/igvteam/igv/contents/test/data/bam/BAMFileIndexTest/index_test.bam' | head -n5
{
  "name": "index_test.bam",
  "path": "test/data/bam/BAMFileIndexTest/index_test.bam",
  "sha": "c33335d331a21aab0f208405c4ff2c13561d218a",
  "size": 597252,
$ curl -s -H 'Accept: application/vnd.github.v3.raw' 'https://api.github.com/repos/igvteam/igv/contents/test/data/bam/BAMFileIndexTest/index_test.bam' | samtools view -H | head -n2
@HD	SO:coordinate	VN:1.0
@SQ	SN:chrM	LN:16571	UR:file:/seq/references/Homo_sapiens_assembly18/v0/Homo_sapiens_assembly18.fasta	M5:d2ed829b8a1628d16cbeee88e88e39eb	SP:Homo sapiens
$ igv -g hg38 -l chrM -H 'Accept: application/vnd.github.v3.raw' 'https://api.github.com/repos/igvteam/igv/contents/test/data/bam/BAMFileIndexTest/index_test.bam'
```

**Comment by adam-azarchs** [comment]
Ideally the patterns should match the format for `~/.netrc`.  Ideally, the user's `.netrc` would also be honored.  The [netrc spec](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html) doesn't offer much, but it's enough at least for many use cases.  For an example of how to extend it, [bazel](bazel.build) offers a [mechanism](https://docs.bazel.build/versions/master/repo/http.html#http_file-auth_patterns) for mapping tokens in the `.netrc` to headers to other header types.

**Comment by jrobinso** [comment]
@sjackman How are you going to enter the URL to this bam,  via the UI or on startup from the command line?

**Comment by sjackman** [comment]
99% of the time I use the command line.

**Comment by jrobinso** [comment]
I added a "-H" command line option, tested as follows.  The header will be added to requests to the host(s) for any files opened in the command.  

```
./igv.sh  -H "Authorization: Bearer <token>" gs://genomics-public-data/platinum-genomes/bam/NA12877_S1.bam
```

**Comment by sjackman** [comment]
Thank you, Jim! I'll try out the nightly build tomorrow.

**Comment by sjackman** [comment]
It works! Thank you, Jim.

```bash
igv-snapshot -g hg19 -l GSTT1 -H 'Accept: application/vnd.github.v3.raw' 'https://api.github.com/repos/igvteam/igv/contents/test/data/bam/gstt1_sample.bam'
```
🎉 

Are multiple headers supported? This test of two headers gave an error:

```bash
❯❯❯ igv-snapshot -g hg19 -l GSTT1 -H 'foo: bar' -H 'Accept: application/vnd.github.v3.raw' 'https://api.github.com/repos/igvteam/igv/contents/test/data/bam/gstt1_sample.bam'
…
INFO [2020-06-15T15:08:03,513]  [MessageUtils.java:76] [pool-3-thread-2]  Error loading https://api.github.com/repos/igvteam/igv/contents/test/data/bam/gstt1_sample.bam: An error occurred while accessing:    https://api.github.com/repos/igvteam/igv/contents/test/data/bam/gstt1_sample.bam<br>Error loading BAM file: org.broad.igv.exceptions.HttpResponseException: Unsupported Media Type <br> {"message":"Unsupported 'Accept' header: [#<Sinatra::Request::AcceptEntry:0x00007f5df31f9bb0 @entry=\"text/plain\", @type=\"text/plain\", @params={}, @q=1.0>]. Must accept 'application/json'.","documentation_url":"https://developer.github.com/v3/media"
```

This test of a CSI index gave an error `Unsupported 'Accept' header`.

```bash
❯❯❯ igv-snapshot -g hg38 -H 'Accept: application/vnd.github.v3.raw' 'https://api.github.com/repos/igvteam/igv/contents/test/data/bam/BAMFileIndexTest/index_test.bam'
…
Error encountered querying alignments: htsjdk.samtools.util.RuntimeIOException: Invalid file header in BAM index https://api.github.com/repos/igvteam/igv/contents/test/data/bam/BAMFileIndexTest/index_test.bam.csi: �
INFO [2020-06-15T13:11:35,612]  [HttpUtils.java:946] [AWT-EventQueue-0]  Range-byte request succeeded
```

**Comment by jrobinso** [comment]
Multiple headers are not supported yet.  In fact I don't know what my command line parser does with that, will have to check.

I wasn't aware you could serve bam files from github like that.   Will have to look into that too.

Ping again if no response by the end of the week.

**Comment by sjackman** [comment]
It's a useful trick! You can serve BAM files up to 1 MB in size that way. Files up to 100 MB can be served up using a different GitHub API:

```console
$ git rev-parse :test/data/bam/NA12878.SLX.sample.bam
5a16ac2e6cf1b8bc20b5f8800bab5adcfee3e646
$ curl -sL -H 'Accept: application/vnd.github.v3.raw' 'https://api.github.com/repos/igvteam/igv/git/blobs/5a16ac2e6cf1b8bc20b5f8800bab5adcfee3e646' | samtools view -H | head -n1
@HD	VN:1.0	GO:none	SO:coordinate
```

IGV doesn't like that URL though, because it doesn't end in `.bam`.

```console
$ igv -H 'Accept: application/vnd.github.v3.raw' -i 'https://api.github.com/repos/igvteam/igv/contents/test/data/bam/NA12878.SLX.sample.bam.bai' 'https://api.github.com/repos/igvteam/igv/git/blobs/5a16ac2e6cf1b8bc20b5f8800bab5adcfee3e646'
Unknown file type: https://api.github.com/repos/igvteam/igv/git/blobs/5a16ac2e6cf1b8bc20b5f8800bab5adcfee3e646 Check file extension
```

**Comment by jrobinso** [comment]
Multiple headers should work now.  The "csi" problem appears to be in the htsjdk.   I'll have to setup a test case for them and submit a bug.

**Comment by sjackman** [comment]
> Multiple headers should work now.

Works for me. Thanks again, Jim!
