### ISSUE TITLE
suggestion for cytoband documentation

### ISSUE THREAD

**Issue by jayoung** [igvteam/igv#806]
hi there,

I'd like suggest an enhancement for the documentation for cytoBand info (https://software.broadinstitute.org/software/igv/Cytoband), as I just spent a frustrating hour trying to my cytoBands appear, adding/removing headers to the file, etc.

I had not realised from that page that the intention is to specify the cytoBand info in the .genome file, rather than as loading a track (although it looks like that feature might come soon, which is cool).  Would be great to clarify that.  

When you try to load a cytoBand as a track it does do something (appears as odd vertical info along the side of all tracks), which was making me think all I needed to do was fix track format.

thanks for considering it!  all the best,

Janet Young

**Comment by helgathorv** [comment]
I can see that would be frustrating! I think that cytoband file format doc was written when a .genome file was the _only_ way to load your own reference genome. We've updated the page to clarify it's for use with .genome files. Thanks for the suggestion.

**Comment by helgathorv** [comment]
Janet, 
here's a link to the Git issue about adding cytoband tracks, in case you want to subscribe to it. https://github.com/igvteam/igv/issues/786

**Comment by jayoung** [comment]
great! thanks, and I will try out cytoband tracks when that becomes possible

Janet
