### ISSUE TITLE
bam file not display

### ISSUE THREAD

**Issue by shihai832** [igvteam/igv#807]
I tried to display attached bam file on IGV. The file loaded but nothing displayed. please help.
[Archive.zip](https://github.com/igvteam/igv/files/4620050/Archive.zip)
[ref.zip](https://github.com/igvteam/igv/files/4620054/ref.zip)

**Comment by helgathorv** [comment]
I tried using your bam and ref genome in IGV, and as the error message says - the names in the reference and the bam don't match. The single chromosome/sequence name in the reference is NC_003143.1, while the bam uses names like Query_1 and Query_2.  They need to match for IGV to know where to display the data.  If you are sure the data is correct, one workaround is to create an alias file in 2-column tab-delimited format. To see how to create this file, see [Creating a Chromosome Name Alias File](http://software.broadinstitute.org/software/igv/LoadData/#aliasfile) in the IGV User Guide.
