### ISSUE TITLE
How to turn insertion markers down?

### ISSUE THREAD

**Issue by xiucz** [igvteam/igv#808]
Hi, 
I have turned on `the insertion markers` or `SHOW_INSERTION_MARKERS ` manually, that purple triangle.
How can I turn it down, not show on ths screen any more?

Thank you.
Xiucz

**Comment by jrobinso** [comment]
Did you try looking in the alignment preferences?

**Comment by xiucz** [comment]
> Did you try looking in the alignment preferences?

Thank you.
