### ISSUE TITLE
Bug with CYP21A1P 

### ISSUE THREAD

**Issue by tky871** [igvteam/igv#809]
I am browsing hg19 and find that CYP21A1P and TNXA on chr6 are incorrectly labelled as CYP21A2 and TNXB, thus duplicating the names of these 2 neighboring genes. Please verify the problem.

**Comment by jrobinso** [comment]
The annotations come from UCSC,  there is nothing really for us to verify.

**Comment by tky871** [comment]
I see, thank you.
