### ISSUE TITLE
Strand issue in sashimi plot in hg38

### ISSUE THREAD

**Issue by wososa** [igvteam/igv#815]
Dear developers,

I used STAR to align stranded RNA-seq reads and visualize it by sashimi plot of IGV 2.8.0. When I click "Forward Strand", only genes on the reverse strand showed junction reads. In other words, the strand information has become the opposite. Is this a known issue? I will appreciate if anyone can give me a hint for this issue.

Thanks,
Woody

**Comment by jrobinso** [comment]
The "strand" is the read strand, or if these are paired reads the read strand of the alignment marked "first in pair".   The relationship between this and the strand from which the RNA was transcribed is somewhat complex and depends on your library prep and protocol.   This is a lot to convey in a simple menu label, but its not really a bug or issue just a convention.   In cases such as yours just click "Forward" when you want to see RNA that was transcribed from the negative DNA strand, and vice versa.   Hope this is clear.
