### ISSUE TITLE
Build fails: invalid flag: --module-path

### ISSUE THREAD

**Issue by yurivict** [igvteam/igv#817]
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> invalid flag: --module-path
```

Build target: ```createDist```

openjdk11-11.0.7+10.2
gradle-5.5.1
OS: FreeBSD 12.1

**Comment by davideby** [comment]
@yurivict Not much of a bug report.  Builds on Linux, Mac as-is on a clean pull from master.  Probably an issue with your environment.
> invalid flag: --module-path
Definitely not invalid for Java 11.  Suggest you try `java -version` and confirm.

> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Did you try it?

**Comment by GregTD42** [comment]
I got the same problem
https://stackoverflow.com/questions/46118716/fatal-error-compiling-invalid-flag-module-path

Changing my JAVA_HOME to point to a java later than Java8 fixed that problem

**Comment by jrobinso** [comment]
IGV requires Java 11, its in the readme.

**Comment by generalbytes** [comment]
The point is that you need Java 11 set also in IntelliJ Build Tools->Gradle settings JVM version option usually independently set from the project settings.
