### ISSUE TITLE
Mutation Data disappears

### ISSUE THREAD

**Issue by vc2504** [igvteam/igv#818]
Hi, I am someone analyzing genome data, and cannot do so because IGV is being quite unreliable in presenting mutations in .MAF files. First, I didn't see any mutations present so I assumed they didn't exist. The second time I opened the file, the mutations were present. I did not close and reopen the file, but rather a few minutes after I had seen the mutations they completely disappeared. There are 2 screenshots I was able to take, first the one with mutations and the second where the same window is completely blank. However, another instance occurred where I could view the gray tracks, but no mutations. So please do not that the disappearance of those tracks in one of the pictures is able to indicate a program error, because sometimes I did see those tracks but did not see the mutations data. 
<img width="1440" alt="Screen Shot 2020-06-07 at 7 12 50 PM" src="https://user-images.githubusercontent.com/66578414/83984656-d3afe880-a8fb-11ea-85a2-afb18cdec411.png">
<img width="1440" alt="Screen Shot 2020-06-07 at 7 34 06 PM" src="https://user-images.githubusercontent.com/66578414/83984660-d6124280-a8fb-11ea-9985-31fa6d4f4238.png">

**Comment by jrobinso** [comment]
Please re-open specifying version number of IGV if this remains a problem.  I can't reproduce it in 2.8.4.
