### ISSUE TITLE
Show soft clipped bases

### ISSUE THREAD

**Issue by shimbalama** [igvteam/igv#826]
Hi.

Is it possible to only view soft clipped bases where in the current window not all of the bases for that read are soft clipped? I'm working with somatic SVs in ONT reads and the screen is full of reads that are fully soft clipped - it makes it very hard to focus on the few where the soft clipping starts at the position I'm interested in.

If this is not possible could I request it as a feature?

Thanks!

**Comment by jrobinso** [comment]
Know its not.  To be sure I understand the request could you define what you mean by "current window",  generally we mean everything that is in view by that term.

Would an option to filter all reads that are fully soft clipped from view help address this?   I wasn't aware that aligners produced such alignments, interpreting what that means is difficult.   If the aligner sets a mapping quality you might be able to filter these using a mapq filter, since I suspect there mapq should be very low.  (View > Preferences > Alignments > Mapping Quality Threshold").

**Comment by shimbalama** [comment]
Thanks for the rapid response, Jim. Re window - yes thats what I meant. I've attached an example - it's not the best example but its the best I could get right now. In this example there are several examples of reads where every base in the current window is soft clipped (the 1st read of the 2nd sample, for example). I don't know where the soft clipping in those reads starts and ends, but it's not at either of the breakpoints i'm interested in.

Would an option to filter all reads that are fully soft clipped from view help address this? Yes - that would be amazing! These are ONT reads commonly up to 50kb in length, they are aligned with NGMLR and have multiple supplementary alignments.

I will try filter by mapping as u suggest.

![igv_snapshot_chr1_248676255_del](https://user-images.githubusercontent.com/17915057/87019113-9057db00-c215-11ea-8336-ad57df72f17b.png)

**Comment by jrobinso** [comment]
Wow what a picture.   You provided an important clarification I missed, all bases **_in the current window_** are soft clipped.   I don't think its possible for an alignment to have 100% of its bases soft clipped.  That wouldn't even be an alignment.  If you think that is happening click on or mouse over the alignment (depending on your preferences) and see what the "Cigar" string is,  I would be interested in seeing that.

So if its not the case that 100% of bases are soft clipped filtering by that criteria wouldn't remove anything.    Its not obvious how we could implement the option you are asking for,  effectively show only the soft clips I want to see.   The criteria would have to involve specifying the breakpoint in some way.

**Comment by jrobinso** [comment]
It might be helpful if you markup that figure showing where the breakpoint of interest is, and exactly which soft clips you want to see.

Here is a trick that might help. Position the view so that the base just to the left (if event is to the right) of the centerline, or alternatively just to the right if the event is to the left.    Then right click and select "sort by base".   the alignments with softclips that  intersect the center line should then be sorted to the bottom, because technically there is nothing there.

**Comment by shimbalama** [comment]
Thanks for the suggestions. I regularly sort by base - this does not normally solve the problem. Break points in ONT data do not neatly line up at one position, they wobble over 10s or 100s or bps. Maybe this is why sorting by base is not often effective. I also don't think its possible for an alignment to have 100% of its bases soft clipped. What I'm talking about is omitting reads where the aligned parts are flanking but completely outside of the current window.

Here's an example sorted by base around a putative breakpoint. It's a super messy region where I doubt I could do much anyway, but it is a good example of what I regularly have to squint through - wall to wall soft clipping. Sorry about the quality, I'm working from home atm.

<img width="1377" alt="Screen Shot 2020-07-10 at 8 38 23 am" src="https://user-images.githubusercontent.com/17915057/87097754-3ee93380-c289-11ea-9bb3-3f3abb689327.png">

**Comment by jrobinso** [comment]
In the top picture most of the rows would not be eliminated by the filter
you propose.  In fact I think only 5 of them would.     Any row with an
insertion (the "I")  bar is not completely soft clipped.   Did you say you
have consensus mismatch turned on here?

Unless you are interested in seeing the actual bases you can turn
soft-clipping off and still flag the regions that are soft clipped.   Have
you tried that?

**Comment by shimbalama** [comment]
Yes only 5 int he top example. Not sure about consensus mismatch - I can't see it in the options. I haven't tried turning
soft-clipping off and flagging the regions that are soft clipped - how do I do that? That sounds like a good start.

**Comment by jrobinso** [comment]
First make sure you are working with a recent release of IGV.  It should
detect your data as 3rd gen, after some alignments load.   If it doesn't
right-click and set the experiment type to 3rd gen.

Select View > Preferences > Third Gen.   "Quick consensus mode" should be
checked.     Check "Flag clipping > flag clipping threshold".   Adjust the
small indel threshold if desired.   I think most of what you are seeing is
not soft clips but random mismatches, "Quick consensus mode" should solve
that.

Next select the "Alignments" tab of preferences and uncheck "Show
soft-clipped bases".

**Comment by jrobinso** [comment]
@shimbalama Have you had a chance to try the suggestions above?

**Comment by shimbalama** [comment]
I have played with it yes. The new 3rd gen options are great. I can confirm that most of what I am seeing is indeed soft clips, not random mismatches and my original feature request stands. If at all possible it would be really useful. However, many of the new 3rd gen options make it easier to work with so no drama if it's too hard basket. Thanks for your help with this.

**Comment by jrobinso** [comment]
It can't be implemented as requested ```Is it possible to only view soft clipped bases where in the current window not all of the bases for that read are soft clipped```,  that would be very difficult to explain or interpret reliably.    For your use case I don't yet understand why you need to see the soft clips at all,  just flagging the clips would highlight the SVs.    If you have other ideas for filtering options please re-open or open a new issue,  I just don't see a way to do this one.
