### ISSUE TITLE
IGV error: Error loading IGV files BBFiles. 

### ISSUE THREAD

**Issue by Janeen-2020** [igvteam/igv#828]
The issue is file upload I only have the .bw files not the original bedgraph files. How to I check for the issue or can i used other file types to upload instead.

**Comment by jrobinso** [comment]
Bigwig files are supported, you don't need any other file type.   If you want us to investigate we'll need more information.  Such as igv versions used, exact description of problem or error message, contents of igv.log file (in the "igv" folder in your home directory).

**Comment by Janeen-2020** [comment]
Hello my IGV version is 2.8.6. Error obtained "Error loading F:\IGV_data\CHG.bw: Error reading BBFile header for: F:\IGV_data\CHG.bw. All other bw files open expect two which displayed this error.

**Comment by jrobinso** [comment]
If you can share the problematic bigwig file I will look into it.  Also I asked for contents of the igv.log file, that might have useful information.  

Another thing I suggest is to use UCSC tools to convert the bigwig back to wig or bedgraph.

**Comment by Janeen-2020** [comment]
Below is apart of the igv.log. I tried to attach the file to the message but I got an error "we don t support that file type". You mention that UCSC tools can convert what is the specific name of the tool, if you don t mind me asking. Also thank you so much for your time. 

INFO [2020-07-05T19:07:24,035] [GenomeComboBox.java:90]  Enter genome combo box
INFO [2020-07-05T19:07:24,126] [GenomeManager.java:284]  Genome loaded.  id= F:\Brassica\DNA\IGV_data\Brassica_rapa.fa
INFO [2020-07-05T19:08:13,446] [IGV.java:1332]  Loading 1 resources.
INFO [2020-07-05T19:08:13,500] [TrackLoader.java:122]  Loading resource, path F:\Brassica\DNA\IGV_data\Brassica_rapa_exon_CDS.gtf
INFO [2020-07-05T19:09:14,916] [IGV.java:1332]  Loading 1 resources.
INFO [2020-07-05T19:09:14,926] [TrackLoader.java:122]  Loading resource, path F:\Brassica\DNA\IGV_data\M1F.CG.bw
INFO [2020-07-05T19:09:53,099] [IGV.java:1332]  Loading 1 resources.
INFO [2020-07-05T19:09:53,112] [TrackLoader.java:122]  Loading resource, path F:\Brassica\DNA\IGV_data\M1F.CHG.bw
ERROR [2020-07-05T19:09:53,178] [BBFileReader.java:137]  BBFile header is unrecognized type, header magic = 0
ERROR [2020-07-05T19:09:53,181] [TrackLoader.java:249]  Error reading BBFile header for: F:\Brassica\DNA\IGV_data\M1F.CHG.bw
java.lang.RuntimeException: Error reading BBFile header for: F:\Brassica\DNA\IGV_data\M1F.CHG.bw
	at org.broad.igv.bbfile.BBFileReader.<init>(BBFileReader.java:138) ~[igv.jar:?]
	at org.broad.igv.track.TrackLoader.loadBWFile(TrackLoader.java:755) ~[igv.jar:?]
	at org.broad.igv.track.TrackLoader.load(TrackLoader.java:172) [igv.jar:?]
	at org.broad.igv.ui.IGV.load(IGV.java:1415) [igv.jar:?]
	at org.broad.igv.ui.IGV.loadResources(IGV.java:1347) [igv.jar:?]
	at org.broad.igv.ui.IGV$4.run(IGV.java:474) [igv.jar:?]
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72) [igv.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by jrobinso** [comment]
@Janeen-2020 Look at the UCSC site under downloads.

**Comment by jrobinso** [comment]
From the error message the bigwig file is corrupt.

**Comment by Janeen-2020** [comment]
In this case, is there any way that the file could be usable. Because if I use the bwtoBedgraph converter wont the file still be corrupt.

**Comment by jrobinso** [comment]
@Janeen-2020 Impossible to say until you try, but if the UCSC tools can't read it then answer is no.
