### ISSUE TITLE
Batch script screenshots: Some are not sorted by base correctly

### ISSUE THREAD

**Issue by ranasats** [igvteam/igv#830]
Hi,

When doing a batch script which goes to pos and sorts by base, I have a handful of screenshots which are not properly sorted, while others are.

Example of script:

```new
genome IGV.genome
snapshotDirectory /screenshots/
load tumor.bam
load normal.bam
maxPanelHeight 500
preference SAM.SHOW_SOFT_CLIPPED true
preference SAM.SHOW_CENTER_LINE true
preference SAM.QUALITY_THRESHOLD 0
preference SAM.ALLELE_THRESHOLD 0.01
preference SAM.COLOR_BY READ_STRAND
preference SAM.DOWNSAMPLE_READS false
setSleepInterval 500
goto 1:16259405-16259405
sort base
collapse
snapshot 1:16259405_p.N2224D.png
goto 1:27101453-27101453
sort base
collapse
snapshot 1:27101453_p.Q1579Ter.png
goto 1:43814636-43814636
sort base
collapse
snapshot 1:43814636_p.W477C.png
goto 10:63816929-63816929
sort base
collapse
snapshot 10:63816929_p.V303SfsTer4.png
```

In this example all of the images are properly sorted aside from 1:43814636_p.W477C.png. This is at the correct spot but unsorted.

Does the order matter (sort first then collapse)? I can't test this because if I run the script a second time all images are sorted. But if I do it 10x times maybe once it'll be unsorted.

**Comment by jrobinso** [comment]
What version of IGV are you using?

**Comment by ranasats** [comment]
I am running an older version, IGV 2.4.10 , was something similar addressed in a newer release?

**Comment by jrobinso** [comment]
That release is  more than 2 years old.  If reporting an issue with older releases at least note that in the report.

Its possible this has been addressed,  but at any rate there's nothing we can do about release 2.4.10.    I suggest you try the current release.    If you continue to have issues re-open the issue, but we'll need a repeatable test case.
