### ISSUE TITLE
"View mate region in split view" freezes IGV on distant reads

### ISSUE THREAD

**Issue by brainstorm** [igvteam/igv#833]
Hello @jrobinso, @igvteam

I have been chasing an IGV freeze bug for a while now. **The regression appeared for sure on commit f9690c6047b92028503031f665dbbc0fe0aa25f4 on Jun 13th**. I bisected from release 2.8.3 (which works) an here's what I found, manually testing the sequence of steps reported by several staff and research members @UMCCR:

4fbb9df78c11234637bae4f2d7857685a5ecb5cb ... Feb 2?	Works
b15e0f0f5e82fbbf14cedef947eddb92a8745513 ...  Mar 7?	Works
4879b5e7eb3099c71ccd5dba004462a704ede677 ... Jun 1?	Works
ce921fd9e77c32b236589151ffcd02e7183ca562 ...  Jun 2?	Works
6979897cf66cf0a518a3f3e9d12661ac657e79c3 ... Jun 12?	Works
b0579ca76ddc8a2b7b79c52a14e5b4df2e52a8f5 ... Jun 12?	Works
**f9690c6047b92028503031f665dbbc0fe0aa25f4 ... Jun 13?	Hangs!**
dd8e3c0f5496990bb3626a3f0448063a0b5f9b72 ... Jun 13?	Hangs!
0f862063c4bcad58d639b1163c8e9322c0b1156e ... Jun 14?	Works but zoom on the right is not shown
b8855c53afb599bb9a33cbd0d1f102a491c0b1e1 ... Jun 20? 	Hangs!
...
All the way to `master` and prior releases **which all freeze/hang IGV completely**.

Would you mind revisiting that "async fix" change? I'll try to craft a minimal reproducer but it might take me a while, by reporting this in advance I hope you can figure it out faster what might be going on here.

/cc @ohofmann @reisingerf

**Comment by jrobinso** [comment]
Thanks for the report, and for narrowing it down.   I'm able to reproduce this with a 1KG file, looking into it.

**Comment by brainstorm** [comment]
Epic fast response, thanks @jrobinso, much appreciated! :)

**Comment by jrobinso** [comment]
There was a thread lock contention.   I'm doing a lot of profiling now, and
looking at making some methods thread safe, to reduce the use of
synchronization generally.   This should give a performance boost in the
end.

However I think the fix I pushed returns us to the status quo.

**Comment by brainstorm** [comment]
Excellent Jim, looking forward to telling our users to download 2.8.8 IGV proper so that they can carry on with mate split view on cancer samples ;)

**Comment by davideby** [comment]
Hey, quick note here @brainstorm.  There's a 2.8.8 release out there **but it doesn't deal with this bug**.  Be on the lookout for **2.8.9** instead.  It should be early next week.

I just didn't want you noticing that and thinking you're all set.  We'll get this out ASAP.

**Comment by jrobinso** [comment]
The fix for this is released as 2.8.9.   It was actually a separate but
related bug and fix to the problem in the master branch.
