### ISSUE TITLE
NTG start codon coloring

### ISSUE THREAD

**Issue by daniel-spies** [igvteam/igv#834]
I'm investigating alternative ORFs that do have alternative start codons, is there a way to specify the start codons somewhere in a config file to add another translation table entry for individual codon coloring?

thanks for this great tool and your effort!

best
Daniel

**Comment by jrobinso** [comment]
Sorry for the delay, I had to browser through the code.   This is not possible currently, if you are comfortable modifying code and building from source you could probably do this.    If that's a possibility let me know and I'll send you some pointers.

**Comment by daniel-spies** [comment]
Hi jim Thanks for the ultra fast reply. I’m not really proficient in java but know how to code. So yeah if you can supply the scripts and some pointers that’d be awesome Thanks a lot and have a nice Sunday!Daniel Sent from Mail for Windows 10 From: Jim RobinsonSent: Saturday, August 1, 2020 7:20 AMTo: igvteam/igvCc: daniel-spies; AuthorSubject: Re: [igvteam/igv] NTG start codon coloring (#834) Sorry for the delay, I had to browser through the code. This is not possible currently, if you are comfortable modifying code and building from source you could probably do this. If that's a possibility let me know and I'll send you some pointers.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by jrobinso** [comment]
Translation tables and genetic codes are defined in the folder  src/main/resources/org/broad/igv/feature/resources.   After editing or making additions there you can rebuild IGV following instructions in README.md.  

To customize color you will need to edit the function org.broad.igv.renderer.SequenceRenderer.getColorForAminoAcid

**Comment by daniel-spies** [comment]
Hi Jim,

just added the alt start codon and rebuild, worked out like a charm.

Thanks a lot for your fast replies and the dedication!

best
Daniel
