### ISSUE TITLE
Error "Found invalid server genome list record"

### ISSUE THREAD

**Issue by robertaboukhalil** [igvteam/igv#839]
Good afternoon!

We've recently started seeing the following errors in our IGV logs:

```
...
INFO [2020-08-13T18:29:41,284]  [GenomeManager.java:192] [pool-3-thread-1]  Loading genome: /root/igv/genomes/b37.genome
ERROR [2020-08-13T18:29:43,896]  [GenomeListManager.java:404] [pool-3-thread-1]  Found invalid server genome list record: # Hosted genomes list.  Tab delimited file with 3 columns  Name (for menu),  url to .genome or .json file,  and genome ID.
INFO [2020-08-13T18:29:43,897]  [GenomeComboBox.java:90] [AWT-EventQueue-0]  Enter genome combo box
...
```

Looking at [the code](https://github.com/igvteam/igv/blob/v2.8.2/src/main/java/org/broad/igv/ui/commandbar/GenomeListManager.java#L404), it seems this happens because IGV skips over invalid lines in the https://s3.amazonaws.com/igv.org.genomes/genomes.tab file, and it's simply skipping over the first line, which is a comment:

```
# Hosted genomes list.  Tab delimited file with 3 columns  Name (for menu),  url to .genome or .json file,  and genome ID. 
```

Is it possible that this file was changed recently? It seems the code treats lines starting with `(#` as comments ([code](https://github.com/igvteam/igv/blob/v2.8.2/src/main/java/org/broad/igv/ui/commandbar/GenomeListManager.java#L386)), but not lines that start with `#`. 

This isn't a big issue since we're just ignoring those warnings, but thought you might want to know.

Also, in case it helps, the errors started showing up yesterday August 12 ~4pm PST.

**Edit:** looks like it's because this file was changed yesterday: https://github.com/igvteam/igv/commit/b1e6482ac9e305bad1e44cca8c7534d08bf72f65 and so the first line is no longer recognized as a comment

**Comment by jrobinso** [comment]
Recently as in the last couple of  hours?  No released version of IGV should be using the file reference (genomes.tab).  Released versions of IGV use genomes.txt.     What version of IGV are you using?

**Comment by robertaboukhalil** [comment]
Recently as in yesterday afternoon. I'm using version 2.8.2

**Comment by jrobinso** [comment]
Did you customize the URL to the genome server?  2.8.2 should use genomes.txt,  not genomes.tab.  I just started 2.8.2 to verify that.

**Comment by jrobinso** [comment]
Either way the warning is harmless,  but genomes.tab might have some genomes that are not compatible with 2.8.2.

**Comment by robertaboukhalil** [comment]
Yes that's right, we use https://s3.amazonaws.com/igv.org.genomes/genomes.txt but that file also starts with a `#`. In any case, I'll just ignore the error, thanks!

**Comment by jrobinso** [comment]
I restored the previous header to genomes.txt.    Many deprecated genomes were removed (some from 2008).   genomes.tab is used in the master branch and includes "json" genome definitions,  going forward we will transition to json definitions from the ".genome" file.

**Comment by robertaboukhalil** [comment]
Thanks! Good to know. And also thank you for this awesome tool!
