### ISSUE TITLE
drs:// urls not working with igv url input

### ISSUE THREAD

**Issue by sabrinacamp2** [igvteam/igv#840]
Hi,

I am attempting to use DRS URLs (they begin with drs://), which is a system that allows the NCI’s Genomic Data Commons (GDC) to relocate physical data without changing the URLs to the data to load a bam into IGV. Since this is now what the majority of TCGA is stored as, is there a solution to the error I'm seeing? 

`Error loading BAM file: htsjdk.samtools.util.RuntimeIOException: Read error; BinaryCodec in readmode; streamed file (filename not available)`

Best,
Sabrina Camp

**Comment by jrobinso** [comment]
drs is not a protocol igv.js (or IGV) recognizes.   I will look into this, but if you have any pointers to information on the "drs" protocol that would be helpful.

**Comment by jrobinso** [comment]
@sabrinacamp2 I can't find any information on "drs://" protocol, where is this documented?

**Comment by aednichols** [comment]
Hi @jrobinso, DRS is like "DNS for files" wherein a stable identifier refers to a (possibly changing) file location in (possibly several) public clouds.

It was not invented by Broad but it is supported in the [DSP Terra project](https://support.terra.bio/hc/en-us/articles/360039330211-Data-Access-with-the-GA4GH-Data-Repository-Service-DRS-).

The DSP publishes a [lightweight Cloud Function-based resolver](https://github.com/broadinstitute/martha/) that may be of interest if you choose to implement it.

**Comment by jrobinso** [comment]
Thanks @aednichols .   This look a bit out-of-scope for me at the moment.   I would be glad to entertain a pull request proposal.

**Comment by ohofmann** [comment]
It's on the to-do list here as well but positively something a bit further away.

**Comment by aednichols** [comment]
Fair enough. I am a Terra developer with no personal stake in IGV/DRS, just dropping the info in case your customers come knocking.

**Comment by jrobinso** [comment]
If someone wants run a web service to match dr: urls I will support it, but without a service to look up the real URL there is really nothing for a client app to do.
