### ISSUE TITLE
Unable to open Arabidopsis thaliana TAIR10 genome

### ISSUE THREAD

**Issue by Neeraja-Vegesna** [igvteam/igv#848]
Hi,
I am unable to download the TAIR10 genome when I open IGV. Never had the issue before. Started having the issue on 09/11/2020.
Thanks!
Neeraja

**Comment by helgathorv** [comment]
Hi. This has been fixed. Shut down IGV, and then remove the file igv/genomes/tair10.genome. The igv folder can be found in your home directory. When you start IGV again, you should be able to load tair10 from Genomes > Load Genome From Server. 

Let us know if you still have problems.
