### ISSUE TITLE
error about "igvtools count"

### ISSUE THREAD

**Issue by zhengjiantao** [igvteam/igv#851]
I perform command "igvtools count --query=chr7:65444350-65444370 -w 1 --bases xxx.bam test.wig xxx.fa"
but I got this error
![image](https://user-images.githubusercontent.com/41890364/94340909-18d96100-0038-11eb-956c-8dbb9b5470c1.png)
I can get count for the whole genome bp without using the "query" option

**Comment by jrobinso** [comment]
Looks like either you bam index is corrupt, or there is no "chr7" present in the file.    Perhaps it uses "7"?
