### ISSUE TITLE
Launching IGV specifying preferences file

### ISSUE THREAD

**Issue by williakd17** [igvteam/igv#853]
Hello,

I'm currently in an environment where we have multiple users using IGV. We are launching IGV using a batch file and I was wondering if there was a way to specify one common preferences file so all the users are using the same central preferences file and not their own? 

Thank you!

**Comment by jrobinso** [comment]
This is not possible in general, many user actions get recorded as preferences and these will get saved locally.     You can provide a default shared starting set if you start from the command line using the "--preferences <path or url to prefs.properties>"   option.   This will override individual user preferences for the values in the file, but users can still customize other settings.

**Comment by williakd17** [comment]
Perfect. Thank you so much!
