### ISSUE TITLE
Does a position occur on multiple chromosomes?

### ISSUE THREAD

**Issue by zhengjiantao** [igvteam/igv#854]
I looked up a position in the "igvtools count -w 1 --bases x.bam result.wig x.fa" result and found multiple matches
Is this normal?
![image](https://user-images.githubusercontent.com/41890364/96203742-2c238080-0f95-11eb-9f7b-b494544453a9.png)

**Comment by jrobinso** [comment]
Yes, if there are multiple sequences in the output.
