### ISSUE TITLE
Support reading BigWig and other file formats from S3 time-gated presigned urls 

### ISSUE THREAD

**Issue by mdug-gfb** [igvteam/igv#856]
We've set up the Amazon IGV backend and it seems to be working well for most files, BED files or BAMs open without issue, however when we try to open bigwig files, we get an error of "file not found" or similar. This is true on both Windows and macOS, running IGV 2.8.10 

Looking in Fiddler while running trying to open the BED files, I can see traffic going to Amazon over port 443 and responses coming back, and the BED file is loaded in IGV. When trying to open a BW file I can see the request being sent for the file and a 200 response from Amazon but we get the "file not found error" in IGV. 

The igv log shows a java.io.FileNotFoundException. I can post the full log if that is helpful.

**Comment by awilcz** [comment]
We're having the same issue. Local IGV, loading files from S3 bucket. BAM/BAI works fine, bigwig doesn't with "no such file or directory" error

**Comment by jrobinso** [comment]
@awilcz @MarkSDuggan  Could you both elaborate?  All of our publicly served data is loaded from S3 buckets, including many bigwig files.  For example,  this, which you can load using "File > Load from URL"  https://s3.amazonaws.com/igv.org.test/data/ENCODE/ENCFF000ARJ.bigWig 

I haven't had time to test this yet but I assume you are using the backend setup described at the UMCCR site, is that correct?   @brainstorm Are you serving any bigwig files there?

**Comment by brainstorm** [comment]
@jrobinso No, we are not using bigwigs via AWS-IGV @umccr... and I recall the reason behind not covering all file formats with the IGV-AWS support, see the specific discussion under https://github.com/igvteam/igv/pull/620#discussion_r317592218.

Namely:

> The fixes you have will work for alignments and many feature formats, but will not protect all file formats (...) It should probably be note that there could be a problem with formats other than bam and tribble type features. Specifically fasta, bigwig/bigbed, and tdf. Of course all formats will work until the url expires, as will as any non-indexed type format for which the entire file is read at once.

Correct me if I'm wrong but essentially we chose not to implement more than BAM/VCF because (currently) every format requires refreshing the reader instead of having a common "abstract" reader that can be used for all, IIRC.

/cc @reisingerf @ohofmann

**Comment by jrobinso** [comment]
Thank you @brainstorm ,  I recall that now.

So I think for now the answer is IGV does not support all formats.   We should probably document what is supported.    Would that be BAM and VCF?   Anything else?  

This ticket should be renamed as its not a problem with S3 per se, which is probably the most common cloud provider used with IGV,  but rather a problem with this particular method of accessing S3.   @brainstorm do you have a suggestion for what to call this succinctly  ("Bigwig files not opening from ????")?

**Comment by jrobinso** [comment]
To be clear I propose renaming this and leaving it open as a feature request,  "Support all file formats with ????"      With what?  Amazon AWS Federated?

**Comment by brainstorm** [comment]
Yep... a simple title like "Support all file formats with through AWS S3" should be searchable/findable enough for users?

**Comment by jrobinso** [comment]
@brainstorm the problem with that is it implies IGV doesn't work with S3, which again is the most common cloud provider (its the only one we use for example).    It works fine, the problem is using this particular method which I am trying to name to authenticate and fetch signed URLs.

**Comment by brainstorm** [comment]
Ah, gotcha, something like "S3 time-gated *presigned* urls"... "presigned url" being the keywords you might be looking for here?

**Comment by jrobinso** [comment]
OK I can run with that.   BTW to be fare your blog only mentions accessing BAM files.

**Comment by jrobinso** [comment]
To be clear to anyone who finds this the issue is loading BigWig files from AWS S3 buckets using the method described here:  https://umccr.org/blog/igv-amazon-backend-setup/.    Reading data from public S3 buckets can be accomplished via the public S3 links, or from signed URLs with expiration times > the IGV session time.
