### ISSUE TITLE
Negative stranded feature colors not updated

### ISSUE THREAD

**Issue by bredeson** [igvteam/igv#858]
Hi IGV devs,
Thank you for the very helpful software!

I'm currently having an issue where, if I attempt to change the track feature color, only the color of positive-stranded features are updated and negative-stranded features remain (the default) dark blue. I observe this with BED and PSL file-based tracks, but not with GFF3 file-based tracks...

I'm running IGV on macOS Catalina 10.15.7 using the IGV_2.8.10.app with java 11 included.
(FYI, I have observed this in prior app versions as well)

Jessen
![Screen Shot 2020-10-24 at 11 15 14](https://user-images.githubusercontent.com/601458/97086641-332c3d80-15ea-11eb-9978-3e345368f975.png)

**Comment by jrobinso** [comment]
Yes I can reproduce this.  However I don't understand quite how this isn't an issue with GFF tracks, I see it with all file types.  Do your GFF track features explicitly set color?

**Comment by bredeson** [comment]
Hey @jrobinso 
Thank you for your quick reply. My GFF3 does not explicitly specify it's own color, no...

Jessen

**Comment by jrobinso** [comment]
@bredeson If possible could you zip up and attach a gff3 that does not exhibit this problem?  I think I've found the issue but the GFF3 exception is puzzling me.

**Comment by bredeson** [comment]
Hey @jrobinso 
Sure thing. The file is compressed with bgzip:
[cassava-v8.repeatMasked.gff3.gz](https://github.com/igvteam/igv/files/5435272/cassava-v8.repeatMasked.gff3.gz)

**Comment by jrobinso** [comment]
OK thanks,  I see the issue with that file as well (see screenshot).   We will have a fix for this in the next point release, will update when available.

<img width="978" alt="Screen Shot 2020-10-25 at 9 29 01 AM" src="https://user-images.githubusercontent.com/933148/97112992-aeeac080-16a4-11eb-9a97-01a34a49f815.png">

**Comment by bredeson** [comment]
@jrobinso Awesome! Thanks for looking into this!

**Comment by bredeson** [comment]
Hey @jrobinso 
I just downloaded IGV_2.8.11 and the coloring appears to be fixed! Thank you!
