### ISSUE TITLE
Add option to copy clipped read sequence to clipboard

### ISSUE THREAD

**Issue by agnibhat** [igvteam/igv#860]
When I try to BLAT the read sequence from IGV, I get this error message. I can find the genome listed in the IGV 'More' section. Any ideas on how I can solve this error? Thanks!

**Comment by jrobinso** [comment]
Only UCSC hosted genomes are blattable,  this one is not a UCSC genome.

**Comment by agnibhat** [comment]
Ah okay. Thanks. Is there any way I can BLAT the read sequences? Especially the clipped read sequence (right or left). Or at least copy the clipped read sequence and not the whole sequence?

**Comment by jrobinso** [comment]
@agnibhat Not with IGV.  You can look at the BLAT documentation at UCSC for information on installing blat locally. 

It looks like there is not an option to copy the clipped sequence.   I will rename this issue to request it and leave it open.

**Comment by agnibhat** [comment]
Great! Thank you so much. It would be really helpful if there was an option to copy clipped read sequences to the clipboard.

**Comment by mmokrejs** [comment]
+1

**Comment by jrobinso** [comment]
This is implemented in the new release 2.9.0.
