### ISSUE TITLE
IGV hg38 TTN gene no NM transcript id, only XM id

### ISSUE THREAD

**Issue by GiantVin** [igvteam/igv#863]
Hi IGV team,
We are using IGV hg38 for viewing NGS data, and found that for all exons of TTN gene it pops out only XM transcripts as shown in the screenshot (below 2). We used to use the NM to report like in hg19 screenshot (below 1). Could you fix it ASAP. Or anyone could teach me how to fix it by myself?
Thanks a lot.

**Comment by jrobinso** [comment]
I'm sorry I don't see any screenshots.  IGV by default displays trasncripts from the "ncbiRefGene.txt.gz" file downloaded from UCSC.    I see many NM transcripts,  for example NM_133437.4     Some screenshots would help.

**Comment by GiantVin** [comment]
Hi jrobinso,

Thank you for your message. I uploaded 2 screenshots but did not showed up.
![hg19-TTN-IGV](https://user-images.githubusercontent.com/50960680/98390246-b605bd00-201a-11eb-9fb4-73b14656d20e.png)
![TTN transcript ID issue-hg38-IGV](https://user-images.githubusercontent.com/50960680/98390248-b69e5380-201a-11eb-9122-dcf64d6ed3ac.png)

**Comment by jrobinso** [comment]
We recently switched from the "refSeq" annotation file to "ncbiRefSeq".    The latter has many more transcripts, and the limit on popup text was set to 10.  I increased the limit to 100 which should show them all, both NM and XM.   This will be in the next release,  or you can use the "nightly snapshot" build.

In the meantime, you can get the old track by loading the following from the "File" menu, either directly by URL or by downloading first

https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/refGene.txt.gz

**Comment by GiantVin** [comment]
Hi Jim,

Thank you very much for your help. Also appreciate if you could notify me when the new release come out.

Best regards,

Wenxin
