### ISSUE TITLE
cannot zoom in when bam file is uploaded

### ISSUE THREAD

**Issue by Ania797** [igvteam/igv#866]
I am having problems uploading the bam files into IGV. It seems ok until I try to zoom in. then error message appears (attached).  If I click OK or close on the error message, the IGV just freezes. The only way to exit is to close it down completely.
Bed files upload with no problems. I have tried different bam files from different NGS panels and always get the same error message. They work ok for my colleagues on different pc. 

[error while loading bam file.docx](https://github.com/igvteam/igv/files/5529607/error.while.loading.bam.file.docx)

**Comment by Ania797** [comment]
I am using IGV_2.4.8. on 64-bit Windows7.
please find attached log file 
[igv.log.txt](https://github.com/igvteam/igv/files/5529969/igv.log.txt)

**Comment by jrobinso** [comment]
Could you try updating to the latest IGV version?

**Comment by Ania797** [comment]
thank you, I will try it once our IT authorize it

**Comment by Ania797** [comment]
I found out the IGV-Web does what I need. No problem uploading bam files and I don't have to wait for our IT to authorize the update. Thank you IGV team. the Web option is a saver!!

**Comment by helgathorv** [comment]
Glad that IGV-Web helped.  We'll close this issue now, but feel free to re-open if you have similar issues when you are able to run the latest version of the desktop IGV.
