### ISSUE TITLE
Socket connection from browser

### ISSUE THREAD

**Issue by luisico** [igvteam/igv#87]
Hi,

I'm developing an web application that leverages igv to see tracks locally available to our researchers. When trying to use IGV's sockets interface from the browser (javascript) I run into a few issues.
First, using WebSocket on chrome or firefox, both in linux, the handshake is not succesful:

```
WebSocket connection to 'ws://localhost:60151/' failed: Error during WebSocket handshake: Status line does not end with CRLF
```

This is the code in use:

``` javascript
 if ("WebSocket" in window) {
    var ws = new WebSocket("ws://localhost:60151/");
    ws.onopen = function() {
      ws.send("echo");
      console.log("send echo");
    }

    ws.onmessage = function (e) {
      console.log("recieved: " + e.data);
    }

    ws.onclose = function() {
      console.log("close");
    };

  } else {
    console.log('no websocket support');
  }
```

If instead I use [socket.io](http://socket.io) I then run into cross-domain problems:

```
XMLHttpRequest cannot load http://localhost:60151/socket.io/?EIO=2&transport=polling&t=1403105328419-0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

This is the code for reference:

``` javascript
    var socket = io.connect("http://localhost:60151");

    socket.on('connect', function() {
      console.log('connected');
    })

    socket.on('error', function() {
      console.log('error connecting');
    })

    socket.emit('echo');
```

My guess is that socket.io is smarter than Websocket and is dealing with the CRLF itself. My questions are:
1. Is there a bug in IGV's sockets interface that is not producing the CRLF
2. Is it possible to enable CORS in IGV's server, hopefully a rather liberal policy since it runs locally and should be trusted by the user.

Thanks,
Luis

I've seen the webstart.js code on github, but the sockets interface is so much more capable.

**Comment by olingerc** [comment]
Sorry to write on a closed issue, but I simply can't get the same situtation to work, even using the latest version of IGV. I get the following error:
```
A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:5000' is therefore not allowed access.
```
Did anybody find a solution for direct javascript to IGV communication?

**Comment by olingerc** [comment]
I'm sorry for the noise. A simple http get request like this
```
http://localhost:60151/execute?command=echo
```
works like a charm! Read this in src/org/broad/igv/batch/CommandListener.java.

**Comment by jrobinso** [comment]
Local access is probably not going to work with credentials in the 
header.   IGV sets the control header for CORS requests (cross origin) 
to "*", and that is not allowed with credentials.

In retrospect we should be echoing the  host in the CORS header, rather 
than using the wildcard.  I will re-open the issue to make that change.

Jim

**Comment by jrobinso** [comment]
Re-open to echo the host in the CORS header, rather than use a wildcard.
