### ISSUE TITLE
Current master fails with newly downloaded genome files

### ISSUE THREAD

**Issue by bbreton** [igvteam/igv#870]
I'm not sure if you want reports on any issues I find with the current master or not.  If you don't want them here let me know.

The new one downloads a json file rather than a .genome file to ~/igv/genomes/: 
s3://igv.org.genomes/json/hg19.json

vs.

s3://igv.org.genomes/hg19/hg19.genome

When it tries to use them the range request gets stuck in a neverending loop until it goes out of range giving an error.

I worked around this by downloading the hg19.genome file and putting it in genomes folder which makes it work properly.

To reproduce:
- start with a clean ~/igv directory and open IGV. 
- Select a genome from Load Genomes From Server.  
- Load a bamfile e.g. http://1000genomes.s3.amazonaws.com/phase3/data/HG00268/high_coverage_alignment/HG00268.wgs.ILLUMINA.bwa.FIN.high_cov_pcr_free.20140203.bam. 
- Goto a location e.g. hg19 chr7:117,230,640-117,234,189. 
- Watch if you have trace enabled as it just goes on and on with the message until it errors

> TRACE [2020-11-19T21:48:06,843]  [IGVSeekableHTTPStream.java:122] [AWT-EventQueue-0]  Trying to read range 1582239442 to 1582239696

**Comment by jrobinso** [comment]
Yes please report issues.  The json is intentional,  .genome files are going away (with legacy support of course).

**Comment by jrobinso** [comment]
That's strange, I can reproduce it as well.   There might be some hint here as to what is causing the batch hanging problem as the same region of code is involved.   For now, until i can look more deeply, I switched to the ".genome" list vs ".json.

**Comment by bbreton** [comment]
> Yes please report issues. The json is intentional, .genome files are going away (with legacy support of course).

Is there a public roadmap of the IGV plans available?

**Comment by jrobinso** [comment]
No, only for the next release (2.9) which you can access through milestones.
