### ISSUE TITLE
hg38 reference problem of CBSL and CBS

### ISSUE THREAD

**Issue by THZ34** [igvteam/igv#873]
In the data of refGene.txt which compress in the hg38.genome, there some problems with CBSL and CBS, their transcript are embedded in each other

bin | name | chrom | strand | txStart | txEnd | cdsStart | cdsEnd | name2
-- | -- | -- | -- | -- | -- | -- | -- | --
634 | NM_000071 | chr21 | - | 6444868 | 6467513 | 6445557 | 6463871 | CBS
634 | NM_001321072 | chr21 | - | 6444868 | 6460082 | 6445557 | 6459456 | CBS
634 | NM_001178009 | chr21 | - | 6444868 | 6468055 | 6445557 | 6463871 | CBS
634 | NM_001320298 | chr21 | - | 6444868 | 6468539 | 6445557 | 6463871 | CBS
634 | NM_001178008 | chr21 | - | 6444868 | 6468070 | 6445557 | 6463871 | CBS
634 | NM_001354012 | chr21 | - | 6444868 | 6467197 | 6445557 | 6463871 | CBSL
634 | NM_001354008 | chr21 | - | 6444868 | 6468109 | 6445557 | 6463871 | CBSL
634 | NM_001354007 | chr21 | - | 6444868 | 6468621 | 6445557 | 6463871 | CBSL
634 | NM_001321073 | chr21 | - | 6444868 | 6468109 | 6445557 | 6463871 | CBSL
634 | NR_148682 | chr21 | - | 6444868 | 6467623 | 6467623 | 6467623 | CBSL
634 | NM_001354010 | chr21 | - | 6444868 | 6467623 | 6445557 | 6463871 | CBSL
634 | NM_001354006 | chr21 | - | 6444868 | 6468621 | 6445557 | 6463871 | CBSL
634 | NM_001354009 | chr21 | - | 6444868 | 6467623 | 6445557 | 6463871 | CBSL
634 | NM_001354014 | chr21 | - | 6444868 | 6467623 | 6445557 | 6463871 | CBSL
634 | NM_001354015 | chr21 | - | 6444868 | 6467623 | 6445557 | 6463871 | CBSL
913 | NM_001321072 | chr21 | - | 43053190 | 43068404 | 43053879 | 43067778 | CBS
913 | NM_001178008 | chr21 | - | 43053190 | 43076392 | 43053879 | 43072193 | CBS
913 | NM_000071 | chr21 | - | 43053190 | 43075835 | 43053879 | 43072193 | CBS
913 | NM_001320298 | chr21 | - | 43053190 | 43076861 | 43053879 | 43072193 | CBS
913 | NM_001178009 | chr21 | - | 43053190 | 43076377 | 43053879 | 43072193 | CBS
913 | NM_001354012 | chr21 | - | 43053190 | 43075519 | 43053879 | 43072193 | CBSL
913 | NM_001354008 | chr21 | - | 43053190 | 43076431 | 43053879 | 43072193 | CBSL
913 | NM_001354006 | chr21 | - | 43053190 | 43076943 | 43053879 | 43072193 | CBSL
913 | NM_001354009 | chr21 | - | 43053190 | 43075945 | 43053879 | 43072193 | CBSL
913 | NM_001354007 | chr21 | - | 43053190 | 43076943 | 43053879 | 43072193 | CBSL
913 | NM_001354010 | chr21 | - | 43053190 | 43075945 | 43053879 | 43072193 | CBSL
913 | NR_148682 | chr21 | - | 43053190 | 43075945 | 43075945 | 43075945 | CBSL
913 | NM_001354015 | chr21 | - | 43053190 | 43075945 | 43053879 | 43072193 | CBSL
913 | NM_001354014 | chr21 | - | 43053190 | 43075945 | 43053879 | 43072193 | CBSL
913 | NM_001321073 | chr21 | - | 43053190 | 43076431 | 43053879 | 43072193 | CBSL

**Comment by jrobinso** [comment]
I'm not sure what you mean by "compress within each other", do you mean overlap?  That is normal.  You can right-click and "expand" the track to see them all, one per row.

In any event, we don't create the annotation, we simply display it.   Our annotation source is the UCSC genome browser.
