### ISSUE TITLE
"View mate region in split screen" not working with IGV on localized OS

### ISSUE THREAD

**Issue by elmaffo** [igvteam/igv#874]
Hi, 

looks like when running from a localized (i.e. not set to en/US) operating system, igv option "View mate region in split screen" does not work.

Please see the following thread on the igv-help mailing list.
https://groups.google.com/g/igv-help/c/vtgf_JTe9V0/m/KaGD6DxoCQAJ

Thank you
Andrea

**Comment by helgathorv** [comment]
This should be fixed now in 2.8.13 which we just released. Let us know if you still have problems with viewing mates in split screen. Thanks for your help on tracking down the issue!
