### ISSUE TITLE
Select By Name Doesn't Scroll to Read

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv#878]
I have a table of gene fusions and one of the columns has read identifiers of split reads and discordant pairs supporting fusions. If the gene is highly expressed and there are about 500 reads covering exons, it would be convenient if the Select by name ... option would scroll down to where it found the read to avoid manual searching by the user.

**Comment by ollenordesjo** [comment]
I was thinking about this previously as well, see response from @jrobinso here: https://github.com/igvteam/igv/issues/842

**Comment by jrobinso** [comment]
Just reviewing open issues, this really isn't possible with IGV's current design if viewing in split screen.  There is no guarantee the reads are in the same rows in separate panels.
