### ISSUE TITLE
Add Goto primary alignment option with some Get back function

### ISSUE THREAD

**Issue by mmokrejs** [igvteam/igv#879]
Hi Jim,
  I have a BAM files with primary and secondary alignments. Not only I cannot distinguish them by color from each other, nor adjust groupping of reads (primary matches top, then followed by secondarily aligned reads to the same locus). A simple but helpful feature would be to hop via the readname to the primary match site, ideally primary few or rev reads, specifically.

  I understand having a chance to hop backwards from primary match to all the secodary matches in a stack is not so simple but don't get distracted by this additional reverse feature.

  Mainly, I want to check how the primary match looks like and compare to the secondary match. Notably, while having softclipped nucleotides to be shown (a bit awkward to change via the long path in Menu -> View -> Preferences). I use igv-2.8.9.

  It happened to me I had to disable softclipping altogether in hisat2 aligner, I was loosing some 10nt deletions due to too short alignment on either side of the deletion site. Softclipping made it even worse. Hisat2 is aimed at about 125 or 150 reads but if you get 75 nt reads, you have to push down the thresholds and disable softlipping too. I ended up with `hisat2-2.2.1/hisat2-align-s --bowtie2-dp 2 --score-min L,0,-1 --no-softclip `, btw.

Thank you for a great tool

**Comment by jrobinso** [comment]
I don't see any possible way to implement the "jump to" unless the location of the primary read is encoded in a tag.   Do you know if that's the case?    I could certainly add this as a group or coloring option however (group/color by primary flag).

One reason there hasn't been any special use of "primary" in the past is according to the spec the primary label is arbitrary,  although its possible some tools give it special significance I don't know.

**Comment by jrobinso** [comment]
@mmokrejs just following up before I close this.   I assume you use the term "secondary" you are referring to alignments marked secondary with the sam flag (0x100), and not supplementary alignments (0x800).   If so there is not information in the sam format on where the other alignments are, including the primary alignment, so there is no way to implement this.
