### ISSUE TITLE
PROXY.TYPE property cannot be set

### ISSUE THREAD

**Issue by gabeng** [igvteam/igv#889]
Selecting any proxy type other than the default HTTP does not work in 2.8.13. 
* Open the Preferences window - proxy,
* Activate and enter a proxy and select an option different from HTTP.
* Klick save.
* Reopen the Preferences window and review the settings: the type drop-down has been reset to HTTP.

It appears that the `PROXY.TYPE` setting is also not written to the `prefs.properties` file. 

Workaround: Close IGV and add the following line to the `prefs.properties` file (for a `SOCKS` proxy):
```
PROXY.TYPE=SOCKS
```

**Comment by jrobinso** [comment]
Yes, that is a known issue.  It is fixed and will be released a 2.9 this
week.

**Comment by gabeng** [comment]
Ah, I did not see that. Thanks for the quick response. Looking forward to 2.9!

**Comment by jrobinso** [comment]
I found it independently working on another preference,  none of the
"select list" type preferences were working.   Look for 2.9 towards the end
of the week,  I'll update this issue when its released.

**Comment by jrobinso** [comment]
Fix is released.
