### ISSUE TITLE
Support tab-delimited bed files with spaces in name field.

### ISSUE THREAD

**Issue by isthisthat** [igvteam/igv#890]
I'm loading a bed file with the following columns, in IGV 2.8.13:
    chr1{tab}1051161{tab}1051177{tab}strong GGGCGGGTGGGGCGGG{tab}0.81{tab}+
In the UI I'm not getting the usual arrows pointing in the direction of the "strand" column (6th bed column).
The name displayed (4th bed column) is just "strong" instead of "strong GGGCGGGTGGGGCGGG".
I suspect that the bed file has been loaded with whitespace as the delimiter instead of just <tab>, which is the bed spec.

**Comment by jrobinso** [comment]
@isthisthat Where is the bed spec you are referring to?   I am not aware of anywhere that has a proper specification for "bed" format, but we follow UCSC convention since they invented it.   The convention there is whitespace delimited, at least last time I checked.

**Comment by jrobinso** [comment]
I've always found this a bit ambiguous  https://genome.ucsc.edu/FAQ/FAQformat.html#format1

```BED fields in custom tracks can be whitespace-delimited or tab-delimited.```

But there are definitely whitespace-delimited bed files.

**Comment by isthisthat** [comment]
I suppose you're right @jrobinso. I've been using tab for so long that I didn't realise there's multiple conventions. Still, I suppose "whitespace-delimited or tab-delimited" technically means one of the two, as in, either space or tab-delimited. Otherwise just "whitespace-delimited" would suffice. In fact bedtools interprets the line I pasted above as I would expect (i.e. it's aware of the strand being in the 6th column). Mixing tabs and spaces is non-standard and bad practice I would think.

**Comment by jrobinso** [comment]
Yes,  I could try to detect this at runtime.  I will rename the issue accordingly.

**Comment by jrobinso** [comment]
BTW I think, but am not sure, that quoted name fields can be used to get around this problem.

**Comment by jrobinso** [comment]
No, I'm wrong about that, quotes don't help.   There's no workaround in the current IGV, but I will fix this soon to detect the presence of tabs (or not).

**Comment by jrobinso** [comment]
@isthisthat This is actually harder than it looks.   If the spec said "tab or space" delimited it would be easy, but it actually says "tab or whitespace delimited".    Multiple consecutive tabs is just whitespace.   That is why UCSC formats generally require a "." in empty columns,  to separate whitespace.    I'm a bit unsure now on what the correct fix would be, if a fix is even possible, but just looking for tabs as my previous commit does is not sufficient.    This is not just theoretical, there is a unit test that has multiple tabs between columns, it would not be there if this had not occurred in real practice.

**Comment by isthisthat** [comment]
I see..
Are the multiple tabs in that test case between the first 3 columns? Is it always multiple tabs or just between some columns?
It is often the case that people tag on random columns to beds, after column 3, without respecting the name, score, strand convention. Wonder if it's one of those cases.
I think bottom line is that the spec is unclear, your previous implementation is fair enough, and we would have to read between the lines to make it stricter (I suppose the way bedtools did). I guess the two options are leaving it as is, or enforcing tabs xor spaces. I'm happy with either. And thank you for your time @jrobinso! I know this is nowhere near the top priority!!

**Comment by jrobinso** [comment]
I think I've found a compromise (already pushed).   The presence of tabs will indicate a modified form of tab-delimited,  that is any number of tabs between columns will delimit them.   So a non-tab character (such as a ".") is required.   This is consistent with UCSC as far as I can tell,  a "." is required for the name file for example if skipping it to get to further fields.   Ditto the strand or color field.    This will cover the old (2011) unit test case, added for reasons forgotten.   The UCSC text cannot be implemented as written,  there is really no proper specification for any of their formats with the exception of bigwig/bigbed, but I think what we have now should cover 99% or more of extant bed files.

**Comment by isthisthat** [comment]
Ok so what you're basically saying is that a bed file can either be tab or space delimited, but allowing for multiple delimiters between fields. Is that correct?

**Comment by jrobinso** [comment]
Yes, that's basically it, but it must be all tabs or all spaces,  the only
thing not allowed is a mix of tabs and spaces as a delimiter (which is of
course whitespace and will work at UCSC).

**Comment by isthisthat** [comment]
I can see that 2.9.0 displays the bed as I would expect. Thanks a lot!!
