### ISSUE TITLE
Error loading Mouse (mm10) reference genome

### ISSUE THREAD

**Issue by ckuenne** [igvteam/igv#894]
Today I got an error loading the default mouse (mm10) genome version. 

"ERROR: Unrecognized annotation file format: ncbiRefSeq.txt Annotations for genome: mm10 will not be loaded."

According to the igv.log it tried to pull from here: INFO [2021-01-28T10:27:31,550] [GenomeManager.java:192]  Loading genome: https://s3.amazonaws.com/igv.org.genomes/mm10/mm10.genome

Other genomes seem to work. I'm using IGV 2.8.10.

Caused by this? https://groups.google.com/g/igv-help/c/UCrhFtYCbTY

**Comment by jrobinso** [comment]
Should be fixed now

**Comment by ckuenne** [comment]
Works. thx.
