### ISSUE TITLE
Problem using custom Blat server for custom genome

### ISSUE THREAD

**Issue by Patg13** [igvteam/igv#899]
Hi

I'm trying to use the Blat option of IGV on my custom genome, so I setup a webBlat according to the Blat documentation and that worked (I see the webBlat interface and I can enter some queries)

My genome name is TBE and I used that name everywhere I could (the 2bit file name, the database name in webBlat configuration file etc.)

I've create a .genome file with the same fasta and named it TBE

I changed the Blat URL in IGV, but I'm still receiving this error :  Cannot determine species name for genome : TBE

What would be the problem ?

**Comment by jrobinso** [comment]
You are possibly the first person in the history of the planet that has actually tried this (configuring a custom blat server for IGV for use with a non-UCSC genome).  The instructions are really for someone running a mirror of the UCSC genome database.   I assume you set the blat URL in the advanced preferences, that is the first step.  

I'm sure we can make this work but you will need to work with me.   An IGV call to the UCSC blat server has the following form, where organism is "species name", and db is the genome ID (e.g. hg19).    What does the corresponding call to your blat server look like, and in particular is an "org" parameter used?

```

http://blatServerURL?org=<organism>&db=<db>&type=dna&sort=query,score&output=psl
```

**Comment by Patg13** [comment]
There is nothing after the server's URL, it's just XX.XX.XX.XX:1234/cgi-bin/webBlat
Which gives me this page:
![image](https://user-images.githubusercontent.com/10926860/106759430-c1a85600-6600-11eb-9160-1a4a70a0de26.png)

And if I enter a DNA sequence, and select the ps1 Output, I got results, but the URL is still the same

**Comment by jrobinso** [comment]
Could you try this and see if it works as expected?

```
http://XX.XX.XX.XX:1234/cgi-bin/webBlat?type=dna&sort=query,score&output=psl&userSeq=<you sequence here>
```

**Comment by Patg13** [comment]
No effect, I'm still on the WebBlat page, no results are showing.

If I input the sequence manually, I got results.

**Comment by Patg13** [comment]
I just checked the webBlat source code, it looks like it does not use the same name for the variables in the URL
if I use this syntax, I got results :

http://XX.XX.XX.XX:1234/cgi-bin/webBlat?wb_qtype=dna&wb_sort=query,score&wb_output=psl&wb_seq=TGGCTTGGACGACCCTGGAGGAGGGAATTTTTCCTCAATTGT

**Comment by jrobinso** [comment]
Ahh, ok,  so what's needed is a template for the url, with a variable that is replaced with the actual sequence.   The other thing needed is a way to associate a particular blat server with a genome.   I will work on this, and also add some clarification documentation.   In retrospect the URL you set in IGV now is not to a webBlat service, but to a UCSC database mirror.

I will update this when there is something to test.

**Comment by Patg13** [comment]
Great, thank you !

**Comment by jrobinso** [comment]
@Patg13 I'm a little concerned about what's returned,  could you save the html from a query,  zip and attach it here (along with the URL for the query).   IGV works by screen scraping the returned html to a UCSC blat query.  That's because UCSC doesn't run a proper webservice, of didn't when this was implemented.   I would like to verify that your blat server is returning the same html, if not there will be issues to address there as well.

**Comment by Patg13** [comment]
Of course, there you go.
[Web BLAT Results.zip](https://github.com/igvteam/igv/files/5920063/Web.BLAT.Results.zip)

Is that what you needed ?

**Comment by jrobinso** [comment]
Yes, exactly,  its similar to a UCSC output.   OK I have what I need,  I don't know how long this will take but if there are no updates in 2 weeks ping this issue again.

**Comment by jrobinso** [comment]
@Patg13 Sorry, one more question.  Is this the name (exactly) of a sequence in your reference genome fasta?  

```
TBE.2bit:chr_10
```

**Comment by Patg13** [comment]
Yes, that is the actual name

**Comment by jrobinso** [comment]
@Patg13 Hi, sorry for the delay,  but I'm going to try to wrap this up in the next few days.    Looking at my source, we query the UCSC browser as a post with the sequence sent in the body with parameter name "userSeq".   In your example the sequence is sent as a GET query parameter with name "wb_seq".    I can't find any documentation at UCSC,  I have no idea how I determined to send the sequence as a post.    In any event if you can look at what you have there and determine if a post works with the custom server that would be helpful.   I don't have time to setup a test blat server, that would delay this siginificantly.

**Comment by jrobinso** [comment]
I just pushed a change that should support your webBlat instance, using a GET query parameter to pass the sequence as shown in your example.  I have no way to test it,  it should be available in the "snapshot" build in a short time.  To use it you need to set the "blat URL" string in the preferences panel to include the genome ID for your custom ".genome" file before the blat URL, with a space separating them.   This is likely going to change but that's how it is currently setup.   It will then use your custom webBlat for that genome, and the default for everything else.   Let me know if you get a chance to try it.

Also, if you confirm that the custom webBlat will accept the sequence via a post I will make a change to use that method.  A post should be able to accomodate a longer sequence than a GET parameter.

**Comment by Patg13** [comment]
That's great, I'll test it and I'll get back to you
Thanks !

**Comment by Patg13** [comment]
I still got the Cannot determine species name for genome : TBE
I put TBE in front of the BLAT url and it's seperated by a space.

I compiled the 2.9.1 version using jdk11

**Comment by Patg13** [comment]
Wait... It could be because I build from source, I just found the snapshot build on IGV website... my bad

I'll try the snapshot and I'll get back to you

**Comment by Patg13** [comment]
I just tried it, same error.

**Comment by jrobinso** [comment]
Could you post your user preferences here (in prefs.properties), or at least the blat URL setting you are using?

**Comment by jrobinso** [comment]
Also, is it possible to share you .genome file?   The error would indicate that "TBE" is not matching you genome ID.   

I'm not sure I'm going to keep this scheme in any event, but I need some way to distinguish UCSC blat servers from this new thing (lets call it web blat),  and be backward compatible for anyone who are using UCSC mirrors.

**Comment by jrobinso** [comment]
@Patg13 Never mind the (removed) requests above.  I've gone a simpler route, should be more robust.   I added an explicit "blat server type" setting in advanced preferences,  with 2 choices, UCSC mirror or WEB_BLAT.   You should select WEB_BLAT and remove the leading genome ID and space from your blat url (i.e. use just the URL).   I also added a log statement to log the actual URL with parameters called,  this will be removed when we have this working.   This change will be in the snapshot development build, or you can build from source.

**Comment by Patg13** [comment]
@jrobinso I just tried the new version and I still got the same error : Cannot determine species name for genome : TBE
Where is the log statement ? the log.txt does not contain anything about the URL

**Comment by jrobinso** [comment]
@Patg13  Did you select "WEB_BLAT" as you. Blat Server Type in the "Advanced" preferences?  The fact that you don't see the url in the log indicates you are not using the latest code, what do you mean by "new version"?   Did you pull and build from master?   If you do not see the "Blat Server Type" option in Advanced preferences you are not running the latest.  

<img width="581" alt="Screen Shot 2021-02-12 at 10 20 45 AM" src="https://user-images.githubusercontent.com/933148/107806709-08dac900-6d1c-11eb-98ee-5b10b2fc1b1a.png">

**Comment by Patg13** [comment]
I see the Blat server type option and I've selected the Web_blat option
Here the log.txt content:

INFO [2021-02-12T10:04:56,458] [Main.java:205]  Startup  IGV Version snapshot 02/12/2021 01:08 AM
INFO [2021-02-12T10:04:56,468] [Main.java:206]  Java 11.0.10 (build 11.0.10+9) 2021-01-19
INFO [2021-02-12T10:04:56,468] [Main.java:209]  Java Vendor: AdoptOpenJDK https://adoptopenjdk.net/
INFO [2021-02-12T10:04:56,469] [Main.java:211]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK   
INFO [2021-02-12T10:04:56,469] [Main.java:214]  Default User Directory: C:\Users\pagagne\Documents
INFO [2021-02-12T10:04:56,469] [Main.java:215]  OS: Windows 10 10.0 amd64
INFO [2021-02-12T10:04:57,222] [GenomeManager.java:183]  Loading genome: C:\Users\pagagne\Documents\Annotation_TBE\IGV_chr_renamed\TBE.genome
INFO [2021-02-12T10:05:02,632] [GenomeManager.java:183]  Loading genome: C:\Users\pagagne\Documents\Annotation_TBE\IGV_chr_renamed\TBE.genome
INFO [2021-02-12T10:05:54,178] [MessageUtils.java:76]  Cannot determine species name for genome: TBE

**Comment by maximilianh** [comment]
Hi, I'm sorry to jump in, but I just came across this while searching for
webBlat (which I thought was only our internal name, wow...), I work for
the UCSC genome browser.
It looks like you're parsing our hgBlat HTML is this correct? This will
break at some point. For example, I just modified that HTML.
We provide servers that speak the binary blat TCP protocol, is that not
sufficient for your use case?

If not: it sounds like hgBlat should have a JSON output option.

[ Also: you may be interested in a feature to be released in a few weeks or
months, the BLAT servers should soon cover all GCF_xxxx RefSeq assemblies. ]

**Comment by jrobinso** [comment]
@Patg13 That's baffling,  could you verify the setting in your prefs.properties file?  I was trying to avoid it but maybe I should setup a blat server to test with.    

@maximilianh So glad you jumped in.  Yes I am screen scraping the html output,  this feature is quite old, more than 10 years, and that's the only option I could find at the time.   I would welcome something more roust.   I've searched for a webservice to use instead but have not found one,  is the binary blat protocol and servers documented somewhere?  Apologies if I've missed it.    @Patg13 is running a custom blat server,  would that server also speak the TCP protocol?

**Comment by jrobinso** [comment]
@maximilianh BTW, re the term webBlat I got it from here https://genome.ucsc.edu/goldenPath/help/blatSpec.html

**Comment by maximilianh** [comment]
Hi Jim,

I just added two options for you, which one do you prefer? I can keep both.

https://hgwdev-max.gi.ucsc.edu/cgi-bin/hgBlat?userSeq=GTCCTCGGAACCAGGACCTCGGCGTGGCCTAGCG&type=DNA&output=psl&db=hg19&output=pslRaw

and

https://hgwdev-max.gi.ucsc.edu/cgi-bin/hgBlat?userSeq=GTCCTCGGAACCAGGACCTCGGCGTGGCCTAGCG&type=DNA&output=psl&db=hg19&output=json

**Comment by maximilianh** [comment]
gfServer speaks a native TCP binary protocol. I just realized that it's not
documented anywhere... it's probably better to not use it then... the
hgBlat options may be a lot easier to use?

**Comment by Patg13** [comment]
@jrobinso Just to be sure, I deleted the entire igv folder (where the log and the prefs.properties were) and I relaunched the latest snapshot
I entered my custom Blat URL and selected the Web_Blat server mode.
I also loaded my TBE genome.
If I click on the Blat tool and I enter a sequence, I still obtain the Cannot determine species name for genome : TBE

And the logs shows nothing about it
Here's the content of my prefs.properties:

BLAT_URL=http://XX.XX.XX.XX:8300/cgi-bin/webBlat
SHOW_SEQUENCE_TRANSLATION=false
IGV.Bounds=-1623,79,1150,800
BLAT_SERVER_TYPE=WEB_BLAT
PORT_ENABLED=false
DEFAULT_GENOME_KEY=TBE

**Comment by jrobinso** [comment]
Hi @maximilianh, that is awesome!   The json option would be great.   

 https://hgwdev-max.gi.ucsc.edu/cgi-bin/hgBlat?userSeq=GTCCTCGGAACCAGGACCTCGGCGTGGCCTAGCG&type=DNA&output=psl&db=hg19&output=json

**Comment by jrobinso** [comment]
@Patg13 I can add more print statements to give us more information.     Are you launching the snapshot from the command line?  If you select "Help > About IGV" what do you see?

**Comment by Patg13** [comment]
@jrobinso Integrative Genomics Viewer
Version Snapshot 02/12/2021 01:08 AM

I am launching IGV using the igv.bat script

**Comment by maximilianh** [comment]
Hi @jrobinso, I've committed the json output, it should be on the public
site genome.ucsc.edu in two weeks.

In the meantime, my HTML changes to the BLAT output have been on the public
site since last week. The good news is that apparently they did not break
your html parsing.

If you're interested in testing the future mega-BLAT feature for hundreds
of genomes, let me know. You can specify a GCF_xxx and GCA_xxx ID (I think)
and it will be a bit slower on the first request, but otherwise identical.

**Comment by maximilianh** [comment]
Hi @jrobinso, webblat was the precursor of hgBlat, it's not used anymore on
our servers. It's possible that mirror sites or commercial customers of
BLAT still use webblat somewhere. The documentation still mentions it for
those legacy applications.

**Comment by jrobinso** [comment]
@Patg13 Apologies I made a stupid mistake,  checking species before server type.  The snapshot should work for you now, or at least get past the species check.    I haven't setup a test server but I can parse the output you provided.

@maximilianh Thanks again for the blat changes,  this is a huge help.    If you ever need a LOS for grants please ask.  

To both of you, I'm a bit confused about terminology and what we are actually using.   For documentation and the user interface I'd like to get it right.   @Patg13 Can you point us to the instructions you used to install your sever.   I have been calling it "webBlat",  but I'm not sure why I think I know that.   Perhaps its hgBlat, or perhaps its something else.

**Comment by Patg13** [comment]
@jrobinso Thanks, I'll test the new snapshot soon
Here's the link to the documentation I used : https://genome.ucsc.edu/goldenPath/help/blatSpec.html#webBlatUsage
Here's the link to the source code : https://genome-test.gi.ucsc.edu/~kent/src/
I used the blatSrc36 version (the link to this source code is on this page : http://hgdownload.soe.ucsc.edu/downloads.html#source_downloads under Utilities -> BLAT

**Comment by Patg13** [comment]
@jrobinso Ok, I got results now, so IGV successfully communicated with my local server !
New problem, the chr column in the results contain the 2bit file name, which is not my genome name:
![image](https://user-images.githubusercontent.com/10926860/108263907-d58da500-7134-11eb-82e0-13056404e886.png)
So when I click on an alignment, I got a Cannot find feature or Locus: 
![image](https://user-images.githubusercontent.com/10926860/108263660-8d6e8280-7134-11eb-82fe-39b285977cb9.png)

I tried to rename my genome to tbe.2bit but it doesn't work. If I remove the tbe.2bit: from the genome navigation panel, it works.
Also, the Blat result doesn't take uppercase into account (highlighted in the first image) so it's not recognized correctly by the navigation panel

We are closer to the goal !!!

**Comment by jrobinso** [comment]
I'm not sure I understand,  you are using a different fasta for your IGV
genome than you are using for the blat server?  Could you paste first line
(or any line starting with ">") from the fasta file you built your blat
database from?

I'm trying to understand if the blat server is adding "tbe.bit:"  to the
returned results or if that is the sequence name in the fasta file.

**Comment by Patg13** [comment]
@jrobinso No, it's the exact same fasta file, but the webBlat server documentation say that I must convert the Genome into a 2bit file (which is designed for fast random access and efficient storage according to the documentation). Then I launch two gfserver with the 2bit file (one for sequence, the other for translation) and link it with APACHE2 (which is called by IGV)

I always used TBE for every file name (TBE.fasta and TBE.2bit)

Here's the first line of the fasta file I used:
>chrZ_1

**Comment by jrobinso** [comment]
@Patg13 So the blat server is appending the filename to the returned record?   That should be easy to strip if we know the filename, which we don't.   We could split on the ':' character.   Maybe I'll try that.

I don't understand the gfserver setup,  what do you mean. "one for the sequence, the other for the translation"?    Could you point to the instructions you used to set this up?

**Comment by Patg13** [comment]
@jrobinso it is in the webBlat setup instruction : https://genome.ucsc.edu/goldenPath/help/blatSpec.html#webBlatUsage
See this section : **Creating in-memory indexes with gfServer**

**Comment by jrobinso** [comment]
@Patg13.  OK I added code to strip out the prefix, specifically it will strip characters up to and including the first ":" from the name.

**Comment by Patg13** [comment]
@jrobinso Yes, it is working now. My Blat result now bring me to the genome position. Thanks !

I still have the uppercase problem (one of my sequence has a uppercase Z in it's name, but the Blat result shows it as a lowercase z, so it's not recognized by the navigation panel.

I've check the psl output of my Blat server and the Z is in uppercase, so it's not coming from the server.

**Comment by jrobinso** [comment]
Yes, I found the lowercase conversion.   Just pushed fix

**Comment by maximilianh** [comment]
- gfServer loads the twobit file, takes all not-too-common 11mers
every stepSize nucleotides and puts a big hash table into memory. It
accepts queries on a given port.
- gfClient is the command line client for gfServer, it connects to the
port, sends the sequences and shows the output in PSL format.
- webBlat used to be a small CGI that sent queries to that port and
showed the output
- hgBlat has been doing the same thing, just nicer, for about 15
years: it send the sequence and the assembly code to gfServer via that
port and generates the HTML

**Comment by maximilianh** [comment]
@Patg13 <https://github.com/Patg13>  oh wow, it looks like webBlat is
indeed almost identical to hgBlat. Nice.

**Comment by maximilianh** [comment]
@jrobinso I had to change the format a little, I forgot that we already
have an API that also serves PSL, so it would probably be better if our PSL
output always looks the same. This is what alignments look in the API
https://api.genome.ucsc.edu/getData/track?jsonOutputArrays=1;genome=ce11;track=est;maxItemsOutput=5;chrom=chrI
and now my hgBlat json format looks similar. The only difference is that it
returns an object now, so we can easily add things in the future and also
that the blockStarts and blockSizes are not comma-sep strings as opposed to
arrays. Sorry!
https://hgwdev-max.gi.ucsc.edu/cgi-bin/hgBlat?userSeq=ACGGTGGCTCACGCCTGTAATCCCAGCACTGGAGGGCGAGGCAGGCGGAT&type=DNA&db=hg19&output=json

**Comment by Patg13** [comment]
@jrobinso Nice, it's working correctly now.
How did you specified which database to use on a webBlat server (is it taken from the genome name in IGV) ?
I'm asking because eventually I will have to add more genome to my webBlat and I want to make sure it will work.

**Comment by jrobinso** [comment]
@Patg13 It doesn't specify right now, if you set the "web_blat" option all blats are sent to it regardless of genome.  We will have to add something to support this.  However given the discussion above I would like to use maximilianh 's API rather than screen scraping webBlat output.     However I'm not sure what server that API is on,  I assume its a wrapper that directs a query to a specific gfServer depending on the value of the "db" parameter.      @maximilianh Can you confirm that, and what is the best option going forward for individual users setting up their own blat?   Would a query similar to this one

https://hgwdev-max.gi.ucsc.edu/cgi-bin/hgBlat?userSeq=ACGGTGGCTCACGCCTGTAATCCCAGCACTGGAGGGCGAGGCAGGCGGAT&type=DNA&db=hg19&output=json

with the same output format work for a custom blat server such as @Patg13 has installed?

**Comment by maximilianh** [comment]
Unfortunately, I have only changed hgBlat, not webblat. webblat is under a
different licence... I could ask Jim if I can change webblat, too...

**Comment by jrobinso** [comment]
@maximilianh I don't think you need to change anything on your end,  I need to add configuration to IGV to associate a specific assembly with a specify webblat server,  I will do that.

**Comment by Patg13** [comment]
@jrobinso did you have some time to work on the multi species capability of the WebBlat server ?

**Comment by maximilianh** [comment]
@jrobinso we have hundreds of new BLAT servers for most of NCBI's genomes
now for your testing, but I don't know your email address to send you
the URLs. Feel free to reach out to ***@***.*** for more information. We
have not been able to find more bugs for a week or so it should be quite
ready for release but the API for it may not be optimal yet for IGV.

>

**Comment by jrobinso** [comment]
@Patg13 Sorry not yet.
@maximilianh That would be great, will send you email.

**Comment by jrobinso** [comment]
Patg13,  if this is still an issue for you I just pushed support for using a command-line blat program, rather than a webservice.  Some doc and an example are here:  https://github.com/igvteam/igv/wiki/Customizing-BLAT.

Again big thanks to @maximilianh and UCSC generally for making this possible.
