### ISSUE TITLE
IGV 2.9.0: tracks don't resize correctly

### ISSUE THREAD

**Issue by marc-sturm** [igvteam/igv#901]
I just tested IGV 2.9.0 (all platforms version with JDK11) on Windows10 (version 10.017134).

I started IGV in window mode and loaded tracks (BAM, BED, etc).
Then I switch IGV to full-screen mode and the tracks did not adjusted the width correctly (screenshot 1).
After zooming once, the BAM track adjusted the width, but the other tracks did not change (screenshot 2).
Only when I changed the height of the other tracks manually, the width was adjusted correctly.

Best,
  Marc

Screenshot1:
![grafik](https://user-images.githubusercontent.com/5638144/106715420-590baa00-65fd-11eb-99f8-f99eecd63822.png)

Screenshot2:
![grafik](https://user-images.githubusercontent.com/5638144/106715655-abe56180-65fd-11eb-9672-1709b5dadc2a.png)

**Comment by jrobinso** [comment]
You are correct.   Manually resizing by dragging a corner works fine on a mac.    Will fix for the next release, thanks for the report.

On my Mac hitting the "refresh" icon on the command bar fixes the problem, which is much faster than manually resizing tracks.
