### ISSUE TITLE
How to enable "show all bases"

### ISSUE THREAD

**Issue by astulaaa** [igvteam/igv#902]
I want to see the alignment where bases are visible in aligned reads.
I found "Show all bases" option that should be able to do it here: https://software.broadinstitute.org/software/igv/PopupMenus#AlignmentTrack but I can't enable it.
I am running IGV 2.8 (I have an option of IGV 1.5 as well)
This is the batch command file content:

genome hg38
snapshotDirectory /Research/Project1/
load /Research/Project1/final.bam
maxPanelHeight 800
goto chr16:31117722-31117622
sort position chr16:31117672
sort base
snapshot new0203.png
exit

Is there any way to specify "Show all bases" option in a batch command file?

Regards,
Asta

**Comment by jrobinso** [comment]
First I recommend you use version 2.9.0 or greater for batch command scripts. 

There is no explicit command for "show all bases",  however using the user preference command should work

```
preference SAM.SHOW_ALL_BASES true
```
Complete set of supported commands are listed here http://software.broadinstitute.org/software/igv/PortCommands.

**Comment by astulaaa** [comment]
Thank you ,

It worked!
