### ISSUE TITLE
Add property to set translation table in genome definition. (was translation table for mitochondria - stop codons)

### ISSUE THREAD

**Issue by marc-sturm** [igvteam/igv#909]
Hi Jim,

in #582  you fixed the coloring of start codons.

There is a similar problem with stop codons:
The codon TGA is not a stop-codon for mitochondria:
https://en.wikipedia.org/wiki/Vertebrate_mitochondrial_code

However the codon TGA is colored red:
![grafik](https://user-images.githubusercontent.com/5638144/107519012-fcd1f880-6baf-11eb-9a4e-b3ffbbfe8cf9.png)

You can download our genome definition used in the screnshot here:
https://download.imgag.de/ahsturm1/genomes/1kg_v37_ensembl.genome

Where is the codon translation table actually defined for each chromosome?
Could not find that information anywhere in the .genome file.

Best,
  Marc

**Comment by jrobinso** [comment]
The translation table for a few human genomes are set in main/resoures.org.broad.igv/features/resources/defaultTranslationTables.json,  which refers by ID to the tables in genecticCode.json.  If they are not in that table you have to set it explicitly through the menu.   This is the problem.  Try manually setting the translation table in the menu.

There should be a field in the ".genome" file to define this, but there is not.  For the time being I'm adding you genome ID to the default translation tables as a synonym for hg19,  but keep this issue open as it needs a more general solution.

**Comment by jrobinso** [comment]
@marc-sturm Actually this is more complex than I thought, it looks like the functionality for automatically setting the translation table was never implemented.   For the time being you will have to manually set the translation table through the sequence track menu.   I will put this on the list of things to address for the next release.

**Comment by marc-sturm** [comment]
Thanks, manually setting it works.

Looking forward for the translation table setting in the .genome file!

**Comment by jrobinso** [comment]
@marc-sturm Sorry for the long delay, this was actually fixed some time ago.   There was a bug in the code that was causing the behavior you saw,  the consequence of the bug was that only 1 translation table could exist for a "genome".   This actually makes biological sense, but as the Mitochondria is commonly represented as another "chromosome" it caused the issue here.  

The bug should be fixed, which makes the request as currently titled unnecessary for this case.
