### ISSUE TITLE
Sequence Tracks Documentation Doesn't Explain Letter Casing

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv#910]
I would like to see an explanation of why the bases are sometimes lowercase and sometimes uppercase in [Viewing the Reference Genome](https://software.broadinstitute.org/software/igv/ViewGenome) section of the software's user guide.

**Comment by jrobinso** [comment]
@DarioS That's not really possible, we don't supply the fasta file(s).   Case conventions depend on the creator of the fasta, to know precisely you need to go to the source of a particular fasta and see what the creators say.   Usually it marks repeat sections, but IIRC there are other conventions, and how repeats are found is not standard.

**Comment by jrobinso** [comment]
Here's a good answer, response # 11  https://bioinformatics.stackexchange.com/a/231

**Comment by helgathorv** [comment]
I added some info about this to the sequence track doc.
