### ISSUE TITLE
IGV 2.9.1 (MacOS App with Java) freezes with multiple error messages.

### ISSUE THREAD

**Issue by hchetia** [igvteam/igv#911]
IGV 2.9.1 (MacOS App with Java) freezes with multiple error messages.

IGV log snippet below attached.

[igv_error.txt](https://github.com/igvteam/igv/files/5984224/igv_error.txt)

**Comment by jrobinso** [comment]
Thanks, I think I found this one.  Its a serious bug, I will release a 2.9.2 with the fix in a day or two, or you can try the snapshot build at https://software.broadinstitute.org/software/igv/download_snapshot

**Comment by hchetia** [comment]
Thanks Jim.

**Comment by jrobinso** [comment]
This should be fixed now in release 2.9.2
