### ISSUE TITLE
Update blat server options

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#913]
Thanks to @maximilianh at UCSC there are now new BLAT options.  See discussion #899 for details.  In summary

* JSON rest like api to replace screen scraping, e.g.
 
```
https://hgwdev-max.gi.ucsc.edu/cgi-bin/hgBlat?userSeq=GTCCTCGGAACCAGGACCTCGGCGTGGCCTAGCG&type=DNA&output=psl&db=hg19&output=json
```

* Support for hundreds of GCF assemblies (not yet released?)     "...You can specify a GCF_xxx and GCA_xxx ID (I think)
and it will be a bit slower on the first request, but otherwise identical."

**Comment by jrobinso** [comment]
@maximilianh. no problem with the format change, I haven't code anything yet and I'm just glad to get an option other than screen scraping.   I could event take raw psl output if that is easier.    So I will proceed with this form unless I hear differently, it will probably be a week or so before I get to this.   https://hgwdev-max.gi.ucsc.edu/cgi-bin/hgBlat?userSeq=ACGGTGGCTCACGCCTGTAATCCCAGCACTGGAGGGCGAGGCAGGCGGAT&type=DNA&db=hg19&output=json

I've opened a new issue because #899 is getting long and there are really 2 parallel issues there,  the custom blat server and the new API.

**Comment by maximilianh** [comment]
I'll ask around how people should set this up internally...

**Comment by maximilianh** [comment]
Another alternative is that you could keep support for webblat for the few custom servers and add the new UCSC Blat server as a separate option.

**Comment by jrobinso** [comment]
@maximilianh Yes that is a perfectly acceptable solution if you think webblat is likely to be stable.   I first coded this screenscraping blat code probably 10 years ago and its never been a problem,  so I'm not too concerned about it, and if something changed that broke it we could just modify the screenscraping.    So let's go with that solution,  but what should I call the new option (for the user UI)?   Also,  I'm going to keep the old screenscraping option because who knows if someone is using that with their own UCSC installation.     So I have 3 options to name,  maybe "UCSC Legacy",  "Webblat",   and "????"

**Comment by maximilianh** [comment]
our name is "hgBlat" but that is not easy to pronounce and maybe not easy
to understand... so for us it would be "hgBlat" and "legacy hgBlat"...
maybe not optimal?

how about something like "BLAT servers at UCSC" and "BLAT servers at UCSC
(legacy)" ?

**Comment by jrobinso** [comment]
@maximilianh Sorry for the long delay, busy year, but I have some time now to work on this.  Is there a production release of the blat service I should be using?  This URL looks like a dev server

https://hgwdev-max.gi.ucsc.edu/cgi-bin/hgBlat?userSeq=GTCCTCGGAACCAGGACCTCGGCGTGGCCTAGCG&type=DNA&output=psl&db=hg19&output=json


Thanks for you work on this!

**Comment by jrobinso** [comment]
Oh never mind, that wasn't hard to guess. (genome.ucsc.edu).  This looks great!

**Comment by jrobinso** [comment]
@maximilianh , a suggestion (is there a forum to post these),  if there is an error or there are no matches the server returns html.   It might be better if it returned json, if "output=json", with an embedded error message.   Small problem, I can work around it.
