### ISSUE TITLE
Missing available datasets in when loading HG19vs hg38

### ISSUE THREAD

**Issue by hchetia** [igvteam/igv#914]
Hi,
Could the datasets available for hg38 be enriched just like the ones for hg19?
**HG19**
![image](https://user-images.githubusercontent.com/64626735/108238002-7caf1400-7116-11eb-9881-fbcf23983e0f.png)
**HG38**
![image](https://user-images.githubusercontent.com/64626735/108237813-470a2b00-7116-11eb-89bb-1b9d1cc3b7d7.png)

**Comment by jrobinso** [comment]
Not anytime soon.
