### ISSUE TITLE
Problem initializing new IGV session from Link api

### ISSUE THREAD

**Issue by alex-seitz** [igvteam/igv#918]
Hello,
I'm trying to load signed S3 URLs to an IGV instance. It works, if I send each file request separately.
However, when loading the first bam, I set the "merge"-flag to "false", in order to create a new session. There it always asks me if I want to "Unload current session before loading new tracks?" (see similar issue #200 but there with batch and not with link URLs).

Additionaly, I tried to generate a session xml-file which could be opened via link, but the pre-signed files don't work there, I always get some error about expecting a ";"

Is there a way you can suppress the Confirm dialog when setting the merge parameter to false?

An example link looks like this (s3 repo removed):
`http://127.0.0.1:60151/load?file=https://<S3 LINK>.bam%3FX-Amz-Content-Sha256%3DUNSIGNED-PAYLOAD%26X-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Credential%3DA4QV58EQ906C3FQDZ8KC%252F20210225%252Fus-east-1%252Fs3%252Faws4_request%26X-Amz-Date%3D20210225T102149Z%26X-Amz-SignedHeaders%3Dhost%26X-Amz-Expires%3D28800%26X-Amz-Signature%3D527b88d051ec3e6f156afcd7ececb00b79eb95a14cc2fa94aee422505a96ceba&index=https%3A%2F%2Fngs-projects.s3.genetikum.de%3A10443%2Fdiagnostic%2Fexom_whole_diag%2FSample_NA12878_29%2FNA12878_29.bam.bai%3FX-Amz-Content-Sha256%3DUNSIGNED-PAYLOAD%26X-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Credential%3DA4QV58EQ906C3FQDZ8KC%252F20210225%252Fus-east-1%252Fs3%252Faws4_request%26X-Amz-Date%3D20210225T102149Z%26X-Amz-SignedHeaders%3Dhost%26X-Amz-Expires%3D28800%26X-Amz-Signature%3Dd4309490c8c019b7ba167ab829e01dfe5ceb674ebad7143a4af6da1bc8d44810&locus=chr17:41194312-41279381&genome=GRCh37&merge=false`

Best,
Alex

**Comment by jrobinso** [comment]
There's at least 2 different issues here, the confirm dialog and pre-signed S3 urls in xml sessions.   Could you open a separate issue for the second?    My initial reaction is that presigned URLs do not belong in session files, they will (or should) expire relatively quickly.    In any event it is a separate issue, with another team involved,  the S3 support is primarily contributed by UMCCR.

I will look at suppressing the confirmation dialog in the next release cycle,  ~ the end of March.

**Comment by alex-seitz** [comment]
Yes, sorry, I will open a separate issue for the second one

Best,
Alex

**Comment by janrehker** [comment]
Well, for me this was not a bug, but a feature. Removing the dialogue alltogether prevents me from upgrading to future IGV-versions.
My users sometimes need to load an additional track to compare two samples and sometimes they will need to unload and load a different track.

Would it be possible to just make this an option somewhere in the settings of igv? Or an optional part of the command that is to be sent to igv?

Best regards,
Jan Rehker
