### ISSUE TITLE
Pre-Signed S3 URLs are not working in session files

### ISSUE THREAD

**Issue by alex-seitz** [igvteam/igv#920]
Hello,
when I'm trying to use pre-Signed S3 URLs in an igv-session xml-file, I always get some error about expecting a ";".
As pre-signed URLs expire rather quickly they might appear to not be relevant for session files, but as you can open a session file through an http link request, this possibility would let me create temporary session files that I link to IGV. These would let me style the windows a lot better, as they allow for more fine-tuning compared to standard URL links.

Best,
Alex

**Comment by alex-seitz** [comment]
Hello,
I realized I made a mistake. I encoded the paths with the php-function `urlencode`. That does not work. However, when you encode the paths with the php-function `htmlentities`, it works great.

Best,
Alex

**Comment by jrobinso** [comment]
Interesting, thanks for pointing that out.
