### ISSUE TITLE
Unable to load native GTK libraries

### ISSUE THREAD

**Issue by wzthhm** [igvteam/igv#921]
Hello：
I meet a trouble in igv , when i run it in my Linux, get the error as below:
thanks a lot
[java.lang.InternalError.txt](https://github.com/igvteam/igv/files/6066346/java.lang.InternalError.txt)

**Comment by jrobinso** [comment]
You'll probably have to take this up on a Linux forum,  in any event there is not enough information in your post for us to help you.    

How did you install IGV?

**Comment by wzthhm** [comment]
> You'll probably have to take this up on a Linux forum, in any event there is not enough information in your post for us to help you.
> 
> How did you install IGV?

I tried to install igv at "http://data.broadinstitute.org/igv/projects/downloads/2.5/IGV_2.5.2.zip" ,an old version. And tried to install at "https://data.broadinstitute.org/igv/projects/downloads/2.9/IGV_Linux_2.9.2_WithJava.zip" ,a new version with jdk. But I meet the same trouble. 
What is the likely reason for this? GTK configure?
thanks!

**Comment by jrobinso** [comment]
I really don't know, this is a Java / Linux / X-Windows question.    I don't know anything about GTK.   You didn't give us any useful description of the problem other than the title of the issue.  Could you include a full stack trace from your console or contents of your igv.log file?   Its in an IGV folder under your home directory.   Also, are you running 64 bit Linux?

**Comment by wzthhm** [comment]
> I really don't know, this is a Java / Linux / X-Windows question. I don't know anything about GTK. You didn't give us any useful description of the problem other than the title of the issue. Could you include a full stack trace from your console or contents of your igv.log file? Its in an IGV folder under your home directory. Also, are you running 64 bit Linux?

Yes,64 bit. T_T
[igv.log](https://github.com/igvteam/igv/files/6066690/igv.log)

**Comment by jrobinso** [comment]
What is your OS version?  Is it reasonably up-to-date?  Newer Java versions might not support old GTK libraries.

**Comment by wzthhm** [comment]
Yes,it‘s a old version
CentOS release 6.5, Linux version 2.6.32-431.23.3.el6.x86_64

**Comment by jrobinso** [comment]
That's probably the reason then,  you'll need to inquire on Centos or Linux forums to determine what the minimum Centos version is.
