### ISSUE TITLE
Support strand specific RNA seq visualization?

### ISSUE THREAD

**Issue by JoKerDii** [igvteam/igv#924]
Like a question asked [here](https://www.biostars.org/p/97512/), I'm trying to use IGV to display positive reads upwards and negative reads downwards, but can't find a way to do this. 

Is it possible to add a function to "igvtools count -strands read" to count positive number of reads on the positive strand and negative number of reads on the negative strand? In this way, I think IGV may achieve what I want. Or there may be other ways.

If there is any suggestion or help for me, I'm very appreciated it!

**Comment by jrobinso** [comment]
I answered on the help forum.
