### ISSUE TITLE
Feature request: Get DNA sequence

### ISSUE THREAD

**Issue by Mashin6** [igvteam/igv#926]
I find myself often in need of the sequence under a signal peak or of certain exon/transcript and I always gave to transfer the coordinates to UCSC Genome Browser to download the sequence. Since IGV have the genomic sequence and annotation as well it shouldn't be difficult to add an option to extract the sequence in certain region or even from annotated feature.

**Comment by jrobinso** [comment]
You can do this.  Create a region of interest covering the sequence of interest (ctrl-R to cover the region in view).    Then click on it and select copy sequence.   Also,  all features within certain size limits have copy sequence options in the right-click menu.

**Comment by Mashin6** [comment]
Oh interesting, that was pretty hidden. I wonder if it would make sense to skip the region requirement and allow copy sequence for current window view.

Anyways thanks for the pointers!
