### ISSUE TITLE
Loading IGV session creates a bunch of genome map files

### ISSUE THREAD

**Issue by tayabsoomro** [igvteam/igv#930]
I have a pre-configured and zipped genome file which I am running with IGV, but it seems like IGV expands the genome zip file and copies a bunch of genome map files into the directory from which I am loading the genome. I am wondering whether this can be prevented? I am running IGV on a limited storage and I would like this to be as compressed as possible. Please let me know?

**Comment by jrobinso** [comment]
Sorry I don't know what you mean,   first what is a "zipped genome file", and for that matter what do you mean by "genome map files".

**Comment by jrobinso** [comment]
I'm closing due to lack of response.   Re open addressing the questions above if this continues to be a problem.
