### ISSUE TITLE
IGV fails to load GTF files in saved sessions

### ISSUE THREAD

**Issue by dixonxray** [igvteam/igv#932]
My GTF tracks load manually into browser OK but cannot be loaded in saved sessions. The presence of GTF tracks in session.xml files causes the Mac version of IGV to hang with very high CPU usage. There are no error messages in the IGV log other than an indication that tracks are loading. In contrast,  GFF files can be loaded from session files.

INFO [2021-03-12T12:44:18,275] [Main.java:205]  Startup  IGV Version 2.9.2 02/16/2021 01:27 PM
INFO [2021-03-12T12:44:18,276] [Main.java:206]  Java 14 (build 14+36-1461) 2020-03-17
INFO [2021-03-12T12:44:18,276] [Main.java:209]  Java Vendor: Oracle Corporation https://java.oracle.com/
INFO [2021-03-12T12:44:18,278] [Main.java:211]  JVM: OpenJDK 64-Bit Server VM    
INFO [2021-03-12T12:44:18,426] [Main.java:214]  Default User Directory: /Users/ray
INFO [2021-03-12T12:44:18,427] [Main.java:215]  OS: Mac OS X 10.16 x86_64
INFO [2021-03-12T12:44:20,260] [GenomeManager.java:183]  Loading genome: /Users/ray/igv/Browser Standards/Avin.fna
INFO [2021-03-12T12:44:20,558] [CommandListener.java:121]  Listening on port 60151
INFO [2021-03-12T12:44:50,610] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/n_V_TSS.bedgraph
INFO [2021-03-12T12:44:50,610] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/ln_lfc_vnfA3-Fe.bedgraph
INFO [2021-03-12T12:44:50,610] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/Mo_TSS_filt.gtf
INFO [2021-03-12T12:44:50,611] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/FIMO-All VnfA and VnfA3 sites filtered.gff
INFO [2021-03-12T12:44:50,610] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/ln_lfc_vnfA-Fe.bedgraph
INFO [2021-03-12T12:44:50,613] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/Avin.bed
INFO [2021-03-12T12:44:50,614] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/n_FE_TSS.bedgraph
INFO [2021-03-12T12:44:50,629] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/FIMO_Avin_AnfA_v2.gff
INFO [2021-03-12T12:44:50,635] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/Genebank_Avin_2013.gb_genes1.gff
INFO [2021-03-12T12:44:50,665] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/ln_lfc_vnfA3-V.bedgraph
INFO [2021-03-12T12:44:50,648] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/FE_TSS_filt.gtf
INFO [2021-03-12T12:44:50,666] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/n_Mo_TSS.bedgraph
INFO [2021-03-12T12:44:50,667] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/Fimo_Avin_RpoN_Azotobacter.gff
INFO [2021-03-12T12:44:50,667] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/V_TSS_filt.gtf
INFO [2021-03-12T12:44:50,667] [TrackLoader.java:122]  Loading resource, path /Users/ray/igv/Browser Standards/ln_lfc_vnfA-V.bedgraph

**Comment by jrobinso** [comment]
High,  I can't reproduce this.    Could you zip up an example that reproduces the problem?

**Comment by dixonxray** [comment]
Hi Jim

Here is a folder with the genome file, all tracks loaded and 2 session files (“minus_gtf” works and “plus_gtf” does not). The log (also included) indicates no errors but in the case of the GTF session, loading hangs with high CPU.

The compressed file exceeds the attachments size limit. It can be downloaded from here:

https://www.dropbox.com/s/zct02t5apkp8aic/Session%20GTF%20issue.zip?dl=0



Thanks,

Ray


From: Jim Robinson ***@***.***>
Date: Wednesday, 17 March 2021 at 21:02
To: igvteam/igv ***@***.***>
Cc: dixonxray ***@***.***>, Author ***@***.***>
Subject: Re: [igvteam/igv] IGV fails to load GTF files in saved sessions (#932)

High, I can't reproduce this. Could you zip up an example that reproduces the problem?

**Comment by jrobinso** [comment]
Thanks for the test data.  I can confirm the problem you described, but am not sure of the cause.  Its not "gtf" files per se however, I can save a session with all the gtf files (and only those) and loads without issue.    I just can't load the complete combination of files here.   Will look more deeply tomorrow.

**Comment by jrobinso** [comment]
@dixonxray How was this session file produced?  If you remove the "Panel" sections, leaving just Resources as shown below.  It works fine.  

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Session genome="Avin.fna" hasGeneTrack="false" hasSequenceTrack="true" locus="Avin:0-5365318" nextAutoscaleGroup="2" version="8">
    <Resources>
        <Resource name="Mo_TSS_filt.gtf" path="Mo_TSS_filt.gtf"/>
        <Resource name="ln_lfc_vnfA3-Fe.bedgraph" path="ln_lfc_vnfA3-Fe.bedgraph"/>
        <Resource name="n_Mo_TSS.bedgraph" path="n_Mo_TSS.bedgraph"/>
        <Resource name="ln_lfc_vnfA-V.bedgraph" path="ln_lfc_vnfA-V.bedgraph"/>
        <Resource name="FE_TSS_filt.gtf" path="FE_TSS_filt.gtf"/>
        <Resource name="Genebank_Avin_2013.gb_genes1.gff" path="Genebank_Avin_2013.gb_genes1.gff"/>
        <Resource name="FIMO_Avin_AnfA_v2.gff" path="FIMO_Avin_AnfA_v2.gff"/>
        <Resource name="Avin.bed" path="Avin.bed"/>
        <Resource name="FIMO-All VnfA and VnfA3 sites filtered.gff" path="FIMO-All VnfA and VnfA3 sites filtered.gff"/>
        <Resource name="n_V_TSS.bedgraph" path="n_V_TSS.bedgraph"/>
        <Resource name="n_FE_TSS.bedgraph" path="n_FE_TSS.bedgraph"/>
        <Resource name="ln_lfc_vnfA3-V.bedgraph" path="ln_lfc_vnfA3-V.bedgraph"/>
        <Resource name="Fimo_Avin_RpoN_Azotobacter.gff" path="Fimo_Avin_RpoN_Azotobacter.gff"/>
        <Resource name="V_TSS_filt.gtf" path="V_TSS_filt.gtf"/>
        <Resource name="ln_lfc_vnfA-Fe.bedgraph" path="ln_lfc_vnfA-Fe.bedgraph"/>
    </Resources>
</Session>
```

Subsequently saving the session and reloading, it also works fine

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Session genome="/Users/jrobinso/Downloads/Session GTF issue/Avin.fna" hasGeneTrack="false" hasSequenceTrack="true" locus="Avin:0-5365318" nextAutoscaleGroup="2" version="8">
    <Resources>
        <Resource name="ln_lfc_vnfA3-V.bedgraph" path="ln_lfc_vnfA3-V.bedgraph"/>
        <Resource name="ln_lfc_vnfA-Fe.bedgraph" path="ln_lfc_vnfA-Fe.bedgraph"/>
        <Resource name="ln_lfc_vnfA-V.bedgraph" path="ln_lfc_vnfA-V.bedgraph"/>
        <Resource name="Mo_TSS_filt.gtf" path="Mo_TSS_filt.gtf"/>
        <Resource name="FE_TSS_filt.gtf" path="FE_TSS_filt.gtf"/>
        <Resource name="Avin.bed" path="Avin.bed"/>
        <Resource name="FIMO_Avin_AnfA_v2.gff" path="FIMO_Avin_AnfA_v2.gff"/>
        <Resource name="FIMO-All VnfA and VnfA3 sites filtered.gff" path="FIMO-All VnfA and VnfA3 sites filtered.gff"/>
        <Resource name="ln_lfc_vnfA3-Fe.bedgraph" path="ln_lfc_vnfA3-Fe.bedgraph"/>
        <Resource name="V_TSS_filt.gtf" path="V_TSS_filt.gtf"/>
        <Resource name="n_V_TSS.bedgraph" path="n_V_TSS.bedgraph"/>
        <Resource name="Fimo_Avin_RpoN_Azotobacter.gff" path="Fimo_Avin_RpoN_Azotobacter.gff"/>
        <Resource name="n_Mo_TSS.bedgraph" path="n_Mo_TSS.bedgraph"/>
        <Resource name="n_FE_TSS.bedgraph" path="n_FE_TSS.bedgraph"/>
        <Resource name="Genebank_Avin_2013.gb_genes1.gff" path="Genebank_Avin_2013.gb_genes1.gff"/>
    </Resources>
    <Panel height="404" name="DataPanel" width="1659">
        <Track attributeKey="vnfA3-Fe_ln_lfc" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/ln_lfc_vnfA3-Fe.bedgraph" name="ln_lfc_vnfA3-Fe.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
            <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="1.2281713" minimum="-0.67026645" type="LINEAR"/>
        </Track>
        <Track attributeKey="n_Mo_TSS" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/n_Mo_TSS.bedgraph" name="n_Mo_TSS.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
            <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="8032.0" minimum="0.0" type="LINEAR"/>
        </Track>
        <Track attributeKey="vnfA-V_ln_lfc" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/ln_lfc_vnfA-V.bedgraph" name="ln_lfc_vnfA-V.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
            <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="1.0876857" minimum="-0.3082418" type="LINEAR"/>
        </Track>
        <Track attributeKey="n_V_TSS" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/n_V_TSS.bedgraph" name="n_V_TSS.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
            <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="7814.61" minimum="0.0" type="LINEAR"/>
        </Track>
        <Track attributeKey="n_FE_TSS" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/n_FE_TSS.bedgraph" name="n_FE_TSS.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
            <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="7949.553" minimum="0.0" type="LINEAR"/>
        </Track>
        <Track attributeKey="vnfA3-V_ln_lfc" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/ln_lfc_vnfA3-V.bedgraph" name="ln_lfc_vnfA3-V.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
            <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="1.3344368" minimum="-1.8926058" type="LINEAR"/>
        </Track>
        <Track attributeKey="vnfA-Fe_ln_lfc" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/ln_lfc_vnfA-Fe.bedgraph" name="ln_lfc_vnfA-Fe.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
            <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="1.1608615" minimum="-0.6722867" type="LINEAR"/>
        </Track>
    </Panel>
    <Panel height="431" name="FeaturePanel" width="1659">
        <Track attributeKey="Reference sequence" clazz="org.broad.igv.track.SequenceTrack" fontSize="10" id="Reference sequence" name="Reference sequence" sequenceTranslationStrandValue="POSITIVE" shouldShowTranslation="true" visible="true"/>
        <Track attributeKey="Mo_TSS_filt.gtf" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/Mo_TSS_filt.gtf" name="Mo_TSS_filt.gtf" visible="true"/>
        <Track attributeKey="FE_TSS_filt.gtf" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/FE_TSS_filt.gtf" name="FE_TSS_filt.gtf" visible="true"/>
        <Track attributeKey="Genebank_Avin_2013.gb_genes1.gff" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/Genebank_Avin_2013.gb_genes1.gff" name="Genebank_Avin_2013.gb_genes1.gff" visible="true"/>
        <Track attributeKey="FIMO_Avin_AnfA_v2.gff" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/FIMO_Avin_AnfA_v2.gff" name="FIMO_Avin_AnfA_v2.gff" visible="true"/>
        <Track attributeKey="Avin.bed" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/Avin.bed" name="Avin.bed" visible="true"/>
        <Track attributeKey="FIMO-All VnfA and VnfA3 sites filtered.gff" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/FIMO-All VnfA and VnfA3 sites filtered.gff" name="FIMO-All VnfA and VnfA3 sites filtered.gff" visible="true"/>
        <Track attributeKey="Fimo_Avin_RpoN_Azotobacter.gff" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/Fimo_Avin_RpoN_Azotobacter.gff" name="Fimo_Avin_RpoN_Azotobacter.gff" visible="true"/>
        <Track attributeKey="V_TSS_filt.gtf" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" fontSize="10" id="/Users/jrobinso/Downloads/Session GTF issue/V_TSS_filt.gtf" name="V_TSS_filt.gtf" visible="true"/>
    </Panel>
    <PanelLayout dividerFractions="0.4821852731591449"/>
    <HiddenAttributes>
        <Attribute name="DATA FILE"/>
        <Attribute name="DATA TYPE"/>
        <Attribute name="NAME"/>
    </HiddenAttributes>
</Session>

```

**Comment by dixonxray** [comment]
Many thanks for following this up. To create this session file, I loaded up the tracks, changed some of the track attributes which get saved in the “Panel” sections and then saved the session.

I can confirm that removing the “panel" section allows the session to load.

Session genome="/Users/ray/igv/Browser Standards/Avin.fna" hasGeneTrack="false" hasSequenceTrack="true" locus="Avin:0-5365318" nextAutoscaleGroup="2" version="8">
 <Resources>
 <Resource name="Mo_TSS_filt.gtf" path="Mo_TSS_filt.gtf"/>
 <Resource name="ln_lfc_vnfA3-Fe.bedgraph" path="ln_lfc_vnfA3-Fe.bedgraph"/>
 <Resource name="n_Mo_TSS.bedgraph" path="n_Mo_TSS.bedgraph"/>
 <Resource name="ln_lfc_vnfA-V.bedgraph" path="ln_lfc_vnfA-V.bedgraph"/>
 <Resource name="FE_TSS_filt.gtf" path="FE_TSS_filt.gtf"/>
 <Resource name="Genebank_Avin_2013.gb_genes1.gff" path="Genebank_Avin_2013.gb_genes1.gff"/>
 <Resource name="FIMO_Avin_AnfA_v2.gff" path="FIMO_Avin_AnfA_v2.gff"/>
 <Resource name="Avin.bed" path="Avin.bed"/>
 <Resource name="FIMO-All VnfA and VnfA3 sites filtered.gff" path="FIMO-All VnfA and VnfA3 sites filtered.gff"/>
 <Resource name="n_V_TSS.bedgraph" path="n_V_TSS.bedgraph"/>
 <Resource name="n_FE_TSS.bedgraph" path="n_FE_TSS.bedgraph"/>
 <Resource name="ln_lfc_vnfA3-V.bedgraph" path="ln_lfc_vnfA3-V.bedgraph"/>
 <Resource name="Fimo_Avin_RpoN_Azotobacter.gff" path="Fimo_Avin_RpoN_Azotobacter.gff"/>
 <Resource name="V_TSS_filt.gtf" path="V_TSS_filt.gtf"/>
 <Resource name="ln_lfc_vnfA-Fe.bedgraph" path="ln_lfc_vnfA-Fe.bedgraph"/>
 </Resources>
</Session>


However, if I then save the session and try to reload it, it does not work for me:

<Session genome="/Users/ray/igv/Browser Standards/Avin.fna" hasGeneTrack="false" hasSequenceTrack="false" locus="Avin:0-5365318" nextAutoscaleGroup="2" version="8">
 <Resources>
 <Resource name="Mo_TSS_filt.gtf" path="Mo_TSS_filt.gtf"/>
 <Resource name="ln_lfc_vnfA3-Fe.bedgraph" path="ln_lfc_vnfA3-Fe.bedgraph"/>
 <Resource name="n_Mo_TSS.bedgraph" path="n_Mo_TSS.bedgraph"/>
 <Resource name="ln_lfc_vnfA-V.bedgraph" path="ln_lfc_vnfA-V.bedgraph"/>
 <Resource name="FE_TSS_filt.gtf" path="FE_TSS_filt.gtf"/>
 <Resource name="Genebank_Avin_2013.gb_genes1.gff" path="Genebank_Avin_2013.gb_genes1.gff"/>
 <Resource name="FIMO_Avin_AnfA_v2.gff" path="FIMO_Avin_AnfA_v2.gff"/>
 <Resource name="Avin.bed" path="Avin.bed"/>
 <Resource name="FIMO-All VnfA and VnfA3 sites filtered.gff" path="FIMO-All VnfA and VnfA3 sites filtered.gff"/>
 <Resource name="n_V_TSS.bedgraph" path="n_V_TSS.bedgraph"/>
 <Resource name="n_FE_TSS.bedgraph" path="n_FE_TSS.bedgraph"/>
 <Resource name="ln_lfc_vnfA3-V.bedgraph" path="ln_lfc_vnfA3-V.bedgraph"/>
 <Resource name="Fimo_Avin_RpoN_Azotobacter.gff" path="Fimo_Avin_RpoN_Azotobacter.gff"/>
 <Resource name="V_TSS_filt.gtf" path="V_TSS_filt.gtf"/>
 <Resource name="ln_lfc_vnfA-Fe.bedgraph" path="ln_lfc_vnfA-Fe.bedgraph"/>
 </Resources>
 <Panel height="547" name="DataPanel" width="2529">
 <Track attributeKey="vnfA3-Fe_ln_lfc" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/ln_lfc_vnfA3-Fe.bedgraph" name="ln_lfc_vnfA3-Fe.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
 <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="1.2281713" minimum="-0.67026645" type="LINEAR"/>
 </Track>
 <Track attributeKey="n_Mo_TSS" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/n_Mo_TSS.bedgraph" name="n_Mo_TSS.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
 <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="8032.0" minimum="0.0" type="LINEAR"/>
 </Track>
 <Track attributeKey="vnfA-V_ln_lfc" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/ln_lfc_vnfA-V.bedgraph" name="ln_lfc_vnfA-V.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
 <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="1.0876857" minimum="-0.3082418" type="LINEAR"/>
 </Track>
 <Track attributeKey="n_V_TSS" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/n_V_TSS.bedgraph" name="n_V_TSS.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
 <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="7814.61" minimum="0.0" type="LINEAR"/>
 </Track>
 <Track attributeKey="n_FE_TSS" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/n_FE_TSS.bedgraph" name="n_FE_TSS.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
 <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="7949.553" minimum="0.0" type="LINEAR"/>
 </Track>
 <Track attributeKey="vnfA3-V_ln_lfc" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/ln_lfc_vnfA3-V.bedgraph" name="ln_lfc_vnfA3-V.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
 <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="1.3344368" minimum="-1.8926058" type="LINEAR"/>
 </Track>
 <Track attributeKey="vnfA-Fe_ln_lfc" autoScale="false" clazz="org.broad.igv.track.DataSourceTrack" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/ln_lfc_vnfA-Fe.bedgraph" name="ln_lfc_vnfA-Fe.bedgraph" renderer="BAR_CHART" visible="true" windowFunction="mean">
 <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="1.1608615" minimum="-0.6722867" type="LINEAR"/>
 </Track>
 </Panel>
 <Panel height="1265" name="FeaturePanel" width="2529">
 <Track attributeKey="Mo_TSS_filt.gtf" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/Mo_TSS_filt.gtf" name="Mo_TSS_filt.gtf" visible="true"/>
 <Track attributeKey="FE_TSS_filt.gtf" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/FE_TSS_filt.gtf" name="FE_TSS_filt.gtf" visible="true"/>
 <Track attributeKey="Genebank_Avin_2013.gb_genes1.gff" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/Genebank_Avin_2013.gb_genes1.gff" name="Genebank_Avin_2013.gb_genes1.gff" visible="true"/>
 <Track attributeKey="FIMO_Avin_AnfA_v2.gff" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/FIMO_Avin_AnfA_v2.gff" name="FIMO_Avin_AnfA_v2.gff" visible="true"/>
 <Track attributeKey="Avin.bed" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/Avin.bed" name="Avin.bed" visible="true"/>
 <Track attributeKey="FIMO-All VnfA and VnfA3 sites filtered.gff" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/FIMO-All VnfA and VnfA3 sites filtered.gff" name="FIMO-All VnfA and VnfA3 sites filtered.gff" visible="true"/>
 <Track attributeKey="Fimo_Avin_RpoN_Azotobacter.gff" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/Fimo_Avin_RpoN_Azotobacter.gff" name="Fimo_Avin_RpoN_Azotobacter.gff" visible="true"/>
 <Track attributeKey="V_TSS_filt.gtf" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" displayMode="EXPANDED" fontSize="10" id="/Users/ray/igv/Browser Standards/V_TSS_filt.gtf" name="V_TSS_filt.gtf" visible="true"/>
 </Panel>
 <PanelLayout dividerFractions="0.4820017559262511"/>
</Session>


The Panel heights and width are different in my session. But this cannot be the source of the issue ?

**Comment by jrobinso** [comment]
@dixonxray I'm not sure,  I will be devoting today to tracking this down.   It is a strange one.

**Comment by jrobinso** [comment]
I found the issue.   The fix will be in the next minor release, the end of next week at the earliest.   If you need it in the meantime you can use the nightly "snapshot" build.
