### ISSUE TITLE
Display translocation on long reads using horizontal split screen

### ISSUE THREAD

**Issue by olechnwin** [igvteam/igv#942]
Hi,

I wonder whether it would be possible to implement a similar feature to view translocation on long reads. 
This is a screen capture of bionano's genome browser. The "read" is in the middle with both reference where it mapped to showing on top and bottom.

![image](https://user-images.githubusercontent.com/20069067/112655508-d649e300-8e26-11eb-9e67-eba9c9da2889.png)

**Comment by jrobinso** [comment]
@olechnwin Sorry for the delay.  This isn't likely to get implemented in IGV, it's out of scope for us.

**Comment by olechnwin** [comment]
@jrobinso Thank you for your reply and for considering this.
