### ISSUE TITLE
display on/off indels in PacBio long reads

### ISSUE THREAD

**Issue by Fred-07** [igvteam/igv#949]
Hello,

The display option to hide indels in pacbio alignments has no effect.
Indels are still visible.
Mapping done with pbmm2.
PacBio tutorial link:
https://www.youtube.com/watch?v=nLpmeD57ToA
IGV versions that were tested : 2.9.4, 2.8.2, version snapshot 29.03.2021

**Comment by helgathorv** [comment]
The Preferences panel has changed since PacBio created that video. There is now a separate tab for 3rd gen sequencing where you can set the display for indels in PacBio reads. If that doesn't work for you please let us know and re-open this issue.

**Comment by Fred-07** [comment]
Thank you! It works.
