### ISSUE TITLE
problem loading annotations in custom genome

### ISSUE THREAD

**Issue by AnitaS321** [igvteam/igv#951]
While creating a custom genome of hg19 plus additional contigs, I ran into an issue where the annotations could not be loaded. I was using the ncbiRefSeq.sorted.txt file that comes bundled with the IGV hg19.genome. Changing the file name from _ncbiRefSeq.sorted.txt_ to _ncbiRefGene.txt_ allowed me to create the custom genome. Test file and further details here: https://groups.google.com/g/igv-help/c/ym5k7QD8spg

**Comment by jrobinso** [comment]
Thanks for he report.  Definitely an IGV bug, I will see what can be done about it.

**Comment by jrobinso** [comment]
@AnitaS321 I think you were using an old version of the hg19.genome.   It now comes bundled with ncbiRefGene.txt.  I suggest you use this file rather than renaming the old one as there are important differences for certain genes.  You can download it form UCSC.

**Comment by jrobinso** [comment]
I can't reproduce the problem, if it remains an issue please re-open and provide access or a pointer to the fasta.
