### ISSUE TITLE
Error message when attempting to start IGV on MacBook Pro with new M1 chip

### ISSUE THREAD

**Issue by CarlH321** [igvteam/igv#952]
Has anyone had trouble launching IGV on a new MacBook Pro?  IGV downloads OK, but I get an error message saying that I don't have permission to open the file.  Apple support seems to be stumped.  Is this an issue with the new M1 chip?
Thanks for your thoughts.

**Comment by helgathorv** [comment]
The user got this working by installing Rosetta, a utility that allows an M1 Mac to run software written for an Intel-based Mac.
