### ISSUE TITLE
Bisulfite mode color change

### ISSUE THREAD

**Issue by rrazaghi** [igvteam/igv#955]
Hi,

I was wondering if there's a way to change the color scheme for bisulfite mode from red and blue to something else.
I tried to change the color legends for methylation but that did not change anything.

Thank you!

**Comment by jrobinso** [comment]
Currently there is not, other than changing source code and building.

**Comment by rrazaghi** [comment]
Thank you, Jim! I figured that was the case but wanted to make sure!

**Comment by jrobinso** [comment]
I'm re-opening because there should be a way to change it, but there isn't currently.
