### ISSUE TITLE
Desplay sample attributes

### ISSUE THREAD

**Issue by SergioRLL** [igvteam/igv#957]
Hello,

I am trying to see by color and to group by an attribute the attributes loaded with a .txt file as indicated in [here](https://software.broadinstitute.org/software/igv/SampleInformation) but it does not work. I am using a metagenome and a VCF file.
As you can see in the image the section for the sample attributes does not show the colors. How can I solve this? The .txt file is already tab-delimited.

Thank you, 
Sergio

![image](https://user-images.githubusercontent.com/65596261/117707885-6a052200-b1cf-11eb-9b30-7ff8f4970641.png)

**Comment by SergioRLL** [comment]
The zip size is 48 MB, may I send it to you via email?
Thanks,

**Comment by SergioRLL** [comment]
Perfect :+1:

**Comment by jrobinso** [comment]
Hi, there are a couple of problems here.  First, the sample names in the VCF you sent us differ from the sample names displayed in the sample information file, and in your screenshot.  For example the first sample is named "BL090113" in the VCF file,  but "BL0900113.bin208.95id.sorted" in the screenshot.    Second, the sample info file must be tab delimited, yours is space delimited.    Either of these problems will cause failure, in the first case by sample name mismatch, in the second the file will not be recognized as a sample information file.
