### ISSUE TITLE
Repeated clustering (in new region) appears affected by some form of cache?

### ISSUE THREAD

**Issue by ollenordesjo** [igvteam/igv#960]
I'm using 2.9.4 and using the cluster (phase) alignments feature.

I'm expecting that clustering first with say 10 clusters, and then subsequently (if I realised there were too many for example) clustering with 2 clusters would only show the 2 clusters after the second run. 

However, it appears that previous groups are stored in some form of cache and are not necessarily reclustered. Is there anyway of clearing this cache without restarting IGV?

Many thanks!

**Comment by jrobinso** [comment]
@ollenordesjo Its a surprise to me that feature even appears, it should not as it was never completed or released.   It was an experimental feature.   However if you're finding it useful I will look into it,  I assume you are using it with long-read data.

**Comment by jrobinso** [comment]
OK I think I fixed this.   It's actually a mistake that this feature appears in the menu, it was an experiment and I was never happy with it, but as at least 1 person is using it we will leave it there for now.    I was myself a bit confused when trying to use it again,  it only clusters alignments that are completely contained in the viewport.   To make this clearer I have assigned a class of "NONE" to alignments that aren't included,  I found it too easy to see those as belonging to the last class.

**Comment by ollenordesjo** [comment]
Hi @jrobinso, it's definitely been a helpful feature! Even if it's not working perfectly, it's way better than not existing. We're definitely more than a handful of people who use it to get a better ordering of data in areas of interest, so I think it's well worth keeping it 👍. Thanks for sorting this quickly as well (:

**Comment by jrobinso** [comment]
@ollenordesjo OK good to know,  it could definitely be improved.

**Comment by ollenordesjo** [comment]
If there is ongoing work to improve it, I think that it would be great if insertions/deletions could also be used for the grouping somehow. I think that might improve on things even further.

**Comment by jrobinso** [comment]
@ollenordesjo Can you open a new git issue for that (insertions / deletions)?   That will keep the topic alive, it's likely to be forgotten here.
