### ISSUE TITLE
visualize Hi-C data

### ISSUE THREAD

**Issue by gorliver** [igvteam/igv#961]
Is there any plan to support visualization of Hi-C contacts using arc plot?

**Comment by jrobinso** [comment]
@gorliver What did you have in mind?   The output of hic analysis is typically TADs or other contact measure in the form of bedpe files, which is supported now.   Do you envision representing every single contact with an arc?   

BTW you might not know this but I am the creator of Juicebox and the .hic format, among other tools in that field, so I understand the data well.

**Comment by gorliver** [comment]
Hi jrobinso,
What I'm looking for is an arc plot of my significant contacts. Below is an example:
![image](https://user-images.githubusercontent.com/15271446/118411434-820ef280-b662-11eb-9e4b-3f6adbb25c1b.png)

The arc is significant contact, thickness represents the significance. It will be super convenient if I can plot this together with my other tracks in IGV.

**Comment by jrobinso** [comment]
This is supported with bedpe format.   You need to use some analysis tool
to determine what is significant.

**Comment by gorliver** [comment]
Thank you very much! It works great!
