### ISSUE TITLE
import igv from 'igv' does not work on Linux

### ISSUE THREAD

**Issue by wendazhoucs** [igvteam/igv#963]
Hello, 
at beginning of my code, I have **import igv from 'igv'**.  This works on my MacOS. But when I copy the same code and running on Linux,  the terminal indicate 
Failed to compile. 
./node_modules/igv/dist/igv.js
Module not found: Can't resolve 'btoa' in '/............./node_modules/igv/dist'.
However, when I changed to **import igv from 'tmp_es6_igv'**; the code runs well. 
Why this happend? 
Thanks

**Comment by jrobinso** [comment]
This varies by browser, but naked imports (e.e. import igv from 'igv') will in general not work,  that is not legal javascript although some browsers will let you do it.  To work everywhere you need to use an explicit path as in your second example.

**Comment by jrobinso** [comment]
Oh, with respect to the "btoa" reference that is a separate issue,  its been fixed but you need to use the latest release.   The previous comment applies though,  you have to use and explicit path including the ".js" extension to work everywhere.

**Comment by wendazhoucs** [comment]
Thank You!! After I change to **import igv from 'igv/dist/igv'** , everything works fine. Thanks again!

**Comment by jrobinso** [comment]
@wendazhoucs it might work on some browsers but if you want you application to work everywhere you need to add the file extension and not rely on package.json to resolve it for you.
