### ISSUE TITLE
install4j(-like?) installer and update notifications

### ISSUE THREAD

**Issue by brainstorm** [igvteam/igv#964]
Hello @igvteam,

I was wondering what's the position @igvteam about automated updates for newly released IGV versions? IIRC [Install4J](https://www.ej-technologies.com/products/install4j/overview.html) offers licenses for open source programs and projects like OpenPnP uses it on their CI/CD, i.e:

https://github.com/openpnp/openpnp/blob/develop/.github/workflows/build_and_deploy.yml#L47

Making the release and update notification process much easier for users. What's your opinion on this? Would you be open to implement/deploy such a system? It would greatly help in UX since curators are sometimes several versions behind and that causes confusion.

/cc @JoepVissers

**Comment by jrobinso** [comment]
We don't have the bandwidth to support that.   Of course individual organizations are free to deploy IGV in any way they see fit, including using an installer, however whatever means you use I would think you would want to freeze curators on a version until a deliberate choice is made to install a new one.     In any event we leave that decision to others.

**Comment by jrobinso** [comment]
I have added a startup message to inform users if there is a new version available.   If there are complaints I will add a preference to turn this off, you can check "skip this version",  which might be changed to "don't every bother me again".

**Comment by brainstorm** [comment]
Here's a possible solution that might work very well:

https://news.ycombinator.com/item?id=30340503
