### ISSUE TITLE
What does the presence/absence of black lines in IGV indicate?

### ISSUE THREAD

**Issue by TimD1** [igvteam/igv#966]
![Screenshot from 2021-05-20 10-27-38](https://user-images.githubusercontent.com/13918078/119022415-9c9ce080-b96e-11eb-8646-b397438191bd.png)
As you can see in this screenshot containing my BAM file in IGV, some deletions have black lines running through them, and others don't. What causes this? Short black lines also appear adjacent to some mutations and insertions.

I generated the CIGAR for the SAM file myself, and am wondering if I made an error. I didn't find anything in IGV's documentation about this. Is it some inconsistency between the CIGAR string and MD tag that is causing this? I ran `samtools calmd` directly prior to creating the index and viewing it...

**Comment by jrobinso** [comment]
The black lines indicate "D" blocks in the Cigar string.   The white space is separating different alignment records, those are not "deletions", unless there is something strange in the CIGAR string.  The MD tag isn't used by IGV.  The short black lines are strange, could you provide a SAM file with those?  

Also, please always provide the IGV version number.
