### ISSUE TITLE
Batch script screenshots：Wrong mutation depth

### ISSUE THREAD

**Issue by NancyChen-git** [igvteam/igv#967]
Hi，
    When I run a batch script ，I got some screenshots which has wrong mutation depth.
    For example:
   
![image](https://user-images.githubusercontent.com/59215031/119093650-8a8c7200-ba42-11eb-8a9e-1a8b29f33ce7.png)
   The correct screenshot should like
![image](https://user-images.githubusercontent.com/59215031/119094010-0686ba00-ba43-11eb-9c12-7dfeae80221f.png)
   
  The IGV version is 2.9.4

**Comment by jrobinso** [comment]
I'm sorry what are you referring too?  I don't understand the reference to depth.

**Comment by NancyChen-git** [comment]
I mean the coverage track show wrong variant allele frequency.

**Comment by jrobinso** [comment]
I can't reproduce this,  could you provide some sample data that exhibits the problem?
