### ISSUE TITLE
Track details popup window not usable in high contrast black theme on Windows

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#970]
[From an igv-help request.](https://groups.google.com/g/igv-help/c/ak6BfSf_6qE)

The details popup window for tracks has black text on a black background when using the high contrast - black theme on Windows 7, which makes it unusable.

![DetailsPopupProblem](https://user-images.githubusercontent.com/1265859/119206066-18c71f00-ba68-11eb-9d35-e9a7b4e2f697.PNG)

**Comment by jrobinso** [comment]
Should be fixed with commit d643581d
