### ISSUE TITLE
[Feature Request] Allow different base name for index file if selectable

### ISSUE THREAD

**Issue by tabbzi** [igvteam/igv#972]
Hi,

I realize that IGV requires the index file to reflect the base name of the bam (S.bam.bai or S.bai for S.bam) but seeing as the web implemented IGV apps on https://terra.bio and https://igv.org/app/ allow selection of the BAM and the index file... is there a reason the base name must conform?

(my use case is that I have weekly files coming off a platform as "S_alignment-**bam**.bam" and "S_alignment-**bai**.bam.bai" directly to a Terra workspace and would like to avoid renaming files if I can)

Thank you,
Kathleen

**Comment by jrobinso** [comment]
Those names are going to cause issues with many tools, not just IGV,  why not follow the ubiquitous naming convention to start with?   This is not likely to be changed in IGV,  it would overly complicate already complex logic for what is an esoteric use case.   You can multi-select bam files with the file chooser,  the base names are used to match index with bam.   This is also true with the web app (igv.org/app).
