### ISSUE TITLE
Snapshots are truncated at the bottom

### ISSUE THREAD

**Issue by ilya-kolpakov** [igvteam/igv#974]
### Description
I am using IGV 2.9.5 with the default configuration file and noticed that the images obtained via `snapshot` command (either from batch script or via the socket connection) do not capture the full window area.

Please compare the system screenshot (first image below) with the snapshot (second image below):
  - In the system screenshot the three alignment panels are nearly identical in height
  - In the snapshot the bottom alignment panel is clearly truncated vertically and is smaller than the other two
 
I am wondering if one can potentially overcome this issue? Thanks a lot for you help and your work on IGV in general.

### System Screenshot
![system-screenshot](https://user-images.githubusercontent.com/592849/119841814-6e874580-bf06-11eb-90b1-10d3c7d0598b.png)

### Snapshot
![batch-snapshot](https://user-images.githubusercontent.com/592849/119841912-8232ac00-bf06-11eb-87fe-086bf1166a2a.png)

### Notes
The truncation happens regardless of number of the panels. I see the same behavior even with one panel present. A session with three alignment panels was chosen for the illustration since it makes the truncation effect more apparent.

The snapshots generated using port (socket) connection and batch script were identical (same md5 hash) and hence only one was shown. The truncation is not due to my IGV configuration file (as I removed it prior to starting IGV) and also happens if one issues `maxPanelHeight -1` port command prior to requesting a snapshot.

**Comment by jrobinso** [comment]
Hi, that is an IGV bug that I think is fixed with commit 1ad0eaaf.   This has not been released, but you can access it through the "snapshot" build from the downloads page.  I anticipate releasing this in the next couple of weeks.

**Comment by ilya-kolpakov** [comment]
Fantastic, thank you very much. I confirm that the issue is fixed in the current snapshot build.
