### ISSUE TITLE
Batch script snapshot Coverage height not autoscaled

### ISSUE THREAD

**Issue by lucmarchandhsj** [igvteam/igv#975]
When I load a bam file manually the data range of the Coverage (height) is adjusted to the highest point of the sample (3811 in the picture below).  However, when it is done via a batch script, the range is 0 to 60 and you cannot see differences in coverage.  I could not find any parameters to change this at the batch script level.  Could you please point me to the parameters or implement it?

Wanted:
![igv_snapshot](https://user-images.githubusercontent.com/78432301/120486435-095aa680-c383-11eb-8cfa-33df250f440a.png)

Batch output:
![test2](https://user-images.githubusercontent.com/78432301/120486530-255e4800-c383-11eb-8049-158c77a3d732.png)

**Comment by jrobinso** [comment]
This is fixed but not yet released.  I anticipate a release by the end of the week, if you need it before then you can download the snapshot build.

**Comment by lucmarchandhsj** [comment]
I have downloaded 2.10 and it is indeed fixed.  I have another issue/request but to keep everything clean, I will create a new ticket.
