### ISSUE TITLE
https://data.broadinstitute.org certificate is invalid

### ISSUE THREAD

**Issue by crashGoBoom** [igvteam/igv#976]
Running  `wget https://data.broadinstitute.org/igv/projects/downloads/2.9/IGV_Linux_2.9.4_WithJava.zip` produces:
```
ERROR: cannot verify data.broadinstitute.org's certificate, issued by ‘/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Organization Validation Secure Server CA’:
  Unable to locally verify the issuer's authority.
ERROR: no certificate subject alternative name matches
        requested host name ‘data.broadinstitute.org’.
To connect to data.broadinstitute.org insecurely, use `--no-check-certificate'.
```

The cert appears to be for `data.igv.org`.

Of course using the recommended --no-check-certificate option works but is not ideal.

**Comment by jrobinso** [comment]
Yes we've filed a ticket at the Broad Institute who administers this.
Hopefully they will take care of it soon.

**Comment by jrobinso** [comment]
Should be working now

**Comment by crashGoBoom** [comment]
Yep tested and it is working as expected. Thanks for the quick reply!
