### ISSUE TITLE
mm39 update?

### ISSUE THREAD

**Issue by laurabchopp** [igvteam/igv#978]
Hi there, 

Will mm39 be added as a genome for the IGV desktop browser? 

Thanks,
Laura

**Comment by jrobinso** [comment]
Yes.   These are added on request, this is the first request.

**Comment by jrobinso** [comment]
mm39 is available now

**Comment by ericdanner** [comment]
I see that this was added. But when I look to load a genome I dont see mm39. I am using current Ubuntu and freshly installed IGV. Any thoughts?

![image](https://user-images.githubusercontent.com/10988149/172592549-760caaff-c3b0-40a9-bfa9-0c58644d2254.png)

**Comment by jrobinso** [comment]
Could you select "help about" and see what the IGV version is?   It should be 2.3.10.   Also, select "View > Preferences > Advanced" and check the "Genome Server URL".   It should be https://s3.amazonaws.com/igv.org.genomes/genomes.tsv
