### ISSUE TITLE
Snapshot image width issue

### ISSUE THREAD

**Issue by lucmarchandhsj** [igvteam/igv#980]
Hi.  I have used the 2.10 version of IGV to create headless snapshots via a batch script on a linux server (xvfb-run --auto-servernum igv.sh -b script.bat).  I do these images on the mitochondria genome (NC_012920) which is 16.5 Kb.  In the previous version, if I would use "goto NC_012920", it would produce a snapshot of the whole 16.5 Kb.  In the 2.10, it shows only 1 to 10000 (10 kb).  Setting goto NC_012920:1-16500 seems to corrects this issue.  The image however is more squished horizontally.  I have read somewhere to use the setting maxPanelHeight -1 to get the maximum width (not sure that it make sense) but it does not produce an image as wide and detailed as if I would run the same script on the GUI.  Is there a way to specify the width of the snapshot image in the batch file?

**Comment by lucmarchandhsj** [comment]
I realized that I should have given examples.  Here's the image with the linux headless batch script:
![snapGM201137-2](https://user-images.githubusercontent.com/78432301/121360553-86959680-c902-11eb-9086-a25f9198af14.png)
size: 640 x 391 pixels (~20 Kb)

Here's the image generated with the Windows GUI with the same batch script:
![snapGM201137-2gui](https://user-images.githubusercontent.com/78432301/121360857-c8264180-c902-11eb-85c1-9e7a2b778ee4.png)
size: 1134 x 670 pixels (~69 Kb)

The difference in height does not bother me but the greater width allows more gene names to be shown at the bottom.

**Comment by jrobinso** [comment]
Whatever the issue is its related to xfvb,  which I personally don't know anything about.    The snapshot width and height are taken from the actual size of the components on the screen,  or virtual screen in the case of xfvb.   There must be a setting to control display size.    I will leave this open to look into an explicit width setting, but in the meantime look for a setting for display size in xfvb,  it looks like the size is 640x480 in your example.

**Comment by lucmarchandhsj** [comment]
You are correct.  Using the command `xvfb-run -s \"-screen 0, 1920x1080x8\" --auto-servernum --server-num=1 /IGV_2.10.0/igv.sh -b IGVbatch.txt` 
The addition being -s "-screen 0, 1920x1080x8", increases the size of the image to 1150 x 711.  Why specifically those numbers (1150 instead 1920 and 711 instead of 1080), I don't know but it's definitely better then 640x480
