### ISSUE TITLE
Regarding Codon matching errors and the inability to automatically recognize the 3‘ and 5’-end when processed by script

### ISSUE THREAD

**Issue by YiZhao990209** [igvteam/igv#984]
1. Codon matching errors: It is often that a base match is misplaced, usually one base shifted back, which makes it necessary to look at the amino acid sideways to see whether they are correct. This is troublesome.
2. Inability to automatically recognize the 3'end and 5'end when processed by running batch script. The bases and amino acids do not match.

**Comment by jrobinso** [comment]
Hi, I don't actually understand either comment. Could you elaborate, perhaps with examples or screenshots?
