### ISSUE TITLE
Evaluate the option of adding T2T CHM13 v1.1 to genome list

### ISSUE THREAD

**Issue by SHuang-Broad** [igvteam/igv#986]
We see more and more people express interests in using the T2T CHM13 v1.1 as the reference, or at least giving that a try.

So I'm wondering if it makes sense to add it to the genome list, though it is still rapidly evolving and doesn't have chrY.

Thanks.
Steve

**Comment by jrobinso** [comment]
@SHuang-Broad I don't know anything about this to be honest, are there annotations available aligned to this assembly?

**Comment by SHuang-Broad** [comment]
There are some annotations, but not to the degree of GRCh38, as you can expect.

http://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v1.1/

http://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_2395475_t2t-chm13-v1.1&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr3%3A90755737%2D90789938&hgsid=1131189877_pobXHAH4SPeFWbWHGmUBrERKoTRi

**Comment by jrobinso** [comment]
@SHuang-Broad so no genes or other features, just GC% and a few other things.   I'm hesitant to add this now,  it could be a maintenance nightmare for me until its released.   anyone can experiment with it by just loading the fasta,  if you have a group that is interested they could host the fasta and its index and then it could be loaded "by url" from the Genomes menu (you load the fasta,  the .fai index is found by name convention).

**Comment by malcook** [comment]
FWIW, @SHuang-Broad  in case you don't already know, the [UCSC Genome Browser on CHM13 Homo sapiens T2T CHM13 \(v1\.1\) Assembly](http://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_2395475_t2t-chm13-v1.1&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr1%3A123%2D1234&hgsid=1250638069_611E6P53vgcHm0OkWNUjFXepAR9V)  now includes [UCSC Genome Browser on CHM13 Homo sapiens T2T CHM13 \(v1\.1\) Assembly](http://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_2395475_t2t-chm13-v1.1&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr1%3A123%2D1234&hgsid=1250638069_611E6P53vgcHm0OkWNUjFXepAR9V) which might profitably be considered source of gene track and can be visualized on T2T genome with "File > Load From URL" http://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v1.1/CAT_V4/CHM13.combined.v4.bb

**Comment by jrobinso** [comment]
@malcook How did you get to (find) this BB file.  Is there some documentation about what's in it?  I would be happy to host it with the fasta but I need to be able to explain what it is, and also provide a pointer for documentation / credit.

Also, if you know, what is the DB id for this assembly for UCSC blat purposes?

**Comment by maximilianh** [comment]
The T2T CHM13 genome that you link to is an assembly hub made by the T2T
group. Some members of this group are at UCSC, different from the genome
browser. There are no native IDs yet, it's a hub. This is because the
assembly lacks a chrY and gene models are somewhat preliminary.

Most databases (Ensembl, NCBI, UCSC) are currently waiting for T2T to
release their final version of the genome. At this point, the assembly will
get a GCF_ ID from NCBI. The final UCSC database identifier is not certain
yet, T2T wanted to help define that (chm13 or t2t were suggestions). If you
are already using this assembly now, I'm very curious, because I thought a
chrY would be a requirement for most use cases. Don't hesitate to contact
me or JimR directly if you don't want to discuss this here on Github (
***@***.***)

**Comment by malcook** [comment]
@jrobinso - I see that [CAT Gene + LiftOff Annotations V4](http://genome.ucsc.edu/cgi-bin/hgTrackUi?hgsid=1250638069_611E6P53vgcHm0OkWNUjFXepAR9V&db=hub_2395475_t2t-chm13-v1.1&c=chr1&g=hub_2395475_consensus_CHM13_V4) documents what's in the bb file, and clicking on "View Table Schema" provides an alternate link to it.

I have no personal stake or use case yet, but was led to find (and comment on) this issue as I learned some of my colleagues are preparing various preparations (blast dbs, STAR indices, etc) using CHM13 and I wanted to see what Jim et. al. were already doing with IGV.

I expect @maximilianh better addresses whether now is the time to reconsider this option.

**Comment by jrobinso** [comment]
OK, thanks for the update @maximilianh.   I'd rather not try to host this officially until UCSC does, but as a convenience you can use the following json to load the assembly with the hub-hosted annotations (bb file) using "Genome > Load from URL" pasting this in.  This will work for IGV desktop and web app.   Of course you can always load any fasta and annotation file directly.

```
https://s3.amazonaws.com/igv.org.genomes/t2t-chm13-v1.1/t2t-chm13-v1.1.json
```

**Comment by SHuang-Broad** [comment]
> FWIW, @SHuang-Broad in case you don't already know, the [UCSC Genome Browser on CHM13 Homo sapiens T2T CHM13 (v1.1) Assembly](http://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_2395475_t2t-chm13-v1.1&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr1%3A123%2D1234&hgsid=1250638069_611E6P53vgcHm0OkWNUjFXepAR9V) now includes [UCSC Genome Browser on CHM13 Homo sapiens T2T CHM13 (v1.1) Assembly](http://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_2395475_t2t-chm13-v1.1&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr1%3A123%2D1234&hgsid=1250638069_611E6P53vgcHm0OkWNUjFXepAR9V) which might profitably be considered source of gene track and can be visualized on T2T genome with "File > Load From URL" http://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v1.1/CAT_V4/CHM13.combined.v4.bb

Thanks @malcook !

**Comment by jrobinso** [comment]
BTW Blat with the default UCSC service will not work for this assembly as it is not a UCSC hosted DB yet, you will need to configure a custom blat for this.  That's easy now thanks to the API @maximilianh developed, see instructions here:  https://github.com/igvteam/igv/wiki/Customizing-BLAT

**Comment by maximilianh** [comment]
Hi Jim, I just looked at this assembly hub and it seems that someone is
already running BLAT servers for this and they're even on machines of the
department. See http://t2t.gi.ucsc.edu/chm13/hub/genomes.txt I don't know
how to specify these in IGV, but they're definitely in the hub files.

By the way: Do you have a converter for the UCSC <key><space><value> hub
text files to IGV jason files?

**Comment by jrobinso** [comment]
@maximilianh I don't have a converter but that could be useful.   I will look into it, but I probably could not cover all the options possible in hub files.  However it seems most people do fairly simple hubs.

**Comment by jrobinso** [comment]
I'm not sure why this was closed. reopening

**Comment by jrobinso** [comment]
Hi all, chm13v1.1 is now in IGV's genome list, data is from the UCSC track hub http://t2t.gi.ucsc.edu/chm13/hub/genomes.txt

@maximilianh I see there is a hub for 2.0, but I can't seem to guess the URL to the track hub description from the browser URL.  Do you have a pointer?  It is clearly not from http://t2t.gi.ucsc.edu/chm13/hub/genomes.txt

https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3267197_GCA_009914755.4&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=CP068277.2%3A82795776%2D82805776&hgsid=1318685057_Ve4o2MeyJnudNcT6ZhtwRmLsbX62

**Comment by maximilianh** [comment]
And on UCSC https://genome.ucsc.edu/h/GCA_009914755.4

**Comment by jrobinso** [comment]
@SHuang-Broad  Yes I already have the fasta indexed from the link you provided, but would like annotations before hosting it.   @maximilianh I found the UCSC browser page, it looks great, but cannot figure out where to find the track hub file ("genomes.txt").

**Comment by jrobinso** [comment]
Found it, I think. https://hgdownload.soe.ucsc.edu/hubs/GCA/009/914/755/GCA_009914755.4/trackDb.txt

**Comment by jrobinso** [comment]
OK CHM13 v1.1 and v2.0 are now in the genome lists for IGV desktop and igv-webapp (as well is igv.js).    There are some slight problems for both with the bigGenePred format, which is new to IGV, its treated as a plain bigBed.  What this means for IGV is no protein translation as its not picking up the exon frameshifts.   For igv.js / igv-webapp its not distinguishing the UTR from coding sections.    I have both on my bug list, but this is really indpendent of CHM13 specifcally.

Here's an igv-webapp session with some random tracks.   Its based on the track hub referenced by @maximilianh .  I parsed the hub text to populate the "tracks" menu.   https://tinyurl.com/y8935qcf

The IGV desktop "Load from server..." menu is still to do, but will include the same tracks and webapp.

**Comment by maximilianh** [comment]
Hi JIm, sorry for the delay, was offline, Yes,
https://hgdownload.soe.ucsc.edu/hubs/GCA/009/914/755/GCA_009914755.4/trackDb.txt
is the URL, we make every effort to keep it stable and the same URL scheme
should work for most NCBI assemblies, and where it doesn't work, you can
request the genome to be added and soon we'll have a webform for requesting
a genome. (hmm...maybe we should have an API...?)

**Comment by jrobinso** [comment]
Thanks @maximilianh .   I've been able to parse that and convert it to igv.js "json", as well as IGV desktop "xml",  automatically for the most part.   Some hand manipulation is still required, I will work towards eliminating that.

**Comment by jrobinso** [comment]
@maximilianh re stability, it looks like several bbi files were renamed over the weekend or this morning, which breaks IGV.  I am parsing the hub files once and conerting to json for igv, not in real time.   Should I copy all the data as well?   I am guessing this does not happen often, maybe a transient problem as chm13 is new.

**Comment by jrobinso** [comment]
@maximilianh No problem I know its early and pre-release.   The best solution would be for IGV to parse the hubs.txt dynamically,  I will get there eventually.

**Comment by maximilianh** [comment]
Also, we'll try to not use the NCBI name anymore, just the accession alone.
