### ISSUE TITLE
Unable to visualize bigwig file

### ISSUE THREAD

**Issue by SB431542** [igvteam/igv#987]
Hello! I have been trying to visualize bigwig files into IGV_2.10.0, however strange tabs keep appearing at the side of my chromosome, and I cannot open the bigwig file. I will really appreciate your advice, thank you!

**Comment by SB431542** [comment]
![IGV bigwig error](https://user-images.githubusercontent.com/86413808/123263142-3be36380-d52b-11eb-8cdd-a42daa4349c5.jpg)
My apologies, I forgot to upload a photo of my error. Here it is!

**Comment by helgathorv** [comment]
@SB431542  It looks like IGV does not recognize your file as a bigwig file. Note that the name of the file is important - make sure that the file name suffix is .bw or .bigwig
