### ISSUE TITLE
 IGV session loading with error when session includes track generated by "Search Motif" menu item and saved in session

### ISSUE THREAD

**Issue by namra1** [igvteam/igv#988]
On Wednesday, June 23, 2021 at 10:36:18 AM UTC-4 nasi...@gmail.com wrote:
When loading a saved IGV session, I get the following error:
      "  Unexpected error: java.lang.NullPointerException.
See igv.log for more details     ".

The igv.log is attached as well as the session xml.
It seems to be related to  tracks in xml file such as this track:
        <Track attributeKey="EML4-GACTCAGGTGGAGTCATGCT" clazz="org.broad.igv.track.FeatureTrack" displayMode="SQUISHED" featureVisibilityWindow="10000000" fontSize="10" groupByStrand="false" id="EML4-GACTCAGGTGGAGTCATGCT" name="EML4_RNA_63_F_Minion" visible="true"/>

Note that I had to change .xml extension to _xml.txt since GitHub does not support .xml attachments.

[igv.log](https://github.com/igvteam/igv/files/6710151/igv.log)

[Fusion_gene_primers-igv_session copy_xml.txt](https://github.com/igvteam/igv/files/6710099/Fusion_gene_primers-igv_session.copy_xml.txt)

**Comment by jrobinso** [comment]
I can reproduce the problem.   Apparently no on has ever tried this (saving session with motifs), or hasn't in a very long time.  Working on a solution.

**Comment by jrobinso** [comment]
I have pushed a fix, it will be available in the next release scheduled for the week of July 12.   If you need it in the meantime you can try the development snapshot build (follow link from downloads page).

Unfortunately the fix requires a change to the XML, if you want to convert existing session files 2 changes are required

1.  Change the "classz" attribute from **org.broad.igv.track.FeatureTrack**. to **org.broad.igv.track.MotifTrack**
2. add **pattern** and **strand** attributes to the track element.   

An example follows

```
        <Track attributeKey="tata" clazz="org.broad.igv.track.MotifTrack" displayMode="SQUISHED" featureVisibilityWindow="10000000" fontSize="10" groupByStrand="false" id="tata" name="tata" pattern="TATA" strand="POSITIVE" visible="true"/>
        <Track attributeKey="tata Negative" clazz="org.broad.igv.track.MotifTrack" color="255,0,0" displayMode="SQUISHED" featureVisibilityWindow="10000000" fontSize="10" groupByStrand="false" id="tata Negative" name="tata Negative" pattern="TATA" strand="NEGATIVE" visible="true"/>
```
