### ISSUE TITLE
IGV feature request: view the BAM/SAM file like watching a running river 

### ISSUE THREAD

**Issue by jielab** [igvteam/igv#996]
Dear James:

I posted the following message previously. I am glad that you agree this is a cool feature. Now I am submitting a ticket here for requesting this feature. It would be great if this could be put on the priority list someday soon. 

These days, large structural variation is still very difficult to be called. And there are many different algorithm. I think, graph-based approach might work better. It will certainly "looks" better and easier to interpret.  Imagine that IGV could display part of a genome like a ECG, shown as below. That would put IGV a big step closer to non-technicians.

![11](https://user-images.githubusercontent.com/26947455/124556419-d49eab00-de6a-11eb-9440-f1dd1631c2d0.gif)

Best regards,
Jie

=========================================================================

Hi, there:

I know that I could use external commands such as "goto chr1:65,289,335-67,427,933" to go to a specific locus. 

However, is there a way to set IGV window to scoll automatically at a certain speed and window size, just like the taxi driver prints out the receipt, or a Doctor's physical exam machine displays an ECG graph?

Then I only need to look at the screen, to scan throuhg a long region of the genome, without the need to click and drag. That would be very cool.

Best regards,
Jie

**Comment by jrobinso** [comment]
That looks cool but I don't know when this will get prioritized, as you can see there are 60 open issues currently.  Have you tried just holding the left or right key down?

**Comment by jielab** [comment]
Dear james:

holding the left or right key, did move the region, but it is going too fast...

Is there a way to use command to simulate this function of holding the key, at a certain speed?

Best regards,
jie

**Comment by jrobinso** [comment]
@jielab Try "Home" and "End" keys, each press will move a page.   On a Mac these keys map to "Fn left arrow", "Fn right arrow"

**Comment by jrobinso** [comment]
This is a nice idea, but upon investigation would be too complex to implement.  I think "Home" and "End" keys should achieve most of what you want.
