### ISSUE TITLE
ArrayIndexOutOfBoundsException when view UltraLong ONT read alignments

### ISSUE THREAD

**Issue by talioto** [igvteam/igv#999]
a ArrayIndexOutOfBoundsException error is thrown when browsing UL nanopore data. It happens when zooming out or moving around. 

This happens with two new datasets from ONT:
- https://labs.epi2me.io/gm24385_2021.05/
- https://labs.epi2me.io/cliveome_2010.05/

The BAMs are those provided with the datasets. The only operations performed were to subset the reads to particular chromosomes for loading on a local machine. We get this error with IGV 2.10.0 on both Windows and Mac.

I suspect it has to do with visualizing certain reads. Is there a maximum read or alignment length to take into consideration. I removed reads over 1Mbp but the problem remains. 

<img width="1151" alt="Screenshot 2021-07-10 at 11 25 15" src="https://user-images.githubusercontent.com/1167665/125158663-be4a6500-e172-11eb-8a55-e02603dc0da1.png">

**Comment by jrobinso** [comment]
Could you please attach your igv.log file, located in the "igv" folder under your home directory.   Also, the subsetted bam file and steps to reproduce would be helpful.

**Comment by watanabe-satoshi** [comment]
Someone more experienced could jump on that, but my guess would be to try add "Filter secondary alignments" and "Filter supplementary alignments" options on Alignments tab in Preferences window.

**Comment by jrobinso** [comment]
Note to self.  Possible URL for bam  https://ont-open-data.s3.eu-west-1.amazonaws.com/gm24385_2020.09/analysis/r10.3/20200914_1356_6F_PAF26223_da14221a/guppy_v4.0.11_r10.3_hac_prom/align_unfiltered/chr6/calls2ref.bam

**Comment by jrobinso** [comment]
@talioto I tried to reproduce this with the URL above, without success.   I need the log and steps to reproduce to investigate further.

**Comment by jrobinso** [comment]
Closing due to lack of response.  Re-open with explicit steps to reproduce with the latest IGV release, and attach the igv.log file, if the problem persists.
